### ISSUE TITLE
[Mod]: Celestial Harmony

### ISSUE THREAD

**Issue by ProximaCentauri-star** [KSP-CKAN/NetKAN#10024]
### Mod Name

Celestial Harmony

### Author(s)

ProximaCentauri-star

### License

All Rights Reserved

### Homepage link

https://github.com/ProximaCentauri-star/Celestial-Harmony

### Download link

https://github.com/ProximaCentauri-star/Celestial-Harmony/releases/

**Comment by HebaruSan** [comment]
Hi @ProximaCentauri-star, thanks for the submission. I had a follow-up question so we can make sure this is added correctly:

I noticed that [your `README.md`](https://github.com/ProximaCentauri-star/Celestial-Harmony/blob/main/README.md) specifies a dependency on "[Kopernicus fork from Ballisticfox](https://github.com/Kopernicus/Kopernicus/releases) (extract with winRAR or 7zip)",  but the link provided is just to the normal Kopernicus releases at <https://github.com/Kopernicus/Kopernicus>. Does your mod actually need a special version of Kopernicus?

**Comment by ProximaCentauri-star** [comment]
> Hi @ProximaCentauri-star, thanks for the submission. I had a follow-up question so we can make sure this is added correctly:
> 
> I noticed that [your `README.md`](https://github.com/ProximaCentauri-star/Celestial-Harmony/blob/main/README.md) specifies a dependency on "[Kopernicus fork from Ballisticfox](https://github.com/Kopernicus/Kopernicus/releases) (extract with winRAR or 7zip)", but the link provided is just to the normal Kopernicus releases at https://github.com/Kopernicus/Kopernicus. Does your mod actually need a special version of Kopernicus?

Hi, just fixed the link.
I linked this fork because the latest version of kopernicus seems to not work at all.

**Comment by HebaruSan** [comment]
OK, thanks.

That version of Kopernicus isn't on CKAN, so we won't be able to add mods that require it. Please let us know if that changes.

Cheers!

**Comment by ProximaCentauri-star** [comment]
> OK, thanks.
> 
> That version of Kopernicus isn't on CKAN, so we won't be able to add mods that require it. Please let us know if that changes.
> 
> Cheers!

I will notify you whenever this gets fixed. Thank you.

Have a good one !

**Comment by HebaruSan** [comment]
Hi @ProximaCentauri-star, I checked with @R-T-B (Kopernicus maintainer), and he says your mod works for him with the regular fork of Kopernicus. He suggested that you were probably seeing a bug in `VertexHeightOblateAdvanced` that was fixed a few days ago. You might want to update that mod and test again.

**Comment by ProximaCentauri-star** [comment]
> Hi @ProximaCentauri-star, I checked with @R-T-B (Kopernicus maintainer), and he says your mod works for him with the regular fork of Kopernicus. He suggested that you were probably seeing a bug in `VertexHeightOblateAdvanced` that was fixed a few days ago. You might want to update that mod and test again.

Hi again! You are right, updated `VertexHeightOblateAdvanced` and it is now working fine with the regular fork of Kopernicus, thank you for the help. I updated the README.md

**Comment by HebaruSan** [comment]
Hi @ProximaCentauri-star, CKAN's bot has noticed that there are now two assets attached to the latest release:

![Image](https://github.com/user-attachments/assets/e4486a39-e7e5-41b1-8ad6-a66ae8f0f2be)

![Image](https://github.com/user-attachments/assets/29589ad6-5f36-4b0f-a0c2-242e400758b5)

As a default, it has chosen to use the first one in the list, `_Chaos.zip`. Is this correct? If not, we can change to look for some specific string in the filename, let us know!
