### ISSUE TITLE
[Bug]: Error during instalation

### ISSUE THREAD

**Issue by GitElias404** [KSP-CKAN/NetKAN#10023]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Operating System

windows 10 64 Bit

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

I had alot of mods but wanted to use CKAN instead so i deleted all of them and then i downloaded them via CKAN

### Describe the bug

Last 8 rows beforte error 

Installing KSPBurst v1.5.5.1...
Successfully installed KSPBurst v1.5.5.1
Installing ModularFlightIntegrator 1.2.10.0...
Could not find a part of the path 'C:\Users\elias\Desktop\1.12.5\Kerbal Space Program\GameData\ModularFlightIntegrator\ModularFlightIntegrator.dll'.
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose

### Steps to reproduce

Go ahead and instal a few mods that dont apear to be conflicting. inluding EVE, Scaterer, Multipayer mods
Download them 
Error

### Relevant log output

RSSVE-LR 2.1.6 conflicts with EnvironmentalVisualEnhancements-HR 2:EVE-1.2.2-1; EnvironmentalVisualEnhancements-HR 2:EVE-1.2.2-1 conflicts with RSSVE-LR 2.1.6; RSSVE-LR 2.1.6 conflicts with EnvironmentalVisualEnhancements-HR 2:EVE-1.2.2-1; EnvironmentalVisualEnhancements-HR 2:EVE-1.2.2-1 conflicts with RSSVE-LR 2.1.6; RSSVE-LR 2.1.6 conflicts with EnvironmentalVisualEnhancements-HR 2:EVE-1.2.2-1; EnvironmentalVisualEnhancements-HR 2:EVE-1.2.2-1 conflicts with RSSVE-LR 2.1.6

About to install:

 * Harmony 2 2.2.1.0 (cached)
 * ClickThrough Blocker 1:2.1.10.21 (cached)
 * Toolbar Controller 1:0.1.9.11 (cached)
 * KSP Community Fixes 1.35.2 (cached)
 * TweakScale Redistributable v2.4.8.3 (cached)
 * Ferram Aerospace Research Continued 3:0.16.1.2 (cached)
 * Community Resource Pack v112.0.1 (cached)
 * Kerbal Changelog v1.4.2 (cached)
 * Solver Engines plugin v3.14.0 (cached)
 * Advanced Jet Engine v2.20.0 (cached)
 * Kerbal Joint Reinforcement Continued v3.7.4.0 (cached)
 * RealChute Parachute Systems v1.4.9.1 (cached)
 * RealHeat v5.1 (cached)
 * ROUtils v1.0.1.0 (cached)
 * SmokeScreen - Extended FX Plugin 2.8.14.0 (cached)
 * Real Fuels 1:v15.8.4.0 (cached)
 * Real Plume 2:v13.3.2 (cached)
 * Realism Overhaul v17.9.0.0 (cached)
 * Background Resources 1:v0.18.0.0 (cached)
 * Custom Pre Launch Checks 1.8.1.1 (cached)
 * Environmental Visual Enhancements Redux 3:1.11.7.1 (cached)
 * KSP Recall v0.5.0.2 (cached)
 * Luna Multiplayer Client 0.29.0 (cached)
 * Scatterer Default Config 3:v0.0838 (cached)
 * Textures Unlimited 1.5.10.25 (cached)
 * Module Manager 4.2.3 (cached)
 * KSPBurst v1.5.5.1 (cached)
 * ModularFlightIntegrator 1.2.10.0 (cached)
 * Chatterer 0.9.99 (cached)
 * HUD Replacer 1.2.11-beta (cached)
 * Real Solar System Textures - 4096 x 2048 v18.6.1 (cached)
 * Scatterer Sunflare 3:v0.0838 (cached)
 * Advanced Fly-By-Wire (Windows) 1.8.4.1 (cached)
 * B9 Aerospace Procedural Wings - Fork 3:0.45.1 (cached)
 * BDA Multiplayer 0.5 (cached)
 * Chatterer Extended 0.6.2 (cached)
 * Distant skies 0.7 (cached)
 * Dock Rotate v1.12.1.56 (cached)
 * EVA Enhancements Continued 0.1.15.3 (cached)
 * EVA Handrails Continued 0.3.0.3 (cached)
 * EVA Parachutes & Ejection Seats 0.2.0.3 (cached)
 * EVE - Stock Planet Configs 2:EVE-1.2.2-1 (cached)
 * Fly By Wire SAS Mode 1.2.0 (cached)
 * Hangar Extender 3.6.0.2 (cached)
 * Kerbal Engineer Redux 1.1.9.0 (cached)
 * Kerbal Konstructs v1.8.6.1 (cached)
 * Kerbal Wind 1:v1.0.2 (cached)
 * KSC Switcher v2.1.0.0 (cached)
 * KSP AVC 1.4.1.9 (cached)
 * MechJeb 2 2.14.3.0 (cached)
 * Mk 33 v1.3.2 (cached)
 * Procedural Fairings 1:v6.5.0.0 (cached)
 * Procedural Parts v2.5.8.0 (cached)
 * RCS Build Aid v1.0.6 (cached)
 * Real Antennas v2.1.1 (cached)
 * Real Solar System v20.1.2.0 (cached)
 * ROLoadingImages v1.0.0.0 (cached)
 * Scatterer 3:v0.0838 (cached)
 * Surestrut Engines 0.3 (cached)
 * Sushut's Main Menu Mod 1 (cached)
 * TAC Life Support (TACLS) 1:v0.18.0.0 (cached)
 * Toolbar 1:1.8.1.1 (cached)
 * TweakScale - Rescale Everything! v2.4.8.3 (cached)
 * Waterfall Core 0.9.0 (cached)
 * ZTheme v1.1.3 (cached)
Installing Harmony2 2.2.1.0...
Successfully installed Harmony2 2.2.1.0
Installing ClickThroughBlocker 1:2.1.10.21...
Successfully installed ClickThroughBlocker 1:2.1.10.21
Installing ToolbarController 1:0.1.9.11...
Successfully installed ToolbarController 1:0.1.9.11
Installing KSPCommunityFixes 1.35.2...
Successfully installed KSPCommunityFixes 1.35.2
Installing TweakScale-Redist v2.4.8.3...
Successfully installed TweakScale-Redist v2.4.8.3
Installing FerramAerospaceResearchContinued 3:0.16.1.2...
Successfully installed FerramAerospaceResearchContinued 3:0.16.1.2
Installing CommunityResourcePack v112.0.1...
Successfully installed CommunityResourcePack v112.0.1
Installing KerbalChangelog v1.4.2...
Successfully installed KerbalChangelog v1.4.2
Installing SolverEngines v3.14.0...
Successfully installed SolverEngines v3.14.0
Installing AdvancedJetEngine v2.20.0...
Successfully installed AdvancedJetEngine v2.20.0
Installing KerbalJointReinforcementContinued v3.7.4.0...
Successfully installed KerbalJointReinforcementContinued v3.7.4.0
Installing RealChute v1.4.9.1...
Successfully installed RealChute v1.4.9.1
Installing RealHeat v5.1...
Successfully installed RealHeat v5.1
Installing ROUtils v1.0.1.0...
Successfully installed ROUtils v1.0.1.0
Installing SmokeScreen 2.8.14.0...
Successfully installed SmokeScreen 2.8.14.0
Installing RealFuels 1:v15.8.4.0...
Successfully installed RealFuels 1:v15.8.4.0
Installing RealPlume 2:v13.3.2...
Successfully installed RealPlume 2:v13.3.2
Installing RealismOverhaul v17.9.0.0...
Successfully installed RealismOverhaul v17.9.0.0
Installing BackgroundResources 1:v0.18.0.0...
Successfully installed BackgroundResources 1:v0.18.0.0
Installing CustomPreLaunchChecks 1.8.1.1...
Successfully installed CustomPreLaunchChecks 1.8.1.1
Installing EnvironmentalVisualEnhancements 3:1.11.7.1...
Successfully installed EnvironmentalVisualEnhancements 3:1.11.7.1
Installing KSP-Recall v0.5.0.2...
Successfully installed KSP-Recall v0.5.0.2
Installing LunaMultiplayer 0.29.0...
Successfully installed LunaMultiplayer 0.29.0
Installing Scatterer-config 3:v0.0838...
Successfully installed Scatterer-config 3:v0.0838
Installing TexturesUnlimited 1.5.10.25...
Successfully installed TexturesUnlimited 1.5.10.25
Installing ModuleManager 4.2.3...
Successfully installed ModuleManager 4.2.3
Installing KSPBurst v1.5.5.1...
Successfully installed KSPBurst v1.5.5.1
Installing ModularFlightIntegrator 1.2.10.0...
Could not find a part of the path 'C:\Users\elias\Desktop\1.12.5\Kerbal Space Program\GameData\ModularFlightIntegrator\ModularFlightIntegrator.dll'.
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose

**Comment by GitElias404** [comment]
Fixed it, but now the loading screen is black. and and nothing has happened for more then 15 min

**Comment by JonnyOThan** [comment]
> Fixed it, but now the loading screen is black. and and nothing has happened for more then 15 min

A common cause of this issue is deleting your Squad folder from GameData. Did you do that by mistake?

**Comment by GitElias404** [comment]
No. here is a picture of my game data to make it easier for you to troubleshoot this
![image](https://github.com/KSP-CKAN/NetKAN/assets/163042785/73a341de-4aa0-4a57-9164-539a83a19275)

**Comment by HebaruSan** [comment]
This path:

> `Could not find a part of the path 'C:\Users\elias\Desktop\1.12.5\Kerbal Space Program\GameData\ModularFlightIntegrator\ModularFlightIntegrator.dll'.`

Does not match the screenshot:

![image](https://github.com/KSP-CKAN/NetKAN/assets/1559108/70c49c99-e4fc-4a43-8c9f-7233d6233f4a)

In the error, there is a `Kerbal Space Program` folder under `1.12.5`, and in the screenshot, it's missing.

@GitElias404, I think you added the instance to CKAN and then moved the folder so it's now in a different path. You'll have to re-add it at the new location.

<https://github.com/KSP-CKAN/CKAN/wiki/User-guide#adding-game-folders>

**Comment by GitElias404** [comment]
![image](https://github.com/KSP-CKAN/NetKAN/assets/163042785/bebd0521-df61-4076-8a88-f4e62fbc7286)
That is where it is. Right?

**Comment by GitElias404** [comment]
Atleast does not seem like it is the wrong directory
![image](https://github.com/KSP-CKAN/NetKAN/assets/163042785/0d5c3c52-19e2-46b1-a798-d2d1c66fc136)
![image](https://github.com/KSP-CKAN/NetKAN/assets/163042785/aca3a73b-e1df-403d-b533-a2eab30ebb0f)
![image](https://github.com/KSP-CKAN/NetKAN/assets/163042785/9b1688bb-e698-4b49-b398-49be956c22fa)
![image](https://github.com/KSP-CKAN/NetKAN/assets/163042785/90bf385f-4d7c-4e61-af9f-06d6435373dc)

I also added a sequence of pictures to try to make it easier

**Comment by GitElias404** [comment]
I still don't have access to my KSP
