### ISSUE TITLE
RSMP (Formerly SRBWE, SWE) links to deleted github/spacedock pages.

### ISSUE THREAD

**Issue by AdiriKSP** [KSP-CKAN/NetKAN#10038]
Mod: https://forum.kerbalspaceprogram.com/topic/207196-112x-rsmp-formally-swe/

Correct github page: https://github.com/dangaffa/RSMP

Github/Spacedock that CKAN links to:
https://spacedock.info/mod/2992/RSMP - Remastered Solid Plume Effects [ALL OLD RELEASES OUTDATED!!!]
https://github.com/AdiriKSP/RSMP

I didn't feel like setting up a new spacedock mod page, hope that doesn't cause any issues.

**Comment by HebaruSan** [comment]
Hey @AdiriKSP, what is the name of the mod? From the alphabet soup in the title I thought StockWaterfallEffects, but that seems to have a completely different set of links.

**Comment by AdiriKSP** [comment]
RSMP is the current name. CKAN has it indexed under a current name which is why I included it. My bad.

**Comment by HebaruSan** [comment]
But what's the _name_, not acronym. We need to be able to find it.

**Comment by AdiriKSP** [comment]
The name CKAN has indexed?

**Comment by HebaruSan** [comment]
Any clue would help, really.

**Comment by AdiriKSP** [comment]
Sorry, the project has gone through a lot of name changes. CKAN should have it indexed under either SRB Waterfall Effects, RSMP, or SRBWE. RSMP is just the name, not an acronym.

**Comment by HebaruSan** [comment]
>  SRB Waterfall Effects

Ahh, that's the one! Perfect, thanks.

**Comment by AdiriKSP** [comment]
Yeah, my bad. Thanks a lot

**Comment by HebaruSan** [comment]
Hey @AdiriKSP, that repo seems to have no releases, so we can't use it. Is that the only source?

**Comment by AdiriKSP** [comment]
I'm asking the owner of the repo to make a release right now. If they cannot I can make a new repo.

**Comment by HebaruSan** [comment]
OK, let us know if that gets straightened out, and we can re-open this.

**Comment by AdiriKSP** [comment]
Release has been made
https://github.com/dangaffa/RSMP/releases/tag/mainrevs

**Comment by HebaruSan** [comment]
Are you sure about `mainrevs` as a version number? That looks pretty weird, and doesn't easily lend it self to predecessor or successor versions.

**Comment by AdiriKSP** [comment]
That is more than likely the final release of this mod ever.

**Comment by AdiriKSP** [comment]
And if it isn't I suppose it can be changed later.

**Comment by HebaruSan** [comment]
> And if it isn't I suppose it can be changed later.

Not really. If it needs to be changed, that should happen now, before it gets added to CKAN. That's why I asked about it.

**Comment by AdiriKSP** [comment]
Numbered release added

**Comment by HebaruSan** [comment]
The previous release was `0.4`. Any chance you could make this easy for everyone else and pick something larger than that instead of `0.0.1` ?

**Comment by AdiriKSP** [comment]
roger, 4.0.1 is the new number

**Comment by HebaruSan** [comment]
Uhh, negatory, the version number is not changed. This is where it comes from:
![image](https://github.com/KSP-CKAN/NetKAN/assets/1559108/8fe97382-bc85-4a0b-bdd2-d97916fd08af)

**Comment by AdiriKSP** [comment]
Should be fixed

**Comment by HebaruSan** [comment]
OK, those changes should be on their way to CKAN users now. Thanks for letting us know!
