### ISSUE TITLE
[Bug]: JNSQ-KSRGAP recommends the wrong version of NavUtilities

### ISSUE THREAD

**Issue by nagleaidan** [KSP-CKAN/NetKAN#10035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

1.12.4.3187

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No

### Describe the bug

`JNSQ-KSRGAP` netkan recommends `NavUtilitiesContinued`. This has been deprecated in favor of LGG's new version `NavUtilitiesUpdated`. The mod author for `JNSQ-KSRGAP` is aware of this change (see [forum comment](https://forum.kerbalspaceprogram.com/topic/202138-jnsq-ksrgap-flight-contracts-for-trans-kerbin-airlines-under-a-bigger-sky/?do=findComment&comment=4035486))

Desired change: update the netkan to point to the updated version of the mod

### Steps to reproduce

- Search `JNSQ-KSRGAP`
- Click Relationships

**Comment by nagleaidan** [comment]
Thanks Hebaru!

**Comment by HebaruSan** [comment]
You're welcome, thanks for letting us know about this!
