### ISSUE TITLE
Latest Parallax stock textures ZIP uses unsupported Deflate64 compression method

### ISSUE THREAD

**Issue by nagleaidan** [KSP-CKAN/NetKAN#10071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

1.12.4.3187

### Describe the bug

![image](https://github.com/KSP-CKAN/NetKAN/assets/15807611/2d170209-5b46-4047-a66c-adf2acb3d5d0)
Linx recently released an update to Parallax to add compatibility for Deferred. CKAN picked up the update to the main app but hasn't pushed it for all the dependencies. As you can see in the picture, CKAN isn't detecting an update to Parallax - Stock Planet Textures but on [GitHub](https://github.com/Gameslinx/Tessellation/releases), there is a 2.0.7 version available. Also confirmed with Linx that it is needed:
![image](https://github.com/KSP-CKAN/NetKAN/assets/15807611/d7e74592-3aeb-47fc-aa9e-6ba935f3895b)

### Steps to reproduce

1. Open CKAN
2. Search Parallax
3. Look at the Latest Version numbers

**Comment by HebaruSan** [comment]
Looks like the stock textures ZIP is doing something weird (our library is telling us "compression method not supported").

<http://status.ksp-ckan.space/>

![image](https://github.com/KSP-CKAN/NetKAN/assets/1559108/3896797a-4947-4a25-806e-e6d78642b873)

I'll take a look and bug @Gameslinx with details...

**Comment by HebaruSan** [comment]
Looks like two of the contained files are using Deflate64, which we saw once before in #9319.

**Comment by HebaruSan** [comment]
Thanks to @Gameslinx for fixing the ZIP.

https://github.com/KSP-CKAN/CKAN-meta/commit/feeb94b603f442b47465c5a861646d437f84380a
