### ISSUE TITLE
[Mod]: "Simple Cargo Solutions"

### ISSUE THREAD

**Issue by TheHighestFleet** [KSP-CKAN/NetKAN#10072]
### Mod Name

Simple Cargo Solutions

### Author(s)

zer0Kerbal

### License

GPL-2.0

### Homepage link

https://github.com/zer0Kerbal/SimpleCargoSolutions/?tab=readme-ov-file

### Download link

https://github.com/zer0Kerbal/SimpleCargoSolutions/releases

**Comment by JonnyOThan** [comment]
Reopening #9397
