### ISSUE TITLE
[Mod]: Add the latest update for Pathfinder

### ISSUE THREAD

**Issue by feralfenrir** [KSP-CKAN/NetKAN#10089]
### Mod Name

Pathfinder

### Author(s)

Angel125

### License

GPL-3.0

### Homepage link

https://forum.kerbalspaceprogram.com/index.php?/topic/121397-*

### Download link

https://github.com/Angel-125/Pathfinder/releases/tag/v1.41.0

**Comment by HebaruSan** [comment]
Thanks, we know, it'll happen once the PRs get reviewed (see https://github.com/KSP-CKAN/CKAN-meta/pulls).
