### ISSUE TITLE
[Mod]: Add the latest update for WildBlueTools

### ISSUE THREAD

**Issue by feralfenrir** [KSP-CKAN/NetKAN#10088]
### Mod Name

WildBlueTools

### Author(s)

Angel125

### License

GPL-3.0

### Homepage link

https://github.com/Angel-125/WildBlueTools

### Download link

https://github.com/Angel-125/WildBlueTools/releases/tag/v1.90.3

**Comment by HebaruSan** [comment]
Thanks, we know, it'll happen once the PRs get reviewed (see https://github.com/KSP-CKAN/CKAN-meta/pulls).
