### ISSUE TITLE
Some frozen netkans use replaced-by instead of replaced_by

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/NetKAN#10109]
https://github.com/search?q=repo%3AKSP-CKAN%2FNetKAN+replaced-by&type=code

The spec erroneously used `replaced-by` in the section header, and apparently several of these netkans use it.

Should we have a warning about fields in netkans that aren't recognized and don't start with `x_` ?

Should we proactively clean these up?

**Comment by HebaruSan** [comment]
Looks like those are all from one PR where this was missed, #7100.

**Comment by JonnyOThan** [comment]
righto...so...probably not really worth fixing unless they get unfrozen? I dunno.

**Comment by HebaruSan** [comment]
I think the history of those mods makes unfreezing very unlikely, but

- there's a chance someone would do a text search and emulate these
- we might want to actually apply `replaced_by` properly in CKAN-meta
