### ISSUE TITLE
[Mod]: Recolour Collection: Near Future Propulsion

### ISSUE THREAD

**Issue by ZZetho** [KSP-CKAN/NetKAN#10120]
### Mod Name

Recolour Collection: Near Future Propulsion

### Author(s)

ZZetho

### License

CC BY-NC-SA 4.0

### Homepage link

https://forum.kerbalspaceprogram.com/topic/225485-112x-recolour-collection

### Download link

https://github.com/ZZetho/TU_NeafFuturePropulsion

**Comment by JonnyOThan** [comment]
Hey @zzetho, would you like us to add all of those recolor packs?  No need to create requests for each one if so.

**Comment by ZZetho** [comment]
Yes please

**Comment by HebaruSan** [comment]
Hey @ZZetho, your repo's name is TU_Nea***f***FuturePropulsion. Might want to fix that before we start adding external references to it.

**Comment by ZZetho** [comment]
> Hey @ZZetho, your repo's name is TU_Nea_**f**_FuturePropulsion. Might want to fix that before we start adding external references to it.

Whoops, renamed.
