### ISSUE TITLE
Add RSSOrigin-TopoRevamp

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/NetKAN#10140]
https://github.com/CharonSSS/RSS-Origin

> Okay hey @JonnyOThan , everything is uploaded

I want to add these 4 to ckan:
![image](https://github.com/user-attachments/assets/821a59f7-80d4-4a6c-9a07-b1b28ea5394b)

Their names and titles should be:
- RSSOriginRSSTextureTopoRevampConfigs | RSS-Origin RSSTexture&TopoRevamp Configs
- RSSOriginRSSTextureTopoRevampTextures4k | RSS-Origin RSSTexture&TopoRevamp Textures4k
- RSSOriginRSSTextureTopoRevampTextures8k | RSS-Origin RSSTexture&TopoRevamp Textures8k
- RSSOriginRSSTextureTopoRevampTextures16k | RSS-Origin RSSTexture&TopoRevamp Textures16k

Relations of cfg pack:
- Dependencies: ModuleManager, Kopernicus, KSPCommunityFixes and one of the texture pack
- Recommendations: All other stuff of RSS-Origin except the texture packs, RealSolarSystem, RealismOverhaul, EVE and Scatterer
- Suggestions: Parallax, TUFX, PlanetShine, DistantObject
- No conflicts

Relations of texture packs:
- Dependencies: The cfg pack, that's all
- No recommendations and suggestions
- The texture packs should conflict with each other

Their abstracts:
- cfg pack: A part of RSS-Origin, which overhauls some RSS celestials with more accurate, more realistic and higher res textures and topography, since some of original RSS textures are unrealistic in color, topo and other stuff. This is the configs pack.
- texture packs: The texture pack of RSS-Origin RSSTexture&TopoRevamp. This is the (xx)k version.

The rest of the informations are the same as other RSS-Origin stuff

_Originally posted by @CharonSSS in https://github.com/KSP-CKAN/NetKAN/issues/10126#issuecomment-2254204106_

**Comment by CharonSSS** [comment]
Hi @JonnyOThan I'd like to ask: If I create a new release v1.1.1 where the file names are all the same as v1.1.0, will ckan automatically identify this new release or it still need a new pull request? Thanks

**Comment by HebaruSan** [comment]
Hi @CharonSSS, CKAN has a bot that runs in the background, which checks your mods for new releases every 30 minutes. If found, the bot will try to add them to CKAN automatically. In most cases this works, but if there are significant changes to the ZIP file that prevent it from being installed correctly based on the existing recipe (such as renaming the mod folder), then the CKAN team would get notified of an error and do some manual clean-up to fix it.
