### ISSUE TITLE
[Bug]: Failing installing TweakScale-Redist

### ISSUE THREAD

**Issue by TitiFPE** [KSP-CKAN/NetKAN#10157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows10

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

1.9.1.2788

### Describe the bug

In order to install Realism Overhaul, TweakScale Redistributable is required. I tried several times, and each time it fails.

![image](https://github.com/user-attachments/assets/e519a242-2911-4ae8-a84d-41f952299614)

### Steps to reproduce

- Check "installed" on Realism Overhaul
- Click "apply"
- Click "apply" on the changeset page
- Click "continue" on the recommended mods without changing anything
- Select "ksp burst" (required for real antennas) and then continue 
- error occurs

### Relevant log output

```
Installing TweakScale-Redist v2.4.8.3...
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it may be a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/NetKAN/issues/new/choose

Please include the following information in your report:

File      : GameData/999_Scale_Redist.dll
Installing Mod : TweakScale-Redist v2.4.8.3
Owning Mod: TweakScale
CKAN Version   : v1.34.4
```

**Comment by HebaruSan** [comment]
Hi @TitiFPE, thanks for the report. We'll need to know a little more to investigate this. Please answer these follow-up questions so we can start figuring out what's going on:

- Which version of TweakScale do you have installed?
- Why are you running such an old game version?

**Comment by TitiFPE** [comment]
Hi @HebaruSan
Thanks for your help
I don't have any version of TweakScale installed yet, this is my first time installing it. I'm playing on such an old KSP version because newer versions conflict some of my installed mods. However, if my problem is related to this old KSP version, I don't mind updating it and not using those said mods anymore.

**Comment by HebaruSan** [comment]
Hi @TitiFPE, this part:

```
Owning Mod: TweakScale
```

... means that TweakScale _is_ installed. The code can't get to that point if it's not. Can you please search for TweakScale and share a screenshot so we can see what it looks like?


You can probably install the mods you want on KSP 1.12.5 (the latest version) by marking 1.9, 1.10, 1.11, and 1.12 compatible here:

- <https://github.com/KSP-CKAN/CKAN/wiki/User-guide#Choosing-compatible-game-versions>

**Comment by TitiFPE** [comment]
Problem solved ! 
I didn't know I already had TweakScale. I updated it to its last version and retried, and it worked just fine.
Thanks for your help !
(the TS version that I had and caused the problem was 2.4.3.14)
