### ISSUE TITLE
[Mod] KSRSS

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/NetKAN#10158]
![image](https://github.com/user-attachments/assets/870b85b7-26e9-403d-97a4-04b95cc57ebe)

- <https://gitlab.com/ksrss/KSRSS/-/releases>
- <https://gitlab.com/ksrss/KSRSS/-/tree/reborn>
- <https://github.com/KerbalFrench/KSRSS-Textures/releases>
- <https://forum.kerbalspaceprogram.com/topic/192818-beta-ksrss-07-kerbin-or-x25-sized-rss/>

**Comment by HebaruSan** [comment]
Note the "known limitations" section at KSP-CKAN/CKAN#3661 when adding this.

**Comment by HebaruSan** [comment]
No new release has appeared; closing. Please comment if some progress is made.
