### ISSUE TITLE
File conflict for License.txt between ColdJsMilitaryPlanes and ColdJsMilitaryPlanesF16

### ISSUE THREAD

**Issue by akravomit** [KSP-CKAN/NetKAN#10154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

windows 10

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

1.12.5.3190

### Steps to reproduce

1. Choose to install `ColdJsMilitaryPlanes` and `ColdJsMilitaryPlanesF16`
2. ![image](https://github.com/user-attachments/assets/82c497e7-9aff-41a6-9220-d06ba639b571)

**Comment by akravomit** [comment]
what does it mean to fix relationships, or the install?

**Comment by JonnyOThan** [comment]
> what does it mean to fix relationships, or the install?

It's just markers we use to categorize certain kinds of problems

**Comment by akravomit** [comment]
so that's not a me issue. ok

**Comment by HebaruSan** [comment]
Both mods also have a `Readme.txt`

**Comment by akravomit** [comment]
and i was downloading both of them and CKAN assumed it was the same mod basically?

**Comment by akravomit** [comment]
yeah it seems to be the case. i downloaded one of them and it didn't give me any problems

**Comment by HebaruSan** [comment]
Basically both mods contain copies of the same files, and mods are not allowed to overwrite each other. We just need to sort out which one should install these files, if any, or possibly rename them during installation (e.g., `License-F16.txt` and `Readme-F16.txt`).

**Comment by HebaruSan** [comment]
@akravomit, thanks for reporting this. In about 35 minutes, if you click Refresh in CKAN, you should be able to install both mods together without issues.

**Comment by akravomit** [comment]
thanks!
