### ISSUE TITLE
[Bug]: CountryDoggo's Random KK Bits download link broken

### ISSUE THREAD

**Issue by badgkat** [KSP-CKAN/NetKAN#10163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 11

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

1.12.5

### Describe the bug

https://spacedock.info/mod/1991/CountryDoggo's Random KK Bits is a broken link. 

### Steps to reproduce

Attempt to install CountryDoggo's Random KK Bits through ckan.

**Comment by HebaruSan** [comment]
Hi @badgkat, thanks for letting us know about this. Unfortunately it looks like our only option will be to remove this mod from CKAN, as there are no remaining valid downloads out there that we could use instead. However, the `ColonyBlocksandPlatforms` mod is another mod by the same author using KerbalKonstructs, so you might try that instead.
