### ISSUE TITLE
[Mod]: Resurfaced - Stockalike PBR Part Shaders

### ISSUE THREAD

**Issue by Tantares** [KSP-CKAN/NetKAN#10172]
### Mod Name

Resurfaced

### Author(s)

Al2Me6, Beale, Zorg, Roger

### License

GPL

### Homepage link

https://github.com/Tantares/Resurfaced

### Download link

https://github.com/Tantares/Resurfaced/releases/

**Comment by HebaruSan** [comment]
This depends on a yet-to-be-released version of Shabby to be uploaded here:

- <https://github.com/KSPModdingLibs/Shabby/releases>

**Comment by HebaruSan** [comment]
Submitted Tantares/Resurfaced#1.
