### ISSUE TITLE
[Mod]: VABOrganizer-SheepDog

### ISSUE THREAD

**Issue by Sheepdog2142** [KSP-CKAN/NetKAN#10178]
### Mod Name

VABOrganizer-SheepDog

### Author(s)

SheepDog2142

### License

VABOrganizer-Sheepdog © 2024 by SheepDog is licensed under CC BY-NC-SA 4.0. To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/

### Homepage link

https://forum.kerbalspaceprogram.com/topic/225797-wip-sdvabo-vab-organizer-support-mod/

### Download link

https://github.com/Sheepdog2142/VABOrganizer-Sheepdog

**Comment by Sheepdog2142** [comment]
Do i need to do anything else to get this added to CKAN?

**Comment by HebaruSan** [comment]
Hi @Sheepdog2142, thanks for the submission.

> Do i need to do anything else to get this added to CKAN?

Yes, you'll need to make at least one release. That's how CKAN tracks what version is installed, and currently there are none:

- <https://github.com/Sheepdog2142/SDVABO_Support/releases>

GitHub has documentation about how to do this, and you can use many existing KSP mods as a model.

**Comment by Sheepdog2142** [comment]
Ok updated the name and created the release.
