### ISSUE TITLE
[Bug]: SpaceY Fuel Tank Z-Fighting. Issue did not occur on non-CKAN install

### ISSUE THREAD

**Issue by heyimastopsign** [KSP-CKAN/NetKAN#10183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS 

### CKAN Version

v1.34.4   

### Games

KSP 1

### Game Version

1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

I have installed BlackRack's volumetric clouds, but this issue has been occurring for several months before this installation.

### Describe the bug

Usage of the vast majority of SpaceY fuel tanks results in violent Z-fighting issues.

<img width="592" alt="Screenshot 2024-08-24 at 2 23 31 PM" src="https://github.com/user-attachments/assets/31557cf3-9749-4096-ad85-99e94e964c59">

### Steps to reproduce

* Navigate to a SpaceY Fuel tank (for instance, the FL-75-k115 7.5m Fuel Tank)
* If the issue is present in this tank, move the camera a bit to view highly intense z-fighting 
*

**Comment by JonnyOThan** [comment]
Hi, this is actually a bug in SpaceYExpanded and I submitted a PR 6 months ago to fix it which has not been merged: https://github.com/zer0Kerbal/SpaceYExpanded/pull/120

**Comment by JonnyOThan** [comment]
Need to check if this is just https://github.com/zer0Kerbal/SpaceYExpanded/pull/120

But that should have only affected a couple tanks I think.

@heyimastopsign  please include ksp.log.

**Comment by JonnyOThan** [comment]
Yep it's a dupe.  I'm not sure why it wouldn't occur in a manual install, or even where you manually installed from.  Note that zer0kerbal has not published the latest version on spacedock which is where CKAN pulls from.  So if you manually installed from github or curseforge you're not installing the same thing CKAN is.  We can't force a mod author to release their latest version on Spacedock.  CKAN can't download from curseforge.  I'd be a bit wary of switching the download source to github without talking to the author, but considering my PR to fix this issue hasn't been merged yet, :shrug:
