### ISSUE TITLE
[Mod]: Kcalbeloh System

### ISSUE THREAD

**Issue by jcyuan06** [KSP-CKAN/NetKAN#10197]
Hi there! Could you help me add [VertexColorMapEmissive](https://forum.kerbalspaceprogram.com/topic/225111-1125-kopernicus-vertexcolormapemissive-100-easy-emissives/) as a new dependencies to [Kcalbeloh System](https://forum.kerbalspaceprogram.com/topic/203753-1125-kcalbeloh-system-planet-pack-v117-a-journey-to-a-black-hole-april-9-2024/) of the next release (v1.1.8)? I'm going to post the release soon. Thank you!

**Comment by HebaruSan** [comment]
Hi @jcyuan06, #10198 is now ready to add this. I have subscribed to new release notifications on your repo and will merge once I receive it. Cheers!

**Comment by jcyuan06** [comment]
The new version was released just now! By the way, is it possible to set SigmaDimensions as a dependency if both Kcalbeloh and RSS are installed?

**Comment by HebaruSan** [comment]
> The new version was released just now!

Cool! Merged; the dependency should appear within 35 minutes.

> By the way, is it possible to set SigmaDimensions as a dependency if both Kcalbeloh and RSS are installed?

No, dependencies can't be conditional on other mods being installed. We can add `SigmaDimensions` as an unconditional dependency if you like.

**Comment by jcyuan06** [comment]
I see. I prefer not to add it as a dependency since it's not required for the main part of the mod. Thank you for your help!

**Comment by SofieBrink** [comment]
Would a plausible workaround be making RSS a conflicting mod with Kcalbeloh and having a seperate Kcalbeloh-RSS ckan item that just installs the same mod files but has hard dependencies on both RSS and SigmaDimensions?
