### ISSUE TITLE
[Mod]: Mass Effect Drive Mod

### ISSUE THREAD

**Issue by Lucaspec72** [KSP-CKAN/NetKAN#10209]
### Mod Name

Mass Effect Drive Mod

### Author(s)

Lucaspec72

### License

CC BY-NC-SA 3.0

### Homepage link

https://forum.kerbalspaceprogram.com/topic/218243-112x-mass-effect-drive-mod/

### Download link

https://github.com/Lucaspec72/Mass-Effect-Drive-Mod-KSP/releases

**Comment by HebaruSan** [comment]
Hi @Lucaspec72, thanks for the submission!

If you're open to suggestions, putting a link to your forum thread in your repo can be helpful for non-CKAN users, and as a bonus CKAN can pull it into the metadata automatically, and you can control that link as needed without the need to make updates to your mod's netkan.

Can be done on the main repo page via the gear icon ⚙️:

![image](https://github.com/user-attachments/assets/61d9f182-dffd-4013-a9fa-9e37684db342)

**Comment by Lucaspec72** [comment]
Didn't know i could do that, added it to my repo.
