### ISSUE TITLE
User noticed Scatterer's self-conflict

### ISSUE THREAD

**Issue by CobaltonGit** [KSP-CKAN/NetKAN#10214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10 22H2

### CKAN Version

v1.34.4

### Games

KSP 1

### Game Version

1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

Had to install Scatterer manually

### Describe the bug

Scatterer is conflicting with... Scatterer?

### Steps to reproduce

* Look at Scatterer
* See conflicting mods

### Relevant log output

![ckan_GL59hmB2S6](https://github.com/user-attachments/assets/9b65b289-2ff9-47e0-bbaf-965bc2265df1)

**Comment by HebaruSan** [comment]
Hi @CobaltonGit, thanks for reaching out.

That was done that way for a reason (see #4541) and it **doesn't** stop Scatterer from being installed. Closing as invalid issue; please feel free to report whatever difficulty made you feel that you could not install Scatterer in the first place.
