### ISSUE TITLE
[Mod]: Universal Resource Transfer

### ISSUE THREAD

**Issue by ProgrammerFailure** [KSP-CKAN/NetKAN#10241]
### Mod Name

Universal Resource Transfer

### Author(s)

ProgrammerFailure (me)

### License

The unlicense

### Homepage link

https://forum.kerbalspaceprogram.com/topic/225761-ksp-18x-universal-resource-transfer-v101/

### Download link

https://github.com/ProgrammerFailure/Universal-Resource-Transfer/releases

**Comment by ProgrammerFailure** [comment]
I can change the license if needed, I don't really care about that.
Incompatible with @Anirrudh Beamed Power Standalone.
Requires ModuleManager
Description: Plugin that enables transmission of arbitrary resources via beamed power.

**Comment by HebaruSan** [comment]
Hey @ProgrammerFailure, thanks for the submission! A couple of things as I'm noticing them...

- Several of these files are part of KSP, and you're not supposed to redistribute them to people who haven't paid for the game (which includes uploading them to GitHub):
  https://github.com/ProgrammerFailure/Universal-Resource-Transfer/tree/master/obj/Debug
  https://github.com/ProgrammerFailure/Universal-Resource-Transfer/tree/master/obj/Release
  https://github.com/ProgrammerFailure/Universal-Resource-Transfer/tree/master/bin/Debug
- The repo contains a `UniversalResourceTransfer.version` file that looks like we could use to set the compatibility, except that the copy of the file in the ZIP is different and just says `1.0.2`, do you want to fix this? Also the compatibility in the file on the repo says `1.8.0` through `1.11.99`, which I'm guessing is not intended as it excludes the 1.12.x versions.

**Comment by ProgrammerFailure** [comment]
Ah, sorry. Give me a few minutes, I'll fix all those.

**Comment by ProgrammerFailure** [comment]
The repo's version file was just retained from the original mod, I'll just double check to see if it's right.

**Comment by ProgrammerFailure** [comment]
@HebaruSan , I think the issues have been corrected

**Comment by HebaruSan** [comment]
Hi, the v1.0.3 release has no ZIP file to download, just the source code.

I guess this is an opportunity to plug @JonnyOThan's KSP Build Tools, which can automate the whole processs of making a release and more:

https://github.com/KSPModdingLibs/KSPBuildTools

**Comment by ProgrammerFailure** [comment]
Oof I'm an idiot

**Comment by ProgrammerFailure** [comment]
I'm aware of KSP build tools, but I wasn't when I started this mod, hence why it's not used.

**Comment by ProgrammerFailure** [comment]
I'm aware of KSP build tools, but I wasn't when I started this mod, hence why it's not used.

**Comment by ProgrammerFailure** [comment]
@HebaruSan 
Hopefully, it should be fixed now. Sorry for the repeated mistakes.

**Comment by HebaruSan** [comment]
Hey @ProgrammerFailure, those changes look good. I noticed a few more minor things, but they don't block merging the PR, so fix or not at your leisure:

- The website link on the repo links to a _comment_ on page two of the forum thread. I'd suggerst removing `/page/2/#comment-4414992` from the URL so the user would see the OP upon clicking it.
- The description on the repo is the same as it was for BeamedPower. You might consider customizing it for your mod.
