### ISSUE TITLE
[Mod]: Remove temporarily Celestial Harmony from CKAN due to many internal changes

### ISSUE THREAD

**Issue by ProximaCentauri-star** [KSP-CKAN/NetKAN#10253]
### Mod Name

Celestial Harmony

### Author(s)

ProximaCentauri-star

### License

All Rights Reserved

### Homepage link

https://github.com/ProximaCentauri-star/Celestial-Harmony

### Download link

https://github.com/ProximaCentauri-star/Celestial-Harmony/releases/

**Comment by ProximaCentauri-star** [comment]
Right now, dependencies were changed and the most is currently listed as a scatterer sunflare config for some reaons

**Comment by HebaruSan** [comment]
Hi @ProximaCentauri-star, thanks for getting in touch. If it's simply a matter of the dependencies changing, we can update the metadata to install the correct dependencies. Would you like to try that option?

**Comment by HebaruSan** [comment]
> the mod is currently listed as a scatterer sunflare config for some reasons

The reason is that `GameData/CelestialHarmony/Scatterer/Config/Sunflares/Sunflares.cfg` contains a `Scatterer_sunflare` config node, which means this mod defines its own sunflare:

![image](https://github.com/user-attachments/assets/0c5f4e74-2140-4f1b-a94d-9139e99ae20c)

**Comment by ProximaCentauri-star** [comment]
> > the mod is currently listed as a scatterer sunflare config for some reasons
> 
> The reason is that `GameData/CelestialHarmony/Scatterer/Config/Sunflares/Sunflares.cfg` contains a `Scatterer_sunflare` config node, which means this mod defines its own sunflare:
> 
> ![image](https://private-user-images.githubusercontent.com/1559108/376321251-0c5f4e74-2140-4f1b-a94d-9139e99ae20c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MzIzMjAsIm5iZiI6MTcyODkzMjAyMCwicGF0aCI6Ii8xNTU5MTA4LzM3NjMyMTI1MS0wYzVmNGU3NC0yMTQwLTRmMWItYTk0ZC05MTM5ZTk5YWUyMGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTRUMTg1MzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzg4NzVlODg1YjhkMzYzODJjMGE3N2M0ZjVkMDNiZTNhMWFhMDZhNGRkN2ZiMDQxYzA3Yzg5ZDQ3MGVjNWE1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.jx7fSRFZEiFlTu3Ib8hWLLNWQyLq_uxiuFJdqke5hj8)

I see

**Comment by HebaruSan** [comment]
Cool, I think CKAN is already up to date with those changes:

![image](https://github.com/user-attachments/assets/40bf5c04-80a8-4f44-8605-45294db7c5b7)

Is there a problem that you know of, or can we close this issue?

**Comment by ProximaCentauri-star** [comment]
> Cool, I think CKAN is already up to date with those changes:
> 
> ![image](https://private-user-images.githubusercontent.com/1559108/376358451-40bf5c04-80a8-4f44-8605-45294db7c5b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MzI5MzcsIm5iZiI6MTcyODkzMjYzNywicGF0aCI6Ii8xNTU5MTA4LzM3NjM1ODQ1MS00MGJmNWMwNC04MGE4LTRmNDQtODYwNS00NTI5NGRiN2M1YjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTRUMTkwMzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjZjZjI1OTVlMjlkNTNjMDRjYjdlMDkyNTc0ZWE1ODdjYWExZmFjZWIzZThjNzFmY2NmNWE5MWE2Mzc5ODU4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WXZ16m-T5moosy32vmPf-4vMjtU-1hsyVbS-dPh2DqA)
> 
> Is there a problem that you know of, or can we close this issue?

Seems about right yes, thank you

**Comment by HebaruSan** [comment]
Cool, thanks for checking in, and let us know if anything else changes or if you notice any issues!

**Comment by HebaruSan** [comment]
Thanks! That answers the question I just asked in https://github.com/KSP-CKAN/NetKAN/issues/10024#issuecomment-2925129387. I think we'll switch the `CelestialHarmony` module over to use `_Harmonia.zip`, and we can add the `_Chaos.zip` as a new module.

**Comment by HebaruSan** [comment]
> a brand new star system that isn't needed for the mod to function to pleasae some low end hardware user for RAM usage

Is that what CKAN should use as the user-visible description of this Chaos system?

**Comment by HebaruSan** [comment]
OK, work on this is proceeding at #10580. Currently the validation scripts are testing installation of both mods.
