### ISSUE TITLE
Remove Kopernicus from RSS-Origin's dependency list

### ISSUE THREAD

**Issue by CharonSSS** [KSP-CKAN/NetKAN#10294]
I just notice that, if one is using RSS-Reborn, and want to install RSS-Origin via CKAN, then, Kopernicus, as a dependency of RSS-Origin, will force to overwrite ballisticfox's custom Kopernicus fork which is needed for RSS-Reborn.

So I request to remove Kopernicus from RSS-Origin's dependency list.

Precisely, remove it for the following mods:

RSS-Origin CelestialsPack Core
![image](https://github.com/user-attachments/assets/4186cfe0-d033-445e-9f15-c4e2a06ed089)

RSS-Origin JSUNrings
![image](https://github.com/user-attachments/assets/211bb2d1-ea8d-4fa6-9f16-578f1f2aa5a3)

RSS-Origin RSS Texture & Topo Revamp Configs
![image](https://github.com/user-attachments/assets/e3023fb8-438f-4a39-9e83-051e4ec6d458)

**Comment by HebaruSan** [comment]
Hi @CharonSSS, I think there's a better workaround. If you install a custom fork of Kopernicus _first_, CKAN should count that as satisfying the dependency. Can you try that and see if it works?

Removing the dependency would cause problems for users who would try to install your mod and end up with no Kopernicus installed whatsoever, confusing them and creating unnecessary support requests.

**Comment by CharonSSS** [comment]
> Hi @CharonSSS, I think there's a better workaround. If you install a custom fork of Kopernicus _first_, CKAN should count that as satisfying the dependency. Can you try that and see if it works?
> 
> Removing the dependency would cause problems for users who would try to install your mod and end up with no Kopernicus installed whatsoever, confusing them and creating unnecessary support requests when the mod does not work.

I agree with you. After sort out the logic clearly it turns out that I was thinking too much. I didn't test it but a few days ago a RSS-Origin user told me that he had encountered a similar scenario and his answer is yes it works.

Alright, I think it's time to close the issue. Thanks!

**Comment by HebaruSan** [comment]
OK, thanks for your reply!
