### ISSUE TITLE
Requesting USI Life Support be added to CKAN

### ISSUE THREAD

**Issue by kpengwin** [KSP-CKAN/NetKAN#1056]
This mod doesn't seem to be in the database yet.

https://github.com/BobPalmer is the author of this mod

https://github.com/BobPalmer/USI-LS/releases/tag/0.1.0 is the mod in question.

I'm just requesting this be added because the Wiki told me it was acceptable to do so. :)

**Comment by Dazpoet** [comment]
See https://github.com/KSP-CKAN/NetKAN/pull/1021 we're waiting for a first stable release so our bot can index it.

**Comment by Dazpoet** [comment]
Prerelease indexed into CKAN manually now.

**Comment by kpengwin** [comment]
Thanks!
