### ISSUE TITLE
PlanetShine

### ISSUE THREAD

**Issue by TeddyDD** [KSP-CKAN/NetKAN#1059]
PlanetShine 0.2.2.1 works under 1.0
However it seems author releasing mod ony on Curse, Kerbal Stuff version wasn't even marked as working under 1.0 http://forum.kerbalspaceprogram.com/threads/96497
https://kerbalstuff.com/mod/266/PlanetShine
We can't edit .ckan file because boot will override it.

What shall we do in that case?

**Comment by Dazpoet** [comment]
grumble grumble... we hardcode 1.0 into the .netkan file and add a comment about why it was done so when the next release of KSP comes about we can curse a lot until we find it :p

**Comment by Dazpoet** [comment]
Aha, or we do nothing because KS was just updated to 1.0 :) netkan-bot should catch it in an hour or two.

I'm closing this since doing nothing paid off for once :+1:
