### ISSUE TITLE
Should InterstellarFuelSwitch have a -Core package with just the .dll?

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/NetKAN#1126]
Looking at NearFutureConstruction and CryoEngines they now depend on InterstellarFuelSwitch but in their respective downloads from Kerbalstuff they only redistribute the InterstellarFuelSwitch.dll

Currently we're not giving the above mentioned mods installs that correctly mirror their behaviour when installed manually. This might cause grief somewhere down the road.

**Comment by dbent** [comment]
:+1:

**Comment by sswelm** [comment]
yes it should (I made it)

**Comment by 602p** [comment]
:+1:

**Comment by Dazpoet** [comment]
Yay this has been resolved and so I'm closing this.
