### ISSUE TITLE
Mk3MiniExpansion exists twice

### ISSUE THREAD

**Issue by mgsdk** [KSP-CKAN/NetKAN#1248]
Going through the netkan-bot log I see that Mk3MiniExpansion is present twice, as https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/Mk3MiniExpansionPack.netkan and https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/OPTMk3MiniExpansion.netkan. Both fail to build at the moment due to a change in the naming scheme in the zip file of the mod.

How do we solve this issue, and get users of one pack onto the other seamlessly?

**Comment by Dazpoet** [comment]
Relevant https://github.com/KSP-CKAN/NetKAN/pull/1087

**Comment by plague006** [comment]
Months-old issue from a long-ago KSP. #1087 should resolve this. If I'm premature in closing this please say so and I'll happily reopen.
