### ISSUE TITLE
HGR/Home Grown Rockets

### ISSUE THREAD

**Issue by 00Augustus00** [KSP-CKAN/NetKAN#1261]
Could it be added?

**Comment by plague006** [comment]
It's under an "All rights reserved" license at the moment, but the author seems interested in having the mod hosted (http://forum.kerbalspaceprogram.com/threads/60974-1-0-2-HGR-1-875m-parts%28v1-2-1-released%29?p=1952951&viewfull=1#post1952951). I've opened a line of dialogue, suggesting he host on KerbalStuff for easier CKAN maintenance and to attain permission to have the mod redistributed by CKAN.

**Comment by Dazpoet** [comment]
as long as it's hosted on mediafire we can't do anything since we can't index from there.

**Comment by plague006** [comment]
I'm drowsy.. Did I type mediafire somewhere instead of curse? He hosts on curse.

**Comment by Dazpoet** [comment]
Oh my, I just checked the linked forumthread and saw a mediafire link, probably I'm not at my best either :)

**Comment by plague006** [comment]
If/when needed, I whipped up the .ckan for v1.2.1: http://pastebin.com/JAqh7vX7

**Comment by plague006** [comment]
Per: http://forum.kerbalspaceprogram.com/threads/60974-1-0-2-HGR-1-875m-parts%28v1-2-1-released%29?p=1960097&viewfull=1#post1960097

@OrionKermin: Thank you, I've given it a quick once over. I'll read over it in more detail over the weekend and try to get everything set up on Kerbalstuff at that time.

**Comment by plague006** [comment]
Leaving this in OrionKermin's hands since he'll be posting to KS, removed the pastebin.
