### ISSUE TITLE
KSP Interstellar Extended

### ISSUE THREAD

**Issue by A2K** [KSP-CKAN/NetKAN#1273]
Here is a .netkan file for Interstellar Extended, please add it to the repository. The file was created in collaboration with FreeThinker, the current mod maintainer.

https://gist.github.com/A2K/ac4e0275c222b741169c

**Comment by sswelm** [comment]
I concur

**Comment by Dazpoet** [comment]
It doesn't depend on InterstellarFuelSwitch?

**Comment by A2K** [comment]
Dazpoet, as far as I know InterstellarFuelSwitch was originally part of the Interstellar mod, but you can play Interstellar without fuel switch. I'm not sure, maybe it is absolutely necessary when using some high level technologies, that's why it is listed in "recommends" section. CKAN GUI will suggest to install the fuel switch mod when installing Interstellar Extended.

**Comment by A2K** [comment]
Trying to speed up the process I have created a pull request with this metadata file. Someone with write access please click the green button here: https://github.com/KSP-CKAN/NetKAN/pull/1314

**Comment by sswelm** [comment]
InterstellarFuelSwitch is required if you want to use any propulsion

**Comment by mgsdk** [comment]
Closed via https://github.com/KSP-CKAN/NetKAN/pull/1363.
