### ISSUE TITLE
Adding RCS Build Aid to CKAN

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/NetKAN#1299]
Followed the guide to create a .netkan for http://forum.kerbalspaceprogram.com/threads/35996

netkan.exe ended up crashing when I tried creating a .ckan file, possibly because I don't have mono? possibly because I'm an idiot? At any rate, I'm pretty sure I formatted the file correctly. Here's a pastebin of it: http://pastebin.com/dBYNSDwh
If someone else would be willing to take it the last 5 yards it would be appreciated. Thanks.

Lastly, paging @m4v as the author per: https://github.com/KSP-CKAN/CKAN-support/wiki/Adding-a-mod-to-the-CKAN#requesting-support-for-a-mod-on-the-ckan

**Comment by Dazpoet** [comment]
See https://github.com/KSP-CKAN/NetKAN/pull/1292#issuecomment-102868557
