### ISSUE TITLE
KSP Interstellar

### ISSUE THREAD

**Issue by Almagnus1** [KSP-CKAN/NetKAN#133]
One of the mods that would be awesome to have available through CKAN is KSP Interstellar.

The forum page for KSP Interstellar is:
http://forum.kerbalspaceprogram.com/threads/43839

Edit:
I've shot Fractal_UK a PM on the KSP Forums, and I'm waiting on a response back.

**Comment by Xolroc** [comment]
How does one access the Interstellar mod? It's not showing up in the repo for me.

**Comment by hakan42** [comment]
@Xolroc,  interstellar is marked as 0.25-compatible. You won't get it offered for 0.90 installations.

**Comment by Xolroc** [comment]
Interstellar has been taken up by a new modder to keep it functional on new versions; it can be found at http://forum.kerbalspaceprogram.com/threads/104943-0-90-KSP-Interstellar-port-maintance-thread .  I don't know any details on what would be needed (CKAN is the third mod manager for KSP I'm trying out, and I'm not entirely sure how ti works yet) but this might let you get a functional 0.90 version listed on there?

**Comment by hakan42** [comment]
@Xolroc, could you please open up a fresh issue and paste your comment above? 

Usually, people don't notice any discussion on already closed issues.
