### ISSUE TITLE
Using 'download' field, netkan.exe won't create .ckan

### ISSUE THREAD

**Issue by lawnmowerlatte** [KSP-CKAN/NetKAN#1371]
I'm trying to add a mod which does't use GitHub or KerbalStuff. Based on [the guide](https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN#other-host-guide), I should be able to do this by specifying a `download` field. However, when I verify the `.netkan` it fails:

    $ netkan --debug WasdEditorCamera.netkan 
    107 [1] DEBUG CKAN.KSPManager (null) - Loading KSP instances from registry
    125 [1] DEBUG CKAN.KSPManager (null) - Loading Default from /Users/lawnmowerlatte/Library/Application Support/Steam/SteamApps/common/Kerbal Space Program
    148 [1] DEBUG CKAN.KSP (null) - Found version 1.0.2
    150 [1] DEBUG CKAN.KSP (null) - /Users/lawnmowerlatte/Library/Application Support/Steam/SteamApps/common/Kerbal Space Program looks like a GameDir
    152 [1] DEBUG CKAN.KSP (null) - Found version 1.0.2
    152 [1] DEBUG CKAN.KSP (null) - /Users/lawnmowerlatte/Library/Application Support/Steam/SteamApps/common/Kerbal Space Program looks like a GameDir
    153 [1] DEBUG CKAN.KSP (null) - Initialising /Users/lawnmowerlatte/Library/Application Support/Steam/SteamApps/common/Kerbal Space Program/CKAN
    153 [1] DEBUG CKAN.KSP (null) - Initialised /Users/lawnmowerlatte/Library/Application Support/Steam/SteamApps/common/Kerbal Space Program/CKAN
    154 [1] DEBUG CKAN.KSPManager (null) - Added Default at /Users/lawnmowerlatte/Library/Application Support/Steam/SteamApps/common/Kerbal Space Program
    158 [1] DEBUG CKAN.KSP (null) - Checking if KSP is in my exe dir: /Applications
    158 [1] DEBUG CKAN.KSP (null) - Cannot find GameData in /Applications
    160 [1] INFO CKAN.NetKAN.MainClass (null) - Using CKAN cache at /Users/lawnmowerlatte/Library/Application Support/Steam/SteamApps/common/Kerbal Space Program/CKAN/downloads
    160 [1] INFO CKAN.NetKAN.MainClass (null) - Processing WasdEditorCamera.netkan
    
    Unhandled Exception:
    System.ArgumentNullException: Argument cannot be null.
    Parameter name: input
      at System.Text.RegularExpressions.Regex.Match (System.String input, Int32 startat) [0x00000] in <filename unknown>:0 
      at System.Text.RegularExpressions.Regex.Match (System.String input) [0x00000] in <filename unknown>:0 
      at System.Text.RegularExpressions.Regex.Match (System.String input, System.String pattern, RegexOptions options) [0x00000] in <filename unknown>:0 
      at System.Text.RegularExpressions.Regex.Match (System.String input, System.String pattern) [0x00000] in <filename unknown>:0 
      at CKAN.NetKAN.MainClass.FindRemote (Newtonsoft.Json.Linq.JObject json) [0x00000] in <filename unknown>:0 
      at CKAN.NetKAN.MainClass.Main (System.String[] args) [0x00000] in <filename unknown>:0 
    [ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentNullException: Argument cannot be null.
    Parameter name: input
      at System.Text.RegularExpressions.Regex.Match (System.String input, Int32 startat) [0x00000] in <filename unknown>:0 
      at System.Text.RegularExpressions.Regex.Match (System.String input) [0x00000] in <filename unknown>:0 
      at System.Text.RegularExpressions.Regex.Match (System.String input, System.String pattern, RegexOptions options) [0x00000] in <filename unknown>:0 
      at System.Text.RegularExpressions.Regex.Match (System.String input, System.String pattern) [0x00000] in <filename unknown>:0 
      at CKAN.NetKAN.MainClass.FindRemote (Newtonsoft.Json.Linq.JObject json) [0x00000] in <filename unknown>:0 
      at CKAN.NetKAN.MainClass.Main (System.String[] args) [0x00000] in <filename unknown>:0 

It looks like it's failing on `MainClass.cs:63` where it's invoking `NetKanRemote remote = FindRemote(json);` which is looking for `$kref`. If I change `download` to `$kref`, I instead get:

    Unhandled Exception:
    CKAN.Kraken: Cannot find remote and ID in kref: http://dl.dropboxusercontent.com/u/7121093/ksp-mods/KSP%5B1.0.2%5DWasdEditorCamera%5BMay20%5D.zip
      at CKAN.NetKAN.MainClass.FindRemote (Newtonsoft.Json.Linq.JObject json) [0x00000] in <filename unknown>:0 
      at CKAN.NetKAN.MainClass.Main (System.String[] args) [0x00000] in <filename unknown>:0 
    [ERROR] FATAL UNHANDLED EXCEPTION: CKAN.Kraken: Cannot find remote and ID in kref: http://dl.dropboxusercontent.com/u/7121093/ksp-mods/KSP%5B1.0.2%5DWasdEditorCamera%5BMay20%5D.zip
      at CKAN.NetKAN.MainClass.FindRemote (Newtonsoft.Json.Linq.JObject json) [0x00000] in <filename unknown>:0 
      at CKAN.NetKAN.MainClass.Main (System.String[] args) [0x00000] in <filename unknown>:0 

This makes sense to me as the value doesn't match the expected formatting of a `$kref` variable. Are third-party downloads still supported? How can I create the `.netkan`?

**Comment by lawnmowerlatte** [comment]
P.S. I've posted the `.netkan` in question [on my fork](https://github.com/lawnmowerlatte/NetKAN/commit/483b26c9f03db1877517f2c6148152b2aea18b93).

**Comment by plague006** [comment]
That's my fault, I overhauled that wiki page recently and I'm still working out kinks. non KS/non github versions shouldn't do verify a .netkan file because you're not generating a .netkan, you're generating a .ckan directly and should submit it to KSP-CKAN/CKAN-meta

**Comment by lawnmowerlatte** [comment]
Oh ok, so should I just submit a pull request then?

**Comment by plague006** [comment]
Just verify the CKAN file itself (so skip anything related to netkan.exe). Section of the guide: https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN#verifying-netkan-files

Off the bat, the license doesn't match one that is allowed in the schema. Allowed licenses are:                 "public-domain",
                "Apache", "Apache-1.0", "Apache-2.0",
                "Artistic", "Artistic-1.0", "Artistic-2.0",
                "BSD-2-clause", "BSD-3-clause", "BSD-4-clause",
                "ISC",
                "CC-BY", "CC-BY-1.0", "CC-BY-2.0", "CC-BY-2.5", "CC-BY-3.0", "CC-BY-4.0",
                "CC-BY-SA", "CC-BY-SA-1.0", "CC-BY-SA-2.0", "CC-BY-SA-2.5", "CC-BY-SA-3.0", "CC-BY-SA-4.0",
                "CC-BY-NC", "CC-BY-NC-1.0", "CC-BY-NC-2.0", "CC-BY-NC-2.5", "CC-BY-NC-3.0", "CC-BY-NC-4.0",
                "CC-BY-NC-SA", "CC-BY-NC-SA-1.0", "CC-BY-NC-SA-2.0", "CC-BY-NC-SA-2.5", "CC-BY-NC-SA-3.0", "CC-BY-NC-SA-4.0",
                "CC-BY-NC-ND", "CC-BY-NC-ND-1.0", "CC-BY-NC-ND-2.0", "CC-BY-NC-ND-2.5", "CC-BY-NC-ND-3.0", "CC-BY-NC-ND-4.0",
                "CC0",
                "CDDL", "CPL",
                "EFL-1.0", "EFL-2.0",
                "Expat", "MIT",
                "GPL-1.0", "GPL-2.0", "GPL-3.0",
                "LGPL-2.0", "LGPL-2.1", "LGPL-3.0",
                "GFDL-1.0", "GFDL-1.1", "GFDL-1.2", "GFDL-1.3",
                "GFDL-NIV-1.0", "GFDL-NIV-1.1", "GFDL-NIV-1.2", "GFDL-NIV-1.3",
                "LPPL-1.0", "LPPL-1.1", "LPPL-1.2", "LPPL-1.3c",
                "MPL-1.1",
                "Perl",
                "Python-2.0",
                "QPL-1.0",
                "W3C",
                "Zlib",
                "Zope",
                "WTFPL",
                "open-source", "restricted", "unrestricted", "unknown"

**Comment by lawnmowerlatte** [comment]
Thanks @plague006, I've changed the license to 'MIT' — forgive me if I'm being dense, but how do I make the CKAN file if `netkan.exe` won't create it?

**Comment by plague006** [comment]
You've created a .ckan already. The file you linked in your fork is a .ckan

A .netkan is just a file that the bots work with to create a .ckan. In your case you manually entered all the info and have a .ckan.

**Comment by lawnmowerlatte** [comment]
Ah, I see. Thanks! I test installed it and it worked great. One last thing: do I add a pull request from NetKAN or from CKAN-meta

**Comment by plague006** [comment]
I would say close the netkan one and send one to ckan-meta.

**Comment by lawnmowerlatte** [comment]
Ok, thanks!
