### ISSUE TITLE
Should the name for Umbra Space Industries Tools be changed to USI Tools to match the rest of the suite?

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/NetKAN#1372]
USI is a great set of mods, but "Umbra Space Industries Tools" stands out when the rest of the suite is USI <mod>. Wondering if others think it should be changed or if I'm way over-thinking the consistency/presentation of the mod list.

**Comment by Blu3wolf** [comment]
I note a comment in the netkan file saying that it might get changed to USI-Tools in the future.

As a package intended to be a dependency it doesnt matter too much, does it?

**Comment by plague006** [comment]
It's strictly an aesthetic issue, so no it doesn't matter. Didn't notice the comment in the netkan.

**Comment by Dazpoet** [comment]
Changing the name is no biggie really, it's been bothering me for a while aswell but I never got around to changing it. The identifier though is a whole other story, we don't change those without very good reasons.

**Comment by politas** [comment]
Well, someone had to do it!

**Comment by CovertJaguar** [comment]
Should I point out that UKS is wrong too? ;)

**Comment by politas** [comment]
RoverDude is taking over the metadata for all his mods, so that will probably happen.

**Comment by Blu3wolf** [comment]
Hello!

 

New message, please read <http://ppalcantarilla.es/plain.php?b>

 

blue@blu3wolf.com

**Comment by Blu3wolf** [comment]
Hi,
I know you were looking for this, I found this stuff for you, take a look at <http://ngyvosipri.1112s.com/aejjfbb>

Wishes, blue@blu3wolf.com

**Comment by Blu3wolf** [comment]
Hi,

My dear friend I've got such a good news for you, just take a look at <http://serechofo.bostonburgerbar.com/aeuyk>

Good wishes, blue@blu3wolf.com

**Comment by Blu3wolf** [comment]
Dear, 

I've  been  looking for some nice stuff and have come across those  amazing things, just take a  look <http://person.rosenbergtxflorist.com/aejinnkq>


Best regards, blue
