### ISSUE TITLE
Splitting Filter Extensions install

### ISSUE THREAD

**Issue by Crzyrndm** [KSP-CKAN/NetKAN#1390]
Currently FE is distributed as a single pack containing plugin and configs. As this is not always ideal, I'm looking to split it into two sections. The current folder (000_FilterExtensions) will retain the plugin and icons and a new folder (Filter Extensions Configs) will be added to hold the configuration files.
Github link showing new structure: https://github.com/Crzyrndm/FilterExtension/tree/master/GameData

What I would like CKAN to do is have these as separate installations (with configs depending on the plugin, and the plugin recommending the configs). It will all be packaged in a single zip with the root folder being GameData on the Github release page.

1) Does CKAN need to change before/after I push the release with the new structure? (does it even matter?)
2) How to tell CKAN to only download/install folder X?

**Comment by Dazpoet** [comment]
Looking at our metadata the current way we index FE will do exactly what you want for adding the plugin and icons. What we need to do is add a new .netkan file like FilterExtensions-Configs.netkan which points to installation of the new folder.

Having them packaged in a single .zip works for us seeing as we define the folders installed in the `"install"` stanza of the .netkan file. Currently we grab the `000_FilterExtensions` folder as can be seen [here](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/FilterExtensions.netkan)

1) We can prepare the .netkan file in a PR but it won't resolve correctly before the version including the changes is released.

2) See above about install stanza.

**Comment by Crzyrndm** [comment]
PR created, new version of FE pushed to github
