### ISSUE TITLE
Near future and .frozen files

### ISSUE THREAD

**Issue by TeddyDD** [KSP-CKAN/NetKAN#1526]
All Near Future Technologies packs are updated to 1.0.2 but they not appears in ckan. I found they have changed extensions to .frozen So my question is really simple: WTF? What is .frozen and can I make it normal again safely?

**Comment by Dazpoet** [comment]
.frozen is so they don't build while we wait for official netkans which NearFuture guys are making themselves.

**Comment by TeddyDD** [comment]
Ok. I'v seeb someone is working on update for this mods so I'm closing this now
