### ISSUE TITLE
TweakableEverything now has Extras which we don't index

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/NetKAN#1580]
We probably should.

Information about [release](http://forum.kerbalspaceprogram.com/threads/64711-1-0-TweakableEverything-1-11-6-For-all-your-part-tweaking-needs?p=2000860&viewfull=1#post2000860) and [function](http://forum.kerbalspaceprogram.com/threads/64711-1-0-TweakableEverything-1-11-6-For-all-your-part-tweaking-needs?p=2001562&viewfull=1#post2001562) are on the forums.

**Comment by blnk2007** [comment]
Should be all set now!

**Comment by dbent** [comment]
Closing as implemented.
