### ISSUE TITLE
Adding B9 Aerospace to CKAN

### ISSUE THREAD

**Issue by NightmareElmo** [KSP-CKAN/NetKAN#1582]
Just a request to add this mod to CKAN. It is one of the most popular mods out there and it is sad to see it not included

**Comment by Dazpoet** [comment]
B9 is on CKAN but is not updated to 1.0+, if you are not seeing it on a 0.90 install though something broke somewhere :O

**Comment by dbent** [comment]
Closing for now as the mod is available for KSP 0.90 as `B9`.
