### ISSUE TITLE
Adding KSP Interstellar to CKAN

### ISSUE THREAD

**Issue by NightmareElmo** [KSP-CKAN/NetKAN#1583]
Just wondering if you add KSP Interstellar to CKAN. Thanks
http://forum.kerbalspaceprogram.com/threads/43839-0-22-KSP-Interstellar-%28Science-Integration-Heat-Mechanics%29-Version-0-7-4-%28Beta%29

**Comment by Dazpoet** [comment]
The version by Boris is on CKAN but currently only KSPI-Extended is updated for 1.0+ of KSP which is why that is the only one to show up currently. If you are not seeing KSPI in an 0.90 install though something broke on out side and we need to fix it.

**Comment by dbent** [comment]
Closing for now as the mod is available for KSP 0.90 as `KSPInterstellar`.
