### ISSUE TITLE
Requesting Mod added to CKAN

### ISSUE THREAD

**Issue by dtphantom** [KSP-CKAN/NetKAN#1628]
Hello,
I'd like to request my mod called Antennas be added to CKAN.  The Mod can be found here https://kerbalstuff.com/mod/920/Antennas and depends on module manager to function.

Thank you.

**Comment by Dazpoet** [comment]
Your mod being added to KS automated a script which sent us a PR in #1618 so it'll be add as soon as we get to it :)

**Comment by plague006** [comment]
@dtphantom: Sorry it took so long, everyone's on a bit of a break from the project at the same time. =(
