### ISSUE TITLE
Modular Rocket Systems, "Lite" and normal versions should not be installed together.

### ISSUE THREAD

**Issue by NecroBones** [KSP-CKAN/NetKAN#1674]
The full version of MRS, and it's "Lite" counterpart should be treated as mutually exclusive, as one is a subset of the other, and they will interfere if both are installed concurrently. Is it possible to disallow installation of both, or at least throw a warning to the user if they try?

**Comment by dbent** [comment]
Mutual `conflicts` relationships added to each mod in the above PRs.
