### ISSUE TITLE
Firespitter version formatting

### ISSUE THREAD

**Issue by altyr** [KSP-CKAN/NetKAN#1675]
(I'm not sure if this is the right place for this bug)
In general, Firespitter packages appear to have a version string similar to "v7.1.1".
However in the 7.1.4 release the FirespitterCore package was labeled "7.1.4" instead of "v7.1.4". This leads to ckan not wanting to upgrade, probably due to "v" being larger than "7" when comparing the strings.

**Comment by pjf** [comment]
Nice spot! Fixing now! :)
