### ISSUE TITLE
KerbalHistoricalInstitute.netkan

### ISSUE THREAD

**Issue by BLSPBlackDeath** [KSP-CKAN/NetKAN#1684]
{
    "spec_version" : 1,
    "identifier"   : "KerbalHistoricalInstitute",
    "$kref"        : "#/ckan/kerbalstuff/309",
    "license" : "CC-BY-NC-4.0",
    "x_netkan_license_ok": true
}

**Comment by pjf** [comment]
Thank you! Added in #1696! :)
