### ISSUE TITLE
Automating overrides for trivial KSP updates

### ISSUE THREAD

**Issue by Murdabenne** [KSP-CKAN/NetKAN#1796]
My initial partially manual process

Given a mod name, basic algorithm is look at highest version CKAN file, make sure its checked for ksp 1.0.2, then create the branch with that name, use a sed script to add the override cod substituting in the version scraped off the CKAN file, build the result with netkan.exe, and if that's all clean, move the resultant CKAN file into a review directory just in case, then commit the changes to my local branch, and checkout the master, push the branch from local to my github fork

once that's done, I open the ckan file for review, if it looks sane, then I would do a test install, and then go to github and start the PR.  If there is an easy way to test the CKAN file then I could probably automate the whole thing.  This would allow iteration on a list of mods.

So in that usage, generate the list by finding all the mods that list compatibility with a specific version we are looking to override, and make the list from that, then iterate the override script on each of those mods. 

That way CKAN admins could automatically override something like the 1.0.3 to 1.0.4 safe patch for apps that are already at 1.0.3 - but not 1.0.2 -> 1.0.4 until the authors or forums agree its stable.  And in the event that bunches are trickling in, those could be batched to have the same thing done, maybe even have an automated way for authors to trigger an override via this script (maybe the indexing bot would detect something that would be a signal from the author to override)

Anyway, at least for hotfixes, it should help get a lot more mods available and "current" for users very quickly.

Initial chat: http://pastebin.com/G6BBRVek

**Comment by Murdabenne** [comment]
this can be done in a shell script.  Or if you want, perl or python.

**Comment by plague006** [comment]
Would you be interested in writing up a [wiki page](https://github.com/KSP-CKAN/CKAN/wiki/_new) with your code so that it's documented and easy to find?

**Comment by Murdabenne** [comment]
Sure, just need to get some time. Been a bit busy lately with my hospital
duties. Heat brings on heart attacks, and I'm in Texas and it's mid summer.

**Comment by plague006** [comment]
Everything can be solved by giving more NS =)

**Comment by plague006** [comment]
Closing this as https://github.com/KSP-CKAN/CKAN/pull/1499 should mostly address this.
