### ISSUE TITLE
Add MechJeb CI version

### ISSUE THREAD

**Issue by glek** [KSP-CKAN/NetKAN#1834]
MechJeb has a continuous integration server that runs new builds often. These builds are compiled against the latest KSP and thus are compatible (normally). It would be useful for those of us who like using the latest version of MechJeb and CKAN to have access to the CI version of MechJeb within CKAN.

Tagging @sarbian.

http://jenkins.mumech.com/job/MechJeb2/

**Comment by dbent** [comment]
This is already possible, instructions are in the [MechJeb thread](http://forum.kerbalspaceprogram.com/threads/124336):

```
CKAN has all the release of MechJeb.
If you want the dev version of MechJeb then :
- open CKAN settings (Settings => CKAN Settings)
- press the New button
- select the MechJeb-dev line, click OK and exit the options.
- refresh
- select "Mechjeb2 - DEV RELEASE" in the list and then "Go to Change" to install
```

Closing, feel free to reopen if that doesn't work for you.

**Comment by glek** [comment]
At this time, it's not working. I am unable to fetch the master list but I am able to refresh my current repositories and check for updates normally.

**Comment by techman83** [comment]
I know that the old jenkins stuff had jobs for inflating mechjeb meta data, but I never got a close look at them. You can see KSP-CKAN/CKAN#1247 for details about the issues.

If anyone knows what those build jobs were doing I'd absolutely love to know.

**Comment by hakan42** [comment]
The jobs basically cloned the NetKAN-dev repo, switched to the appropriate branch (check the "branches" dropdown on the github UI to see them), and called the build.sh from the main NetKAN repo. In the end, they are somewhat simple wrappers around the main NetKAN build.
