### ISSUE TITLE
Locking FAR/Realheat to specific MFI version

### ISSUE THREAD

**Issue by NathanKell** [KSP-CKAN/NetKAN#1863]
The current release of FAR, and the current release of RealHeat, both depend on MFI 1.0.
With MFI 1.1 released, they need to be locked to only install 1.0.

@sarbian an alternate solution is to release a 1.1.1 of MFI that has "1.0.0.0" as its version (since KSP will not load a plugin that references another dll where the loaded dll's version doesn't match the requested reference version, even if KSPAssembly version does match)--and unless the interfaces changed, that's certainly the cleanest solution since it would be good to have fixed-MFI with older mods.

**Comment by sarbian** [comment]
I changed the version thinking some mod may require code change but in the end none do. I'll push a 1.1.1

**Comment by plague006** [comment]
KSP-CKAN/CKAN-meta#688 seems to solve this.

**Comment by plague006** [comment]
Closing this since @sarbian provided a new MFI, let me know if there are any further issues. =)
