### ISSUE TITLE
adding Kerbal Planetary Surface Structures from KerbalStuff

### ISSUE THREAD

**Issue by Nils277** [KSP-CKAN/NetKAN#1888]
Hi,

can you please add my mod *Kerbal Planetary Surface Structures* to the repository.
It's hosted on KerbalStuff.

The file is here: https://www.dropbox.com/s/3ervyfqxpjgtza1/PlanetaryBaseInc.netkan?dl=0

Thanks in advance. :)

**Comment by plague006** [comment]
The license on the kerbalstuff page and the license files you've included in your .zip are not the same.

**Comment by Nils277** [comment]
Updated the files in the .zip, All licences should now be the same. Thanks and sorry for the inconvenience.

**Comment by plague006** [comment]
Thanks for the update. =)
