### ISSUE TITLE
FAR install error

### ISSUE THREAD

**Issue by TeddyDD** [KSP-CKAN/NetKAN#1897]
About to install...

 * FerramAerospaceResearch 1:v0.15.3.1 (cached)
 * ModularFlightIntegrator 1.1.1 (cached)

Continue? [Y/n] y

Installing mod "FerramAerospaceResearch 1:v0.15.3.1"
Could not find a part of the path "/home/teddy/.local/share/Steam/steamapps/common/Kerbal Space Program/Ships/@thumbs/SPH/FAR Blitzableiter.png".

**Comment by plague006** [comment]
I haven't had this issue.. but I could see it potentially being caused if you don't have a Ships/@thumbs directory before the installation. Was that the case?

**Comment by TeddyDD** [comment]
@plague006 Thanks that was the issue

**Comment by plague006** [comment]
Happy to help.
