### ISSUE TITLE
Fuel Tanks Plus dependecies, again.

### ISSUE THREAD

**Issue by NecroBones** [KSP-CKAN/NetKAN#1935]
I made a change to how the dependencies work for FTP. 

It needs one of either the Firespitter Core, or Interstellar Fuel Switch. Either will work, but Interstellar is more robust, and preferred. 

How should we update the dependencies to reflect this? If it can only have a single requirement, it would be better to use Interstellar, between the two. 

(ModuleManager is still required in any case).

**Comment by plague006** [comment]
For clarity, `InterstellarFuelSwitch-Core` is GameData\InterstellarFuelSwitch\Plugins\ while full `InterstellarFuelSwitch` includes a couple fuel tanks. Is `core` sufficient?

**Comment by Gustavo6046** [comment]
Kerbonite dependencies are also bugged: https://github.com/KSP-CKAN/NetKAN/issues/1939

**Comment by NecroBones** [comment]
Yes, the "Core" would be ideal. Thanks :)

**Comment by plague006** [comment]
You're all set. Depends `InterstellarFuelSwitch-Core`.

For what it's worth, there *is* a way to have "depend this or that" but in this case just having interstellar as a flat dependency is significantly easier and is less likely to generate tangential issues.

**Comment by NecroBones** [comment]
OK great. Sounds good to me. :)

**Comment by NecroBones** [comment]
Thanks!
