### ISSUE TITLE
Issues using MechJeb on newer versions.

### ISSUE THREAD

**Issue by Gustavo6046** [KSP-CKAN/NetKAN#1937]
We have many of them if you check the KerbalCurse's MechJeb2 mod page (http://www.curse.com/ksp-mods/kerbal/220221-mechjeb).

**Comment by plague006** [comment]
I'm not sure what you're saying the issue is. Can you be more specific?

**Comment by Gustavo6046** [comment]
The issues are those in the comments, at the main page of the mod's page in Curse. You should probably check it out and include them. One of them says, for example, the following:
"Spent the better part of my day trying to get two ships (stock station core and a pod) to dock, only to have the retarded autopilot get both witihn a meter of each other before causing both to spin out of control. Nice to know this bullshit mod hasn't been fixed even after two whole game updates, seeing as how I went through the trouble of downgrading back to 1.0.2. Surprise, shit still doesn't work, and it's probably fair to say it never will."

**Comment by plague006** [comment]
CKAN doesn't list user comments. CKAN also doesn't accept issues or bug reports relating to mod behaviour that isn't caused by faulty CKAN installs. For more up to date information the KSP forum thread for MechJeb2 is http://forum.kerbalspaceprogram.com/threads/124336-PART-1-0-4-Anatid-Robotics-MuMech-MechJeb-Autopilot-v2-5-3-%28July-6th%29

**Comment by Gustavo6046** [comment]
Okay, maybe I did not got the part of "bug reports relating to mod behavior that isn't caused by faulty CKAN installs" before.

**Comment by Gustavo6046** [comment]
Am I collaborator?

**Comment by Postremus** [comment]
No, you are not a collaborator.

2015-07-17 19:35 GMT+02:00 Gustavo6046 <notifications@github.com>:

**Comment by plague006** [comment]
CKAN installs mods. That's all it does. If it's not installing mods correctly then we want you to tell us about it. If you don't know how to use a mod, or if a mod has problems you need to contact the mod's author.

**Comment by Gustavo6046** [comment]
I leave the issue for the mod author. Thanks for hearing.
