### ISSUE TITLE
LaunchCountDown: no way to trigger the countdown

### ISSUE THREAD

**Issue by Gustavo6046** [KSP-CKAN/NetKAN#1938]
It comes with no documentation and I found problems where the count down doesn't happens. Can it be a conflict with MechJeb's target rendezvous window count down? I haven't been doing many manual launches ultimately... mainly because I need to play more KSP now. :8ball:

**Comment by plague006** [comment]
The forum page for Launch CountDown is http://forum.kerbalspaceprogram.com/threads/42859

It gives instructions for MechJeb use with it, if there are complications between the two mod's functions you should inform their respective authors. From what I can see, CKAN is accurately installing both mods, but if it's not installing them properly for you let us know.

**Comment by Gustavo6046** [comment]
Oh  thanks. I forgot to put the clamps :D (embarassed)
