### ISSUE TITLE
Missing Kethane on 1.0 but not Kerbonite

### ISSUE THREAD

**Issue by Gustavo6046** [KSP-CKAN/NetKAN#1939]
The Kerbonite mod is suposed to work with Kethane, it appears in 1.0 but Kethane not, when searching for CKAN compatible mods.

**Comment by plague006** [comment]
We'll be happy to update Kethane once there's a new release. Presently we index Kethane v0.9.2 which is the most recent release. There's a patch available to use Kethane with 1.0.2 but as a general rule CKAN doesn't index patches.

**Comment by Gustavo6046** [comment]
I mean only 1.0.0 girl!

**Comment by plague006** [comment]
What?

**Comment by Gustavo6046** [comment]
I mean that I play KSP in 1.0.0, and there is no Kethane for 1.0.0, only for 1.0.2 and later. Even then Kerbonite just appears in 1.0.0 CKAN compatibles list, even though the dependency Kethane isn't!

**Comment by plague006** [comment]
Karbonite does not depend on Kethane. Karbonite is an alternative to Kethane.
http://forum.kerbalspaceprogram.com/threads/89401

**Comment by Gustavo6046** [comment]
Oh thanks. That clarify all.

"So much decision power you have made me decide you're male." - forget that :white_check_mark:

**Comment by Gustavo6046** [comment]
But CKAN says Karbonite depends on Kethane, thus I can't install Karbonite in CKAN!

**Comment by plague006** [comment]
What version of Karbonite are you trying to install?

**Comment by Gustavo6046** [comment]
But CKAN says Karbonite depends on Kethane, thus I can't install Karbonite in CKAN!
Karbonite 1.0.0.

**Comment by plague006** [comment]
There is not a single mod in all of CKAN that depends on Kethane. https://github.com/KSP-CKAN/CKAN-meta/search?utf8=%E2%9C%93&q=kethane

AGExt `supports` Kethane.
Extraplanetary-Launchpads `recommends` Kethane.

No mod `depends` Kethane.

**Comment by Gustavo6046** [comment]
In my CKAN Karbonite depends Kethane.

**Comment by plague006** [comment]
Maybe you have very old metadata? Press refresh, make sure you have the most recent version of CKAN.

**Comment by Gustavo6046** [comment]
Wait, I was saying about KarbonitePlus! And Karbonite don't appear to have an 1.0.0 version, unlike Karbonite.
That confused me until I checked CKAN. I confused Karbonite - KarbonitePlus with Kethane - Karbonite. Wow!

**Comment by plague006** [comment]
So you're trying to install `KarbonitePlus` and it's failing to give you `Karbonite`?

**Comment by plague006** [comment]
Are you able to install `Karbonite` on its own?

**Comment by Gustavo6046** [comment]
No, I can't install Karbonite on its own because it won't appear in the compatible mods list. Yes, I am "trying to install KarbonitePlus and it's failing to give [me] Karbonite".

**Comment by plague006** [comment]
While there was a `Karbonite` available for 1.0.0, we cannot meet `Karbonite`'s dependency on `FirespitterCore` because there was no release for 1.0.0. There were only 5 days between the releases of KSP 1.0.0 and 1.0.2 and in that span of time `Firespitter` did not have a release.

In other words, without a `Firespitter`, there's no `FirespitterCore`, which means no `Karbonite`, which means no `KarbonitePlus`.

For the release list for `Firespitter` see: https://github.com/snjo/Firespitter/releases

**Comment by Gustavo6046** [comment]
I can make the 1.0.0 version, I am downloading the source code. It is my first time I mess with CKAN files and such, but believe me. I'll do a pull request when I compatibilize it!

**Comment by plague006** [comment]
Closing this, as it's not a CKAN issue. We'll index the Firespitter release once it's on https://github.com/snjo/Firespitter/releases

**Comment by Gustavo6046** [comment]
The project is in https://github.com/Gustavo6046/FireSpitter-1.0.0/tree/master anyone contributing to it. We will later do a pull request to the original Firespitter.

**Comment by BobPalmer** [comment]
A few things.  First - I will absolutely not take a pull request for FireSpitter to go back to 1.0.0.  Second, you're in violation of the FireSpitter license - so to CKAN folks, please be aware that any attempt by Gustavo6046 to add FireSpitter stuff to CKAN is unauthorized.  Third.  There is no Karbonite release for 1.0.0 - again, any attempt to CKAN this is just muddying the waters - Karbonite is a 1.0.2+ mod (soon to be 1.0.4).  Lastly.  Karbonite has as much to do with Kethane as Ham does with Hamsters.

**Comment by plague006** [comment]
@BobPalmer: Don't worry, we CKAN people are sensible. @Gustavo6046 is either a troll or very odd/misinformed and nothing he says is regarded with any degree of seriousness.

When I saw https://github.com/snjo/Firespitter/pull/122 I had a chuckle, knowing it would (and should) be closed. His OP in https://github.com/KSP-CKAN/CKAN/issues/1314 was also particularly weird/funny.

**Comment by Gustavo6046** [comment]
Well you admited the reason and the fault, "nothing [me] says is regarded with any degree of seriousness by the CKAN team." I just wish to play KerbonitePlus in 1.0.0 since it seems K+ is for some reason avaiable in 1.0.0. Whatever, I am misinformed either, I am a bit lazy to check in the forums (that's why I use CKAN ;) ) so let's not feel much. I can live without it.
Know that LPIP? I could carry a entire plugin with only a single .lpf file! I only needed LPIP to install the file into the gamedata. And the file was keeped, so that I could install twice, and carry it without needing temporary copies or multiple downloads!
