### ISSUE TITLE
Fuel Tanks Plus not updating

### ISSUE THREAD

**Issue by NecroBones** [KSP-CKAN/NetKAN#1944]
I see other mod versions updating, but yesterday's releases of Fuel Tanks Plus don't seem to be appearing. Is there anything I need to do? Thanks,

**Comment by plague006** [comment]
Thanks for pointing it out, Outer Planets Mod is undergoing the same issue. Netkan-bot isn't pushing them through and at the moment we can't verify why. I just created https://github.com/KSP-CKAN/CKAN-meta/issues/713 to see why the bot isn't doing its thing, and I'll manually PR the metadata changes required shortly.

**Comment by NecroBones** [comment]
OK great, thanks. I'm about to push out a new version too (1.0.3). Since it was such a large overhaul, we're rapidly finding small things to fix.

**Comment by NecroBones** [comment]
OK, I just posted 1.0.3, so that's good to go. Will CKAN properly filter out the "InterstellarFuelSwitch" folder? I'm including it in the zip now, since the dependency is confusing non-CKAN people.

**Comment by plague006** [comment]
Lol I pushed https://github.com/KSP-CKAN/CKAN-meta/commit/a72c88f5329512ce268a61d58b104a29ef326ed5 just seconds ago. I'll look at 1.0.3 now.

**Comment by NecroBones** [comment]
Lol, great timing :)

**Comment by plague006** [comment]
1.0.3 is up -- CKAN won't have any problems with your releases as long as the `FuelTanksPlus` folder isn't renamed or moved. It ignores everything but that folder.

**Comment by NecroBones** [comment]
OK perfect. Thanks!

**Comment by plague006** [comment]
Closing this, the overall issue (mods not updating) is in https://github.com/KSP-CKAN/CKAN-meta/issues/713
