### ISSUE TITLE
RealFuels and InterstellarFuelSwitch

### ISSUE THREAD

**Issue by NathanKell** [KSP-CKAN/NetKAN#1976]
Update to  #1579 and other issues re: incompatibility.

After talking with FreeThinker, we figured out a good approach is for RF to just nuke any IFS modules on parts that also have RF/MFT fuel tank modules (on :FINAL). I suggest @taniwha-qf do the same in MFT.

Therefore by next release, RF should no longer be incompatible with IFS, and vice versa.

**Comment by plague006** [comment]
Thanks for the heads up. As soon as #1979 is merged things should be set between RF and IFS.
