### ISSUE TITLE
RP-0 versioning

### ISSUE THREAD

**Issue by NathanKell** [KSP-CKAN/NetKAN#2016]
We include a .version file now, but that overrides the tag-set versioning that netkan used to use, so the override is no longer valid, and 0.0.34 is treated as older than v0.33. Wut do?

I manually updated the .ckan for 0.0.34 to be for 1.0.4, but I'm not sure if the next netkan pass won't rebuild it anyway, and we'll be back to 90...

**Comment by techman83** [comment]
Looking at that, an epoch is likely the required thing.

**Comment by techman83** [comment]
Yeah the bot did blat it. The download link has RP-0-v0.34 as the version. So the version file would be 0.34.0 to match, however it'd still need a ```"x_netkan_force_v": true``` to get it to work.

Playing around with the version file and adding the force v does produce the desired result. Let us know how you wish to handle it and it can be sorted out easy enough :-)

**Comment by plague006** [comment]
Related: https://github.com/KSP-CKAN/CKAN/pull/1299

**Comment by NathanKell** [comment]
I'm fine with whatever way is easiest for you all. I'm away from home and can't dig in properly, so I'm willing to go with whatever. :)

**Comment by NathanKell** [comment]
For now I'm yanking the .version and manually setting KSP version.

**Comment by plague006** [comment]
With KSP-CKAN/CKAN#1299 merged, you can restore the .version file.

**Comment by plague006** [comment]
With my comment on Aug 11, there's not really anything further in this issue. 9aef77f can be reverted if there's a .version file, otherwise it's fine as is.
