### ISSUE TITLE
adding SentarExpansion

### ISSUE THREAD

**Issue by Borisbee1** [KSP-CKAN/NetKAN#2023]
Here is the .netkan file.

https://www.dropbox.com/s/oqfea4pmo20e9nz/SentarExpansion.netkan?dl=0

**Comment by plague006** [comment]
Are the cache folders intentionally installed or are those files extraneous?

**Comment by Borisbee1** [comment]
Intentional.

**Comment by plague006** [comment]
Ty. Netkan is merged in #2035 and will be live for end-users within 3 hours.
