### ISSUE TITLE
NetKAN/TACLSMining.netkan - showing as incompatible in 1.0.4 despite presence of override

### ISSUE THREAD

**Issue by draeath** [KSP-CKAN/NetKAN#2076]
TACLSMining shows as incompatible in GUI for KSP 1.0.4. .netkan overrides for version show support for 1.0.2 through 1.0.4.

I compared this one to a few other working mods, and I can't spot an obvious difference. The only thing I can suspect is '"x_netkan_epoch" : "1",' on [line 11 of NetKAN/TACLSMining.netkan](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/TACLSMining.netkan#L11)

**Comment by plague006** [comment]
Thanks for spotting that, the epoch bump changes the version number and negates the override. It's happened a couple times, it's a weird interaction.
