### ISSUE TITLE
Fuel Tanks Plus and Color Coded Canisters feature integration

### ISSUE THREAD

**Issue by NecroBones** [KSP-CKAN/NetKAN#2100]
Both of the mods "Fuel Tanks Plus" and "Color Coded Canisters" now (optionally) cooperate with each other for color-switching. They work independently, but to get the most out of them, they should be installed together. They should probably have a "suggest" or "recommend" rule, in both directions. 

Am I right in assuming that "recommend" is stronger than "suggest" (like a default "yes", or something)? If there's a difference between the two, I would probably do this:

FTP "suggests" CCC (for a more consistent art style)
CCC "recommends" FTP (since it has an optional feature that requires FTP)

**Comment by plague006** [comment]
>Am I right in assuming that "recommend" is stronger than "suggest" (like a default "yes", or something)?

Exactly right, recommends are default yes while suggests are default no.

**Comment by NecroBones** [comment]
Perfect, thanks.
