### ISSUE TITLE
Can't use netkan.exe

### ISSUE THREAD

**Issue by ArnePeirs** [KSP-CKAN/NetKAN#2133]
I made a .netkan file using the wiki and came to the point that you need to download the netkan.exe to create a .ckan file. So I downloaded the exe and runned it (double clicked it). It starts up shows two lines in the command window and then it closes itself directly. I can't even read the two lines that are shown.

I don't know if this is the purpose of it, but i guess not as the wiki says to type
`netkan.exe --verbose <identifier>.netkan`

**Comment by Dazpoet** [comment]
You don't start the netkan.exe by doubleclicking it :) From a commandline prompt (cmd.exe) you need to be in the folder where netkan.exe is located and then run the command `netkan.exe --verbose path/to/<identifier>.netkan`

**Comment by ArnePeirs** [comment]
That worked, thx
