### ISSUE TITLE
Is Kerbalstuff or Github preferred?

### ISSUE THREAD

**Issue by ABZB** [KSP-CKAN/NetKAN#2170]
I just uploaded one of my mods, which is already on Kerbalstuff, to Github, to make updating it easier. Is it preferable to switch CKAN to grab the Github release, or leave it pulling it from Kerbalstuff?

**Comment by plague006** [comment]
KerbalStuff gives us more information through scraping. We can get the mod's name, the abstract, the ksp_version compatibility, and a couple other pieces of info that GitHub doesn't provide. So unless the KS page will be out of date, it is the preferred location to have CKAN point to.

**Comment by plague006** [comment]
Closing this issue, if you have further questions I'll happily reply/reopen the issue as needed.
