### ISSUE TITLE
Nanogauges works in 1.0.4

### ISSUE THREAD

**Issue by damerell** [KSP-CKAN/NetKAN#2218]
I hope this is still the right place to report this. The NanoGauges mod is restricted to 1.0.2 (kerbalstuff thinks it doesn't work in 1.0.4) but in practice it appears to work fine - one or two of the gauges may be confused by new stock heat, but it's still very useful.

**Comment by plague006** [comment]
Absolutely the right place, thanks for giving us a heads up.
