### ISSUE TITLE
SpaceY Expanded (expansion for SpaceY Lifters) dependencies

### ISSUE THREAD

**Issue by NecroBones** [KSP-CKAN/NetKAN#2247]
I just launched an alpha for the expansion pack for SpaceY. Since it's a separate, optional add-on, it has some dependencies. It should require:

Module Manager
SpaceY Heavy Lifters

And it should recommend (default yes):

Interstellar Fuel Switch

Thanks! :)

**Comment by NecroBones** [comment]
Oh also, I think we should add a return suggestion, that SpaceY Lifters should suggest (default no) SpaceY Expanded.

**Comment by NecroBones** [comment]
Looks like it's still not showing up in CKAN, btw. The referenced merge still shows a failure.

**Comment by plague006** [comment]
Closed with #2271
