### ISSUE TITLE
Scatterer version issue

### ISSUE THREAD

**Issue by TeddyDD** [KSP-CKAN/NetKAN#2260]
CKAN install v0.0171 while newest version is  v0.0175.
.ckan is available so its some kind of version issue. I don't know how to fix this :disappointed:

**Comment by plague006** [comment]
I have v0.0175 showing in CKAN. Is it showing 1 thing and installing another?

**Comment by TeddyDD** [comment]
It were showing and installing v0.0171 (tested on two KSP installations) but now it seems to work OK. Weird. I suppose I can close it now.
