### ISSUE TITLE
Kopernicus planet/star/galaxy packs

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/NetKAN#2292]
There are a bunch of mods yet to be added to CKAN to add planets and stars using the Kopernicus framework. Should we think about handling them similarly to ContractConfigurator? It would make things much easier for users.

There are also at least two mods in development that use the Kopernicus framework to create galaxies with entire star systems - [Kerbal Galaxy 2] (http://forum.kerbalspaceprogram.com/threads/125078) and [Galactic Neighborhood] (http://forum.kerbalspaceprogram.com/threads/128856), which will conflict with each other. Galactic Neighborhood at least is designed to allow adding of extra Stars and planets to fit into the Galaxy. The Provides and Conflicts are going to need to be worked out, and if we can get on top of it early, we might be able to convince the mod authors to use a framework of some kind.

**Comment by Olympic1** [comment]
I'm working on this in KSP-CKAN/CKAN-meta/issues/588

**Comment by Olympic1** [comment]
Closing as this process is started. You can follow the progress further on KSP-CKAN/CKAN-meta#588
