### ISSUE TITLE
NAS - Naval Artillery System

### ISSUE THREAD

**Issue by zzhwudiaa** [KSP-CKAN/NetKAN#2299]
An addon of BDArmory, providing a set of WWII naval weapon replicas.
This is the author, whose forum ID is Acea, and this addon is now active.
http://forum.kerbalspaceprogram.com/threads/131605

**Comment by zzhwudiaa** [comment]
https://github.com/zzhwudiaa/NAS/raw/master/NAS.netkan

**Comment by plague006** [comment]
Closed in  #2300
