### ISSUE TITLE
Proposal: Retarget Hangar Extender

### ISSUE THREAD

**Issue by NathanKell** [KSP-CKAN/NetKAN#2310]
Since Alewx's fork is currently being updated, and Snjo's master hasn't been in a while, should CKAN maybe target the fork?
https://github.com/Alewx/FShangarExtender/releases/

**Comment by plague006** [comment]
Changing targets currently wouldn't be beneficial as the releases in the repo you linked are all .rar

If releases were changed to .zip I would be +1 for the change.

**Comment by NathanKell** [comment]
@Alewx has added zip downloads on github:
https://github.com/Alewx/FShangarExtender/releases/

**Comment by Alewx** [comment]
Actually I made a new release with Zip
https://github.com/Alewx/FShangarExtender/releases/tag/v3.4.5

**Comment by NathanKell** [comment]
Poke

**Comment by Alewx** [comment]
Anything I need to do?

**Comment by NathanKell** [comment]
@plague006 while you're around, poke? :)

**Comment by plague006** [comment]
http://puu.sh/kUg8M/b112bcb5fb.png those timestamps.

**Comment by NathanKell** [comment]
:D I saw you respond to the RP-0 versioning thing and figured I might as well poke. ^_^
