### ISSUE TITLE
Pathfinder-USILS-CommunityPatch.netkan merged, but not showing up

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#2359]
This was merged at the same time as the Pathfinder-RemotetechPatch was merged.

The remotetech one is visible in ckan, but this one is not, even when I filter all

**Comment by Olympic1** [comment]
It is visible in at my pc

**Comment by Olympic1** [comment]
netkanbot just added it to ckan

**Comment by linuxgurugamer** [comment]
Ok, I'm now seeing it myself.

This can be closed.


Thanks for checking


JBB
