### ISSUE TITLE
The netkan bot won't pick up multple releases if they are released too close to each other

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/NetKAN#236]
The bot refreshes the index about once an hour. However, it seems to assume that only one release has appeared since the last update.

Case study: we missed a FAR release. If you look at the changelog on kerbalstuff, there is a v0.14.4.1 release that hasn't been indexed by the bot. This is because ferram4 has released v0.14.4.1 and v0.14.5 within minutes of each other and the bot only picked up the latest one, ignoring the other one.

Poking @pjf and @AlexanderDzhoganov : we might want to improve the bot's detection of new releases.

**Comment by AlexanderDzhoganov** [comment]
This should be in CKAN-netkan, could you move it?

**Comment by hakan42** [comment]
This issue was moved to KSP-CKAN/CKAN-netkan#23

**Comment by pjf** [comment]
and unmoved. :)

**Comment by Dazpoet** [comment]
I think this is acctually for NetKAN-bot rather than this directory, notifying @techman83 who is either interested enough to open a duplicate over there or close this :)

**Comment by techman83** [comment]
I'm hoping KSP-CKAN/NetKAN-bot#2 will help this. Currently NetKAN grabs the latest release and pushes it into CKAN-meta and that only happens every 3 hours currently (due to cpu utilisation).

How common is this situation? What are we missing by missing a release if a new one was released soon after (presumably it would most commonly done to fix a futzed release?).

**Comment by Dazpoet** [comment]
Not sure how big of a problem this really is acctually, I can't say I've ever ran into a problem because of this.

For the completionist in all of us it would be nice to have an as complete repository as possible though which should include all versions, no matter how insignificant.

**Comment by plague006** [comment]
@techman83 if this can't be (reasonably) fixed, can we close the issue?

**Comment by techman83** [comment]
@plague006 generally if releases are really close together it probably means a bug and we'll likely miss the buggy one. So it's probably pretty edge case.

There is room in the code for more frequent indexing and we'll get there eventually. So I think yes :+1:
