### ISSUE TITLE
Can you delete the netkan for Pathfinder-Antennarange

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#2367]
The author has included this in the mod, so this isn't needed anymore

**Comment by plague006** [comment]
Deleting the netkan will not de-list the mod, but will simply stop new versions of the mod from being indexed. With that said, I'll change the abstract in an attempt to stop people from installing the mod.

**Comment by linuxgurugamer** [comment]
thanks.

What would happen if I deleted the Kerbalstuff entry?

**Comment by plague006** [comment]
People would be unable to download the mod (which is fine), but de-listing it from CKAN would cause issues for end users who already have it installed.
