### ISSUE TITLE
Deltaglider

### ISSUE THREAD

**Issue by RacerXx** [KSP-CKAN/NetKAN#2374]
{
    "spec_version" : 1,
    "identifier"   : "Deltaglider",
    "$kref"        : "#/ckan/kerbalstuff/1165",
    "license"      : "CC-BY-NC-ND",
    "depends" : [
        { "name" : "ModuleManager" } ,
        { "name" : "ASETProps" },
        { "name" : "AGExt" },
        { "name" : "RasterPropMonitor" },
        { "name" : "RasterPropMonitor-Core" },
        { "name" : "KAS" },
        { "name" : "KIS" },
        { "name" : "ShipManifest" },
        { "name" : "ThrottleControlledAvionics" },
        { "name" : "Toolbar" },
        { "name" : "TMSTACLSRetexture" },
        { "name" : "VesselViewer"},
        { "name" : "SCANsat" },
    ]
}

**Comment by plague006** [comment]
Deltaglider.netkan [already exists](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/Deltaglider.netkan) and you wrote it. Are you saying you want something changed?

**Comment by RacerXx** [comment]
the file was uploaded to kerbalstuff updated to v0.3. There really needs to be a video tutorial on this for mod makers

**Comment by RacerXx** [comment]
[quote from the instructions under SUBMITTING on github instructions] 
If you've got everything working, then open an issue on the NetKAN and include a copy of the .netkan! 
[/quote]

**Comment by plague006** [comment]
You only ever need to submit 1 netkan for a mod, after that @netkan-bot will generate all .ckan files for newer versions of the mod. The netkan only needs to be updated when dependencies or the install method changes from one version to the next. See #2375 for more information on the specifics of the problem with Deltaglider.
