### ISSUE TITLE
Deltaglider 

### ISSUE THREAD

**Issue by RacerXx** [KSP-CKAN/NetKAN#2375]
{
    "spec_version": 1,
    "identifier": "Deltaglider",
    "name": "Deltaglider XR-1 for KSP",
    "abstract": "A variant of Orbiter space flight simulator Deltaglider and Altea Aerospace Deltaglider XR-1 Thanks to Dr. Martin Schweiger,Doug Beachy,Frying Tiger for permission and use of meshes and textures ",
    "author": "Redneck",
    "license": "CC-BY-NC-ND",
    "resources": {
        "homepage": "http://forum.kerbalspaceprogram.com/threads/130783-WIP-Deltaglider-XR-1",
        "kerbalstuff": "https://kerbalstuff.com/mod/1165/Deltaglider%20XR-1%20for%20KSP",
        "x_screenshot": "https://kerbalstuff.com/content/Redneck_14905/Deltaglider_XR-1_for_KSP/Deltaglider_XR-1_for_KSP-1442889113.8541472.png"
    },
    "version": "Version_Work_In_Progress_V0.3",
    "ksp_version": "1.0.4",
    "depends": [
        {
            "name": "ModuleManager"
        },
        {
            "name": "ASETProps"
        },
        {
            "name": "AGExt"
        },
        {
            "name": "RasterPropMonitor"
        },
        {
            "name": "RasterPropMonitor-Core"
        },
        {
            "name": "KAS"
        },
        {
            "name": "KIS"
        },
        {
            "name": "ShipManifest"
        },
        {
            "name": "ThrottleControlledAvionics"
        },
        {
            "name": "Toolbar"
        },
        {
            "name": "TMSTACLSRetexture"
        },
        {
            "name": "VesselViewer"
        },
        {
            "name": "SCANsat"
        }
    ],
    "download": "https://kerbalstuff.com/mod/1165/Deltaglider%20XR-1%20for%20KSP/download/Version_Work_In_Progress_V0.3",
    "download_size": 20172369,
    "x_generated_by": "netkan"
}

**Comment by plague006** [comment]
I'm not sure what you're posting. It's a .ckan generated by netkan, but I have no idea what you're trying to say.

**Comment by RacerXx** [comment]
i have no idea either..trying to update the mod to version 0.3

**Comment by plague006** [comment]
Ah yeah I see the issue. For version 0.2 you named the version `Work_In_Progress_V0.2` while version 0.3 versioned as `Version_Work_In_Progress_V0.3`. CKAN is of course just a machine so interprets versions in a machine way, according to it the "W" in "Work" is greater than the "V" in "Version", so while 0.3 [is indexed](https://github.com/KSP-CKAN/CKAN-meta/blob/master/Deltaglider/Deltaglider-Version_Work_In_Progress_V0.3.ckan) according to the version name it's an earlier version.

At any rate, #2378 will address the issue.

**Comment by RacerXx** [comment]
so what if I delete WIP v0.3 and just re upload and set it to v0.3? Will that be better?

**Comment by plague006** [comment]
That would avoid the issue in the future, which would be nice.

**Comment by RacerXx** [comment]
new zip uploaded to kerbal stuff and set to v0.3 on the page and not WIPv0.3 re ran the command
netkan.exe --verbose Deltaglider.netkan

**Comment by RacerXx** [comment]
There is an issue with the zip file being corrupted and kerbal stuff says they already have this version after I have deleted that version from kerbal stuff

**Comment by RacerXx** [comment]
hello anybody around? this is day 2 trying to get this thing on CKAN. I need some help here!

**Comment by plague006** [comment]
Don't know about v0.3, but v0.4 isn't corrupt and passes local tests.

**Comment by RacerXx** [comment]
when can we expect to see the mod on CKAN?Date: Sun, 4 Oct 2015 10:13:40 -0700

**Comment by plague006** [comment]
d2959204702cc7a75510087fe043c9af3f148799
