### ISSUE TITLE
Sigma OPM Expansion split

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/NetKAN#2382]
Via @Sigma88 https://github.com/KSP-CKAN/NetKAN/pull/1533#issuecomment-145795408

So,
the 3 mods that were originally part of "Sigma OPM Expansion" are now released separately

these are the links to the forum threads and github repositories

Sigma: OPM Recolor
http://forum.kerbalspaceprogram.com/threads/135895
https://github.com/Sigma88/Sigma-OPMRecolor

Sigma: OPM Tilt
http://forum.kerbalspaceprogram.com/threads/135899
https://github.com/Sigma88/Sigma-OPMTilt

Sigma: PluronKhato
http://forum.kerbalspaceprogram.com/threads/135881
https://github.com/Sigma88/Sigma-PluronKhato

the last one is now a standalone mod, it doesn't require OPM.

**Comment by Sigma88** [comment]
@plague006  the moving around of all my mods is completed!

you can find all the links to the new threads here:

http://forum.kerbalspaceprogram.com/threads/112095

**Comment by plague006** [comment]
Thanks for the heads up.

**Comment by plague006** [comment]
Took a bit of time, but I created a PR that should solve things.

**Comment by Sigma88** [comment]
:+1:  Thanks, I'm going to check it out as soon as I get some time
