### ISSUE TITLE
[PSA] How to force a Jenkins rebuild.

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/NetKAN#2390]
I noticed in https://github.com/KSP-CKAN/NetKAN/pull/2383 that if you close and re-open a PR it forces a rebuild. Faster, easier, and cleaner than forcing an unnecessary commit.

**Comment by qm3ster** [comment]
Damn, I am awesome.
(In all seriousness, my left click is destroyed, and it happened unintentionally)

**Comment by Postremus** [comment]
Nice finding! 

----- Ursprüngliche Nachricht -----
Von: "Mihal Malostanidis" <notifications@github.com>
Gesendet: ‎08.‎10.‎2015 10:33
An: "KSP-CKAN/NetKAN" <NetKAN@noreply.github.com>
Betreff: Re: [NetKAN] [PSA] How to force a Jenkins rebuild. (#2390)

Damn, I am awesome.
(In all seriousness, my left click is destroyed, and it happened unintentionally)
