### ISSUE TITLE
Request to add GPWS mod to ckan

### ISSUE THREAD

**Issue by CommanderJohnKoenig** [KSP-CKAN/NetKAN#2406]
mod is [WIP][1.0.4]GPWS - Warning System for Planes - 2015-08-22.  It is posted on GitHub. I hope this is all you need to add it to ckan for KSP.

        Thanks in advance.

**Comment by CommanderJohnKoenig** [comment]
I think there may be a misunderstanding.  The mod I mentioned is a mod for adding an in flight warning system for planes and to some extent to other craft getting close to the ground.  It also does altitude call outs up to 1000 feet above surface.  The mod is [WIP][1.0.4]GPWS - Warning System for Planes - 2015-08-22.  The mod maker is bssthu.  His Github source page  is https://github.com/bssthu/KSP_GPWS.  It is apparently set up for Linux but he has simple instructions for use on windows.  Sorry if my request was done incorrectly.  I hope this helps.

**Comment by pacbard** [comment]
I really don't know how that happened. I don't remember referencing this issue in my previous pull request.

Anyhow, I created the pull request for GPWS.

**Comment by CommanderJohnKoenig** [comment]
Thank you for doing that and getting to it so quickly.  Much appreciated.
