### ISSUE TITLE
Request: [1.0.2] NavUtilities, ft. HSI & Instrument Landing System v0.5.1 RC 1 *June 2015*

### ISSUE THREAD

**Issue by CommanderJohnKoenig** [KSP-CKAN/NetKAN#2416]
This is a mod by kujuman and is listed on kerbalstuff and has a GitHub listing for source.  The version states 1.0.2 but does seem to work.  I understand that the GPWS is not in release state so this would be a slight alternative with a landing aid.  It also has functionality with Rastorprop.

**Comment by plague006** [comment]
>The version states 1.0.2 but does seem to work.

You mean it works with 1.0.4? I had a look at the forum thread and I'm assuming that's what you mean.
