### ISSUE TITLE
Jenkins not properly installing multiple .ckans

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/NetKAN#2496]
In PRs with multiple changed files Jenkins is accurately testing the .netkans separately which is great, but where it should be testing the installation of multiple .ckans it's actually just running the same one multiple times. See any PR with multiple changed files to see the behaviour. #2495 #2482 

IMO this is a low priority issue as 99% of errors are picked up by testing the netkans, but it's nice to have the file tree visible to see if anything is wrong.

**Comment by techman83** [comment]
See KSP-CKAN/CKAN#1479 - only appears to affect NetKAN and not CKAN-meta.

I'll take a look after Pax.

**Comment by plague006** [comment]
Ah right, I thought we had an issue about it. Closing as a duplicate.
