### ISSUE TITLE
EnvironmentalVisualEnhancements Packages Need Revision

### ISSUE THREAD

**Issue by toadicus** [KSP-CKAN/NetKAN#2550]
rbray89 has released the overhauled EVE!  This is very exciting, but CKAN can't handle it quite yet.

Forum thread regarding the release: http://forum.kerbalspaceprogram.com/threads/55905

github release: https://github.com/rbray89/EnvironmentalVisualEnhancements/releases/tag/EVE-1.05-1

The NetKAN file for EVE-HR caught it and updated, but probably wouldn't work even if it could be installed correctly (which hopefully it can't be).  The packaging these days comes in two parts:

x86-Configs-Release.zip -- configs and textures; currently not offered in high and low res; presumably will share an install slot with similar packs from Astronomer et al

x86-EVE-Release.zip -- core plugin

I took a look at the EVE NetKAN files, but the $kref stuff for github asset detection is a bit above my paygrade.

TIA!

**Comment by Olympic1** [comment]
@toadicus, is the latest version only compatible with KSP 1.0.5, or can it be uses in earlier version too?

**Comment by rbray89** [comment]
I'm afraid I haven't tried the binaries on KSP 1.0.4. I see no reason why it shouldn't work (aside from possibly requiring a recompile).
