### ISSUE TITLE
KW Rocketry Community Fixes & KW Rocketry Community Fixes - Interstage Config

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#2580]
I updated the community fixes earlier today.  I see in CKAN that the Interstage config is available for 1.0.5, but the basic Community Fixes is not;  they are both the same file

**Comment by TeddyDD** [comment]
KWRocketry depends on ModuleAnimateEmissive. When I tried to install KW via ```ckan install -c KWRocketry-2.7.0-community.ckan``` output was 

```
1893 [1] ERROR CKAN.RelationshipResolver (null) - Dependency on ModuleAnimateEmissive found, but nothing provides it.
Module ModuleAnimateEmissive required, but not listed in index, or not available for your version of KSP
If you're lucky, you can do a `ckan update` and try again.
Try `ckan install --no-recommends` to skip installation of recommended modules
```
There is newest ModuleAnimateEmissive version in ckan (v1.11) but it's marked as compatible with KSP 1.0.4 So I suppose this need to be updated.

 Alternatively If you sure that KW works in 1.0.5 I can mark ModuleAnimateEmissive v1.11 and KWRocketry-2.7.0-community.ckan as compatible with 1.0.5

**Comment by Olympic1** [comment]
> I updated the community fixes earlier today. I see in CKAN that the Interstage config is available for 1.0.5, but the basic Community Fixes is not; they are both the same file.

Our bot updated both files to v0.4.0 ([`4d476ca`](https://github.com/KSP-CKAN/CKAN-meta/commit/4d476cabc50ba5551838a3460919c6407451e73c) and [`a1df3f2`](https://github.com/KSP-CKAN/CKAN-meta/commit/a1df3f2fea505e32b65a9b740675609a452ca0ca)) so I'll need to look into that.

> There is newest ModuleAnimateEmissive version in ckan (v1.11) but it's marked as compatible with KSP 1.0.4 So I suppose this need to be updated.

afaik, v1.11 doesn't work 100% in 1.0.5, they are working on bringing an update.

**Comment by linuxgurugamer** [comment]
The Community Patches replace the ModuleAnimateEmissive with FXModuleAnimateThrottle.  It doesn't depend on the ModuleAnimateEmissive anymore

**Comment by linuxgurugamer** [comment]
I don't know what changed, but it looks like it's fixed.  At least for me, when I refresh CKAN, it seemed to load ok

**Comment by Olympic1** [comment]
Loads for me too

**Comment by linuxgurugamer** [comment]
Did anybody do anything?


JBB

**Comment by Olympic1** [comment]
No, they just needed some time to show up.
