### ISSUE TITLE
AstronomersVisualPack

### ISSUE THREAD

**Issue by Olympic1** [KSP-CKAN/NetKAN#2609]
Restrict the AVP versions from Astronomer to `1.0.4` as these use the old EVE. Add the `Reboot` versions of AVP that are compatible with the new EVE. These are made by another author though, so I'll add his name. I think it would be best if we just changed the download link to the new KS page of the `Reboot` version.

* [ ] `AstronomersPack-PlanetShine`
* [ ] `AstronomersPack-Snow`
* [ ] `AstronomersPack-SurfaceGlow`
* [ ] `AstronomersPack-AtmosphericScattering`
* [ ] `AstronomersPack-DistantObjectEnhancement`
* [ ] `AstronomersPack-Eve-Jool-Clouds-2K`
* [ ] `AstronomersPack-Eve-Jool-Clouds-4K`
* [ ] `AstronomersPack-Eve-Jool-Clouds-8K`
* [ ] `AstronomersPack-Sandstorms`
* [ ] `AstronomersPack-Lightning`
* [ ] `AstronomersPack`
* [ ] `AstronomersPack-Auroras-4K`
* [ ] `AstronomersPack-Auroras-8K`
* [ ] `AstronomersPack-Clouds-High`
* [ ] `AstronomersPack-Clouds-Low`
* [ ] `AstronomersPack-Clouds-Medium`

**Comment by Olympic1** [comment]
On hold, as Astronomer is back, but it isn't sure if he will work further on AVP

**Comment by plague006** [comment]
AVP was restricted to 1.0.4 and `Reboot` isn't yet released for 1.1 Closing this.
