### ISSUE TITLE
WernerChecker is not available in a 1.0.4 install, even though it is compatible

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#2630]
Maybe I'm wrong, but all it has in the version file is:

	"KSP_VERSION":
	{
		"MAJOR":1,
		"MINOR":0,
		"PATCH":5
	}

I thought that unless there was a min version, that it would  be available for lower versions such as 1.0.4

**Comment by plague006** [comment]
No, ksp_version specifies the specific compatible version, not a range.

**Comment by linuxgurugamer** [comment]
ok, then I'll ask the author to update the netkan to reflect thecompatibility

thanks
