### ISSUE TITLE
Davon Throttle Control Systems is compatible with 1.0.5, but CKAN.exe doesn't show it

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#2731]
When I use CKAN on a 1.0.4 game, the Metadata for this says: 
Max KSP Ver: 1.0.5 (using mod version 080)

When I use CKAN on a 1.0.5 game, it doesn't show up

**Comment by linuxgurugamer** [comment]
Ummm, please check this, it suddenly seemed to start working.  So if you can confirm that it's working, then assume it was a glitch on my system.

**Comment by plague006** [comment]
Was able to install the mod without issue on both a 1.0.4 and 1.0.5 install.

**Comment by linuxgurugamer** [comment]
ok, thanks for checking
