### ISSUE TITLE
KerbalFoundries compatibility

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/NetKAN#2792]
Is KerbalFoundries working adequately in 1.0.5? The forum thread is locked and I don't actually have an install of KSP these days.

**Comment by Olympic1** [comment]
The parts themself work but the moment you pause the game using `Esc` the game can't unpause anymore and it spams NRE's.

The old author didn't had time anymore to work on KF so he passed it on someone else. The new thread is here: http://forum.kerbalspaceprogram.com/index.php?/topic/121236-/

**Comment by plague006** [comment]
So no 1.0.5. Sounds good, thanks for the heads up.
