### ISSUE TITLE
HeatResistantSpaceplaneParts needs an Epoch

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/NetKAN#2797]
I still don't get how Epochs work, but it looks like [HeatResistantSpaceplaneParts](https://github.com/KSP-CKAN/CKAN-meta/tree/master/HeatResistantSpaceplanePartsHRP) needs an Epoch. The mod author started with 1.1, then switched to 1.0.4 and seems to be basing off the supported KSP version, now

**Comment by plague006** [comment]
Thanks for the catch.

**Comment by politas** [comment]
It's just that easy?

**Comment by plague006** [comment]
EZPZ
