### ISSUE TITLE
retro actively releasing an older version 

### ISSUE THREAD

**Issue by severedsolo** [KSP-CKAN/NetKAN#2798]
Hey guys, need your help please. 

Basically, I messed up my 1.0.5 release(3.0.2) and ckan offered it to 1.0.4 users (my fault, I didn't update my avc properly) 

I now need to fix this, but I'm a release ahead on the 1.0.5 branch. This is 3.0.3 and because I changed the avc it was issued to 1.0.5 users only. 

What I plan to do, is re-release the last 1.0.4 version (3.0.1) as 3.0.2.1 (so ckan picks up the update)

2 questions :

If I put the version file in the release as 1.0.4 only, will ckan be intelligent enough to pick it up, and offer it to 1.0.4 only because it's higher than3.0.2 (even though the online version will still say 1.0.5 only), or will it ignore it because 3.0.2.1 is lower than 3.0.3 (which is for 1.0.5 only)

**Comment by plague006** [comment]
I'm 1 foot out the door and just skimmed the issue. I think the issue you're describing is this:

CKAN thinks 3.0.2 is compatible from ksp_versions 0.90-1.0.5 but in fact it's exclusively for 1.0.5.

If I understand your issue correctly, we can just change `ContractConfigurator-KerbinSpaceStation-3.0.2.ckan` to be exclusively for ksp_version 1.0.5.

**Comment by severedsolo** [comment]
That's basically what I need yes please!
