### ISSUE TITLE
Changing a listed mods name.

### ISSUE THREAD

**Issue by severedsolo** [KSP-CKAN/NetKAN#2836]
From the next update ContractConfigurator-KerbinSpaceStation will be changing it's name to "Contract Pack: Bases and Stations" - absolutely fine to leave the identifier in place, but I would like the display name updated. Is it just a simple case of updating the netkan? Or is there anything special I need to do?

**Comment by plague006** [comment]
>Is it just a simple case of updating the netkan

Yep. Netkans apply to current and future releases, so because we don't want to affect the current release I wrote an override that maintains the current name if the version number is 3.0.3 or below.
