### ISSUE TITLE
Kerbodyne Plus CKAN Add Request

### ISSUE THREAD

**Issue by bonus-eventus** [KSP-CKAN/NetKAN#2982]
##CKAN File
[kerbodynePlus-1.0.ckan.zip](https://github.com/KSP-CKAN/NetKAN/files/110559/kerbodynePlus-1.0.ckan.zip)

P.S. I'm new to both GitHub and CKAN. Hope I got this right ;)

EDIT: Forgot to mention I'm the mod author

**Comment by politas** [comment]
Thanks for letting us know about your mod. Have you got a forum thread about this? Does it have any dependencies?

**Comment by bonus-eventus** [comment]
Here's the thread. [link](http://forum.kerbalspaceprogram.com/index.php?/topic/112686-kerbodyne-plus-development-thread/&page=1)

No dependencies. Purely a parts pack.

**Comment by plague006** [comment]
Closed via #2983.
