### ISSUE TITLE
Contracts Window +  Multiple folders

### ISSUE THREAD

**Issue by DMagic1** [KSP-CKAN/NetKAN#2986]
The latest version of Contracts Window + contains a separate folder with a required assembly:
* GameData/ContractsWindow
* GameData/ProgressParser

What is the best way to handle this for CKAN?

I am distributing both folders in a single package (I intend use the ProgressParser for multiple mods and don't want to duplicate data) right now.

Can I add a second "install" node to the NETKAN file?

If not, should I create a special release just for CKAN and mark Progress Parser as a dependency? Would that require special packages for both assemblies, or would CKAN ignore the copy of ProgressParser included in the regular Contracts Window + package?

**Comment by politas** [comment]
Yes, add a second directive to the "install" list, unless ProgressParser would be useful for other mods, in which case a separate mod with a dependency would be the way to go. You can use the same download in that case.

**Comment by DMagic1** [comment]
Thanks. I setup a Github download for Progress Parser; see #2988.

**Comment by politas** [comment]
Wonderful. No problems I can see with any of that. Merged with thanks!
