### ISSUE TITLE
Scatterer update not being picked up

### ISSUE THREAD

**Issue by Richard-Payne** [KSP-CKAN/NetKAN#3001]
I'm using CKAN v1.1.60-0-0g7206ce5.

Scatterer is being detected as version v0.02182 but there is a new version on KerbalStuff (v0.022).  From what I can tell from the netkan file here, it should be picking up from KerbalStuff.

Any thoughts?

**Comment by politas** [comment]
2182 is larger than 22, so that's the latest version?

**Comment by Richard-Payne** [comment]
Yes, but they are not the version numbers.  0.022 is larger that 0.02182.

**Comment by plague006** [comment]
To most people (myself included) the `v` in `v0.022` denotes a version number, not a decimal number. The period (`.`) in version numbers does not denote a decimal place but a delimiter. Thus @politas was correct in comparing `022` to `02182` and not ` 0.022` to `0.02182`

**Comment by Richard-Payne** [comment]
What you're saying would make some sense with multi-segment versions (2.3.4 for example) but decimal versions are not exactly uncommon either.

**Comment by politas** [comment]
Feel free to raise an issue detailing the clear rules under which CKAN should use decimal versioning rather than version number versioning. If you can come up with a good set of rules, we'd be delighted, since fixing this stuff is a pain.

**Comment by politas** [comment]
Let me be clear that we know you are right, and the author intends v0.022 to indicate a more recent version than v0.02182, but automatically deciding when to use decimal versioning is quite hard, and a simplistic rule will screw up on v0.10 releases far more often.
