### ISSUE TITLE
Netkan Jenkins test not matching spec for initial character of name

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/NetKAN#3002]
As per #2978, The build test is using a grep string that only matches mod names starting with a letter, but the spec says nothing about the initial character being special, so mod names should be able to start with digits or even dashes. Either the test or the spec should be changed. Is there a technical reason to limit the starting character to letters?

**Comment by plague006** [comment]
This should be in the main CKAN repo as it deals with the spec and actual code, not with the metadata itself.

**Comment by politas** [comment]
Moved to KSP-CKAN/CKAN#1570
