### ISSUE TITLE
Netkan doesn't create .ckan for my mod.

### ISSUE THREAD

**Issue by NoPanShabuShabu** [KSP-CKAN/NetKAN#3003]
Here's the .netkan for my mod:

{
    "spec_version" : 1,
    "identifier"   : "FacilityReset",
    "$kref"        : "#/ckan/kerbalstuff/1446",
    "x_netkan_license_ok": true
}

It seems to be downloading the mod into the CKAN\downloads folder OK, but netkan.exe always ends with:

FATAL CKAN.NetKAN.program (null) - Exception has been thrown by the target of an invocation.

I think it has to do with the license which is "Public Domain."  I've tried a couple of variations of the .netkan, such as having the line: x_netkan_license_ok": false, or explicity stating: "license" : "Public Domain".  Still, no dice.

**Comment by politas** [comment]
"public-domain" is the string used for Public Domain in the [CKAN schema](https://github.com/KSP-CKAN/CKAN/blob/master/CKAN.schema).

**Comment by NoPanShabuShabu** [comment]
Thanks for the help.  I fixed the license and added your suggestions, and a version that works is below.  The instructions for adding a mod say that a pull request is preferred, but what I see when I follow the links doesn't quite match what it says I'm supposed to see, so I'm a bit confused about just how to do that.

FacilityReset.netkan

{
    "spec_version" : 1,
    "identifier"   : "FacilityReset",
    "$kref"        : "#/ckan/kerbalstuff/1446",
    "license"      : "public-domain",
	"name"         : "Facility Reset for 64 bit",
	"abstract"     : "A plugin which works around a bug affecting 64 bit versions by resetting the Space Center facilities to the correct level.",
	"resources"    : { "homepage" : "http://forum.kerbalspaceprogram.com/index.php?/topic/131454-facility-reset-for-64-bit-ksp/" },
	"install"      : [{
                      "file": "FacilityReset",
                      "install_to":"GameData",
                      "filter":"FacilityResetSource.cs"
                      }]
}

**Comment by politas** [comment]
That's perfect, @NoPanShabuShabu. Should be appearing in CKAN within two hours. Thanks for the submission!
