### ISSUE TITLE
I'm back

### ISSUE THREAD

**Issue by Olympic1** [KSP-CKAN/NetKAN#3028]
Ok, I'm finally back. Holidays are over, exams are done and I'm healthy again.

Now I need to catch up first with all the changes that happended since my absence (800-ish commits) and check on mod updates on the forums. Then I'll need to get back into the flow I had before on CKAN :smiley:.

I also didn't welcome our newest member to the team, so:
Welcome to the team @politas.

**Comment by politas** [comment]
Glad to see you back, Olympic1. There's a bunch of planet mods waiting for your loving attention! And thanks for the welcome!

**Comment by plague006** [comment]
In the slew of PRs and issues the last week I totally missed your announcement (though of course I noticed your return). Good to have you back, glad to hear you're back in good health.
