### ISSUE TITLE
new mod

### ISSUE THREAD

**Issue by RaginCaucasian** [KSP-CKAN/NetKAN#3070]
I have included the .netkan and the .ckan in the attached zip. GitHub wouldn't let me attach the files on their own.

[RaginCaucasian.zip](https://github.com/KSP-CKAN/NetKAN/files/129266/RaginCaucasian.zip)

Thanks!

**Comment by plague006** [comment]
Ref https://github.com/KSP-CKAN/NetKAN/pull/3020
