### ISSUE TITLE
Add mod to CKAN

### ISSUE THREAD

**Issue by Shuudoushi** [KSP-CKAN/NetKAN#3075]
HI... So I tried making the netkan file myself, but it kept exploding in my face while trying to make the .ckan file with netkan... So if y'all would be so kind as to add my add-on to ckan for me...

Github repo: https://github.com/Shuudoushi/BlackRibbon/tree/master
Name: `BlackRibbon`
Requires: `BDArmory`
Desc: `This is an add-on for BDArmory. It adds new weapons and parts.`

Thanks in advance, and sorry for being a pain...

**Comment by Olympic1** [comment]
I will add it to CKAN but therefor you'll need to release a stable release (no pre-release) with a `.zip` file otherwise we can't download a GitHub release.

**Comment by Shuudoushi** [comment]
Thank you very much. The next release should be a stable, as none of the parts have caused issues yet.

**Comment by Shuudoushi** [comment]
Is [this](https://github.com/Shuudoushi/BlackRibbon/releases/tag/0.4) satisfactory?

**Comment by Olympic1** [comment]
You need to include a `.zip` file into the download. So compress one and edit the release to add the file.

**Comment by Shuudoushi** [comment]
It's didn't want to upload the zip the first time around...

**Comment by Olympic1** [comment]
Mod will be added when #3076 gets merged

**Comment by Shuudoushi** [comment]
Woot, tyvm!
