### ISSUE TITLE
64k wants incompatible version of Kopernicus

### ISSUE THREAD

**Issue by ChucklesTheBeard** [KSP-CKAN/NetKAN#3303]
ref #3300

**Comment by plague006** [comment]
It's only an issue if a another mod is also trying to install `Kopernicus`. In the case of #3300 that'd be `ExtrasolarPlanetsBeyondKerbol-RealisticScale` itself.

If 64k can't function without any other version then it's implicitly in conflict with any mod that uses more modern versions.

**Comment by plague006** [comment]
Tagging `HarderSolarSystem-generic` as the only mod that has a relationships to 64k and depends `Kopernicus`.

**Comment by plague006** [comment]
When/if `KSP-64k` updates to KSP 1.1 this will get resolved in the course of updating its metadata.
