### ISSUE TITLE
Request For Science Continued to download to point to github please?

### ISSUE THREAD

**Issue by nobodyhasthis** [KSP-CKAN/NetKAN#3326]
For Science Continued download mirror is https://github.com/Xarun/ForScienceContinued/releases

Poking @plague006 in response to 
Running down individual mods for mirrors is a time consuming process and by sharing you can reduce that workload significantly. & Officially, https://github.com/KSP-CKAN/CKAN-meta if it's related to .ckans and https://github.com/KSP-CKAN/NetKAN if it's related to netkans. If you're not sure what the difference is, either is fine: we see issues on all the repos.

Is this link helpful?

I know you are busy and I don't want to waste your time

**Comment by plague006** [comment]
Looks like @Olympic1 got to this first, and it indeed looks like it was helpful. Thanks. =)
