### ISSUE TITLE
KDEX - Kerbal Dust Experiment v1.04 primary host is Curse Forge. To clear 404 error.

### ISSUE THREAD

**Issue by nobodyhasthis** [KSP-CKAN/NetKAN#3372]
KDEX - Kerbal Dust Experiment v1.04 primary host is Curse. We where previously drawing data using the alternative Kerbal Stuff site. 

I suspect that this will not be moved to Spacedock at all. Authors last visit to forum Dec 2014

License is CC BY-NC-SA 3.0

http://kerbal.curseforge.com/projects/kdex

**Comment by politas** [comment]
Thanks for the heads-up!
