### ISSUE TITLE
KerboKatzUtilities download needs directed to github to fix 404 and dependency errors

### ISSUE THREAD

**Issue by nobodyhasthis** [KSP-CKAN/NetKAN#3380]
Passing on information of possible down load of KerboKatzUtilities to prevent 404 error

https://github.com/Xarun/KerboKatzUtilities

Dependency download error reported in Jenkins build of merged #3327 ForScienceContiuned. I should have checked the dependence when reporting the original issue to move ForScienceContiuned. Sorry for any inconvenience caused.

**Comment by politas** [comment]
Fixed by #3382, I believe
