### ISSUE TITLE
KerbalAtomics has a github

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/NetKAN#3388]
https://github.com/ChrisAdderley/KerbalAtomics/releases

While the .zip contains a .version file it's not a valid JSON.

**Comment by politas** [comment]
Should we raise an issue on his github?

**Comment by politas** [comment]
Hmm. Is there a conflict between this mod and SimpleAtomics? I'm thinking they are both tweaking the configs of other mods' nuclear parts.

**Comment by plague006** [comment]
I don't have a chance to look into the second question at the moment, but to the former the author has already been informed via the mod's ksp forum thread about the issue with the version file.

**Comment by plague006** [comment]
Did some searching and didn't come up with anything about a conflict with SimpleAtomics.

**Comment by plague006** [comment]
Closing for  #3766
