### ISSUE TITLE
netkan bot should show URLs in case of network errors

### ISSUE THREAD

**Issue by hakan42** [KSP-CKAN/NetKAN#340]
The MirrorKAN log is full of stack traces where we encounter 404 or 403 HTTP errors.

In those case, the attempted URL should also be printed to make debugging easier.

**Comment by AlexanderDzhoganov** [comment]
This really should be in CKAN-netkan, could you move it there?

**Comment by hakan42** [comment]
This issue was moved to KSP-CKAN/CKAN-netkan#24
