### ISSUE TITLE
Buffalo: NASA Inspired MSEV download needs moved to Github / 404 Error

### ISSUE THREAD

**Issue by nobodyhasthis** [KSP-CKAN/NetKAN#3409]
Buffalo: NASA Inspired MSEV is still pointing to Kerbalstuff

It has a GitHub release https://github.com/Angel-125/Buffalo/releases

Looks like Wildblue Tools is a dependency and possibly the community resource pack.

**Comment by nobodyhasthis** [comment]
Looks like there is a possible mix up in Wildblue Tools NetKan. Looks like CKAN version is 1.0.29
Should be 1.0.32. The one provided looks like it points to
 "$kref"          : "#/ckan/kerbalstuff/947",

**Comment by nobodyhasthis** [comment]
Ref #3408 looks like Wildblue Tools NetKan is done already ;D

**Comment by politas** [comment]
Resolved in #3438
