### ISSUE TITLE
KSCSwitcher and KerbalRenamer have been eated

### ISSUE THREAD

**Issue by NathanKell** [KSP-CKAN/NetKAN#3412]
They are now on KSP-RO. Could some kind person redirect the netkans there?

(regex is once again done with KSP modding, so the RO group has forked both of those and will maintain them.)

**Comment by politas** [comment]
I've left the author as-is for now. Let us know when that should be updated.

**Comment by NathanKell** [comment]
@politas thanks! Yeah, that's very fair, since we haven't done anything to them as yet. At most we'd just be adding authors, it's not like @jbengtson should stop getting the credit. :)
