### ISSUE TITLE
RP-0 netkan not firing

### ISSUE THREAD

**Issue by NathanKell** [KSP-CKAN/NetKAN#3416]
the RP-0 netkan does not seem to be generating a .ckan. I released 0.44 last night, so a run should have occurred by now. Or is the netkan bot down?

**Comment by techman83** [comment]
Hmm, looks like the indexer indeed hasn't run in a couple days. I'll check it when I take my coffee break.

http://status.ksp-ckan.org

**Comment by NathanKell** [comment]
Thanks! :)

**Comment by techman83** [comment]
Looks like we're back rolling again. The indexer's cache partition filled up as a result from all the mods moving to spacedock.

**Comment by NathanKell** [comment]
Ah, that would explain it. Thanks, on behalf of all of us. :)

**Comment by techman83** [comment]
Np, a nice simple one :)
