### ISSUE TITLE
Adding a .version file to RP-0

### ISSUE THREAD

**Issue by NathanKell** [KSP-CKAN/NetKAN#3465]
I'd like to add a version file to RP-0. However, last time I did that, the versioning on CKAN got messed up (because we use v in the version tag on github, and therefore in the CKAN release). How would I go about changing the netkan to use the version number in the .version file but still prepend the v to keep sync with earlier versions?

**Comment by techman83** [comment]
You can force a 'v' with

```"x_netkan_force_v": true```

**Comment by dbent** [comment]
Alternatively,

```json
{
    "x_netkan_epoch": 1
}
```

**Comment by NathanKell** [comment]
Right, sorry. @pjf did this on the RP-0 repo as a PR but I've been crunching so hard on 1.1 I never got back to this.

**Comment by plague006** [comment]
Yep, followed the ref'ed issues. I should have commented to that effect.
