### ISSUE TITLE
CrossFeedEnabler

### ISSUE THREAD

**Issue by pjslauta** [KSP-CKAN/NetKAN#3515]
Fixing CrossFeedEnabler

{
    "spec_version" : 1,
    "identifier"   : "CrossFeedEnabler",
    "$kref"        : "#/ckan/github/NathanKell/CrossFeedEnabler",
    "name"         : "Crossfeed Enabler",
    "abstract"     : "Adds toggleable fuel crossfeed between the part it's added to, and the part this part is surface-attached to. Use it for radial tanks.",
    "license"      : "CC-BY-4.0",
    "ksp_version"  : "1.0.5",
    "resources": {
        "homepage": "http://forum.kerbalspaceprogram.com/index.php?/topic/69286-10-crossfeedenabler-v33-may-11/",
		"source code": "https://www.github.com/NathanKell/CrossFeedEnabler"
    }
}

**Comment by politas** [comment]
On what basis do you say the latest version of this mod is for KSP v1.0.5 and only 1.0.5? The last comments by the mod author in the forum thread says he has not updated this mod, and that it is no longer required, as the functionality is now supported in stock.

**Comment by plague006** [comment]
Over 2 weeks and no reply? You can probably close this.

**Comment by politas** [comment]
Yep. Closing.
