### ISSUE TITLE
Add ForgottenRealEngines

### ISSUE THREAD

**Issue by Zarbizaure** [KSP-CKAN/NetKAN#3517]
Hello! I would like to integrate my mod, [Forgotten Reals Engines](http://spacedock.info/mod/456/Forgotten%20Real%20Engines) in CKAN. For some strange reasons netkan.exe does not work on my computer. Here is a copy of my .netkan file; could anyone check if it works? :)
[FRE-CKAN.zip](https://github.com/KSP-CKAN/NetKAN/files/200989/FRE-CKAN.zip)
Thanks!

**Comment by Dazpoet** [comment]
Some small errors and things that weren't needed, I changed the file and started a PR. Hope you don't mind?

**Comment by Zarbizaure** [comment]
You're right, I forgot the license and made typo errors. Thanks for your help!
