### ISSUE TITLE
Tweak Scale shown for KSP 1.1 using old version 1.50. Strict max 1.0.5 with version 2.2.6 ?

### ISSUE THREAD

**Issue by nobodyhasthis** [KSP-CKAN/NetKAN#3522]
Testing 1.1 pre release. Tweak Scale showing up as compatible using old version 1.50.

Max KSP version shown as 1.0.5 with version 2.2.6 which is correct. The mod should not being showing up for Ksp 1.1. It is a plugin that is not currently compatible. Is the this a case for setting  ksp_version_strict for this particular mod given the Unity changes ?

**Comment by plague006** [comment]
> s the this a case for setting ksp_version_strict?

Nah, it's a case of https://github.com/KSP-CKAN/CKAN-meta/issues/623 (a ksp_version_min set without a ksp_version_max). https://github.com/KSP-CKAN/CKAN-meta/pull/1037 should fix this (if I caught all the versions of tweakscale that were affected).
