### ISSUE TITLE
Add Mod - RCS Build Aid for 1.1

### ISSUE THREAD

**Issue by ace220** [KSP-CKAN/NetKAN#3570]
Confirmed it working in 1.1pre
http://forum.kerbalspaceprogram.com/index.php?/topic/135824-rcs-build-aid-compiled-for-ksp-11/
http://kerbal.curseforge.com/projects/rcs-build-aid/files/2292475

Thanks!

**Comment by politas** [comment]
KSP/CKAN-meta#1048 has sorted this out.
