### ISSUE TITLE
NearFuture have dropped the IFS-Core dependency and...

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/NetKAN#3680]
...replaced it with something names B9-PartSwitch. I have no idea what the latter is but saw it in the forumpost [here](http://forum.kerbalspaceprogram.com/index.php?/topic/47786-11ish-near-future-technologies-april-22-updates/&page=1) and seeing as I'm going to bed I thought I should mention it here. It also seems most of our NF mods are still .kerbalstuff so I don't forsee anything breaking right this moment.

**Comment by Dazpoet** [comment]
Seems it'll be fixed by Streetwind (who's github handle I've seemingly forgotten) sometime during the weekend as can be seen [on the forums](http://forum.kerbalspaceprogram.com/index.php?/topic/47786-11ish-near-future-technologies-april-22-updates/&page=237#comment-2532906)

**Comment by nobodyhasthis** [comment]
Trying to provide relevant links to help resolve this issue.
Cross Ref #3718 there is a comment on this from @plague006. Also I believe you are referring to @lOmicronl 
Hope this helps to clarify things.

**Comment by plague006** [comment]
https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/B9PartSwitch.netkan is a mod by blowfishpro. https://github.com/KSP-CKAN/CKAN-meta/blob/master/B9PartSwitch/B9PartSwitch-v1.1.ckan gives us a version for ksp 1.1.
