### ISSUE TITLE
B9 Aerospace

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/NetKAN#37]
Assuming we get permission, B9 has a long list of bundled mods:
- [x] CrossFeedEnabler
- [x] Firespitter (core)
- [x] RasterPropMonitor
- [ ] KineTechAnimation
- [ ] KlockheedMartian gimbal
- [ ] ResGen
- [ ] SmokeScreen
- [ ] Virgin Kalactic's "Generic" plugin

Update: on the forum thread it's stated that FAR/NEAR are considered requirements:
- [x] FAR
- [x] NEAR

Additionally it also provides a custom config for Hot Rockets, which maybe isn't worth a package on its own.

**Comment by starikki** [comment]
B9 pack has custom files for JSI Rasterpropmonitor, the current package on CKAN does not include that thus all B9 cockpit does not have working MFDs

**Comment by madadam** [comment]
@starikki the B9 package does not include RasterPropMonitor, but it does depend on it. I was under the impression that the JSI folder in the B9 archive is just a copy of the RasterPropMonitor mod and does not include any additional files. Therefore simply depending on the core RasterPropMonitor package should be enough. If this is not the case, could you tell me which are the custom files you are talking about?

**Comment by starikki** [comment]
@madadam I'm pretty sure the original B9 Package contains extra files other than normal JSI contents.
 It's mainly a folder called RPMPodPatches inside JSI folder. If you install B9 outside CKAN and without the RasterPropMonitor Mod (just use the JSI folder included inside B9 Package), everything will work just fine. B9 mod page also mentioned that its not compatible with original RPM mod.
