### ISSUE TITLE
Near Future Extras: RTG decay. Install error. Module NearFutureElectrical has not been found

### ISSUE THREAD

**Issue by nobodyhasthis** [KSP-CKAN/NetKAN#3739]
Near future electrical working fine. There is a separate addon showing as available in CKAN. There is an extra config file to introduce RTG power loss of time within Near Future Electrical.

This is Near Futures Extras. Selecting this additional file produces the following error pop up.

Module NearFutureElectrical has not been found. This may be because it is not compatible with the currently installed version of KSP

**Comment by nobodyhasthis** [comment]
Ref #3720 is last merge for move to spacedock

**Comment by plague006** [comment]
Just tested and was able to install `NearFutureElectrical-DecayingRTGs`. Can you confirm if this issue is resolved?

**Comment by nobodyhasthis** [comment]
Resolved. All dependencies now satisfied and are available. Guess it just took a little while for everything to catch up. Thanks for testing anyway.
