### ISSUE TITLE
Please clear the indexer's cache for B9AnimationModules

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/NetKAN#3806]
New file but under the same github release so we're using a broken/outdated .version file.

Thanks @techman83

**Comment by techman83** [comment]
Cache files removed and triggered the inflate Webhook. New metadata committed in [34cee98](https://github.com/KSP-CKAN/CKAN-meta/commit/34cee982b55c063dafd4182c9bfd140edd7ba621)

**Comment by plague006** [comment]
TYTY
Have a happy otter:
http://i.imgur.com/PVOXWfq.gifv

**Comment by politas** [comment]
I'll happily join that class!
