### ISSUE TITLE
Joolian Discovery

### ISSUE THREAD

**Issue by ryancastlemaine** [KSP-CKAN/NetKAN#3825]
This parts pack is inspired by the USS Discovery One ship, from the 2001: A Space Odyssey feature film.
[JoolianDiscovery.zip](https://github.com/KSP-CKAN/NetKAN/files/243330/JoolianDiscovery.zip)

**Comment by plague006** [comment]
@NecroBones I'd love your input. You're often maintaining your own metadata, have you held off on this because it's in beta/early or should we add this to the index?

**Comment by NecroBones** [comment]
Actually I think it's one of those things where I had assumed that KerbalStuff had added it automatically, and then never verified (back then I was relying more on that). Adding a Netkan for it that points to its new SpaceDock entry would be fine. I can write one up later tonight.
