### ISSUE TITLE
Joolian Discovery

### ISSUE THREAD

**Issue by ryancastlemaine** [KSP-CKAN/NetKAN#3826]
This parts pack is inspired by the USS Discovery One ship, from the 2001: A Space Odyssey feature film.
[JoolianDiscovery.zip](https://github.com/KSP-CKAN/NetKAN/files/243342/JoolianDiscovery.zip)

**Comment by plague006** [comment]
Closing this due to / in favour of the referred PR/issue/commit.

 #3825
