### ISSUE TITLE
PreciseManeuver plugin add

### ISSUE THREAD

**Issue by radistmorse** [KSP-CKAN/NetKAN#3945]
Hi there. I'm the author of the PreciseManeuver plugin (a fork of the PreciseNode plugin) and I think it's ready for CKAN. I tried to write the netkan module for it:
```
{
    "spec_version" : 1,
    "identifier"   : "PreciseManeuver",
    "$kref"        : "#/ckan/github/radistmorse/KSPPreciseManeuver",
    "name"         : "Precise Maneuver",
    "abstract"     : "A tool that gives you a much better control over your maneuvers",
    "license"      : "BSD-2 clause",
    "ksp_version"  : "1.1.2",
    "resources": {
        "homepage": "http://forum.kerbalspaceprogram.com/index.php?/topic/128303-11x-precise-maneuver-editor-ver-20-pre-17-04-2016/"
    }
}
```
But I encountered several problems. First of all, netkan.exe segfaults while processing it, both on win10 and fedora linux. Second, is there a way to provide a range of supported KSP versions? Like 1.1.1-1.1.99.

**Comment by plague006** [comment]
`BSD-2 clause` is an invalid license. `BSD-2-clause` will give you a passing test. Does this conflict with PreciseNode or can users use both in tandem without issue?

**Comment by radistmorse** [comment]
Not on technical level, no. But if you start to use both mods concurrently, you will probably get all sorts of weird behavior. As an example, the default hotkeys are the same for many functions and pressing them may result in these functions being applied twice.
But if you know what you're doing, there is no technical limitations that prevents you from using both mods simultaneously.

**Comment by plague006** [comment]
Using both would probably cause bug reports for one or both of you though right? Because of the odd behaviour it'll likely be best to have them conflict.

**Comment by radistmorse** [comment]
Probably yes. People usually choose one or another, not both.
```
{
    "spec_version" : 1,
    "identifier"   : "PreciseManeuver",
    "$kref"        : "#/ckan/github/radistmorse/KSPPreciseManeuver",
    "name"         : "Precise Maneuver",
    "abstract"     : "A tool that gives you a much better control over your maneuvers",
    "license"      : "BSD-2-clause",
    "ksp_version"  : "1.1.2",
    "resources": {
        "homepage": "http://forum.kerbalspaceprogram.com/index.php?/topic/128303-11x-precise-maneuver-editor-ver-20-pre-17-04-2016/"
    },
    "conflicts": [
        { "name": "PreciseNode" }
    ]
}
```
The question with KSP version remains. I do not expect any problems with minor KSP updates. Can I just say "any 1.1.x version is fine"?

**Comment by plague006** [comment]
Yep that's perfectly fine just use `"ksp_version"  : "1.1",`

**Comment by radistmorse** [comment]
Well then, I guess this version should do it
```
{
    "spec_version" : 1,
    "identifier"   : "PreciseManeuver",
    "$kref"        : "#/ckan/github/radistmorse/KSPPreciseManeuver",
    "name"         : "Precise Maneuver",
    "abstract"     : "A tool that gives you a much better control over your maneuvers",
    "license"      : "BSD-2-clause",
    "ksp_version"  : "1.1",
    "resources": {
        "homepage": "http://forum.kerbalspaceprogram.com/index.php?/topic/128303-11x-precise-maneuver-editor-ver-20-pre-17-04-2016/"
    },
    "conflicts": [
        { "name": "PreciseNode" }
    ]
}
```
netkan still segfaults on my linux machine though, and I don't have access to windows right now.
