### ISSUE TITLE
Docking Port sounds FX now point to Github release? 

### ISSUE THREAD

**Issue by nobodyhasthis** [KSP-CKAN/NetKAN#3970]
Have been looking at installing Docking Port sounds FX. 
I think the NetKan is pointing to spacedock. Which does not look like it has been updated. There is also no link to Spacedock from the mods forum thread. The latest release appears to be on Github here:

https://github.com/TedThompson/Docking-Sounds/releases

Should the netkan point to the github entry?

**Comment by nobodyhasthis** [comment]
Looking at the NetKan and manually down loading the mod to see what happens. The file name on spacedock is Docking_Port_Sound_FX-1.0.2.zip. Which actually contains mod version v2.1.1

If you download via CKAN and look in the gamedata you might see v2.1.1 but it will say version 1.0.2 on the list. If this true. I needed to say something in the issue report. It is too confusing to new users even if it works. I think it is cleaner to go to the Github version. I could be very wrong on this. Really sorry if I am wasting your time with this and it turns out to user error.

**Comment by politas** [comment]
The AVC .version file specifies 1.1.1 as the max ksp version, but the online copy has 1.1.2, and that's what should get used.
