### ISSUE TITLE
KerbalKrashSystem is on v0.3.3 on CurseForge

### ISSUE THREAD

**Issue by nobodyhasthis** [KSP-CKAN/NetKAN#3975]
KerbalKrashSystem is on v0.3.3 on CurseForge. Could it get updated in CKAN, as it still reports 0.3.2?

I realise this might require some manual help. Pending a solution for automatic Curse.com indexing https://github.com/KSP-CKAN/CKAN/pull/1608

Thanks for your help.

**Comment by politas** [comment]
Thanks for the heads-up.
