### ISSUE TITLE
Stock Visual Enhancements

### ISSUE THREAD

**Issue by Blu3wolf** [KSP-CKAN/NetKAN#3997]
SVE includes a copy of Environmental Visual Enhancements with it, which conflicts with having EVE already installed. The metadata should reflect this.

Unfortunately, the version of EVE included is modified compared to EVE as released on CKAN. So that does make it a little awkward. I think the best solution is to mark the two as mutually incompatible.

**Comment by politas** [comment]
The Metadata does reflect that. SVE conflicts with EVE.

**Comment by politas** [comment]
That was changed fairly recently, so you may need to uninstall both and reinstall whichever you wish to use.

**Comment by Blu3wolf** [comment]
cheers!

**Comment by Blu3wolf** [comment]
I failed to notice this, but it looks like my version of EVE installed is not actually managed by CKAN. In fact it doesnt show up at all.
