### ISSUE TITLE
Bot hasn't picked up on TACLS release for 1.1.2?

### ISSUE THREAD

**Issue by aw1621107** [KSP-CKAN/NetKAN#4023]
TACLS has a release for 1.1.2 [here](https://github.com/KSP-RO/TacLifeSupport/releases), but it looks like the CKAN metadata doesn't have a corresponding release. The NetKAN file seemed to look alright.

**Comment by plague006** [comment]
Critical metadata was missing from the .netkan which meant it wasn't passing the indexer. Fill be fixed in #4026

**Comment by aw1621107** [comment]
Oh wow, that's quite the oversight. Thanks!
