### ISSUE TITLE
Request adding a CKAN mod

### ISSUE THREAD

**Issue by adsii1970** [KSP-CKAN/NetKAN#4027]
I think I have everything ready to add this mod to CKAN. I am the author of the images and files within this mod; the ribbons require the Final Frontier mod by Nereid. 
https://github.com/adsii1970/realspaceprogram.git
Please let me know if I did this correctly; if I didn't let me know what I need to do to make it right.
Thanks in advance for your help and time...

**Comment by plague006** [comment]
Your mod has no [releases](https://github.com/adsii1970/realspaceprogram/releases). Is it uploaded anywhere?

**Comment by adsii1970** [comment]
No, this is my first mod and my first upload. It is currently on Github.

**Comment by politas** [comment]
If you want the ribbons to definitely be available, add the following:

    "depends": [
        { "name": "FinalFrontier" }
    ],

(The final comma is needed for every stanza except the last, of course, so if this is at the end, then move the comma to after the `}` at the end of the `"resources"` bit)

Now, if you want people to be able to choose whether they're using FinalFrontier or not, and let them just use the flags, then have this instead: 

    "recommends": [
        { "name": "FinalFrontier" }
    ],

That release doesn't quite look right. Check out what my flagmod looks like: https://github.com/politas/Sarkomand/releases

GitHub creates the release zip for you if you upload the original files in the correct folder structure

**Comment by plague006** [comment]
A week waiting on a reply. I'll reiterate what @politas said: you need to attach GameData.zip to the actual release. Not as a URL but by uploading the file as part of the release. Closing but will re-open if a release is issued or there is a reply.

**Comment by adsii1970** [comment]
Sorry about the delay. In the “real world” I teach at a local university and am working on a book-length manuscript. Sometimes KSP gets shoved to the back, if you understand.

 

I will be working to address these items you’ve listed here so hopefully we can get this up.

AS

 

Alan D. Simmons II

PO Box 274  Henderson, KY 42419-0274

(270) 925-5506

 

"Democracy and socialism have nothing in common but one word, equality. But notice the difference: while democracy seeks equality in liberty, socialism seeks equality in restraint and servitude."

- Alexis de Tocqueville, French Political Philosopher and Historian, (1805-1859)

 

My faith-based blog:  <http://www.thedailywalk.org/> www.thedailywalk.org

My political based blog:  <http://www.right-of-center.com/> www.right-of-center.com

**Comment by politas** [comment]
Hi! I notice you've made some changes. Instead of the GameData.zip link you have in your release notes, you need to attach the file to the release. I'll submit some changes to your .netkan file to clean that up, too.

**Comment by Dazpoet** [comment]
Modrepository no longer exists so I'm closing this for now.
