### ISSUE TITLE
One level too much indirection

### ISSUE THREAD

**Issue by marce155** [KSP-CKAN/NetKAN#405]
Hi!
I **just now** realized that there is one level too much when my mods are installed via CKAN.

Example:
GameData
. CIT
.. ActiveStruts <- too much
... ActiveStruts
.... [ModContent]

For the CIT-Utils the structure should be:
GameData
. CIT
.. [ModContent]
as well.

This is true for **all** my CIT packages and breaks the mods which expect a certain path. I don't have access to my dev machine until the weekend so it would be really great if someone could fix the files.
**Very sorry for the inconvenience!**

**Comment by AlexanderDzhoganov** [comment]
Ugh, sure, on it.

**Comment by AlexanderDzhoganov** [comment]
Should be fixed now, thanks for notifying us so quickly :)
