### ISSUE TITLE
InterstellarFuelSwitch-Core file conflict?

### ISSUE THREAD

**Issue by miki-g** [KSP-CKAN/NetKAN#4061]
Oh no!

It looks like you're trying to install a mod which is already installed,
or which conflicts with another mod which is already installed.

As a safety feature, the CKAN will *never* overwrite or alter a file
that it did not install itself.

If you wish to install InterstellarFuelSwitch-Core 2.0.6 via the CKAN,
then please manually uninstall the mod which owns:

GameData/InterstellarFuelSwitch/Plugins/MiniAVC.xml

and try again.

Your GameData has been returned to its original state.

Error!

... small workaround ...
after manual deleting GameData/InterstellarFuelSwitch/Plugins/MiniAVC.xml update ok

**Comment by plague006** [comment]
That's not a workaround, it's the solution. The file used to not be included in the installation of this mod and was generated after running KSP. Now that it's included in the install it conflicts with the existing `MiniAVC.xml`

**Comment by politas** [comment]
We're going to get a bunch of these, now that we've removed all the filters for miniavc.xml

**Comment by plague006** [comment]
We pay for our mistakes. :(
