### ISSUE TITLE
Surface Science Experiments still conflicts with installing Sounding Rockets

### ISSUE THREAD

**Issue by nobodyhasthis** [KSP-CKAN/NetKAN#4184]
CKAN thinks Sounding Rockets still conflicts with Surface Science Experiments. It did in the past. Since then @CobaltWolf has fixed the problem.

> It's been compatible with Sounding Rockets for at least a week. It was a typo that was breaking our ScienceDefs which broke any that loaded afterwards. v1.4.1 fixed it.

So I asked on the forum if the CKAN block could be removed and got this answer back

> @nobodyhasthis, The metadata for Sounding Rockets is self-hosted by @RoverDude. You'll need to take it up with him to remove the conflict.

I have raised an issue with Sounding Rockets as @Roverdude does of course maintain his own metadata. However there is also a case of the automated data being picked up from Spacedock in regards to Surface Science Experiments https://github.com/KSP-CKAN/CKAN-meta/blame/e7a2a6a402126a3c9f14b3a1c2c6ecb00ee2ef91/SurfaceExperimentPack/SurfaceExperimentPack-1-1Hotfix.ckan

Which should be the latest compatible version 1.4.1. Is the compatibility block actually coming from the  Surface Science Experiments metadata?

As always I am tremendously grateful for CKAN.  Thank you for looking into this.

**Comment by plague006** [comment]
As `SurfaceExperimentPack` does not and never included a conflicts relationship this lies entirely with `SoundingRockets`. My bet would be that the author/metadata host pushed an update but did not bump an epoch thus the new conflict relationships (or lack thereof) has not been propogated to existing users.

Solution is to have affected users uninstall then re-install `SoundingRockets`.

**Comment by plague006** [comment]
To elaborate a little more: when a user installs a mod via CKAN the metadata is copied locally and does not change until the mod is uninstalled. This behaviour will change with https://github.com/KSP-CKAN/CKAN/pull/1730 but that will only affect the next release of CKAN (at the earliest).
