### ISSUE TITLE
Raise Planetshine version to 1.1.2 if not 1.1.99.

### ISSUE THREAD

**Issue by gparent** [KSP-CKAN/NetKAN#4188]
Hello,

As per [this post](http://forum.kerbalspaceprogram.com/index.php?/topic/87012-11-planetshine-v025-stable-v05-experimental-4-april-2015/&page=23#comment-2556161) and reports of the mod working on KSP 1.1.2, I think the metadata should be upped to 1.1.2 or 1.1.99 for this mod if possible.

**Comment by politas** [comment]
Thanks. I hadn't seen that post from Valerian before.
