### ISSUE TITLE
UniversalStorage >= 1.0.90.1 conflicts with other UniveralStorage mods

### ISSUE THREAD

**Issue by fat-lobyte** [KSP-CKAN/NetKAN#421]
This issue is about the following mods:

* UniversalStorage-ECLSS.netkan
* UniversalStorage-IFI.netkan
* UniversalStorage-KAS.netkan
* UniversalStorage-SNACKS.netkan
* UniversalStorage-TAC.netkan
* UniversalStorage.netkan

The newest release of UniversalStorage (1.0.90.1) combines all of its submods into one package that detects the presence of other mods and enables the specific submods if required.

Trying to install UniversalStorage >= 1.0.90.1 alongside with any other UniversalStorage mods causes a conflict on installation (overwriting files of another mod).

For more information and in case you need feedback from the author, please refer to this thread: http://forum.kerbalspaceprogram.com/threads/75129-Universal-Storage-1-0-90-0-%28For-KSP-0-90%29-2nd-January-2015?p=1644627&viewfull=1#post1644627

**Comment by AlexanderDzhoganov** [comment]
Thanks for the report, fixed in https://github.com/KSP-CKAN/NetKAN/pull/425/files.
