### ISSUE TITLE
Adding Information

### ISSUE THREAD

**Issue by Lupinarius** [KSP-CKAN/NetKAN#4235]
I just had my first mod added to CKAN via pull #4191 and I want to know the fastest, easiest (for everybody) and best (on your end) way to update information in my CKAN Metadata. I use GitHub but am still learning about using it. The corrections I need to make to the .ckan file are simple ones I can make myself, I just need to know the process so I do things right.

**Comment by politas** [comment]
If you want to just use GitHub, open the .netkan file [here ](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/BWA-X-ROMBUS.netkan), click on the little pencil to edit the file, which will ensure that you have a fork of the Netkan repository, save your changes to a new branch preferably with a meaningful name so you know which branch is which, then create a pull request which you should be prompted to do. Make sure you keep going until you have a PR# showing at the top. 

Then it'll undergo build checks and appear on notification lists for those of us watching the repo. We'll make sure it's going to actually do what you want, given Netkan/CKAN's quirks and merge it.

If you want to update older releases, things get a little more complicated, and it may be best to just raise an issue here in the NetKAN repo for a team member to sort it out.

**Comment by politas** [comment]
Just to be clear, changes made to the .netkan file will be reflected through to the current release .ckan file.

**Comment by Lupinarius** [comment]
Thank you, I'll get started right away.

**Comment by nobodyhasthis** [comment]
@Lupinarius are you happy enough to close this issue please?

If you still want some help that is ok. I am just trying to clear down some open issues and I found this one. I thought this issue was solved. Is that correct?

**Comment by Lupinarius** [comment]
Thought the issue had been closed already. My apologies.
