### ISSUE TITLE
Historian Expanded Failing To Update

### ISSUE THREAD

**Issue by Cphoenix** [KSP-CKAN/NetKAN#4264]
Despite #4257 it appears that Historian Expanded still isn't updating correctly. At least for me, it's not appearing after refreshing the CKAN application.

It [appears](https://github.com/KSP-CKAN/CKAN-meta/tree/master/Historian-expanded) that the correct metadata files are available. Perhaps the incorrect 1.2.5 file (not v1.2.5) needs to be deleted?

[status.ksp-ckan.org](http://status.ksp-ckan.org/) reports that it was last checked and inflated 3hrs ago (at time of posting this issue) but last indexed 13 days ago. O.o

**Comment by politas** [comment]
Ah, ok, I found the issue.

**Comment by Cphoenix** [comment]
Thanks. >.<
