### ISSUE TITLE
Remove the Malemute Rover.

### ISSUE THREAD

**Issue by BobPalmer** [KSP-CKAN/NetKAN#4270]
1.  I explicitly have not added this mod to CKAN at this time.
2.  When I am ready to, I will submit my own PR.
3.  The Metadata included is actually *WRONG*, and is going to cause me a bucket of support issues with it's next release.

Please remove this, and in the future, do not add any of my mods to CKAN.

**Comment by politas** [comment]
There you go.

**Comment by BobPalmer** [comment]
Thank you
