### ISSUE TITLE
Add HalfRSS with Textures to CKAN from Github

### ISSUE THREAD

**Issue by pap1723** [KSP-CKAN/NetKAN#4276]
This includes 4 .netkans for the HalfRSS mod and the accompanying Textures

[HalfRSS Netkans.zip](https://github.com/KSP-CKAN/NetKAN/files/330425/HalfRSS.Netkans.zip)

**Comment by linuxgurugamer** [comment]
All of these have syntax errors.  I've corrected them, am waiting on a response in #4458 as to how to proceed

**Comment by Olympic1** [comment]
Done in #4458
