### ISSUE TITLE
Remove all USI mod except for CRP and FireSpitter from CKAN.

### ISSUE THREAD

**Issue by BobPalmer** [KSP-CKAN/NetKAN#4277]
In protest of CKAN's draconian de-listing stance, and due to the ARR nature of most of my mods, I am requesting these be de-listed.  CRP and FireSpitter are of course exceptions, both due to their licenses, and because I would rather not cause support issues for other modders.

Talk to me when CKAN decides that working with and respecting the wishes of the modding community are more important than 'market share'.  And congratulations for driving our community to increased adoption of ARR.

**Comment by Blu3wolf** [comment]
This could probably be closed now @BobPalmer ?

**Comment by Cassio38** [comment]
i was wondering why USI mods are not in Ckan... What is ARR ?

**Comment by BobPalmer** [comment]
They are not up at the moment as I have to resolve a dependency metadata issue.
