### ISSUE TITLE
Request for de-listing Sigma88 mods

### ISSUE THREAD

**Issue by Sigma88** [KSP-CKAN/NetKAN#4278]
I would like to request the de-listing of my mods from CKAN

the interested mods are:

- [Sigma Dimensions](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/SigmaDimensions.netkan)
- [Sigma Binary](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/SigmaBinary-core.netkan)
- [Galactic Neighborhood](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/GalacticNeighborhood.netkan)
- [Sigma: OPM Recolor](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/SigmaOPMRecolor.netkan)
- [Sigma: Jool Recolor](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/SigmaJoolRecolor.netkan)
- [Sigma: PluronKhato](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/SigmaPluronKhato.netkan)
- [Sigma: Antennas](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/SigmaRTExpansion.netkan)
- [Sigma: OPM Tilt](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/SigmaOPMExpansion.netkan)
- [Sigma: EveRecolor](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/SigmaStockRecolor.netkan)
- [Sigma: OuterSpaceComms](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/SigmaModExpansions.netkan)
- [Sigma Binary - DunaIke](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/SigmaBinary-DunaIke.netkan)

If you want to freeze them or remove them completely that's your choice.
Before I come back to ckan I want to see how the attitude evolves and I want to consider the possibility of managing my metadata myself.

The longer this request gets ignored, the less likely I am to come back to ckan in the future.

None of my mods will get any updates untill this has been solved.

**Comment by Sigma88** [comment]
I see you had time to add new mods to ckan but not time to respect your policy about de-listing.

I'll take care of that by myself if this cannot be achieved asking nicely

after all this is totally legal right?

**Comment by Sigma88** [comment]
Freezing is fine for me as well

**Comment by Sigma88** [comment]
I've updated the text of the issue

if anyone cares

**Comment by politas** [comment]
Sorry, I missed this one. Doing it now.

**Comment by politas** [comment]
You didn't include Eve Recolor. I'm going to assume you meant to include it.

**Comment by politas** [comment]
All Sigma88 mods removed.

**Comment by Sigma88** [comment]
I did include the eve recolor (third from last)

you probably missed it because the identifier was different
no problems there, I've added a PR

thanks for accepting to delist my mods and good luck with your "wake up call" to the ckan team

**Comment by yalov** [comment]
@Sigma88  are you still against CKAN?

**Comment by Sigma88** [comment]
I'm not against CKAN as long as everything is handled without asking me to do stuff

however, my mods are not updated to 1.7 and I don't really know how long before I will get the time to work on them
