### ISSUE TITLE
Please update ModularFlightIntegrator to version 1.1.5

### ISSUE THREAD

**Issue by ThomasKerman** [KSP-CKAN/NetKAN#4281]
1.1.5 fixed a critical bug that prevented me from using it in Kopernicus. Users who got Kopernicus through CKAN will get version 1.1.3, and therefor, they get the bug.

**Comment by politas** [comment]
Fixed in KSP-CKAN/CKAN-meta#1187

**Comment by politas** [comment]
UnfortunatelyThe latest version of MFI is not marked as compatible with KSP 1.1.3, so adding it as a dependency will make Kopernicus disappear for KSP 1.1.3 installs, due to KSP-CKAN/CKAN#1695.
