### ISSUE TITLE
Some help fixing KAC metadata

### ISSUE THREAD

**Issue by TriggerAu** [KSP-CKAN/NetKAN#4283]
Heya,

Have had some issues with people using KSP1.1.2 and the latest version of KAC.

What I need to do is change the version min and max values so KAC 3.6.3 is the last version for 1.1.2 and 3.7 and above is the 1.1.3 and above setup. I think I need to set the max version in 3.6.3 and teh min version in 3.7 and all future ones in netkan and in my .version files going forward.

Can I lean on someone to make the changes to netkan repo's? and do I need to also change any existing .version files in github so they stay right

Dave

**Comment by TriggerAu** [comment]
Also tried this for helping these peeps out to install the old version, but it fails - not sure why as it seems to fit the supported version thing

![image](https://cloud.githubusercontent.com/assets/3683611/16353327/fb89746e-3abb-11e6-9e2b-589d20961f93.png)

**Comment by politas** [comment]
Hi Dave, Sorry to take so long to look into this. I notice that your latest release is coming up as ksp_version_min 1.1.0. If it has the backward compatibility for that, then you don't need to change anything. If it isn't backward compatible, you should set "KSP_VERSION_MIN" in your .version file to "1.1.3". If you don't want to push a release just for that change, we can set an override in the .netkan to force ksp_min.

**Comment by DinCahill** [comment]
Do we need the go-ahead from @TriggerAu to merge this?

**Comment by politas** [comment]
We're responding to a direct author request, doing what he asked (for the old releases). Sorry, forgot to clear the "In Progress" labels.
