### ISSUE TITLE
PersistentRotation update not being displayed.

### ISSUE THREAD

**Issue by MarkusA380** [KSP-CKAN/NetKAN#4295]
I have PR submitted on SpaceDock and it is published to CKAN. But the updated version does not appear on CKAN.

**Comment by Blu3wolf** [comment]
https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/PersistentRotation.netkan
I can see the 1.0.2 version as the latest version on CKAN. Perhaps it didnt like your versioning changing from three digits to two digits?
Perhaps someone with more know how can chime in.

**Comment by Blu3wolf** [comment]
The CKAN meta file doesnt include any versions after 1.0.2, so presumably its something to do with the process that creates new CKAN files from the NetKAN files and external data from SpaceDock.

**Comment by Blu3wolf** [comment]
In version 1.0.2, your downloaded file structure was GameData/PersistentRotation. Now, its PersistentRotation/GameData/PersistentRotation. It looks like you didnt update the NetKAN file to reflect that (and no one else caught it either). Should be an easy fix now.

**Comment by Blu3wolf** [comment]
This should hopefully be fixed now?

**Comment by Blu3wolf** [comment]
Can download in CKAN now, should be okay to be closed I think.

**Comment by politas** [comment]
Closing as per above. Please reopen if problems persist, @MarkusA380
