### ISSUE TITLE
Reinstate mods

### ISSUE THREAD

**Issue by BobPalmer** [KSP-CKAN/NetKAN#4299]
All of my metadata is back up.  Please feel free to unfreeze any mod for which there is metadata (this would be all except the Malemute, that one will go up shortly).  If it is easier on the team for me to do a version bump, let me know and I can do so.  Just looking at the lowest-friction way of sorting this.

There *will* be a fairly large metadata change coming up (I am shuffling some dependencies), but I don't want that to delay getting these bits up there for folks to use.

Thanks!

**Comment by politas** [comment]
FirespitterCore, SoundingRockets and USITools are showing up as only 1.1.2 compatible, so a version bump would probably fix them if only their AVC files have changed. Everything else looks up to date.

**Comment by nobodyhasthis** [comment]
@politas here we go again. The above feedback that you have given is covered in the report I sent. There is a history here. There also an outstanding PR to help close the loophole mentioned. Can't be more specific on details. This not the time or place for that. I just wanted to leave a note here that underlines the connection  between the advice given above and information presented elsewhere.

**Comment by BobPalmer** [comment]
@nobodyhasthis - can we please cut with the secret squirrel stuff?

**Comment by politas** [comment]
This has all been fixed, now, all Bob's mods are available..
