### ISSUE TITLE
Kerbal Engineer Redux versioning confusion

### ISSUE THREAD

**Issue by Blu3wolf** [KSP-CKAN/NetKAN#4314]
KER is marked in CKAN as having a max KSP version of 0.25; despite this, you can still queue it for installing. KSP-AVC error perhaps?

**Comment by TeddyDD** [comment]
That's the .version file from newest release of KER  v1.1.1.0
```
{
	"NAME":"Kerbal Engineer Redux",
	"URL":"http://ksp-avc.cybutek.net/version.php?id=6",
	"VERSION":
	{
		"MAJOR":1,
		"MINOR":1,
		"PATCH":1,
		"BUILD":0
	},
	"KSP_VERSION":
	{
		"MAJOR":1,
		"MINOR":1,
		"PATCH":1
	}
}
```
![zrzut ekranu z 2016-07-01 12-41-37](https://cloud.githubusercontent.com/assets/4397533/16519432/39502ba4-3f89-11e6-9344-ce52b7b4c0da.png)

For me everything looks OK

**Comment by Blu3wolf** [comment]
Cant replicate the issue today.
