### ISSUE TITLE
KIS max version is displayed as 0.90, but is installable

### ISSUE THREAD

**Issue by Blu3wolf** [KSP-CKAN/NetKAN#4315]
KIS can be installed on a 1.1.3 installation, despite the GUI informing me the max version is 0.90 KSP. Additionally, the mod is only updated to 1.1.2 by the author.

**Comment by TeddyDD** [comment]
KIS netkan points to https://github.com/KospY/KIS/blob/master/KIS.netkan witch contains $vref.
.version file in KIS archive:
```
   "KSP_VERSION_MAX": {
        "MAJOR": 1, 
        "MINOR": 1, 
        "PATCH": 99
    }, 
```
So I'd say this is upstream error.

**Comment by politas** [comment]
I see the latest version as 1.2.12.0, with a min KSP of 1.1.3 and a max KSP of 1.1.99 
Looks like this has been fixed in the upstream?

**Comment by Blu3wolf** [comment]
Does seem to have been resolved.
