### ISSUE TITLE
Automatic ksp_verison bumps make mods not installable on N-1 KSP

### ISSUE THREAD

**Issue by lamont-granquist** [KSP-CKAN/NetKAN#4326]
This is kind of an annoying ksp_version bump:

https://github.com/KSP-CKAN/CKAN-meta/commit/ba3ff39bd2bc89dc24bfee5cfac7922a4c50b4d1#diff-c5ec697dca8bc261d2d8a3c94f3ac216

The files haven't changed, the hashes haven't changed, the ksp_version has been bumped though and a mod that worked fine on 1.1.2 is no longer installable now that 1.1.3 is out.

I suspect that without any other information that netkan is just assuming the latest version of KSP.  But it should check that it already has metadata and that the file has not been updated -- and then really it should write out ksp_min_version and ksp_max_version in order to bracket the versions appropriately.  Once a sha changes then the version floor should be updated and the ksp_version should be written out.

**Comment by NathanKell** [comment]
The issue here is that it is taking the metadata from Spacedock, and the maintainer of the mod told Spacedock that it is for KSP 1.1.3 rather than 1.1.2. We can add a netkan override to allow it in both cases, but that would be us overriding author-specified metadata.

**Comment by lamont-granquist** [comment]
Yeah, okay, lets not, lets educate mod authors better...
