### ISSUE TITLE
TACLS netkan isn't building a ckan for v0.12.2

### ISSUE THREAD

**Issue by NathanKell** [KSP-CKAN/NetKAN#4340]
Checked ckan-meta, no sign of it; if you check the repo the netkan points to, it's there.

**Comment by politas** [comment]
> Could not find GameData/ThunderAerospace entry in zipfile to install

**Comment by NathanKell** [comment]
Ah thanks! I bet it got packaged differently then, I'll fix up the netkan.

**Comment by politas** [comment]
Thanks.

**Comment by NathanKell** [comment]
Turns out there were two zips uploaded for the release, a source zip as well as the release zip, and CKAN pulled from the source zip. Fixed.
