### ISSUE TITLE
Having a min version of 1.1.3 causes build to fail

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#4343]
When the minimum version is 1.1.3, the build fails.  From examining the output, it appears to build a dummy 1.1.2 environment, and thinks that the mod isn't available for that.

Changing the min version from 1.1.3 to 1.1.2 solved the problem, but this is a workaround.

The version was being obtained from the .version file in the zip.

For reference, the following is the mod I was doing:
https://github.com/KSP-CKAN/NetKAN/pull/4332

**Comment by politas** [comment]
Strictly, this occurs when the ksp_version_min is 1.1.3 and ksp_version_max is 1.1.99, and it happens because the default ksp version in the build environment hasn't been updated, yet. @techman83, can you change it when you have a moment? I don't have access.

**Comment by techman83** [comment]
Everyone has access, it's the metatesting repository. I'll send a PR shortly.
