### ISSUE TITLE
-

### ISSUE THREAD

**Issue by Cassio38** [KSP-CKAN/NetKAN#4374]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

Please note that this repository is strictly for metadata (issues relating to incorrect information about mods, missing versions, or incorrect installations). If you want to suggest something or report a bug relating to CKAN as a whole, open the issue in: https://github.com/KSP-CKAN/CKAN

**Comment by politas** [comment]
You can use `File->Export Installed Mods...` to save a .ckan file for easy reinstallation of all available mods in your set. This is a really handy thing to do regularly, it helps a lot if CKAN starts playing up and you want to clean out your installation and refresh your GameData.
