### ISSUE TITLE
Wrong compatibility for Infernal Robotics

### ISSUE THREAD

**Issue by mscg82** [KSP-CKAN/NetKAN#4379]
The last version of Infernal Robotics (2.0.5) is marked as compatible with 1.1.2 and not wiht 1.1.3. As stated in this post http://forum.kerbalspaceprogram.com/index.php?/topic/104535-112-magic-smoke-industries-infernal-robotics-202/&do=findComment&comment=2668515 , the developer has released an archive with an incorrect .version file, but then he fixed it.
Is it possible that the error comes from the mod being indexed when the wrong archive was online?

**Comment by techman83** [comment]
Yes, that'll cause the issue. I've nuked the cache for Infernal Robotics and triggered an inflation.
```
2016/07/12 02:01:35 INFO Commiting InfernalRobotics-v2.0.5
```
A new version got committed afterwards, which has the updated version KSP-CKAN/CKAN-meta@2e29641e24c72d363327a880dc481a75348fafca

**Comment by mscg82** [comment]
Definitely solved the issue. I'm closing this one.
Thanks for your help!
