### ISSUE TITLE
ImprovedChaseCamera: 1.6.0 vs v1.5.0

### ISSUE THREAD

**Issue by adamsmd** [KSP-CKAN/NetKAN#4380]
I am not sure if this is the right place to report this.  If there is a better place, let me known and I'll move it there.

The client shows version "v1.5.0" of ImprovedChaseCamera as the latest version even though "1.6.0" is available and in the CKAN archive.  I believe this is due to the "v" at the front of "v1.5.0" but not "1.6.0".

**Comment by techman83** [comment]
You're correct, the NetKAN will need `"x_netkan_force_v" : true` added to it.
