### ISSUE TITLE
StockVisualEnhancements

### ISSUE THREAD

**Issue by adamsmd** [KSP-CKAN/NetKAN#4381]
I am not sure if this is the right place to report this.  If there is a better place, let me know and I'll move it to there.

As seen on [1], there is a new maintainer for StockVisualEnhancements who has just released a new version.  However, CKAN has StockVisualEnhancements currently marked as frozen so it is not picking up the new version.

[1] http://forum.kerbalspaceprogram.com/index.php?/topic/123455-depreciated-sve-do-not-enter/

**Comment by politas** [comment]
I'm working on it
