### ISSUE TITLE
Indexing is broken, also Jenkins

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#4383]
Subject says it all

**Comment by techman83** [comment]
So indexing looks fine to me. It's committed to CKAN-meta recently KSP-CKAN/CKAN-meta@899bf7ca3372d48f82cbbea7d07849604599b80e

But indeed Jenkins has stopped processing PRs.

In future it's super helpful if you could point out exactly what isn't working or why you suspect something isn't working.

**Comment by techman83** [comment]
Ok I gave Jenkins some attention and he's churning through the backlog.

**Comment by linuxgurugamer** [comment]
thank you
