### ISSUE TITLE
Netkan failing on 3897 for unknown reason

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#4390]
The message is extremely uninformative, can you take a look at it:

http://ci.ksp-ckan.org/job/NetKAN/3897/console

**Comment by techman83** [comment]
I'm not 100% sure, you might have to run it with `netkan.exe --verbose` and see if it fails locally.
```
8175 [1] WARN CKAN.NetKAN.Transformers.SpacedockTransformer (null) - Could not normalize URL: 
20059 [1] FATAL CKAN.NetKAN.Program (null) - Exception has been thrown by the target of an invocation.
```

**Comment by linuxgurugamer** [comment]
It was a bad license.  Any chance of improving the errors, rather than just having an exception, to actually display a message?

**Comment by linuxgurugamer** [comment]
That is actually the error which is shows when I ran it with the --verbose option.

It was a bad license, but instead of showing a readable error message, it just thows an exception

**Comment by politas** [comment]
I might actually have figured out enough of the code to make that happen. I'll look into it.

**Comment by techman83** [comment]
Ahhh, that'll do it. Yeah sounds like a proper exception needs to be thrown rather than the generic one.

**Comment by politas** [comment]
I looked into this ages ago, and from memory, the exception raised contains better info, but it is lost when it fails back to the calling method. I think it needs an error log message thrown.

**Comment by ayan4m1** [comment]
`TargetInvocationException` generally relates to exceptions thrown inside a constructor or static initializer.
