### ISSUE TITLE
WindowShineTR v12

### ISSUE THREAD

**Issue by tsmelt** [KSP-CKAN/NetKAN#4413]
WindowShineTR has been updated to v12 for KSP 1.1.3, but it's marked as frozen in NetKAN.

http://forum.kerbalspaceprogram.com/index.php?/topic/110080-113-windowshine-v12-stock-and-mod-dynamic-part-reflections-1-jul-2016/

**Comment by politas** [comment]
This mod has to be manually updated for each release, so many thanks for bringing it to our attention!

**Comment by tsmelt** [comment]
Awesome, thanks for acting so quickly!
