### ISSUE TITLE
Near FuturePropulsion not being updated

### ISSUE THREAD

**Issue by sargunster** [KSP-CKAN/NetKAN#445]
NetKan hasn't picked up version 0.4.0 of NearFuturePropusion from KerbalStuff.

[KerbalStuff](https://kerbalstuff.com/mod/347/Near%20Future%20Propulsion)

**Comment by AlexanderDzhoganov** [comment]
Seems like the bot picked it up - https://github.com/KSP-CKAN/CKAN-meta/blob/master/NearFuturePropulsion/NearFuturePropulsion-0.4.0.ckan
Thanks for the report, closing issue.
