### ISSUE TITLE
 [KSP 1.1.3] [x] Science! - KSP Science report and checklist (V4.20)

### ISSUE THREAD

**Issue by Homer-S** [KSP-CKAN/NetKAN#4507]
As confirmed by the .version file, "[KSP 1.1.3] [x] Science! - KSP Science report and checklist (V4.20)" is updated for 1.1.3, however, CKAN lists it with 4.19 for 1.1.2 only.

Relevant links:
http://forum.kerbalspaceprogram.com/index.php?/topic/107661-ksp-113-x-science-ksp-science-report-and-checklist-v420/

http://themoose.co.uk/ksp/x-science-v4.20.zip

Homer

**Comment by ayan4m1** [comment]
I can't reproduce this, are you sure you have refreshed your modlist?

<img width="114" alt="repro" src="https://cloud.githubusercontent.com/assets/266545/17587985/c41b6732-5f99-11e6-87c4-bddec8405b1d.PNG">

**Comment by Olympic1** [comment]
Shows correct version
