### ISSUE TITLE
KerBalloons v0.4.1 .ckan File for Upload

### ISSUE THREAD

**Issue by JoePatrick1** [KSP-CKAN/NetKAN#4517]
[KerBalloons-v0.4.1.txt](https://github.com/KSP-CKAN/NetKAN/files/418401/KerBalloons-v0.4.1.txt)

file is .txt as can't upload .ckan

**Comment by politas** [comment]
Does this new release not work on older versions of KSP?

**Comment by politas** [comment]
Thanks for the submission, @JoePatrick1!
