### ISSUE TITLE
'CriticalTemperatureGauge' matches an existing frozen identifier

### ISSUE THREAD

**Issue by formicant** [KSP-CKAN/NetKAN#4543]
Hi!
I’m new to CKAN. Recently, I became a new owner of the CriticalTemperatureGauge mod by Ravien.
I made a pull request to add a .netkan file: https://github.com/KSP-CKAN/NetKAN/pull/4542
The build failed with the message:
```
'CriticalTemperatureGauge' matches an existing frozen identifier: NetKAN/CriticalTemperatureGauge.frozen
Build step 'Execute shell' marked build as failure
```
I’ve realized my mistake, but what shall I do now? Should I edit the .frozen file or what? Please help.

**Comment by politas** [comment]
You just need to delete [CriticalTemperatureGauge.frozen in your patch-1](https://github.com/formicant/NetKAN/blob/patch-1/NetKAN/CriticalTemperatureGauge.frozen) branch so both changes are being examined together in the PR.
