### ISSUE TITLE
.netkan for mod exists but there is no maching ckan file

### ISSUE THREAD

**Issue by TeddyDD** [KSP-CKAN/NetKAN#456]
Recently I added two mods to netkan ( #437 ) OPTSpacePlaneParts works fine but there is no ckan file in CKAN-meta repo for OPTMk3MiniExpansion.  https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/OPTMk3MiniExpansion.netkan

I installed both mods and they working [screen](http://i.imgur.com/I4mA1YJ.png) (and .ckan generation was successful as well as Jenkins test: http://ci.ksp-ckan.org:8080/job/PR%20builder%20-%20NetKAN%20metadata/192/console) It seems there is a problem with netkan bot.

**Comment by hakan42** [comment]
Here they are:

* https://github.com/KSP-CKAN/CKAN-meta/tree/master/OPTMk3MiniExpansion
* https://github.com/KSP-CKAN/CKAN-meta/tree/master/OPTSpacePlaneParts

The netkan bot seems to have had a hiccup, I don't really understand the exception in the log files... Please observe if the next versions of those mods get picked up correctly.
