### ISSUE TITLE
Mission Controller 2 support

### ISSUE THREAD

**Issue by malkuth1974** [KSP-CKAN/NetKAN#457]
{
    "spec_version" : 1,
    "identifier"   : "Mission Controller 2",
    "$kref"        : "#/ckan/kerbalstuff/93",

"install": [
        {
            "file"       : "GameData/MissionControllerEC/",
            "install_to" : "GameData"
        }
    ]

    "depends": [
        { "name": "KERT" },
        { "name": "CommunityResourcePack" },
    ]

}

**Comment by hakan42** [comment]
Here you go:

* https://github.com/KSP-CKAN/NetKAN/pull/459
* http://ci.ksp-ckan.org:8080/job/PR%20builder%20-%20NetKAN%20metadata/222/console
