### ISSUE TITLE
Editor Extensions - broken homepage

### ISSUE THREAD

**Issue by damerell** [KSP-CKAN/NetKAN#4578]
The homepage link for Editor Extensions Redux is to http://forum.kerbalspaceprogram.com/index.php?/topic/127378-/ which doesn't work.

The forum insists that something follows the dash - anything, so eg http://forum.kerbalspaceprogram.com/index.php?/topic/127378-stoatface/ works.

**Comment by politas** [comment]
Thanks for the heads-up
