### ISSUE TITLE
Realism Overhaul and TACLS

### ISSUE THREAD

**Issue by NathanKell** [KSP-CKAN/NetKAN#4593]
First, apologies for not being able to do more at present, and therefore begging you all to do so. :)
(1.2 is OMGBUSY atm)

TACLS recently updated and changed the location of its config file. RO also moved its file. However, neither Config netkan entry (those which provide TACLS-Config) were updated, causing conflicts.

Can someone unfreeze the TACLS-stock config and point it at the new correct place? And put the TACLS netkan back to requiring a config? (I'm not sure why that was _ever_ dropped). The RO TACLS config netkan appears to still be correct.

**Comment by Olympic1** [comment]
Referenced PR will fix this issue

**Comment by politas** [comment]
I think TACLS-StockConfig was dropped because it was pointing to a non-existent file, thanks to it being moved to a new location.
