### ISSUE TITLE
PlanetShine 2.5.0 re-uploaded: need re-indexing with updated URL

### ISSUE THREAD

**Issue by valerian** [KSP-CKAN/NetKAN#4636]
Hi,

Yesterday I re-uploaded the zip file for PlanetShine 2.5 to Curse without changing its version number, because I wanted to fix the `.version` file included in it for MiniAVC, however CKAN-meta is still linking to the old one.

Could you please somehow re-index it with the proper file ID and hashes etc?

The files in question: https://kerbal.curseforge.com/projects/planetshine/files?filter-game-version=&filter-status=
The new updated and proper one: https://kerbal.curseforge.com/projects/planetshine/files/2330189
The old deprecated one (which I set on the "archived" status): https://kerbal.curseforge.com/projects/planetshine/files/2292131

I also uploaded about an hour ago the new version 2.5.1 for KSP 1.2, which I believe should be auto-indexed soon without issue.

Thank you!

**Comment by valerian** [comment]
Actually, I see now that you have created an alternate version `1:0.2.5` along the original `0.2.5` to kind of force support for KSP 1.1.* : this version `1:0.2.5` should be removed, and `0.2.5` should be naturally updated according to the metadata from Curse and/or the GitHub repository, since now I properly set PlanetShine 0.2.5 to officially support KSP 1.1.0 to 1.1.3

https://github.com/KSP-CKAN/CKAN-meta/tree/master/PlanetShine

**Comment by Olympic1** [comment]
@valerian PR's made

**Comment by valerian** [comment]
Thank you!

**Comment by valerian** [comment]
I think it's good now, this issue can be closed
