### ISSUE TITLE
RoverScience Revisited Duplicated on CKAN

### ISSUE THREAD

**Issue by theSpeare** [KSP-CKAN/NetKAN#4644]
This is definitely my fault. I uploaded to SpaceDock with CKAN integration ticked; but after two days of no response I incorrectly thought that I needed to submit a NETKAN file AS WELL. So it looks like it's been duplicated. Probably best to delete the manually submitted netkan.

![image](https://cloud.githubusercontent.com/assets/6429228/18605222/0457797c-7ce0-11e6-944e-896fb895abd4.png)

Correct identifier: RoverScienceRevisited
Incorrect identified: RoverScience

any other information needed?

**Comment by politas** [comment]
What's the status of the original Rover Science?

**Comment by theSpeare** [comment]
**Problem's been fixed.** Only one "RoverScience Revisited" is on CKAN now, thank you!

_the "original" Rover Science (e.g. not "RoverScience Revisited") was never added to CKAN. However when I chose to manually input the identifier for RoverScience Revisited I decided to do it with "RoverScience" for simplicity's sake_
