### ISSUE TITLE
Add MemGraph?

### ISSUE THREAD

**Issue by rkagerer** [KSP-CKAN/NetKAN#4648]
I noticed this mod by Padishar (@Gerry1135) doesn't appear in CKAN: http://forum.kerbalspaceprogram.com/index.php?/topic/139128-113-memgraph-10010-with-stutter-reduction/&page=1

Granted, it's geared toward intermediate-to-advanced users, but could we add it?

**Comment by politas** [comment]
A good suggestion. I've sent the author a message on the forums.

**Comment by politas** [comment]
Got a positive reply from Padishar.

**Comment by Gerry1135** [comment]
Both of the commits in this issue say ksp_version 1.2 but the commit in the linked issue (#4653) says ksp_version 1.1.3 and references the 1.0.0.10 version of MemGraph.  That is the correct version for KSP 1.1.3 but are the bits saying 1.2 going to cause issues?

**Comment by politas** [comment]
The latest release on GitHub is the 1.2 version, and NetKAN is only inflating the latest release, so 1.0.0.10 should remain as 1.1.3 as long as you don't remove all 1.2 releases. If you wish to upload a new 1.1.3 release, we'll need to rejigger things, but as long as that's the final 1.1.3 release, it should be all good.
