### ISSUE TITLE
Add KSTS?

### ISSUE THREAD

**Issue by mmoench** [KSP-CKAN/NetKAN#4652]
Hello, could you add the "Kerbal Space Transport System" to the repo: https://github.com/mmoench/KSTS ?
It should already have a valid netkan-file. Thnaks.

**Comment by politas** [comment]
Do you wish to continue hosting your own netkan, or would you prefer it be added to the main repository to be curated here?

**Comment by mmoench** [comment]
I think I would like to keep hosting it myself.

**Comment by politas** [comment]
Ok. I think you have an extra comma at the end of your install block that needs to be deleted.

**Comment by mmoench** [comment]
I've removed the additional comma. Thanks.
