### ISSUE TITLE
Crash if failed to download mods

### ISSUE THREAD

**Issue by jansenfuller** [KSP-CKAN/NetKAN#4673]
There has been a recurring issue where if a mod cannot be found (404), the mod installations, regardless of where it is in the list of mods, will error and only a cancel option can be selected in the bottom right hand corner.
After that you will be taken back to the first window asking you select recommended mods to install. Clicking continue will create a error dialog box stating the error. You cannot click to other tabs and clicking either Continue or Cancel will invoke the same error box.

Error output found [here](http://pastebin.com/0bbxmkKW)

**Comment by Dazpoet** [comment]
Sorry for catching this so late, afaik this is a somewhat known error but I can't really find an issue on it at this moment over in https://github.com/KSP-CKAN/CKAN/issues where issues like this one belong.

This repository is for metadata errors like if a file is being installed incorrectly through CKAN or if we're missing a dependency. Therefore I'll close this issue but encourage the opening of a similar one in the appropriate repository.
