### ISSUE TITLE
Phoenix industries unable to update 

### ISSUE THREAD

**Issue by AsHalt** [KSP-CKAN/NetKAN#4676]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

Please note that this repository is strictly for metadata (issues relating to incorrect information about mods, missing versions, or incorrect installations). If you want to suggest something or report a bug relating to CKAN as a whole, open the issue in: https://github.com/KSP-CKAN/CKAN

------------------------------
**Error Report**
------------------------------

Downloading "https://spacedock.info/mod/245/Phoenix Industries - Cargo Resupply System/download/2.1"
Downloading "https://spacedock.info/mod/246/Phoenix Industries - Boosters/download/2.0"

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/NetKAN/issues/new

Please including the following information in your report:

File           : GameData/CTN/Flags/Thumbs.db
Installing Mod : PhoenixIndustriesFlags 2.0
Owning Mod     : PhoenixIndustriesAres
CKAN Version   : v1.20.1-0-gd41fe54 (beta)

Your GameData has been returned to its original state.

Error!
-----------------------------------------
I thought my version (CKAN) was the latest , Plus I have redownloaded the .exe (v1.20.1 / d41fe54) again from the site after the previous attempt. 

Was try to update the following : 
- Phoenix Industries - Cargo Resupply System
- Phoenix Industries - Boosters

**Comment by Olympic1** [comment]
Fixed with #4678
