### ISSUE TITLE
EVE for KSP 1.2

### ISSUE THREAD

**Issue by WazWaz** [KSP-CKAN/NetKAN#4684]
The original author is AFK, so I have temporarily (and unilaterally) taken responsibility for maintenance releases. The release for KSP is here:

https://github.com/WazWaz/EnvironmentalVisualEnhancements/releases/tag/EVE-1.2-1

There are now a number of EVE config mods (and probably more on the way). If there is anything that I could do to smooth the way users choose which configs to use, please let me know. All too often in the past, users ended up with both the simple default configs *and* other configs (eg. SVE), which is of course a pain for everyone. Possible CKAN already handles this, in which case, bravo!

**Comment by politas** [comment]
With SVE, we've put in a conflict between SVE and EVE, and grabbed all the EVE files from the SVE distribution. 

Probably the most helpful thing would be a clear explanation of which files are the core files, and which are the configuration. That would help us to make modular packages. But I fear a lot of EVE configs are only partial replacements, rather than complete sets of config files?

**Comment by WazWaz** [comment]
Has SVE even made a release for KSP 1.2 yet?

The core files are those in the AnyCPU-EVE-Release.zip file, the configs in the other file. I'm pretty sure CKAN already distinguished between the two (as "EnvironmentalVisualEnhancements" and "EnvironmentalVisualEnhancements-Config"). It's really just the source of content that has changed for KSP 1.2.

**Comment by WazWaz** [comment]
BTW, the forum link should now also move, to http://forum.kerbalspaceprogram.com/index.php?/topic/149733-environmentalvisualenhancements

Users were already having trouble following outdated instructions, so I opened a new thread.

**Comment by WazWaz** [comment]
SVE is certain a complete config replacement. KSPRC (which isn't on CKAN, AFAIK) also entirely supplies it's own. I'm not aware of any mod that just tweaks the "BoulderCo" files that constitute the configs shipped with EVE.

**Comment by politas** [comment]
KSPRC will probably never go on CKAN. It overwrites some Squad KSP files, which CKAN won't do.

**Comment by politas** [comment]
Do you have any hint from rbray89 that a smooth transition back to his or her control will happen?

**Comment by WazWaz** [comment]
No, unfortunately they've been completely silent since July or so. But you certainly have my word that if they want it back, I'd immediately comply. (Re KSPRC - yes, really needs to use ModuleManager that one).

**Comment by WazWaz** [comment]
I've posted another update (https://github.com/WazWaz/EnvironmentalVisualEnhancements/releases/tag/EVE-1.2-2)
