### ISSUE TITLE
SVE Updates for 1.1.3 and 1.2

### ISSUE THREAD

**Issue by rkagerer** [KSP-CKAN/NetKAN#4711]
There are new SVE releases for KSP [1.1.3](http://forum.kerbalspaceprogram.com/index.php?/topic/143288-12-stock-visual-enhancements-111/&do=findComment&comment=2803196) and [1.2](http://forum.kerbalspaceprogram.com/index.php?/topic/143288-12-stock-visual-enhancements-111/&do=findComment&comment=2803120).

Note this ticket might relate to #4684.

SVE's for KSP 1.1.3 is at https://github.com/Galileo88/StockVisualEnhancements/releases/tag/1.0.83
SVE's for KSP 1.2 is at https://github.com/Galileo88/StockVisualEnhancements/releases/tag/1.1.1

**Comment by Olympic1** [comment]
- [ ] 1.1.3
- [ ] 1.2
