### ISSUE TITLE
Missing mods, KSP interstellar extended has been updated and is missing, so is Konstruction and Kraken science

### ISSUE THREAD

**Issue by xXtheguy52Xx** [KSP-CKAN/NetKAN#4741]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

Please note that this repository is strictly for metadata (issues relating to incorrect information about mods, missing versions, or incorrect installations). If you want to suggest something or report a bug relating to CKAN as a whole, open the issue in: https://github.com/KSP-CKAN/CKAN

**Comment by Olympic1** [comment]
These don't show up because their dependencies aren't met
