### ISSUE TITLE
Requesting StationPartsExpansion

### ISSUE THREAD

**Issue by leandrotlz** [KSP-CKAN/NetKAN#4743]
This mod provides many new stockalike parts, including a very needed 2.5m "hub":

http://spacedock.info/mod/736/Stockalike%20Station%20Parts%20Expansion
https://kerbal.curseforge.com/projects/stockalike-station-parts-expansion-0-3-2
https://github.com/ChrisAdderley/StationPartsExpansion

The version in Github was recently (9 hours ago) patched to work with KSP 1.2.

**Comment by Olympic1** [comment]
This mod is already available on CKAN 'till 1.1.2. Nertea will release an update for 1.2 when he finds the mod is ready.
