### ISSUE TITLE
Mod metadata seems to be reverted to an old version

### ISSUE THREAD

**Issue by nimobeeren** [KSP-CKAN/NetKAN#4752]
Hi,

I am the author of the mod MusicMute, which is currently available on the CKAN. When trying to install it, I recently noticed that the CKAN client was showing an older version of my mod (1.1.0), which supports up to KSP 1.0.5. When looking in the NetKAN repository, it seems as though this is incorrect ([see this file](https://github.com/KSP-CKAN/NetKAN/blob/add4e5f8522ef30211320d147cc356c9f87c3017/NetKAN/MusicMuteContinued.netkan)). This older version had the identifier `MusicMute`, which was later merged with another mod called `MusicMuteContinued`.

Also, I have updated the mod with a new release 1.1.3, which supports KSP 1.2. This release is available on [GitHub](https://github.com/nimobeeren/MusicMute/releases/tag/1.1.3).

What I want to do is:
* Make the CKAN client show the same data as [this file](https://github.com/KSP-CKAN/NetKAN/blob/add4e5f8522ef30211320d147cc356c9f87c3017/NetKAN/MusicMuteContinued.netkan)
* Update the metadata so that KSP 1.2 is supported

Is it enough to change the value of `"ksp_version"` to `"1.2"`, or is there something else I need to do in order to let the CKAN client serve my new release version 1.1.3?

**Comment by politas** [comment]
So you've taken over the "MusicMuteContinued" netkan, rather than reviving the "MusicMute" iidentifier . updating the "ksp_version" to "1.2" should do the trick. It looks like the machine that runs our bot is having some issues at the moment, which would explain why your new release has not yet appeared.

**Comment by nimobeeren** [comment]
Thanks! I changed the version value so I'll wait and see if CKAN updates properly.
