### ISSUE TITLE
Update HAIT Lander Orientation Improvement; it works in 1.2

### ISSUE THREAD

**Issue by rkagerer** [KSP-CKAN/NetKAN#4770]
Lander Orientation Improvement works in KSP 1.2 (I've tested it), but CKAN doesn't know that.  Could you please update the CKAN file (which I'm guessing is [here](https://github.com/KSP-CKAN/NetKAN/blob/ada4f8324490724f517801fdd0bf2432612cf9bf/NetKAN/LanderControl.netkan), although looking at that file I'm not clear why CKAN thinks its Max KSP Version is 1.3)?

**Comment by politas** [comment]
CKAN is getting the KSP version from Curse, according to that netkan

**Comment by rkagerer** [comment]
Thanks politas.  I don't think I'm able to update their Curse page (?), and I [can't find a forum thread](http://forum.kerbalspaceprogram.com/index.php?/search/&q=Lander%20Orientation%20Improvement) to contact the author.

**Comment by politas** [comment]
Righto - That's how we fix that, then.

**Comment by rkagerer** [comment]
Cool; thanks!
