### ISSUE TITLE
http://spacedock.info/mod/836/QuizTechAeroPackContinued

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/NetKAN#4789]
This mod is 1.2 ready but not showing in the CKAN client

**Comment by Olympic1** [comment]
The mod is added to CKAN but its dependencies aren't met. The mod will show if `BDAnimationModules` and `RasterPropMonitor-Core` are updated for 1.2

**Comment by Dazpoet** [comment]
Since a complete answer has been given I'll close this for now, feel free to open this up again if you feel I've closed this in error.
