### ISSUE TITLE
better error message...

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/NetKAN#4820]
I know this is my own lack of attention but if you try to "update" a mod while KSP is running can you check for this and tell the user "Hey you cant update the mod if the game is running!!"

as I just had a strange issue where I had minimized KSP and forgot it was running...  then went back and ran up CKAN again.  installed some new mods, which of course worked as you do not overwrite any files.  but then I tried to update some mods and it failed repeatedly.  obviously it was my own lack of attention.  but still it could be a good thing to check for and warn rather than the generic error it gives about the .dll being registered to the mod, but not deleted...

**Comment by politas** [comment]
Can you open this as a feature request [issue on the main CKAN repo](https://github.com/KSP-CKAN/CKAN/issues)? Issues on this repository are meant to deal with metadata problems.
