### ISSUE TITLE
Carrier Vessel eXpansion 

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/NetKAN#4859]
This mod is 1.2 ready.  could we get it added to CKAN for 1.2?

**Comment by ayan4m1** [comment]
I _would_ recommend forwarding the request on to the mod author, except that most modders don't like being asked about compatibility changes. We don't change that data on request, it is up to the author.

**Comment by politas** [comment]
As far as I can tell, that mod is not currently on CKAN at all. I've sent a message to the mod author to discuss adding it.

**Comment by politas** [comment]
Mod author has approved.
