### ISSUE TITLE
Include Landertron mod

### ISSUE THREAD

**Issue by Naesstrom** [KSP-CKAN/NetKAN#4863]
Hi

Attached is the netKAn file for the mod Landertron,

[Landertron.zip](https://github.com/KSP-CKAN/NetKAN/files/563618/Landertron.zip)

Best regards

**Comment by politas** [comment]
Message sent to mod author on forums.

**Comment by politas** [comment]
Kerbas_ad_astra has asked for Landertron to not be added to CKAN at this time.
