### ISSUE TITLE
Update Crowd Sourced Science compatibility

### ISSUE THREAD

**Issue by rkagerer** [KSP-CKAN/NetKAN#4875]
Apparently the mod [works with 1.2](http://forum.kerbalspaceprogram.com/index.php?/topic/92332-broken-in-12-crowd-sourced-science-biome-reports-everywhere-may-3rd-squad-bug/&do=findComment&comment=2828459) (and likely 1.2.1), save for a minor issue that folks don't really seem to mind as it doesn't break anything.

Maybe the information here could be updated to make this mod available to users again?

@DuoDex

**Comment by IronCretin** [comment]
The mod is available, just install it yourself. No need to have CKAN list a broken mod and then have people complain to the author when it doesn't work on a version it's not compatible with.

**Comment by Olympic1** [comment]
The reason because its not added for 1.2 is that @DuoDex asked to keep it on hold for now.

**Comment by rkagerer** [comment]
Totally understand that; didn't realize the original author had made that request.  Thanks.
