### ISSUE TITLE
MODULE MANAGEr

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/NetKAN#4876]
For some reason my CKAN is telling me Module manager is now "AD" however in order to fix this I need to reinstall it.  but in order to reinstall it I need to first delete it.  but after I delete it CKAN sees it is gone and will now let me select it for reinstall, but then it wants to uninstall every mod in the list that requires MM.

is there some way to get CKAN to just install MM without uninstalling every other mod on the list?

maybe make a option in the config some where that tells CKAN:

**"yes, I know what I am doing, and I take full responsibility.  Just over-write the file."**

**Comment by politas** [comment]
Unfortunately not. What you can do is save a "favourites" list to reinstall all the currently installed mods easily. They should all be cached, so the reinstall is very quick.

**Comment by Bit-Fiddler** [comment]
how do you make a favorites list?

**Comment by Olympic1** [comment]
1. Install all mods that you want using CKAN.
2. Click `File` -> `Export installed mods...`
4. Save file
5. Uninstall **ALL** mods
6. Click `File` -> `Install from .ckan...`
7. Select the saved file from step 4

**Comment by Bit-Fiddler** [comment]
ah ok... easy enough, I was looking for something called "Favorites"...

**Comment by politas** [comment]
There was a plugin that tried to convert AD mods into CKAN handled ones, but it never worked and the developer has given up on it.

**Comment by Dazpoet** [comment]
Closing this basen on the issue appering to be resolved, if I am in error feel free to open it again
