### ISSUE TITLE
KSP-AVC

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/NetKAN#4877]
KSP-AVC is also reporting as "AD" yet if I delete the KSP-AVC directory, it does not change from "AD" to uninstalled in the CKAN list.  it is still showing up as "AD".  I assume this is due to it is looking or ANY copy of the miniavc.dll... however many mods have this .dll in their directory so KSP-AVC will always show up as "AD".  could CKAN stop looking for the miniavc.dll?

**Comment by politas** [comment]
Have you done a Refresh and restarted CKAN after deleting AVC?

**Comment by Bit-Fiddler** [comment]
yes.  but is is reporting mini avc is installed as if finds every copy of miniavc.dll in every mod in the directory.

**Comment by politas** [comment]
I suspect there was a temporary glitch with the zip file for the KSP-AVC 1.1.6.2 release, where it had MiniAVC instead of AVC. Can you upload your registry.json file?

**Comment by Bit-Fiddler** [comment]
to drop box is fine?

**Comment by politas** [comment]
Ok, open your registry.json file in a text editor (might need something better than Notepad) and search for this string

    MiniAVC": {

Delete that entire line and the rest of that entry down to and including the line just above "MiniAirbrakes"

**Comment by Bit-Fiddler** [comment]
oh sorry I just wiped my KSP install and am rebuilding it from scratch.   so did not look back at this issue.  so this can be closed I guess, unless it wants to be elevated as a real CKAN problem and a fix implemented.
