### ISSUE TITLE
Future Weapons Updated

### ISSUE THREAD

**Issue by Aerolfos** [KSP-CKAN/NetKAN#4898]
All right, I am the author of Future Weapons, which is now updated to 1.2.1.
It used to be on CKAN (I can still find it, but using the old version) it may however be linked to Spaceport, rather than Spacedock. 

That needs to be updated, and it also has the dependency BDArmory, which is for now defunct. Instead, it now uses BDArmory Continued.

Requesting some help to update those two, and get it working again.

**Comment by politas** [comment]
The .netkan all looks fine and 3.3 ought to be available. Not sure why it isn't.

**Comment by Olympic1** [comment]
@Bit-Fiddler I can install it just fine.

Did you select other mods first, and then Future Weapons.
Did you have other mods installed already.
Or something else

**Comment by Aerolfos** [comment]
Yeah I am getting the error too.
I do have a bunch of other mods installed, but selected only Future Weapons.

Is the requirement for it still just BDArmory (which is discontinued), or BDArmory Continued?

**Comment by Olympic1** [comment]
It is `BDArmoryContinued` but if you set the name to to `BDArmory` it selects it the continued version.

I just selected the mod with no error:
![knipsel](https://cloud.githubusercontent.com/assets/8020752/20116172/8d613b1a-a5fb-11e6-9f58-edc98fa17859.PNG)

**Comment by Aerolfos** [comment]
Huh. That is as it should be.

I cannot select it though.

**Comment by politas** [comment]
Can you set filter to "All" and look for BDArmory installations?

**Comment by Aerolfos** [comment]
BDArmory Continued is installed, via CKAN.

**Comment by politas** [comment]
Huh. So much for that idea. Can you upload your registry.json file?

**Comment by Aerolfos** [comment]
Zipped it since apparently .jsons are not allowed, but here you go:
[registry.zip](https://github.com/KSP-CKAN/NetKAN/files/579423/registry.zip)

**Comment by politas** [comment]
Can you successfully install any other mods?

**Comment by Aerolfos** [comment]
Attempted install of C.A.L++, another addon for BDArmory... no problems. Installed just fine.

**Comment by politas** [comment]
I think the problem may be with the version restriction on BDArmory in Future Weapons dependency. It looks like it's preventing CKAN from using the "provides" of BDArmory. My testing seems to support that theory.

**Comment by politas** [comment]
@Aerolfos, can you test this and report back?

**Comment by Aerolfos** [comment]
Sadly, still getting same error it seems.

**Comment by politas** [comment]
You're getting that same "System.NullReferenceException: Object reference not set to an instance of an object"?

Can you run "ckan --debug > debugoutput.txt" from a command line, attempt to install Future Weapons again, than post that debugoutput.txt file?

**Comment by Aerolfos** [comment]
Nope, no idea how to run command lines...
It is the same error though.

**Comment by politas** [comment]
You're on Windows 10? Type "command" into the Start button search, you should see a "Command Line" entry to run. Then you'll need to use the "cd command to go to the directory where you downloaded CKAN, so if it is in your downloads folder, I think you can just "cd downloads". If you can't figure this out, there's not much more we can do to solve the specific problem, and it'll be a lot easier if you clear out your KSP GameData folder, delete your CKAN/registry.json, and reinstall everything fresh.

**Comment by Aerolfos** [comment]
Yes windows.

And as programs just love doing, running it in debug mode has no error message appear, and it seems to work just fine... 
I'll just put the debug text anyway.

[debugoutput.zip](https://github.com/KSP-CKAN/NetKAN/files/587199/debugoutput.zip)

**Comment by politas** [comment]
The "> debugoutput.txt" part of the command explicitly directed all the output to that text file, so you wouldn't see anything.

**Comment by Aerolfos** [comment]
That way yes, but it did indeed install. CKAN did not crash or anything, but rather acted as expected...

**Comment by politas** [comment]
Ok, can you uninstall it and reinstall successfully without using any --debug flag? (If you're happy to just leave it and get on with playing KSP, I completely understand)

**Comment by Aerolfos** [comment]
Uninstalled, then reinstalled by launching CKAN completely normally.
Exactly what you would expect, no errors this time.

**Comment by politas** [comment]
Ok, closing issue.
