### ISSUE TITLE
BoxSat is missing its OptionalModuleManagers files

### ISSUE THREAD

**Issue by hakan42** [KSP-CKAN/NetKAN#490]
Those MM files being optional an all, we should have a new netkan, similar to the "BoxSat-prototypes" file, to allow installation of those files. Maybe even one for each MM file, but this might be slight overkil :smiling_imp:

**Comment by amedee** [comment]
If BoxSat implements NEEDS[] then the OptionalModuleManagers files can be moved to the GameData/BoxSat folder.
I would do the work myself and send a pull request, however i cannot find the BoxSat GitHub repository to fork from.

**Comment by plague006** [comment]
Is this still an issue we need to resolve?

**Comment by plague006** [comment]
I'm closing this since there's no response in a week. If anyone feels this was closed prematurely just comment and I'll reopen.

**Comment by amedee** [comment]
It's an issue for BoxSat, not for CKAN. Can anyone point me to the BoxSat issue tracker? I can't find it, my google-fu is weak today.

**Comment by plague006** [comment]
All I found were the [forum thread](http://forum.kerbalspaceprogram.com/threads/91616) and [curseforge page](http://kerbal.curseforge.com/ksp-mods/224250-boxsat).
