### ISSUE TITLE
Gravity turn continued will not install

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/NetKAN#4912]
when you select this mod from the list the green check never lights up and you can't click apply changes. looking at the list I see no mods highlighted in red so I assume this is not from a compatibility issue.

**Comment by Olympic1** [comment]
Cannot replicate this problem

**Comment by politas** [comment]
Switch your filter to "All" and see if you have an autodetected (AD) copy of GravityTurn. That's the only conflicting mod. It may be that CKAN has mis-identified the previous GravityTurnContinued release as GravityTurn, in which case uninstalling the existing GravityTurnContinued, refreshing and then installing the new GravityTurnContinued should do the trick.  

Also noted that CKAN has the release order out of whack so #4915.

**Comment by Bit-Fiddler** [comment]
ah yes it was not reporting files in use or anything like that, it just never gave me the install option.  but indeed there was an old version installed.
