### ISSUE TITLE
master tech aerospace will not install

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/NetKAN#4913]
I assume this is due to looking for the original Quiztech mod.  but the mod is now quiztech continued.

**Comment by Olympic1** [comment]
Mod requires `QuizTechAeroPack-internals` but it isn't available for 1.2 because it depends on `RasterPropMonitor` that hasn't had a release for 1.2 yet.

**Comment by Dazpoet** [comment]
Looking at MasterTechAerospace something seems screwy, lacking a better word. My client reports that the latest version is indeed 1 and compatible with my 1.2.1 install. However it lists itself as having [max ksp version of 1.1.2](http://imgur.com/gxZomh9) which is the case for the "highest" version of the mod, namely version 4.

I wonder if our logic is freaking out somewhere? Interesting case :)

**Comment by politas** [comment]
It's [not our logic that's screwy](https://spacedock.info/mod/393). Classic case for an epoch.

**Comment by Dazpoet** [comment]
just looking in the client I saw a bunch more mods with similar issues. I shall leave that problem for a rainy day.

**Comment by politas** [comment]
Inconsistent Mod versioning is a definite problem for us.
