### ISSUE TITLE
TAC-LS is not listed for install

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/NetKAN#4914]
TAC-LS is not listed as an install option but the "Stock Config" option is listed.  this will not install however as it reports TAC-LS is not available.

**Comment by Olympic1** [comment]
`TACLS` depends on `CommunityResourcePack` which isn't availbale for 1.2.1

**Comment by Dazpoet** [comment]
CRP has updated and atleast for me TAC-LS shows up now :)

**Comment by politas** [comment]
It's not going to install properly until #4894 is merged, though

**Comment by Dazpoet** [comment]
The problem has been resolved and the files merged so I will close this now.
