### ISSUE TITLE
Kerbal Planetary Base Systems missing

### ISSUE THREAD

**Issue by nerdmastax** [KSP-CKAN/NetKAN#4919]
Kerbal Planetary Base Systems is missing from ckan, according to the dev:

"The mod has a .ckan file on the CKAN-meta repository and therefore should be available via CKAN. Please contact the developers of CKAN to refresh or fix this, i can't do much about that. "

perhaps somebody can figure out why.

Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

Please note that this repository is strictly for metadata (issues relating to incorrect information about mods, missing versions, or incorrect installations). If you want to suggest something or report a bug relating to CKAN as a whole, open the issue in: https://github.com/KSP-CKAN/CKAN

**Comment by politas** [comment]
This will not appear on KSP 1.2.1 installations because one of its dependencies, Community Resource Pack, has not been updated for KSP 1.2.1 yet. RoverDude promised to have a new release out a few days ago, so hopefully, it won't be too long.
