### ISSUE TITLE
WernherChecker support

### ISSUE THREAD

**Issue by Magion** [KSP-CKAN/NetKAN#492]
Hi there,
I would like to add CKAN support for my mod WernherChecker.

Here is the .netkan:
```
{
    "spec_version" : 1,
    "identifier"   : "WernherChecker",
    "$kref"        : "#/ckan/kerbalstuff/91",
    "x_netkan_license_ok": true,
    "resources": {
    	"repository": "https://github.com/Magion/WernherChecker"
  },
}
```

Thanks!

**Comment by hakan42** [comment]
Here you go: http://ci.ksp-ckan.org:8080/job/PR%20builder%20-%20NetKAN%20metadata/266/console

The AVC parser is not really happy with your embedded .version file though, you might want to look into this before uploading your next release.
