### ISSUE TITLE
Stock Visual Enhancements missing

### ISSUE THREAD

**Issue by okozlovsky** [KSP-CKAN/NetKAN#4940]
CKAN does not list SVE at all at the moment. The latest version 1.1.4 is compatible with KSP 1.2.1.
SVE forum page: http://forum.kerbalspaceprogram.com/index.php?/topic/143288-121-113-stock-visual-enhancements-114-1083/
Github release: https://github.com/Galileo88/StockVisualEnhancements/releases

**Comment by ayan4m1** [comment]
https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/EnvironmentalVisualEnhancements.netkan#L9

Max version of one of SVEs dependencies is 1.2.0 - bug 1695 in CKAN is why you aren't seeing the mod.

**Comment by politas** [comment]
Scatterer in particular is missing.
