### ISSUE TITLE
InFlightFlagSwitcher

### ISSUE THREAD

**Issue by adsii1970** [KSP-CKAN/NetKAN#4959]
I posted the updated mod, as I have been granted permission from iPeer to adminster the mod. Please include my name in the meta-data that shows up in the cKAN directory.
Also, the exact page for the continued mod is: 
http://forum.kerbalspaceprogram.com/index.php?/topic/151525-121-in-flight-flag-switcher-v-11-04-11-2016/#comment-2839102

I had included this information in the pull request...or so I thought...

**Comment by politas** [comment]
I haven' seen a PR for this, and can't find one now, so...

**Comment by adsii1970** [comment]
What's a PR? The new OP on the forum contains the links to iPeer's permissions as well as the new file. What else do I need to send you? I just want to get this right so I know how to handle the next updated mod. 

Thank you for your help...

**Comment by politas** [comment]
That thing I linked to this - InFlightFlagSwitcher - new maintainer #4961 - is a Pull Request (PR)  that changes the mod over to your repo, adjusts the installation instructions to match the new zip file folder structure, updates the resources links, and lists you and iPeer as co-authors.

**Comment by adsii1970** [comment]
Ok, thanks! I had no idea what it was as I am fairly new to GitHub… 

 

 

Alan D. Simmons II

PO Box 274  Henderson, KY 42419-0274

(270) 925-5506

 

"Democracy and socialism have nothing in common but one word, equality. But notice the difference: while democracy seeks equality in liberty, socialism seeks equality in restraint and servitude."

- Alexis de Tocqueville, French Political Philosopher and Historian, (1805-1859)

 

My faith-based blog:  <http://www.thedailywalk.org/> www.thedailywalk.org

My political based blog:  <http://www.right-of-center.com/> www.right-of-center.com
