### ISSUE TITLE
distant object enhancement reports 1.2.x for KSP but i do not see this for my 1.2.1 game

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/NetKAN#4969]

**Comment by politas** [comment]
The .version file distributed with v1.1.8 of DistantObjectEnhancement specifies only 1.2.0, and the `https://raw.githubusercontent.com/MOARdV/DistantObject/master/GameData/DistantObject/DistantObject.version` says the same.

**Comment by Bit-Fiddler** [comment]
ah this was based off his forum title...


> [1.2.x] Distant Object Enhancement bis v1.8.1 (20 October 2016)

so I assumed his .version info would match.
