### ISSUE TITLE
Environmental Visual Enhancements support

### ISSUE THREAD

**Issue by SpaceTeph** [KSP-CKAN/NetKAN#497]
A favorite mod from @rbray89 I've been waiting to land on CKAN before I get into KSP again, until I thought to make the metadata for it myself. Here's the NetKAN:

```
{
    "spec_version"   : 1,
    "identifier"     : "EnvironmentalVisualEnhancements",
    "$kref"          : "#/ckan/github/rbray89/EnvironmentalVisualEnhancements",
    "name"           : "Environmental Visual Enhancements",
    "abstract"       : "Visual enhancements including clouds, lights, etc.",
    "license"        : "open-source",
    "ksp_version_min": "0.24",
    "resources" : {
        "homepage"     : "http://forum.kerbalspaceprogram.com/threads/55905",
        "repository"   : "https://github.com/rbray89/EnvironmentalVisualEnhancements"
    },
    "install" : [
        {
            "file"       : "GameData",
            "install_to" : "GameData"
        }
    ]
}
```

The current 7-4 release lists both the high-res and low-res variants of the mod and NetKAN picks the "wrong" ZIP file (the low-res one), so a manually-corrected CKAN is needed for now:

```
{
  "spec_version": 1,
  "identifier": "EnvironmentalVisualEnhancements",
  "name": "Environmental Visual Enhancements",
  "abstract": "Visual enhancements including clouds, lights, etc.",
  "license": "open-source",
  "ksp_version_min": "0.24",
  "resources": {
    "homepage": "http://forum.kerbalspaceprogram.com/threads/55905",
    "repository": "https://github.com/rbray89/EnvironmentalVisualEnhancements"
  },
  "install": [
    {
      "file": "GameData",
      "install_to": "GameData"
    }
  ],
  "author": "rbray89",
  "version": "7-4",
  "download": "https://github.com/rbray89/EnvironmentalVisualEnhancements/releases/download/7-4/EnvironmentalVisualEnhancements-7-4.zip"
}
```

No data for the low-res release yet - I'd name it differently but make it provide "EnvironmentalVisualEnhancements" so that additional configs can use either the high- or low-res mod.

**Comment by SpaceTeph** [comment]
Looking at the kind of files Astronomer's Pack overwrites makes me think that EVE's default configuration should be split from the core mod, otherwise it gets problematic fast. Please do not use this configuration yet... There's more work needed on that. The subdir "EnvironmentalVisualEnhancements" should be installed by the core mod and "BoulderCo" by the default config mod. The former has a configuration file, but it does not look like something that should be modified by any visual pack...

**Comment by hakan42** [comment]
Ah, actually you are about one day too late with the EVE netkan. If I remember correctly, I implemented an asset_match option into netkan on Wednesday and then the netkan was adapted to use that... 

Note to self : update docu, too :) 

Your ideas about splitting config files are interesting though, I will look at them tomorrow morning when I am really awake again...

**Comment by SpaceTeph** [comment]
Here's a corrected version. NetKAN for the core mod:

```
{
    "spec_version"   : 1,
    "identifier"     : "EnvironmentalVisualEnhancements",
    "$kref"          : "#/ckan/github/rbray89/EnvironmentalVisualEnhancements",
    "name"           : "Environmental Visual Enhancements",
    "abstract"       : "Visual enhancements including clouds, lights, etc.",
    "license"        : "open-source",
    "ksp_version_min": "0.24",
    "resources" : {
	"homepage"     : "http://forum.kerbalspaceprogram.com/threads/55905",
	"repository"   : "https://github.com/rbray89/EnvironmentalVisualEnhancements"
    },
    "install" : [
	{
	    "file"       : "GameData/EnvironmentalVisualEnhancements",
	    "install_to" : "GameData"
	}
    ],
    "depends" : [
	{ "name" : "EnvironmentalVisualEnhancements-Config" }
    ]
}
```

And the NetKAN for the default config that comes in the mod's ZIP:

```
{
    "spec_version"   : 1,
    "identifier"     : "EnvironmentalVisualEnhancements-Default",
    "$kref"          : "#/ckan/github/rbray89/EnvironmentalVisualEnhancements",
    "name"           : "Environmental Visual Enhancements (Default configuration)",
    "abstract"       : "Visual enhancements including clouds, lights, etc.",
    "license"        : "open-source",
    "ksp_version_min": "0.24",
    "resources" : {
	"homepage"     : "http://forum.kerbalspaceprogram.com/threads/55905",
	"repository"   : "https://github.com/rbray89/EnvironmentalVisualEnhancements"
    },
    "install" : [
	{
	    "file"       : "GameData/BoulderCo",
	    "install_to" : "GameData"
	}
    ],
    "depends" : [
	{ "name" : "EnvironmentalVisualEnhancements" }
    ],
    "provides" : [ "EnvironmentalVisualEnhancements-Config" ]
}
```

That's what I meant by splitting the configuration. A similar technique is used by e.g. Distant Object Enhancement.

**Comment by hakan42** [comment]
Could you please double-check with the (already merged) pull request #483 of Bashar two days ago?

**Comment by hakan42** [comment]
Also, if you are putting so much effort into writing the netkans, could you perhaps just fork the NetKAN repo and send pull requests? That way, our robots would check your contribution too without having to do manual work first...

**Comment by SpaceTeph** [comment]
Oh, sure. Haven't come around to installing git on that machine yet, but I could do so, of course.

Checked Bashar's pull request. It splits between high and low res, but not between the mod and its configuration. The core mod is apparently the same (the files have identical sizes) in the high and low resolutions, only the configuration part changes.

**Comment by SpaceTeph** [comment]
Another thing that is very irritating, though, is that the Astronomer's Pack apparently still uses some textures from the default EVE data - unless you use some optional features that finally overwrite everything. Guess that if anybody would put together NetKANs for that pack, this particular optional feature of the pack would have to be made mandatory to enforce the no-overwrite rule.

Been trying to put together some NetKANs for that pack, BTW; it's in the realm of the possible if one is ready to leave some of it out, such as some replacement sounds for Chatterer...

**Comment by SpaceTeph** [comment]
Currently rewriting the current EVE NetKAN files to split the mod from its configuration. I can't test them myself because I do not have a netkan.exe with the asset matcher feature. Do you have a CI/Build server somewhere from which I could get a nightly build, or should I build that myself? Haven't installed Xamarin yet...

**Comment by SpaceTeph** [comment]
Never mind, found it.

**Comment by SpaceTeph** [comment]
See the oncoming pull request.
