### ISSUE TITLE
Blue Hawk industries will not download for 1.2.1.   it reports the file is missing.

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/NetKAN#4977]

**Comment by Dazpoet** [comment]
Can reproduce. For reasons unknown the mod is no longer on spacedock but can be found [here](https://www.dropbox.com/sh/okudbdq1w0b3cob/AABEaRU6qQlr30L7ed72jJ0ka?dl=0) as was linked from [here](http://forum.kerbalspaceprogram.com/index.php?/topic/136721-blue-hawk-industries/&page=1)
