### ISSUE TITLE
Procedural Airships tutorial installation incorrect

### ISSUE THREAD

**Issue by ItMustBeACamel** [KSP-CKAN/NetKAN#498]
See  #491
@hakan42 
Installing the example crafts is working now.
Tutorials don't get installed correctly however. In the zip, the tutorials are located under "/saves/training/" (this matches the folder layout of KSP). Now CKAN erroneously creates subfolders in the training folder like this:
/saves/training/saves/training/

I had a look in the spec. and (if I understand it correctly) there seem to be no way to install the *contents* of a folder, rather than the folder itself. Which is rather unfortunate, since KSP does not seem to support subfolders in the tutorial folder anyway.

**Comment by Ippo343** [comment]
Hey @ItMustBeACamel , thanks for your report. I'm closing this as it's really old, if it's still relevant please comment and I'll reopen it.
