### ISSUE TITLE
LLL is out with version 1.1 but CKAN still only has 1.0.2

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/NetKAN#4984]

**Comment by Dazpoet** [comment]
A precursory expedition onto the forums, github and spacedock gave me no hits on LLL version 1.1. could you please supply a link since I'm seemingly blind :s

**Comment by Necessarycoot72** [comment]
I believe OP is referring to the ksp add-on checker stating that LLL is out of date

**Comment by linuxgurugamer** [comment]
LLL is at a beta 1.0.2.5, only available on Github.

Not a bug, I haven't yet released a final version for 1.2
