### ISSUE TITLE
Don't fail all updates if one download fails

### ISSUE THREAD

**Issue by Svish** [KSP-CKAN/NetKAN#5001]
When updating several mods, sometimes one fails to download (probably because of my garbage internet connection). It would be nice if it actually continued and completed the ones that did download OK, rather than seemingly aborting the whole process.

Currently I get an error message, and then only have a Cancel-button which takes me back to the list of mods which looks the same as before. I.e. the ones with new versions are still not listed as up to date.

So yeah.. would be nice to instead of getting an error message and a Cancel-button, a summary of which ones failed and which ones were OK. And every mod that was downloaded OK should've been updated too, maybe except if they depend on one that failed.

**Comment by politas** [comment]
Since this is an enhancement request related to the CKAN client, please log it in [the CKAN repository](https://github.com/KSP-CKAN/CKAN/issues). Issues in this repository are for problems with CKAN metadata.

**Comment by Svish** [comment]
Oh. WIll do :)
