### ISSUE TITLE
Changes in Kerbalism metadata

### ISSUE THREAD

**Issue by ShotgunNinja** [KSP-CKAN/NetKAN#5009]
Hi,

starting from Kerbalism version 1.1.5 for KSP 1.2.1 (to be released in the following days), multiple profiles can cohexist in the same user installation.

As a consequence of this, the package Kerbalism-Profile-Default is now obsolete and has no reason to keep existing. I don't know how to proceed about this, but I doubt that is as simple as deleting the metadata associated.

In addition, the package Kerbalism has a special provision: files with extension .cfg in the Profile/ subfolder are deleted post-installation. This is not necessary anymore, for the same reason specified above.

**Comment by Dazpoet** [comment]
pinging @dbent who did the last update to account for profiles. There are so many fancy netkan tools nowadays there's probably a much easier way to resolve this than the ones I know off.

**Comment by ShotgunNinja** [comment]
Thanks a lot!

**Comment by politas** [comment]
Thanks for letting us know ahead of time, @ShotgunNinja !

**Comment by dbent** [comment]
Just to note @ShotgunNinja users upgrading that already have `Kerbalism-Profile-Default` installed will have to uninstall it before they can upgrade to `Kerbalism` 1.1.5 since the `Profiles/Default.cfg` file will now be provided by `Kerbalism` and will produce a conflict on upgrade.
