### ISSUE TITLE
bdarmory version bump

### ISSUE THREAD

**Issue by Nerfclasher** [KSP-CKAN/NetKAN#5021]
BDArmory Continued needs a version bump and has updated
https://github.com/PapaJoesSoup/BDArmory/releases/download/v0.11.1.6/BDArmory.0.11.1.6_11082016.zip

**Comment by Dazpoet** [comment]
It appears we're looking in the wrong place, our [.netkan file](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/BDArmoryContinued.netkan) is pointing towards spacedock rather than github.
