### ISSUE TITLE
KIS has disappeared from CKAN

### ISSUE THREAD

**Issue by ihsoft** [KSP-CKAN/NetKAN#5027]
Hello,

Recently [KIS](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/KIS.netkan) has stopped showing in CKAN. I didn't change any ckan related file before it happen. Though, there were two events that could trigger the issue:
* Curseforge which holds the release archive went down couple of times in the last week.
* Github repositry owner for KIS mod has changed from `KospY` to `ihsoft`. This could the the reason but another mod `KAS` has exactly same setup and owner change didn't affect it.

I did a check with `netkan.exe` for the metadata and it worked fine:
```
netkan.exe  --verbose KIS.netkan 

48 [1] INFO CKAN.NetKAN.Program (null) - Transforming KIS.netkan
69 [1] INFO CKAN.NetKAN.Program (null) - Using CKAN cache at k:/steam/SteamApps/common/Kerbal Space Program/CKAN/downloads
100 [1] INFO CKAN.NetKAN.Program (null) - Finished reading input
101 [1] INFO CKAN.NetKAN.Validators.HasIdentifierValidator (null) - Validating that metadata contains an identifier
101 [1] INFO CKAN.NetKAN.Program (null) - Input successfully passed pre-validation
107 [1] INFO CKAN.NetKAN.Transformers.MetaNetkanTransformer (null) - Executing MetaNetkan transformation with #/netkan/https://raw.githubusercontent.com/ihsoft/
KIS/master/KIS.netkan
458 [1] INFO CKAN.NetKAN.Transformers.AvcTransformer (null) - Executing Interal AVC transformation with
612 [1] INFO CKAN.NetKAN.Transformers.AvcTransformer (null) - Found internal AVC version file
612 [1] INFO CKAN.NetKAN.Transformers.AvcTransformer (null) - Found remote AVC version file at https://raw.githubusercontent.com/KospY/KIS/master/KIS.version
646 [1] INFO CKAN.NetKAN.Transformers.AvcTransformer (null) - Remote AVC version file describes same version as local AVC version file, using it preferrentially
.
651 [1] INFO CKAN.NetKAN.Transformers.DownloadAttributeTransformer (null) - Executing Download Attribute transformation with
697 [1] INFO CKAN.NetKAN.Transformers.GeneratedByTransformer (null) - Executing Generated By transformation with
698 [1] INFO CKAN.NetKAN.Transformers.StripNetkanMetadataTransformer (null) - Executing Strip Netkan Metadata transformation with
702 [1] INFO CKAN.NetKAN.Transformers.PropertySortTransformer (null) - Executing property sort transformation
704 [1] INFO CKAN.NetKAN.Program (null) - Finished transformation
709 [1] INFO CKAN.NetKAN.Program (null) - Output successfully passed post-validation
711 [1] INFO CKAN.NetKAN.Program (null) - Transformation written to .\KIS-1.4.0.0.ckan
```

As of now I've updated all files obn my side to use new onwer folder on Github. Also, I've submitted changes for `.netkan` files (https://github.com/KSP-CKAN/NetKAN/pull/5026 and https://github.com/KSP-CKAN/NetKAN/pull/5025).

**Comment by Y3mo** [comment]
Probably just a dependendy not being cleared for ksp 1.2.2.

In that case, for some reason the dependent mod does not shot even show up under the "all" tab.
Yep, looking at the netkan file and ckan, CommunityCategoryKit is not yet available for ksp 1.2.2. As soon as that is set to be compatible, KIS will show up again.

**Comment by ihsoft** [comment]
Thanks for the investigation. Fixed KSP version for CCK, let's see if it helps. Too bad dependent mods get hidden completely, it confuses players a lot.

**Comment by ihsoft** [comment]
It got resolved after I've updated the dependent version.
