### ISSUE TITLE
Maneuver Node Evolved wrong KSP version support

### ISSUE THREAD

**Issue by DMagic1** [KSP-CKAN/NetKAN#5029]
Maneuver Node Evolved version 2.1 (not the latest version, 2.2) was improperly flagged as supporting KSP 1.2.2 in Space Dock and now doesn't seem to list KSP 1.2.1 support.

Could I get the 2.1 .ckan file changed back to KSP 1.2.1?

https://github.com/KSP-CKAN/CKAN-meta/blob/master/ManeuverNodeEvolved/ManeuverNodeEvolved-2.1.ckan

**Comment by Dazpoet** [comment]
That should do it, thanks for bringing it to our attention.
