### ISSUE TITLE
OuterPlanetsMod needs some more love

### ISSUE THREAD

**Issue by hakan42** [KSP-CKAN/NetKAN#504]
According to the listing at https://kerbalstuff.com/mod/437 , we need to double-check the "recommends" and "suggests" sections.

Also, Kopernicus is not available as a binary distribution yet, but OuterPlanetsMod nevertheless includes a binary (which is not installed by the current netkan).

**Comment by hakan42** [comment]
The just-merged https://github.com/KSP-CKAN/NetKAN/pull/503 fixes only the license and primary install section so the MirrorKAN does not stumble...

**Comment by Ippo343** [comment]
Hey @hakan42 , I'm closing this one as it's pretty old. If it's still relevant, let me know and I'll reopen the issue :)
