### ISSUE TITLE
Trajectories version 1.6.5 not picked up

### ISSUE THREAD

**Issue by andrewcchen** [KSP-CKAN/NetKAN#5046]
CKAN-meta only has 1.6.3, instead of the most recent version [1.6.5 on spacedock]( http://spacedock.info/mod/396/Trajectories).

**Comment by Dazpoet** [comment]
Some looking leads me to believe that we do index [version 1.6.5](https://github.com/KSP-CKAN/CKAN-meta/blob/master/Trajectories/Trajectories-v1.6.5.ckan) of the mod. Are you by any chance running ksp 1.1.3? If so 1.6.3 is the last compatible version.

**Comment by andrewcchen** [comment]
Ah I probably accidentally entered an old commit when searching in CKAN-meta, so I only saw 1.6.3 when I was looking in the Trajectories folder.

Btw, I'm running 1.2.1, doesn't seems like Trajectories is compatible with that yet.

**Comment by politas** [comment]
The AVC .version file and the forum thread specify only 1.2.0 as the current KSP compatibility. If Youen updates the .version file, CKAN will pick that up.
