### ISSUE TITLE
It appears that Goodspeed and GPOSpeedPump refer to the same mod

### ISSUE THREAD

**Issue by dringdahl** [KSP-CKAN/NetKAN#5073]
I did a quick search for a prior issue regarding this but did not find one. However, if this is a duplicate, feel free to close the issue.

**Comment by linuxgurugamer** [comment]
It looks like the one pointing to CKAN is being used by CKAN.exe, even though both are fully complient.

I've sent a message to the author about it, hopefully I'll get a response.

**Comment by linuxgurugamer** [comment]
Resolved per #5140, after confirmation from the author
