### ISSUE TITLE
Improperly listed mod description

### ISSUE THREAD

**Issue by jaxx050** [KSP-CKAN/NetKAN#5084]
> Thanks for wanting to bring an issue to our attention!
> 
> Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.
> 
> Please note that this repository is strictly for metadata (issues relating to incorrect information about mods, missing versions, or incorrect installations). If you want to suggest something or report a bug relating to CKAN as a whole, open the issue in: https://github.com/KSP-CKAN/CKAN

The mod DSD Mobile Labs is improperly described on CKAN because it has the mod description from Kerbal Research and Development.

**Comment by politas** [comment]
Can you suggest a pithy description? I can't find a single-sentence description.

**Comment by jaxx050** [comment]
"A stock rebalance of the science lab as well as two new lab parts, designed to expand the range of labs that different missions may use, in a stock-alike aesthetic, primarily done with varying the data-to-transmission value per lab."

**Comment by politas** [comment]
Thanks!
