### ISSUE TITLE
Downloadlink for "Diverse Kerbal Heads 1.0" is wrong

### ISSUE THREAD

**Issue by El-eucerico** [KSP-CKAN/NetKAN#5094]
Hi, install of  Diverse Kerbal Heads Mod fails.
The link is dead.
This link is OK: "https://kerbal.curseforge.com/projects/diverse-kerbal-heads-1-0/files/latest"
Here the log and errormessage:

About to install...
 * Diverse Kerbal Heads 1.0
Downloading "http://kerbal.curseforge.com/ksp-mods/220366-diverse-kerbal-heads-1-0/files/2201771/download"
Error!

Failed to download "http://kerbal.curseforge.com/ksp-mods/220366-diverse-kerbal-heads-1-0/files/2201771/download" - error: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.

**Comment by linuxgurugamer** [comment]
I don't have time now, but the URL should be:
https://kerbal.curseforge.com/projects/diverse-kerbal-heads-1-0/files/latest
