### ISSUE TITLE
Error when installing Nebula Decals and EVA Handrails Continued

### ISSUE THREAD

**Issue by reseune** [KSP-CKAN/NetKAN#5120]
As title says. Error text follows. Thanks!

Module "EVA Handrails Continued" successfully installed

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/NetKAN/issues/new

Please including the following information in your report:

File           : GameData/NEBULA/readme.txt
Installing Mod : NEBULADecalsContinued 0.1.1.1
Owning Mod     : EVAHandrailsPackContinued
CKAN Version   : v1.22.1-0-g174271a (beta)

Your GameData has been returned to its original state.

Error!

**Comment by politas** [comment]
@linuxgurugamer, this is a pair of mods you've taken on. Can you re-release them with their contents in subfolders to stop them conflicting? Might want to look at the two ModuleManager DLLs in EVAHandrailsPackContinued, too. Have just one of them in GameData where it belongs?

**Comment by linuxgurugamer** [comment]
Sure.
The MM dlls will be taken care of when I do the release

**Comment by linuxgurugamer** [comment]
Moving into subfolders will be difficult.  I'll fix this by making sure there aren't any conflicting files

**Comment by linuxgurugamer** [comment]
New versions have been uploaded, when CKAN updates, this should be fixed:
EVAHandRailsPack:  0.2.1.4
NebulaDecals: 0.1.1.2
