### ISSUE TITLE
Vessel Viewer Continued UI modules not being installed

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#5131]
These three netkan files:
VesselView.netkan
VesselView-UI-RasterPropMonitor.netkan
VesselView-UI-Toolbar.netkan

used to work.  After a change suggested by Politas, to use a "find_matches"files" rather than excluding, and coinciding with the release of the latest ckan.exe, they don't work.
What happens is that the main mod gets installed, and then it says it's installing the other (ie: UI), and finishes, but the UI part doesn't get installed.
Here is the output from a command line install, on Windows:

`C:\Windows\System32>"D:\KerbalInstalls\1.1 Turbo Charged\ckan.exe" install VesselView VesselView-UI-Toolbar
About to install...

 * Vessel Viewer Continued 2:0.8.3(cached)
 * VesselView-UI-Toolbar 1:0.8.3(cached)

Continue? [Y/n] y

Installing mod "VesselView 2:0.8.3"
Installing mod "VesselView-UI-Toolbar 1:0.8.3"
Updating registry
Commiting filesystem changes
Rescanning GameData
Done!`

When I look at the relationships in the GUI for one of the UIs, it says that the VesselView-UI is provided by the other one, see the attached picture
![ckan](https://cloud.githubusercontent.com/assets/1630166/21641936/10e3b6de-d24d-11e6-9d1a-5017532e6bff.png)

**Comment by linuxgurugamer** [comment]
I marked this a critical because there wasn't anything else which was relevent.  I'm not sure if this is a bug in ckan.exe, or just the netkan files aren't good.

**Comment by politas** [comment]
Don't worry about the "Provided By" in that view - it's biased to showing an alternate, it seems. The installation works fine for me. I get both DLLs installed when I select both UI mods for installation.

**Comment by linuxgurugamer** [comment]
Well, yes, so I'll get that fixed.
Wow, that's really strange.  When those dlls aren't in the same directory, they aren't loaded properly.  So this is the problem.
Thanks
