### ISSUE TITLE
DockingcameraKURSstyle: v1.2.0.2 is wrongly determined by ckan to be more recent than 1.2.1.1

### ISSUE THREAD

**Issue by andrewcchen** [KSP-CKAN/NetKAN#5134]
Seems to be the `v` in front of v1.2.0.2 that's causing things to break. 

![screenshot.png](https://cloud.githubusercontent.com/assets/6744506/21660049/8c24afe8-d332-11e6-8135-7376284f6047.png)

**Comment by politas** [comment]
Yep, that'd do it. "v" comes after "1"

**Comment by andrewcchen** [comment]
Still broken :(

Now that I look at it again 1.2.0.2 is actually `v.1.2.0.2`, notice the extra dot after v.
