### ISSUE TITLE
CKAN Overwrite Error and Unhandled Exception Report

### ISSUE THREAD

**Issue by JustaSimpleUser** [KSP-CKAN/NetKAN#5142]
KSP 1.2.2, UKS is the only mod being installed.

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug. Please report it at:

https://github.com/KSP-CKAN/NetKAN/issues/new

Please including the following information in your report:

File           : GameData/UmbraSpaceIndustries/Karibou/Karibou_CTT.cfg
Installing Mod : UKS 1:0.50.9.0
Owning Mod     : KaribouExpeditionRover
CKAN Version   : v1.22.1-0-g174271a (beta)

Then, CKAN generates an unhandled exception:

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.Main._MarkModForUpdate(String identifier)
   at CKAN.Util.Invoke[T](T obj, Action action)
   at CKAN.Main.PostInstallMods(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ckan
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///D:/Programs/Games/Steam/steamapps/common/ckan.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1636.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

**Comment by politas** [comment]
Looks like Karibou rover is now included in UKS, so you'll need to uninstall karibou expedition rover mod.

**Comment by Torih** [comment]
Getting the same issue,  Karibou is no longer showing in CKAN to uninstall it. I've deleted it manually but now UKS errors with:
About to install...

 * USI Kolonization Systems (MKS/OKS) 1:0.50.9.0(cached)

The following inconsistencies were found:
UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Karibou_CTT.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Karobou_CLS.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/BlueGlass30.dds, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/BlueGlass30.png.ddsified, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/Crinkle.dds, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/Crinkle.png.ddsified, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/crinkleFoil_NRM.dds, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/crinkleFoil_NRM.png.ddsified, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/KER_Adapter.mu, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/KER_CargoBay.mu, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/KER_Crate.mu, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/KER_CrewCab.mu, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/KER_FlatBed.mu, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/KER_Hub.mu, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/KER_KISCrate.mu, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/KER_RadialProbe.mu, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/KER_RCSBlock.mu, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/KER_RoverCab.mu, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/KER_SABRE.mu, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/KER_Shelter.mu, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/KER_Tank.mu, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/KER_VTOL.mu, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/KER_WheelBay.mu, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/KER_WheelBay_Short.mu, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/KER_Wheel_01.mu, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/KPS_SHARED_01.dds, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/KPS_SHARED_01.png.ddsified, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/MKII_Shared_01.dds, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/MKII_Shared_01.png.ddsified, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/MKII_Shared_01_GLOW.dds, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/MKII_Shared_01_GLOW.png.ddsified, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/MKII_Shared_02.dds, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/MKII_Shared_02.png.ddsified, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/RoverCab.dds, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/RoverCab.png.ddsified, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/RoverCab_Lights.dds, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/RoverCab_Lights.png.ddsified, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/RoverCab_Lights_GLOW.dds, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/RoverCab_Lights_GLOW.png.ddsified, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/RoverCab_Lights_TRAN copy.dds, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/RoverCab_Lights_TRAN copy.png.ddsified, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/RoverCab_Lights_TRAN.dds, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/RoverCab_Lights_TRAN.png.ddsified, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/RoverKontainers.dds, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/RoverKontainers.png.ddsified, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/RoverWheel.dds, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/RoverWheel.png.ddsified, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/tubeEndPlain.dds, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/tubeEndPlain.png.ddsified, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/USI-LD.dds, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Assets/USI-LD.png.ddsified, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Parts/KER_Adapter.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Parts/KER_CargoBay.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Parts/KER_Crate.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Parts/KER_CrewCab.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Parts/KER_FlatBed.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Parts/KER_Hub.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Parts/KER_KISCrate.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Parts/KER_PassengerCab.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Parts/KER_RadialProbe.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Parts/KER_RCSBlock.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Parts/KER_RoverCab.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Parts/KER_SABRE.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Parts/KER_Shelter.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Parts/KER_Tank.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Parts/KER_VTOL.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Parts/KER_WheelBay.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Parts/KER_WheelBay_Short.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Parts/KER_Wheel_01.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Patches/Karibou_RPM.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Patches/RemoteTech_USI_Karibou_Probe.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Patches/WheelSounds_Karibou.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Spaces/cab_internal.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Spaces/cab_internal_rpm.cfg, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Spaces/RoverCab_IVA.dds, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Spaces/RoverCab_IVA.mu, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Spaces/RoverCab_IVA_GLOW.dds, but this file is registered to KaribouExpeditionRover
 * UKS wishes to install GameData/UmbraSpaceIndustries/Karibou/Spaces/RoverWheel.dds, but this file is registered to KaribouExpeditionRover



Error!

Launched the game a few times with both Karibou and UKS installed and tried restarting ckan a couple of times, Still the same.

**Comment by Commissar0617** [comment]
looks liek roverdude combined some mods... in a rather unususal fashion

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/NetKAN/issues/new

Please including the following information in your report:

File           : GameData/UmbraSpaceIndustries/KarbonitePlus/ATM.cfg
Installing Mod : Karbonite 1:0.8.5.0
Owning Mod     : KarbonitePlus
CKAN Version   : v1.22.1-0-g174271a (beta)

Your GameData has been returned to its original state.




Error!

**Comment by politas** [comment]
Uninstall all Roverdude's mods and reinstall the ones you want. The conflicts should be sorted out that way.
