### ISSUE TITLE
ModulaFuelSystem is 1.2.2 compatible, CKAN list is outdated

### ISSUE THREAD

**Issue by bokrif** [KSP-CKAN/NetKAN#5151]
ModulaFuelSystem is 1.2.2 compatible, CKAN list is outdated

Reference: [https://github.com/NathanKell/ModularFuelSystem](https://github.com/NathanKell/ModularFuelSystem)
[http://forum.kerbalspaceprogram.com/index.php?/topic/58235-122-modular-fuel-tanks-v583/](http://forum.kerbalspaceprogram.com/index.php?/topic/58235-122-modular-fuel-tanks-v583/
)
> [1.2.2] Modular Fuel Tanks v5.8.3

**Comment by politas** [comment]
Thanks for letting us know!
