### ISSUE TITLE
does not correctly pull up to day module manager

### ISSUE THREAD

**Issue by Commissar0617** [KSP-CKAN/NetKAN#5154]
sooo.. i had module manager installed via ckan, so i could update it, but cka won't update it, and it's quite behid... soo i removed it, and now i'ds "autodetected"... but that's supposedly causing problems with realfuels.,...
and now, afdter deleting the dll, it wants to remove about 40 or 50 mods. so... what i'm kinda asking, is if we can get an override for "autodetected" mods, to avoid this cluster****

**Comment by politas** [comment]
I have a plan in my head for a better way to handle installations outside CKAN, but it's very theoretical at this stage. Currently, the only method is to use File->"Export Installed Mods" , save as type CKAN favourites list, then delete the AD mod, let CKAN delete all the others, then use File->"Install from .ckan", selecting the favourites list you created. CKAN will pull all the removed mods back in from the cache, so it should be pretty quick.

**Comment by Commissar0617** [comment]
well, i ended up just handling modulemanager manually for now. 
any idea as to why it wasn't updating in the first place?

**Comment by politas** [comment]
Without knowing what error message you were getting, I couldn't say.
