### ISSUE TITLE
Previous files are ordered in a weird way I guess?

### ISSUE THREAD

**Issue by jaxx050** [KSP-CKAN/NetKAN#5162]
```
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

Please note that this repository is strictly for metadata (issues relating to incorrect information about mods, missing versions, or incorrect installations). If you want to suggest something or report a bug relating to CKAN as a whole, open the issue in: https://github.com/KSP-CKAN/CKAN
```
I had installed the Karibou Rover by Umbra Space Industries (RoverDude) a while ago, and I was doing mod updates to catch me up on 1.2.2's latest release, and it told me that it was trying to overwrite another mod's files, but that mod wasn't actually listed in the modlist, so I deleted it locally and tried to find which update was trying to ghost update, but now it's trying to update a mod that doesn't exist anymore. And I'm confused.

**Comment by jaxx050** [comment]
On going through my mod updates one by one, I think it might be because USI MKS merged some of its child folders in a way CKAN doesn't understand, and I can't figure out how to get it to recognize however its newly structured to not bug out on me when updating.

**Comment by politas** [comment]
My understanding is that Karibour Rover is now part of MKS, so just uninstall the separate mod.

**Comment by jaxx050** [comment]
That's just the thing, Karibou Rover is now no longer listed on my mod installs and trying to remove it manually has it throwing even more errors as it tries to update something that doesn't exist.

**Comment by politas** [comment]
If you select the "Installed" filter, you should see it.

**Comment by jaxx050** [comment]
Whelp. Thanks. I'm so used to being on compatible.
