### ISSUE TITLE
USI Kolonization wont install

### ISSUE THREAD

**Issue by 09gara** [KSP-CKAN/NetKAN#5170]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

Please note that this repository is strictly for metadata (issues relating to incorrect information about mods, missing versions, or incorrect installations). If you want to suggest something or report a bug relating to CKAN as a whole, open the issue in: https://github.com/KSP-CKAN/CKAN

Please including the following information in your report:

File           : GameData/UmbraSpaceIndustries/Karibou/Assets/BlueGlass30.dds
Installing Mod : UKS 1:0.50.12.0
Owning Mod     : KaribouExpeditionRover
CKAN Version   : v1.22.1-0-g174271a (beta)

Your GameData has been returned to its original state.

Error!

**Comment by Olympic1** [comment]
This is fixed as both mods have been merged into 1
