### ISSUE TITLE
Trailing tilde seems to cause a problem

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#5172]
It's been reported to me that a file with a trailing tilde seems to be causing a problem in CKAN.

I haven't verified it, was wondering if there is any basis in this or if the user was just spouting off

**Comment by politas** [comment]
A file being downloaded? I can't think of a reason that would cause a CKAN issue

**Comment by linuxgurugamer** [comment]
No, a file inside the mod directory (ie:  a.cfg~)

**Comment by politas** [comment]
I think we need some more details. What is the file called, where is it, and what are the symptoms of the problem?

**Comment by linuxgurugamer** [comment]
I don't have complete details.  and I don't really buy into this either, but I'm just following up on what was told me.
What I have is this:
`
I get an error trying to update Take Command with CKAN: it says "<path to GameData>\TakeCommand\ModuleManager is already absolute". Apparently, something's wrong with the assembly.`

and then later, someone said the following:

`
@linuxgurugamer The root problem is that you've included some lock files with the .cfg files you're distributing. In this mod, specifically, takeCommand.cfg~ and SXTContinuded.cfg~ should be deleted. For any end users, deleting these files will be required before updating.

These lock files let other programs know that the file in question is being modified right now by another program, and that it may not be safe to change it. When software that respects lock files, such as CKAN, sees the lock files while trying to perform an operation it throws an error. Many text editors will automatically create lock files of files you open in them. They're supposed to get cleaned up when you're done working with the file, but sometimes they stick around due to buggy software or crashes.`

**Comment by politas** [comment]
filename~ doesn't mean lock file, or at least, not in Unixland. They're backups. And text editors don't "clean them up" unless you turn off the "Create a backup copy of files before saving" or whatever configuration option your text editor uses. It would be weird if they did.

**Comment by politas** [comment]
But that "path to <x> is already absolute" is definitely a bug we need to chase down.

**Comment by linuxgurugamer** [comment]
@politas I know that, you know that, but the person who posted that didn't :-)

I've already replied to him, but the bug which _may_ be related to this is the real issue.

**Comment by politas** [comment]
Well, I've just tried to replicate the issue by forcing an upgrade from 1.4.6 of TackeCommandContinued to 1.4.7 (which I note has the ~backups), and it worked fine.

**Comment by techman83** [comment]
What platforms? Linux (probably Mac too being bsd based) copes a lot better with things in paths.

**Comment by politas** [comment]
My test was on Linux. I'll have a go on my Windows VM

**Comment by politas** [comment]
Tested fine on Windows, too, which supports the notion that it's installation/machine specific. We'd have a lot more people screaming if it always failed.

**Comment by linuxgurugamer** [comment]
Ok.  I'll ask the people for some more feedback.
