### ISSUE TITLE
Linuxgurugamer's netkan generator

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#5178]
This is for information only.

I've updated my script with the following changes:

- Looks for and excludes the Mac-specific files/directories
- Looks for a Ships folder, and if found it installs the included ships
- Looks for included *.pdb files, and adds a filter to exclude them if found
- Looks for files ending in tilde, and if found, adds a filter to exclude them

The Zenit3SLBReduzx netkan was the first one made with these new changes.  Hopefully this will make more reliable  files moving forward.

**Comment by politas** [comment]
Sounds like you've got quite a bit of automation happening for all those mods you're taking on!

**Comment by linuxgurugamer** [comment]
I couldn't do it without automation. But this is used only to generate netkan files

**Comment by Blu3wolf** [comment]
Does your script handle NetKANs for where the one release has 3 different versions? Im currently looking at your (Blizzy's) Toolbar 1.7.17.15, which has three different subversions (one for each of KSP 1.4.5, 1.5.1, and 1.6.1). 

I wanted to ask if there could be CKAN metadata for those versions added, but the CKAN metadata repo doesnt have Issues enabled, and Im not sure if a NetKAN can figure out subversions within a single Release?

**Comment by linuxgurugamer** [comment]
Not at the present.  It works by looking at the release zip and deriving information from it

**Comment by politas** [comment]
A netkan file for each subversion would need to be created, extracting the relevant files and splitting Toolbar into multiple conflicting/providing entries.

**Comment by Olympic1** [comment]
Test

**Comment by HebaruSan** [comment]
I'm assuming we can close this as there don't seem to be any open tasks to complete.
Please let us know if that's mistaken.
