### ISSUE TITLE
Mod request

### ISSUE THREAD

**Issue by HiddenKn** [KSP-CKAN/NetKAN#5180]
I was wondering if it was possible to add [REKT](https://github.com/steedcrugeon/REKT) by @steedcrugeon and [XTLandertron](https://github.com/Kerbas-ad-astra/XTLandertron) by @Kerbas-ad-astra.

**Comment by linuxgurugamer** [comment]
You should speak to @steedcrugeon and @kerbas-ad-astra to do that

**Comment by politas** [comment]
At least try to get their agreement for their mods to be listed.

**Comment by HiddenKn** [comment]
Well, they probably have gotten a notification because I highlighted them :)

**Comment by politas** [comment]
Of course, that depends on what setting they have for GitHub notifications.

**Comment by steedcrugeon** [comment]
I have no objections to REKT being added. What is the preferred process for adding a mod, for future reference?

**Comment by linuxgurugamer** [comment]
A simple request to anyone on the CKAN list would do

**Comment by linuxgurugamer** [comment]
Re. REKT, as soon as I see the new release you mentioned, I'll get it added

**Comment by linuxgurugamer** [comment]
Oh, I see you pushed it to Spacedock, you need to get Github updated as well.  Anyway, I'll get started withthe spacedock file

**Comment by linuxgurugamer** [comment]
@steedcrugeon see my comments in the REKT thread, the file has problems

**Comment by steedcrugeon** [comment]
Comments noted, I have rectified the issue (failed merge) and pushed a release.

**Comment by linuxgurugamer** [comment]
I'll be doing REKT either this evening or tomorrow.  I pinged @Kerbas-ad-astra about the XTLandertron, will do that when I hear back

**Comment by Kerbas-ad-astra** [comment]
Not until I've released 1.0.  I'll let you know when that happens.

**Comment by linuxgurugamer** [comment]
@Kerbas-ad-astra Thanks, appreciate the feedback

REKT is done

**Comment by HiddenKn** [comment]
@linuxgurugamer I'm probably overlooking it, but I can't seem to find REKT in CKAN or in the recent commits. :worried:

**Comment by politas** [comment]
REKT is merged now.

**Comment by HiddenKn** [comment]
Thank you for your help!

**Comment by Kerbas-ad-astra** [comment]
Landertrons 1.0.0 is out.  @linuxgurugamer et al, you're clear to move forward.  Testing in KSP 1.2.9 indicates that it will not be compatible out-of-the-box with KSP 1.3, so please be conservative with version compatibility (if you're inheriting from the .version file, it should be okay).

**Comment by politas** [comment]
KSP 1.2.9 is breaking stuff? Damn. So much for all those mods with 1.2 or 1.2.99 or such. I'm glad it's just a pre-release.
