### ISSUE TITLE
.version files in included dependencies are being detected as an error

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#5187]
Running netkan.exe on a new file, got the following error:

1120 [1] WARN CKAN.NetKAN.Transformers.SpacedockTransformer (null) - Could not normalize URL:
5209 [1] FATAL CKAN.NetKAN.Program (null) - Too may .version files located: REKT-0.4.3.1/RetractableLiftingSurface/RetractableLiftingSurface.version, REKT-0.4.3.1/SHED/rekt.version

**Comment by linuxgurugamer** [comment]
I fixed this one by adding a filter, but this can become a real problem if not fixed

**Comment by politas** [comment]
Can you raise this in the CKAN repo, instead? This is a code issue.

**Comment by linuxgurugamer** [comment]
sure
