### ISSUE TITLE
Please Add Kerbal Mechanics

### ISSUE THREAD

**Issue by IRnifty** [KSP-CKAN/NetKAN#519]
NetKan file:

	{
		"spec_version"   : 1,
		"identifier"     : "KerbalMechanics",
		"release_status" : "development",
		"license"        : "GPL-3.0",
		"$kref"          : "#/ckan/kerbalstuff/48",
		"resources" : {
			"homepage"     : "http://forum.kerbalspaceprogram.com/threads/85798",
			"bugtracker"   : "https://github.com/IRnifty/KerbalMechanics/issues",
			"repository"   : "https://github.com/IRnifty/KerbalMechanics",
			"kerbalstuff"  : "https://kerbalstuff.com/mod/48"
		}
	}

**Comment by hakan42** [comment]
Here you go....

**Comment by IRnifty** [comment]
Thanks. Got one more coming in a bit, a third party tool, when I finalize the builds.
