### ISSUE TITLE
Trajectories 1.6.6 not on CKAN

### ISSUE THREAD

**Issue by andrewcchen** [KSP-CKAN/NetKAN#5203]
Trajectories version 1.6.6 has been released on github but its spacedock page hasn't been updated (yet).

https://github.com/neuoy/KSPTrajectories/releases

**Comment by politas** [comment]
Is Youen no longer releasing to Spacedock?

**Comment by linuxgurugamer** [comment]
maybe he forgot, I'll ping him

**Comment by linuxgurugamer** [comment]
It's on spacedock
