### ISSUE TITLE
Mod was renamed, showing up 2x

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#5207]
The following two mods:

ScienceSituationInfo (max KSP vesion 1.0,4)

ExtendedInfoSciExp (max KSP 1.2.1) 

are actually the same mod.  I got confused when I saw the Science one listed in CKAN as AD after I installed the Extended one.

Can anything be done about this?

**Comment by politas** [comment]
I'm not entirely sure, but I think if we change the name (not the identifier) of the final release of the old mod to match the new one, it will be treated by the CKAN client as a single mod, though that needs testing. I should get on with KSP-CKAN/CKAN#1888, that would fix this.

**Comment by Dazpoet** [comment]
Horrible HORRIBLE things happen when a mod has two identifiers. See e.g #1087 which was a bad solution to a bad problem way back when.

**Comment by linuxgurugamer** [comment]
Can anything be done about this?

**Comment by Dazpoet** [comment]
Well, you can do what we did in the PR I linked, lock on of them to a distinct version of ksp so that the problem is contained to that versions. As people move away from it the problem "disappears"

**Comment by linuxgurugamer** [comment]
Ok, I did, but then realized that the file was a .frozen file, so it won't be processed, will it?
In this case, would it be better just to delete the contents of the file as I've seen in some other .frozen files?

**Comment by Dazpoet** [comment]
Why does a 1.0.4 mod show up as AD in, what I assume is, a 1.2.2 installation?

Seeing as the mod is frozen since 1.0.4 I guess it might be prudent to prune it from CKAN-meta (aka freeze the files there). I doubt we have a lot of users stuck in 1.0.x land anymore.

**Comment by linuxgurugamer** [comment]
You just went beyond me, I'll leave it in your capable hands

**Comment by politas** [comment]
I can only think that the AD code is matching the file/folder name on the first mod that matches, ignoring KSP versioning. (and the repo data that say which mod owns the files)
