### ISSUE TITLE
Phoenix Mods by MovieCollins have issues claiming files in other mods (cannot install all 3 at the same time)

### ISSUE THREAD

**Issue by whiteknight4981** [KSP-CKAN/NetKAN#5216]
About to install...

it would appear that the 'Agents' folder needs to be packaged separately as a component required by each his 3 mods (Cargo Respully, CubeSat, Boosters) so they don't all try to install it on their own and then error out after the first mod has loaded.

 * Phoenix Industries - CubeSat 2.2(cached)

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/NetKAN/issues/new

Please including the following information in your report:

File           : GameData/CTN/Agencies/Agents.cfg
Installing Mod : PhoenixIndustriesCubeSat 2.2
Owning Mod     : PhoenixIndustriesCargoResupplySystem
CKAN Version   : v1.22.1-0-g174271a (beta)

Your GameData has been returned to its original state.

Error!

**Comment by Bit-Fiddler** [comment]
yes I have found this as well.  the cargo resupply mod conflicts with the other 2.
you can have the CubeSat mod and the Boosters mod both installed, but the cargo mod will conflict with both of these.

**Comment by linuxgurugamer** [comment]
It doesn't need to be packaged separately, but it needs to be installed via a separate netkan file

**Comment by linuxgurugamer** [comment]
I'll see what I can do this evening
