### ISSUE TITLE
CKAN has stopped working

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/NetKAN#5245]
on starting CKAN I get this message in the "Updating Repositories" tab.  

```
The` following inconsistencies were found:
- KerbalAtomics-NFECompatibility depends on NearFutureElectrical but it is not listed in the index, or not available for your version of KSP.
- NearFutureElectrical-DecayingRTGs depends on NearFutureElectrical but it is not listed in the index, or not available for your version of KSP.



Repository successfully updated
```

I am not sure if this has anything to do with the problem, but I also now can't install or remove any mods via CKAN.  I can browse the list and check or uncheck mods but the apply button will never light up.  However if I select the "add available updates" button the apply button will light up, but the list of actions to perform on the "changeset" tab is blank in spite of the updates being checked in the "manage Mods" tab.  Furthermore at this point clicking the "Apply" button on the "Changeset" tab does not so anything, implying to me that the list is not just visually blank, but there is in reality nothing waiting to be done.

due to this I am unable to uninstall the offending mods listed in the error message, or install the required mods listed.   When all this started The Near future Electrical mod and Kerbal Atomics were both installed but may have been outdated.  I have since then deleted them hoping to correct the issue, but of course CKAN still thinks they are installed as I can never get the "uninstall" action to run.

so the question is how do I edit the registry file to remove these mods manually so I see if CKAN will then recover and continue?

**Comment by Bit-Fiddler** [comment]
Ok this issue can be closed...

i resolved the problem by using the CLI to manually remove the offending mods.  then reinstalled them all with the GUI.

**Comment by Electric-Pants** [comment]
Wait what did you do? The same thing happened to me but with all the mods for Realism Overhaul.
