### ISSUE TITLE
Mods that i use need updates in CKAN

### ISSUE THREAD

**Issue by DarthLyte** [KSP-CKAN/NetKAN#5249]
KSP: 1.2.2 (Win64) - Unity: 5.4.0p4 - OS: Windows 10  (10.0.0) 64bit

**_BetterTimeWarpContinued - 2.3.1_**     Needs  2.3.4
**_StageRecovery - 1.6.5_                                                    Compatability issue: "Was ment to run on Kerbal 1.2 and Is a 3rd Party Mod i cant find were i downloaded it would like it on CKAN .
**_TacSelfDestructContinued - 1.6.1_**       Needs 1.6.2
**_TweakableEverything - 0.1.17_**            Needs 0.1.18
**_TweakableEverything - 0.1.16.1_**          Needs 0.1.18    Compatability issue: "Was ment to run on Kerbal 1.2
  
Also I have a bunch of crash logs... I hope they'll help so here you go.

[output_log.txt](https://github.com/KSP-CKAN/NetKAN/files/761198/output_log.txt)
[output_log.txt](https://github.com/KSP-CKAN/NetKAN/files/761200/output_log.txt)
[output_log.txt](https://github.com/KSP-CKAN/NetKAN/files/761201/output_log.txt)
[output_log.txt](https://github.com/KSP-CKAN/NetKAN/files/761204/output_log.txt)
[output_log.txt](https://github.com/KSP-CKAN/NetKAN/files/761207/output_log.txt)

[output_log.txt](https://github.com/KSP-CKAN/NetKAN/files/761208/output_log.txt)

**Comment by linuxgurugamer** [comment]
TacSelfDestruct is already available in CKAN at 1.6.2, try refreshing 
TweakableEverything is already available in CKAN at 10.1.18, again, try refreshing
stageRecovery is already available in CKAN at 1.6.8, try refreshing.

BetterTimeWarpContinued is  already available in CKAN at 2.3.4, try refreshing.
