### ISSUE TITLE
Error updating Phoenix Industries Cargo Resupply System

### ISSUE THREAD

**Issue by bombaatu** [KSP-CKAN/NetKAN#5253]
File           : GameData/CTN/Agencies/Agents.cfg
Installing Mod : PhoenixIndustriesCargoResupplySystem v2.2
Owning Mod     : PhoenixIndustriesBoosters
CKAN Version   : v1.22.1-0-g174271a (beta)

The CTN/Agencies/Agents.cfg file was installed by CKAN with another Phoenix Industies mod

**Comment by linuxgurugamer** [comment]
Duplicate of: #5216
