### ISSUE TITLE
Bad netkan file: ASETProps-CE.netka

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#5256]
there is a bad netkan:  NetKAN/NetKAN/ASETProps-CE.netkan, the mod was deleted from Spacedock when the full ASETProps was released.  Would deleting this or renaming it be the right thing to do?

**Comment by techman83** [comment]
Looks like @Dazpoet sorted it, freezing is usually the way to go. Avoids future identifier clashes.

**Comment by linuxgurugamer** [comment]
Yup. Thanks
