### ISSUE TITLE
PhoenixIndustriesAgencies has wrong name in CKAN

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#5265]
I make this to fix a confict in installs, but for some reason (I don't have the time right now), it shows up as Phoenix Industries - Boosters.
I have the .netkan getting the agencies folder from the Boosters, so I assume the spacedock info is overriding the name.

**Comment by Dazpoet** [comment]
There is no name listed in the .netkan file, hence the error

**Comment by Dazpoet** [comment]
And well, it does show up correctly in my CKAN client. Probably was due to the change not instantly (as in right on the millisecond) populating over to CKAN-meta. However it installs a Thumbs.db file which it shouldn't.

The error appears to have been resolved so I'll close this.

**Comment by linuxgurugamer** [comment]
Thank you
