### ISSUE TITLE
CKAN Error in auto update 

### ISSUE THREAD

**Issue by JoshHollis** [KSP-CKAN/NetKAN#5284]
On trying to Install CKAN  I encounter this message  "Error in auto update. Unable to connect to remote server "
Have tried turning firewall off and re installing but to no use 

Windows 10

**Comment by politas** [comment]
Where did you save ckan.exe? There is no "install" as such, just running it.
Did it create a "CKAN" folder in your KSP directory?

**Comment by UniversityOfPi** [comment]
I was having the same problem

It looks like the issue is using v1.24.0-PRE and earlier

> NOTE: Due to a change in GitHub servers, all versions of CKAN prior to v1.24.0 will not function. You must upgrade the CKAN client manually to v1.24.0

https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1240-bruce/
