### ISSUE TITLE
New Tantares and New TantaresLV

### ISSUE THREAD

**Issue by DerpyFirework** [KSP-CKAN/NetKAN#5295]
I've just created the NetKAN files for the new versions of Tantares and TantaresLV (attached)
I created them separate from Tantares and TantaresLV as they are completely redone from the ground up.
[NewTantares & NewTantaresLV.zip](https://github.com/KSP-CKAN/NetKAN/files/815289/NewTantares.NewTantaresLV.zip)

**Comment by blackk100** [comment]
I guess this should go in a pull request.
