### ISSUE TITLE
failed to download Karbonite Plus

### ISSUE THREAD

**Issue by 09gara** [KSP-CKAN/NetKAN#5315]
About to install...

 * KarbonitePlus 0.7.2.0

Downloading "https://github.com/BobPalmer/KarbonitePlus/releases/download/0.7.2.0/KPlus_0.7.2.0.zip"

Error!

Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

Please note that this repository is strictly for metadata (issues relating to incorrect information about mods, missing versions, or incorrect installations). If you want to suggest something or report a bug relating to CKAN as a whole, open the issue in: https://github.com/KSP-CKAN/CKAN

**Comment by politas** [comment]
Looks like Bob has removed that mod.

**Comment by politas** [comment]
KarbonitePlus has been removed from CKAN

**Comment by linuxgurugamer** [comment]
Just an FYI, it look slike it is now included in the regular Karbonite mod
