### ISSUE TITLE
TACLS install options

### ISSUE THREAD

**Issue by PhineasFreak** [KSP-CKAN/NetKAN#5326]
Before the TACLS update for KSP 1.2 the life support settings were not accessible via Module Manager, so CKAN used the "multi-choice" system to allow the user to select between the stock and the RO config. Now, it uses a global config (that can be modified via MM), meaning that this system is not needed now (RO has updated it's own configs for this change).

* TACLS commit: https://github.com/KSP-RO/TacLifeSupport/commit/1b301ea7ff36346fbbed051c748a819ecedb2491
* RO TACLS config: https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_RecommendedMods/TACLS/RO_TACLS_TacLifeSupportCfg.cfg
* Original stock TACLS NetKAN: https://github.com/KSP-CKAN/NetKAN/blob/00b0fd7c4e33f3345230ae4e2735673b37b96a15/NetKAN/TACLS-Config-Stock.netkan
* RO TACLS NetKAN: https://github.com/KSP-CKAN/NetKAN/blob/ada4f8324490724f517801fdd0bf2432612cf9bf/NetKAN/TACLS-Config-RealismOverhaul.netkan

**Comment by benjwgarner** [comment]
The changes have been made and (accidentally) included in pull request #5330.
