### ISSUE TITLE
Astronomer's visual pack download link broken

### ISSUE THREAD

**Issue by jtprotech** [KSP-CKAN/NetKAN#5343]
hello guys, i just wanted to report that the download link for all of the astronomers visual pack assets is broken. i have found a new link https://addons-origin.cursecdn.com/files/2221/625/Astronomer%27s%20Visual%20Pack%20-%20Interstellar%20V2.zip that hosts the exact same file with the same sha-1 hash. could we get this replaced ?

**Comment by politas** [comment]
For Astronomer's Pack version Interstellar.V2?
