### ISSUE TITLE
KSP Interstellar 0.90 version

### ISSUE THREAD

**Issue by Xolroc** [KSP-CKAN/NetKAN#535]
Interstellar has been taken up by a new modder to keep it functional on new versions; it can be found at http://forum.kerbalspaceprogram.com/threads/104943-0-90-KSP-Interstellar-port-maintance-thread . 

I don't know any details on what would be needed (Not yet really sure how to use CKAN) but this might let you get a functional 0.90 version listed on there?

**Comment by hakan42** [comment]
CKAN built and pull request created.

@Xolroc , could you by any chance download the ckan file from my PR linked above, and try to install and play with it? Here is the direct link:

https://raw.githubusercontent.com/hakan42/CKAN-meta/KSPInterstellar_0_90/KSPInterstellar/KSPInterstellar-0.13.6.ckan

download it, and run ckan from the command line:
```
ckan install -c <whereever you downloaded it to>\KSPInterstellar-0.13.6.ckan
```
If you are confident that it does not break too much stuff, we can merge it and announce on the appropriate forum thread.

**Comment by Xolroc** [comment]
Would you rather I try to play with this alone, or with other mods as well? Because if there's a feature to save a list of active mods and restore it later, I can't find it.

**Comment by hakan42** [comment]
Whenever you install something via ckan, a file "installed-default.ckan" gets saved into the CKAN directory in your KSP folder. That, and the registry.json file from the same directory should be information enough. 

Also, when in doubt, you can simply zip up your GameData and Saves directories and keep them on a backup drive :smile:

**Comment by hakan42** [comment]
Also play it however feels natural to you. I don't have much experience with Insterstellar (none, actually) and very little time to play myself. 

Basically, install the ckan and try to break stuff :smile:

**Comment by Xolroc** [comment]
Well, one error comes up immediately. For whatever strange reason, any fission reactors added by Interstellar will quickly grow in size when hovered over in the parts list. This doesn't seem to affect gameplay, it's just an annoying graphical glitch.

**Comment by hakan42** [comment]
Annoying, but needs to be reported to the addon maintainer. I have seen that behavior on many parts before they were fully adapted to 0.90

**Comment by Xolroc** [comment]
I've reported it to the addon maintainer; in the meantime, I've added a workaround to all the affected parts. Is there some way CKAN can automatically edit configuration files?

**Comment by hakan42** [comment]
No. CKAN is an installation tool only, the most we do is filter the files to be installed, but whatever we install has to be in the addon archive.

**Comment by Ippo343** [comment]
Hey, since the PR has been merged, I'm closing this one :)
