### ISSUE TITLE
RSS/Constellations File Overwrite Conflict

### ISSUE THREAD

**Issue by mtarleton** [KSP-CKAN/NetKAN#5363]
File           : GameData/RealSolarSystem/RSSKopernicus/Sun.cfg
Installing Mod : RSSExtrasolar 1.0
Owning Mod     : RealSolarSystem
CKAN Version   : v1.22.1-0-g174271a (beta)****

This is from a clean install but I'm admittedly adding oodles of mods to it. Haven't booted up the game yet though and I'm pretty sure Constellations(aka RSSExtrasolar) is conflicting with one of its own dependencies.

**Comment by Olympic1** [comment]
They shouldn't overwrite each other because they have different folder names.
Installing RealSolarSystem **v12.0.0** and Constellations **v2.0** works fine for me.

**Comment by politas** [comment]
@mtarleton , it looks like you'll need to uninstall and reinstall RSSExtrasolar rather than upgrading.

**Comment by Olympic1** [comment]
@mtarleton does this still happen?

**Comment by mtarleton** [comment]
Hey folks, sorry for the delay. I just put together a clean install of KSP 1.1.3. First RP-0 and all of it's dependencies. Then Constellation and still get the same error.

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/NetKAN/issues/new

Please including the following information in your report:

File           : GameData/RealSolarSystem/RSSKopernicus/Sun.cfg
Installing Mod : RSSExtrasolar 1.0
Owning Mod     : RealSolarSystem
CKAN Version   : v1.22.2-dev

**Comment by Olympic1** [comment]
There was a new release, is this fixed now?
