### ISSUE TITLE
SVT 2.0.3 can't be downloaded via CKAN

### ISSUE THREAD

**Issue by DrRaphello** [KSP-CKAN/NetKAN#5376]
2.0.3 has been removed by Galilleo: [link](http://forum.kerbalspaceprogram.com/index.php?/topic/143828-122-stock-visual-terrain-v202/&do=findComment&comment=2986777). CKAN just gives an error on an attempt to downolad it.

Could somebody remove 2.0.3 from CKAN?
The only other option is a manual download from Github

**Comment by DrRaphello** [comment]
This is now fixed. Issue can be closed

**Comment by politas** [comment]
Done
