### ISSUE TITLE
kRPC 0.3.8.post1 NetKAN metadata

### ISSUE THREAD

**Issue by PhineasFreak** [KSP-CKAN/NetKAN#5387]
A small update was pushed to the kRPC repository but the changes were interpreted as a mod update from the NetKAN bot: https://github.com/KSP-CKAN/CKAN-meta/commit/313f07482a29e4da45c8a6c24ea447c5a8360a7b

This replaces the entire mod content with python source code files that have nothing to do with the actual mod (well, they are used to create the python kRPC server and client but they are not meant to be distributed).

**Comment by Olympic1** [comment]
If you make it a pre-release, the bot will ignore it and v0.3.8 will stay the latest release available until there is a new full release. It's better to mark it as a pre-release if you don't want it to be indexed or doens't contain all the content.

If it's marked as a pre-release, let us know so we can delete the file otherwise it will keep indexing it.

**Comment by PhineasFreak** [comment]
It is a proper release **but** it is not part of the normal kRPC redistributions: https://github.com/krpc/krpc/releases/tag/v0.3.8.post1. These are just fixes for the kRPC python client and **not** KSP binaries (i.e. something that would never be included in a normal release). However, i have no idea why this was marked as a "normal" kRPC release and i am sure that @djungelorm did not mean to mark it as such.

Since my words may not make a lot of sense "as is" i can provide some debug steps to follow:

* Open CKAN.
* Install kRPC as provided by the CKAN metadata.
* Download the latest kRPC redistribution from [here](https://github.com/krpc/krpc/releases/tag/v0.3.8).
* Open the folders and compare the contents of the two.

**Comment by Olympic1** [comment]
@PhineasFreak PR #5391 should fix this and future releases

**Comment by djungelorm** [comment]
This was indeed not intended to be a release of the kRPC mod archive shared via CKAN. Those regex changes look good to me! Thanks.
