### ISSUE TITLE
Throttle Controlled Avionics

### ISSUE THREAD

**Issue by qfeys** [KSP-CKAN/NetKAN#540]
Hi, 
could you add throttle controlled avionics to the library? The code of the .netkan file is pasted underneath. I've tested it and it seems to work on my computer.
Thanks

{
    "spec_version" : 1,
    "identifier"   : "ThrottleControlledAvionics",
    "$kref"        : "#/ckan/kerbalstuff/510",
    "x_netkan_license_ok": true
}

**Comment by hakan42** [comment]
ThrottleControlledAvionics had a broken avc version file. Issues are fixed, the ckan should be available within the hour.
