### ISSUE TITLE
FASA dependency - 

### ISSUE THREAD

**Issue by bthylafh** [KSP-CKAN/NetKAN#5447]
FASA requires RealChute Parachute Systems for correct parachute function, but this dependency isn't noted in CKAN.

**Comment by Olympic1** [comment]
FASA doesn't require RealChute in any way, so don't know what you mean.

**Comment by bthylafh** [comment]
Sorry for not being clear.  What I mean is that without RealChute installed, the FASA chutes won't slow your craft enough for a safe landing.  For example, a Project Mercury shot using the Mercury chute will hit the surface at ~70 m/s without RealChute installed, but with it present the ship will slow to a survivable ~5 m/s.  A similar thing happens with a Gemini and an Apollo shot.

This was tested on a fresh KSP 1.2.2 install with no other mods besides MechJeb and Kerbal Engineer.

**Comment by Olympic1** [comment]
I can maybe add it as a recommendation or suggestion, but you need to be sure there is no problems with both mods. Apparantly it was removed because there were some problems with it.

**Comment by bthylafh** [comment]
OK.  I'm opening a bug report with FASA to see what they say.

**Comment by bthylafh** [comment]
A dev says this is not unexpected: they develop FASA mainly for Realism Overhaul, FAR, et al and not so much for stock, but will consider contributed fixes for stock.

I suppose this bug report should be closed since it's basically unknown whether RealChute might break anything with stock configs.
