### ISSUE TITLE
Coyote Space Industries - Cargo Freighter 0.2.0 Packaging Bug

### ISSUE THREAD

**Issue by Esquire42** [KSP-CKAN/NetKAN#5460]
<img width="320" alt="screen shot 2017-05-01 at 18 16 51" src="https://cloud.githubusercontent.com/assets/24740020/25600614/60fb0ed4-2e9a-11e7-94a8-302dfb6be3ff.png">
Attempting to install this mod with USI Tools already installed results in the following error. USI Tools might not be a dependency in the metadata

**Comment by linuxgurugamer** [comment]
working on it now
