### ISSUE TITLE
BDArmoryContinued is Missing 'PhysicsRangeExtender'

### ISSUE THREAD

**Issue by pirateswarm** [KSP-CKAN/NetKAN#5469]
Hello CKAN,

I have been attempting to use CKAN to install BDArmoryContinued, however, recent versions of BDArmory maintained by Papa_Joe now includes mod 'PhysicsRangeExtender'. Installing via CKAN, excludes mod 'PhysicsRangeExtender' causing there to be compatibility & gameplay issues along with affecting Contract Configuration contract packs. Please include 'PhysicsRangeExtender' in the CKAN BDArmoryContinued mod install.

I've linked the repository for Papa Joe:

https://github.com/PapaJoesSoup/BDArmory/releases

Thanks!

----------------------------------
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

Please note that this repository is strictly for metadata (issues relating to incorrect information about mods, missing versions, or incorrect installations). If you want to suggest something or report a bug relating to CKAN as a whole, open the issue in: https://github.com/KSP-CKAN/CKAN

**Comment by politas** [comment]
PhysicsRangeExtender has a separate author. @jrodrigv, are you happy for PhysicsRangeExtender to be listed and installed by CKAN?
