### ISSUE TITLE
Advanced Jet Engine not showing up for KSP version 1.2.2.1622

### ISSUE THREAD

**Issue by Blu3wolf** [KSP-CKAN/NetKAN#5479]
I can see that its listed as being specifically for 1.2.2, could that be the issue?

https://github.com/KSP-CKAN/CKAN-meta/blob/master/AdvancedJetEngine/AdvancedJetEngine-v2.8.0.ckan

Line 17, 

`  "ksp_version": "1.2.2", `

**Comment by Olympic1** [comment]
`"ksp_version": "1.2.2",` means that if will only show up for 1.2.2. The reason it's not showing up is because there is no `FAR` version available for KSP 1.2.2.

**Comment by Blu3wolf** [comment]
Ahh, that would do it. I should have figured that one out, what with the having to manually install that one. 

Cheers!
