### ISSUE TITLE
Error on KWRocketryRedux-InstantPwr update

### ISSUE THREAD

**Issue by AeonDave** [KSP-CKAN/NetKAN#5503]
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/NetKAN/issues/new

Please including the following information in your report:

File           : GameData/KWRocketry/Parts/Engines/1mMaverick1D/KW1mengineMaverick1D.cfg
Installing Mod : KWRocketryRedux-InstantPwr 3.1.2
Owning Mod     : KWRocketryRedux
CKAN Version   : v1.22.1-0-g174271a (beta)

Your GameData has been returned to its original state.

**Comment by khr15714n** [comment]
About to install...

 * KW Rocketry Redux 3.1.2
 * KW Rocketry Redux - Graduated Power Response Configs 3.1.2

Downloading "https://github.com/linuxgurugamer/KWRocketryRedux/releases/download/3.1.2/KWRocketryRedux-StandardInstall-3.1.2.zip"
Module "KW Rocketry Redux" successfully installed

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/NetKAN/issues/new

Please including the following information in your report:

File           : GameData/KWRocketry/Parts/Engines/1mMaverick1D/KW1mengineMaverick1D.cfg
Installing Mod : KWRocketryRedux-GraduatedPwr 3.1.2
Owning Mod     : KWRocketryRedux
CKAN Version   : v1.22.1-0-g174271a (beta)

Your GameData has been returned to its original state.




Error!
-----------------
Same here ...
Cleared CKAN cache, removed KWRocketry before after first try to update.
There's an "Extras" folder included with different Configs (GraduatedPowerResponseConfigs and InstantPowerResponseConfigs). Seems when CKAN tries to install GraduatedPowerResponseConfigs - "GameData/KWRocketry/Parts/Engines/1mMaverick1D/KW1mengineMaverick1D.cfg" is the first file within the folder - the issue arises. And like a good boy CKAN removes all changes it has done. Thus no KWRocketry gets installed.

**Comment by Olympic1** [comment]
@linuxgurugamer its your mod. Apparantly the latest release only has 1 zip file while the previous releases had 2. It was always downloading the `KWRocketryRedux.zip` but this isn't available in v3.1.2

**Comment by mipla23** [comment]
Same here:

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/NetKAN/issues/new

Please including the following information in your report:

File           : GameData/KWRocketry/Parts/Engines/1mMaverick1D/KW1mengineMaverick1D.cfg
Installing Mod : KWRocketryRedux-GraduatedPwr 3.1.2
Owning Mod     : KWRocketryRedux
CKAN Version   : v1.22.1-0-g174271a (beta)

Your GameData has been returned to its original state.



Error!

**Comment by linuxgurugamer** [comment]
ok, I'll take care of it

**Comment by linuxgurugamer** [comment]
I've uploaded the missing file, does anything need tob e done for CKAN to see it?

**Comment by linuxgurugamer** [comment]
Guess not, test had it work properly now.
Can someone verify and close this please?

**Comment by khr15714n** [comment]
Works fine, thanks.
