### ISSUE TITLE
can we get    [1.2.2] Mark One Laboratory Extensions (M.O.L.E.) v.1.6.6   added to ckan?

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/NetKAN#5514]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

Please note that this repository is strictly for metadata (issues relating to incorrect information about mods, missing versions, or incorrect installations). If you want to suggest something or report a bug relating to CKAN as a whole, open the issue in: https://github.com/KSP-CKAN/CKAN

**Comment by Olympic1** [comment]
Last year @Angel-125 wanted to de-list his mods from CKAN, so we respect his decision.

Reference #4294
