### ISSUE TITLE
How to update my old mod after Kerbalstuff is shutdown?

### ISSUE THREAD

**Issue by satoi8080** [KSP-CKAN/NetKAN#5520]
I was AFK from KSP about 2 years ago. I made a mod then, and uploaded it to Kerbalstuff, and now I find Kerbalstuff was shutdown.
Now I can find my old mod in CKAN (filter: incommpatible) , but it seems to be automatically added to ckan via Kerbalstuff.

I found a file [here](https://github.com/KSP-CKAN/NetKAN/blob/ada4f8324490724f517801fdd0bf2432612cf9bf/NetKAN/SpearofLonginus.frozen) that seems to be relevant to this issue.

I have to update it, and I [uploaded it to GitHub.](https://github.com/satoi8080/KSP-Spear-of-Longinus) and added a .netkan file according to the instruction. 
How to update(or override) the old one to the new one now?

You could see #695 to prove I'm the author (my formal ID was tetsuchou and I don't know how it knew it was me! My avatar is on [a6bfe69](https://github.com/KSP-CKAN/NetKAN/pull/695/commits/a6bfe6978622e918bc37502c7fdab5082b1e32c1))
or  see [here](http://forum.kerbalspaceprogram.com/index.php?/topic/99734-122spear-of-longinus/) which contains my GitHub link.

**Comment by politas** [comment]
Hi satoi8080! Thanks for getting in touch! You'll need to create a Release for your mod in GitHub so that the Netkan bot can see it. As a reference, your last release on kerbalstuff was 0.7, so as long as you use a higher version number than that, it should work. Your proposed .netkan file needs a bit of work, though, so I'll fix that up.

**Comment by satoi8080** [comment]
Hi @politas ! I made a  pull request, but the Jenkins says "Existing Frozen Identifier". Can you remove it?
By the way, does every time I update a version needs a pull request?

**Comment by Olympic1** [comment]
Merged with #5527, closing.
