### ISSUE TITLE
ImprovedStrategies v0.12 not working if installed from CKAN

### ISSUE THREAD

**Issue by vtdmhd** [KSP-CKAN/NetKAN#554]
The CKAN version unzips to gamedata/Strategies instead of gamedata/ImprovedStrategies/Strategies. It gets loaded after SQUAD's strategies.cfg and the original unmodded file gets used.

**Comment by hakan42** [comment]
Actually, now that I think about it, maybe the installation folder should be something like 000_ImprovedStrategies like it is with 000_Toolbar. 
This would make it obvious that the loading order is important. But it would require the ImprovedStrategies project to provide a changed zip file so people installing via CKAN or manually both see the same result.

**Comment by borsek** [comment]
renamed folder, might help, if not, I'll add a file structure - gamedata folder to the zip
