### ISSUE TITLE
Checkbox anchor not set in File -> Select KSP Install...

### ISSUE THREAD

**Issue by matt1986** [KSP-CKAN/NetKAN#5541]
The "Set as default" Checkbox isn't anchored at the bottom left of the window, itstays at it's absolute position when resizing the window. See attached print screen

![anchor](https://cloud.githubusercontent.com/assets/29013822/26528224/9ca8925a-4374-11e7-9980-0b35daa86523.JPG)

**Comment by politas** [comment]
Can you raise this under [the CKAN repo](https://github.com/KSP-CKAN/CKAN/issues)?
