### ISSUE TITLE
ckan error

### ISSUE THREAD

**Issue by kek75** [KSP-CKAN/NetKAN#5548]
![egggggggggg](https://cloud.githubusercontent.com/assets/29028741/26532989/20e44d5a-43d6-11e7-9e6e-117b1c1ab6c7.PNG)

**Comment by maixgame** [comment]
I have the same problem 

![2017-05-29_03-55-36](https://cloud.githubusercontent.com/assets/25564867/26533530/ce26f160-4422-11e7-8cce-3eea572fc78a.png)

**Comment by Olympic1** [comment]
This should now be fixed, feel free to reopen when this issue still persists.
