### ISSUE TITLE
CKAN crashes when I try to install any of the USI related mods to KSP

### ISSUE THREAD

**Issue by HegemonyCricket** [KSP-CKAN/NetKAN#5554]
I am using CKAN v.1.22.3. and KSP v.1.3.0.1804. When I attempt to install any of the USI Tools dependent USI mods, CKAN crashes. Unfortunately, I did not record the error. It ultimately did install USI Tools, but then all of the dependent USI mods reported a conflict with USI Tools.

**Comment by Olympic1** [comment]
See #5544
