### ISSUE TITLE
NEOS / OMS in CKAN

### ISSUE THREAD

**Issue by mwerle** [KSP-CKAN/NetKAN#5557]
Now that [Nehemiah has given me the go-ahead](http://forum.kerbalspaceprogram.com/index.php?/topic/73723-090-orbital-material-science-version-06/&do=findComment&comment=2868282) to be the official maintainer until his (hopefully soon) return, I'd like to investigate how best to get his excellent mod-collection into CKAN.

Basically it consists of a number of very closely-linked mods which all share a plugin and some common configuration/models (names below correspond to the current directory paths):

1. Kemini - early science using just the Mk1 capsule
   * Requires: Module Manager
1. KEES - mid-level science, using KAS to attach various exposure experiments to the outside of a craft
   * Requires Kerbal Attachment System
   * Recommends: K2 Command Pod
1. KerbalLifeScience/OMS - end-level station science requiring building a station and using various supply missions to stock it with equipment and experiments
   * Recommends: Connected Living Spaces
1. MultiPurposeParts- Common parts (not released as a separate mod at present, but included in KLS and OMS)
1. NE_Science_Common - Plugin and common configuration (not released as separate mod at present, but included in Kemini/KEES/KLS/OMS)

The first 4 are released as separate downloads, as well as in a single "Science Pack" download. Each of the components has an AVC-compatible version file, and all are released via GitHub at present:
https://github.com/mwerle/OrbitalMaterialScience/releases

All mods are installed under GameData/NehemiahInc

Part of the reason for splitting the mods up originally was due to the relatively large download-sizes of some of them (affected some users), as well as some users only wanting a subset (usually Kemini). By far the biggest number of downloads is for the "Science Pack" though.

How would you recommend the mods be structured in future to be both good for CKAN as well as continuing to be good for standalone distribution?  I don't really want standalone users to have to download A + B + C separately before they have a usable install.

For CKAN I'm guessing having a "lite" version of each download which only includes its own data, with links to the dependent mods, then for standalone distribution have the current "full" versions which include the dependencies inside the ZIP.

Alternatively could just link the "Science Pack" for CKAN, which means CKAN users would always have to do the full download (14MiB) on any update.

**Comment by Olympic1** [comment]
We still have the netkan files for these mods. They are still pointing to KS but easy to change to your github.

This is the structure I plan:

* Nehemiah Science Common
    * Gets `NE_Science_Common` from KEES
    * Depends on ModuleManager
* Nehemiah Multi Purpose Parts
    * Gets `MultiPurposeParts` from MultiPurposeParts
    * Depends on ModuleManager
* Kerbal Environmental Effects Study
    * Depends on NehemiahScienceCommon & KIS
    * Recommends K2CommandPodCont
* Kemini Research Program
    * Depends on NehemiahScienceCommon
* Kerbal Life Science
    * Depends on NehemiahScienceCommon & NehemiahMultiPurposeParts
    * Recommends ConnectedLivingSpace
* Orbital Material Science
    * Depends on NehemiahScienceCommon & NehemiahMultiPurposeParts
    * Recommends ConnectedLivingSpace
* Nehemiah Inc - All-in-one Pack
    * Depends on ModuleManager & KIS
    * Recommends K2CommandPodCont & ConnectedLivingSpace

This way people can install some ones seperatly or choose to use the all-in-one pack

**Comment by mwerle** [comment]
> "We still have the netkan files for these mods. "

great  :)  I was just reading up on how to make them..

> "Gets NE_Science_Common from KEES"

Ah so I don't have to break apart the ZIPs I currently build/release to best suit CKAN?  

And how does that work - does it effectively extract NE_Science_Common from the KEES release, and repackage it? If so where is it hosted (I thought CKAN was just metadata repo). Also, the "all-in-one" would be the better ZIP to extract NE_Science_Common from as that is always guaranteed to be updated (In future, some releases may update only some parts, eg, a bug-fix in Kemini only) 
Otherwise any download will download KEES + whatever, even though <whatever> already includes NE_Science_Common, or am I misunderstanding something here?

> "Gets MultiPurposeParts from MultiPurposeParts" 

There is currently no separate "MultiPurposeParts" download (although I can make one).

I just joined #ckan - @Micha - but going to lunch soon. Can discuss further this afternoon if you're free.

**Comment by Olympic1** [comment]
> Ah so I don't have to break apart the ZIPs I currently build/release to best suit CKAN?

No, the way it is now will work.

> And how does that work - does it effectively extract NE_Science_Common from the KEES release, and repackage it? If so where is it hosted (I thought CKAN was just metadata repo).

Because KEES depends on NehemiahScienceCommon, we can download the KEES zip and only install the `NE_Science_Common` folder. When it tries to install KEES it already has downloaded the zip and will only install the KEES folder.

> Also, the "all-in-one" would be the better ZIP to extract NE_Science_Common from as that is always guaranteed to be updated (In future, some releases may update only some parts, eg, a bug-fix in Kemini only)
Otherwise any download will download KEES + whatever, even though already includes NE_Science_Common, or am I misunderstanding something here?

If this will always be updated it is better to install it from here, but if we need to download it just to get NE_Science_Common for KEES, this take up extra space. But we can discuss this further on IRC.

> There is currently no separate "MultiPurposeParts" download (although I can make one).

That was a typo, I meant "Gets MultiPurposeParts from KLS" (or other zip)

> I just joined #ckan - @micha - but going to lunch soon. Can discuss further this afternoon if you're free.

Great, just ping me (Olympic1) on there when you're back.
