### ISSUE TITLE
6.4k scale overhaul (request for putting on CKAN

### ISSUE THREAD

**Issue by Kerbinorbiter** [KSP-CKAN/NetKAN#5566]
I' am the author of a new mod-6.4k scale overhaul-it adds KScale64 (though you can use any 6.4 scale kerbin sized body) configs to the game
forum threadhttp://forum.kerbalspaceprogram.com/index.php?/topic/161381-122-64k-overhaul/
Currently for version 1.2.2
requires: Module manager so it should work in 1.3 currently but when i add mod configs the version will be tied to the mod with the lowest KSP version more info on the forum thread 
Download: https://github.com/Kerbinorbiter/64k-overhaul/releases/tag/p0.01
thanks in advance
-KerbinOrbiter

**Comment by Kerbinorbiter** [comment]
Wow issue for me wasn't awake good job brain

**Comment by politas** [comment]
Hi Kerbinorbiter. We don't list pre-release versions of mods in the main CKAN repo, so your mod won't be added until you upgrade to a full release or push a separate full release. Does your mod not use Kopernicus at all?

**Comment by politas** [comment]
Ah, I see, it's just resource modifications for stock parts to make them work better in a 6.4k scale system?

**Comment by Kerbinorbiter** [comment]
Yes that is correct @politas it is a resource modification for 6.4k scale stock
