### ISSUE TITLE
compatibility issue with the KSP 3.0 update and CKAN 1.2.2

### ISSUE THREAD

**Issue by MJJM-Matthius** [KSP-CKAN/NetKAN#5574]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

Please note that this repository is strictly for metadata (issues relating to incorrect information about mods, missing versions, or incorrect installations). If you want to suggest something or report a bug relating to CKAN as a whole, open the issue in: https://github.com/KSP-CKAN/CKAN

**Comment by politas** [comment]
No issue content
