### ISSUE TITLE
MaErDa Beta Tester Pack Submission to CKAN

### ISSUE THREAD

**Issue by Warsoul112** [KSP-CKAN/NetKAN#5580]
Idk why i can't upload my MaErDa.netkan

[MaErDa.txt](https://github.com/KSP-CKAN/NetKAN/files/1049640/MaErDa.txt)

https://spacedock.info/mod/899/MaErDa%20Corp%20Beta%20Testers%20Pack

**Comment by Olympic1** [comment]
We already tried to add you mod to CKAN but you told us that you didnt want to.

Ref: http://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1223-mahia/&do=findComment&comment=3072391

PR: #5534

**Comment by Warsoul112** [comment]
Because i was missclicked in SpaceDock. but now i'm ready i think.

**Comment by Warsoul112** [comment]
Anyway SpaceDock show my Mod has CKAN rdy anyway

**Comment by Warsoul112** [comment]
It took how many time before CKAN is updated ?
