### ISSUE TITLE
TestFlight 1.8.0.0 – needs minimum KSP version set to 1.2

### ISSUE THREAD

**Issue by bfrobin446** [KSP-CKAN/NetKAN#5583]
Used CKAN to set up an archived install of KSP 1.1.3 as RP-0. CKAN incorrectly showed TestFlight 1.8.0, which is compiled for KSP 1.2, as compatible with my KSP installation. I had to manually downgrade to TestFlight 1.7, which was built for KSP 1.1.3, to get TestFlight to work.

**Comment by Olympic1** [comment]
Fixed in https://github.com/KSP-CKAN/CKAN-meta/pull/1275
