### ISSUE TITLE
Overwrite Error - Interstellar Fuel Switch

### ISSUE THREAD

**Issue by SentryRaven** [KSP-CKAN/NetKAN#5588]
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/NetKAN/issues/new

Please including the following information in your report:

File           : GameData/InterstellarFuelSwitch/Resources/ModuleFuelJettison.cfg
Installing Mod : InterstellarFuelSwitch-Core 2.6.1
Owning Mod     : InterstellarFuelSwitch
CKAN Version   : v1.22.3

Your GameData has been returned to its original state.

Error!

**Comment by Olympic1** [comment]
Should be fixed now
