### ISSUE TITLE
ASET IVA Replacement issue

### ISSUE THREAD

**Issue by tabbycat12** [KSP-CKAN/NetKAN#5599]
I'm getting this error:
---------------------------------------------------------------------
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/NetKAN/issues/new

Please including the following information in your report:

File           : GameData/ASET/MK1-2_IVA_Replacement_by_ASET/MK1-2_ASETinternal-patch.cfg
Installing Mod : MK12PodIVAReplacementbyASET 1:0.2
Owning Mod     : MK12PodIVAReplacementbyASET2
CKAN Version   : v1.22.3

Your GameData has been returned to its original state.

---------------------------------------------------------------------

....running CKAN 1.22.3 on KSP 1.2.2.1622.

It looks like two of the ASET mods are arguing over the same file. It happens when I go to install the MK1-2 IVA replacement, and I think it's conflicting with the Mk1 Cockpit replacement.

**Comment by politas** [comment]
No, the installing mod and Owning mod appear to be the same. Try uninstalling it and reinstalling

**Comment by lolman824** [comment]
Hello, I'm facing a problem where when I install these mods (as shown in the screenshot), I get this error (as shown in the screenshot), and reinstalling them either manually or through CKAN doesn't solve the issue. Can you please advise on what I should do?

<img width="594" height="197" alt="Image" src="https://github.com/user-attachments/assets/0cb9e975-e46a-4780-965f-833b0a713a15" />
<img width="433" height="86" alt="Image" src="https://github.com/user-attachments/assets/8d78d6b0-aa50-4d64-bf81-006623f93459" />

**Comment by HebaruSan** [comment]
> Can you please advise on what I should do?

Yes @lolman824, you can find mods' forum threads on the right side of CKAN under "Home page". Try asking there.

<img width="643" height="844" alt="Image" src="https://github.com/user-attachments/assets/c52dca8e-44a9-49cd-99f3-dbcc4268d819" />

**Comment by lolman824** [comment]
Thank you
