### ISSUE TITLE
"Shuttle Lifting body" will crash the game on load.

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/NetKAN#5614]
there is an erroneous folder included in the Download shown here in **_Bold_**

\KSP\1.3\GameData\Cormorant Aeronology\Assets\mk3_Shuttle\ **_Cormorant Aeronology 1.2.2b_**

this folder should not be in the install and needs to be removed.

**Comment by politas** [comment]
This folder appears to have been removed in later versions of the mod.
