### ISSUE TITLE
MOLE Mod

### ISSUE THREAD

**Issue by DrFish6t9** [KSP-CKAN/NetKAN#5624]
Hi,
Really find your program useful but maybe I am not doing something right any more, or the modders have changed, but one of the most useful mods (MOLE), my CKAN says its version 0.7.7 but online its at version 1.70...the old version does not work with the newer version of KSP.

I've just deleted all my mods (CKAN was erroring out when I tried to update any mod saying they were not there) and freshly nstalled CKAN and there is a lot of mods in the not-compatible list now esp MOLE.

Just wondering if there is something that I Can do to get the latest mod lists, it is supposed to update itself with every load.
Many thanks

**Comment by Svish** [comment]
Not a CKAN answer, but for that mod specifically, if you haven't already, you can download the latest version from [SpaceDock](https://spacedock.info/mod/792/M.O.L.E.) and install it manually. That's what I did when I couldn't find the latest version in CKAN at least... 🙂

**Comment by solarsootysmudge** [comment]
Game should be installed to seprate folder after each update. So previous game versions are still available whilst waiting for mod updates. A lot of people are still playing KSP 1.2 even if 1.3 has been out of a while. Until their favourite mods migrate across. 

After most have migrated to new game version. Old mods left behind can still be used by clicking on the settings menu. Then selecting Compatible Ksp Versions. The lets you force load old mods by picking an old KSP version allowed. However please note the red warning: **There is no way to check if a mod is fully compatible !!!**

So use the force install method at your own risk. The end user must take responsibility to ensure they have read all the mods documentation. To ensure it is safe to use in this way. If you have done the due diligence in checking compatible mods. This method will work like a charm and you don't have to wait for the index to update.

Finally in regard to MOLE. Take this with a pinch of salt. This comment based on a conversation from last year. Although not mentioned in CKAN opt out policy now. Angel-125 may have requested that MOLE was not to be supported at that time. I also noted at the time that support was at risk (folders changed fequently). So can I please ask future maintainers to check carefully on current situation before pushing a new Netkan in regard to MOLE or any other Angel-125 mod?

As @Svish has said for MOLE you can download the latest version from SpaceDock. Please install it manually for now.

**Comment by politas** [comment]
Angel-125 is on the [Opt-Out List](https://github.com/KSP-CKAN/CKAN/blob/master/policy/Opt-out-list.md). There will be no updates to Mark One Laboratory Extensions until Angel-125 approaches us asking to be taken off that list.
