### ISSUE TITLE
RetractableLiftingSurface - should use version 0.1.3 on KSP 1.2.2

### ISSUE THREAD

**Issue by bfrobin446** [KSP-CKAN/NetKAN#5631]
The KSP-AVC file included with RetractableLiftingSurface 0.1.4 claims that this version of RetractableLiftingSurface is compatible only with KSP 1.3 or higher, but CKAN installed it on KSP 1.2.2. I had to perform a manual downgrade to RetractableLiftingSurface 0.1.3.

**Comment by linuxgurugamer** [comment]
This happened because of a bad initial upload, so CKAN indexed the wrong file.
I've directly edited the CKAN meta file to fix the file version, and after a refresh, the CKAN program now installs the correct version on 1.2.2

**Comment by bfrobin446** [comment]
CKAN is still showing RetractableLiftingSurface 0.1.4 as available on my 0.2.2 install.

**Comment by politas** [comment]
Have you restarted CKAN after clicking on "Refresh"?
