### ISSUE TITLE
KSP Interstellar version is wrong (in CKAN metadata is 1.4.3 but the correct latest one is 1.14.3)

### ISSUE THREAD

**Issue by minecraft2048** [KSP-CKAN/NetKAN#5635]
Looking at history of KSP Interstellar 1.4.3: https://github.com/KSP-CKAN/CKAN-meta/commit/7a3659a1663109303d2117c726766de6c5ca0ff0 NetKAN somehow changed a very old version of KSP Interstellar that is from KSP version 1.0.4 to 1.3.0, breaking pyKAN (and probably mainline CKAN client) as it tries to download from spacedock and fails with a 404 error as the file does not exist.

Looking at KSP Interstellar Github repo, FreeThinker correctly writes in his .version file as 1.14.3, so it is probably not his fault: https://github.com/sswelm/KSP-Interstellar-Extended/commit/f91426fb93dc7efdc08f90b8226e358366948f1c

**Comment by minecraft2048** [comment]
Link to KSP Interstellar thread reporting this: http://forum.kerbalspaceprogram.com/index.php?/topic/161531-13-ksp-interstellar-extended-1143-4-6-2017-continued-development-thread/&do=findComment&comment=3093335

**Comment by sswelm** [comment]
Actually, I made a small mistake when uploading on spacedock where I forgot to add an 1, I removed the file and reuploaded the same file assuming it would fix the mistake. Apparently not.

**Comment by minecraft2048** [comment]
I don't know about that, but shouldn't spacedock or CKAN determine mod version from uploaded .version file? I think that Spacedock/NetKAN should complain if manually imported version differs from the .version file then

**Comment by minecraft2048** [comment]
I'm starting to think that only pyKAN have this problem, as it thinks that 1.4.3 > 1.14, but this issue is still relevant though, as wrong metadata is bad

**Comment by ajventer** [comment]
I have confirmed that the current version.py contains a bug which incorrectly determines 1.4.3 to be a higher version than 1.14 @minecraft2048 is currently doing some work on versioning as well so tagging him. I am looking into why this would be.

**Comment by ajventer** [comment]
I have found the bug in pyKAN, and just pushed a fix. The latest commit in git contains it. I will release a new official version with the fix once @minecraft2048 finishes his current work so it can all go into one release. In the meantime you can get the (small) fix by using the master-branch git code directly.

**Comment by politas** [comment]
metadata fixed in KSP-CKAN/CKAN-meta#1279
