### ISSUE TITLE
Taking over Contract Pack: Bases and Stations

### ISSUE THREAD

**Issue by LemonSkin** [KSP-CKAN/NetKAN#5636]
[ContractConfigurator-KerbinSpaceStation.zip](https://github.com/KSP-CKAN/NetKAN/files/1080052/ContractConfigurator-KerbinSpaceStation.zip)

Hi, this is the new netkan data for Bases and Stations. It redirects to my github and the new forum thread.
Cheers

**Comment by solarsootysmudge** [comment]
Confirmed working. Seen on CKAN 1,22.3 -KSP 1.3.0.1804
Thanks for carrying support for this excellent mod.

**Comment by politas** [comment]
Has been merged
