### ISSUE TITLE
the Phoenix Industries ARES Rover 1.2 is improperly packaged

### ISSUE THREAD

**Issue by firestarc333** [KSP-CKAN/NetKAN#5640]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

Please note that this repository is strictly for metadata (issues relating to incorrect information about mods, missing versions, or incorrect installations). If you want to suggest something or report a bug relating to CKAN as a whole, open the issue in: https://github.com/KSP-CKAN/CKAN

**Comment by politas** [comment]
Could you perhaps give us some details on _how_ it is wrong?

**Comment by HebaruSan** [comment]
@firestarc333, we need some information to be able to investigate and fix anything. Closing this for now; if you can share more details about the problem you observed, please reply here and we will re-open the issue.
