### ISSUE TITLE
Raidernick's mods updated to 1.3 version on 1.2.2 KSP

### ISSUE THREAD

**Issue by DegenerateGroundState** [KSP-CKAN/NetKAN#5645]
CKAN updated @raidernick 's various mods (Soviet Rockets, Soviet Probes, etc) to their new 1.3 version on my 1.2.2 KSP install today (6/20 around 12 pm EST). This prevents KSP from loading correctly, presumably due to the included plugins. I guess the max/min version number was set incorrectly.

CKAN version 1.22.3
CKAN identifies my game version as 1.2.2.1622, no other versions are checked on the Compatible Ksp Version window.

**Comment by raidernick** [comment]
The max/min version isn't set incorrectly. It's because they haven't merged my PR for the changes to 1.3 here yet. CKAN thinks the mod was updated for 1.2.2 which it wasn't. You'll need to push them to merge it soon if you don't want it to happen again.

**Comment by politas** [comment]
Now merged. Uninstall & reinstall on KSP 1.2.2 should get it back to the correct version
