### ISSUE TITLE
Feature request: Show reverse depends relationships

### ISSUE THREAD

**Issue by Svish** [KSP-CKAN/NetKAN#5646]
In this relationship type selector menu screenshotted(?) below here... Could another option be added, called something like Dependees (or whatever would be the best english word for it), that would list which *currently installed* mods depends on *this* mod?

Want to clean up my mods a bit, and that would be much easier if I could just select one I don't think I need, and then get a list of which mods depends on it, and if that list is empty, I know I can safely remove it.

![capture](https://user-images.githubusercontent.com/142162/27350224-1248fbb6-55fa-11e7-8506-46718da3b518.PNG)

So in this screenshot, `Near Future Solar Core` should show me that it is required/depended upon by `Near Future Solar`.

**Comment by Dazpoet** [comment]
See https://github.com/KSP-CKAN/CKAN/issues/978

**Comment by HebaruSan** [comment]
Looks like this is addressed by KSP-CKAN/CKAN#2753. Now we track which mods were auto installed, so this clean-up is automatic.
