### ISSUE TITLE
"Maritime Pack" & "1869 Steam punk"

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/NetKAN#5673]
Why are these two mods dependent on each other?  I know they are both from the same modder, but they really do not belong together.   I should not have to have all the steam punk stuff loaded up to get the maritime pack parts.

if they have a common .dll or something should this not be setup as a 
"core mod" and then the other 2 both depend on that core?

**Comment by gandalf3** [comment]
Plus, "1869 Steampunk" is [currently causing KSP to crash on startup](http://forum.kerbalspaceprogram.com/index.php?/topic/145330-13x-1869-steampunk-mod-updated-for-ksp-13/&page=2#comment-3129500).

**Comment by politas** [comment]
Both mods have been removed at the request of the mod author
