### ISSUE TITLE
Aviation Lights v3.13 incorrectly marked compatible with KSP 1.2.2.1622

### ISSUE THREAD

**Issue by S4qFBxkFFg** [KSP-CKAN/NetKAN#5680]
When using CKAN to install the Aviation Lights mod, it crashes on loading.

This appears to be because (probably due to bad metadata) CKAN is suggesting the v3.13 for a KSP install of 1.2.2 when it should probably be suggesting v3.12

See this post: http://forum.kerbalspaceprogram.com/index.php?/topic/16801-13-aviation-lights-v314-by-moardv/&do=findComment&comment=3087019

**Comment by politas** [comment]
Thanks for the report!
