### ISSUE TITLE
Multiple Mods Require Updating

### ISSUE THREAD

**Issue by AirwaveRaptor** [KSP-CKAN/NetKAN#5694]
Multiple mods have released updates that have not been added to CKAN yet:

ALL SETI mods, including those linked to RemoteTech
AmpYear Power Manager
Connected Living Space
Kerbal Konstructs
Filter Extensions
Contract Configurator
Contract Pack: Field Research
TAC Life Support
Cryogenic Engines

**Comment by solarsootysmudge** [comment]
Index should have picked most these up. Check again.
