### ISSUE TITLE
Custom Barn Kit

### ISSUE THREAD

**Issue by mbdixon68** [KSP-CKAN/NetKAN#5695]
Custom Barn Kit needs to be updated to version 1.1.13.0 to make it compatible with KSP v1.3. Thanks.

**Comment by politas** [comment]
There seems to be a problem with @sarbian 's AVC file in 1.1.13

`{
    "NAME": "CustomBarnKit",
    "URL": "https://ksp.sarbian.com/jenkins/job/CustomBarnKit/lastSuccessfulBuild/artifact/CustomBarnKit/CustomBarnKit.version",
    "DOWNLOAD": "http://forum.kerbalspaceprogram.com/index.php?/topic/109027-/",
    "VERSION":{
        "MAJOR": 1,
        "MINOR": 1,
        "PATCH": 13,
        "BUILD": 0
    },
    "KSP_VERSION": {
        "MAJOR": @KSP_MAJOR@,
        "MINOR": @KSP_MINOR@,
        "PATCH": @KSP_PATCH@
    },
    "KSP_VERSION_MIN": {
        "MAJOR": 1,
        "MINOR": @KSP_MINOR_MIN@,
        "PATCH": 2
    },
    "KSP_VERSION_MAX": {
        "MAJOR": 1,
        "MINOR": @KSP_MINOR_MAX@,
        "PATCH": 0
    }
}`

@Sarbian, are those @NAME@ variables something in your code, or is there an update to the AVC format that CKAN needs to support?

**Comment by sarbian** [comment]
No, my template was messed up. It is fixed now.
