### ISSUE TITLE
This is no good

### ISSUE THREAD

**Issue by kiwi1960** [KSP-CKAN/NetKAN#5697]
I thought CKAN might make it faster to install mods on a clean install. So far, I have wasted 5 hours and multiple attempts to download mods. It keeps crashing, so rather than waste another 5 hours, I WON'T BOTHER USING THIS GARBAGE ANY MORE! That is 5 hours I have wasted. I'd be playing the game by now if this .... thing ... (trying to be polite, wanted to use a word start with C and ending in P with A and R in the middle. I will NEVER bother using this again.

**Comment by Dazpoet** [comment]
Thank you for your constructive feedback.
