### ISSUE TITLE
 Research Bodies install path changed : GameData/REPOSoftTech> not <GameData/ResearchBodies>

### ISSUE THREAD

**Issue by solarsootysmudge** [KSP-CKAN/NetKAN#5699]
The install file should be <GameData/REPOSoftTech>, but CKAN installs the mod as <GameData/ResearchBodies>. The folder called ResearchBodies is found within REPOSoftTech, along with a couple of other folders that as a result do not get installed. The wrong install causes several bugs. 

Copied from forum report by ev0

tested on CKAN 1,22.3 -KSP 1.3.0.1804

**Comment by solarsootysmudge** [comment]
Also needs Dependency: Contract Configurator

**Comment by politas** [comment]
Thanks for bringing it to our attention, @solarsootysmudge!
