### ISSUE TITLE
 Action Group Manager Continued 

### ISSUE THREAD

**Issue by emirkustirika** [KSP-CKAN/NetKAN#5723]
Action Group Manager Continued a new mod and  Action Group Manager  not work any more 

http://forum.kerbalspaceprogram.com/index.php?/topic/161919-13-en-es-action-group-manager-continued/&page=2#comment-3126941

this iis new mod page and pls add  the ckan on thess mod thank u.

Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

Please note that this repository is strictly for metadata (issues relating to incorrect information about mods, missing versions, or incorrect installations). If you want to suggest something or report a bug relating to CKAN as a whole, open the issue in: https://github.com/KSP-CKAN/CKAN

**Comment by linuxgurugamer** [comment]
Can you provide some more specifics, just saying that it doesn't work is not helpful

**Comment by linuxgurugamer** [comment]
I think this can be closed, as far as I know, the mod works and is installable via CKAN

**Comment by linuxgurugamer** [comment]
@politas 
@Olympic1 

Pinging you

**Comment by politas** [comment]
Existing ActionGroupManager is Spacedock mod 1412; I can't see a problem.
