### ISSUE TITLE
BDArmory Weapons Extension is showing the wrong version number it should be v1.9 not 1.8.1

### ISSUE THREAD

**Issue by NextStarIndustries** [KSP-CKAN/NetKAN#5818]
BDArmory Weapons Extension is showing the wrong version number it should be v1.9 not v1.8.1

**Comment by NextStarIndustries** [comment]
NetKAN is correct but CKAN isn't.

**Comment by politas** [comment]
v_1.8.1 comes after v1.9 unfortunately.
