### ISSUE TITLE
AnalogControlContinued-2.1.3.ckan contains wrong KSP version information

### ISSUE THREAD

**Issue by SerTheGreat** [KSP-CKAN/NetKAN#5824]
Please correct the following data in the AnalogControlContinued-2.1.3.ckan:
"ksp_version_min": "1.2.2",
"ksp_version_max": "1.3.0"

I guess because of this CKAN installs version 2.1.3 into KSP 1.2.2, which is wrong.
Correct metadata should be:
"ksp_version": "1.3.0",

**Comment by HebaruSan** [comment]
This is happening because the `AnalogControlContinued.version` file shipped in the archive says 1.2.2.

Pull request to fix that: https://github.com/SerTheGreat/Analog-Control-continued/pull/1

**Comment by politas** [comment]
Even if that is merged, it won't fix the .ckan file we have, I fear. Thus ^^
