### ISSUE TITLE
[Request] Remove or freeze RSSVE

### ISSUE THREAD

**Issue by PhineasFreak** [KSP-CKAN/NetKAN#5830]
I have been getting bug reports from users that are installing RSSVE via CKAN. I would like to request either a complete removal or a temporary freeze of the metadata (so it is not accessible) until a non-dev version is released (currently RSSVE is still in a "release candidate" state, meaning it does not have a proper package release).

Thank you for your time.

**Comment by HebaruSan** [comment]
Try checking the "This is a pre-release" box when creating the releases on Github. CKAN should ignore such releases.

**Comment by Olympic1** [comment]
Done, sorry for the inconvenience

**Comment by PhineasFreak** [comment]
@HebaruSan Unfortunately i am not the one that manages the metadata. Someone went and added it, even if had explicitly stated that it should not be, for the time being, on CKAN.

@Olympic1 Thank you!

**Comment by HebaruSan** [comment]
@PhineasFreak , I'm not referring to metadata. I mean the releases created on the repository on your GitHub account. When you create/edit them, there's a checkbox "This is a pre-release" that can be used to keep that release out of CKAN, even if someone else adds it without your permission:

![image](https://user-images.githubusercontent.com/1559108/31034598-59406dcc-a52a-11e7-9786-300fe406a83b.png)

Glad it's sorted now, though!

**Comment by Olympic1** [comment]
He is releasing them as pre-release's. This is the latest release:
![release](https://user-images.githubusercontent.com/8020752/31035247-9b885090-a567-11e7-8dea-ebd0f21728a3.PNG)

https://github.com/PhineasFreak/RSSVE/releases

**Comment by HebaruSan** [comment]
Sorry, my mistake. I thought I checked that.
I take it the "workaround" was to directly include the `download` field in the .netkan?

**Comment by Olympic1** [comment]
yes
