### ISSUE TITLE
Kaptain's Log is mucking about with DMagic's progress parser

### ISSUE THREAD

**Issue by madlemur** [KSP-CKAN/NetKAN#5856]
```
File           : GameData/DMagicUtilities/ProgressParser/License.txt
Installing Mod : KaptainsLog 0.1.0
Owning Mod     : ProgressParser
CKAN Version   : v1.22.3+64309722a446
```
ProgressParser is needed fuctionality, but that should all be based on a depends relationship, not a direct inclusion in the release package. It's dying on the license file, but I presume that it would also die on the other files included in the release (which is everything, since he packaged it all together).

Should probably ask @linuxgurugamer to re-release without Progress Parser, and add it in as a dependency instead.

**Comment by linuxgurugamer** [comment]
Being fixed now, sorry

**Comment by linuxgurugamer** [comment]
No need to rerelease, I'm fixing the netkan.
