### ISSUE TITLE
TAC Life Support .90 Release

### ISSUE THREAD

**Issue by Almagnus1** [KSP-CKAN/NetKAN#586]
TAC Life Support has been updated to .90, and is available at:
http://www.curse.com/ksp-mods/kerbal/221022-tac-life-support-v0-10-2-25jan/2225501

See: http://forum.kerbalspaceprogram.com/threads/40667 for more info

**Comment by Ippo343** [comment]
Fixed in commit 39b47664c07f028bc8adb155044d4364534b97a7
