### ISSUE TITLE
Request.

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/NetKAN#5866]
is it possible to have CKAN mark all directories it is "controlling" as hidden?  so as it installs a mod it will hide that directory, then if it uninstalls it will unhide it ...  assuming it does not just delete it that is.

this would make searching through the game data folder for mods not under CKAN control much easier.  and it might prevent people from accidentally modifying a mod folder that is under CKAN control.

**Comment by Olympic1** [comment]
@Bit-Fiddler, can you open an issue on the [CKAN repo](https://github.com/KSP-CKAN/CKAN/issues/new)? This one is for reporting metadata problems.
