### ISSUE TITLE
CKAN Launched Game Not Loading

### ISSUE THREAD

**Issue by dragonspawn98** [KSP-CKAN/NetKAN#5867]
I can not get my launched game to load past half way. I uninstalled all my mods to see if that was the problem but it still continues. There's no error code it just doesn't continue to load. CKAN v1.22.3 - KSP 1.2.1.1604

**Comment by dragonspawn98** [comment]
I can not get my launched game to load past half way. I uninstalled all my mods to see if that was the problem but it still continues. CKAN v1.22.3 - KSP 1.2.1.1604

**Comment by dragonspawn98** [comment]
I have a copy of the game so I cant update it...

**Comment by politas** [comment]
It could be that CKAN is loading the 32bit version of KSP, which if you've modded it to heck and gone, will crash on loading. Check your **Settings - KSP command-line**
