### ISSUE TITLE
New Version for CatEye 2 Orbital Telescope is missing

### ISSUE THREAD

**Issue by herbiems89** [KSP-CKAN/NetKAN#5912]
The mod CatEye 2 Orbital Telescope seems to have been picked up by another modder and updated for V1.3. CKAN however only shows the old version for 1.0.

Here's the new mod: https://forum.kerbalspaceprogram.com/index.php?/topic/141298-130-cacteye-optics-community-takeover-updated-7182017/&

Is this something CKAN can do on their own or do you need permission from the modder?

**Comment by politas** [comment]
If you are referring to CactEye Optics Community, which replaces CactEye 2 on CKAN, [the most recent GitHub release](https://github.com/icedown/CactEye-2/releases/tag/1.2.2.12p) is marked as a pre-release, with a big warning that it is only for testing, so we won't be adding that to the CKAN repo. The most recent release we have is 1.3.0, marked as compatible with KSP 1.3.0 only.
