### ISSUE TITLE
i cant unninstal mods

### ISSUE THREAD

**Issue by smurlock** [KSP-CKAN/NetKAN#5913]
first i installed ckan, and i placed it on a folder, this folder was all of the ksp data pasted into this folder,
i installed lots of mods, and then i unninstalled the folder, reinstalled ckan into the steam ksp directory but when i opened ckan all of the previuos mods were in the installed section, i went to the ckan folder, opened dowlads and the mods were there, i uninstalled them all, but when i whent back i still could not delete them

**Comment by politas** [comment]
If you have effectively removed all mods by returning the GameData directory to a fresh install, simply delete the registry.json file in the CKAN directory and you can start afresh.
