### ISSUE TITLE
Feature Request: Override Max KSP version

### ISSUE THREAD

**Issue by mwerle** [KSP-CKAN/NetKAN#5937]
It would be great if, as a user, I could override a mod's compatibility for a KSP version and force it to install anyway.

**Comment by politas** [comment]
You can. There are two main ways. In the GUI, you can use the KSP Compatibility feature to make CKAN accept a wider range of KSP version compatibility, or you can use the CLI to specify a particular version of a mod, which will ignore compatibility, by using this syntax:

    ckan install AwesomeMod=v1.incompatible

**Comment by mwerle** [comment]
Ah cool, thanks :)
