### ISSUE TITLE
InterstellarFuelSwitch wants to overwrite InterstellarFuelSwitchCore's file...

### ISSUE THREAD

**Issue by Ninja2500** [KSP-CKAN/NetKAN#5939]
Packaging problem in the newest version of InterstellarFuelSwitch.

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

File           : GameData/InterstellarFuelSwitch/Localization/Parts/en-us.cfg
Installing Mod : InterstellarFuelSwitch 2.10.0
Owning Mod     : InterstellarFuelSwitch-Core
CKAN Version   : v1.22.3

I deleted the en-us.cfg file for debugging purposes, and there are actually two problematic files. 
./Fields/en-us.cfg and ./Parts/en-us.cfg.

**Comment by Olympic1** [comment]
Fixed in https://github.com/KSP-CKAN/NetKAN/commit/e417ebb72801b90655c56629f99e03d2cb9376f7

Refresh your ckan gui and try again
