### ISSUE TITLE
Bad metadata and incorrect values in Max KSP version column

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN#5945]
It was recently [pointed out on the forums](https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1223-mahia/&do=findComment&comment=3193139) that the "Max KSP version" column can be incorrect if the "latest" version of a mod has narrower compatibility than an earlier version. This was in response to the suggestion to use this column to determine whether it's safe to upgrade to the next version of KSP.

I started looking at a fix to display the actual highest version in that column and in the process found 70+ mods with bad metadata affecting this column. Some of these represent ticking time bombs, as once the next version after KSP 1.3.1 is out, an older version of a mod could be reactivated unintentionally (unless I'm misunderstanding something, which is quite possible). For example, consider `CraftImport` (data excerpted from a current `registry.json`):

```
		"CraftImport": {
			"module_version": {
				"0.8.10": {
					"ksp_version": "1.3.1",
					"ksp_version_max": null,
					"ksp_version_min": null,
				},
				"0.8.9": {
					"ksp_version": null,
					"ksp_version_max": "1.3.99",
					"ksp_version_min": "1.3.0",
				},
```

Currently the highest mod version compatible with 1.3.1 is 0.8.10, and for 1.3.0 it's 0.8.9, as it should be. But if a KSP 1.3.2 is released, then in the interim before a new release, 0.8.9 would start being installed for it, since that older version is marked as compatible up to 1.3.99 and 0.8.10 is not. While it would technically be possible to create a mod that validly has this pattern of versioning (say the oldest version has no plugins but a plugin is added later), it is probably either very rare or nonexistent in the real world.

That's one kind of problem; the other possibility is that the wrong mod version is being selected as "latest" for some mods. I think that's the case for `AlternisKerbolRekerjiggered`, which seems to have removed a "v" prefix from its version numbers and thus frozen its "latest" version in time:

```
		"AlternisKerbolRekerjiggered": {
			"module_version": {
				"v1.5.1": {
					"ksp_version": "1.0.5",
					"ksp_version_max": null,
					"ksp_version_min": null,
				},
				"2.1.1": {
					"ksp_version": "1.3.0",
					"ksp_version_max": null,
					"ksp_version_min": null,
				},
```

I will continue looking into a code fix to show the true highest version, but I thought these findings would be worth taking a break to report.

Full list follows, format: ModName: Max KSP version column value < Actual max KSP version according to metadata

```
BOSSContinued: 1.3.1 < 1.3.99
CareerManagerContinued: 1.3.1 < 1.3.99
CCTV: 1.3.1 < 1.3.99
ChampagneBottleRedux: 1.3.1 < 1.3.99
CivilianPopulation: 1.0.4 < Any version
CommunityTerrainTexturePack: 1.3.1 < Any version
CraftImport: 1.3.1 < 1.3.99
CrewQueueTwo: 1.3.1 < 1.3.98
DangerAlertsContinued: 1.3.1 < 1.3.99
DangItContinued: 1.3.1 < 1.3.99
EVAEnhancementsContinued: 1.3.1 < 1.3.99
EvaFuelCont: 1.3.1 < 1.3.99
EVAParachutes: 1.3.1 < 1.3.99
ExtensiveEngRptContinued: 1.3.1 < 1.3.99
FlagRotateCont: 1.3.1 < 1.3.99
FMRSContinued: 1.3.1 < 1.3.99
FTLDriveContinued: 1.3.1 < 1.3.99
FuseBoxContinued: 1.3.1 < 1.3.98
HullcamVDSContinued: 1.3.1 < 1.3.99
ImageViewerCont: 1.3.1 < 1.3.99
JSIPartUtilities: 1.0.99 < 1.3.1
KerbalAnimationSuiteCont: 1.3.1 < 1.3.99
KerbalLaunchFailure: 1.3.1 < 1.3.99
KerbalNRAP: 1.3.1 < 1.3.99
KerbalObjectInspectorCont: 1.3.1 < 1.3.99
kOS: 1.2.99 < 1.3.99
KRASH: 1.3.1 < 1.3.99
KSPCasherCont: 1.3.1 < 1.3.98
KVVContinued: 1.3.1 < 1.3.99
NavballDockAlignIndCE: 1.3.1 < 1.3.99
NEBULADecalsContinued: 1.3.1 < 1.3.99
OctosatContinued: 1.3.1 < 1.3.99
PartCommanderCont: 1.3.1 < 1.3.99
PartWizardContinued: 1.3.1 < 1.3.99
PersistentDynamicPodNames: 1.3.1 < 1.3.99
QuizTechAeroPackContinued: 1.3.1 < 1.3.99
SensiblePumpsCont: 1.3.1 < 1.3.99
SmartParts: 1.3.1 < 1.3.99
SmartStage: 1.3.1 < 1.3.1000
SSRSS-Clouds-HR: 1.3.1 < 1.3.3
SSRSS-Clouds-LR: 1.3.1 < 1.3.3
SSRSS-StockIncl: 1.3.1 < 1.3.3
StateFundingContinued: 1.3.1 < 1.3.99
SXTContinued: 1.3.1 < 1.3.99
TacSelfDestructContinued: 1.3.1 < 1.3.99
TankLockRedux: 1.3.1 < 1.3.99
TotalTime: 1.3.1 < 1.3.99
VaporVent: 1.3.1 < 1.3.99
WasdEditorCameraContinued: 1.3.1 < 1.3.99
10kmOmniEVA4RT: 1.2.2 < 1.3.0
AerojetKerbodyne: 0.25 < 1.1.2
AlternisKerbolRekerjiggered: 1.0.5 < 1.3.0
Canadarm: 1.1.2 < 1.1.3
CarcharothAeronautics: 1.0.5 < 1.1.3
ContractFilterContinued: 1.1.3 < 1.1.99
ExceptionDetector: 1.0.4 < 1.3.0
HotRockets: 0.25 < 1.0.4
KerbalRPNCalculator: 1.0.0 < 1.0.4
KerbalTubes: 1.0.5 < 1.3.0
KerbfleetPlanetPackTheKerbulusSystem: 1.1.3 < 1.3.0
KlockheedMartian-Gimbal: 1.0 < 1.0.5
MissionController2: 1.2.2 < 1.3.0
MoarMk1: 1.1.0 < 1.1.3
MrScienceMeistersNuclearWarfare: 1.0.4 < 1.0.5
newReactionWheels: 1.2.2 < 1.3.0
PhoenixIndustriesAres: 1.0.5 < 1.1.2
PhoenixIndustriesAscentVehicle: 1.0.5 < 1.1.2
Protractor: 1.0 < 1.0.2
REKT: 1.2.2 < 1.3.0
RosterManager: 1.1.0 < 1.3.0
SensibleTechTree: 1.2.1 < 1.2.2
SovietConversion: 1.2.0 < 1.3.0
SpaceDock: 1.2 < 1.2.0
StationScience: 1.1 < 1.1.2
VesselMoverContinued: 1.2.2 < 1.3.0
```

**Comment by politas** [comment]
Hoo boy! That's a lot more than I was expecting. The lost "v" issue happens often enough that we have a special entry for it:

    "x_netkan_force_v": true,

**Comment by HebaruSan** [comment]
Regarding long term vision, should the bot auto-generate an issue in this repo if it generates a new `.ckan` that puts a mod into this state (out-of-order max KSP versions)? Obviously there would be many implementation details to work out, but right now there are no guardrails to prevent more bad metadata.

**Comment by politas** [comment]
If you can get sane mod version GT/LT comparisons in the x_netkan_meta Perl code, that would be great! It would also be great if we could replace some of the fixed mappings to Default KSP version to drop to the highest valid version in the range. I should raise issues for these things.

**Comment by HebaruSan** [comment]
Closing as fixed by https://github.com/KSP-CKAN/CKAN-meta/pull/1305 and https://github.com/KSP-CKAN/CKAN-meta/pull/1304 . There are a few stragglers out there still, but the main part of the problem is resolved.
