### ISSUE TITLE
Kraken when trying to update HullcamVDS Continued

### ISSUE THREAD

**Issue by Locusi** [KSP-CKAN/NetKAN#5947]
Hi,
When I try to upgrade HullcamVDS Continued by linuxgurugamer from version 0.1.7.1 to 0.1.8 I get the following Kraken:

************** Tekst wyjątku **************
CKAN.PathErrorKraken: d:/Gry/Steam/SteamApps/common/Kerbal Space Program/GameData/HullCameraVDS/Parts/hc_kazzelblad is already absolute
   w CKAN.KSPPathUtils.ToAbsolute(String path, String root)
   w CKAN.ModuleInstaller.<>c__DisplayClass34_0.<AddParentDirectories>b__1(String dir)
   w System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   w System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   w System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   w System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   w CKAN.ModuleInstaller.AddParentDirectories(HashSet`1 directories)
   w CKAN.ModuleInstaller.Uninstall(String modName)
   w CKAN.ModuleInstaller.AddRemove(IEnumerable`1 add, IEnumerable`1 remove, Boolean enforceConsistency)
   w CKAN.ModuleInstaller.Upgrade(IEnumerable`1 modules, NetAsyncModulesDownloader netAsyncDownloader, Boolean enforceConsistency)
   w CKAN.Main.WasSuccessful(Action action)
   w CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   w System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   w System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

I hope it's enough information and that I posted it in the right place (it's my first time ;-) ).
Thanks for your awesome work on CKAN!
Luke

**Comment by politas** [comment]
Please re-attempt with [CKAN client 1.22.4](https://github.com/KSP-CKAN/CKAN/releases/tag/v1.22.4)

**Comment by Locusi** [comment]
It Works! Thank you!
