### ISSUE TITLE
Broken Sound Track Editor install from CKAN?

### ISSUE THREAD

**Issue by Locusi** [KSP-CKAN/NetKAN#5953]
Hi,
I know that it outdated mod, but it's still in library so I wanted to share that from CKAN it only unpacks files from GameData/SoundtrackEditor directory and there are 6 more directories to unpack outside of GameData. I don't know if CKAN can do that, nevertheless just wanted to let you know about the issue.
Kind Regards,
Luke

**Comment by politas** [comment]
I keep meaning to try out this mod, but I'd need to convert all the music I want to use to .ogg files

**Comment by politas** [comment]
Unfortunately, we just can't do it without rather radically changing [the spec](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md):

>install_to: The target location where the matched file or directory should be installed.
>- Valid values for this entry are GameData, Ships, Ships/SPH(v1.12), Ships/VAB(v1.12), Ships/@thumbs/VAB(v1.16), Ships/@thumbs/SPH(v1.16), Tutorial, Scenarios (v1.14) and GameRoot (which should be used sparingly, if at all).
>- A path to a given subfolder location can be specified only under GameData (v1.2); for example: GameData/MyMod/Plugins. The client must check this path and abort the install if any attempts to traverse up directories are found (eg: GameData/../Example).
>- Subfolder paths under a matched directory will be preserved, but directories will only be created when installing to GameData, Tutorial, or Scenarios.

**Comment by Locusi** [comment]
Sorry, I didn't read the specs, thanks for time taken to answer this.
Now I think I should contact the author and then maybe he can change directory locations so they meet your spec.
And if I may add - I think that if mod doesn't work installed from CKAN it should be removed from the list or at least marked as incomplete (or something). 
I hope this is good place to report "broken/incomplete" mods?
Should I close this issue?
Always thankful for your great job on CKAN!
Luke

**Comment by politas** [comment]
Agreed. Thanks for bringing it to our attention!
