### ISSUE TITLE
Provide Flags package for Lazarus

### ISSUE THREAD

**Issue by hakan42** [KSP-CKAN/NetKAN#596]
The Flags are part of each and every archive in the SpaceX addons and are therefore filtered out.

Provide a package that provides / installs the Lazarus Flag.

**Comment by politas** [comment]
To do this, I assume we pick one of the SpaceX mods to pull the Flags from, and then add the new mod as a Recommends to all the SpaceX files?

**Comment by Dazpoet** [comment]
That is indeed one way of solving it, I suggest the smallest possible mod since flags aren't really that big. The reason is wasn't done might be because of there being no pack small enough to warrant regrabbing it for a few flags.

**Comment by politas** [comment]
Ah, CKAN would force a re-download of the whole file?

**Comment by Dazpoet** [comment]
unfortunatly yes, this is also happening with e.g. the NearFuturePropulsionExtras where the entire thing is downloaded again to grab something like 8 .cfg files.

**Comment by politas** [comment]
Hmm. And since all the SpaceX mods are still at 0.90, they'll refuse to build.
Actually, it seems like the Flags directory is only present in the Launch Pack, so why don't we just take out the filter when they upgrade to 1.0?

**Comment by Dazpoet** [comment]
Taking it out of one pack (esspecially if it's a dependency) sounds like a splendid solution :)

**Comment by politas** [comment]
I assume they're all failing because they're only up to 0.90 .

**Comment by Dazpoet** [comment]
Probably it yes, while you're editing them would you please also change the conflict logic so they all conflict with SpaceX-LaunchPack rather than the other mods?

**Comment by politas** [comment]
Done.

**Comment by Dazpoet** [comment]
Fixed and as such I'm closing this :)
