### ISSUE TITLE
CKAN.ModuleNotFoundKraken on startup

### ISSUE THREAD

**Issue by Fumblesneeze** [KSP-CKAN/NetKAN#5963]
I've been having exceptions on startup since the recent update of ckan and still have it with 1.22.6:
(although I think the kind of exceptions changed over time)

Other symptoms are that only installed mods appear on the mod list.

Exception:
> CKAN.ModuleNotFoundKraken: Eine Ausnahme vom Typ "CKAN.ModuleNotFoundKraken" wurde ausgelöst.
>    bei CKAN.Registry.AllAvailable(String module)
>    bei CKAN.MainAllModVersions.set_SelectedModule(GUIMod value)
>    bei CKAN.Main.ModList_SelectedIndexChanged(Object sender, EventArgs e)
>    bei System.Windows.Forms.DataGridView.OnSelectionChanged(EventArgs e)
>    bei System.Windows.Forms.DataGridView.FlushSelectionChanged()
>    bei System.Windows.Forms.DataGridView.ClearSelection(Int32 columnIndexException, Int32 rowIndexException, Boolean selectExceptionElement)
>    bei System.Windows.Forms.DataGridView.SetAndSelectCurrentCellAddress(Int32 columnIndex, Int32 rowIndex, Boolean setAnchorCellAddress, Boolean validateCurrentCell, Boolean throughMouseClick, Boolean clearSelection, Boolean forceCurrentCellSelection)
>    bei System.Windows.Forms.DataGridView.MakeFirstDisplayedCellCurrentCell(Boolean includeNewRow)
>    bei System.Windows.Forms.DataGridView.OnRowCollectionChanged_PostNotification(Boolean recreateNewRow, Boolean allowSettingCurrentCell, CollectionChangeAction cca, DataGridViewRow dataGridViewRow, Int32 rowIndex)
>    bei System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged_PostNotification(CollectionChangeAction cca, Int32 rowIndex, Int32 rowCount, DataGridViewRow dataGridViewRow, Boolean changeIsDeletion, Boolean changeIsInsertion, Boolean recreateNewRow, Point newCurrentCell)
>    bei System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged(CollectionChangeEventArgs e, Int32 rowIndex, Int32 rowCount)
>    bei System.Windows.Forms.DataGridViewRowCollection.AddRange(DataGridViewRow[] dataGridViewRows)
>    bei CKAN.Main._UpdateFilters()
>    bei CKAN.Main._UpdateModsList(Boolean repo_updated)
>    bei CKAN.Main.CurrentInstanceUpdated()
>    bei CKAN.Main.OnLoad(EventArgs e)
>    bei System.Windows.Forms.Form.OnCreateControl()
>    bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
>    bei System.Windows.Forms.Control.CreateControl()
>    bei System.Windows.Forms.Control.WmShowWindow(Message& m)
>    bei System.Windows.Forms.Control.WndProc(Message& m)
>    bei System.Windows.Forms.Form.WmShowWindow(Message& m)
>    bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> == Loaded Assemblies ==
> mscorlib
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2115.0 built by: NET47REL1LAST.
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
> ----------------------------------------
> ckan
>     Assembly-Version: 1.22.0.0.
>     Win32-Version: 1.22.6.
>     CodeBase: file:///C:/Users/Manuel/Downloads/ckan.exe.
> ----------------------------------------
> System.Core
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2116.0 built by: NET47REL1LAST.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
> ----------------------------------------
> System
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2110.0 built by: NET47REL1LAST.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
> ----------------------------------------
> System.Configuration
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2046.0 built by: NET47REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
> ----------------------------------------
> System.Xml
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2102.0 built by: NET47REL1LAST.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
> ----------------------------------------
> System.Windows.Forms
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2110.0 built by: NET47REL1LAST.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
> ----------------------------------------
> System.Drawing
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2046.0 built by: NET47REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
> ----------------------------------------
> System.Transactions
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2046.0 built by: NET47REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll.
> ----------------------------------------
> System.Windows.Forms.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2046.0 built by: NET47REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
> ----------------------------------------
> mscorlib.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2046.0 built by: NET47REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
> ----------------------------------------
> Microsoft.GeneratedCode
>     Assembly-Version: 1.0.0.0.
>     Win32-Version: 4.7.2102.0 built by: NET47REL1LAST.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
> ----------------------------------------
> System.Numerics
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2046.0 built by: NET47REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll.
> ----------------------------------------
> System.Runtime.Serialization
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2112.0 built by: NET47REL1LAST.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll.
> ----------------------------------------
> System.Data
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2102.0 built by: NET47REL1LAST.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll.
> ----------------------------------------
> Anonymously Hosted DynamicMethods Assembly
>     Assembly-Version: 0.0.0.0.
>     Win32-Version: 4.7.2115.0 built by: NET47REL1LAST.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll.
> ----------------------------------------
> Microsoft.CSharp
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2046.0.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll.
> ----------------------------------------
> System.Dynamic
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2046.0.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll.
> ----------------------------------------
> Microsoft.CSharp.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2046.0.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp.resources/v4.0_4.0.0.0_de_b03f5f7f11d50a3a/Microsoft.CSharp.resources.dll.
> ----------------------------------------

**Comment by politas** [comment]
If you're only seeing installed mods, is it because you have selected the "Installed" filter?

**Comment by Fumblesneeze** [comment]
that would not be a bug report then, no. 

![image](https://user-images.githubusercontent.com/25569137/31709960-e8b14c60-b3f3-11e7-9b87-3ff4c6c0d2a7.png)

**Comment by politas** [comment]
Ok, so it looks like a Refresh has failed and you have nothing in your Available Mods" section in your registry.json. If you post your registry.json, I can try and fix it for you, but I think a [Clean & Reinstall](https://github.com/KSP-CKAN/CKAN/wiki/Clean-and-reinstall-process) would be the best bet for you.
