### ISSUE TITLE
Infernal Robotics missing parts

### ISSUE THREAD

**Issue by dukeharold** [KSP-CKAN/NetKAN#5999]
I loaded Infernal Robotics from CKAN and I the tab in the VAB but no parts, after looking in the GameData folder i saw the parts folder in MagicSmokeIndustries was empty. I had this installed previously and all parts were there then I removed all my mods manually and changed to running CKAN after installing Mods with it Infernal Robotics has not had parts since.

**Comment by politas** [comment]
You will need to install the "InfernalRobotics-LegacyParts" to get the parts. Infernal Robotics in in the process of migrating to a new set of parts, I gather, and the maintenance releases are going out without any parts.

**Comment by HebaruSan** [comment]
See also #6131 and #6134.
