### ISSUE TITLE
When I click on the installation check, it gets ticked, but no changeset tab appears and the mod does not install, Windows 10, KSP 1.3.1, CKAN 1.22.6

### ISSUE THREAD

**Issue by barty12** [KSP-CKAN/NetKAN#6032]
![image](https://user-images.githubusercontent.com/33497299/32570789-2962840c-c4bd-11e7-927c-5525cc4ead47.png)

all the ones with a dash in version installed aren't installing and I don't know why, or how to fix it, the changeset tab just doesn't appear no matter what I do

**Comment by barty12** [comment]
![image](https://user-images.githubusercontent.com/33497299/32570789-2962840c-c4bd-11e7-927c-5525cc4ead47.png)

**Comment by barty12** [comment]
all the ones with a dash in version installed aren't installing and I don't know why, or how to fix it, the changeset tab just doesn't appear no matter what I do

**Comment by HebaruSan** [comment]
Can you try changing the filter to Compatible? Maybe it's getting confused by the versions that are in the cache.

![image](https://user-images.githubusercontent.com/1559108/32577073-5fcfc938-c49e-11e7-9382-5d0f06b87e52.png)

**Comment by politas** [comment]
The filter you have selected there is "Cached". Are there other installed mods that have dropped out of your cache that may be conflicting? CKAN will make the changeset tab unavailable and will grey out the "apply changes" button only when you have selected a set of mods that will lead to inter-mod incompatibilities. The most likely mod causing issues in what you have there is Stock Visual Enhancements, which has undergone several changes to dependency and provision scheme. I would advise uninstalling all of the "Visual Enhancements" type mods on your system to see if that makes the "apply changes" button available again.

**Comment by yasha1231** [comment]
anyway if it is compatble it wont download it

**Comment by Bal0ny** [comment]
i am having this same issue and i am unsure how to fix it

**Comment by Bal0ny** [comment]
i am trying to download/uninstall mods but the changeset tab wont apear
