### ISSUE TITLE
Collision between two mods with the same Name, but different Identifiers.

### ISSUE THREAD

**Issue by FreyjaKA** [KSP-CKAN/NetKAN#6040]
Two mods have the same name "ESLD Jump Beacons", however they have different Identifiers, namely "ESLDCore", and "ESLDJumpBeacons".

This causes the second one to not show up in the GUI. This is particularly unfortunate as the first one is only for KSP 1.0.4, while the second is for KSP 1.3.0

**Comment by HebaruSan** [comment]
They do have the same name, but I'm not seeing them hide each other:

![image](https://user-images.githubusercontent.com/1559108/32955286-296b3c18-cb7b-11e7-8ec0-9145878c3a04.png)

How exactly are you testing this?

**Comment by politas** [comment]
Well, you're only seeing one, because the other is hidden. This is a common problem when a core mod is drawing its name from the GitHub/Spacedock transformer. We need to set a different name for the Core mod.
