### ISSUE TITLE
All builds are failing

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#6051]
Just started today, all build fail with a missing perl module

**Comment by HebaruSan** [comment]
Related to KSP-CKAN/xKAN-meta_testing#29. The module was added to the list that's supposed to be installed, but the interpreter isn't finding it. We'll need @techman83's input to figure out what's going on.

**Comment by techman83** [comment]
I feel I need to add the ci stuff into the build process, that way it can build itself! Basically it just needs to run `docker build -t ckan-ci .` on the jenkins host at it'll be sorted.

**Comment by techman83** [comment]
Fixed
