### ISSUE TITLE
Merge Nehemiah's mods?

### ISSUE THREAD

**Issue by mwerle** [KSP-CKAN/NetKAN#6057]
Original issue #5557 

After more thinking and also requesting information from the users, as well as checking the download stats, it seems that having split these mods apart is far more bother than worth.

Download Info:
> KEES_0.3_beta_2.zip (1.70 MiB) - downloaded 68 times. Last updated on 2017-07-27
> KeminiResearch_0.2_beta_2.zip (0.87 MiB) - downloaded 43 times. Last updated on 2017-07-27
> KerbalLifeScience_0.2_beta_2.zip (3.90 MiB) - downloaded 43 times. Last updated on 2017-07-27
> NehemiahIncSciencePack_0.2_beta_2.zip (14.03 MiB) - downloaded 4,434 times. Last updated on 2017-07-27
> OrbitalMaterialScience_0.7_beta_2.zip (11.18 MiB) - downloaded 50 times. Last updated on 2017-07-27

As such, I'm wondering whether it's possible to replace the various mods with one new one "Nehemiah Engineering Orbital Science" (NEOS).  I would remove the version files from all the sub-directories.

Thoughts?

If we go ahead with this change, we'd need to:
* Mark the old mods as deprecated or replaced-by or something.
* Mark the new mod as conflicting with the old mods

I'm presuming that's possible?

**Comment by HebaruSan** [comment]
This was done in #6071.
