### ISSUE TITLE
Latest update missing.

### ISSUE THREAD

**Issue by jharri74** [KSP-CKAN/NetKAN#6111]
The latest version of my mod Kerbalized SpaceX isn't showing up on CKAN. The latest version I was able to install was 1.26. The recent update brought the mod to 1.3. I checked the meta files and my 1.3 has one but I'm not able to find it in the CKAN system. This is causing the old version to outperform the new version in downloads. http://farm5.staticflickr.com/4737/39311600172_acd8eaa9fe_b.jpg
http://farm5.staticflickr.com/4591/25472261308_7f81112086_b.jpg

**Comment by HebaruSan** [comment]
Aha, it thinks that's an older version because 3 is less than 26. Would you be opposed to relabeling that as 1.30?

![image](https://user-images.githubusercontent.com/1559108/34397122-17b99ca2-eb6b-11e7-9825-5c2a935c56f0.png)

**Comment by techman83** [comment]
There is also the epoch for cases like this, @jharri74 KSP-CKAN/CKAN-meta#1314 will need to be set in the NetKAN

**Comment by jharri74** [comment]
Ah, I see what is going on now. Yeah, ill change the version to 1.30

**Comment by HebaruSan** [comment]
KSP-CKAN/NetKAN#6113 switched the NetKAN to SpaceDock.

**Comment by jharri74** [comment]
Yep just seen that. Thanks for the help!
