### ISSUE TITLE
mods installation problem

### ISSUE THREAD

**Issue by yannsousseau** [KSP-CKAN/NetKAN#6124]
Dear,

I install RSS mod with CKAN by following strongly all steps outlined, and when I start KSP it works as if I hadn't installed RSS.

Thank you for your help

**Comment by HebaruSan** [comment]
Hi! Thanks for reporting this problem. To help, we're going to need some information about your setup:

1. Operating system
2. KSP version
3. CKAN version
4. Do you have multiple copies of KSP installed?
5. Are the RSS files installed to GameData?
6. When you say "all steps outlined," were you following an installation guide? If so, which one?

**Comment by yannsousseau** [comment]
I had indeed two copies of KSP so I removed one of them. Since then RSS works very well.
Thank you for your help.

**Comment by HebaruSan** [comment]
Excellent! Glad you figured it out.
