### ISSUE TITLE
Custom Asteroids instalation via ckan don't work

### ISSUE THREAD

**Issue by miki-g** [KSP-CKAN/NetKAN#6125]
1 - check [Custom Asteroids](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/CustomAsteroids.netkan) from @Starstrider42 
2 - chose one from 4 available mods
3 - continue

... no action, instalation don't start,
Custom Asteroids stay checked as instaled (or as selected for instalation)
Apply changes button stay disabled

/edit ... ehm ...
when i chose extrasolar in second screenshot, Apply changes button is enabled
all other choices - Apply changes disabled

**Comment by HebaruSan** [comment]
Hi! Thanks for reporting this problem. To help, we're going to need some information about your setup:

1. Operating system
2. KSP version
3. CKAN version
4. A screenshot of your CKAN when the problem occurs

**Comment by miki-g** [comment]
M$ Win 10.0.15063
KSP 1.3.1.1891
CKAN 1.22.6

![image](https://user-images.githubusercontent.com/11336623/34502972-6ad57d7a-f016-11e7-9ed0-2def99b84a9a.png)

![image](https://user-images.githubusercontent.com/11336623/34502990-7c5a65a6-f016-11e7-9dc3-cf959b249fb9.png)

![image](https://user-images.githubusercontent.com/11336623/34503002-8e886da4-f016-11e7-9c99-27a1b42a2ea5.png)

**Comment by HebaruSan** [comment]
Thanks!
Do you have any other mods already installed? It's possible there's a conflict. When I try this with a clean install, the Apply changes button is enabled.

**Comment by miki-g** [comment]
hmmm ... some mods :)
... sorry, i dont try with clean instal before posting issue

[ksp-131-1891-20180103.ckan.txt](https://github.com/KSP-CKAN/NetKAN/files/1599103/ksp-131-1891-20180103.ckan.txt)

**Comment by miki-g** [comment]
maybe close this while working on clean install, or we want to find possible mods conflict?
I'm going to sleep now, but tomorrow I try to delete the modes one by one and try to find out where the conflict is ... ok?

**Comment by Starstrider42** [comment]
@miki-g, the three default configs are incompatible with RSS (or any mod that gets rid of the stock solar system). Sorry about that.

**Comment by HebaruSan** [comment]
Aha, those configs **are** marked as conflicting with RealSolarSystem. _That's_ why the Apply button is disabled! It just doesn't tell you that; however, a code change is under way to raise a popup in this scenario at KSP-CKAN/CKAN#2237.

Closing this as resolved. @miki-g, it sounds like your options are to uninstall RealSolarSystem or go without the use of CustomAsteroids, since the mods don't work with one another. Please let us know if you observe any other odd behavior.
