### ISSUE TITLE
Error when installing KWRocketryRebalanced 3.2.3

### ISSUE THREAD

**Issue by lolotux** [KSP-CKAN/NetKAN#6138]
Background
----------

File           : GameData/KWRocketry/Flags/KWFlag01.png
Installing Mod : KWRocketryRebalanced 3.2.3
Owning Mod     : KWRocketryRedux
CKAN Version   : v1.22.6

Problem
-------

Just wanted to install KWRocketryRebalanced here is the error !
 ```
 * KW Rocketry Rebalanced 3.2.3(cached)


Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/NetKAN/issues/new
```

**Screenshots:**

No CKAN error : 
$ mono ckan.exe

PS
--

Distributor ID: Debian
Description:    Debian GNU/Linux 9.3 (stretch)
Release:        9.3
Codename:       stretch
Linux debian 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux

**Comment by HebaruSan** [comment]
@linuxgurugamer, are these the same mod? They have the same home page and both names appear on the SpaceDock page.

**Comment by linuxgurugamer** [comment]
Yes and no, the Rebalanced did changes that would potentially break existing saves, so I created a new mod and stopped supporting the old one.

This sounds like he has the old KW installed by hand and is trying to install the new one, I put in several "Conflicts" statements in the rebalanced Netkan

**Comment by linuxgurugamer** [comment]
The player needs to do two things to be sure to clean this up:
1.  If installed via CKAN, remove the old KW Rocketry 
2.  Manually delete the KW Rocketry directory

Then he should be able to install without any problem.

**Comment by HebaruSan** [comment]
They don't actually conflict currently:

```
$ ckan install KWRocketryRedux KWRocketryRebalanced
1) KWRocketryRedux-GraduatedPwr (KW Rocketry Redux - Graduated Power Response Configs)
2) KWRocketryRedux-InstantPwr (KW Rocketry Redux - Instant Power Response Configs)
Enter a number between 1 and 2 (To cancel press "c" or "n".): 
2
About to install...

 * KW Rocketry Redux 3.1.4 (cached)
 * KW Rocketry Rebalanced 3.2.3 (cached)
 * KW Rocketry Redux - Instant Power Response Configs 3.1.4 (cached)
 * Module Manager 3.0.1 (cached)
 * Simple Adjustable Fairings - KW Rocketry Pack v1.0.1 (cached)
 * Simple Adjustable Fairings - Plugin v1.0.1 (cached)
 * The Janitor's Closet 0.3.2 (cached)
 * Filter Extensions - Plugin 3.0.4 (cached)
 * Filter Extensions - Default Configuration 3.0.4 (cached)
 * KSP AVC 1.1.6.2 (cached)

Continue? [Y/n] 
```

We may need to have another look at those `conflicts` relationships.
