### ISSUE TITLE
les mod crash

### ISSUE THREAD

**Issue by fighter4life** [KSP-CKAN/NetKAN#6148]
Background
----------

**CKAN Version:** 
1.22.6

**KSP Version:** 
1.2.2

**Operating System:** 
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

**Affected mods and mod versions:**
PEBKACIndustriesLaunchEscapeSystem

Problem
-------

**What steps did you take in CKAN?**
tried to install it in a pack of mods..everything crashed, started over one by one (reaaalllyyyyy annoying when you have over 70 of them) and finally came to launch escape system. i cleaned the install once more and installed launch escape system by itself as a control. it also crashed on load.

**What did you expect to happen?**
the game to load...

**What happened instead?**
the game crashed....

**Screenshots:**

**CKAN error codes (if applicable):** 

SIDE NOTE this happened on two different pc's and ive been fighting to s=figure this out for months. id really like it if you guys could figure it out or just take the mod off of ckan so nobody else has to fight it like i did. i went without my rocket scientist fix for almost two months.

**Comment by HebaruSan** [comment]
Thanks for bringing this to our attention!

It looks like the version compatibility metadata on this mod is messed up. For example, the SpaceDock page specifically says that the 2017.11.21 version is for 1.3.1 only, but we have it compatible with 1.1.3 through 1.3.1. That means CKAN was probably installing that version for you on 1.2.2.

I think I see the problem, should be an easy fix...

**Comment by HebaruSan** [comment]
OK, the metadata for this mod should be cleaned up now. If you click Refresh to update your registry, it should now only install versions that are compatible with your game. Please let us know if you still have a crash after doing that.
