### ISSUE TITLE
Version mismatches between NetKAN and forum threads

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN#6154]
#6148 gave me nightmares, so I wrote [a script to check versions hard-coded in NetKAN against their forum threads](https://github.com/HebaruSan/KSP_Tools/blob/master/ckan_find_bad_versions); output below. Some of these are false positives (ScottManleyHeadPack is 1.3.1 compatible but the title just isn't updated), but others probably cause CKAN to install incompatible mods.

| Netkan | ksp_version | Forum thread | Links |
| --- | --- | --- | ---- |
| df95e48ca0e1108e66b20b988278ff654cb6b48f MechJeb2.netkan | 1.3 | 1.3.1 | [netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/MechJeb2.netkan) [forum](http://forum.kerbalspaceprogram.com/index.php?/topic/154834-*) |
| SDHI-StrobeOMatic.netkan | 1.3.0 | 1.3 | [netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/SDHI-StrobeOMatic.netkan) [forum](http://forum.kerbalspaceprogram.com/index.php?/topic/137804-11-sdhi-strobe-o-matic-warning-rotator-lights-v10-23-april-2016/) |
| SDHI-ServiceModuleSystem.netkan | 1.3.0 | 1.3 | [netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/SDHI-ServiceModuleSystem.netkan) [forum](http://forum.kerbalspaceprogram.com/index.php?/topic/48073-121-sdhi-service-module-system-v321-20-november-2016/) |
| NewHorizons.netkan | 1.3.0 | 1.3 | [netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/NewHorizons.netkan) [forum](http://forum.kerbalspaceprogram.com/index.php?/topic/102776-nh/) |
| LaunchPadLamp.netkan | 1.3.0 | 1.3 | [netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/LaunchPadLamp.netkan) [forum](https://forum.kerbalspaceprogram.com/index.php?/topic/164677-13-launch-pad-lamp/) |
| KerbalStats.netkan | 1.3.0 | 1.3 | [netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/KerbalStats.netkan) [forum](http://forum.kerbalspaceprogram.com/threads/99018) |
| RoverWheelSounds.netkan | 1.2.0 | 1.3 | [netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/RoverWheelSounds.netkan) [forum](http://forum.kerbalspaceprogram.com/index.php?/topic/50431-RoverWheelSounds) |
| AmazingCurveEditor.netkan | 1.0 | 1.2 | [netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/AmazingCurveEditor.netkan) [forum](http://forum.kerbalspaceprogram.com/threads/124708) |
| KSPLogiRGB.netkan | 1.1.0 | 1.1 | [netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/KSPLogiRGB.netkan) [forum](http://forum.kerbalspaceprogram.com/index.php?/topic/137859-11-ksp-logitech-rgb-control-v101-2016-22-04/) |
| DynamicTextureLoader.netkan | 1.0.5 | 1.1 | [netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/DynamicTextureLoader.netkan) [forum](http://forum.kerbalspaceprogram.com/index.php?/topic/128660-1051-0-dec-25-2015-dynamic-texture-loader/) |
| KlockheedMartian-Gimbal.netkan | 1.0 | 1.1 | [netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/KlockheedMartian-Gimbal.netkan) [forum](http://forum.kerbalspaceprogram.com/threads/55985) |
| KSCSwitcher.netkan | 1.2 | 1.0.5 | [netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/KSCSwitcher.netkan) [forum](http://forum.kerbalspaceprogram.com/threads/117893) |
| AeroGUI.netkan | 1.0 | 1.0.5 | [netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/AeroGUI.netkan) [forum](http://forum.kerbalspaceprogram.com/threads/117141) |
| ScienceContainers.netkan | 0.90 | 1.0.5 | [netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/ScienceContainers.netkan) [forum](http://forum.kerbalspaceprogram.com/threads/90678) |
| ActsEW.netkan | 1.0 | 1.0.2 | [netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/ActsEW.netkan) [forum](http://forum.kerbalspaceprogram.com/threads/100932) |
| ActiveTextureManagement-x64-Basic.netkan | 0.90 | 1.0 | [netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/ActiveTextureManagement-x64-Basic.netkan) [forum](http://forum.kerbalspaceprogram.com/threads/59005) |
| ActiveTextureManagement-x64-Aggressive.netkan | 0.90 | 1.0 | [netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/ActiveTextureManagement-x64-Aggressive.netkan) [forum](http://forum.kerbalspaceprogram.com/threads/59005) |
| MapResourceOverlay.netkan | 0.90 | 0.24.2 | [netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/MapResourceOverlay.netkan) [forum](http://forum.kerbalspaceprogram.com/threads/92393) |
| CustomDesignSpacesuits-Steampunk.netkan | 0.90 | 0.23.5 | [netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/CustomDesignSpacesuits-Steampunk.netkan) [forum](http://forum.kerbalspaceprogram.com/threads/72115) |

Resolved:

| Netkan | ksp_version | Forum thread | Links |
| --- | --- | --- | ---- |
| ~~SigmaBinary-DunaIke.netkan~~ | ~~1.3~~ | ~~1.3.1~~ | ~~[netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/SigmaBinary-DunaIke.netkan) [forum](http://forum.kerbalspaceprogram.com/index.php?/topic/115114-sb/)~~ |
| #6159 ~~Taerobee.netkan~~ | ~~1.2.2~~ | ~~1.3.1~~ | ~~[netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/Taerobee.netkan) [forum](http://forum.kerbalspaceprogram.com/index.php?/topic/119858-*)~~ |
| #6157 ~~Kethane.netkan~~ | ~~1.2.2~~ | ~~1.3.1~~ | ~~[netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/Kethane.netkan) [forum](http://forum.kerbalspaceprogram.com/index.php?/topic/119480-105-kethane-plugin-and-parts-094-new-maintainer/)~~ |
| 3c66d7e9cfa76912b142b77a1bad314367b3279e ~~ForScienceContinued.netkan~~ | ~~1.0.5~~ | ~~1.3.0~~ | ~~[netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/ForScienceContinued.netkan) [forum](http://forum.kerbalspaceprogram.com/index.php?/topic/95531-*)~~ |
| #6164 ~~KerbalLaunchVehicles.netkan~~ | ~~1.3.0~~ | ~~1.3~~ | ~~[netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/KerbalLaunchVehicles.netkan) [forum](https://forum.kerbalspaceprogram.com/index.php?/topic/164440-13-kerbal-launch-vehicles/)~~ |
| #6162 ~~RCSLandAid.netkan~~ | ~~1.2~~ | ~~1.3~~ | ~~[netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/RCSLandAid.netkan) [forum](http://forum.kerbalspaceprogram.com/threads/85838)~~ |
| #6158 e05b38e98903d7d36d27ddb09f510348cd631131 ~~KittopiaTech.netkan~~ | ~~1.2~~ | ~~1.3~~ | ~~[netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/KittopiaTech.netkan) [forum](https://forum.kerbalspaceprogram.com/index.php?/topic/140581-kittopia/)~~ |
| #6160 ~~KerbalWind.netkan~~ | ~~1.1~~ | ~~1.3~~ | ~~[netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/KerbalWind.netkan) [forum](http://forum.kerbalspaceprogram.com/threads/107989)~~ |
| #6182 ~~EngineIgnitor.netkan~~ | ~~1.2.1~~ | ~~1.2~~ | ~~[netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/EngineIgnitor.netkan) [forum](http://forum.kerbalspaceprogram.com/index.php?/topic/150673-12-engine-ignitor-continued-23-oct-2016/)~~ |
| #6161 ~~UnchartedLands.netkan~~ | ~~1.3.0~~ | ~~1.3.1~~ | ~~[netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/UnchartedLands.netkan) [forum](http://forum.kerbalspaceprogram.com/index.php?/topic/120111-ul/)~~ |
| ~~RealHeat.netkan~~ | ~~1.2.2~~ | ~~1.1.3~~ | ~~[netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/RealHeat.netkan) [forum](http://forum.kerbalspaceprogram.com/threads/127769)~~ |
| ~~nofuel.netkan~~ | ~~1.0.5~~ | ~~1.05~~ | ~~[netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/nofuel.netkan) [forum](http://forum.kerbalspaceprogram.com/index.php?/topic/130365-105-nofuel-all-tanks-defueled)~~ |
| ffaf89b5440d918c04591367718dc113e6c18688 ~~Snacks.netkan~~ | ~~1.3~~ | ~~1.0.5~~ | ~~[netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/Snacks.netkan) [forum](http://forum.kerbalspaceprogram.com/index.php?/topic/81929-105-snacks-kerbal-simplified-life-support)~~ |
| #6163 ~~KerbCam-Continued.netkan~~ | ~~1.1~~ | ~~0.23.5~~ | ~~[netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/KerbCam-Continued.netkan) [forum](http://forum.kerbalspaceprogram.com/index.php?/topic/22781-0235-kerbcam-v013-camera-pathing-tool-for-videos/&do=findComment&comment=2571620)~~ |
| ~~ScottManleyHeadPack.netkan~~ | ~~1.3.1~~ | ~~1.0.4~~ | ~~[netkan](https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/ScottManleyHeadPack.netkan) [forum](https://forum.kerbalspaceprogram.com/index.php?/topic/116374-104-scott-manley-head-pack/)~~ |

**Comment by HebaruSan** [comment]
I think I've taken care of the high risk ones. Other findings to follow...

KSCSwitcher essentially doesn't have a current forum page. Regex transferred it to the RealismOverhaul team, and they have a GitHub repo for it with a release for 1.2.2, but it's not listed on the RealismOverhaul thread (or included in that download). So the metadata still points to Regex's very old forum thread.

RoverWheelSounds's thread title says its works with KSP 1.3.X, but the actual 2.3 release says KSP 1.2. Then some commenters, but not the author, report that it does work in 1.3.1. I don't feel completely comfortable updating it on that basis.

**Comment by linuxgurugamer** [comment]
Depreciate the EngineIgnitor, I've adopted it and it's out under a new name, EngineIgnitorReignited

**Comment by HebaruSan** [comment]
Thanks, done.

**Comment by HebaruSan** [comment]
I think this is as fixed as it's going to get. I have looked into a few more, but they either are fine as-is or have no clear way to resolve the issues. Closing.
