### ISSUE TITLE
ckan download issue

### ISSUE THREAD

**Issue by lederin77** [KSP-CKAN/NetKAN#6167]
Background
----------

**CKAN Version:** 

**KSP Version:** 

**Operating System:** 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

**Affected mods and mod versions:**

Problem
-------

**What steps did you take in CKAN?**

**What did you expect to happen?**

**What happened instead?**

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
Please type something when submitting an issue.
