### ISSUE TITLE
Spacedock files unable to download via CKAN

### ISSUE THREAD

**Issue by f2ecebce** [KSP-CKAN/NetKAN#6168]
Background
----------

**CKAN Version:** 
1.24.0-PRE

**KSP Version:** 
1.3.1

**Operating System:** 
Win 10 Fall Creators Edition

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Yes

**Affected mods and mod versions:**
All Downloads pulling from Spacedock are impacted.  

Problem
-------
This is not a CKAN issue.  Spacedock lost its certs and is flagged by my AV and Browser as not safe. Any downloads from Github work fine.

**What steps did you take in CKAN?**
Tried to use CKAN as normal.  Had to get a some additional files from Spacedock for a mod and encountered the problems there. 

**What did you expect to happen?**
to work

**What happened instead?**
did not work

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by f2ecebce** [comment]
Here is an error code
Failed to download "https://spacedock.info/mod/144/AmpYear/download/V1.5.1.0" - error: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

**Comment by Olympic1** [comment]
This is an issue on SpaceDock, they are aware of this issue and should be fixed soon.

**Comment by HebaruSan** [comment]
(KSP-CKAN/CKAN#2249 was the first one this time.)
