### ISSUE TITLE
Error with SSL/TLS. Help.

### ISSUE THREAD

**Issue by TheDanMan2** [KSP-CKAN/NetKAN#6169]
How to solve this problem? 
![image](https://user-images.githubusercontent.com/35430552/34919162-f32fe1da-f96f-11e7-92f4-e10b87810589.png)

Help
Не удалось установить доверительные отношения для защищенного канала SSL/TLS.
Could not establish trust relationship for the secure channel SSL/TLS.

**Comment by HebaruSan** [comment]
See #6168, KSP-CKAN/CKAN#2249, KSP-CKAN/CKAN#2250.
