### ISSUE TITLE
CKAN can't read target file when I hit "Launch KSP". 

### ISSUE THREAD

**Issue by yuryhater** [KSP-CKAN/NetKAN#6171]
Background
----------

**CKAN Version:** 
1.22.6

**KSP Version:** 
1.3.1.1891

**Operating System:** 
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Only trashed folder with SVT, problem started after its download

**Affected mods and mod versions:**
many many mods, but they worked as they should

Problem
-------

No reasons for this, only downloaded Stock Visual Terrain. Now it completely removed from CKAN and folder. Restarts do not help, as the refreshes. WTF?

**What steps did you take in CKAN?**

tried to launch KSP

**What did you expect to happen?**
Launching of KSP

**What happened instead?**
Program cant't search file

**Screenshots:**

![image](https://user-images.githubusercontent.com/35458026/34946983-d058e01c-fa19-11e7-9f38-75dd42a17a7b.png)

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
What do your command line settings look like in this window?

![image](https://user-images.githubusercontent.com/1559108/34921217-166a7d34-f977-11e7-98db-25199a955e02.png)

![image](https://user-images.githubusercontent.com/1559108/34921219-1d44a166-f977-11e7-899c-1387436702d9.png)

**Comment by yuryhater** [comment]
![image](https://user-images.githubusercontent.com/35458026/34987479-5a2425ba-facc-11e7-9cad-093e5593621c.png)
No, like dat. Problem is here only?

**Comment by yuryhater** [comment]
Thank you man! You are the best!
![image](https://user-images.githubusercontent.com/35458026/34987618-d4e9f978-facc-11e7-8d8a-9d9e9689d20a.png)
