### ISSUE TITLE
Can't download 403 errors everytime.

### ISSUE THREAD

**Issue by w1r3dh4ck3r** [KSP-CKAN/NetKAN#6191]
Background
----------

**CKAN Version:** 

**KSP Version:** 

**Operating System:** 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

**Affected mods and mod versions:**

Problem
-------

**What steps did you take in CKAN?**

**What did you expect to happen?**

**What happened instead?**

I can't download the bigger mods, github fucks me over on my slow connection, I wanted to know what are those numbers and letters that are added in front of the zip file downloaded so I can download the mods manually.

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
Thanks, we know about this already, see KSP-CKAN/CKAN#2210 and others. GitHub throttles their downloads and we are discussing how to deal with it.

The file name prefix in the cache is the first 8 characters of the SHA1 of the download URL interpreted in hexadecimal:

https://github.com/KSP-CKAN/CKAN/blob/26ff29b007c8a1c6bbfe774007023f567bb2c0ca/Core/Net/NetFileCache.cs#L323-L331
