### ISSUE TITLE
new Stockalike Station Parts Redux

### ISSUE THREAD

**Issue by yalov** [KSP-CKAN/NetKAN#6211]
https://forum.kerbalspaceprogram.com/index.php?/topic/170211-131-stockalike-station-parts-redux-january-28th

> @Nertea is there backwards compatibility with the old station expansion pack?

> There is no overlap at all. If you have the old pack installed, you can just add this one on - don't delete the old one, there's no overlap.

**Comment by HebaruSan** [comment]
Thanks for letting us know!
