### ISSUE TITLE
Apply Changes button not enabling when selecting a mod to install

### ISSUE THREAD

**Issue by TheKerman21** [KSP-CKAN/NetKAN#6221]
Background
----------

**CKAN Version:** 
My CKAN verion is 1.22.6

**KSP Version:** 
My KSP version is 1.3.1

**Operating System:** 
OS is Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

**Affected mods and mod versions:**
None

Problem
-------

**What steps did you take in CKAN?**
I click on the box on the mod I wanted to install.

**What did you expect to happen?**
I expected the Apply Changes button to light up.

**What happened instead?**
Nothing happened, only the box got checked.

**Screenshots:**

https://docs.google.com/drawings/d/1oHCfk4l1mF9p2EpccYUGqJSxccCnV3pjKOrk47opS-w/edit
The link has the pic on a google drawing.

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
Which mods do you currently have installed?

**Comment by HebaruSan** [comment]
Can't investigate without follow-up questions, closing.
