### ISSUE TITLE
JDLiquidFuelCell not listed as conflict with Ballistanks

### ISSUE THREAD

**Issue by Khormin** [KSP-CKAN/NetKAN#6224]
Background
----------

**CKAN Version:** 
v1.24.0-PRE

**KSP Version:** 
1.3.1

**Operating System:** 
W7.64

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

**Affected mods and mod versions:**
JDLiquidFuelCell
Ballistanks

Problem
-------

**What steps did you take in CKAN?**
Loaded Ballistanks.
Later, tried to load Liquid Fuel Cell.

**What did you expect to happen?**
Load mod

**What happened instead?**

**CKAN error codes (if applicable):** 

```
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.

File           : GameData/JatwaaDemolitionsCo/Resources.cfg
Installing Mod : JDLiquidFuelCell 1
Owning Mod     : Ballistanks
CKAN Version   : v1.24.0-PRE
```

**Comment by HebaruSan** [comment]
Confirmed that they both have that file, and it's not even the same between the two mods.
Adding a conflict is probably the only way to fix this, unless the author feels like fixing it.

**Comment by HebaruSan** [comment]
Looks like they also both conflict with JDBallisback, which also installs the same file.
