### ISSUE TITLE
All the "Panzer Labs" mods conflict with each other, as they all try to load the same files.

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/NetKAN#6236]
Background
----------

**Affected mods and mod versions:**

These all reference module 471 on SpaceDock:

- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/PL-KSat.netkan
- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/PL-Common.netkan
- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/PanzerLabsAeroSpaceKSatSeries.netkan

Problem
-------

The PL-* modules were added first, then #6197 created a duplicate.

**Comment by HebaruSan** [comment]
Thanks for noting this.

@politas, how should we fix this? Freezing PanzerLabsAeroSpaceKSatSeries and adding a conflict would be my first instinct, but how do we migrate people over to PL-KSat?
