### ISSUE TITLE
Add Principia

### ISSUE THREAD

**Issue by MagixInTheAir** [KSP-CKAN/NetKAN#6242]
Please add this mod to the CKAN supported mods list : 
https://github.com/mockingbirdnest/Principia

Thank you !
@mockingbirdnest

**Comment by pleroy** [comment]
(Principia author here.)

We are not particularly interested by integration with CKAN. We prefer that people come to github or the forum threads where they can find documentation, information about how to report bugs, and general assistance from fellow players.

In particular, the bug reporting procedures are different from other mods, so if the users follow the standard procedure of giving us the `KSP.log` file, the bug report is useless.

Furthermore, Principia has system dependencies (like the C++ runtime) that to the best of my understanding CKAN cannot manage.

**Comment by HebaruSan** [comment]
Thanks for the response, @pleroy!

Nowadays CKAN doesn't index mods when authors say No. Closing this and #5643...
