### ISSUE TITLE
choose version for recommended mod

### ISSUE THREAD

**Issue by Sigma88** [KSP-CKAN/NetKAN#6244]
when choosing an older version for a required mod it looks like the requirements are installed correctly 

however, doing the same for "recommended" mods does not seem to work

this is the output of the installation of SASS which requires kopernicus 1.3.1-3 (rather than the latest 1.3.1-6) and sigmabinary v1.6.9 (rather than the latest v1.6.11)

as you can see, the correct version of kopernicus is chosen, but the wrong one for sigma-binary

```
About to install...

 * Science Def Renamer v0.3.2(cached)
 * ModularFlightIntegrator 1.2.4.0(cached)
 * SASS-DRP 2.0(cached)
 * SASS-NH 2.0.1(cached)
 * SASS-OPM 1.2.4(cached)
 * SASS-RevSS 0.6(cached)
 * SASS-RevJ 1(cached)
 * SASS-Saru 0.1(cached)
 * SASS-SE 1.0(cached)
 * SASS-ER 1.2.4(cached)
 * SASS-StockalikeNeptune 1(cached)
 * SASS-UL 0.5.4(cached)
 * Stockalike Solar System v0.5.5
 * Sigma Binary 1:v1.6.11
 * Kronometer v1.3.1-2
 * Kopernicus Planetary System Modifier 2:release-1.3.1-3
 * Sigma Dimensions 0.9.6

Downloading "https://github.com/Sigma88/Stockalike/releases/download/v0.5.5/StockalikeSolarSystem.v0.5.5.zip"
Downloading "https://github.com/Sigma88/Sigma-Binary/releases/download/v1.6.11/Sigma-Binary.v1.6.11.zip"
Downloading "https://github.com/StollD/Kronometer/releases/download/v1.3.1-2/Kronometer.v1.3.1-2.zip"
Downloading "https://github.com/Kopernicus/Kopernicus/releases/download/release-1.3.1-3/Kopernicus-1.3.1-3.zip"
Downloading "https://github.com/Sigma88/Sigma-Dimensions/releases/download/v0.9.6/Sigma-Dimensions.v0.9.6.zip"
```

**Comment by Sigma88** [comment]
nevermind, I found the issue

**Comment by HebaruSan** [comment]
Can you please explain what doesn't work? I.e., you linked a netkan file, which part of it is having problems?

**Comment by Sigma88** [comment]
[here](https://github.com/Sigma88/CKAN/blob/master/Stockalike/StockalikeSolarSystem.netkan#L29) I specify I recommend a specific version of sigma binary

if I make a PR to KSP-CKAN/NetKAN with that .netkan file, [the output](https://ci.ksp-ckan.org/job/NetKAN/6866/console) shows this:

```
Recommends:
- SigmaBinary-core, version: v1.6.9
- SigmaSciDefRenamer
- Kronometer, version: v1.3.1-1
```

but, if I generate the .ckan file using netkan.exe and I load that .ckan file manually, the version I get is Sigma Binary v1.6.11 (which is the latest release, as opposed as the latest compatible one)

**Comment by HebaruSan** [comment]
Thanks! Of _course_ the relationship resolver has to make me a liar. :roll_eyes:
Are you finding that it works correctly for `depends`?

**Comment by Sigma88** [comment]
@HebaruSan it `depends` 😂

everything works fine in my locally generated .ckan file but if I use ckan.exe to install the mod normally (instead of doing install from .ckan) it still fails

**Comment by Sigma88** [comment]
I think I found the issue, the version number for mods makes absolutely no sense to me 😂

apparently:
- Kopernicus is `2:release-1.3.1-3` instead of `release-1.3.1-3`
- SigmaBinary is `1:v1.6.9` instead of `v1.6.9`
- SigmaDimensions is `0.9.6` instead of `v0.9.6`
- Kronometer is `v1.3.1-1` which is what I use on github

I have no idea why those are used, but I'm guessing those will work

**Comment by HebaruSan** [comment]
Ahh yup, those `number:` prefixes are version "epochs". Sometimes a mod's "true" version numbers change in a non-increasing way, so CKAN has to tweak them to make them make sense, and that's the main way of doing it.

https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#epoch

**Comment by Sigma88** [comment]
as soon as ckan updates and I can verify everything works fine I will close this

let's hope 🤞

**Comment by Sigma88** [comment]
I give up.

I have no idea what's going on with CKAN, the version requirements seem to be completely ignored by the executable while jenkins seems to install everything correctly

executable:

![image](https://user-images.githubusercontent.com/12640834/36299733-c024d7de-12fe-11e8-94f7-d571ba300822.png)


jenkins console:

https://ci.ksp-ckan.org/job/NetKAN/6872/console

**Comment by Sigma88** [comment]
so, even tho the preview is wrong, it looks like the requirements are installed correctly 

the "recommended" however are not installed correctly

```
About to install...

 * Science Def Renamer v0.3.2(cached)
 * ModularFlightIntegrator 1.2.4.0(cached)
 * SASS-DRP 2.0(cached)
 * SASS-NH 2.0.1(cached)
 * SASS-OPM 1.2.4(cached)
 * SASS-RevSS 0.6(cached)
 * SASS-RevJ 1(cached)
 * SASS-Saru 0.1(cached)
 * SASS-SE 1.0(cached)
 * SASS-ER 1.2.4(cached)
 * SASS-StockalikeNeptune 1(cached)
 * SASS-UL 0.5.4(cached)
 * Stockalike Solar System v0.5.5
 * Sigma Binary 1:v1.6.11
 * Kronometer v1.3.1-2
 * Kopernicus Planetary System Modifier 2:release-1.3.1-3
 * Sigma Dimensions 0.9.6

Downloading "https://github.com/Sigma88/Stockalike/releases/download/v0.5.5/StockalikeSolarSystem.v0.5.5.zip"
Downloading "https://github.com/Sigma88/Sigma-Binary/releases/download/v1.6.11/Sigma-Binary.v1.6.11.zip"
Downloading "https://github.com/StollD/Kronometer/releases/download/v1.3.1-2/Kronometer.v1.3.1-2.zip"
Downloading "https://github.com/Kopernicus/Kopernicus/releases/download/release-1.3.1-3/Kopernicus-1.3.1-3.zip"
Downloading "https://github.com/Sigma88/Sigma-Dimensions/releases/download/v0.9.6/Sigma-Dimensions.v0.9.6.zip"
```

**Comment by Sigma88** [comment]
just to be sure, is anyone else seeing what I am seeing?

or is this just happening to me?

**Comment by HebaruSan** [comment]
Sorry, I forgot what this issue was. Would you mind updating the OP?

**Comment by Sigma88** [comment]
the OP is exactly what this issue is.

even if I select a version in the "recommended" mods, CKAN ignores it

**Comment by Sigma88** [comment]
if you are having troubles reproducing this issue please let me know what more information I can provide / tests I can make to help solve the issue

**Comment by HebaruSan** [comment]
Going to try moving this from NetKAN to the CKAN issues list since I keep missing it and it's not something that can be fixed by changing metadata. First time trying https://github-issue-mover.appspot.com/, brace for impact...

**Comment by HebaruSan** [comment]
This issue was moved to KSP-CKAN/CKAN#2319
