### ISSUE TITLE
Error in autoupdate: The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by ncc17001** [KSP-CKAN/NetKAN#6279]
Background
----------

**CKAN Version:** 1.22.6

**KSP Version:** 
1.3.1.1891

**Operating System:** 
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Fresh install of ksp and CKAN will not work  

**Affected mods and mod versions:**

Problem
------- Every repositry except Mechjeb dev 2, 
will not open or respond to repeated connection attempts 

**What steps did you take in CKAN?**
cleared chache
removed all repositories and tested one by one
mechjeb is the only one to connect

**What did you expect to happen?**
repositorys to connect to
 ckan and import mod lists 

**What happened instead?**
Error in autoupdate: 
	The request was aborted: Could not create SSL/TLS secure channel.

**Screenshots:**

**CKAN error codes (if applicable):** 
Error in autoupdate: 
	The request was aborted: Could not create SSL/TLS secure channel.

**Comment by HebaruSan** [comment]
GitHub's having some kind of a conniption. The first report was KSP-CKAN/CKAN#2293, please go there if you want to follow this issue.
