### ISSUE TITLE
Whenever i start up CKAN I get this Error "Failed to connect to repository. Exception: Value cannot be null. Parameter name: collection", it was working just fine last night before i shut down my computer.

### ISSUE THREAD

**Issue by blackbeard76** [KSP-CKAN/NetKAN#6280]
Background
----------

**CKAN Version: v1.24.0-Pre

**KSP Version: 1.3.1

**Operating System: Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)? Yes, but have since done a clean install

**Affected mods and mod versions:**

Problem
-------

**What steps did you take in CKAN? Reinstalled 

**What did you expect to happen? Hopefully it would fix the issue/bug

**What happened instead?Nothing

**Screenshots:**

**CKAN error codes (if applicable):** Failed to connect to repository. Exception: Value cannot be null.
Parameter name: collection

**Comment by cmheisel** [comment]
Same here and I confirmed that I can reach the URL it's requesting: https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz

**Comment by Immrspy** [comment]
It looks like the github directory has been changed, or that file has been moved. I was going to start modding, but this is getting in the way a bit. I'll keep searching for the new place of master.tar.gz

**Comment by Immrspy** [comment]
It appears that you can go to https://github.com/KSP-CKAN/CKAN-meta/tree/master and download all the mod .ckan files. I think the reason for the move of the file was to prevent downloads. They are in the process of moving hosts to archive.org (This is my guess based off of the metadata and .ckan file info.)
You can manually import the .ckan files, but it looks like the download service is temporarily down.

**Comment by techman83** [comment]
This relates to KSP-CKAN/CKAN#2293, follow it for updates. archive.org is a fallback as we've been archiving OSS mods there for sometime. There aren't any plans to use it as a primary host.
