### ISSUE TITLE
Connection to https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz could not be established.

### ISSUE THREAD

**Issue by HelpPlsLmao** [KSP-CKAN/NetKAN#6281]
Connection to https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz could not be established.

I installed CKAN (Newest version) earlier today and I downloaded a few mods. Scatterer, Chatter(er), Astronomers Visual Pack, and all dependencies along with mos recommended mods. 

It had been working fine up until noon and I had been playing around and looking around the internet but it hadn't worked. 

I really want to use CKAN as downloading mods manually is a pain. Please help me!

-Best Regards

**Comment by HebaruSan** [comment]
Yup, GitHub changed their servers in a way that broke CKAN, see KSP-CKAN/CKAN#2293.
Investigation ongoing.

**Comment by HelpPlsLmao** [comment]
I know this is closed, but did the same happen to you?

**Comment by HebaruSan** [comment]
On Windows, Yes. It happened to every CKAN user on Windows yesterday.

**Comment by HebaruSan** [comment]
Install the new release to fix: https://github.com/KSP-CKAN/CKAN/releases/tag/1.24.0
