### ISSUE TITLE
CKAN doesn't work

### ISSUE THREAD

**Issue by nektpol** [KSP-CKAN/NetKAN#6282]
Background
----------

**CKAN Version:**  1.22.6

**KSP Version:** 1.3.1.189

**Operating System:** Windows 10 PRO X64

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** NO

**Affected mods and mod versions:** 

KSP: 1.3.1 (Win64) - Unity: 5.4.0p4 - OS: Windows 10  (10.0.0) 64bit
Toolbar - 1.7.16.5
AutoAsparagus - 2.2.8
B9 Part Switch - 2.1.1
Community Category Kit - 2.0.2
Community Resource Pack - 0.8
CommunityTechTree - 3.2.1
Contract Configurator - 1.23.3
DynamicBatteryStorage - 1.2
Easy Vessel Switch - 1.5.6471.31118
RasterPropMonitor - 0.29.3
Kerbal Attachment System - 0.6.3
Kerbal Engineer Redux - 1.1.3
Kerbal Joint Reinforcement - 3.3.3
Feline Utility Rover - 1.0.8
Kerbal Inventory System - 1.9.6571.274
KSP-AVC Plugin - 1.1.6.2
NearFutureConstruction - 0.8.4
NearFutureElectrical - 0.9.8
NearFutureProps - 0.3
NearFuturePropulsion - 0.9.5
NearFutureSolar - 0.8.8
NearFutureSpacecraft - 0.7.5
SCANsat - 1.1.8.4
SmartStage - 2.9.9
StationPartsExpansion - 0.5.2

Problem
-------

When I run CKAN.exe  the first error appear (look at the screenshots), when I click dismiss the second error appears. When I click continue the CKAN starts but in the list there are only the mods I downloaded before the errors. It crushed while downloading a mod and never started again correctly.

**What steps did you take in CKAN?**
I did this steps: 
https://github.com/KSP-CKAN/CKAN/wiki/Basic-troubleshooting
(there is a screenshot showing what happens when I run "ckan update" )
https://github.com/KSP-CKAN/CKAN/wiki/Clean-and-reinstall-process

**What did you expect to happen?**
Solve the problem

**What happened instead?**
Nothing. The errors keep coming

**Screenshots:**
1st Error

![image](https://user-images.githubusercontent.com/36765011/36595391-a3bfb576-18aa-11e8-8d3c-fd6209fec913.png)
2nd Error
![image](https://user-images.githubusercontent.com/36765011/36595407-b409c1e2-18aa-11e8-892c-d316bc4a0fd6.png)
CKAN
![image](https://user-images.githubusercontent.com/36765011/36595421-bf3fc052-18aa-11e8-9955-ade8c84e3d41.png)
CKAN update
![image](https://user-images.githubusercontent.com/36765011/36596074-305324d0-18ad-11e8-9c51-f548bd07d351.png)

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
GitHub changed their servers in a way that broke CKAN, see KSP-CKAN/CKAN#2293.
There's a new release that fixes this: https://github.com/KSP-CKAN/CKAN/releases/tag/1.24.0
