### ISSUE TITLE
Unable to look at the links for the Mods

### ISSUE THREAD

**Issue by Zuthorex** [KSP-CKAN/NetKAN#6288]
Basically with the new update you cannot scroll down to look at the links for the mods (I use them to get more information) Id have to either enlarge the window or look it up manually to get the link.

**Comment by HebaruSan** [comment]
You have to move the splitter.

![splitter low](https://i.imgur.com/DY5sKsE.png) &rArr; ![splitter high](https://i.imgur.com/7KdZsgy.png)
