### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by nerftruck** [KSP-CKAN/NetKAN#6289]
Background
----------

**CKAN Version:** 1.22.6

**KSP Version:** 1.3.1.1891

**Operating System:** 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** No

**Affected mods and mod versions:**

Problem
-------

**What steps did you take in CKAN?** Reinstall

**What did you expect to happen?**able to maybe access the mods to maybe delete the files 

**What happened instead?** same error

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
#2293, https://github.com/KSP-CKAN/CKAN/releases/tag/v1.24.0
