### ISSUE TITLE
Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by TheCodyCZ** [KSP-CKAN/NetKAN#6295]
Background
----------

**CKAN Version:** 
1.22.6

**KSP Version:** 
1.3.1.1891

**Operating System:** 
Windows 10 Education 1709

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
I only Add my own flag into game

**Affected mods and mod versions:**
no

Problem
-------

**What steps did you take in CKAN?**
I Start CKAN

**What did you expect to happen?**
Normaly Autoupdate and start

**What happened instead?**
Show mw error on screenshot

**Screenshots:**

![obrazek](https://user-images.githubusercontent.com/36842644/36663506-10bd0280-1ae2-11e8-91c2-f29bc479d7e5.png)

**CKAN error codes (if applicable):** 
Error in autoupdate: 
	The request was aborted: Could not create SSL/TLS secure channel.

**Comment by HebaruSan** [comment]
GitHub changed their servers in a way that broke CKAN, see KSP-CKAN/CKAN#2293, KSP-CKAN/CKAN#2294, KSP-CKAN/CKAN#2295, KSP-CKAN/NetKAN#6279, KSP-CKAN/CKAN#2296, KSP-CKAN/NetKAN#6280, KSP-CKAN/NetKAN#6281, KSP-CKAN/NetKAN#6282, KSP-CKAN/CKAN#2299, KSP-CKAN/NetKAN#6284, KSP-CKAN/CKAN#2304, KSP-CKAN/CKAN#2309, KSP-CKAN/NetKAN#6289, KSP-CKAN/CKAN#2317, and possibly others.

Install https://github.com/KSP-CKAN/CKAN/releases/tag/v1.24.0
