### ISSUE TITLE
GPP not recommending SigmaReplacements: Skybox

### ISSUE THREAD

**Issue by Galileo88** [KSP-CKAN/NetKAN#6300]
So GPP updated and is on CKAN successfully again, but its not showing SigmaReplacements: Skybos, as a recommended mod, though it's in the netkan to do so. Any Idea why this could be?

**Comment by linuxgurugamer** [comment]
It says in CKAN.exe, in red:

SigmaReplacements-Skybox (not indexed)

**Comment by HebaruSan** [comment]
Relationships are case sensitive, the recommendation is for Skybox but the module is Sky**B**ox.

**Comment by Galileo88** [comment]
Oh ok cool I’ll fix that. Thanks!
