### ISSUE TITLE
KAS version is not updating

### ISSUE THREAD

**Issue by ihsoft** [KSP-CKAN/NetKAN#6314]
Hello,

I've [updated](https://github.com/ihsoft/KAS/commit/292804e3248eec8bd7b1722773947bcd1196a668) the version about 10 hours ago, but CKAN still shows the old version. The config of the mod is in: https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/KAS.netkan.

Is it something broken in the pipeline, or 10 hours is not enough for it to update?

**Comment by HebaruSan** [comment]
Thanks for calling this to our attention. The bot seems to not be running at all currently; "15 hours ago" is not a normal value for "last checked": http://status.ksp-ckan.org/

@techman83, can you please give it a good smack?

**Comment by HebaruSan** [comment]
There it goes. Latest KAS is here: https://github.com/KSP-CKAN/CKAN-meta/commit/5c6325110aa706b6bd3828a32b6baf4e49626aa8

Please let us know if there are any further issues.

**Comment by ihsoft** [comment]
Awesome! Thank you very much for the quick resolution.

**Comment by techman83** [comment]
Usually things are fine, but when a lot of new mods drop or one of the bigger hosting sites are under a bit of strain the indexing takes longer. Sometimes hitting the run time out. After a few runs, the mods get cached up, things get archived and it catches up.

I've dropped the timeout and the schedule to let it do a complete run and check back later tonight.
