### ISSUE TITLE
My mods/ all the mods won't load in 

### ISSUE THREAD

**Issue by progradethistime** [KSP-CKAN/NetKAN#6322]
**CKAN Version:** 
The new one Mar 11, 2018 

**KSP Version:** 
1.3.1

**Operating System:** 
windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Yes, I have when I did the clean restart. 

**Affected mods and mod versions:**
All the mods won't show up.

Problem
-------

**What steps did you take in CKAN?**

**What did you expect to happen?**
I thought all the mods would load.

**What happened instead?**
None of the mods loaded.

**Screenshots:**

![ckan problem](https://user-images.githubusercontent.com/37260538/37256488-fcf9249c-2520-11e8-8000-edd80d21a72f.PNG)
![ckan problem2](https://user-images.githubusercontent.com/37260538/37256490-00d4910a-2521-11e8-9b59-91b626fb9368.PNG)
![ckan problem3](https://user-images.githubusercontent.com/37260538/37256494-0616973a-2521-11e8-8b29-e80cacbad0c2.PNG)

Please  help.

**Comment by HebaruSan** [comment]
Hi, that's not the new version as of Mar 11, 2018.

![image](https://user-images.githubusercontent.com/1559108/37256559-64a57d30-252a-11e8-8a19-b970e30aed95.png)

The new version is here: https://github.com/KSP-CKAN/CKAN/releases/tag/v1.24.0

See KSP-CKAN/CKAN#2293, GitHub changed their servers in a way that broke older versions of CKAN.

You'll get an error at startup as per KSP-CKAN/CKAN#2298. Click Continue, then Refresh.
