### ISSUE TITLE
ShowFPS still shows Max KSP version even though it's been updated

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#6368]
I adopted this mod, and updated the netkan.
It properly shows in CKAn when showing compatible mods, but it still lists the Max KSP version as 1.1

I suspect this is because the old version had it hard-coded in the netkan, and that's been removed, as well as the new .version file doesn't have that field at all.

I can always push a new version with an updated .version file, but would rather not if I don't have to.

Let me know

**Comment by linuxgurugamer** [comment]
I also added an epoch to it, hoping that will fix the issue, since the versioning changed

**Comment by linuxgurugamer** [comment]
The epoch fixed it

**Comment by HebaruSan** [comment]
Thanks for calling this out; the client shouldn't be doing that, but KSP-CKAN/CKAN#2131 got reverted along with KSP-CKAN/CKAN#1929 in KSP-CKAN/CKAN#2150...
