### ISSUE TITLE
ContractPack-AnomalySurveyor not showing up in CKAN-meta

### ISSUE THREAD

**Issue by jrossignol** [KSP-CKAN/NetKAN#637]
Hmmm....  @hakan42  merged the pull request for the .netkan file about 5 hours ago, but I haven't seen the module show up in the CKAN-meta repository yet (and I can see that the bot has run, as it has made other commits).

Can someone take a look and let me know if there's a problem on my side (github or in the .netkan file)?

**Comment by hakan42** [comment]
The MirrorKAN script runner fails to create directories for new mods. Creating the directories manually fixed this issue, so new versions of should be recognized immediately.

netkan throws a System.IO.DirectoryNotFoundException , but maybe the log collector script should detect those and display them prominently on the index page.

**Comment by jrossignol** [comment]
Awesome, thanks!
