### ISSUE TITLE
Cant figure out why GPP's main mod folder is not updated in CKAN

### ISSUE THREAD

**Issue by Galileo88** [KSP-CKAN/NetKAN#6405]
The netkan on my end seems ok [HERE](https://github.com/Galileo88/Galileos-Planet-Pack/blob/master/CKAN/GPP.netkan)

The Textures and clouds updated just fine, so I'm now looking for an issue, wherever it could be

**Comment by HebaruSan** [comment]
Check http://status.ksp-ckan.org/

The netkan is out of date:

> Could not find Optional Mods/GPP_KSCSwitcher/GameData/KSCSwitcher entry in zipfile to install

**Comment by Galileo88** [comment]
I figured since it wasn't updated, I would update the netkan and noticed that. Hopefully that corrects it.
and thanks for that link. It will come in handy.

**Comment by HebaruSan** [comment]
Running netkan.exe locally correctly generates the `GPP-1-1.6.2.1.ckan` file, so maybe something weird with the bot? ...

**Comment by techman83** [comment]
It was last indexed an hour ago, is it good now?

**Comment by Galileo88** [comment]
Yes its up now!
