### ISSUE TITLE
Mods by same author have same files CKAN won't install both

### ISSUE THREAD

**Issue by Topside08** [KSP-CKAN/NetKAN#6413]
**CKAN Version:**  
1.24.0

**KSP Version:** 
1.3.1.1891

**Affected mods and mod versions:**
- [PicoPort 0.1.3](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/PicoPort.netkan)
- [Recoverable Emergency Kerbal Transport 0.4.5.1](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/REKT.netkan) 

These mods are by the same author so the zips contain some of the same files 
a License file and everything in the Agencies folder

**Comment by HebaruSan** [comment]
Thanks for letting us know. There should be updated metadata within a few minutes that would address this.
