### ISSUE TITLE
Why Mods hosted on both SpaceDock and GitHub should follow the SpaceDock guide?

### ISSUE THREAD

**Issue by yalov** [KSP-CKAN/NetKAN#6420]
both use .version file, so what is the difference?

trying to move from autogenerated spacedock to github. Is this correct?

``` json
{
    "spec_version" : 1,
    "identifier"   : "SpeedUnitAnnex",
    "$kref"        : "#/ckan/github/yalov/SpeedUnitAnnex",
    "name"         : "Speed Unit Annex",
    "author"       : "flart",
    "abstract"     : "Add (annex) some new speed unit and helpful value to the navball's top line, depending from navball mode and vesselType.",
    "license"      : "GPL-3.0",
    "$vref" : "#/ckan/ksp-avc",
    "resources" : {
        "homepage": "https://forum.kerbalspaceprogram.com/index.php?/topic/169611-*"
    },
    "conflicts": [
        { "name": "SpeedUnitChanger" },
        { "name": "SpeedUnitDisplay" }
    ]
}
```

**Comment by HebaruSan** [comment]
You can test it out by clicking the pencil icon and saving your changes to a new pull request:

https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/SpeedUnitAnnex.netkan

**Comment by HebaruSan** [comment]
Fixed by #6422.

**Comment by yalov** [comment]
Does it parse .version from /master or /releases/latest ?

**Comment by HebaruSan** [comment]
The CKAN bot downloads the ZIP file from the release and searches it for a .version file.

**Comment by yalov** [comment]
Do several zips also work for CKAN bot?
https://github.com/yalov/SpeedUnitAnnex/releases/tag/1.1.4

but KSP Addon Version Checker still use .version from /master ?

**Comment by HebaruSan** [comment]
I believe KSP-AVC uses the file in the download to determine the _current_, and uses the URL tag to determine whether there are updates available. @linuxgurugamer has been working on that code recently so he may be able to give you a better answer.

**Comment by yalov** [comment]
Sometime you can already push new .version to master but delay with push new tag and upload zip-release. 
@linuxgurugamer, Will KSP-AVC be OK?
@HebaruSan, Will CKAN-bot be OK?

**Comment by HebaruSan** [comment]
The CKAN bot only looks at the releases. If there's no new release, it won't change anything.
