### ISSUE TITLE
Snacks

### ISSUE THREAD

**Issue by GargamelKSP** [KSP-CKAN/NetKAN#6434]
Ckan is forcing a 1.4.x version of Snacks onto my 1.3.1 version.  The 1.4 version is incompatible with 1.3.  
Thanks!

Background
----------

**CKAN Version:** 

**KSP Version:** 

**Operating System:** 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

**Affected mods and mod versions:**

Problem
-------

**What steps did you take in CKAN?**

**What did you expect to happen?**

**What happened instead?**

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
Thanks for letting us know. This should be fixed now if you click Refresh.
