### ISSUE TITLE
EVE configs not version-specific

### ISSUE THREAD

**Issue by WazWaz** [KSP-CKAN/NetKAN#6445]
The configs for Environmental Visual Enhancements are not specific to 1.3.9, they work with any version and should have at least 1.4.99 as their compat version (but 1.99 is more likely).

**Comment by HebaruSan** [comment]
Can you please give us a hint as to the name of the packages with the problem? Is it just `EnvironmentalVisualEnhancements-HR`?

**Comment by WazWaz** [comment]
Oops, sorry, yes, that's the package ID.

**Comment by HebaruSan** [comment]
Thanks for letting us know. It should be updated within a few minutes.
