### ISSUE TITLE
SXTContinued 0.3.25 is installed and not 0.3.23.1

### ISSUE THREAD

**Issue by ericfriesen** [KSP-CKAN/NetKAN#6466]
Background
----------

**CKAN Version:** 
v 1.24.0

**KSP Version:** 
v 1.3.1.1891

**Operating System:** 
Windows 10 Professional 64-bit v1709

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

**Affected mods and mod versions:**
SXTContinued

Problem
-------

**What steps did you take in CKAN?**
v 0.3.23.1 is marked for install

**What did you expect to happen?**
For v 0.3.23.1 to be installed

**What happened instead?**
v 0.3.25 is installed

**Screenshots:**
![image](https://user-images.githubusercontent.com/25352077/38472133-d05db944-3b40-11e8-8aea-84749c1966bc.png)

**CKAN error codes (if applicable):** 
none

**Comment by HebaruSan** [comment]
That's what's in the download for 0.3.23.1 on SpaceDock. See for yourself:

- https://spacedock.info/mod/1030/SXTContinued/download/0.3.23.1

Recommend filing an issue report on the mod's repo:

- https://github.com/linuxgurugamer/SXTContinued/issues/new
