### ISSUE TITLE
No update for Astronomer's Visual Pack

### ISSUE THREAD

**Issue by mkaaaf** [KSP-CKAN/NetKAN#6480]
Background
----------

**CKAN Version:** 
1.25.0

**KSP Version:** 
1.4.2.2110

**Operating System:** 
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

**Affected mods and mod versions:**
Astronomer's Visual Pack

Problem
-------

**What steps did you take in CKAN?**
Latest version is v3.63

**What did you expect to happen?**
Last version on github is v3.70

**What happened instead?**
Can't update to 3.7

**Screenshots:**

![image](https://user-images.githubusercontent.com/22660015/38782804-0ed6b80c-40f9-11e8-85f3-bc25348ae292.png)

![image](https://user-images.githubusercontent.com/22660015/38782808-1c283706-40f9-11e8-8db1-a94eecc94ad2.png)

**Comment by HebaruSan** [comment]
[It's indexed](https://github.com/KSP-CKAN/CKAN-meta/blob/master/AstronomersVisualPack/AstronomersVisualPack-v3.7.ckan). Have you clicked Refresh recently?

**Comment by mkaaaf** [comment]
I just downloaded Ckan, and i refreshed a lot of time (i had a problem with some dependencies) 

![image](https://user-images.githubusercontent.com/22660015/38784013-6d3261d2-410b-11e8-9058-d364130464d2.png)

Still 3.63 

![image](https://user-images.githubusercontent.com/22660015/38784015-7c71ce94-410b-11e8-902a-41f1660da23a.png)

**Comment by Olympic1** [comment]
I think the problem lies in the numbering.
63 is higher then 7

**Comment by mkaaaf** [comment]
It's really weird, and i dont think so @Olympic1, in the Github page of astronomer's 3.70 is the last one, and on my game at start it says me that i have to update this mod...

**Comment by HebaruSan** [comment]
Where does it say 3.70 instead of 3.7?

**Comment by mkaaaf** [comment]
3.7 I'm sorry, anyway i'm still in 3.63 and everytime i connect to the game it asks me to update :/

**Comment by HebaruSan** [comment]
That makes sense, as 3.63's version file says 3.6.3 instead.

```json
"VERSION":{"MAJOR":3,"MINOR":6,"PATCH":3,"BUILD":0}
```
