### ISSUE TITLE
When I open CKAN it shows a ERROR message

### ISSUE THREAD

**Issue by wolfman19** [KSP-CKAN/NetKAN#6496]
Background
----------

**CKAN Version:** 
v1.24.0-pre

**KSP Version:** 
1.4.2

**Operating System:** 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
yes

**Affected mods and mod versions:**
it won't let me install new mods

Problem
-------

**What steps did you take in CKAN?**
I open it 

**What did you expect to happen?**

**What happened instead?**

**Screenshots:**

**CKAN error codes (if applicable):** 
Failed to connect to repository. Exception: Value cannot be null.
Parameter name: collection

**Comment by HebaruSan** [comment]
1.4.2.2110 is a KSP version, not a CKAN version. What is your CKAN version? It's shown in the title bar.

**Comment by wolfman19** [comment]
v1.24.0-pre
