### ISSUE TITLE
DMagic and USI mods for 1.4.X versions

### ISSUE THREAD

**Issue by DavideCoco** [KSP-CKAN/NetKAN#6503]
Hi and first of all, thanks for your work!
I'm trying to install several mods of DMagic (like CapCom, Contracts Window +, Orbital Science, Portrait Stats) but they are listed as 1.4.1. On its official forum pages thay are both listed as 1.4.X, so are their dependencies.

Also there's an issue with USI Modular Kolonization System. It is listed as compatibile with 1.4.0-1.4.99 but in its changelog page there is only a compatibility with 1.4.1.

**Comment by HebaruSan** [comment]
Thanks for letting us know; the DMagic mods should be fixed within a few minutes as soon as the bot has time to re-index them.

The metadata for USI MKS is managed directly by the mod author; the CKAN team can't change it, so you'll have to contact him to get that updated.
