### ISSUE TITLE
CKAN wont let me install new mods! I was trying to install EVE for KSP 1.3.1 but the apply changes button is greyed out and none of my mods say theyre incompatible. 

### ISSUE THREAD

**Issue by Dakotaagunn** [KSP-CKAN/NetKAN#6505]
Background
----------

**CKAN Version:** 

**KSP Version:** 

**Operating System:** 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

**Affected mods and mod versions:**

Problem
-------

**What steps did you take in CKAN?**

**What did you expect to happen?**

**What happened instead?**

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
Works for me. We'll need to know your mod list to investigate this.
