### ISSUE TITLE
Near Future Construction [1.0.0] to [1.0.1] 

### ISSUE THREAD

**Issue by DavideCoco** [KSP-CKAN/NetKAN#6525]
Hi!
Nertea released an update (1.0.1) of Near Future Construction on April 10th, but in CKAN there is the previous version (1.0.0) listed as compatible with 1.4.2.

**Comment by HebaruSan** [comment]
The bot has been [erroring out on that mod](http://status.ksp-ckan.org/) for a while, with an error it shared with two other mods:

| NetKAN | Last Error ▾ |
| ---- | --- |
| NearFutureConstruction | Cannot find central directory |

I don't know what that means, and it works fine if run locally. I'm hoping that we'll get more information if/when KSP-CKAN/NetKAN-bot#63 is merged. So far my only guess is that a broken ZIP was uploaded initially and replaced, with the original file still in the bot's cache, but that's pure speculation.

**Comment by HebaruSan** [comment]
Looks like 1.0.2 just came out and was indexed without a problem.

https://github.com/KSP-CKAN/CKAN-meta/commit/95c96f9fa2e6998c0239290d4b761f913288a068
