### ISSUE TITLE
Blank Changeset - Can't apply changes

### ISSUE THREAD

**Issue by DocBennett** [KSP-CKAN/NetKAN#6533]
Background
----------

**CKAN Version:** 
1.25.1

**KSP Version:** 
1.4.3.2152

**Operating System:** 
Windows 10 Pro

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

**Affected mods and mod versions:**
Multiple

Problem
-------

**What steps did you take in CKAN?**
Launched
Saw updates available
Clicked "Add available updates"
Clicked "Apply changes"

**What did you expect to happen?**
The Changeset log would show the update process

**What happened instead?**
The Changeset log is blank, Apply button does nothing.

**Screenshots:**

![image](https://user-images.githubusercontent.com/10655304/39723889-2042e91c-5215-11e8-979d-0ad465927fcf.png)

![image](https://user-images.githubusercontent.com/10655304/39718606-cbee019a-5204-11e8-88d1-91b09d032934.png)

**Comment by HebaruSan** [comment]
Thanks for the report. Can you please fill in which mods it's trying to update? Looks like a duplicate of KSP-CKAN/CKAN#2428, but we would need to know the mods to be sure.

**Comment by DocBennett** [comment]
![image](https://user-images.githubusercontent.com/10655304/39723889-2042e91c-5215-11e8-979d-0ad465927fcf.png)

**Comment by HebaruSan** [comment]
OK, I managed to set up that scenario on my PC (sorry for the delay, some of them took a while to download). I get a proper change set when I queue the updates, so it may be a conflict with one of the other mods.

Do you have a planet pack installed? Maybe it's trying to version-pin your Kopernicus.

**Comment by DocBennett** [comment]
No planet pack. I tried to see if any single mod update worked/didn't. I found that no matter which of those shown in the screenshot are checked manually that the "Apply changes" button stays inactive. It will only become click-able when I use "Add available updates" to check the updates.

Also, unchecking these mods in the "Installed" column to attempt removal also gives no listing/action on the Changeset.

**Comment by DocBennett** [comment]
I think I sorted this out. I had a manual install of For Science that was conflicting with DMagic Orbital Science. CKAN back to expected behavior after removing the folder from GameData.
