### ISSUE TITLE
KIS version is not updating

### ISSUE THREAD

**Issue by ihsoft** [KSP-CKAN/NetKAN#6543]
CKAN missed to latest version updates. It says the last version is 1.10, while in fact there is 1.12 available.
The Netkan file for the mod is here: https://github.com/ihsoft/KIS/blob/master/KIS.netkan

**Comment by HebaruSan** [comment]
Curse asked the developer of the (third party) API to stop running it, see his comments in #6481. This froze all netkans with a $kref pointing to Curse as of March 17, 2018.

We migrated mods with alternate downloads off of Curse in #6483. If there's a non-Curse host available for this mod, please let us know.

**Comment by ihsoft** [comment]
Hello, @HebaruSan. Thank you for the reply. It's sad they did it :( I liked CurseForge for its versions history. The alternatives either lack this ability (SpaceDock), or it's not convenient for a non-technical player (GitHub). But now I have no choice, I guess.

**Comment by HebaruSan** [comment]
In case you're referring to the ability to see old versions, SpaceDock has this, but it's hidden behind the "Changelog" button.

**Comment by HebaruSan** [comment]
[An update](https://github.com/KSP-CKAN/CKAN-meta/commit/cf78a8dd5de0237a7c4f00e48918b10611974706) just came through for KIS, along with [one for ForScience](https://github.com/KSP-CKAN/CKAN-meta/commit/56335d9b353da722981f25fd04c2614aa48c3f2b)! You may not need to migrate after all.

@citricsquid, is the Curse widget formally back in business? I notice that the disclaimer header is gone now. Thanks for whatever fix has taken place!

**Comment by ihsoft** [comment]
@HebaruSan Woohoo! Thanks for pointing it out. I hope it's a long term solution. I love CKAN integration with Curse.

**Comment by citricsquid** [comment]
@HebaruSan you beat me to it, the (updated) system is back online in the last hour or so.

The CurseForge team have worked with me to bring data to the widget, I now have access to the data directly and I'm using that data source instead of scraping the CurseForge pages -- which is no longer possible. Hopefully this should be a good sign for long term stability :-) 

Let me know if you run into any issues. Thanks for your patience!

**Comment by HebaruSan** [comment]
That's fantastic! I was afraid the Curse team decided they didn't want third party programmatic access, but now it's the opposite with official support!

Closing this issue as fixed, and thanks again!

**Comment by techman83** [comment]
NetKAN|Last Checked|Last Inflated|Last Indexed
---|---|---|---
KIS|an hour ago|an hour ago|5 hours ago
