### ISSUE TITLE
.netkan help please? Why won't this file work.

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-CKAN/NetKAN#656]
Whenever I test this using netkan.exe I get:

>106 [1] INFO CKAN.NetKAN.MainClass (null) - Using tempdir for cache: /var/folders/sq/zqvhmlzj3kgc9vq66fx2xp4m0000gn/T/
121 [1] INFO CKAN.NetKAN.MainClass (null) - Processing TestFlight.netkan
949 [1] ERROR CKAN.NetKAN.MainClass (null) - Downloaded releases for jwvanderbeck/TestFlight but there were none
949 [1] ERROR CKAN.NetKAN.MainClass (null) - There was an error, aborting

    {
	    "spec_version" : "v1.2",
    	    "name" : "TestFlight",
	    "abstract" : "Flight Testing of your space hardware in KSP!  Fly your parts to gain flight data and make them more reliable and less likely to fail.",
	    "identifier" : "TestFlight",
	    "$vref" : "#/ckan/ksp-avc",
	    "$kref" : "#/ckan/github/jwvanderbeck/TestFlight",
	    "license" : "CC-BY-NC-SA-4.0",
	    "release_status" : "testing",
	    "ksp_version" : "0.90",
	    "resources" : {
		    "homepage" : "http://forum.kerbalspaceprogram.com/threads/88187",
		    "repository" : "https://github.com/jwvanderbeck/TestFlight",
		    "bugtracker" : "https://github.com/jwvanderbeck/TestFlight/issues",
	    },
	    "install" : [
            {
                "file"       : "GameData/TestFlight",
                "install_to" : "GameData"
            }
        ],
	    "depends" : [
                { "name" : "ModuleManager", "min_version" : "2.5.8" }
            ],
        "suggests" : [
    	    { "name" : "RP-0" },
    	    { "name" : "RealismOverhaul"} 
        ]
    }

**Comment by TeddyDD** [comment]
I suppose netkan doesn't see pre releases. You should remove pre-release tag from one of your releases. Or consider posting this on **Kerbal Stuff**. If you do so then you would need much simpler netkan: (look here: https://github.com/KSP-CKAN/CKAN-support/wiki/Adding-a-mod-to-the-CKAN)
```json
{
    "spec_version" : 1,
    "identifier"   : "Test Flight",
    "$kref"        : "#/ckan/kerbalstuff/<ksid>",
    "x_netkan_license_ok": true,
     "depends": [
        {
            "name": "ModuleManager",
            "min_version": "2.5.8"
        }
    ],
    "suggests": [
        {
            "name": "RP-0"
        },
        {
            "name": "RealismOverhaul"
        }
    ]
}
```

Also, remeber to lint your netkan file to make sure it is proper json http://jsonlint.com/ :smiling_imp:
```json
{
    "spec_version": "v1.2",
    "name": "TestFlight",
    "abstract": "Flight Testing of your space hardware in KSP!  Fly your parts to gain flight data and make them more reliable and less likely to fail.",
    "identifier": "TestFlight",
    "$vref": "#/ckan/ksp-avc",
    "$kref": "#/ckan/github/jwvanderbeck/TestFlight",
    "license": "CC-BY-NC-SA-4.0",
    "release_status": "testing",
    "ksp_version": "0.90",
    "resources": {
        "homepage": "http://forum.kerbalspaceprogram.com/threads/88187",
        "repository": "https://github.com/jwvanderbeck/TestFlight",
        "bugtracker": "https://github.com/jwvanderbeck/TestFlight/issues"
    },
    "install": [
        {
            "file": "GameData/TestFlight",
            "install_to": "GameData"
        }
    ],
    "depends": [
        {
            "name": "ModuleManager",
            "min_version": "2.5.8"
        }
    ],
    "suggests": [
        {
            "name": "RP-0"
        },
        {
            "name": "RealismOverhaul"
        }
    ]
}
```
If you have any questions will be happy to help :)
Cheers

**Comment by hakan42** [comment]
Actually netkan *can* see pre-releases if you give it the command line option --pre-release. 

This is intended for development releases though,  so the comment of  @TeddyDD is still valid :smile:

**Comment by jwvanderbeck** [comment]
You know I've just been so used to ticking that pre-release box during development I just did it out of habit even though this was the first 1.0 release!  Didn't even realize I had done it.

Thanks!
