### ISSUE TITLE
New version of ClickThroughBlocker not indexed

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#6560]
Uploaded to Spacedock hours ago, also on Github.

Not updated.
Current version should be 0.1.6.5

**Comment by HebaruSan** [comment]
Looks like it needs an install stanza update.

> ClickThroughBlocker
> Could not find ClickThroughBlocker entry in zipfile to install

http://status.ksp-ckan.org/

**Comment by linuxgurugamer** [comment]
oh crap.  I renamed things, I'll get it fixe.d

Thanks
