### ISSUE TITLE
An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by ace4545** [KSP-CKAN/NetKAN#6563]
Background
----------

**CKAN Version:** 1.25.1

**KSP Version:** 1.4.3.2152

**Operating System:** W10 64x

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** No

**Affected mods and mod versions:** None APplicable

Problem
-------

**What steps did you take in CKAN?** Start CKAN up

**What did you expect to happen?** To show a list of mods

**What happened instead?** Error screen provided (Repository update failed)

**Screenshots:**

![image](https://user-images.githubusercontent.com/14132183/40556545-e8b68d78-6001-11e8-8f7e-703662d9a7ff.png)

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
Looks identical to KSP-CKAN/CKAN#2445. Please try adjusting your Windows Firewall settings as per this link:

https://social.technet.microsoft.com/Forums/windows/en-US/e0cc1b3e-2c63-451a-abc8-8e1e66a23287/an-attempt-was-made-to-access-a-socket-in-a-way-forbidden-by-its-access-permissions?forum=w7itpronetworking

**Comment by ace4545** [comment]
My antivirus/firewall software (Norton) secretly blocked it, thanks for the help, had to finagle norton stuff
