### ISSUE TITLE
RealHeat 4.6 installed with KSP 1.3

### ISSUE THREAD

**Issue by ericfriesen** [KSP-CKAN/NetKAN#6572]
Background
----------

**CKAN Version:** 
1.25.1

**KSP Version:** 
1.3.1.1891

**Operating System:** 
Windows 10 Professional 64-bit v1803

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

**Affected mods and mod versions:**
RealHeat

Problem
-------

**What steps did you take in CKAN?**
Installed RealHeat

**What did you expect to happen?**
v4.5 to be installed

**What happened instead?**
v4.6 was selected to be installed, which is not compatible with 1.3.x
See https://github.com/KSP-RO/RealHeat/blob/v4.6/Source/Checkers.cs
**Screenshots:**

![image](https://user-images.githubusercontent.com/25352077/40640827-49019e38-62dd-11e8-963d-9d6cead449b7.png)

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
Thanks for letting us know. Should be fixed within a few minutes.
