### ISSUE TITLE
BackgroundProcessing.netkan failure

### ISSUE THREAD

**Issue by jamespicone** [KSP-CKAN/NetKAN#658]
Hi, I'm the developer of the BackgroundProcessing mod. The .netkan for it is failing right now, and I'm not entirely certain how to fix it.

Starting from version 0.3.5.1 of my mod, I started adding a version number to the DLL's filename for assembly identity reasons - it's necessary for the mod's only-most-recent-assembly code to work properly. And the mod is supposed to go into top-level GameData, although it isn't hugely important. And the last several releases haven't had a folder inside the .zip to "find" inside install instructions. This is all similar to the ModuleManager situation, which as far as I can tell is resolved by manually making each MM .ckan file in the ckan-meta repository. Is that likely to be the solution here, or maybe some kind of macro facility inside netkan, or the ability to "find" : ".", or wildcards in "file", or what?

**Comment by TeddyDD** [comment]
I see that your mod is installed like ModuleManager. I'm not sure how CKAN deal with ModuleManager (Probably .ckan files created manually or by some script?) 

I think would be needed support for wildcards in the "find" statement. I'll open the issue in CKAN-core

@jamespicone If you want I can create the .ckan file manually as a temporary solution.

**Comment by TeddyDD** [comment]
Ok, here's PR @jamespicone ping me please when you release new version :)

**Comment by hakan42** [comment]
Aaaand merged :smile:
