### ISSUE TITLE
Main Menu Buttons Not Working

### ISSUE THREAD

**Issue by McYodo** [KSP-CKAN/NetKAN#6609]
Background
----------

**CKAN Version:** 
1.25.1

**KSP Version:** 
1.4.4.2215

**Operating System:** 
Windows

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

**Affected mods and mod versions:**
Kerbal planetary base systems, 1.6.4/ Mechjeb 2,  2.7.3.0/ Kerbal engineer redux, 1.1.5.2

Problem
-------

**What steps did you take in CKAN?**
Downloaded those mods and launched KSP

**What did you expect to happen?**
The game to launch normally and play

**What happened instead?**
It launched, then at the main menu none of the buttons worked (Start game, Addons and mods, Quit, etc.)

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
Are they disabled? What happened when you clicked them? Can you add a screenshot?

**Comment by HebaruSan** [comment]
Try the modded support subforum; the CKAN team doesn't fix bugs inside the game proper:

https://forum.kerbalspaceprogram.com/index.php?/forum/70-technical-support-pc-modded-installs/
