### ISSUE TITLE
Version error: Atronomers Visual Pack

### ISSUE THREAD

**Issue by GorgeousWalrus** [KSP-CKAN/NetKAN#6637]
Background
----------

**CKAN Version:** 
1.25.1

**KSP Version:** 
1.4.x

**Operating System:** 
Ubuntu18.04/Windows10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

**Affected mods and mod versions:**
Astronomers Visual Pack

Problem
-------

**What steps did you take in CKAN?**
Tried to install the Astronomers Visual Pack 8k-Textures (also 4k&2k)

**What did you expect to happen?**
Successful install

**What happened instead?**
CKAN reports that the dependency Astronomers Visual Pack is not compatible with the installed KSP version (all >= 1.4.0) although on the forum site of the AVP and in CKAN in the 'Max KSP' coloumn it says it is compatible up to 1.4.4.

**Comment by HebaruSan** [comment]
Check the dependencies. Kopernicus isn't out for 1.4.4 yet, and neither is Scatterer.

![image](https://user-images.githubusercontent.com/1559108/42950025-a6eea380-8b62-11e8-8af0-e3bc23ab5d9a.png)

**Comment by GorgeousWalrus** [comment]
Yes for 1.4.4 that‘s true, but both are released for 1.4.0-1.4.2!

**Comment by HebaruSan** [comment]
OK, so what version exactly are you trying? "1.4.x" is not a specific version.

**Comment by GorgeousWalrus** [comment]
I tried it on all available versions, that‘s why I wrote 1.4.x

**Comment by HebaruSan** [comment]
Looks like it works fine on 1.4.2:

![image](https://user-images.githubusercontent.com/1559108/42954215-b674ec5c-8b6b-11e8-9174-abe6b320d088.png)
