### ISSUE TITLE
applying Updates 

### ISSUE THREAD

**Issue by Sgtquin** [KSP-CKAN/NetKAN#6640]
Background
----------

**CKAN Version:** 

**KSP Version:** 

**Operating System:** 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

**Affected mods and mod versions:**

Problem
-------

**What steps did you take in CKAN?**

**What did you expect to happen?**

**What happened instead?**

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
No information; closing.
