### ISSUE TITLE
Need to purge SpaceplanePlus download from bot cache

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN#6643]
[AirplanePlus has replaced its current version download after the original was indexed](https://forum.kerbalspaceprogram.com/index.php?/topic/140262-14x-144-airplane-plus-r230-full-1875m-parts-crj-series-new-jet-engine-fixes-jul-20-2018/&do=findComment&comment=3419001), so the file size and hash metadata doesn't match anymore.

@techman83, can you please purge this file from the bot's cache?

- 06501A9B-netkan-AirplanePlus.zip

**Comment by politas** [comment]
Purged
