### ISSUE TITLE
Kopernicus not updating to 1.4.5-4 from 1.4.5-3

### ISSUE THREAD

**Issue by JoESmash** [KSP-CKAN/NetKAN#6672]
See title. Kopernicus isn't being updated for some reason....

Also it says on the top of your page after I logged in:

The password you provided has been reported as compromised due to re-use of that password on another service by you or someone else. GitHub has not been compromised directly. To increase your security, please change your password as soon as possible.

Read our documentation on safer password practices. See our blog for more details.

Has my password really been compromised and being used by hackers and I need to change my passwords everywhere? Or is this just your site's dumb way of saying I need a stronger password that has a symbol in it...?

**CKAN Version:** 

**KSP Version:** 

**Operating System:** 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

**Affected mods and mod versions:**

Problem
-------

**What steps did you take in CKAN?**

**What did you expect to happen?**

**What happened instead?**

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
It is being updated. The previous version was indexed 5 hours ago. Please be patient.
As for the password stuff, the CKAN team has nothing to do with that. Try GitHub:
https://github.com/contact
