### ISSUE TITLE
DependencyNotSatisfiedKraken when trying to install a mod

### ISSUE THREAD

**Issue by tommyb554** [KSP-CKAN/NetKAN#6676]
Background
----------

**CKAN Version:** 
1.25.2

**KSP Version:** 
1.4.4.2215

**Operating System:** 
windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
~~yes but deleted when ckan was installed~~
- Manually installed ModuleManager
- Possibly other manually installed mods (unknown)
- As initially stated, "deleted" something when starting to use CKAN (unspecified, possibly one or more manually installed mods)

**Affected mods and mod versions:**
everything

Problem
-------

**What steps did you take in CKAN?**
tried to install mods

**What did you expect to happen?**
 mod install

**What happened instead?**
error

**Screenshots:**

**CKAN error codes (if applicable):** 

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
CKAN.DependencyNotSatisfiedKraken: Exception of type 'CKAN.DependencyNotSatisfiedKraken' was thrown.
   at CKAN.RelationshipResolver.ResolveStanza(IEnumerable`1 stanza, SelectionReason reason, RelationshipResolverOptions options, Boolean soft_resolve, IEnumerable`1 old_stanza)
   at CKAN.RelationshipResolver.Resolve(CkanModule module, RelationshipResolverOptions options, IEnumerable`1 old_stanza)
   at CKAN.RelationshipResolver.AddModulesToInstall(IEnumerable`1 modules)
   at CKAN.MainModList.ComputeConflictsFromModList(IRegistryQuerier registry, IEnumerable`1 change_set, KspVersionCriteria ksp_version)
   at CKAN.Main.<UpdateChangeSetAndConflicts>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKAN.Main.<ModList_CellValueChanged>d__240.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by HebaruSan** [comment]
Which mod are you trying to install?

**Comment by tommyb554** [comment]
every mod, also kicks up the same error trying to update any

**Comment by HebaruSan** [comment]
OK, which mods do you already have installed?

**Comment by tommyb554** [comment]
![image](https://user-images.githubusercontent.com/42352000/44048584-a7d4ad1e-9f29-11e8-8d98-06a34ddcb213.png)

**Comment by HebaruSan** [comment]
OK, what is the exact nature of the changes you made "yes but deleted when ckan was installed"?
I notice that ModuleManager is not listed among your installed mods, but it's probably a requirement for several. Did you by any chance have a manual install of ModuleManager, and then remove it?

**Comment by HebaruSan** [comment]
What is the exact nature of the changes you made "yes but deleted when ckan was installed"?

**Comment by tommyb554** [comment]
when ckan was installed i deleted all the mods and installed them again through ckan

**Comment by HebaruSan** [comment]
... except for ModuleManager. Any other exceptions?

**Comment by tommyb554** [comment]
when ckan was installed i deleted all the mods and installed them again through ckan

**Comment by HebaruSan** [comment]
Except that you just said:

> moduleManager is installed but is not managed and has AD in the installed columns

... so you did not delete ModuleManager and install it again through CKAN.

**Comment by politas** [comment]
Are there some mods that have a version requirement for ModuleManager, and if so, would that fail on an AD ModuleManager?

**Comment by HebaruSan** [comment]
I believe AD mods are considered to satisfy all version requirements:

https://github.com/KSP-CKAN/CKAN/blob/b57eb90d0b2f905fb6ac1c077b9d2ca4ceaa9eb4/Core/Types/CkanModule.cs#L79-L83

**Comment by HebaruSan** [comment]
Looks like we're not going to get enough info to reproduce.
