### ISSUE TITLE
What's the right way to maintain RealHeat (and other mods)

### ISSUE THREAD

**Issue by rsparkyc** [KSP-CKAN/NetKAN#6692]
Background
----------

**CKAN Version:** 1.25.3

**KSP Version:**  1.4.5

**Operating System:** Windows

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** yes

**Affected mods and mod versions:** RealHeat

Problem
-------

**What steps did you take in CKAN?**
View the RealHeat mod 

**What did you expect to happen?**
it would show a min ksp version of 1.4.5

**What happened instead?**
the min version is 1.4.3

I'm asking this because i'm trying to figure out what the _right_ wait to properly maintain this on ckan is.  https://github.com/KSP-CKAN/NetKAN/pull/6573 said that RealHeat does not have a .version file, however there is one here: https://github.com/KSP-RO/RealHeat/blob/master/RealHeat/RealHeat.version

What is the preferred method for maintaining a mod on ckan?  I've seen at least 2 approaches, having a .netkan file somewhere in the project, or having a .version file.  Is it also possible to just add the .netkan file as a PR to NetKAN? Is the .version file only used if you're using AVC?  I'm trying to understand what I need to do to make this a bit more seamless when I updated the versions of mods.

**Comment by HebaruSan** [comment]
Good question. Now that it has a .version file, we can tell the CKAN bot to get the versioning info out of it. I'll start a pull request showing how to do that...

**Comment by rsparkyc** [comment]
Ok, it looks like RealHeat is still showing a max ksp version of 1.4.3, even though in the .version file in the zip package, it's defined as 1.4.99.
