### ISSUE TITLE
Recommendations don't handle conflicts

### ISSUE THREAD

**Issue by 4x4cheesecake** [KSP-CKAN/NetKAN#6709]
Background
----------

**CKAN Version:** 
1.25.3

**KSP Version:** 
1.4.2 (+MH)

**Operating System:** 
Win10 Pro x64

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No, tested it with a fresh install

**Affected mods and mod versions:**
Environmental Visual Enhancement (EVE) 1.4.2-2 and (Stock Visual Enhancement(SVE) 1.3.0.4

Problem
-------

**What steps did you take in CKAN?**
I've tried to install EVE and SVE with High Res-Textures, so I selected them and hit 'Apply changes'. 
When the 'recommend mods' window appears, CKAN listed 'EVE Stock Planet Config files' there. Well, I know it is not possible to use them along with SVE but I got curious and tried it anyway.

**What did you expect to happen?**
Since I know that this configuration will conflict, I expected 2 possible things: 
1) CKAN installs everything and SVE will not work properly
or
2) CKAN will detect the conflict between SVE and EVE Stock Planet Configs

**What happened instead?**
I got an error message about the conflict between SVE High Res Textures and SVE (that doesn't make any sense since SVE requires these textures). The conflict exists between SVE and EVE Stock Planet Configs

**Screenshots:**

![image](https://user-images.githubusercontent.com/40007416/45244224-38897980-b2f7-11e8-8ad8-79bab97168a2.png)

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
The relevant metadata looks OK:

- [EVE](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/EnvironmentalVisualEnhancements.netkan) recommends EnvironmentalVisualEnhancements-Config, which is a virtual module provided by other modules, not a specific one
- [The stock config module](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/EnvironmentalVisualEnhancements-HR.netkan) provides and conflicts with EnvironmentalVisualEnhancements-Config, as it should
- [SVE](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/StockVisualEnhancements.netkan) also provides and conflicts with EnvironmentalVisualEnhancements-Config, as it should

Maybe EVE should use a "depends" relationship instead. I wonder why it doesn't...

**Comment by HebaruSan** [comment]
Answer to previous question is in #5969, making the config optional allows a user the option of manually installing configs that aren't indexed on CKAN.

I wonder whether we check the recommended list for conflicts with mods that are already chosen for install...

**Comment by HebaruSan** [comment]
I think that's it. Suggestions and recommendations are just displayed as they appear in the metadata with no filtering:

https://github.com/KSP-CKAN/CKAN/blob/e825bdef9d52a4117e37acf6b6b74da216ee4567/GUI/MainInstall.cs#L118-L133

In addition to the problem described in this issue, that also means that a mod can recommend other mods that conflict with one another, and they'll both default to being installed, which will then cause an error if the user clicks Continue without de-selecting one. It should be safe to accept the defaults presented to the user without modification.

Depends relationships, unlike recommends or suggests, have special logic for "provides" that only allows the user to choose one of the options.

This is similar to KSP-CKAN/CKAN#965 and KSP-CKAN/CKAN#2268 in that recommends and suggests should be handled in Core but are instead implemented separately in each UI.

Might make sense to check for conflicts here:

https://github.com/KSP-CKAN/CKAN/blob/e825bdef9d52a4117e37acf6b6b74da216ee4567/GUI/MainInstall.cs#L304-L308

**Comment by 4x4cheesecake** [comment]
If you consider some code changes and want another case for testing purposes:
I've noticed the same issue with GPP, GPP HighRes Clouds and GPP LowRes Clouds as well. Trying to install both texture versions will result in conflict but if you just marked one to be installed, the other one will be listed as **suggested**. 
It is getting a bit more tricky in this case because none of them is actually required to run GPP, so if you choose to install just GPP, both cloud textures will be listed as '**suggested**':
![image](https://user-images.githubusercontent.com/40007416/45260333-048c8200-b3e5-11e8-808b-56727ca9d7ea.png)
I would suggest to highlight those conflicts like it is done in the 'main view':
![image](https://user-images.githubusercontent.com/40007416/45260344-84b2e780-b3e5-11e8-8945-22127d1e8c0f.png)

**Comment by HebaruSan** [comment]
Just noticed a minor error in the problem report:

> I got an error message about the conflict between SVE High Res Textures and SVE (that doesn't make any sense since SVE requires these textures). The conflict exists between SVE and EVE Stock Planet Configs

The reported conflict *is* between SVE (StockVisualEnhancements) and EVE Stock Planet Configs (EnivronmentalVisualEnhancements-HR):

![image](https://user-images.githubusercontent.com/1559108/45268389-05530180-b441-11e8-8771-fba8102d73bd.png)

So the error message does make sense.
