### ISSUE TITLE
Overlapping current NetKAN's for "Extended information about scientific experiments in VAB"

### ISSUE THREAD

**Issue by Jacke4913** [KSP-CKAN/NetKAN#6716]
CKAN version 1.25.3
KSP version 1.4.5
Operating System: all

NetKAN's:

"1.3.1.2 NetKan" appears to provide several versions from Spacedock up to latest 1.3.1.2
default download is "F6A972A9-ExtendedInfoSciExp-1-1.3.1.2.zip"
https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/ExtendedInfoSciExp.netkan

"1.3.1.1 NetKan" appears to provide 2 versions from Spacedock, 1.3.1.1 and 1.0
default download is "F6A972A9-ScienceSituationInfo-1.3.1.1.zip" 
https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/ScienceSituationInfo.netkan

Note:

Upstream Spacedock current version 1.3.1.2 has 2 typos in its .version file, "SituationModuleInfo.version": 
1. Missing a colon ':' after the second "MINOR"
2. Says mod version is 1.3.1.1

Missing colon typo also exists in upstream version 1.3.1.1.  Reported to upstream in its KSP forums topic, most recently here:

https://forum.kerbalspaceprogram.com/index.php?/topic/121633-131-extended-information-about-scientific-experiments-in-vab-30-jan-2018/&page=2&tab=comments#comment-3455902

Description:

In the CKAN display after refreshing from the default repository, there are two entries with "name" being the same:  "Extended information about scientific experiments in VAB"

The first lists versions up to 1:1.3.1.2 and downloads "F6A972A9-ExtendedInfoSciExp-1-1.3.1.2.zip"

The second lists versions 1.3.1.1 and 1.0, and downloads "F6A972A9-ScienceSituationInfo-1.3.1.1.zip"

Once either is downloaded, both list the same contents in "GameData/OLDD/SituationModuleInfo/" and the other can't be downloaded until the cache download is removed and CKAN client restarted.

It appears the 1.3.1.2 NetKAN did not replace the 1.3.1.1 NetKAN but was added.

**Comment by HebaruSan** [comment]
Confirmed these modules both reference the same `$kref` (`#/ckan/spacedock/1008`). The mod is maintained by @linuxgurugamer, who also worked on both of these netkans. Assigned to him for fix, to make sure the conflict is resolved as he prefers.

**Comment by HebaruSan** [comment]
... time's up! Did it to as *I* prefer. :grin: 
SituationModuleInfo is cleaned up and has all the versions backported to it.
ExtendedInfoSciExp is frozen.
