### ISSUE TITLE
Kerbalism has misordered versions in CKAN and other version issues

### ISSUE THREAD

**Issue by Jacke4913** [KSP-CKAN/NetKAN#6724]
CKAN version 1.25.3
KSP version 1.4.5
Operating System: Windows 10 1803

Mod: Kerbalism
Current Mod Maintainer: KSP forum user N70 and others
Source: https://github.com/steamp0rt/Kerbalism/
Download: https://spacedock.info/mod/1774/Kerbalism/

CKAN metadata:

several .ckan in a directory:
https://github.com/KSP-CKAN/CKAN-meta/tree/master/Kerbalism/

Issue: Kerbalism has misordered versions in CKAN and other version issues

Other issues include a CKAN download marked as being for KSP 1.4.5 is actually for KSP 1.3.1

Description:

Saw this post in the KSP topic for Kerbalism about a player running KSP 1.4.5 getting a KSP 1.3.1 version of Kerbalism as the default from CKAN.

https://forum.kerbalspaceprogram.com/index.php?/topic/172400-131145-kerbalism-v190/&page=35&tab=comments#comment-3458441

I took a look at Kerbalism in CKAN and with KSP compatibility set to KSP 1.4 and 1.3, saw this list of versions:

BP-1.4.3          KSP 1.3.0 - 1.3.1
BP-1.4.2          KSP 1.3.0 - 1.3.1
BP-1.4.1.4       KSP 1.3.0 - 1.3.1
BP-1.4.1.3       KSP 1.3.0 - 1.3.1
1.9.0.0             KSP 1.4.0 - 1.4.5
1.8.0.0             KSP 1.4.0 - 1.4.5
1.7.0.0             KSP 1.4.0 - 1.4.3
1.6.0.0             KSP 1.4.0 - 1.4.3
1.6.0                KSP 1.4.0 - 1.4.3
1.5.1                KSP 1.4.0 - 1.4.3
1.5.0                KSP 1.4.0 - 1.4.3
....

Checking on Kerbalism's GitHut and Spacedock pages, I see Kerbalism offered downloads for both KSP 1.3.x and 1.4.x versions of its recent releases (see links for GitHub and Spacedock above).  The most recent is 1.9.0.0 for KSP 1.4.5 and BP-1.9.0.0 for KSP 1.3.1

I obtained the .zip files for Kerbalism from both CKAN and GitHub directly.

For CKAN's "BP-1.4.3  KSP 1.3.0 - 1.3.1", download was AC8B14B6-Kerbalism-BP-1.4.3.zip.  Kerbalism.version file attached as AC8B14B6-Kerbalism-BP-1.4.3.zip--Kerbalism.version.

For CKAN's "1.9.0.0   KSP 1.4.0 - 1.4.5", download was 2B6BA28E-Kerbalism-1.9.0.0.zip.  Kerbalism.version file attached as 2B6BA28E-Kerbalism-1.9.0.0.zip--Kerbalism.version.

Both of these .version files claim the install is for KSP 1.3.1.

GitHut has download Kerbalism-1.9.0-1.3.1.zip
Kerbal.version file attached as Kerbalism-1.9.0-1.3.1.zip--Kerbalism.version.

GitHut also has download Kerbalism-1.9.0-1.4.5.zip.  
Kerbal.version file attached as Kerbalism-1.9.0-1.4.5.zip--Kerbalism.version.

The .version files claim they are for KSP 1.3.1 and 1.4.5 respectively.

Sizes of Kerbalism.dll from respective downloads:

AC8B14B6-Kerbalism-BP-1.4.3.zip--Kerbalism.version     292,352
2B6BA28E-Kerbalism-1.9.0.0.zip--Kerbalism.version        349,696
Kerbalism-1.9.0-1.3.1.zip                                                 349,696
Kerbalism-1.9.0-1.4.5.zip                                                 350,208

It appears the CKAN download for KSP 1.4.5, Kerbalism's 1.9.0.0, is the KSP 1.3.1 version instead.

Zip containing the 4 Kerbalism.version files attached.

[20180926a-Kerbalism.version.zip](https://github.com/KSP-CKAN/NetKAN/files/2422574/20180926a-Kerbalism.version.zip)

**Comment by Jacke4913** [comment]
I have heard that it is problematic to have Spacedock offer up versions of a mod compiled for different KSP versions.

Along with other measures to resolve these issues, I wonder if adopting a new Kerbalism version numbering scheme could help (along with appropriate use of epoch numbers).  I got the idea from Kopernicus's version scheme.

Versions 1.4.5.build for KSP 1.4.5
Versions 1.3.1.build for KSP 1.3.1

New build X comes out, compile version 1.4.5.X for KSP 1.4.5 and 1.3.1.X for KSP 1.3.1.

I wonder if with proper .version files, CKAN receiving the information from Spacedock could automatically keep things straight.

Don't know if this could be made to work, as I don't know the details of the protocol between Spacedock and CKAN and what CKAN does, besides it extracting the .version file and using it.

**Comment by HebaruSan** [comment]
The .version file for the supposedly 1.3.1 backport says:

```json
  "URL": "http://ksp-avc.cybutek.net/version.php?id=559",
```

... [which in turn says](http://ksp-avc.cybutek.net/version.php?id=559):

```json
{"NAME":"Kerbalism","URL":"http://ksp-avc.cybutek.net/version.php?id=559","DOWNLOAD":"https://spacedock.info/mod/1749/Kerbalism","CHANGE_LOG_URL":"https://spacedock.info/mod/1749/Kerbalism","VERSION":{"MAJOR":1,"MINOR":9,"PATCH":0,"BUILD":0},"KSP_VERSION":{"MAJOR":1,"MINOR":4,"PATCH":4},"KSP_VERSION_MIN":{"MAJOR":1,"MINOR":4,"PATCH":0},"KSP_VERSION_MAX":{"MAJOR":1,"MINOR":4,"PATCH":5}}
```

So that's where it's getting 1.4 compatibility from. Updating the online .version file pointed to by `URL` allows mod authors to extend or change the game version compatibility info without requiring users to download a new copy of the mod (note that KSP-AVC also works this way). That `URL` field should point to an online .version file that's specific to the backport series, but it's currently shared with the 1.4 series.

**Comment by PiezPiedPy** [comment]
So Am I right in saying we should just have the 1.4.x versions on the current Spacedock and also start a new Spacedock Kerbalism-BP that has just the 1.3.1 Backport in it ?

**Comment by PiezPiedPy** [comment]
tbh would be good if there was a way Spacedock, AVC and CKAN could support Backports with same version numbers.

**Comment by Jacke4913** [comment]
I'm not the expert here, but I think you could do backports with the scheme I laid out in my reply to the initial post in one mod profile on both GitHub and Spacedock.  The backport and the current version have to have 2 different version numbers because they are different.  (Near 2 decades of use of Debian's apt including backports.)  You make those version numbers both relate to their difference, the KSP version number they are compiled for, and their similarity, the code release they share (obviously with condition code based on that KSP version number).

Say the next build of Kerbalism is called 191, even if there are no changes from the current, just to fix this version problem.  Then you compile

Kerbalism 1.4.5.191 for KSP 1.4.5
Kerbalism 1.3.1.191 for KSP 1.3.1

Those go on GitHub and Spacedock (which both need the version numbers in their download .zip filenames).  On CKAN, I think a properly crafted .netkan on getting the info from Spacedock would take their Kerbalism.version files and push out

Kerbalism 1:1.4.5.191 for KSP 1.4.0 to 1.4.9
Kerbalism 1:1.3.1.191 for KSP 1.3.0 to 1.3.1

The epoch numbers ("1:") are also used in Debian.  It places them as more recent than all the previous epoch releases.

That way, on CKAN, if it's set to have KSP 1.3 as compatible, it gets Kerbalism 1:1.3.1.191.

If it's set to have KSP 1.4 as compatible, even if it also has KSP 1.3 as compatible, it gets Kerbalism 1:1.4.5.191.

Next Kerbalism build is 192.  Put 1.4.5.192 and 1.3.1.192 in the respective .version files and onto Spacedock.  Spacedock tells CKAN.  Via the .netkan's on CKAN it now offers up 1:1.4.5.192 and 1:1.3.1.192 to CKAN users.

And everyone gets the right version.

**Comment by PiezPiedPy** [comment]
That scheme would mess with the CI dev builds, probably best to have the Backports separate.
Kerbalisms versioning uses Major.Minor.Patch.Build

**Comment by Jacke4913** [comment]
I think you can still use that build system.

Think of what KSP uses.

2018 Jul 26 Thu		KSP 1.4.5.2243
2018 Jun 21 Thu		KSP 1.4.4.2215
2018 Apr 27 Fri		KSP 1.4.3.2152
2018 Mar 28 Wed		KSP 1.4.2.2110
2018 Mar 13 Tue		KSP 1.4.1.2089
2018 Mar 06 Tue		KSP 1.4.0.2077
2017 Nov 15 Wed		KSP 1.3.1.1891
2017 May 25 Thu		KSP 1.3.0.1804
2016 Dec 06 Tue		KSP 1.2.2.1622		Unity 5.4.0p4
2016 Nov 01 Tue		KSP 1.2.1.1604
2016 Oct 11 Tue		KSP 1.2.0.1586
2016 Jun 21 Tue		KSP 1.1.3.1289
2016 Apr 30 Sat		KSP 1.1.2.1260
2016 Apr 29 Fri		KSP 1.1.1.1250
2016 Apr 19 Tue		KSP 1.1.0.1230		Unity 5 & 64-bit !!!

Note the big jump in build numbers between each release.  The "missing" numbers were the development builds.

**Comment by Jacke4913** [comment]
You can either put them all on GitHub, flagging as pre-release.  And only push to Spacedock (and thus) when it's a general release build.

You can special number the general release builds, say all builds ending in '0' are general release.

So for development, you have:

192
193
194
195
196
197
198
199
201
202
203
210

That 210 is the general release build, with the non-zero ending showing it as such.

**Comment by Jacke4913** [comment]
Or you can do what sarbian does with MechJeb.  Keeps a separate repository for dev builds.  He even has it as a repository you can add to CKAN so you can use CKAN to install development MechJeb.  (Have to go into CKAN settings and add the MechJeb dev Metadata Repository by clicking on "New" and selecting it.)

And the development versions have numbers like:

2.7.4.0-803
2.7.4.0-802
2.7.4.0-801
....

with one of them eventually pushed out as the general release when appropriate.

sarbian sets up the development as separate.  Allows people to use it as a different manual or CKAN install.

**Comment by Jacke4913** [comment]
So, you could have the next Kerbalisms to fix the version numbers be:

1:1.4.5.191
1:1.3.1.191

then in a separate dev build, have

1:1.4.5.191-01
1:1.4.5.191-02

etc and 1:1.3.1.191-xx for KSP 1.3.1.  When you get a good version for release, say -07, 

1:1.4.5.191-07  on the dev track becomes 1:1.4.5.192 on the main release track

or some system like that.

I think you need to keep the backport and the current KSP release together, else you will have a major port to do on new KSP versions.  This method or some others have minor porting just to push out general releases.

Again, I think these will work.  Others will have to fill in the details of implementing this.

**Comment by PiezPiedPy** [comment]
personally I don't like the idea of merging the Major.Minor.Patch into a Build section. Also our BP port is handled automatically with CI. Not a big deal to upload the BP build to a separate Spacedock entry.
But all being said it is N70 who has the say in what happens.

**Comment by PiezPiedPy** [comment]
Would be better if Spacedock AVC and CKAN had provision for updates to backports rather than treating backports as old releases.

**Comment by Jacke4913** [comment]
That's a major feature and it may not be the right way to do things, as it would complicate KSP-AVC, Spacedock, and CKAN.  And backports should be able to be done with appropriate version numbers (and properly crafted .version files) of the mod releases without any changes to the 3 of them.  That's why I outlined a few ways above.

I also did that because of the consequences of doing it in a different way, like separate mods for Kerbalism and Kerbalism-backports, which aren't necessarily understood until it's taken through a major KSP release.    sarbian separates MechJeb into main release and development versions and that may be the better way to split, if you feel you have to split.  But with the right system for version numbers, it should be possible to handle development, main release, and backports all together.

Backports are a recent phenomenon (last 10 to 15 years) and an extension that occurs when more than one version of the major system (Debian or KSP major release) is in use.  How Debian uses them now has evolved into this from a slightly different method back around 8 years ago.  Debian apt really didn't change, just how to tell it about the existence and priority of backports.   The standard package info (inside the software package, the .deb file) on which Debian release, the package version number, and its versioned dependencies is all the info Debian apt needs to pick the right version to install.

Overall, Debian has more knobs and whistles than is needed for Spacedock and CKAN.  But the ideas around it can help figure things out for Spacedock and CKAN.

**Comment by Jacke4913** [comment]
This issue still is catching some users.  Like this one on the KSP forums who's CKAN gave him Kerbalism BP-1.4.3 instead of 2.1.2.

https://forum.kerbalspaceprogram.com/index.php?/topic/172400-literally-every-ksp-version-since-13-kerbalism-v212/&page=50&tab=comments#comment-3535160

Currently the list of Kerbalism versions in CKAN looks like this.

`BP-1.4.3     KSP 1.3.0 - 1.3.1`
`BP-1.4.2     KSP 1.3.0 - 1.3.1`
`BP-1.4.1.4   KSP 1.3.0 - 1.3.1`
`BP-1.4.1.3   KSP 1.3.0 - 1.3.1`
`2.1.2        KSP 1.3.1 - 1.6.99`
`2.1.1        KSP 1.3.1 - 1.6.99`
`2.1.0.0      KSP 1.3.1 - 1.5.9`
`2.0.0.0      KSP 1.3.1 - 1.5.1`
`1.9.0.0      KSP 1.3.1 - 1.5.9`
and so on.

**Comment by HebaruSan** [comment]
The BP-* versions were de-indexed in KSP-CKAN/CKAN-meta#1411.
Kerbalism since 2.1.1 seems to have released one version with broad support rather than individual backports. Is this issue resolved?

![image](https://user-images.githubusercontent.com/1559108/60684065-23379a00-9e8b-11e9-9292-be8e199a414c.png)

**Comment by Jacke4913** [comment]
I'll confirm in the next few days.  If the BP-* versions were de-indexed and things appear as they do for you, that should be good.
