### ISSUE TITLE
Mods with incorrect homepages

### ISSUE THREAD

**Issue by Artemonim** [KSP-CKAN/NetKAN#6734]
Background
----------
**CKAN Version:** 1.25.3

Problem
-------

- [x] The right homepage for "BurnTogether Continued" mod is [this](https://forum.kerbalspaceprogram.com/index.php?/topic/178156-14x-bdarmory-continued-v1222a-882018-vessel-mover-camera-tools-bdmk22-destruction-effects-burn-together)
- [x] The right homepage for "Civilian Population" mod is [this](https://forum.kerbalspaceprogram.com/index.php?/topic/162204-145-civilian-population-released-07042018)
- [x] The right homepage for "Distant Object Enhancement" mod is [this](https://forum.kerbalspaceprogram.com/index.php?/topic/89214-13x-14x-distant-object-enhancement-bis-v191-8-july-2017)
- [x] The right homepage for "Distant Object Enhancement default config" mod is [this](https://forum.kerbalspaceprogram.com/index.php?/topic/89214-13x-14x-distant-object-enhancement-bis-v191-8-july-2017)
- [x] The right homepage for "Earn Your Stripes" mod is [this](https://forum.kerbalspaceprogram.com/index.php?/topic/161790-143-earn-your-stripes-150-110518-allowing-kerbals-to-earn-an-orange-suit-since-2017).
- [x] The right homepage for "Stock Visual Enhancements" mod is [this](https://forum.kerbalspaceprogram.com/index.php?/topic/143288-ksp-142-131-stock-visual-enhancements-v1304-05-april-2018)
- [x] The right homepage for "Stock Visual Enhancements-High Res Textures" mod is [this](https://forum.kerbalspaceprogram.com/index.php?/topic/143288-ksp-142-131-stock-visual-enhancements-v1304-05-april-2018)
- [x] The right homepage for "Stock Visual Enhancements-Low Resolution Textures" mod is [this](https://forum.kerbalspaceprogram.com/index.php?/topic/143288-ksp-142-131-stock-visual-enhancements-v1304-05-april-2018)
- [x] The right homepage for "Stock Visual Enhancements-Medium Resolution Textures" mod is [this](https://forum.kerbalspaceprogram.com/index.php?/topic/143288-ksp-142-131-stock-visual-enhancements-v1304-05-april-2018)
- [x] The right homepage for "Stock Visual Terrain" mod is [this](https://forum.kerbalspaceprogram.com/index.php?/topic/143828-ksp-142-stock-visual-terrain-v214-01-april-2018)
- [x] The right homepage for "Eva Follower" mod is [this](https://forum.kerbalspaceprogram.com/index.php?/topic/167310-141-eva-follower/)

**Comment by HebaruSan** [comment]
Would you be interested in fixing any of these yourself? You can try it by clicking the mod at http://status.ksp-ckan.org/ to open the netkan, then click the pencil icon to edit, make your changes, then use the box at the bottom to start a pull request.

**Comment by Artemonim** [comment]
> Would you be interested in fixing any of these yourself? You can try it by clicking the mod at http://status.ksp-ckan.org/ to open the netkan, then click the pencil icon to edit, make your changes, then use the box at the bottom to start a pull request.

Oh. Ok. I didn't now about it.
Check [my try](https://github.com/KSP-CKAN/NetKAN/pull/6736), please.

**Comment by HebaruSan** [comment]
Fixed in:

- #6736
- #6737
- #6738
- #6739
- #6740
- #6741
- #6742
- #6743
- #6744
- #6745
- #6746
