### ISSUE TITLE
Mods with no longer exist homepages.

### ISSUE THREAD

**Issue by Artemonim** [KSP-CKAN/NetKAN#6735]
Background
----------

**CKAN Version:** 1.25.3

Problem
-------
- [ ] The "[Engineering Tech Tree](https://forum.kerbalspaceprogram.com/threads/125055)" mod homepage is no longer exist.
- [ ] The "[Feyntera System](https://spacedock.info/mod/1764/Feyntera%20System)" mod homepage is no longer exist. Source too.

**Comment by HebaruSan** [comment]
Should both be fixed now, ETT with current forum thread, Feyntera with archive.org page.
