### ISSUE TITLE
Where is info from CKAN?

### ISSUE THREAD

**Issue by Artemonim** [KSP-CKAN/NetKAN#6756]
Background
----------

**CKAN Version:** 1.25.3

Why not all the information I can see in the CKAN application can be seen in NetKAN files?
[KIS](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/KIS.netkan) as an example.

**Comment by HebaruSan** [comment]
That's a "meta-netkan", the data is hosted elsewhere and can only be changed by the owner, in this case @ihsoft:

- https://raw.githubusercontent.com/ihsoft/KIS/master/KIS.netkan

**Comment by Artemonim** [comment]
> and can only be changed by the owner

Restricted license is about it?

**Comment by ihsoft** [comment]
@Artemonim No, the restricted license only applies to the source code and resources. The reason why KIS uses own `netkan` file is for the convenience.
