### ISSUE TITLE
MiniAirbrakes isn't in index?

### ISSUE THREAD

**Issue by Artemonim** [KSP-CKAN/NetKAN#6769]
**CKAN Version:** 1.25.3

MiniAirbrakes is shown in CKAN, but didn't in [NetKANs Index](http://status.ksp-ckan.org).

Also mod have incorrect homepage. Correct homepage is [this](https://forum.kerbalspaceprogram.com/index.php?/topic/108121-*)

**Comment by HebaruSan** [comment]
It was only hosted on KerbalStuff, which no longer exists, and it has not been re-uploaded by the author to a new host. So the netkan was renamed with a ".frozen" extension to take it out of the bot's rotation:

https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/MiniAirbrakes.frozen

All that's left now is the .ckan file:

https://github.com/KSP-CKAN/CKAN-meta/tree/master/MiniAirbrakes

The current download location is an archival one originally created by the CKAN bot.
