### ISSUE TITLE
RemoteTechRedevAntennas

### ISSUE THREAD

**Issue by yalov** [KSP-CKAN/NetKAN#6783]
@KSP-TaxiService reloaded the mod archive with fixed .version-file. 
Not sure, what NetKAN will parse it automatically.

**Comment by HebaruSan** [comment]
Thanks for the heads-up, updated the .netkan and notified the server admin to purge the bot cache.

**Comment by yalov** [comment]
KSP_VERSION_MAX = 1.99.99 but CKAN shows 1.4.9

**Comment by HebaruSan** [comment]
That's probably the bot caching. Let's see what it says after @techman83 purges it.
