### ISSUE TITLE
Tantares and tantareslv are now 1.5, but still 1.4.2 on ckan

### ISSUE THREAD

**Issue by mr-engino** [KSP-CKAN/NetKAN#6802]
Background
----------

**CKAN Version:** 1.25.3

**KSP Version:** 1.5.1.2335

**Operating System:** windows 7

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

**Affected mods and mod versions:** tantares and tantareslv

Problem
-------

tantares and tantareslv have been updated to 1.5.x, but they are still listed as 1.4.2 on ckan.

**Comment by HebaruSan** [comment]
Thanks for letting us know.
