### ISSUE TITLE
NearFutureAeronautics is not in CKAN

### ISSUE THREAD

**Issue by yalov** [KSP-CKAN/NetKAN#6814]

**Comment by HebaruSan** [comment]
[That mod can't be indexed](https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1253-woomera/&do=findComment&comment=3444356
); it bundles KerbalActuators, by Angel-125, who is on the do-not-index list.

https://github.com/KSP-CKAN/CKAN/blob/master/policy/Opt-out-list.md
