### ISSUE TITLE
[Suggestion] Highlight dependents or dependencies on click

### ISSUE THREAD

**Issue by VasVadum** [KSP-CKAN/NetKAN#6825]
**CKAN Version:** 1.25.3

**KSP Version:** 1.5.1.2335

**Operating System:** Windows 10 Severely Outdated
(You can thank Microsoft for that)

**Have you made any manual changes to your GameData folder ?** 
No

Request/Suggestion:
-------

**What do you expect to happen?**
I'd like to have dependents or dependencies highlighted when I click on an item rather than switching its tab to "relationships" and hovering over each item to find out whats a dependent or whats a recommendation.  I'd like an easy way to find the dependencies and dependents when I am scrolling through my list so colorizing them when I click on one would be nice. Especially if I check, or uncheck something to be installed or removed.

If I uncheck something that is depended upon, it should turn red, and turn the dependents orange.

If I check something that is a dependent of something, it should turn orange, and mark the dependency red while marking the other things that dependency is depended upon yellow. That way you know you can uninstall the dependency if there are no more dependents.  If that makes any sense. :P

**Comment by HebaruSan** [comment]
Would that be useful in practice, though? The list of available mods can be 1000+ items long, so if you click a row, its dependencies might be dozens of screenfuls away and difficult to find in the main list.

Red is currently used for conflicts, so it's probably best not to confuse that with other usages.

![screenshot](https://user-images.githubusercontent.com/1559108/39786266-733d86b0-52e5-11e8-98e8-a64814af6108.png)

**Comment by VasVadum** [comment]
Well you don't need to use the exact colors I suggested. I just needed an easier way to find what mods required other mods and what mod dependencies were no longer needed after I uninstalled a mod. I tend to sort my list with my installed items at the top, and even when I'm not looking for mods I only have installed mods showing up.

**Comment by HebaruSan** [comment]
I think APT sets a flag like `auto-installed`, without regard to which mod had the dependency. Then after removing mods, check whether any auto-installed mods have no remaining depending mods, and remove them as well. That should be feasible for CKAN as well.
