### ISSUE TITLE
Near Future IVA Prop

### ISSUE THREAD

**Issue by yalov** [KSP-CKAN/NetKAN#6840]
0.4.4 is some fake version (wrong written 0.3.4?)
0.3.5 is the last one
 https://github.com/ChrisAdderley/NearFutureProps/releases

**Comment by HebaruSan** [comment]
0.4.4 is unfortunately the actual version given to that release on GitHub by the author:

![image](https://user-images.githubusercontent.com/1559108/48396367-130f5680-e712-11e8-838b-a166e7143e8d.png)
