### ISSUE TITLE
Omega482 mods

### ISSUE THREAD

**Issue by yalov** [KSP-CKAN/NetKAN#6846]
https://spacedock.info/profile/Omega482
Half of them have the CKAN badge, but I didn't find them on the ckan

**Comment by HebaruSan** [comment]
Yeah, that part of SpaceDock isn't working, see KSP-SpaceDock/SpaceDock#188.

Feel free to make your own pull requests if you notice ones that are missing. Otherwise I do catch-up PRs every couple of weeks.

- KSP-CKAN/NetKAN#6686
- KSP-CKAN/NetKAN#6705
- KSP-CKAN/NetKAN#6788
- KSP-CKAN/NetKAN#6827
