### ISSUE TITLE
SXTContinued wrong version installed for 1.3.1

### ISSUE THREAD

**Issue by ericfriesen** [KSP-CKAN/NetKAN#6848]
Background
----------

**CKAN Version:** 
1.25.3

**KSP Version:** 
1.3.1.1891

**Operating System:** 
Windows 10 Professional x64 v1809

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

**Affected mods and mod versions:**
SXTContinued

Problem
-------

**What steps did you take in CKAN?**
Install 1.3.1 compatible version for SXTContinued

**What did you expect to happen?**
Have version 0.3.23.1 installed

**What happened instead?**
Version 0.3.23.5 was installed

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
Well it looks like the metadata is fine.
Any chance you added 1.4 as a compatible game version?

https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions

**Comment by ericfriesen** [comment]
Tried with freshly downloaded 1.3.1 and latest CKAN 1.25.3  installed only SXT continued and still installs and what looks like 0.3.23.5, but it is in fact 0.3.23.1, verified by comparing hashes of ModuleBounce.dll.
Error is in the .version file with SXTContinued, so not a CKAN problem. Closing and thank you for your time.
