### ISSUE TITLE
ksp-ckan.org domain expired?

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN#6856]
Problem
-------

**What steps did you take?**
Go to https://ci.ksp-ckan.org/job/NetKAN/7841/

Or http://status.ksp-ckan.org

**What did you expect to happen?**
Page to load with outcome of pull request test scripts or status

**What happened instead?**

```
This site can’t be reached ci.ksp-ckan.org’s server IP address could not be found.
Try:

Checking the connection
Checking the proxy, firewall, and DNS configuration
Running Windows Network Diagnostics
ERR_NAME_NOT_RESOLVED
```

`wget` says 

> wget: unable to resolve host address 'ci.ksp-ckan.org'

@politas @techman83 @Olympic1 @dbent, I think the domain name has expired.

**Comment by dbent** [comment]
Whelp, it's gone now.

```
> whois ksp-ckan.org
Domain Name: KSP-CKAN.ORG
Registry Domain ID: D174543473-LROR
Registrar WHOIS Server: whois.namesilo.com
Registrar URL: www.namesilo.com
Updated Date: 2018-11-21T01:27:42Z
Creation Date: 2014-11-20T15:19:35Z
Registry Expiry Date: 2019-11-20T15:19:35Z
Registrar Registration Expiration Date:
Registrar: Namesilo, LLC
Registrar IANA ID: 1479
Registrar Abuse Contact Email: abuse@namesilo.com
Registrar Abuse Contact Phone: +1.4805240066
Reseller:
Domain Status: clientHold https://icann.org/epp#clientHold
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Domain Status: autoRenewPeriod https://icann.org/epp#autoRenewPeriod
Registrant Organization: See PrivacyGuardian.org
Registrant State/Province: AZ
Registrant Country: US
Name Server: NS-1526.AWSDNS-62.ORG
Name Server: NS-1563.AWSDNS-03.CO.UK
Name Server: NS-666.AWSDNS-19.NET
Name Server: NS-383.AWSDNS-47.COM
DNSSEC: unsigned
URL of the ICANN Whois Inaccuracy Complaint Form https://www.icann.org/wicf/)
>>> Last update of WHOIS database: 2018-11-21T04:08:01Z <<<

For more information on Whois status codes, please visit https://icann.org/epp

Access to Public Interest Registry WHOIS information is provided to assist persons in determining the contents of a domain name registration record in the Public Interest Registry registry database. The data in this record is provided by Public Interest Registry for informational purposes only, and Public Interest Registry does not guarantee its accuracy. This service is intended only for query-based access. You agree that you will use this data only for lawful purposes and that, under no circumstances will you use this data to (a) allow, enable, or otherwise support the transmission by e-mail, telephone, or facsimile of mass unsolicited, commercial advertising or solicitations to entities other than the data recipient's own existing customers; or (b) enable high volume, automated, electronic processes that send queries or data to the systems of Registry Operator, a Registrar, or Afilias except as reasonably necessary to register domain names or modify existing registrations. All rights reserved. Public Interest Registry reserves the right to modify these terms at any time. By submitting this query, you agree to abide by this policy.

The Registrar of Record identified in this output may have an RDDS service that can be queried for additional information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
```

**Comment by HebaruSan** [comment]
I assume this will also break SpaceDock's web hooks.

**Comment by politas** [comment]
I'm pretty sure @pjf was maintaining the domain

**Comment by techman83** [comment]
I think @AlexanderDzhoganov may have the domain still. I don't think we ever managed to sort the transfer.

**Comment by HebaruSan** [comment]
Netkan pull request validation doesn't seem to be running at all anymore, see #6859. This violates the spirit of CKAN's previous commitments to the community made in various highly contentious conversations (#1761, #1793). The current state isn't viable long-term.

Brainstorming fixes, does anyone already own a domain that could have some of this stuff moved to it? I.e., status.ksp-ckan.mysite.org / ci.ksp-ckan.mystuff.net? Presumably the host computer is still there and the various web hooks could be pointed to a new location.

**Comment by techman83** [comment]
I own a domain and have access to the infrastructure. I'll shift some stuff around.

**Comment by techman83** [comment]
Well it kinda works, even with the busted URL. Update jenkins, so had to refresh the container. Last one fails because of linting errors. But it works :man_shrugging: 

The url thing was always painful from memory. I'll have a look when I can dedicate more than a coffee break to it :P

**Comment by techman83** [comment]
Yeah, internally it's still redirecting to ci.ksp-ckan.org. I haven't yet stumbled on the thing I need to tweak to make it let go of the old domain. Java apps and reverse proxies :roll_eyes:

**Comment by pjf** [comment]
Just chiming in (a touch late) confirm that to the best of my knowledge, @AlexanderDzhoganov was the domain holder.

Thank you all *so much* for your incredible work! ♥

**Comment by techman83** [comment]
@HebaruSan - figured it out. It was the OAuth configuration in GitHub that needed updating. That link seems to be working for me now.

**Comment by politas** [comment]
Well, it's gone, anyway. I've registered ckan.games for us to use.  We need a host list somewhere.

**Comment by politas** [comment]
Ah, should have refreshed this page.

**Comment by politas** [comment]
I was considering using the .space TLD, too.

**Comment by politas** [comment]
Well, I guess I will hang on to ckan.games as a backup.

**Comment by HebaruSan** [comment]
Hmm, I'm still getting 404's...

**Comment by techman83** [comment]
Ahh, you're not logged in. Might be a Jenkin's bug that isn't redirecting you to the login page first?

**Comment by HebaruSan** [comment]
I just logged in, and it still says:

> HTTP ERROR 404
> Problem accessing /job/NetKAN/7849/. Reason:
> 
>     Not Found
> Powered by Jetty:// 9.4.z-SNAPSHOT

**Comment by V1TA5** [comment]
ill check this out on the production system.

**Comment by HebaruSan** [comment]
Still having that problem with the CI. Any chance of a fix?

![image](https://user-images.githubusercontent.com/1559108/49692429-724d6480-fb20-11e8-9060-73efd09c2613.png)

**Comment by V1TA5** [comment]
Hi,
can someone clearify if this has anything to do with spacedock?

**Comment by HebaruSan** [comment]
@V1TA5, SpaceDock is affected by this problem but is not the cause, and there are other effects that aren't related to SpaceDock. If you change ksp-ckan.org to ksp-ckan.space in the notify-url setting, that should take care of the SpaceDock related piece.

**Comment by techman83** [comment]
@HebaruSan can you check now? They dropped a new version of Jenkins and now I'm able to view jobs without being logged in.

**Comment by DasSkelett** [comment]
Yep, works again for me :+1:

**Comment by HebaruSan** [comment]
Yup, all fixed now, thanks!
Status page and CI are now functional, SpaceDock may or may not be but either way doesn't depend on CKAN team. Closing this as fixed. :)

**Comment by HebaruSan** [comment]
I think it would have to be somebody from the admin team. I can't edit that.

https://github.com/orgs/KSP-CKAN/teams/admin

**Comment by DasSkelett** [comment]
Oh, okay.
I can't open your link, I'm getting a 404 (as on all ksp-ckan/teams/* link I tried to open yet...).

**Comment by techman83** [comment]
Fixed!
