### ISSUE TITLE
Terras Ignotas has incorrect Max KSP version

### ISSUE THREAD

**Issue by DeltaDizzy** [KSP-CKAN/NetKAN#6868]
**CKAN Version:** 
1.25.3

**KSP Version:** 
1.3.1.1891 and 1.5.1

**Operating System:** 
Windows 10

**Affected mods and mod versions:**
Terras Ignotas v0.1.1

Problem
-------

**What steps did you take in CKAN?**
I searched "Terr" to make Terras Ignotas appear in the list.

**What did you expect to happen?**
I was looking to make sure everything was correct, the Max KSP version was supposed to be 1.5.1.

**What happened instead?**
The Max KSP version was 1.3.1.

**Screenshots:**
![CKAN Screenshot](https://cdn.discordapp.com/attachments/409435221977595924/516459753002500096/Screenshot_845.png)

This is backed up by someone with 1.5.1 trying to access it.
![CKAN 1.5](https://media.discordapp.net/attachments/402245592165646336/516468632503713792/well.PNG)

**Comment by HebaruSan** [comment]
That's coming from the remote version file:
http://ksp-avc.cybutek.net/version.php?id=548
Try fixing that.

**Comment by DeltaDizzy** [comment]
It's fixed on the repo now.

**Comment by HebaruSan** [comment]
No, it's not: http://ksp-avc.cybutek.net/version.php?id=548

**Comment by DeltaDizzy** [comment]
well I just revalidated the netkan using the merged version, and I saw it print `id=548`, even though the repo says the id is 592. I have no idea where it's getting 548 from.
https://github.com/KSP-DDR/Terras-Ignotas/blob/e4e7c0bfc8dd71464150ccd183313a643caeb366/Release/GameData/TerrasIgnotas/Versioning/Terras-Ignotas.version#L1-L10

**Comment by HebaruSan** [comment]
548 is in the version file in the download.
