### ISSUE TITLE
RO/RSS netkan help

### ISSUE THREAD

**Issue by raidernick** [KSP-CKAN/NetKAN#6900]
I'm looking for help on how to change the RO netkan file depends section. I am making a release that supports both ksp 1.3.1 and 1.4.5. The issue is that FerramAerospaceResearch stops at a version for 1.3.1 and FerramAerospaceResearchContinued starts at 1.4.5 and nothing earlier. I want to add both of these to depends but have the old FAR install only when you are using 1.3.1 and the new far if you are using 1.4.5 or later, NEVER both at the same time. How do I go about doing this?

https://github.com/KSP-RO/RealismOverhaul/blob/e3177bd12811218f4826fa2bdc493fcdd7899ede/RealismOverhaul.netkan

**Comment by DasSkelett** [comment]
So I'm not really into netkan and stuff, so I might be wrong.
Both [FerramAerospaceResearch](https://github.com/KSP-CKAN/NetKAN/blob/4c4e8a71d90a0cf37dae140d506b2a923384ce72/NetKAN/FerramAerospaceResearch.netkan) and [FerramAerospaceResearch Continued](https://github.com/KSP-CKAN/NetKAN/blob/994f2c7a49a0800e50c22019ca04819575a671fa/NetKAN/FerramAerospaceResearchContinued.netkan) provide FAR.
So if you replace "FerramAerospaceResearchContinued" with "FAR" in your depends-section, CKAN should always install the right one for the current KSP version.
