### ISSUE TITLE
Tundra Exploration

### ISSUE THREAD

**Issue by AKCX2002** [KSP-CKAN/NetKAN#6918]
Background
----------

**CKAN Version:** 

**KSP Version:** 

**Operating System:** 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

**Affected mods and mod versions:**

Problem
-------

**What steps did you take in CKAN?**

**What did you expect to happen?**

**What happened instead?**

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by AKCX2002** [comment]
Tundra Exploration
1.5.1
Windows10

**Comment by HebaruSan** [comment]
Please edit and answer the questions.

![image](https://user-images.githubusercontent.com/1559108/50568139-54d07c80-0d13-11e9-899a-e808758349fc.png)
