### ISSUE TITLE
Netkan/CKAN meta issue with KJR

### ISSUE THREAD

**Issue by raidernick** [KSP-CKAN/NetKAN#6933]
@HebaruSan I thought I had just fixed this with KJR but apparently there is still an issue. KJR continued is supposed to provide KJR. However when I load up ckan on a 1.4.5 install, I only see the original KJR in red(for 1.3-1.3.99) and RO is not listed as compatible because of this. It appears that the provides in this case is not working. I'm not sure what the problem is and whether or not it needs to be fixed here or in the meta repo.

**Comment by HebaruSan** [comment]
That's probably the relationships tab not handling this specific case (mixture of "virtual" module and real module). Does it give you errors when actually trying to install? I get "RealismOverhaul v12.5.0 requires AdvancedJetEngine but it is not listed in the index, or not available for your version of KSP.", not anything to do with KJR.

**Comment by raidernick** [comment]
@HebaruSan it does not install no, it gives an error. Also, AJE is busted because of solver engines. For some reason the meta bot still hasn't updated to fix that for the new release for 1.4.5 I did earlier. Real Fuels should also be busted because of this but for some reason it's showing up as green despite not being listed as compatible...

**Comment by HebaruSan** [comment]
SolverEngines is in progress. Uploaded 3 hours ago, [status page](http://status.ksp-ckan.space/) says last inflated 5 hours ago. So expect that in maybe an hour or 2, 3 max?

When you say it gives an error, is it an error *about KJR*?

**Comment by raidernick** [comment]
well it's not an error so much as it just hangs and does nothing when it tries to install kjr, I have no idea what exactly it's trying to do. I don't know if it's trying to install the new or old version. It appears the meta data for it is pointing it to the old version but when it tries to download nothing happens.

**Comment by HebaruSan** [comment]
SolverEngines just updated, now I get "RealismOverhaul v12.5.0 requires RealFuels but it is not listed in the index, or not available for your version of KSP."

**Comment by HebaruSan** [comment]
No, all mods provide themselves by default, and adding it explicitly causes problems, see #6068.

**Comment by raidernick** [comment]
Ok so not sure how to fix KJR then.

As for real fuels you are correct. It is shown as good to install and all the depends are compatible with 1.4.5 but for some reason it's not showing up as compatible with 1.4.5. I have no idea what's going on there.

**Comment by HebaruSan** [comment]
The KJR thing is working now:

![image](https://user-images.githubusercontent.com/1559108/50870801-78e62a80-13b1-11e9-8c43-70df08819505.png)

(My last test was accidentally on 1.4.2, this is 1.4.5.)

**Comment by HebaruSan** [comment]
This is everything it installs if I include all recommendations and suggestions:

![image](https://user-images.githubusercontent.com/1559108/50870876-b945a880-13b1-11e9-9f37-4a3b21ba82dd.png)

**Comment by raidernick** [comment]
Wait does that mean real fuels is working for you now? Because it's still not showing up as compatible despite me still not seeing any reason why it shouldn't

**Comment by HebaruSan** [comment]
Try clicking Refresh. The latest RealFuels is marked as KSP 1.4.5 compatible:

https://github.com/KSP-CKAN/CKAN-meta/blob/master/RealFuels/RealFuels-rf-v12.7.2.ckan

**Comment by raidernick** [comment]
Ok so real fuels appears to be fine now as does AJE. The only issue left is that KJR is showing up as red because it's listing the old version instead of the virtual version. You said despite that it installs correctly for you, it doesn't for me but I may just be having a problem with mine. It would still be beneficial to see if it's possible to fix the KJR listing in RO at least to show the virtual version like FAR does as to not confuse people.

**Comment by HebaruSan** [comment]
Submitted KSP-CKAN/CKAN#2643. This should be a cosmetic issue only, with the installation still working.
