### ISSUE TITLE
Meta bot not indexing mod not sure if there is an error on my side of your side

### ISSUE THREAD

**Issue by raidernick** [KSP-CKAN/NetKAN#6935]
The meta bot is not indexing the latest release of solver engines. I released the 1.4.5 version as you know and that was indexed fine, it has been about 24 hours now and the new 1.5.1 release is not being indexed, I'm wondering if there is an error with it in the bot.
https://github.com/KSP-RO/SolverEngines/releases/tag/v3.7.2

**Comment by HebaruSan** [comment]
Weird, the GitHub API is returning those releases out of order:

https://api.github.com/repos/KSP-RO/SolverEngines/releases

**Comment by raidernick** [comment]
No they weren't. Remember I removed a release because I had deleted it on github. I made a new release for 1.4.5 and then another for 1.5.1. Both are incremented in version from the previous including the old one I removed to avoid this problem and it still somehow is out of order?

**Comment by HebaruSan** [comment]
OK, looking at the API data, my guess is v3.7.2 was created first and left in a "pending" state while v3.7.1 was created afterwards and released. Yes I realize you just contradicted that, but I don't think the id property could look like it does otherwise (lower id for v3.7.2 than v3.7.1).

**Comment by raidernick** [comment]
I didn't realize ckan read drafts. I thought it ignored drafts and pre-releases and only indexed actual releases. Are you saying it actually takes the timestamp from the draft when it creates the id? That doesn't seem like a great idea. Is there an easy way to fix it?

**Comment by HebaruSan** [comment]
CKAN **doesn't** read drafts (or prereleases) and I didn't say it does.

I'm trying to figure out why they're in the wrong order in the API, and the `id` property is the only thing that seems to explain it so far:

```json
[
  {
    "id": 14865708,
    "tag_name": "v3.7.1",
  },
  {
    "id": 14865653,
    "tag_name": "v3.7.2",
  },
```

If v3.7.2 was created second, it ought to have an id higher than 14865708.

**Comment by HebaruSan** [comment]
Well whatever happened here, I think I'll just index v3.7.2 manually. Hopefully future updates will not repeat the issue...
