### ISSUE TITLE
CI failed

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#6937]
I updated the PWDFuelBalancer, PR #6936 

There was a new step I saw, **continuous-integration/travis-ci/pr — The Travis CI build failed**
 
First, it took about 10 minutes to run
Second, it failed with the following error, which wasn't related to my file:

```
The command "jsonlint -s -v NetKAN/*.netkan" exited with 0.
0.07s$ prove
No tests named and 't' directory not found at /usr/share/perl/5.18/App/Prove.pm line 528.
The command "prove" exited with 2.
```

**Comment by HebaruSan** [comment]
Weird, Travis isn't supposed to run for NetKAN. I think you can ignore it as long as the real test works.

**Comment by HebaruSan** [comment]
The pull request validation scripts don't seem to be running for CKAN-meta either.

**Comment by techman83** [comment]
NetKAN builds are running, but the UI for GitHub has changed, probably some plugin updates are required.

CKAN-meta's webhook needed fixing and the Travis Webhooks have been disabled, we haven't used Travis for metadata since the early days of the project!

**Comment by HebaruSan** [comment]
Working with netkan PRs today, I think this is fixed now.
