### ISSUE TITLE
Near Future Electrical compatibility misidentified.

### ISSUE THREAD

**Issue by Funtime60** [KSP-CKAN/NetKAN#6969]
Background
----------

**CKAN Version:** 
1.25.4

**KSP Version:** 
1.6.1.2401

**Operating System:** 
Windows 10 Home
10.0.17134 Build 17134

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Not with this installation

**Affected mods and mod versions:**
Near Future Electrical Extras: Decaying RTGs Patch
Near Future Electrical

Problem
-------

**What steps did you take in CKAN?**
Attempted to install Near Future Electrical Extras: Decaying RTGs Patch letting CKAN take care of its dependency of Near Future Electrical

**What did you expect to happen?**
For both Near Future Electrical Extras: Decaying RTGs Patch and Near Future Electrical to be added to the changeset

**What happened instead?**
It generated an error that Near Future Electrical was incompatible with my KSP version 1.6.1 despite being listed as compatible with 1.6.0-1.6.99

**Screenshots:**

![image](https://user-images.githubusercontent.com/24595923/51508856-0586e480-1dc5-11e9-830b-a48fd2451e4f.png)
![image](https://user-images.githubusercontent.com/24595923/51508871-1afc0e80-1dc5-11e9-966f-2e1cf8499ebe.png)

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
Check the Relationships tab, CommunityResourcePack isn't updated to 1.6 yet:

![image](https://user-images.githubusercontent.com/1559108/51509993-d53d4700-1dc0-11e9-9419-c1c453a92e72.png)

Try adding 1.5 as a compatible version:

https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions
