### ISSUE TITLE
KSPWheel version 0.13.10.29 can't be CKAN installed due to wrong value in .ckan ksp_version_max field

### ISSUE THREAD

**Issue by Jacke4913** [KSP-CKAN/NetKAN#6975]
CKAN v1.25.4
KSP v1.6.1
Mod KSPWheel

In CKAN, version 0.13.10.29 is shown as available but not available for KSP 1.6.1.  Checked its .netkan and .ckan:

https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/KSPWheel.netkan

https://github.com/KSP-CKAN/CKAN-meta/blob/master/KSPWheel/KSPWheel-0.13.10.29.ckan

Its .ckan has a wrong ksp_version_max field:

> "version": "0.13.10.29",
> "ksp_version_min": "1.6.0",
> "ksp_version_max": "1.5.9",

I couldn't download the install .zip via CKAN but could do so directly from the mod's source, GitHub:

https://github.com/shadowmage45/KSPWheel/releases

The KSPWheel.version file contains correct KSP version values which don't match those in the .ckan:

	"VERSION":
	{
		"MAJOR":0,
		"MINOR":13,
		"PATCH":10,
		"BUILD":29
	},
	"KSP_VERSION":
	{
		"MAJOR":1,
		"MINOR":6,
		"PATCH":0
	},
	"KSP_VERSION_MIN":
	{
		"MAJOR":1,
		"MINOR":6,
		"PATCH":0
	},
	"KSP_VERSION_MAX":
	{
		"MAJOR":1,
		"MINOR":6,
		"PATCH":9
	}

**Comment by HebaruSan** [comment]
That's from http://ksp-avc.cybutek.net/version.php?id=429 which is specified in the "URL" property of the .version file. Try [reporting it to the mod author](https://github.com/shadowmage45/KSPWheel/issues/new).

**Comment by BaelRathLian** [comment]
Love cKan, but **one major flaw**.  It needs to be able to undo what it installed and or have a detailed list of what and where things were installed.

**Comment by DasSkelett** [comment]
@BaelRathLian If you want to raise a bug report or feature request, please create a new issue

**Comment by DasSkelett** [comment]
@BaelRathLian, if you want to raise a bug report or a feature suggestion, please [open a new issue](https://github.com/KSP-CKAN/CKAN/issues/new). Don't comment on old, closed issues regarding completely different topics.

**Comment by HebaruSan** [comment]
Another option is to add a comment on an existing issue that is relevant, such as #6234.
