### ISSUE TITLE
Missing adopted version of Ext. info. about scientific experiments 

### ISSUE THREAD

**Issue by 4x4cheesecake** [KSP-CKAN/NetKAN#6980]
Background
----------

**CKAN Version:** 
1.25.4

**KSP Version:** 
1.6.1

**Operating System:** 
Win 10 Prof 64bit

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

**Affected mods and mod versions:**
[Extended information about scientific experiments](https://spacedock.info/mod/2000)

Problem
-------
CKAN still points to [the old/original release](https://spacedock.info/mod/1008) but doesn't lists the [adopted version of Linuxgurugamer](https://spacedock.info/mod/2000)

**What steps did you take in CKAN?**
Compatible KSP versions are set to: 1.6, 1.5 and 1.4.
Searching for the mod name 'Extended' or 'scientific' or any mod by linuxgurugamer didn't find this mod.
After setting KSP 1.3 to be compatible as well, it can be found through CKAN but just the original release, not the adopted version.

**What did you expect to happen?**
I expected to find the adopted version of the mod.

**What happened instead?**
See above

**Comment by HebaruSan** [comment]
Oh, *that* explains what the heck was going on in #6716–presumably LGG meant to index this new one at some point instead of making a duplicate!

**Comment by HebaruSan** [comment]
Collection is complete at last:

![image](https://user-images.githubusercontent.com/1559108/51845901-1ca26680-22de-11e9-8669-971a64ddfaf9.png)

**Comment by 4x4cheesecake** [comment]
Thanks :)
