### ISSUE TITLE
New version of REKT  0.4.6.2 not picked up

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7000]
I released an update to REKT yesterday, 0.4.6.2

It's on Spacedock and Github, I verified the correct version by downloading the current file from each.

CKAN hasn't picked it up yet

**Comment by HebaruSan** [comment]
SpaceDock says today, not yesterday. https://spacedock.info/mod/1021

![image](https://user-images.githubusercontent.com/1559108/52382091-9d2d3980-2a39-11e9-9402-cd1c00907a8c.png)

Looks like another case of being patient. :wink:

**Comment by linuxgurugamer** [comment]
Then it was early this morning (rather busy here).  Early meaning about 7am eastern.  as of now, 13 hours ago.
I'll check tomorrow

**Comment by techman83** [comment]
The indexer is still really upset about staging. I think removing the staging branches after merge (which is a good thing) is causing a problem, as the branch does exist locally. Keeping the branch prevents multiple PRs being opened for a change, but if the branch doesn't exist upstream we should probably purge the local one.

I've restored the problem branch and re-running the indexer. If it is indeed the case, I'll raise an issue, write a test case and think about the workflow.

**Comment by HebaruSan** [comment]
Yeah, something weird's going on. I ran it locally and it generated a 0.4.6.2 file for me without problems, but the bot hasn't, and it hasn't raised an error either despite claiming to have checked this mod less than an hour ago.

In case the staging stuff doesn't solve it, can you try fixing the URL field in the version file? There should be two forward slashes (`//`) between `http:` and `ksp.spacetux.net`.

```json
  "URL": "http:/ksp.spacetux.net/avc/RecoverableEmergencyKerbalTransport",
```

**Comment by techman83** [comment]
Yeah, the NetKAN part of the process was fine. But the bot bailed out as it wasn't on the branch it thought it was.

**Comment by HebaruSan** [comment]
Looks like it worked.

https://github.com/KSP-CKAN/CKAN-meta/commit/e96e46755e5a8e532ffb7845c39b2d665587fbb9

Closing since @techman83 said he'll create a new issue if there's an outstanding underlying issue to be fixed.
