### ISSUE TITLE
Universal Storage II latest 1.3.1-compatible versions missing

### ISSUE THREAD

**Issue by buttercookie42** [KSP-CKAN/NetKAN#7003]
The latest KSP 1.3.1-compatible version offered by CKAN is 1.3.1.7, however according to [the changelog](https://spacedock.info/mod/1933/Universal%20Storage%20II), versiosn 1.3.1.8 and 1.3.1.9 should be available, too.

**Comment by HebaruSan** [comment]
Looks like another consequence of KSP-SpaceDock/SpaceDock#192. These probably got uploaded too quickly for the bot to catch each one, and with the web hook broken, versions got skipped.
