### ISSUE TITLE
Universal Storage II compatibility data

### ISSUE THREAD

**Issue by buttercookie42** [KSP-CKAN/NetKAN#7004]
According to the [forum thread](https://forum.kerbalspaceprogram.com/index.php?/topic/177385-universal-storage-ii/), the current version (1.6.0.9) is listed as being compatible with KSP 1.4.x upwards, whereas CKAN only has 1.6.0 compatibility noted. The same might also be true for the intermediate 1.5.x.y mod versions.

**Comment by HebaruSan** [comment]
Is there a bug tracker for this mod? The version file which we would otherwise use for this is out of date and would produce bad data in CKAN (note that VERSION says 1.5.1.9 in the download for 1.6.0.9):

```json
{
"NAME":"Universal Storage 2","URL":"http://ksp-avc.cybutek.net/version.php?id=591",
"DOWNLOAD":"https://spacedock.info/mod/1933/Universal%20Storage%20II/download/1.5.1.8",
"CHANGE_LOG_URL":"https://spacedock.info/mod/1933/Universal%20Storage%20II",
"VERSION":{"MAJOR":1,"MINOR":5,"PATCH":1,"BUILD":9},
"KSP_VERSION":{"MAJOR":1,"MINOR":6,"PATCH":0},
"KSP_VERSION_MIN":{"MAJOR":1,"MINOR":4,"PATCH":5},
"KSP_VERSION_MAX":{"MAJOR":1,"MINOR":6,"PATCH":99}
}
```

If the author can get that fixed, we could start using this data.

**Comment by HebaruSan** [comment]
Hmm, trying it out in #7005, the metadata actually turns out OK, but it's still not super safe to knowingly use partially wrong data. Not sure how to proceed.

**Comment by buttercookie42** [comment]
Thank you.

**Comment by HebaruSan** [comment]
Thanks for letting us know about this!
