### ISSUE TITLE
Better SRBs version "1.05" doesn't exist upstream and is identical to version "1.0.5"

### ISSUE THREAD

**Issue by Jacke4913** [KSP-CKAN/NetKAN#7010]
CKAN v1.25.4
KSP v1.6.1
running on Windows 10

Better SRBs on the KSP forums
https://forum.kerbalspaceprogram.com/index.php?/topic/175316-ksp-16x-15x-bettersrbs-v105-12-nov-2018/

Better SRBs on GitHub
https://github.com/OhioBob/BetterSRBs/releases

Its NetKAN
https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/BetterSRBs.netkan

Its CKANs
https://github.com/KSP-CKAN/CKAN-meta/blob/master/BetterSRBs/BetterSRBs-1.05.ckan
https://github.com/KSP-CKAN/CKAN-meta/blob/master/BetterSRBs/BetterSRBs-1.0.5.ckan
https://github.com/KSP-CKAN/CKAN-meta/blob/master/BetterSRBs/BetterSRBs-1.0.4.ckan

----------------------------------------------------------------

When reviewing my mods, noticed Better SRBs in CKAN had 3 versions available:

1.05
1.0.5
1.0.4

Located its forum topic and upstream source.  Saw that version "1.05" doesn't exist there.

Compared the two download install zips

B84FB5EC-BetterSRBs-1.05.zip
6DEC27DA-BetterSRBs-1.0.5.zip

and saw their contents are identical, including both having a BetterSRBs.version file saying it is version "1.0.5".

**Comment by HebaruSan** [comment]
Do you want to try fixing this yourself? You can open the 1.05 file and click the trash icon to start the process of making a pull request.

**Comment by Jacke4913** [comment]
Thanks for the advice.  Created the pull request as described.
