### ISSUE TITLE
Unable to install Toolbar Controller

### ISSUE THREAD

**Issue by 4x4cheesecake** [KSP-CKAN/NetKAN#7016]
Pinged HebaruSan in the forum already but for the sake of completenes, here is the actual issue:

Background
----------

**CKAN Version:** 
1.25.4

**KSP Version:** 
1.6.1

**Operating System:** 
Win10 x64 Pro

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

**Affected mods and mod versions:**
Toolbar Controller 0.1.6.20

Problem
-------

**What steps did you take in CKAN?**
I've tried to install Toolbar Controller

**What did you expect to happen?**
CKAN should install the mod

**What happened instead?**
CKAN throws an error:

CKAN.InvalidModuleFileKraken: ToolbarController 1:0.1.6.20: C:\Users\cheesecake\AppData\Local\Temp\tmpA27A.tmp has length 103767, should be 103763
   bei CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   bei CKAN.NetAsyncModulesDownloader.ModuleDownloadsComplete(NetModuleCache cache, Uri[] urls, String[] filenames, Exception[] errors)

**Background**
Toolbar Controller got an update to fix an issue with the .version file. If I understood it correctly, the previous version didn't got a full release but just an .version file update to support KSP 1.6.0 so basically, it was still version 0.1.6.19 but the .version file said it is 0.1.6.20.
Now, Toolbar Controller actually got a full release, still listed as version 0.1.6.20 but with different content.
Forum posts related to this issue:
https://forum.kerbalspaceprogram.com/index.php?/topic/169509-151-toolbar-controller-for-modders/&do=findComment&comment=3542866

**Comment by HebaruSan** [comment]
Unfortunately this isn't something I have access to fix.

@techman83 , can you please purge this file from the bot's cache?

- `3BCE0BBA-netkan-ToolbarController.zip`

**Comment by techman83** [comment]
Done!

**Comment by HebaruSan** [comment]
Thanks! Latest data looks good.
https://github.com/KSP-CKAN/CKAN-meta/commit/633fb804f4bab9f520cf474462f90788247a979d
