### ISSUE TITLE
Testing required

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/NetKAN#7027]
@KSP-CKAN/wranglers, there's a new pre-release available that includes the long-delayed "replaced_by" addition to the spec. (Huge thanks to @HebaruSan for finishing up the code that had me dithering about implementation specifics!)

We really need some of the old entries in CKAN-Meta modified to use the new field so we can test out the new client.

**Comment by HebaruSan** [comment]
For reference, this was the original feature request: KSP-CKAN/CKAN#904

One possible test case is xScience &rarr; xScienceContinued in #7021.

**Comment by HebaruSan** [comment]
<details><summary>Expand for the (very long) list of identifiers in NetKAN that might be applicable...</summary>

- AirPark → AirParkContinued
- AnalogControl → AnalogControlContinued
- AnyRes → AnyResContinued
- AudioMuffler → AudioMufflerRedux
- B9-PWings → B9-PWings-Fork
- BahaEPL → BahaEPLRedrilled
- BAM → BAMCont
- BargainRockets → BargainRocketsCont
- BDArmory → BDArmoryContinued
- BetterScienceLabs → BetterScienceLabsContinued
- BetterTimeWarp → BetterTimeWarpCont
- BOSS → BOSSContinued
- BurnTogether → BurnTogetherContinued
- CactEyeTelescopes → CactEyeTelescopesContinued
- CareerManager → CareerManagerContinued
- ChampagneBottle → ChampagneBottleRedux
- CivilianPopulations → CivilianPopulationsRevived
- CollisionFX → CollisionFXUpdated
- ContractFilter → ContractFilterContinued
- CrewQueue → CrewQueueTwo
- DangerAlerts → DangerAlertsContinued
- DangIt → DangItContinued
- EditorExtensions → EditorExtensionsRedux
- EngineIgnitor → EngineIgnitorReignited
- EVAEnhancements → EVAEnhancementsContinued
- EvaFuel → EvaFuelCont
- EVAHandrailsPack → EVAHandrailsPackContinued
- ExceptionDetector → ExceptionDetectorUpdated
- ExtensiveEngRpt → ExtensiveEngRptContinued
- FarFromKerbin → FarFromKerbinCont
- FASALaunchClamps → FASALaunchClampsContinued
- FerramAerospaceResearch → FerramAerospaceResearchContinued
- FlagRotate → FlagRotateCont
- FMRS → FMRSContinued
- ForScience → ForScienceContinued
- FTLDrive → FTLDriveContinued
- FuseBox → FuseBoxContinued
- GravityTurn → GravityTurnContinued
- HangerExtender → HangerExtenderExtended
- Haystack → HaystackContinued
- Haystack → HaystackReContinued
- HullcamVDS → HullcamVDSContinued
- ImageViewer → ImageViewerCont
- InterKalactic → InterKalactic2
- JetSounds → JetSoundsContinued
- K2CommandPod → K2CommandPodCont
- KerbalAnimationSuite → KerbalAnimationSuiteCont
- KerbalFoundries → KerbalFoundriesContinued
- KerbalGalaxy → KerbalGalaxyRevamped
- KerbalGPS → KerbalGPSRevived
- KerbalHotSeat → KerbalHotSeatCont
- KerbalJointReinforcement → KerbalJointReinforcementContinued
- KerbalObjectInspector → KerbalObjectInspectorCont
- KerbCam → KerbCam-Continued
- KerbQuake → KerbQuakeExtended
- KolyphemusSystem → KolyphemusSystemContinued
- KramaxAutopilot → KramaxAutopilotContinued
- KSPCasher → KSPCasherCont
- KSPInterstellar → KSPInterstellarExtended
- Kurrikane → KurrikaneExpanded
- KVV → KVVContinued
- KWRocketry → KWRocketryRebalanced
- LargeStructuralComponents → LargeStructuralComponentsRedux
- LaunchCountDown → LaunchCountDownextended
- LTech → LTechContinued
- MicroSat → MicroSatRevived
- MissionController → MissionController2
- MusicMute → MusicMuteContinued
- NavballDockingIndicator → CommunityNavballDockingIndicator
- NavballDockingIndicator → NavballDockAlignIndCE
- NavHud → NavHudRenewed
- NavUtilities → NavUtilitiesContinued
- NEBULADecals → NEBULADecalsContinued
- NoCrewRequirement → NoCrewRequirementContinued
- NoMoreGrind → NoMoreGrindRedux
- NovaPunch → NovaPunchContinued
- Octosat → OctosatContinued
- OldParts → OldPartsRedux
- OSEWorkShop → OSEWorkShopCont
- PAD → PADContinued
- PAPIPlugin → PAPIPluginContinued
- PartCommander → PartCommanderCont
- PartWizard → PartWizardContinued
- ProbeControlRoom → ProbeControlRoomRecontrolled
- PWBFuelBalancer → PWBFuelBalancerRestored
- QuantumStruts → QuantumStrutsContinued
- QuizTechAeroPack → QuizTechAeroPackContinued
- RCSBuildAid → RCSBuildAidCont
- RealTimeClock → RealTimeClock2
- RLA → RLAContinued
- RLA → RLAReborn
- RLA → RLARecontinued
- RoverScience → RoverScienceCont
- ScienceRevisited → ScienceRevisitedRevisited
- SensiblePumps → SensiblePumpsCont
- ShipEffects → ShipEffectsContinued
- ShipSections → ShipSectionsContinued
- ShowAllFuels → ShowAllFuelsContinued
- SlingShotter → SlingShotterReslung
- Spacedocks → SpacedocksRedeployed
- SpannersBoomsticks → SpannersBoomsticksContinued
- SSRSS → SSRSS-Cont
- StateFunding → StateFundingContinued
- StationPartsExpansion → StationPartsExpansionRedux
- StationScience → StationScienceContinued
- SXT → SXTContinued
- TacSelfDestruct → TacSelfDestructContinued
- TakeCommand → TakeCommandContinued
- TankLock → TankLockRedux
- Telemachus → Telemachus-2
- Telemachus → TelemachusContinued
- Telemachus → TelemachusReborn
- TextureReplacer → TextureReplacerReplaced
- ToadicusTools → ToadicusToolsContinued
- TurboNisu → TurboNisuReloaded
- TweakableEverything → TweakableEverythingCont
- UbioWeld → UbioWeldContinued
- UniversalStorage → UniversalStorage2
- USIKolClassSuits → USIKolClassSuitsRedux
- VesselMover → VesselMoverContinued
- Vostok → VostokContinued
- WasdEditorCamera → WasdEditorCameraContinued
- WernherChecker → WernherCheckerContinued
- YongeTechTreesPlugin → YongeTechTreesPlugin-Revived

</details>

**Comment by HebaruSan** [comment]
How will old (1.25) clients react to metadata with a higher (1.26) spec_version? Is it safe to merge #7048?

**Comment by Tekaoh** [comment]
Maybe I'm just a noob, but: Is it a little confusing that `replaced_by:` wants `{name: }` to be the *identifier* of the new mod by which it is to be replaced? Wouldn't `"replaced_by": { "identifier": "someIdentifier" }` be a little more intuitive?

**Comment by HebaruSan** [comment]
If this was all being designed from scratch, then yes something like `{ "id": "whatever" }` would be better.
But this is building on the existing depends/conflicts/suggests/recommends relationships, all of which use `"name"` in the same way.

**Comment by Tekaoh** [comment]
Ah, that makes sense. Thanks for the info! Totally off the wall suggestion, but what would be the implication of trying to map `identifier` to `name` as an alias or something to allow more intuitive relationships while not breaking compatibility for the many hundreds of relationships that already exist?

**Comment by HebaruSan** [comment]
OK, a repo update that contains a future spec version will throw `UnsupportedKraken`:

https://github.com/KSP-CKAN/CKAN/blob/6b4cd143996f029b94162ec89a2e0cb86f9a7c3f/Core/Types/CkanModule.cs#L516-L526

However, that will then be caught by the repo update code, which just skips the module:

https://github.com/KSP-CKAN/CKAN/blob/6b4cd143996f029b94162ec89a2e0cb86f9a7c3f/Core/Net/Repo.cs#L542-L553

So we won't cause crashes by merging these, but clients older than the 1.26 prerelease *will* see some module versions disappear upon a repo update. I guess that's a necessary evil to get the testing done.

**Comment by HebaruSan** [comment]
xScienceContinued works fine, but trying to replace OSEWorkshopCont runs into a problem with the conflict relationship between the two modules:

![image](https://user-images.githubusercontent.com/1559108/53910178-dfd23980-4018-11e9-8954-531fb2e5be22.png)

**Comment by HebaruSan** [comment]
CKAN v1.26 is out in the wild; presumably the testing was done.
