### ISSUE TITLE
Remove DoctorDavinci's mod

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7099]
DoctorDavinci seems to have deleted his Github account and all his mods, so all netkans related tp him should be checked and frozen

**Comment by DasSkelett** [comment]
Those would be https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/DCKFutureTech.netkan and https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/DCKDavincisCombatKit.netkan.

**Comment by politas** [comment]
They're GPL, so we can switch the downloads over to the archive.org copies, if the modder hasn't asked us to remove them.
