### ISSUE TITLE
Hitting 'home' / 'Pos1' key on modlist throws error.

### ISSUE THREAD

**Issue by Lucidus360** [KSP-CKAN/NetKAN#7108]
Background
----------

**CKAN Version:** 
v1.26.0

**KSP Version:** 
1.6.1.2401

**Operating System:** 
Windows 7

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

**Affected mods and mod versions:**
N/A

Problem
-------
I get an exception whenever I hit the 'home' key in windows 7. Expected behavior would be to jump to the top of the list of installed mods. My workaround is to hit page up repeatedly (but I usually forget and keep hitting home key).

**What steps did you take in CKAN?**
Hit 'Home' key

**What did you expect to happen?**
Jump to top of list of mods

**What happened instead?**
Unhandled exception occurs.

**Screenshots:**

![image](https://user-images.githubusercontent.com/49299135/55604003-9ec66580-573b-11e9-9c61-3f681afc5c33.png)

**CKAN error codes (if applicable):** 
```
System.InvalidOperationException: Die aktuelle Zelle kann nicht auf eine unsichtbare Zelle festgelegt werden. (Rough translation: the current cell can't be set to an invisible cell)
   bei System.Windows.Forms.DataGridView.set_CurrentCell(DataGridViewCell value)
   bei CKAN.Main.ModList_KeyDown(Object sender, KeyEventArgs e)
   bei System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   bei System.Windows.Forms.DataGridView.OnKeyDown(KeyEventArgs e)
   bei System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   bei System.Windows.Forms.DataGridView.ProcessKeyEventArgs(Message& m)
   bei System.Windows.Forms.Control.WmKeyChar(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by DasSkelett** [comment]
Thanks for the report.
Can confirm the issue, I added the error message to your post.
I suspect it's a similar issue to https://github.com/KSP-CKAN/CKAN/issues/2703, CKAN tries to select a cell in a hidden column.
