### ISSUE TITLE
Kerbal Academy new versions not listed

### ISSUE THREAD

**Issue by Blu3wolf** [KSP-CKAN/NetKAN#7115]
Background
----------

**CKAN Version:** 
1.26.0

**KSP Version:** 
1.4.5

**Operating System:** 
W7 x64

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Yup!

**Affected mods and mod versions:**
Contract Pack: Kerbal Academy

Problem
-------

**What steps did you take in CKAN?**
auto-updated to the current mod versions

**What did you expect to happen?**
to be updated to the current mod versions

**What happened instead?**
an out of date mod version was installed - 1.1.10 (1.2.1.1 is available)

**Notes:** 
The newer versions are by a new author - https://github.com/Mark-Kerbin/Kerbal-Academy-Contract-Pack/releases

I guess the NetKAN is looking at the old author still?

**Comment by HebaruSan** [comment]
1.2.1 has a syntax error in its .version file that's preventing it from being indexed.

http://status.ksp-ckan.space/
> After parsing a value an unexpected character was encountered: ". Path 'GITHUB.USERNAME', line 8, position 8.

Mark-Kerbin/Kerbal-Academy-Contract-Pack#16 fixed that, but those changes haven't been included in a new release yet.
