### ISSUE TITLE
Repository update failed

### ISSUE THREAD

**Issue by Wert19699** [KSP-CKAN/NetKAN#7120]
CKAN Version: 1.26.0

KSP Version: 1.6.1

Operating System: Windows 10

Have you made any manual changes to your GameData folder (i.e., not via CKAN)? No 

Problem
---------

**What steps did you take in CKAN?**
Opened ckan.exe

**What did you expect to happen?**
ckan would update repositories and send me to main window

**What happened instead?**
Repository update failed (stuck on please wait screen)

**Screenshots:**

![image](https://user-images.githubusercontent.com/49451731/56080214-d5644600-5df5-11e9-97b5-583184368009.png)

Please help! Thanks!

**Comment by Wert19699** [comment]
its not ksp 1.22 as it says in the screenshot its ksp 1.6.1

**Comment by HebaruSan** [comment]
Do you have some weird DNS setup in your OS? Your computer seems to think that github.com is 127.0.0.1, but that's the special IP address for local host.

**Comment by Wert19699** [comment]
I have no idea, do you know how i can change it back?

**Comment by HebaruSan** [comment]
No, I have never seen this error message before and don't know what's causing it.

**Comment by Wert19699** [comment]
ok well thanks for your help anyway

**Comment by DasSkelett** [comment]
Try `ping github.com` in the command line and see if it says the same IP.

**Comment by Wert19699** [comment]
![image](https://user-images.githubusercontent.com/49451731/56080710-4dce0580-5dfc-11e9-84a2-5b4076c81876.png)

Ok, this is what came up

**Comment by HebaruSan** [comment]
Well that looks fine.

Maybe your OS's firewall is blocking CKAN but not other apps?
https://support.mozilla.org/en-US/kb/configure-windows-firewall-allow-firefox-access

**Comment by DasSkelett** [comment]
Yep, looks like a blocked internet access for CKAN. If you have an AV/Firewall installed, look if there's a whitelist option.

**Comment by Wert19699** [comment]
when i select "allow an app through the firewall", ckan.exe is not there

**Comment by Wert19699** [comment]
oh nvm ive added it let me try to launch now

**Comment by Wert19699** [comment]
still not updating any ideas? I have allowed ckan through the firewall

**Comment by HebaruSan** [comment]
Is the error message still the same?

**Comment by Wert19699** [comment]
Sorry for my absence. Yes the error message is the same

**Comment by Wert19699** [comment]
Guys?

**Comment by linuxgurugamer** [comment]
What antivirus do you have installed?  Are you using a VPN?

**Comment by Wert19699** [comment]
No I do not use a vpn

**Comment by Wert19699** [comment]
I use windows defender and bt virus protect (basically mcafee)

**Comment by Wert19699** [comment]
It was working fine a few weeks ago so idk why this is happening

**Comment by Wert19699** [comment]
Btw love your mods!

**Comment by Wert19699** [comment]
I think I have a rare issue that no one knows how to solve so I might close this in a few days as there is no point. However, I would like to thank all of you for trying to help me the best you can.

**Comment by DasSkelett** [comment]
I strongly believe it has to do with your Antivirus.
In my opinion you should get rid of it, they do more harm than good.
It's most likely not a CKAN issue.

**Comment by Wert19699** [comment]
The thing is I've had this antivirus for ages and ckan was working just fine

**Comment by HebaruSan** [comment]
Antivirus programs update all the time to stay ahead of the current malware (ostensibly).

**Comment by Wert19699** [comment]
I have uninstalled my antivirus but still getting the same error. I even tried turning off windows defender to see if that worked. It is definitely not an antivirus issue

**Comment by DasSkelett** [comment]
Hmm. You could take a look at the hosts file `%SystemRoot%\system32\drivers\etc\hosts` and see if there is a entry for github.com.

**Comment by Wert19699** [comment]
![image](https://user-images.githubusercontent.com/49451731/56471523-7e8ceb00-644b-11e9-9d56-5775f47a6e1f.png)

im guessing codeload github is the entry

**Comment by Wert19699** [comment]
but that ip is the one that comes up in the error

**Comment by DasSkelett** [comment]
Yep, put a # before this line and try again.

**Comment by Wert19699** [comment]
in front of codeload.github.com?

**Comment by DasSkelett** [comment]
It should look like this afterwards:
```
# 127.0.0.1    codeload.github.com
```
And see if you find more entries for github, and do the same.

**Comment by Wert19699** [comment]
ok

**Comment by Wert19699** [comment]
No way! It worked, thanks so much!

**Comment by Wert19699** [comment]
Also, thank you to everyone for all of your contributions!

**Comment by DasSkelett** [comment]
Nice! For your info: this file manually maps domain names to IP addresses. It is mostly used to block traffic to malicious sides (e.g. if a script on a webpage tries to load something bad).
I'm still pretty sure that it was your Antivirus which added those entries. So if you reinstall it, it might add them again, and maybe every now and then do so.
So make sure to check the file if this happens again. Or better, see if there's an option to add an exception for github.

**Comment by Wert19699** [comment]
Ok thanks for the info! The best thing about it is that others who had the same issue as me will be able to look at this and fix it for themselves because when i googled a solution for this, nothing came up

**Comment by HebaruSan** [comment]
Wow, the hosts file never crossed my mind as a potential cause to this! Nice work, @DasSkelett!

**Comment by Wert19699** [comment]
btw me and a friend run a youtube channel if you want to check it out: 

https://www.youtube.com/channel/UCKsbtYxTy7cZoAFDWUxj9Kg
