### ISSUE TITLE
ABCORS 0.5.0.3 has invalid file size and hash.

### ISSUE THREAD

**Issue by DasSkelett** [KSP-CKAN/NetKAN#7124]
[The .ckan](https://github.com/KSP-CKAN/CKAN-meta/blob/master/ABCORS/ABCORS-0.5.0.3.ckan) states 24.725 bytes, the download is 25.694.
The hashes changed too. Likely linuxgurugamer re-released the version after it's been indexed by the bot.
Please purge from the cache.

**Comment by DasSkelett** [comment]
@politas @techman83

**Comment by HebaruSan** [comment]
This isn't the latest release, so the bot won't be checking it and no cache purging is necessary. You can just do a `netkan --releases 2` command to regenerate the metadata.

**Comment by DasSkelett** [comment]
Even better. Thanks!

**Comment by linuxgurugamer** [comment]
Just an FYI, if this happens again, please contact me. I make it a point to not re-release things for this reason, I'll do a version bump if necessary.
