### ISSUE TITLE
CKAN not showing compatible mods

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7139]
I updated DatedQuicksaves to version 1.2.3.4, and the compatibility is from 1.5.1 onward.
However, CKAN itself, doesn't show this for a 1.6.1 game.
I examined the CKAN meta, and it shows the following:
`    "version": "1.2.3.4",
    "ksp_version_min": "1.5.1",
    "ksp_version_max": "1.7.0",`
Full URL is here:
https://github.com/KSP-CKAN/CKAN-meta/blob/master/DatedQuickSaves/DatedQuickSaves-1.2.3.4.ckan

Not sure if this is a bug in CKAN or in the meta data

**Comment by HebaruSan** [comment]
Unable to reproduce; this mod shows up and is installable on 1..6.1:

![image](https://user-images.githubusercontent.com/1559108/56294449-91857f80-611a-11e9-8e45-b6f11bf53825.png)

**Comment by linuxgurugamer** [comment]
Thank you for checking.
I had to restart CKAN for it to work.  
While I obviously can't reproduce it right now, I think what happened is that I had CKAN open (I leave it open all the time), updated DatedQuickSaves, and then when CKAN updated the metadata, while it seemed to get the right information (based upon examination of the registry), it wasn't processing it properly in this specific case.

**Comment by HebaruSan** [comment]
Sounds good, if you're able to make it happen again/consistently please re-open this.
