### ISSUE TITLE
unfrozen Sigma Dimension

### ISSUE THREAD

**Issue by yalov** [KSP-CKAN/NetKAN#7153]
https://github.com/KSP-CKAN/NetKAN/issues/4278

> I'm not against CKAN as long as everything is handled without asking me to do stuff
> 
> however, my mods are not updated to 1.7 and I don't really know how long before I will get the 
> time to work on them

also https://github.com/Galileo88/Rescale/releases have many assets in one release. 
Will some manual way get work there?

**Comment by HebaruSan** [comment]
See the more recent conversation in #6527 for why this is frozen. Does Sigma want them unfrozen?

**Comment by yalov** [comment]
Quote above is the most recent answer.

> I don't like the attitude of squad and I have lost all interest in making mods for KSP
Looks like Sigma start all frozen process because he was no longer into ksp, and didn't want to maintain anything about the ckan.

> I'm not against CKAN as long as everything is handled without asking me to do stuff
so as long as Dimensions will be just parsed from the Github repo he is ok?

**Comment by HebaruSan** [comment]
I'm not comfortable with taking action based on assumptions and interpretations like that. The only unambiguous statement we have so far is the request to freeze. I wouldn't want to unfreeze these mods only to discover that it wasn't actually what the mod author wanted.

> so as long as Dimensions will be just parsed from the Github repo he is ok?

But that's how it was before, when he asked for them to be frozen.

@Sigma88, would you mind if we reverted KSP-CKAN/NetKAN#6534 to reactivate your mods in CKAN? @yalov thinks your recent remarks mean that you would be OK with that.

**Comment by HebaruSan** [comment]
No response for quite a while. Let us know if you hear from him, we can consider it then.

**Comment by Sigma88** [comment]
Sorry for the late reply, I managed to miss the ping for some reason

I can confirm that I am no longer against CKAN integration as long as it is done without asking me to do anything.

However, most of my mods are out of date so it might not be worth the time. but that's up to you to decide

**Comment by HebaruSan** [comment]
If something goes wrong on the CKAN side, we'll fix it. If something goes wrong on your end (corrupt version file, etc.), we'll let you know. If we have questions, we'll ask. Same as anyone. Sound OK?

**Comment by Sigma88** [comment]
I'm ok as long as I am not asked to do anything. If you don't think it can be handled all on ckan side maybe it's not worth unfreezing it.

**Comment by HebaruSan** [comment]
I agree, if the only other option is for me to make a binding agreement that all metadata maintainers will tremble in fear at the idea of asking a question or notifying about a bug, then it's better not to unfreeze this.

**Comment by HebaruSan** [comment]
Handy historical links for future reference:

- https://github.com/KSP-CKAN/NetKAN/issues/4278
- https://github.com/KSP-CKAN/NetKAN/pull/4291
- https://github.com/KSP-CKAN/CKAN-meta/pull/1188
- https://github.com/KSP-CKAN/NetKAN/pull/5560
- https://github.com/KSP-CKAN/NetKAN/pull/6527
- https://github.com/KSP-CKAN/NetKAN/pull/6534
- https://github.com/KSP-CKAN/CKAN-meta/pull/1345
- https://github.com/KSP-CKAN/NetKAN/issues/7153
