### ISSUE TITLE
CKAN mods not showing

### ISSUE THREAD

**Issue by Austinsanity** [KSP-CKAN/NetKAN#7158]
Background
----------

**CKAN Version:** 
1.26.0

**KSP Version:** 
1.7.0.2483

**Operating System:** 
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Yes

Problem: There are no mods popping up.
-------

**What steps did you take in CKAN?**
I open CKAN, and no mods show up. I've tried running as admin, restarting my computer and even reinstalling the program entirely but nothing pops up even after all that. Has anybody else had this issue? How do I fix it?

**What did you expect to happen?**
I expected for the mods to show up.

**What happened instead?**
There were no mods listed.

**Screenshots:**

![save space](https://user-images.githubusercontent.com/49927270/56624080-3e716800-6605-11e9-8d2d-d51d7ec45fa1.PNG)

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
We need the info in the issue template to answer questions like that. Please fill it out.

**Comment by HebaruSan** [comment]
You selected the Replaceable filter. Switch it to All or Compatible.

![image](https://user-images.githubusercontent.com/1559108/56624132-2e558a80-65fd-11e9-9b24-d24b8665ee7d.png)

**Comment by Austinsanity** [comment]
that was simple, thanks!
