### ISSUE TITLE
Spacedock compatibility flag overrides the .version file

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7166]
I just found that two of my  most important mods, ClickThroughBlocker and ToolbarController, have not been available for 1.7, even though the .version files embedded in each allowed the compatibility.

Upon investigation, I saw that Spacedock was saying that they weren't compatible, I had to go and manually update each mod to allow the compatibility.

This is unexpected and wrong.  The .version file is supposed to specify the compatibility.  I have a significant number of bug reports because of this

**Comment by HebaruSan** [comment]
No, that's not how it works. AVC overrides SD. Need actual examples of what you're saying.

**Comment by HebaruSan** [comment]
OK, "overrides" is not quite the right word. The values from SD and AVC are combined. The logic is in the AVC netkan code; both SD and AVC are checked for min and max values, and the smallest value is used for min and the largest for max:

https://github.com/KSP-CKAN/CKAN/blob/44d44ea5cd38e2f568d95f2af6d24674e01f7a45/Netkan/Transformers/AvcTransformer.cs#L131-L184

I don't think any of that could be changed without breaking things.

Recommendation: revert #7032 and #6659. If you want an open-ended version range defined completely by the AVC file, then a host that requires selection of the compatible game version is not for you. GitHub is a better fit.

**Comment by linuxgurugamer** [comment]
I'll do that for the KURS to get the correct versions, and will move it back to spacedock when I push out the 1.7.0 version of KURS.
For the others, I'll just have to keep it in mind
