### ISSUE TITLE
DockingCamKURS has wrong info in generated ckan

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7170]
I've updated the .netkan for this mod to pull from github.
I have verified that the .version in the file contains the following:
`  "KSP_VERSION_MIN": {
    "MAJOR": 1,
    "MINOR": 4,
    "PATCH": 5
  },
  "KSP_VERSION_MAX": {
    "MAJOR": 1,
    "MINOR": 6,
    "PATCH": 1
  }`

However, the generated CKAN file lists it as only for KSP 1.7.0

**Comment by HebaruSan** [comment]
The "URL" property overrides the contents of the AVC file, and this one says 1.7.0:

https://raw.githubusercontent.com/linuxgurugamer/DockingCam/master/DockingCamera.version

**Comment by linuxgurugamer** [comment]
I didn't know that ckan used the url for that, the URL was for the AVC mod.
I'll get it updated and push again

**Comment by HebaruSan** [comment]
Yup, here's the logic. If the online file is for the same module version as the one in the download, the online file's values are used:

https://github.com/KSP-CKAN/CKAN/blob/44d44ea5cd38e2f568d95f2af6d24674e01f7a45/Netkan/Transformers/AvcTransformer.cs#L66-L79

See KSP-CKAN/CKAN#1701.

**Comment by linuxgurugamer** [comment]
Thanks for  your help.  It's all been updated now, for both pre 1.7.0 and now a 1.7.0 version
