### ISSUE TITLE
Newly compatible mods not updating

### ISSUE THREAD

**Issue by PhildeCube** [KSP-CKAN/NetKAN#7177]
Background
----------

**CKAN Version:** 
1.26.0

**KSP Version:** 
1.7.0

**Operating System:** 
Windows 7 Pro SP1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

**Affected mods and mod versions:**
None

Problem
-------

**What steps did you take in CKAN?**
Installed and started using.

**What did you expect to happen?**
Newly compatible mods would update day to day.

**What happened instead?**
From the start there were 2000 odd Newly compatible mods, I guess because they were all new. Now there are 2173 Newly compatible mods after about two weeks use. There were two new mods that came in today, based on the number of compatible mods this morning and this afternoon (285 and 287). I can't find what they were in the list.

**Screenshots:**

![image](https://user-images.githubusercontent.com/8325792/57060978-a6f3cf80-6cfe-11e9-8fba-c69973b03099.png)

**CKAN error codes (if applicable):** 
None

**Comment by DasSkelett** [comment]
That's https://github.com/KSP-CKAN/CKAN/issues/2716, already fixed in https://github.com/KSP-CKAN/CKAN/pull/2734.
If you want to use the 'Newly compatible' filter, deactivate the auto-refresh of the modlist in the settings, and refresh yourself at startup.

**Comment by PhildeCube** [comment]
Thanks. I have an old version? Weird. I only installed it about 2 weeks ago.

**Comment by DasSkelett** [comment]
The new CKAN release with this fix was released just today, so not your fault ;)

**Comment by PhildeCube** [comment]
New version works well. Thanks.
