### ISSUE TITLE
new mod - "Kerbal Joint Reinforcement - Next"

### ISSUE THREAD

**Issue by meirumeiru** [KSP-CKAN/NetKAN#7180]
I wanted to add a new mod to CKAN... (https://github.com/meirumeiru/Kerbal-Joint-Reinforcement) -> KJRn.netkan, but I'm not sure if it's ok like this.

**Comment by HebaruSan** [comment]
CKAN doesn't index releases that are marked as pre-releases on GitHub:

![image](https://user-images.githubusercontent.com/1559108/57181105-25777b00-6e7f-11e9-9fa2-4d06556c7d83.png)

Also does this have that famous "KSPe" dependency? We would need to make sure that's handled properly.

**Comment by meirumeiru** [comment]
ok, I have removed the "Pre-release"... it's a "Release" now
and no, there are no dependencies at all

**Comment by HebaruSan** [comment]
Cool, it validates properly now.
It sounds like you're planning big changes soon, so please check back with us if there are any new dependencies, folders to install, etc.

**Comment by meirumeiru** [comment]
thanks
yes, I'll inform you about changes
