### ISSUE TITLE
Module Manager

### ISSUE THREAD

**Issue by raidernick** [KSP-CKAN/NetKAN#7192]
@HebaruSan @Olympic1 

Can we get the module manager netkan updated for 1.7. The current version (4.0.2) works perfectly fine in 1.7. It not being marked for this is preventing a lot of mods from being shown as compatible and we would like this updated in order to release RO as that is the only mod holding it back.

**Comment by HebaruSan** [comment]
What do you say, @sarbian?

**Comment by sarbian** [comment]
That I was sure I made the change a while ago...
Will do right now
