### ISSUE TITLE
RO and KJR netkan issue

### ISSUE THREAD

**Issue by raidernick** [KSP-CKAN/NetKAN#7203]
Ok so we no longer need KJR to do a "provides" as we aren't supporting a RO release that can use either the original KJR or Continued. I removed the dependency "KerbalJointReinforcement" and just set "KerbalJointReinforcementContinued" to avoid having the original listed anymore. CKAN is still displaying RO as incompatible for 1.6.1 because it's showing the original KJR as a dependency even though it shouldn't be.

https://github.com/KSP-CKAN/CKAN-meta/blob/master/RealismOverhaul/RealismOverhaul-v12.7.0.ckan

That shows that the meta bot indexed it correctly at least.

Also I would like to point out KJR NEXT should NOT be able to provide for KJR. RO/RSS does not support next at all. It has known issues with the RO/RSS suite of mods, in fact both RO and KJR Continued conflicts with next yet ckan seems to be allowing people to install it with these mods.

**Comment by HebaruSan** [comment]
Not really following the first issue. The relationship shows up as you describe, and it's compatible:

![image](https://user-images.githubusercontent.com/1559108/58291376-b4a3ee80-7dac-11e9-8df3-35fb6234c705.png)

Can you show us that problem?

**Comment by HebaruSan** [comment]
Similarly for the second point, if I try to install both KJRs, they're highlighted red, the status bar explains the conflict, and the apply changes button is disabled:

![image](https://user-images.githubusercontent.com/1559108/58291809-58da6500-7dae-11e9-96a3-45c63c323bd0.png)

Will need reproducible description of that.

**Comment by DasSkelett** [comment]
> CKAN is still displaying RO as incompatible for 1.6.1 because it's showing the original KJR as a dependency even though it shouldn't be.

Did you refresh the modlist?

**Comment by raidernick** [comment]
Yes I refreshed it several times and I even deleted all the ckan cache files and restarted it to regenerate everything. I ended up just trying it on a new computer which I've never used it on and it has it listed correctly. So it turns out there is something preventing my current pc from updating the index.
