### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Jackal-Shadowwolf** [KSP-CKAN/NetKAN#7252]
[error.log](https://github.com/KSP-CKAN/NetKAN/files/3293368/error.log)
[output_log.txt](https://github.com/KSP-CKAN/NetKAN/files/3293369/output_log.txt)

**Comment by HebaruSan** [comment]
Try the modded support subforum;

https://forum.kerbalspaceprogram.com/index.php?/forum/70-technical-support-pc-modded-installs/

The CKAN team doesn't cause or fix in-game bugs.

**Comment by Jackal-Shadowwolf** [comment]
i cant add the files

**Comment by Jackal-Shadowwolf** [comment]
please help

**Comment by HebaruSan** [comment]
Don't add the files. Stop using this web site. Click on the link and post on the forum.

**Comment by Jackal-Shadowwolf** [comment]
https://forum.kerbalspaceprogram.com/index.php?/topic/185517-help-pls-crashed/

**Comment by HebaruSan** [comment]
Yes, that is the right place to ask this. Good luck.

**Comment by Jackal-Shadowwolf** [comment]
thanks.  :) no reply  yet
