### ISSUE TITLE
[Bug] Hangar by allista no longer being indexed

### ISSUE THREAD

**Issue by willwill2will54** [KSP-CKAN/NetKAN#7255]
New updates to the Hangar mod by allista is not being indexed. I do not know what is causing the issue, but the kref points at the space dock entry for the mod, which **has** released these updates. I have also opened another [report](https://github.com/allista/hangar/issues/200) in allistas repo, as that is where the main NetKan file is located.

**Comment by allista** [comment]
No, CKAN indexes all my mods, including Hangar, alright (see below).

The problem, though, may be that it depends on the CommunityResourcePack that haven't been updated for a while; so unless you set supported KSP versions in CKAN client manually you won't see the Hangar in the list of compatible mods.

![CKAN v1 26 2 - KSP 1 7 0 2483    --    -home-storage-Games-Projects-AT_KSP_Plugins-KSP-test-KSP_1 7 0_205](https://user-images.githubusercontent.com/6084589/59604144-fa39aa00-9113-11e9-9de3-9d27fadbe035.png)

**Comment by DasSkelett** [comment]
Also, for the latest update (3.3.7), our bot had some problems with indexing. It should be fixed now, but it takes some time until he catches up.
See https://github.com/KSP-CKAN/NetKAN-bot/pull/92 and https://github.com/KSP-CKAN/CKAN/pull/2783.

**Comment by DasSkelett** [comment]
Newest release is now indexed and should be available in the client:
https://github.com/KSP-CKAN/CKAN-meta/commit/f82a2dd1210c33c49a3b07ef713e6715457b441f
