### ISSUE TITLE
Error when installing Tundra Exploration

### ISSUE THREAD

**Issue by RabblerouserGT** [KSP-CKAN/NetKAN#7270]
CKAN vers. 1.26.2
KSP vers. 1.7.2.2556
Operating System: Windows 7 Professional Service Pack 1
**NO** manual changes to GameData
Affected mod: "Tundra Exploration - Stockalike Dragon V2 and Falcon 9" (Identifier: TundraExploration)

What steps did I take?
- Checked the mod in CKAN to install
- Follow all the steps to install, "Apply Changes" followed by "Apply" on the next screen
- Progress bar goes all the way to 100% before [Error 1](https://i.imgur.com/ljwbGKd.png) appears.
- Pressing "Dismiss" is the only option, which brings us to [Error 2](https://i.imgur.com/628CjAD.png).

You'd expect it to install the mod with no questions asked. However, it seems something goes awry that forces forces the program to halt. Pressing "Continue" on Error 2 leaves the window up but renders buttons, menus, etc inoperable.

EXTRA INFO: I should note I have 1.6 set in Compatible Versions as well.

EXTRA INFO 2: It seems to pick on Tundra specifically. I can install the dependencies and supported mods with no problem.

### Error 1 Screenshot Text
```
CKAN.InvalidModuleFileKraken: TundraExploration 1.5.0: C:\Users\Dell-XPS\AppData\Local\Temp\tmp4E65.tmp has length 135760085, should be 135760122
   at CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadsComplete(NetModuleCache cache, Uri[] urls, String[] filenames, Exception[] errors)
```

### Error 2 Screenshot Text
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
CKAN.FileNotFoundKraken: Trying to install TundraExploration 1.5.0, but it's not downloaded or download is corrupted
   at CKAN.ModuleInstaller.Install(CkanModule module, String filename)
   at CKAN.ModuleInstaller.InstallList(ICollection`1 modules, RelationshipResolverOptions options, IDownloader downloader, Boolean ConfirmPrompt)
   at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by DasSkelett** [comment]
This release was most likely reuploaded, thus changing the file size.

Since this is the latest release, we need to remove the cached zip, right @HebaruSan?
@techman83

**Comment by RabblerouserGT** [comment]
A few questions myself.
Would you like me to try and get in contact with the mod author? Or is this solely something to do with CKAN's internal workflow?

Also, more of a question out of curiosity since I like to know how things work. I assume this is a security function? To keep the program from delivering the wrong file?

**Comment by DasSkelett** [comment]
> Would you like me to try and get in contact with the mod author? Or is this solely something to do with CKAN's internal workflow?

Well, this time it "has already happened", so nothing the mod author can do now.
We now need to update the [metadata](https://github.com/KSP-CKAN/CKAN-meta/blob/master/TundraExploration/TundraExploration-1.5.0.ckan) of the mod to take over the new file size and hashes.
But we can't just change the file, because our bot, used to scan for new mod releases, would overwrite it again, because he has the old zip in his cache.

You could, if you want, advise the author, that to keep the download via CKAN from breaking, he should always release updates as a new version (even if it's just a one line change).



> Also, more of a question out of curiosity since I like to know how things work. I assume this is a security function? To keep the program from delivering the wrong file?

You can read through here https://github.com/KSP-CKAN/CKAN/issues/62 and here https://github.com/KSP-CKAN/CKAN/issues/77. It's a mix of security and download validation/integrity.
Furthermore, I think the hashes are used for the mirroring of FOSS licensed mods to archive.org too: https://github.com/KSP-CKAN/CKAN/issues/1682 and https://github.com/KSP-CKAN/CKAN/pull/1710

**Comment by HebaruSan** [comment]
> I tried echo 

Try `echo -n`. `echo` appends a line break by default.

**Comment by HebaruSan** [comment]
Possibly fixed in KSP-CKAN/CKAN-meta#1475, although I expect the bot to fight us on this.

**Comment by techman83** [comment]
Hmm, I actually don't see it cached.

```
netkan@ckan-bot:~$ find . -name *Tundra*zip
./Cache/D0EABB61-netkan-TundraTechnologies.zip
./Cache/2A9F6D08-netkan-TundraSpaceCenter.zip
./Cache/95145431-netkan-TundraTechnologies.zip
```

Assuming the cache expired since this and in the next run it'll update the metadata.

**Comment by HebaruSan** [comment]
This mod shares its download with TundraTechnologies; this one is the problem:

> ./Cache/95145431-netkan-TundraTechnologies.zip

**Comment by techman83** [comment]
Oh right! Thanks for pointing that out.
```
netkan@ckan-bot:~/Cache$ rm -v *TundraTec*
removed ‘95145431-netkan-TundraTechnologies.zip’
removed ‘D0EABB61-netkan-TundraTechnologies.zip’
```

**Comment by techman83** [comment]
Fixed KSP-CKAN/CKAN-meta@03f93516fec6327e69117b88f74457490fbde8a3

**Comment by politas** [comment]
Ah, it was the TundraTechnologies zip! I wondered why I couldn't find the cached file.

**Comment by politas** [comment]
I thought we'd fixed the bot to replace the cached file when it changes?

**Comment by HebaruSan** [comment]
> I thought we'd fixed the bot to replace the cached file when it changes?

Only on GitHub, not SpaceDock. GitHub's API provides the timestamps, SD's doesn't.
