### ISSUE TITLE
CKAN does not sort versions correctly

### ISSUE THREAD

**Issue by Artemonim** [KSP-CKAN/NetKAN#7274]
Mod: ResearchBodies
v1.9.9 is considered to be newer than the V1.10.0.0

**Comment by HebaruSan** [comment]
This is because JPLRepo can't make up his mind whether his version numbers are prefixed with a 'v' or a 'V'.

![image](https://user-images.githubusercontent.com/1559108/60380269-5369dd80-9a32-11e9-98b0-612993883bb1.png)
