### ISSUE TITLE
Latest toolbar (1.17.20) was released and indexed, not showing up in ckan

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7318]
I released both Toolbar and ToolbarController last night, and then updated the .netkan files to remove the unblur dependency.

The update for the ToolbarController  is visible, but the toolbar is not.
I checked the meta files, looks ok to me

**Comment by DasSkelett** [comment]
It is showing up, however you typoed the previous release version, thus it is not ordered on top:
![toolbar versions](https://user-images.githubusercontent.com/28812678/61541492-0cbf4000-aa40-11e9-8720-c2eaab208e0c.png)

**Comment by linuxgurugamer** [comment]
What typo?
Regardless, I'll do an epoch, thanks

**Comment by DasSkelett** [comment]
Shouldn't it be `1.7.17.19.1` instead of `1.17.19.1`?

**Comment by linuxgurugamer** [comment]
1.7.17.19.1  is 5 parts, which both I don't use and I don't think CKAN supports.

Previous version was 1.7.19.1
New version is 1.7.20

What's the mistake?

**Comment by DasSkelett** [comment]
Just look at the screenshot or on spacedock.

You are missing the second part the `7`.

**Comment by linuxgurugamer** [comment]
Just realized the second was a 17 instead of a 7.
Well, the epoch should fix it

**Comment by linuxgurugamer** [comment]
Thank you, sometimes the obvious isn't apparent

**Comment by DasSkelett** [comment]
No worries.

**Comment by DasSkelett** [comment]
The epoch fixes the ordering for the newest version, but `1.7.20` is still < `1.17.19.1`. But it probably doesn't really matter since `1.7.20` also covers their KSP version ranges, and will be pulled in instead.
