### ISSUE TITLE
CKAN won't launch KSP?

### ISSUE THREAD

**Issue by Pontosaurus74** [KSP-CKAN/NetKAN#7331]
When I attempt to launch KSP with CKAN, I get this error message:

"Couldn't Start KSP.
Cannot find the specified file."

I'm not really sure what this means, and how to fix it. I don't currently have any mods installed with CKAN, but the issue also occurs with mods installed. I am running it on Mac OS v10.12.6, if that helps anything. Sorry for my ignorance, I am not the most tech-savvy person, lol.

**Comment by DasSkelett** [comment]
Can you please share what's specified as the command to start KSP in CKAN?
Under Settings \> KSP command line, and copy paste what's in the text box.
