### ISSUE TITLE
[Feature] Change ASET .netkan's to not require but recommend or suggest RasterPropMonitor Core

### ISSUE THREAD

**Issue by Jacke4913** [KSP-CKAN/NetKAN#7332]
Problem
-------
ASET Avionics and ASET Props are used to extend both the now suspended Raster Prop Monitor (RPM) but also with its replacement, MOARdV's Avionic Systems (MAS).

https://forum.kerbalspaceprogram.com/index.php?/topic/160856-wip-17x-moardvs-avionics-systems-mas-interactive-iva-v101-27-july-2019/

MOARdV has decided not to include MAS in CKAN or to support CKAN installs.  MAS has to be manually installed.

In a CKAN install, I'd like to minimize the packages I have to manage manually.  I'd like to install MAS's requirements via CKAN: Module Manager, ASET Avionics, and ASET Props.  MM has no other requirements.  ASET Avionics and ASET Props both require ASET Agency, a minor extra, but also require RasterPropMonitor Core.

https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/ASETAvionics.netkan

https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/ASETProps.netkan

Both RPM and MAS apparently can co-exist in a KSP install, but I don't know which is preferred.  To properly test and use MAS, it should be installed without RPM.

Suggestions
-----------
In the .netkan's for ASET Avionics and ASET Props, change RPM Core from a requirement to either a recommendation or a suggestion.

I tried manually installing ASET Avionics and ASET Props.  However, the current CKAN (v1.26.2) doesn't recognise that these packages were installed by other means and would possibly try to install them again over top of the manual install.

**Comment by HebaruSan** [comment]
Additional note, #5254 updated or created several more ASET mods that depend on RPM.

**Comment by HebaruSan** [comment]
The author of MAS appears to contradict the premise of this suggestion here (**emphasis** added):

https://forum.kerbalspaceprogram.com/index.php?/topic/160856-wip-17x-moardvs-avionics-systems-mas-interactive-iva-v101-27-july-2019/&do=findComment&comment=3640183

> If it's a prop that does something (button, light, MFD), you need to use MAS-prefixed props for it to function in MAS.  **The ASET-prefixed props were designed for RPM.**  (Although there is nothing preventing a mix of MAS and RPM props, as long as both MAS and RPM are installed)

To me this sounds like the dependency of ASET on RPM is correct, but frankly I don't quite understand what MAS is supposed to be. Am I misinterpreting that reply?

**Comment by Jacke4913** [comment]
Hmmm.  This is now making me wonder.  Went back to the ASET posts:

https://forum.kerbalspaceprogram.com/index.php?/topic/116479-aset-avionics-pack-v-21-for-the-modders-who-create-iva/

https://forum.kerbalspaceprogram.com/index.php?/topic/116430-aset-props-pack-v15-for-the-modders-who-create-iva/

I think the original dependency was:

IVA depends on ASET and RPM
ASET depends on RPM

But MAS now adds:

MAS depends on ASET

Does MAS also add this?

MAS implements RPM enough that ASET calls to RPM are intercepted by MAS

Without that, technically MAS depends on RPM via its dependency on ASET.

I guess either a source dive or talking to MOARdV is needed.

**Comment by HebaruSan** [comment]
Those ASET forum threads unambiguously state that it depends on RPM. Closing this.
If the authors of any of these mods would like changes made, please send them our way.
