### ISSUE TITLE
Shangsheng Orbital

### ISSUE THREAD

**Issue by damonvv** [KSP-CKAN/NetKAN#7346]
Mod info
--------
* Mod name: Shangsheng Orbital
* Author(s): damonvv
* License: CC BY_NC-ND 4.0
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/187254-17x-shangsheng-orbital-v01-stockalike-newline-1-rocket/
* Download: https://spacedock.info/mod/2209/Shangsheng%20Orbital

KSP version 1.6.1 and above

For folders
Inside the zip is a "Gamedata" folder where the mod is
There's a "Ships/VAB" folder for the craft file

This mod requires KRE - Kerbal Reusability Expansion

This mod recommends: Smokescreen and Community Category Kit

**Comment by DasSkelett** [comment]
@damonvv, just FYI: For CKAN it makes a difference whether you prefix a `v` in front of the version number or not.
All versions with a `v` will be sorted above (i.e. "newer") than versions without one:
![grafik](https://user-images.githubusercontent.com/28812678/63304597-dba68980-c2e3-11e9-908f-7f4dee5dd91d.png)

I will fix it for this mod by always forcing the bot to prefix a `v`, even if there's none by default, but please pay attention to this for potential future mods.
