### ISSUE TITLE
Mod addition

### ISSUE THREAD

**Issue by jh1806** [KSP-CKAN/NetKAN#735]
{
    "spec_version": 1,
    "identifier"  : "MechJebForAll",
    "name"        : "MechJeb and Engineer for all!",
    "author"      : [ "nadseh" ],
    "version"     : "1.1.0",
    "abstract"    : "Automatically includes a MechJeb computer, Flight Engineer and Build Engineer on any craft that includes a probe core or a command module.",
    "ksp_version" : "0.90",
    "license"     : "GPL-3.0",
    "download": "http://addons.curse.cursecdn.com/files/2225/270/MechJebAndEngineerForAll-v1.1.0.0.zip",
    "depends": [
        { "name": "MechJeb2" }
    ]
}

**Comment by Dazpoet** [comment]
This has now been added, Issue can be closed
