### ISSUE TITLE
How to choose one of multiple version files

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7357]
I have a mod which has a main .version file, and there are three other .version files inside, for the three different dlls in the mod.

For now, I had to rename the secondary .version files.  I'd like to have them available for AVC, is there a way to tell netkan to use a specific .version file in the zip (or even from a file on github)?

**Comment by HebaruSan** [comment]
> is there a way to tell netkan to use a specific .version file in the zip?

Yes:

```json
    "$vref": "#/ckan/ksp-avc/NameOfFile.version",
```

or:

```json
    "$vref": "#/ckan/ksp-avc/Full/Path/To/File.version",
```

https://github.com/KSP-CKAN/CKAN/blob/6bbcf0b213598d96ad324b066b8637c93efe210a/Netkan/Services/ModuleService.cs#L126-L150

> (or even from a file on github)

No.

**Comment by linuxgurugamer** [comment]
That's perfect.  I only mented the file on github as a secondary possibility.
Thanks, I'll get the mod and the netkan updated this evening.
I'm going to leave this open until then (make it easier to find)

**Comment by HebaruSan** [comment]
> I only mented the file on github as a secondary possibility.



Rectifying an error I made, I think the options are actually:

```json
    "$vref": "#/ckan/ksp-avc/Full/Path/To/File.version",
```

or:

```json
    "$vref": "#/ckan/ksp-avc/RegularExpressionMatchingPathToFile",
```

The `NameOfFile.version` usage only works because it can be interpreted as a regex (which matches the path).

**Comment by linuxgurugamer** [comment]
lucky me, the "full path" worked because the file was in the root of the mod dir
