### ISSUE TITLE
Mk2 Stockalike Expansion has incorrect length

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7359]
Following error occurs when trying to download this:

CKAN.InvalidModuleFileKraken: Mk2Expansion 2:1.8.6: C:\Users\jbb\AppData\Local\Temp\tmpB347.tmp has length 27702121, should be 27702381
   at CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error)

A bad length or checksum should not cause a crash, it needs to be handled safely

**Comment by HebaruSan** [comment]
@techman83 , please purge 348CF9C0-netkan-Mk2Expansion.zip from the bot's cache.

**Comment by HebaruSan** [comment]
Should be OK now: https://github.com/KSP-CKAN/CKAN-meta/commit/8d3720cb8886de5389c402bc4ece51526819839b

**Comment by DasSkelett** [comment]
We definitely need to fix the error handling on mod installations though.
If an error occurs, CKAN crashes most of the times, only some errors are catched and shown in CKAN's own error dialog, but even if, it mostly renders the GUI unusable, and it needs to be forced to quit via task manager or similar.
