### ISSUE TITLE
InvalidModuleFileKraken: Mk2Expansion 

### ISSUE THREAD

**Issue by GJNelson7030** [KSP-CKAN/NetKAN#7364]
**Background
----------
* Operating System:** Windows 10 (64 bit)
*** CKAN Version:** v1.26.4
*** KSP Version:** v1.7.3 and all DLC

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
None

**Problem
--------------------------------------------------------------------------------------------------------**
I'm getting the following error message when I try to download the "Mk2 Stockalike Expansion"...
```
CKAN.InvalidModuleFileKraken: Mk2Expansion 2:1.8.6: C:\Users\Gregory\AppData\Local\Temp\tmp55C6.tmp has length 27577119, should be 27702121
   at CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error)
```

Steps to reproduce
Attempt to update or install this mod.

Expected behavior
Mod should load via CKAN.

**CKAN error code (if applicable):**<details><summary>Click to expand</summary>
```
CKAN.InvalidModuleFileKraken: Mk2Expansion 2:1.8.6: C:\Users\Gregory\AppData\Local\Temp\tmp55C6.tmp has length 27577119, should be 27702121
   at CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error)
```

**Comment by HebaruSan** [comment]
Wow, two in-place replacements for the same download! (Previous was #7359.)

@techman83 , please purge 348CF9C0-netkan-Mk2Expansion.zip from the bot's cache again.

**Comment by GJNelson7030** [comment]
Is there anything I can do to fix this? Any help I can offer?

**Comment by DasSkelett** [comment]
@HebaruSan the mod is also released on GitHub, we could change the kref to it.

**Comment by HebaruSan** [comment]
@GJNelson7030 no, we know what the problem is, it just takes some time to get it sorted.

@DasSkelett I've made an attempt to explain why replacing downloads is a bad idea in general on this mod's forum thread. With luck this won't happen again (for this mod).

**Comment by GJNelson7030** [comment]
Thanks y'all, for taking action on this. CKAN is my primary means of tracking and updating the mods I use with KSP.

**Comment by techman83** [comment]
I have purged the file from the cache!

**Comment by HebaruSan** [comment]
And there's the update: https://github.com/KSP-CKAN/CKAN-meta/commit/b1258d4e0e4513b11269ece900ff10c09f46af31

**Comment by GJNelson7030** [comment]
Awesome, thanks!
