### ISSUE TITLE
kdex not pulling vref from GitHub

### ISSUE THREAD

**Issue by mwerle** [KSP-CKAN/NetKAN#7368]
In Kdex's netkan, the following is specified :

	"$vref"           : "#/ckan/ksp-avc/",

This does not seem to find the kdex.version file.

Will submit a pull request to specify the path.

**Comment by HebaruSan** [comment]
Looks like it's working fine.

https://github.com/KSP-CKAN/CKAN-meta/blob/master/KDEX/KDEX-v1.11.3.ckan

```json
    "ksp_version_min": "1.0.0",
    "ksp_version_max": "1.6.99",
```

What specific problem leads you to believe it's not finding it?

**Comment by mwerle** [comment]
Isn't it supposed to pick up the version file from master? I updated kdex to mark it compatible with1.7.x ages ago but ckan hasn't picked that up.

Release 1.11.4.

**Comment by HebaruSan** [comment]
Oh. 1.11.4 isn't indexed at all because it has no downloadable assets:

![image](https://user-images.githubusercontent.com/1559108/64078838-913ee880-cca5-11e9-9354-54ad7269d0a8.png)

**Comment by HebaruSan** [comment]
And the change to the remote version file isn't picked up because the VERSION property doesn't match:

In 1.11.3 download, BUILD is 10, on GitHub it is 11:

```json
    "VERSION":
    {
        "MAJOR":1,
        "MINOR":11,
        "PATCH":3,
        "BUILD":10
    },
```

https://raw.githubusercontent.com/mwerle/kdex/master/GameData/masTerTorch/kdex.version

```json
    "VERSION":
    {
        "MAJOR":1,
        "MINOR":11,
        "PATCH":3,
        "BUILD":11
    },
```

**Comment by mwerle** [comment]
Hmm.

I didn't create any because apart from the version file there's no changes. Figured no need for people to have to redownload.

Thought it was similar to marking a mod compatible with a new version of KSP on Spacedock. That works without uploading a new file...

**Comment by mwerle** [comment]
Hmm.  I don't consider the BUILD to be part of the version. That's just a tag for recompile/repackaging.

ok. so ckan needs that to remain the same as well. noted.

will have to pick this up tomorrow, sorry. 1am here.

**Comment by HebaruSan** [comment]
I see two options at this point:

1. Change `URL.BUILD` in the remote version file to 10. This would make the bot pull the version info in that file for 1.11.3, which would then be marked as compatible up to 1.7.99. Maybe delete the 1.11.4 release to reduce confusion.
2. Create ZIP files for 1.11.4 and attach them to the release. This would then index that version in CKAN according to whatever is in its .version file.

Either one would work, but option 1 is probably cleaner if indeed there are no changes.

**Comment by HebaruSan** [comment]
> Hmm. I don't consider the BUILD to be part of the version. That's just a tag for recompile/repackaging.

Maybe for you, but others use it to distinguish real versions:

https://github.com/KSP-CKAN/CKAN-meta/tree/master/KSPInterstellarExtended

**Comment by HebaruSan** [comment]
Looking into this a bit further, the filtering out of 1.11.4 is done by **GitHub**, not CKAN; it doesn't show up in the API's release listing at all:

https://api.github.com/repos/mwerle/kdex/releases?per_page=100

**Comment by HebaruSan** [comment]
> ckan needs that to remain the same as well.

Confirmed that KSP-AVC and MiniAVC have the same requirement:

https://github.com/linuxgurugamer/KSPAddonVersionChecker/blob/1274c6751dcf109614741f01f5e89babff1bb617/MiniAVC/Addon.cs#L201-L207

https://github.com/linuxgurugamer/KSPAddonVersionChecker/blob/1274c6751dcf109614741f01f5e89babff1bb617/MiniAVC/VersionInfo.cs#L260-L266

**Comment by mwerle** [comment]
Apologies, I was already 3/4 asleep last night and tapping away on my phone. I wasn't meaning you should change the way build numbers are treated, it was just what I think of them as.

Thank you so much for investigating and pointing out the various reasons/gotchas why things weren't working.  I'll try option (1) suggested by @HebaruSan a few comments up.  If that doesn't work out, I'll try a full point release.

**Comment by HebaruSan** [comment]
Good news, the bot picked up the changes to the remote version file in its latest pass:

https://github.com/KSP-CKAN/CKAN-meta/commit/a392e65288c6291a339043c894f305046f06afec

**Comment by mwerle** [comment]
Awesome. Thanks for confirming and I'll try to remember for next time.

Thanks for all your help.
