### ISSUE TITLE
Issue installing KopernicusExpansionContinued mods

### ISSUE THREAD

**Issue by RGIves** [KSP-CKAN/NetKAN#7378]
I was attempting to add mods to KSP using CKAN, when an error showed up. I checked the version of CKAN and refreshed everything, however the problem persisted. The error report said that it may be a packaging bug. 

File      : GameData/KopernicusExpansion/Plugins/KEX-Common.dll
Installing Mod : KopernicusExpansionContinued-EmissiveFX release-1.7.1-5
Owning Mod: KopernicusExpansionContinued-CometTail
CKAN Version   : v1.26.4

**Comment by HebaruSan** [comment]
Thanks for letting us know, this should be fixed if you wait 10 minutes or so and click Refresh.
