### ISSUE TITLE
Community Delta-V Maps

### ISSUE THREAD

**Issue by Pepepito** [KSP-CKAN/NetKAN#7390]
{
    "spec_version" : "v1.0",
    "identifier"   : "ksp-cheat-sheet",
    "$kref"        : "#/ckan/spacedock/2234",
    "license"      : "CC-BY-NC-SA-4.0",
    "ksp_version"  : "any",
    "install": [ {
	    "file"      : "GameData",
        "install_to": "GameData"
    } ],
}

**Comment by HebaruSan** [comment]
Already indexed as CommunityDeltaVMaps, but thanks!

https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/CommunityDeltaVMaps.netkan

**Comment by Pepepito** [comment]
I have downloaded the latest .ckan package and i can't see this mod. (is have KSP 1.7.1 installed).
 CKAN-meta/CommunityDeltaVMaps/CommunityDeltaVMaps-2.6.ckan file is set with :

- "ksp_version": "1.6.1",
So is specificly set to be compatible with a compatible KSP version installed.
I have the KSP version 1.7.1 installed and my CKAN don't show it if i don't set a "Compatible KSP Version" at 1.6 . (the function into the settings menu)

This is need to be modified with the variable :

- "ksp_version" : "any",

_This mod on Spacedock (https://spacedock.info/mod/1914) is marked as "Outdated", i don't know if it have an importance_

Thanks.
