### ISSUE TITLE
[Mod] Contract Pack: CommNet Relays

### ISSUE THREAD

**Issue by yalov** [KSP-CKAN/NetKAN#7398]
Mod info
--------
* Mod name: Contract Pack: CommNet Relays
* Author(s): Kerbas_ad_astra
* License: Contract configuration files are released under the GPL v3 license
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/116789-13-14-15-16-contract-pack-commnet-relays-210-2019-jan-13/
* Download: https://github.com/Kerbas-ad-astra/CommNet-Relays/releases
 
 -------

* Mod name: Contract Pack: Career Evolution 
* Author(s): pap1723
* License: CC-BY-NC-SA
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/162205-122-13-career-evolution-contract-pack/
* Download: https://github.com/pap1723/Career-Evolution/releases

----------

* Mod name: Interkosmos
* Author(s): Well
* License: Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/185337-173-interkosmos-02-science-parts/
* Download: https://github.com/AstroWell/Interkosmos/releases

**Comment by HebaruSan** [comment]
Have the authors given permission?

**Comment by yalov** [comment]
They have not. But I checked their absence in the opt-out list

**Comment by HebaruSan** [comment]
Would you mind asking them?

**Comment by yalov** [comment]
@Kerbas_ad_astra, @pap1723, @Well, do you like having your mods available in the CKAN? 
@HebaruSan kindly have made the .ckan files

**Comment by HebaruSan** [comment]
Might want to ask on their forum threads. Sometimes people don't receive or react to GitHub notifications.

**Comment by yalov** [comment]
I already PM them on the forum and other places:
Well wants to opt-out-list,
pap1723 "would be perfectly fine with that"
Kerbas-ad-astra didn't answer

**Comment by HebaruSan** [comment]
Sounds good, we'll move forward with pap1723's, then.
