### ISSUE TITLE
[Mod] SETI Mods become increasingly broken over time

### ISSUE THREAD

**Issue by mkalte666** [KSP-CKAN/NetKAN#7406]
The SETI Mods by Y3mo (including, but not limited to) SETI-ProbeParts, SETI-Rebalance, SETI_UbM, ... are incompatible with current module manager versions and show werid buggy behaviour on current ksp versions. There are also quite a few reccomendations/suggestions not updated despite there being newer versions.  The mod author seems to be inactive.

I suggest that they are marked incompatible with newer KSP versions. The last version the mods officially supported was 1.3.x

**Comment by HebaruSan** [comment]
The netkans for those mods are all hosted on @Y3mo's own repo. He will have to handle making the updates (and should probably have a say in the matter / be notified of the problem).

- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/SETI-ProbeParts.netkan
- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/SETI-RebalanceMaterialsGoo.netkan
- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/UnmannedBeforeManned.netkan

Submitted Y3mo/SETI-NetKAN#2 to help get the ball rolling on that.
