### ISSUE TITLE
PlanetaryDiversity updated in netkan, not in ckan

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7415]
I updated the PlanetaryDiversity to look at Spacedock.info, but even though its in the netkan, the CKAN is still showing the old github version

**Comment by linuxgurugamer** [comment]
@HebaruSan

**Comment by linuxgurugamer** [comment]
Ah well, never mind, I just forced a rebuild and it worked this time

**Comment by HebaruSan** [comment]
Just a guess, but merging five PRs for the same netkan in rapid succession may have tripped up the webhooks. Next time if you specify what you're trying to accomplish we can take a look at it and validate it to get the desired outcome in fewer tries.

**Comment by linuxgurugamer** [comment]
probably.  I didn't expect to need to do more than 1.
