### ISSUE TITLE
StockalikeRealismOverhaul

### ISSUE THREAD

**Issue by HyperFunOriginal** [KSP-CKAN/NetKAN#7422]
Mod info
--------
* Mod name: Stockalike Realism Overhaul
* Author(s): HyperFun
* License: DO WHATEVER YOU WANT
* Homepage: 
* Download: https://spacedock.info/mod/2239/Stockalike%20Realism%20Overhaul

**Comment by DasSkelett** [comment]
That mod is already indexed https://github.com/KSP-CKAN/NetKAN/pull/7402.

**Comment by HebaruSan** [comment]
That netkan is missing (but the .ckan exists):

https://github.com/Space-Duck/NetKAN/blob/master/NetKAN/StockalikeRealismOverhaul.netkan

#7408 is missing, too. Kind of looks like KSP-CKAN/NetKAN-Infra#33, but the bot doesn't push to NetKAN.

**Comment by HebaruSan** [comment]
Yup!

![image](https://user-images.githubusercontent.com/1559108/66481704-0bae1580-ea67-11e9-8002-a9b3c78c7376.png)

**Comment by HyperFunOriginal** [comment]
It is an older version. I want to update it!
