### ISSUE TITLE
StockalikeRealismOverhaul Update

### ISSUE THREAD

**Issue by HyperFunOriginal** [KSP-CKAN/NetKAN#7428]
Mod info
--------
* Mod name: Stockalike Realism Overhaul
* Author(s): HyperFun
* License: DO WHATEVER YOU WANT
* Homepage: https://spacedock.info/mod/2239/Stockalike%20Realism%20Overhaul
* Download: https://spacedock.info/mod/2239/Stockalike%20Realism%20Overhaul

**Comment by HyperFunOriginal** [comment]
Help me update urgently!

**Comment by HyperFunOriginal** [comment]
If you can, help me update my mod on CKAN every 2 weeks. Thanks a lot!

**Comment by DasSkelett** [comment]
See https://github.com/KSP-CKAN/CKAN-meta/pull/1515, I added the two latest versions.
Our webhook for SpaceDock seems to be down currently, we are working on it.

**Comment by HyperFunOriginal** [comment]
Can you let me know how to update my mod on CKAN manually if possible. Thanks!

**Comment by DasSkelett** [comment]
Well, you would have to build CKAN from source yourself if you want to, because you need a tool called NetKAN.

**Comment by HebaruSan** [comment]
Netkan is available here:
- https://ckan-travis.s3.amazonaws.com/netkan.exe

**Comment by DasSkelett** [comment]
Oh that's nice, didn't know that.
In this case:
1) Donwload the netkan.exe
2) Check if your mod version has already been indexed by the bot (you should give it some time, about 2 hours). Either check in the client, or here: https://github.com/KSP-CKAN/CKAN-meta
3) If not, download the netkan file for your mod: https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/StockalikeRealismOverhaul.netkan and save it in the same folder as the netkan.exe.
4) Run `netkan.exe StockalikeRealismOverhaul.netkan`
5) A new file named StockalikeRealismOverhaul-[version].ckan should appear.
6) Upload this file in the StockalikeRealismOverhaul folder of the CKAN-meta repository and create a pull request

**Comment by HyperFunOriginal** [comment]
Right now, I can't reach SpaceDock for because my connection would time out but everything else is in order.

**Comment by HyperFunOriginal** [comment]
None of my devices could reach SpaceDock!? What is happening?

**Comment by HyperFunOriginal** [comment]
Evidence suggests that the entire server is down! lets hope that it doesn't take every mod on there down with it!

**Comment by HyperFunOriginal** [comment]
Okay, it's just extremely slow that my browser stops trying to connect. Phew!

**Comment by DasSkelett** [comment]
> None of my devices could reach SpaceDock!? What is happening?

If all your devices fail to connect to SpaceDock, it's best to check SpaceDock's forum thread for information, as this is for sure not a problem with CKAN, but the website itself.

As you can read in [this comment](https://forum.kerbalspaceprogram.com/index.php?/topic/170865-spacedockinfo-mod-hosting-site/&do=findComment&comment=3684863), it is a planned downtime. It will be back up shortly.
