### ISSUE TITLE
StockalikeRealismOverhaul Update (again)

### ISSUE THREAD

**Issue by HyperFunOriginal** [KSP-CKAN/NetKAN#7431]
Mod info
--------
* Mod name: StockalikeRealismOverhaul
* Author(s): HyperFun
* License: DO WHATEVER YOU WANT
* Homepage: https://spacedock.info/mod/2239/Stockalike%20Realism%20Overhaul
* Download: https://spacedock.info/mod/2239/Stockalike%20Realism%20Overhaul

**Comment by HyperFunOriginal** [comment]
Oops! There seems to already been updated!

**Comment by DasSkelett** [comment]
Please stop opening more issues for the same case, this doesn't help.

The problem with the webhook is resolved (see https://github.com/KSP-CKAN/NetKAN-Infra/pull/55), and as soon as SpaceDock is back up, everything should work normally again, and your mod  updates will be indexed automatically.
