### ISSUE TITLE
Stockalike Realism Overhaul Parts Pack

### ISSUE THREAD

**Issue by HyperFunOriginal** [KSP-CKAN/NetKAN#7434]
Mod info
--------
* Mod name: Stockalike Realism Overhaul Parts Pack
* Author(s): HyperFun
* License: Do whatever you want
* Homepage: https://spacedock.info/mod/2251/Stockalike%20Realism%20Overhaul%20Parts%20Pack
* Download: https://spacedock.info/mod/2251/Stockalike%20Realism%20Overhaul%20Parts%20Pack

**Comment by HebaruSan** [comment]
Duplicate of #7433

**Comment by HyperFunOriginal** [comment]
The mod isn't showing up. For CKAN installations, remove step 3 & 4 and ignore physics.cfg file. Thanks a lot!
