### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by JustaSimpleUser** [KSP-CKAN/NetKAN#7439]
Mod info
--------
* Mod name: Toolbar (Toolbar Continued on the Forums)
* Author(s): LinuxGuruGamer
* License: BSD-2-clause
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/161857-13-*
* Download: https://github.com/linuxgurugamer/ksp_toolbar

This mod's Version data shows Toolbar v1.7.17.15 as being compatible with KSP v1.5.1 and later, whereas Toolbar version 1.7.22.2 (the latest) is for KSP 1.7.1-3.  In CKAN, this mod is displaying v1.7.17.15 as compatible with KSP 1.8 which is incorrect.

**Comment by HebaruSan** [comment]
Thanks for letting us know!
