### ISSUE TITLE
RadialEngineMounts mod for indexing

### ISSUE THREAD

**Issue by teejaye85** [KSP-CKAN/NetKAN#744]
I've got a .netkan file that tests nicely.

Couldn't possibly be more overwhelmed by this github business, though:)  Where should I throw the file?

Thanks in advance, and I LOVE CKAN!!!

**Comment by TeddyDD** [comment]
If you not into git workflow yet you can paste the netkan here and someone create pull request

**Comment by teejaye85** [comment]
The file should be called "RadialEngineMountsPPI.netkan

content should be:

[CODE]
{
    "spec_version" : 1,
    "identifier"   : "RadialEngineMountsPPI",
    "$kref"        : "#/ckan/kerbalstuff/153",
    "x_netkan_license_ok": true
}
[/CODE]

**Comment by TeddyDD** [comment]
It's quiet simple however you need to know basics of git (there is plenty of tutorials so you can learn it quickly, you need to know how to stage and commit files, switch branches and clone repositories)
**Warning:** I'm an artist not a programmer, if I'm doing something wrong please correct me!

**Basic setup**
- First you have to fork NetKAN repo (it works for CKAN-meta too) then clone it to your PC.
- Add original (not forked) NetKAN repo as remote 
```git remote add upstream https://github.com/KSP-CKAN/NetKAN.git```

**Adding new netkan**
- update your local repo and your fork on github: ```git pull upstream master``` and ```git push```
- create new branch ```git checkout -b AddedModXYZ``` (of course you can choose any name for branch
- write your .netkan file and commit it
- send your commits to your github fork ```git push --set-upstream origin  AddedModXYZ```
- open your github fork in browser and [create pull request](https://help.github.com/articles/using-pull-requests/)
- when your PR will be merged you can repeat first step ( update your local repo and your fork on github) and delete your local branch ```git branch -d  AddedModXYZ```

**Comment by teejaye85** [comment]
Thanks so much for the detailed walkthrough.  I'll give it a go

**Comment by Dazpoet** [comment]
Since I see that the mod is now in NetKAN I'll close this issue.

**Comment by teejaye85** [comment]
Thanks!  Also so new to github that I didn't realize threads needed closing.
