### ISSUE TITLE
Updated mods on Spacedock not being updated

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7444]
I've been updating my mods, and noticed that the ones I did today (Champagne Bottle Redux, ConstantTWR) were not updated after I updated them on Spacedock

**Comment by HebaruSan** [comment]
https://github.com/KSP-CKAN/CKAN-meta/commit/1b4f8868c97408a1618c930be23ad0950a813826

**Comment by HebaruSan** [comment]
Should be fixed in KSP-CKAN/NetKAN-Infra#64. Let us know if you notice this again.

**Comment by linuxgurugamer** [comment]
Thank you

**Comment by linuxgurugamer** [comment]
Can you do CrewQueueTwo as well, hasn't updated in the past 4 hours (I updated it this morning)

**Comment by HebaruSan** [comment]
https://github.com/KSP-CKAN/CKAN-meta/commit/f5e14601393206e131b06b27d509bfc9b75de957
https://github.com/KSP-CKAN/CKAN-meta/commit/c7fb50ebbba20194ea04492df0f78e0d18e41ca5
