### ISSUE TITLE
CurseForge blocking "bots" from downloading mods

### ISSUE THREAD

**Issue by ihsoft** [KSP-CKAN/NetKAN#7446]
I've updated my mod [KIS](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/KIS.netkan) more than a day ago, but it's still not in the database.

When I try to run NetKAN locally, I get this:
```
K:\work\KSP>netkan.exe --version
v1.26.5+cbcd3ac55958

K:\work\KSP>netkan.exe --verbose KIS.netkan
42 [1] INFO CKAN.NetKAN.Program (null) - Transforming KIS.netkan
105 [1] INFO CKAN.NetKAN.Program (null) - Finished reading input
285 [1] INFO CKAN.KSPManager (null) - Loading KSP instances from registry
298 [1] INFO CKAN.KSP (null) - Initialising O:/SteamLibrary/SteamApps/common/Kerbal Space Program/CKAN
299 [1] INFO CKAN.KSP (null) - Initialised O:/SteamLibrary/SteamApps/common/Kerbal Space Program/CKAN
321 [1] INFO CKAN.NetKAN.Processors.Inflator (null) - Using main CKAN meta-cache at C:\Users\IH\AppData\Local\CKAN\downloads
494 [1] INFO CKAN.NetKAN.Validators.HasIdentifierValidator (null) - Validating that metadata contains an identifier
495 [1] INFO CKAN.NetKAN.Validators.KrefValidator (null) - Validating that metadata contains valid or null $kref
504 [1] INFO CKAN.NetKAN.Processors.Inflator (null) - Input successfully passed pre-validation
509 [1] INFO CKAN.NetKAN.Transformers.CurseTransformer (null) - Executing Curse transformation with #/ckan/curse/228561
509 [1] INFO CKAN.NetKAN.Sources.Curse.CurseApi (null) - Calling https://api.cfwidget.com/project/228561
1596 [1] FATAL CKAN.NetKAN.Program (null) - The remote server returned an error: (403) Forbidden.
```

Tried to load "https://api.cfwidget.com/project/228561" from the browser and had no issues - it loads just fine.

**Comment by HebaruSan** [comment]
There's a step missing from the log. api.cfgwidget.com is not failing, rather these are:

- https://kerbal.curseforge.com/projects/228561
- https://www.curseforge.com/kerbal/ksp-mods/kerbal-inventory-system-kis/download/2718071/file

Hmm, looks like CurseForge may have configured their servers to block non-browser clients:

```
$ wget https://www.curseforge.com/kerbal/ksp-mods/kerbal-inventory-system-kis/download/2718071/file
--2019-10-24 10:43:08--  https://www.curseforge.com/kerbal/ksp-mods/kerbal-inventory-system-kis/download/2718071/file
Resolving www.curseforge.com (www.curseforge.com)... 104.19.147.132, 104.19.146.132, 2606:4700::6813:9384, ...
Connecting to www.curseforge.com (www.curseforge.com)|104.19.147.132|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-10-24 10:43:08 ERROR 403: Forbidden.

$ wget https://kerbal.curseforge.com/projects/228561
--2019-10-24 10:43:27--  https://kerbal.curseforge.com/projects/228561
Resolving kerbal.curseforge.com (kerbal.curseforge.com)... 104.19.146.132, 104.19.147.132, 2606:4700::6813:9284, ...
Connecting to kerbal.curseforge.com (kerbal.curseforge.com)|104.19.146.132|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-10-24 10:43:27 ERROR 403: Forbidden.
```

**Comment by Lisias** [comment]
And you will need to have JavaScript enabled too. I browse with JS and cookies disabled, and could not navigate into \#changelog with JS disabled (cookies are ok).

**Comment by ihsoft** [comment]
It seems they require some particular headers now: agent, language, and cache control. Tried this:
```
curl -v -i -o /dev/null 'https://www.curseforge.com/kerbal/ksp-mods/kerbal-inventory-system-kis/download/2718071/file' -H 'cache-control: no-cache' -H 'user-agent: CKAN' -H 'accept: text/html' -H 'accept-encoding: gzip, deflate' -H 'accept-language: en-US'
```
Got:
```
> GET /kerbal/ksp-mods/kerbal-inventory-system-kis/download/2718071/file HTTP/1.1
> Host: www.curseforge.com
> cache-control: no-cache
> user-agent: CKAN
> accept: text/html
> accept-encoding: gzip, deflate
> accept-language: en-US
>
< HTTP/1.1 307 Temporary Redirect
< Date: Thu, 24 Oct 2019 22:08:14 GMT
< Content-Length: 0
< Connection: keep-alive
< Set-Cookie: __cfduid=db9766cf29bfbafe6aadafedfec9d5a1f1571954894; expires=Fri, 23-Oct-20 22:08:14 GMT; path=/; domain=.curseforge.com; HttpOnly
< Cache-Control: private
< Location: https://edge.forgecdn.net/files/2718/71/KIS_v1.22.zip
```

**Comment by DasSkelett** [comment]
Yeah the redirect happens in the browser too, that should be fine.

However I can't recreate this, I still get a 403 on my system, with the exact same command :(

**Comment by ihsoft** [comment]
Interesting. Maybe on your system `curl` adds more headers? What's the output?

**Comment by DasSkelett** [comment]
```
> GET /kerbal/ksp-mods/kerbal-inventory-system-kis/download/2718071/file HTTP/2
> Host: www.curseforge.com
> cache-control: no-cache
> user-agent: CKAN
> accept: text/html
> accept-encoding: gzip, deflate
> accept-language: en-US
> 
< HTTP/2 403
< date: Thu, 24 Oct 2019 22:21:09 GMT
< content-type: text/html; charset=UTF-8
< set-cookie: __cfduid=d8275732b8980e49cfea9a496624093e91571955669; expires=Fri, 23-Oct-20 22:21:09 GMT; path=/; domain=.curseforge.com; HttpOnly
< cache-control: max-age=15
< expires: Thu, 24 Oct 2019 22:21:24 GMT
< x-frame-options: SAMEORIGIN
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< vary: Accept-Encoding
< server: cloudflare
< cf-ray: 52af57946c02c2f4-FRA
< content-encoding: gzip
```

The only difference I spot is that curl uses HTTP/2.

**Comment by ihsoft** [comment]
I can't believe they block by IP. Maybe it's SSL handshake?
```
* SSL connection using ECDHE-ECDSA-AES128-GCM-SHA256
* Server certificate:
*        subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=ssl962282.cloudflaressl.com
*        start date: 2018-12-13 00:00:00 GMT
*        expire date: 2019-12-11 23:59:59 GMT
*        subjectAltName: www.curseforge.com matched
*        issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*        SSL certificate verify ok.
```
You can also try this: open the URL in browser with the `Network` debug tab open. Then, do `Copy as Curl`. This was what I started from. By removing some headers and shortening the others I got my working version, but it can be something else that is missing.

**Comment by DasSkelett** [comment]
```
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=ssl962282.cloudflaressl.com
*  start date: Dec 13 00:00:00 2018 GMT
*  expire date: Dec 11 23:59:59 2019 GMT
*  subjectAltName: host "www.curseforge.com" matched cert's "*.curseforge.com"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*  SSL certificate verify ok
```
Looks totally fine too.

Direct copy-paste of Firefox's curl command same 403.
The URLs after the first redirect work.

**Comment by DasSkelett** [comment]
```sh
curl 'https://www.curseforge.com/kerbal/ksp-mods/kerbal-inventory-system-kis/download/2718071/file' \
-H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0' \
-H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' \
-H 'Accept-Language: de-DE,en;q=0.7,en-US;q=0.3' --compressed \
-H 'DNT: 1' -H 'Connection: keep-alive' \
-H 'Cookie: __cfduid=d405f001f3eb56c9ceea5fd0e5358c4e01571938792; AWSALB=sK03KcosNbjyCzWt0LSsJ+PpKjKsi2UsIrcasZ6rSTjDEESpxg4bltkNvnqgKXe/pk/0RKK2R1Vg3ShuPy5JrJr+fRLiVKaUeIamO4z1bw+qBfBjyppf4CWX4tTl; Unique_ID_v2=1147917aa3a74a64b281f9224a1f84b8; __cf_bm=47d38bba39a926dd66494e5fde9020f54c216110-1571956400-1800-AQD7sIxFghPX95+R77h/LgmgBj+7pOckaasH4y0bLTIIfpv6SjEViQF5EqKJL+VcBUV6/8yrba31WVnjqDtkiS4=' \
-H 'Upgrade-Insecure-Requests: 1' -H 'Pragma: no-cache' \
-H 'Cache-Control: no-cache' -H 'TE: Trailers'
```
That's the curl command my browser generates.
And again, the header of the answer:
```
HTTP/2 403
date: Thu, 24 Oct 2019 22:59:26 GMT
content-type: text/html; charset=UTF-8
cache-control: max-age=15
expires: Thu, 24 Oct 2019 22:59:41 GMT
x-frame-options: SAMEORIGIN
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
vary: Accept-Encoding
server: cloudflare
cf-ray: 52af8fa8fb3497cc-FRA
```

**Comment by ihsoft** [comment]
Weird. Maybe, after all, they do filter by IP. I'm running the command from a data center in Texas.

**Comment by DasSkelett** [comment]
But why does it work in my browser then? Also, via VPN to Washington it also doesn't work using curl.

**Comment by ihsoft** [comment]
My only guess, is it's something with your Curl version. Your's by default uses HTTP2, and mine uses 1.1. Maybe there are more differences in how they establish connection. It would be weird though.

**Comment by techman83** [comment]
I can get it to work with HTTP/2, but I did have to allow it to follow redirects.

```bash
➜  NetKAN-Infra git:(master) curl -v 'https://www.curseforge.com/kerbal/ksp-mods/kerbal-inventory-system-kis/download/2718071/file' \
-H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0' \
-H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' \
-H 'Accept-Language: de-DE,en;q=0.7,en-US;q=0.3' --compressed \
-H 'DNT: 1' -H 'Connection: keep-alive' \
-H 'Upgrade-Insecure-Requests: 1' -H 'Pragma: no-cache' \
-H 'Cache-Control: no-cache' -L -o /tmp/kis.zip
➜  NetKAN-Infra git:(master) curl --version     
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

**Comment by DasSkelett** [comment]
Hey fellow Kerbonauts! We have an announcement regarding CurseForge.

About two months ago, CurseForge's servers began blocking the CKAN bot's attempts to check for new versions of mods. I contacted CurseForge support, and they confirmed the problem and provided some background:

> Hey there,
>
> Unfortunately, due to the massive amount of scrappers and abuse CurseForge has been receiving, we have enabled CloudFlares bot detection. This is unfortunate since there is no way to granularly allow a whitelist through this at scale. So while these attacks persist, we will be unable to help with this situation.
>
> Apologies,
> Daniel

So it is not their intention to block CKAN, but it is an unavoidable side effect of changes they have made for other reasons.

Because of these circumstances, the CKAN will no longer be able to guarantee a successful indexing and download of mods hosted on CurseForge. If you wish to host your mods on CurseForge **and** have them listed in CKAN, we strongly recommend also hosting them on an additional platform that CKAN can access (for example, SpaceDock or GitHub).

Since CurseForge is the official mod hosting partner of Squad, I reached out to Squad regarding this issue, but have not received a response yet.

Thank you for your attention
~DasSkelett
in representation of the CKAN Team

**Comment by HebaruSan** [comment]
It does not appear that we will be able to restore Curse functionality, since the details of the blocking 
they have instituted are inconsistent from test to test and probably a moving target to stay ahead of malicious bots.

- [The wiki's Curse section](https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN#curse-guide) is updated to explain the problem and recommend other hosting
- We are down to only `DiscordRP` still hosted on Curse
  - We have reached out to its author to report the problem and offer assistance with migration (no response so far)

If Curse announces a change in their server policy in the future, we would be happy to revisit this, but for now I think that's all we can do.
