### ISSUE TITLE
KAX 2.8.0.2 not uploaded to SD yet

### ISSUE THREAD

**Issue by yalov** [KSP-CKAN/NetKAN#7448]
the last 1.8.0.2 isn't on the CKAN
https://github.com/net-lisias-ksp/KAX/releases

**Comment by DasSkelett** [comment]
Because @Lisias forgot to upload it on SpaceDock ;)
https://spacedock.info/mod/2150

**Comment by HebaruSan** [comment]
Try https://github.com/net-lisias-ksp/KAX/issues
