### ISSUE TITLE
Request to add KSP version checking via .version file to bluedog design bureau

### ISSUE THREAD

**Issue by zorg2044** [KSP-CKAN/NetKAN#7449]
Bluedog design bureau's current netkan file is handled via the Spacedock API. as such it is only marked as compatible with KSP 1.8

However the .version file in the zip will have the correct KSP compatibility info (back to ksp 1.6.1).

 We would really appreciate if you guys could set it up so that the backwards compatibility is picked up from the version file. Thanks a lot!

https://github.com/KSP-CKAN/CKAN-meta/tree/master/BluedogDB

**Comment by DasSkelett** [comment]
Done in #7450, see https://github.com/KSP-CKAN/CKAN-meta/commit/4bf8612320aa64218b06cbbd369d15c1333e5cc3

**Comment by zorg2044** [comment]
Thanks so much!
