### ISSUE TITLE
Meta data incorrect for KerbalConstruction Time

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7452]
I've created a new .netkan file for KCT-1.7.3, pointing to a new Spacedock entry (2254)

The 1.7.3 meta data looks good, but for some reason, the old KCT entry, which points to Spacedock (222) is getting the wrong version information.

There had been a problem in the previous upload, where there were two .version files in the KCT zip, but that was fixed.

Not sure if that's the cause, please help

**Comment by HebaruSan** [comment]
> getting the wrong version information

Can you be more specific? What exactly is wrong?

**Comment by linuxgurugamer** [comment]
Oh.  I was looking at the wrong CKAN.
Looks ok, sorry for the false alarm
