### ISSUE TITLE
.version file not being honored 

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7455]
This netkanfile:
https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/KerbalConstructionTime-173.netkan
points to the 1.7.3 version of KCT.

This is the .version file for 1.7.3:
`{
  "NAME": "Kerbal Construction Time",
  "URL": "http://ksp.spacetux.net/avc/KerbalConstructionTime-173",
  "DOWNLOAD": "https://forum.kerbalspaceprogram.com/index.php?/topic/182877-151-161-kerbal-construction-time-unrapid-planned-assembly/",
  "GITHUB": {
    "USERNAME": "linuxgurugamer",
    "REPOSITORY": "KCT",
    "ALLOW_PRE_RELEASE": false
  },
  "VERSION": {
    "MAJOR": 1,
    "MINOR": 4,
    "PATCH": 6,
    "BUILD": 13
  },
  "KSP_VERSION_MIN": {
    "MAJOR": 1,
    "MINOR": 6,
    "PATCH": 1
  },
  "KSP_VERSION_MAX": {
    "MAJOR": 1,
    "MINOR": 7,
    "PATCH": 3
  }
}
`

This is the meta file generated for this, it is ignoring the MIN & MAX settings and only putting in a specific version:

https://github.com/KSP-CKAN/CKAN-meta/blob/master/KerbalConstructionTime-173/KerbalConstructionTime-173-1.4.6.13.ckan

**Comment by DasSkelett** [comment]
Because the netkan file has no $vref, so it takes the version compatibility from SpaceDock.

**Comment by linuxgurugamer** [comment]
ah.  Thank you
