### ISSUE TITLE
Gravity Turn continued [Mod]

### ISSUE THREAD

**Issue by pricelessppp** [KSP-CKAN/NetKAN#7472]
Mod info
--------
* Mod name: Gravity turn continued
* Author(s): AndyMt
* License: GPL V3
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/148448-14177-gravityturn-continued-automated-efficient-launches/
* Download:https://github.com/AndyMt/GravityTurn/releases/download/1.7.7/GravityTurn_1.7.7.zip

Mod is from version 1.6 of the game but the mod Author said it should work. Also I did do a bit of play testing & it does.

**Comment by HebaruSan** [comment]
Where did the author say it should work (I assume you mean on 1.8)? The forum thread still says 1.4.
