### ISSUE TITLE
[Meta] Metadata for KerboKatz Mods Should be 1.8

### ISSUE THREAD

**Issue by Homer-S** [KSP-CKAN/NetKAN#7473]
Background
----------
* Operating System:  Windows 10
* CKAN Version: 1.26.4
* KSP Version: 1.8.0

*No manual changes to CKAN folder

Problem
-------
*CKAN lists all KerboKatz mods incorrectly as 1.4.3 maximum KSP version.

*Website here: https://kerbokatz.github.io

lists all except for SmallUtilities - EditorCamUtilities as updated to 1.8.

KerboKatzUtilities
Last release: 18.10.2019
Last version: 1.5.2-KSP1.8

AutomatedScienceSampler
Last release: 18.10.2019
Last version: 1.3.5-KSP1.8

CraftHistory
Last release: 18.10.2019
Last version: 2.2.1-KSP1.8

SmallUtilities
Last release: 18.10.2019
Last version: 1.5.4-KSP1.8

SmallUtilities - FPSLimiter
Last release: 18.10.2019
Last version: 1.5.4-KSP1.8

SmallUtilities - FPSViewer
Last release: 18.10.2019
Last version: 1.5.4-KSP1.8

SmallUtilities - PhysicalTimeRatioViewer
Last release: 18.10.2019
Last version: 1.5.4-KSP1.8

SmallUtilities - ModifiedExplosionPotential
Last release: 18.10.2019
Last version: 1.5.4-KSP1.8

SmallUtilities - RecoverAll
Last release: 18.10.2019
Last version: 1.5.4-KSP1.8

SmallUtilities - DestroyAll
Last release: 18.10.2019
Last version: 1.5.4-KSP1.8

SmallUtilities - KerbalScienceExchange
Last release: 18.10.2019
Last version: 1.5.4-KSP1.8

SmallUtilities - DailyFunds
Last release: 18.10.2019
Last version: 1.5.4-KSP1.8

**SmallUtilities - EditorCamUtilities
For Kerbal: 1.0.5
Last release: 17.09.2015
Last version: 1.2.5

**Comment by HebaruSan** [comment]
These are all metanetkans hosted on @KerboKatz's own repo. Try asking here:

- https://github.com/KerboKatz/Netkan/issues/new
