### ISSUE TITLE
Need to get entry rebuilt for Deployable Batteries

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7481]
I just updated the netkan for DeployableBatteries, and then uploaded a new version for KSP 1.7.3 to SpaceDock.  This adds a missing dependency.
I need this updated, so that I can then upload a new version for KSP 1.8 for the same thing, although that one can wait on the update since it got updated when I updated the netkan

**Comment by HebaruSan** [comment]
Here's the error it had:

> Too many .version files located: GameData/DeployableBatteries/DeployableBatteries.version, GameData/DeployableBatteries/DeployableBatteries-173.version

**Comment by linuxgurugamer** [comment]
thanks (grrr)

**Comment by linuxgurugamer** [comment]
Ok, I've fixed that and uploaded 0.1.0.5 to Spacedock.  It got indexed quickly.
I then uploaded 0.2.0.5 (for 1.8), and as of now, it has not been indexed

**Comment by techman83** [comment]
It'll be in the queue to get indexed, the work for a separate Webhook inflator isn't quite ready yet. http://status.ksp-ckan.space/

**Comment by HebaruSan** [comment]
Actually, @linuxgurugamer, did you upload both of those within 5 minutes of each other?

@techman83, using the MD5 of the netkan file as the `MessageDeduplicationId` may be preventing rapid inflations of the same module within 5 minutes.

https://github.com/KSP-CKAN/NetKAN-Infra/blob/39a237ca9cc39dcd860249d214a2e5edaea79fe5/netkan/netkan/metadata.py#L60-L66

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/using-messagededuplicationid-property.html

> If a message with a particular message deduplication ID is sent successfully, any messages sent with the same message deduplication ID are accepted successfully but aren't delivered during the 5-minute deduplication interval.

**Comment by linuxgurugamer** [comment]
I did, probably about 2 min apart

**Comment by HebaruSan** [comment]
I think that's it, then. The webhooks sent the same queue message twice within 5 minutes, and the second one got dropped by the queue.

**Comment by HebaruSan** [comment]
Let's track this with a fresh issue that doesn't have other mods and problems mixed in.
