### ISSUE TITLE
[Mod] DoubleTapBrakes

### ISSUE THREAD

**Issue by Poodmund** [KSP-CKAN/NetKAN#7489]
Mod info
--------
* Mod name: DoubleTapBrakes
* Author(s): severedsolo
* License: MIT
* Homepage: https://github.com/severedsolo/DoubleTapBrakes / https://forum.kerbalspaceprogram.com/index.php?/topic/163950-1
* Download: https://github.com/severedsolo/DoubleTapBrakes/releases

**Comment by HebaruSan** [comment]
I don't suppose you've already asked @severedsolo if he's OK with this?

**Comment by Poodmund** [comment]
![Untitled-1](https://user-images.githubusercontent.com/10106634/68546677-ee0afd80-03d0-11ea-83c0-afd710163ec0.png)

Yes he is fine with this being indexed. :D
