### ISSUE TITLE
I think CKAN is referencing an incorrect download link for DSSHU for KSP v1.8

### ISSUE THREAD

**Issue by GJNelson7030** [KSP-CKAN/NetKAN#7492]
Deep Space Surface Habitat Unit Pack for KSP v1.8 is located at this website...

https://forum.kerbalspaceprogram.com/index.php?/topic/168962-18-deep-space-surface-habitat-unit-pack/

...and this is their download link...

https://spacedock.info/mod/1622/Deep%20Space%20Surface%20Habitat%20Unit%20Pack

CKAN is currently listing the wrong website and appears to be linked to the wrong download site. When I download via CKAN, I get 4 extra CFG file, one of which is for TweakScale and causes a fatal error between TweakScale and DSSHU.

**Comment by GJNelson7030** [comment]
I checked and the download link is correct. The problem is the mod is using a TweakScale CFG that is wrong. The mod's website though is out of date and the link I provided is their new website.

Sorry, didn't wish to confuse anyone.

**Comment by DasSkelett** [comment]
CKAN is referencing SpaceDock #1622:
https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/DeepSpaceSurfaceHabitatUnitPack.netkan

The reason the "wrong" website (old Add-on Development thread) is linked is because it is set in SpaceDock as homepage.

**Comment by DasSkelett** [comment]
Oh you've been a bit faster ;)

**Comment by GJNelson7030** [comment]
Yeah, it was my bad, not a CKAN problem. I figured it out though. Thanks for responding though! Y'all are fairly fast with responses I've found.
