### ISSUE TITLE
Distant Object Enhancement Continued v2.0.0.0

### ISSUE THREAD

**Issue by TheDarkBadger** [KSP-CKAN/NetKAN#7495]
Forum Thread: https://forum.kerbalspaceprogram.com/index.php?/topic/189759-181-distant-object-enhancement-continued-v2000-12-november-2019/

NetKAN file:
[DistantObject-v2.0.0.0 NetKAN.zip](https://github.com/KSP-CKAN/NetKAN/files/3838711/DistantObject-v2.0.0.0.NetKAN.zip)

**Comment by HebaruSan** [comment]
Duplicate of #7494

**Comment by HebaruSan** [comment]
We'll take care of this in #7494.
