### ISSUE TITLE
[Mod] Ven's Stock Revamp

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [KSP-CKAN/NetKAN#7498]
Mod info
--------
* Mod name: Ven's Stock Revamp
* Author(s): Kerbas_ad_astra
* License: CC-BY
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/189732-18x-vens-stock-revamp-resurrected-v1141-mercury-delayed-12-nov-02019/
* Download: https://github.com/Kerbas-ad-astra/Stock-Revamp/releases

I've updated Ven's Stock Revamp for KSP post-1.3.  My latest release is v1.14.1 for KSP 1.8.x, but I've also 'retroactively' made releases for KSP 1.6 (v1.12.0) and 1.7 (v1.13.0) for the sake of RP-1 players.

To provide a graceful off-ramp for people wanting to try Restock, I've re-arranged the files (and duplicated some files) starting with VSR 1.13 so that the subfolder with new parts (Part Bin) is completely independent of the files needed to revamp the stock parts (Path Patches and Squad) and vice-versa.  Localization, Patches, and the other loose files are common.  I don't know if you want to go to the trouble of defining multiple mods, but the capability exists do do something like:
- "VSR Core" has Localization, Patches, and loose files, recommends VSR/VNP.  Does not conflict with Restock.
- "Ven's Stock Revamp" needs VSR Core, has PathPatches and Squad, recommends Ven's New Parts, conflicts with Restock.
- "Ven's New Parts" needs VSR Core, has Part Bin, recommends VSR.  Does not conflict with Restock.

**Comment by siimav** [comment]
Thanks, really appreciate you creating retroactive releases for also 1.6.x and 1.7.x. I think you will need to take those GH releases out of the Pre-release status before the netkan is updated? Otherwise only the latest 1.8 release would get indexed, right?
