### ISSUE TITLE
[Mod] Contract Pack: CommNet Relays (current entry is frozen)

### ISSUE THREAD

**Issue by Poodmund** [KSP-CKAN/NetKAN#7504]
Mod info
--------
* Mod name: Contract Pack: CommNet Relays
* Author(s): Kerbas_ad_astra

I wrote this all out once but GitHub decided to navigate away from the page so this will be abridged.

- Current NetKAN entry is frozen.
- Contract Pack works fine so not sure why its frozen.
- Author states in forum OP that CKAN listing is planned.
- Is there any reason why this cannot be resolved?

https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/ContractConfigurator-CommNetRelays.frozen

https://forum.kerbalspaceprogram.com/index.php?/topic/116789-13-14-15-16-17-18-contract-pack-commnet-relays-210-2019-jan-13/

**Comment by Poodmund** [comment]
Seems it was frozen because the Author never responded to the opened issue here: https://github.com/KSP-CKAN/NetKAN/issues/7398

However, on the forum mod thread OP this author states:
```
Roadmap
As my schedule permits, I'll get this mod released on CurseForge and CKAN.

If you have other suggestions, please bring them up in the KSP forum thread or raise an issue on the GitHub repo!
```

**Comment by HebaruSan** [comment]
It wasn't frozen so much as not-indexed-yet, and it wasn't because the author didn't respond as because I don't add things without author permission.

**Comment by Kerbas-ad-astra** [comment]
Yes, you can set up a config for this mod.
