### ISSUE TITLE
wrong repo and forum thread listed

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7519]
Had a report from a user:

https://forum.kerbalspaceprogram.com/index.php?/topic/188343-18x-crew-light-relit/&do=findComment&comment=3708051

re. Crew Light Relit:

Hello @linuxgurugamer :) I know you're very busy, so it's just FYI – CKAN still referes to Lion's repository and forum thread...

**Comment by DasSkelett** [comment]
Metadata is fine
https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/CrewLight.netkan
https://github.com/KSP-CKAN/CKAN-meta/blob/master/CrewLight/CrewLight-1.20.0.ckan

The client also shows the correct links:
![grafik](https://user-images.githubusercontent.com/28812678/69356553-ef1b1500-0c83-11ea-9619-e8f3de2d8c70.png)

Not sure which links the user means.

**Comment by DasSkelett** [comment]
I asked him on the forum thread, let's see.

**Comment by linuxgurugamer** [comment]
ok, thanks

**Comment by DasSkelett** [comment]
See https://forum.kerbalspaceprogram.com/index.php?/topic/188343-18x-crew-light-relit/&do=findComment&comment=3708116
This was due to incorrect version ordering, fixed in #7520.
