### ISSUE TITLE
CKAN showing wrong version of mod for KSP 1.6.1 for ToolbarController

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7543]
Please see this post for full details:

https://forum.kerbalspaceprogram.com/index.php?/topic/169509-18x-toolbar-controller-for-modders/&do=findComment&comment=3715152

Not sure why , but:
So I guess something needs a slight tweak in whatever CKAN is tweaked by so that it spits out the correct one for 1.6.1

**Comment by DasSkelett** [comment]
I'm not sure I can follow.
1.7.19 is the latest one marked as compatible for KSP 1.6.1:
![versions](https://user-images.githubusercontent.com/28812678/70440863-6f6ab400-1a93-11ea-8c21-01c488757d59.png)

The version file of any higher version states compatibility only from KSP 1.7.1 upwards, example:
```
  "VERSION": {
    "MAJOR": 1,
    "MINOR": 7,
    "PATCH": 22,
    "BUILD": 2
  },
  "KSP_VERSION_MIN": {
    "MAJOR": 1,
    "MINOR": 7,
    "PATCH": 1
  }
```

It looks like CKAN indexed them exactly as it should.

**Comment by HebaruSan** [comment]
Please describe whatever the issue here is (steps taken, expected results, actual results, etc.)

**Comment by HebaruSan** [comment]
@DasSkelett I think that's Toolbar. ToolbarController looks like this:

![image](https://user-images.githubusercontent.com/1559108/70457055-0411e980-1a75-11ea-96db-1ef48db9366d.png)

**Comment by DasSkelett** [comment]
I think the linked forum comment is about Toolbar regarding the "wrong" metadata @HebaruSan :

>> You have version 1.7.19 installed of the Blizzy toolbar, you need to install 1.7.22.2, you can get it here 

>the fact that CKAN had suggested 1.7.19, (and the fact that 1.7.22.2 said in its version file that was for 1.7.1 when I manually checked) threw me off the scent! 
 So I guess something needs a slight tweak in whatever CKAN is tweaked by so that it spits out the correct one for 1.6.1

**Comment by HebaruSan** [comment]
Hmm, maybe I'm just groggy, but I have no idea what's being said on that thread. The title here said ToolbarController, so I went with that.
