### ISSUE TITLE
Don't add tags to my mods

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7553]
Please don't add tags to my mods, I'm going to be doing an update with all my .netkans

I've written a script to make it easy for myself, using the suggested tags

Thanks

**Comment by HebaruSan** [comment]
Sorry, but I want to get lots of them done, and it's a pain to check which ones are yours. You can always fix them later if you don't like what I pick.

**Comment by linuxgurugamer** [comment]
Ok, in that case I'll wait until you are done and then will review

**Comment by HebaruSan** [comment]
I'd also like to get a consistent base laid down before we get into a full free-for-all of lots of mod authors making up their own random tags. It's tempting to hyper-customize, but the resulting user experience would be pretty frustrating.

**Comment by linuxgurugamer** [comment]
I was trying to save you work, and was only going to use the suggested tags, but that's fine

**Comment by HebaruSan** [comment]
(For what it's worth, I do also think there's room for a few more suggested tags. `combat` in particular seems pretty justifiable, and I expect to find others during this survey.)

**Comment by linuxgurugamer** [comment]
Would you like to try my script?  It will go through the .netkan files in a directory, present you with a list of possible tags, and then update the .netkan when done.  Restartable

**Comment by HebaruSan** [comment]
Thanks for the offer, but I've already got a pretty good workflow. The bottlenecks are researching the mods and waiting for the PR validation scripts, editing the metadata is the easy quick part.
