### ISSUE TITLE
[Bug] Wrong homepage was added to the InlineBallutes netkan file

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7573]
I don't know who added it, but the homepage as listed is incorrect.
It should be:

https://forum.kerbalspaceprogram.com/index.php?/topic/173733-inline-ballutes-update-thread/

**Comment by HebaruSan** [comment]
That was from #6750, fixed in dc139bb6dd489af3221e2915e5f62b17f45217f0

**Comment by linuxgurugamer** [comment]
Thank you
