### ISSUE TITLE
[Mod Request] KSPX

### ISSUE THREAD

**Issue by UniversityOfPi** [KSP-CKAN/NetKAN#758]
@ClairaLyrae would need to approve this, but KSPX is a very popular mod maintained by @StupidChris 

Kerbal Stuff page: https://kerbalstuff.com/mod/191/KSPX
Github page: https://github.com/StupidChris/KSPX
Kerbal Forum page: http://forum.kerbalspaceprogram.com/threads/107047

Should anything be disagreeable for any involved party, can a note please be made of it? Given the popularity, a request like this is likely to occur again.

**Comment by AlexanderDzhoganov** [comment]
Added in #800 with license field set to `restricted` so we comply with the no-redistribution policy. If permission is obtained to redistribute we can change the metadata.
