### ISSUE TITLE
[Incorrect Metadata] CKAN installs wrong version of Chatterer for KSP 1.7.3

### ISSUE THREAD

**Issue by nan0bug00** [KSP-CKAN/NetKAN#7620]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.26.6
* KSP Version: 1.7.3.2594

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Installed Ad Astra, some old 1.4 mods that still work, but nothing related to Chatterer

Problem
-------
**Describe the bug**

When using CKAN to manage mods for a 1.7.3 install, if you select Chatterer, it will download and install version 0.9.96, which is not the correct version for 1.7.3 and throws a bunch of notifications about it being outdated on startup

**Steps to reproduce**
* Go to CKAN, Open a 1.7.3 install
* Click on the check box next to Chatterer
* Run KSP and enjoy AVC screaming at you that the version is outdated

**Expected behavior**

Install Chatterer v. 0.9.97, which is the correct version for KSP 1.7.3

**Comment by nan0bug00** [comment]
BTW, in case it's helpful, [here is a link to 0.9.97 which is the correct version for KSP 1.7.3.](https://spacedock.info/mod/208/Chatterer/download/0.9.97)

**Comment by HebaruSan** [comment]
Thanks for letting us know!
