### ISSUE TITLE
Can't install Realism Overhaul on KSP 1.6.1

### ISSUE THREAD

**Issue by mahmoudahmed133** [KSP-CKAN/NetKAN#7680]
Background
----------
* Operating System: Windows 10 pro
* CKAN Version: 1.27.0
* KSP Version: 1.6.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
no

Problem
-------
**Describe the bug**
i try to install realism overhaul mod but SmokeScreen - Extended FX Plugin - Realism Overhaul not compatible with the currently installed version of KSP
but when i download SmokeScreen - Extended FX Plugin - Realism Overhaul alone its working

**Steps to reproduce**
* Go to...Realism Overhaul
* Click on...Realism Overhaul
* See error

**Expected behavior**

**Screenshots (if applicable)**

![Annotation 2020-02-11 051007](https://user-images.githubusercontent.com/60908446/74208633-18e54600-4c8d-11ea-9e0f-35cc8f3cede0.png)

**CKAN error code (if applicable):**

```
PLACE CODE HERE !RealismOverhaul v12.7.4 depends on SmokeScreen-RO, which is not compatible with the currently installed version of KSP
```

**Comment by HebaruSan** [comment]
Yup, it's not compatible with KSP 1.6.1. Why do you think this is indicative of a problem?

**Comment by mahmoudahmed133** [comment]
beacuse its working

**Comment by mahmoudahmed133** [comment]
> Yup, it's not compatible with KSP 1.6.1. Why do you think this is indicative of a problem?

beacuse its working

**Comment by DasSkelett** [comment]
This is a issue for the RO team. Their dependency change from SmokeScreen to SmokeScreen-RO was done a bit unfortunate.

They should either limit the latest RO version, in which they changed the dependency (which is KSP 1.7.3 only) to KSP 1.7.3.
Or change the dependency back and let the user decide which mod to install in our `TooManyModsProvide` process, hoping that they are choosing the right one.

**Comment by mahmoudahmed133** [comment]
> This is a issue for the RO team. Their dependency change from SmokeScreen to SmokeScreen-RO was done a bit unfortunate, so that users can no longer easily install RO on KSP 1.4.5 - 1.7.2.
> 
> They should either limit the latest RO version, in which they changed the dependency (which is KSP 1.7.3 only) to KSP 1.7.3.
> Or change the dependency back and let the user decide which mod to install in our `TooManyModsProvide` process, hoping that they are choosing the right one.

ok
