### ISSUE TITLE
[Mod] Rename NSSC to NotSoSimpleConstruction

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN#7688]
- #4968 indexed NSSC, which has had 4 versions released under that identifier
- #6202 indexed NotSoSimpleConstruction, a duplicate of NSSC, with 1 version released
- #7586 froze NotSoSimpleConstruction

The current maintainer would prefer NotSoSimpleConstruction (and I agree in principle, since acronyms are a pain), but changing identifiers is risky. Luckily it's only referenced in one place:

https://github.com/KSP-CKAN/NetKAN/blob/37bb4b6b6e1ad2986cd2932025f84d0e3d1d7a81/NetKAN/SimpleConstruction.netkan#L30

Submitting this issue to track the request and document investigations.

**Comment by HebaruSan** [comment]
Risks to consider:

- Current users probably have `NSSC` installed, so we would need to use `replaced_by` to create an upgrade path
- Need to update that dependency in SimpleConstruction, obviously
- What if somebody made a modpack with `NSSC` in it? (bit of a stretch, maybe)

**Comment by DasSkelett** [comment]
> What if somebody made a modpack with NSSC in it? (bit of a stretch, maybe)

Can we solve this with `NotSoSimpleConstruction` providing `NSSC`?

**Comment by HebaruSan** [comment]
OK, it's converted over now. I kind of expect some hiccups because we haven't purposely changed an identifier before so there are likely to be "unknown unknown"-type problems, but this will be an opportunity to find out what those are and fix them.
