### ISSUE TITLE
I need some help to my texture pack work with ckan!

### ISSUE THREAD

**Issue by Vannadin** [KSP-CKAN/NetKAN#7699]
Hello, I'm the author of this [texturepack](https://forum.kerbalspaceprogram.com/index.php?/topic/191018-vannadins-16k-rss-texture-pack-bugpatch-update210-28-jan-2020/). I want to make it work with ckan so I read manual but it was a bit hard to understand. I'll upload my texture pack to github after check so ckan can download. can you help me?

**Comment by HebaruSan** [comment]
Is the upload on SpaceDock complete? We have tried to add it in #7700, but we got this error:

```
Running NetKAN for NetKAN/RSSTextures16K.netkan
106539 [1] FATAL CKAN.NetKAN.Program (null) - https://spacedock.info/mod/1357/VaNnadin's 16K RSS texture pack/download/1.2.1 is not a valid ZIP file: Wrong Central Directory signature
Build step 'Execute shell' marked build as failure
```

**Comment by Vannadin** [comment]
I was trying to upload it into github but failed cuz it's too big. I think I have to fix this problem first :(

**Comment by HebaruSan** [comment]
@Vannadin, are you still planning to create a working upload for this mod? If not, then we can close this.

**Comment by Vannadin** [comment]
I hope so. can I use googledrive for ckan? if isn't, I'm gonna need some more time so you can close it

**Comment by HebaruSan** [comment]
No, unfortunately Google Drive recently redirected their download links to an unskippable HTML virus warning page that prevents CKAN from using them, see #7629 for an example.

How big is this file?

**Comment by Vannadin** [comment]
It's about 1.2gb per version. it will grow when new texture is added

**Comment by HebaruSan** [comment]
OK, that's in line with a few other mods that are already indexed. For example, JNSQ is 1.9 GB, and TheWorldBeyond is 1.6 GB. Both of those are hosted on GitHub, so maybe that's a good thing to try?

- https://raw.githubusercontent.com/Galileo88/JNSQ/master/CKAN/JNSQ.netkan
  - https://github.com/Galileo88/JNSQ
- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/TheWorldBeyond.netkan
  - https://github.com/TheProtagonists/TheWorldBeyond

**Comment by Vannadin** [comment]
yes please! how can I do that?

**Comment by HebaruSan** [comment]
First make a repository:

- https://help.github.com/en/github/getting-started-with-github/create-a-repo

Then upload your 1.2 GB ZIP file attached to a release:

- https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

**Comment by Vannadin** [comment]
thanks! this is the link:
https://github.com/Vannadin/VaNnadin-s-16K-RSS-texture-pack
