### ISSUE TITLE
Question about updating RealismOverhaul

### ISSUE THREAD

**Issue by siimav** [KSP-CKAN/NetKAN#7707]
The current release of RO has an dependency on SmokeScreen-RO in it's netkan file. For KSP 1.8+ releases we would have to once again start using the regular SmokeScreen because the -RO variant was specifically made as a backport for KSP 1.7.3.
What would be the correct way to handle such transition? Is it also possible to create a single release for RO that supports KSP versions 1.7.3 up to 1.9.x at the same time such that 1.7,3 gets the -RO variant of SS and 1.8+ gets the regular SS?

**Comment by HebaruSan** [comment]
> Is it also possible to create a single release for RO that supports KSP versions 1.7.3 up to 1.9.x at the same time such that 1.7,3 gets the -RO variant of SS and 1.8+ gets the regular SS?

Yes, changing the dependency to SmokeScreen should accomplish that, because SmokeScreen-RO provides SmokeScreen:

https://github.com/KSP-CKAN/NetKAN/blob/92e10e158e3be055642dc8762a1bcd9b5bec8b30/NetKAN/SmokeScreen-RO.netkan#L29-L31

The `provides` property effectively defines aliases that the module can satisfy in dependencies.

**Comment by siimav** [comment]
Yes but if we switch it back to SmokeScreen, then anyone installing RO on 1.7.3 would get a choice between SS and SS-RO, right? Ideally the -RO variant should be the only thing they can install because it fixes a crucial bug.

**Comment by HebaruSan** [comment]
Does SmokeScreen-RO actually have any dependencies on RealismOverhaul? Maybe we should just merge its releases into the main SmokeScreen module.

**Comment by HebaruSan** [comment]
Oh yuck, they share/overlap versions. Merging isn't going to be an option.

**Comment by HebaruSan** [comment]
Looks like the conclusion was to depend on SmokeScreen.

https://github.com/KSP-CKAN/CKAN-meta/blob/master/RealismOverhaul/RealismOverhaul-v12.8.1.ckan
