### ISSUE TITLE
[Mod] Chrayol Design Org.

### ISSUE THREAD

**Issue by DylanSemrau** [KSP-CKAN/NetKAN#7710]
Mod info
--------
* Mod name: Chrayol Design Org.
* Author(s): DylanSemrau
* License: Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0)
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/189111-18-v10-chrayol-design-org-isro-mod/
* Download: https://github.com/DylanSemrau/Chrayol-Design-Org./releases

> {
>   "spec_version"        : "v1.4",
>   "identifier"          : "ChayrolDesignOrg",
>   "$kref"               : "#/ckan/github/DylanSemrau/Chayrol-Design-Org.",
>   "abstract"            : "This mod aims to add a number of different ISRO rockets and spacecraft to the game. Eventually the plan is to add SLV, GSLV MK1-3, RLV, along with a couple of probes (Ex. Chandrayaan, Mangalyaan etc).",
>   "author"              : "DylanSemrau",
>   "license"             : "CC-BY-NC-SA-4.0",
>   "$vref"               : "#/ckan/ksp-avc",
>   "resources": {
>     "homepage": "https://forum.kerbalspaceprogram.com/index.php?/topic/189111-18-v10-chrayol-design-org-isro-mod/",
>     "repository": "https://github.com/DylanSemrau/Chrayol-Design-Org."
>   },
>   "depends": [
>       { "name" : "ModuleManager" }
>   ],
>   "suggests": [
>       { "name" : "JNSQ" },
>       { "name" : "RealPlume-StockConfigs" },
>       { "name" : "BluedogDB" },
>       { "name" : "ModularLaunchPads" }
>   ],
>   "install" : [
>       { 
>       "file" : "GameData/Chrayol_Design_Org",
>        "install_to" : "GameData"
>        }
>   ]
> }

**Comment by HebaruSan** [comment]
Do you need the period character in the repository name? I think that might be messing up our attempts to index this.
