### ISSUE TITLE
BladeTweaks added a 1.2.0 tag without a ZIP, so ckan hasn't indexed it

### ISSUE THREAD

**Issue by blade1981m** [KSP-CKAN/NetKAN#7721]
I updated BladeTweaks on the 17th and made a new release on Github. I have been refreshing ckan the last couple of days and have not seen it updated yet.

**Comment by HebaruSan** [comment]
Try uploading a ZIP file for the release:

![image](https://user-images.githubusercontent.com/1559108/74906337-99502900-53a8-11ea-882b-5c92873a71e0.png)

**Comment by blade1981m** [comment]
doh. Thanks

**Comment by DasSkelett** [comment]
The version has been indexed! :tada:

https://github.com/KSP-CKAN/CKAN-meta/blob/master/BladeTweaks/BladeTweaks-1.2.0.ckan
