### ISSUE TITLE
[Bug] F.A.R. not downloading?

### ISSUE THREAD

**Issue by ksp-noob** [KSP-CKAN/NetKAN#7730]
Background
----------
* Operating System: windows 10
* CKAN Version: 1.27.0
* KSP Version: 1.7.3

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
~~No, i don't think.~~

Either FAR was installed manually, or it was installed via CKAN and then the CKAN registry was purged according to the old Clean and reinstall process.

Problem
-------
When i try to download ferram aerospace continued it says: "Oh no!

It looks like you're trying to install a mod which is already installed,
or which conflicts with another mod which is already installed.

As a safety feature, the CKAN will *never* overwrite or alter a file
that it did not install itself.

If you wish to install FerramAerospaceResearchContinued 3:0.15.11.2 via the CKAN,
then please manually uninstall the mod which owns:

Ships/@thumbs/SPH/E42.png

and try again.
Your GameData has been returned to its original state.
Error during installation!"
I don't have a single mod in the gamedata, just module manager.

**Expected behavior**
It downloading?

**CKAN error code (if applicable):**

```
Oh no!

It looks like you're trying to install a mod which is already installed,
or which conflicts with another mod which is already installed.

As a safety feature, the CKAN will *never* overwrite or alter a file
that it did not install itself.

If you wish to install FerramAerospaceResearchContinued 3:0.15.11.2 via the CKAN,
then please manually uninstall the mod which owns:

Ships/@thumbs/SPH/E42.png

and try again.
Your GameData has been returned to its original state.
Error during installation!
```

**Comment by HebaruSan** [comment]
Try opening your game folder and deleting these files:

![FAR ships](https://cdn.discordapp.com/attachments/601456752906469388/662697513177841666/unknown.png)

**Comment by HebaruSan** [comment]
BTW, did you get here by following the clean and reinstall process?

https://github.com/KSP-CKAN/CKAN/wiki/Clean-and-reinstall-process

If so:  It was updated recently because it was missing steps to handle the Ships folder; take another look to avoid this in the future.

**Comment by ksp-noob** [comment]
ill see if it works, thanks!
