### ISSUE TITLE
[Mod] ShipManifest (taking over maintenance)

### ISSUE THREAD

**Issue by mwerle** [KSP-CKAN/NetKAN#7742]
**Discussion at first; please no changes to Netkan yet!**

Considering taking over Ship Manifest (temporarily?) as [discussed in the forum thread here](https://forum.kerbalspaceprogram.com/index.php?/topic/56643-141-ship-manifest-crew-science-resources-v-5210-17-mar-18/&do=findComment&comment=3747418). 

Wondering what the best approach is given that I **have not** been given the official go-ahead by the author @PapaJoesSoup as I haven't been able to contact him.  But since it's been quite a long time, and the last official release was for KSP1.4, I think it's valid to consider a "hostile" takeover.. ;)

Options are:

1) Create a new mod called "Ship Manifest Continued" (or similar) and mark it as replacing the original mod.

2) Take over the CKAN metadata of the existing mod and point it at my fork of the official repo instead of the current download links.

My preference would be #2 as I would hand the mod back to @PapaJoesSoup as soon as / if he returns and it would be the least disruption for users, at least via CKAN.  Not entirely sure how to handle Spacedock and Curse without his help though.

Would appreciate any recommended "Best Practices" for this situation.

Mod info
--------
* Mod name:  Ship Manifest
* Author(s): Papa_Joe, Micha
* License: CC BY-NC-SA 4.0
* Homepage: TBD (new forum thread?)
* Download: https://github.com/mwerle/ShipManifest/releases

**Comment by linuxgurugamer** [comment]
You could do #2, and then if/when he comes back, it could be repointed back at his repo

**Comment by HebaruSan** [comment]
Yeah number 2 :hankey: sounds fine to me.
