### ISSUE TITLE
[Mod] Real Exoplanets

### ISSUE THREAD

**Issue by Monniasza** [KSP-CKAN/NetKAN#7750]
Mod info
--------
* Mod name: Real Exoplanets
* Author(s): [AndyDrawsPrettyPictures](https://spacedock.info/profile/AndyDrawsPrettyPictures)
* License: Creative Commons Attribution-NonCommercial-ShareAlike
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/187033-181-real-exoplanets-v094-09022020/
* Download: https://spacedock.info/mod/2286/Real%20Exoplanets/download/0.9.4

**Comment by HebaruSan** [comment]
Has the author given permission?

**Comment by Monniasza** [comment]
Permission is not needed according to license. Full text [here](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode)

**Comment by HebaruSan** [comment]
We ask anyway. It significantly improves mod authors' moods.

**Comment by HebaruSan** [comment]
Fine, I'll ask.
https://forum.kerbalspaceprogram.com/index.php?/topic/187033-181-real-exoplanets-v096-04032020/&do=findComment&comment=3753917

**Comment by HebaruSan** [comment]
![image](https://user-images.githubusercontent.com/1559108/76181107-ef4e0a80-61b7-11ea-8483-70bf53d6732e.png)

**Comment by HebaruSan** [comment]
Author gave permission, added in #7765. Should be visible in CKAN in a few minutes (there will be a bit of a delay for processing as it's a large download).
