### ISSUE TITLE
CKAN-META not indexing latest RealFuels

### ISSUE THREAD

**Issue by raidernick** [KSP-CKAN/NetKAN#7757]
The 12.8.4 release of real fuels was removed and replaced with 12.8.4.1 days ago. The bot has not picked up this change can this be remedied.

https://github.com/NathanKell/ModularFuelSystem/releases/tag/rf-v12.8.4.1

**Comment by HebaruSan** [comment]
The current indexing error is:

http://status.ksp-ckan.space/

> Error parsing version file GameData/RealFuels/RealFuels.version: After parsing a value an unexpected character was encountered: ". Path 'VERSION.PATCH', line 9, position 2.

I'll send you a PR with a fix.

**Comment by HebaruSan** [comment]
Oh never mind, I already did that, see NathanKell/ModularFuelSystem#238. Just need a new release that contains that fix.

**Comment by raidernick** [comment]
the download was updated which is why I'm confused as to why it hasn't reindexed it. Doesn't it usually pick up if the hash has changed?

**Comment by HebaruSan** [comment]
Was it? I just re-downloaded it to check and the syntax error was still there.

**Comment by raidernick** [comment]
You are absolutely right. I only checked that the dll was updated not that the version file was fixed.

**Comment by HebaruSan** [comment]
Latest upload worked!

https://github.com/KSP-CKAN/CKAN-meta/commit/755212dd45701ea378e3a520acd76f9665a6d59b

**Comment by raidernick** [comment]
thanks seems to be good now
