### ISSUE TITLE
[Bug] Unable to install Impossible Innovations

### ISSUE THREAD

**Issue by Monniasza** [KSP-CKAN/NetKAN#7766]
Background
----------
* Operating System: Windows 10
* CKAN Version: 
* KSP Version: KSP 1.8.1.2694

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Installed mods from CurseForge BEFORE problem occured, and other mods installed by CKAN successfully.

Problem
-------
**Describe the bug**

**Steps to reproduce**
* Try to install Impossible Innovations

**Expected behavior**
Impossible Innovations installs completely

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
Oh no!

It looks like you're trying to install a mod which is already installed,
or which conflicts with another mod which is already installed.

As a safety feature, the CKAN will *never* overwrite or alter a file
that it did not install itself.

If you wish to install ImpossibleInnovations 0.8.8.6 via the CKAN,
then please manually uninstall the mod which owns:

Ships/SPH/Impossible Innovations_A.craft

and try again.
Your GameData has been returned to its original state.
Error during installation!
An unknown error occurred, please try again!

```

**Comment by HebaruSan** [comment]
The [Clean and reinstall process](https://github.com/KSP-CKAN/CKAN/wiki/Clean-and-reinstall-process) was updated recently to account for Ships. If you installed this mod previously and then used the old Clean and reinstall process, this file would have been left behind. Just delete the file.

**Comment by Monniasza** [comment]
The CKAN installation contains self-conflicting files.

**Comment by HebaruSan** [comment]
How do you figure that?

**Comment by HebaruSan** [comment]
I just installed it myself and had no errors, there are no self-conflicting files.

**Comment by linuxgurugamer** [comment]
Delete the file and try again:
Ships/SPH/Impossible Innovations_A.craft

**Comment by Monniasza** [comment]
> Delete the file and try again:
> Ships/SPH/Impossible Innovations_A.craft

I did this, but issue persists.

**Comment by HebaruSan** [comment]
What is the full text of the new error?
