### ISSUE TITLE
Tarsier Space Techonology v7.10 not compatible with KSP 1.8.x and less

### ISSUE THREAD

**Issue by JustaSimpleUser** [KSP-CKAN/NetKAN#7772]
Mod info
--------
* Mod name: Tarsier Space Technology
* Author(s): JPLRepo
* License: 
* Homepage: https://github.com/JPLRepo/TarsierSpaceTechnology
* Download: https://github.com/JPLRepo/TarsierSpaceTechnology

Reference [this forum post](https://forum.kerbalspaceprogram.com/index.php?/topic/154853-19x-tarsier-space-technology-with-galaxies-v710-29th-feb-2020/&do=findComment&comment=3757151).

TST's author doesn't support CKAN but someone has created the NetKAN file.  The author reports that TST v7.10 (latest) supports only KSP 1.9.x but CKAN reports compatibility with 1.7.x to 1.9.x. 

TST v7.10 should be limited to KSP v1.9.x.

If I knew where to find the TST NetKAN and how to do a proper PR, this simple fix might be in my ability to submit.

**Comment by HebaruSan** [comment]
That is controlled directly by author-entered data here (line breaks added for readability):

http://ksp-avc.cybutek.net/version.php?id=148

```json
{
"NAME":"TarsierSpaceTechnology",
"URL":"http://ksp-avc.cybutek.net/version.php?id=148",
"DOWNLOAD":"http://spacedock.info/mod/143/Tarsier%20Space%20Technology%20with%20Galaxies%20Continued...",
"VERSION":{"MAJOR":7,"MINOR":10,"PATCH":0,"BUILD":0},
"KSP_VERSION":{"MAJOR":1,"MINOR":9,"PATCH":0},
"KSP_VERSION_MIN":{"MAJOR":1,"MINOR":7,"PATCH":0},
"KSP_VERSION_MAX":{"MAJOR":1,"MINOR":9,"PATCH":99}
}
```

Specifically:

```json
"KSP_VERSION_MIN":{"MAJOR":1,"MINOR":7,"PATCH":0},
```

If the author doesn't want 1.7 supported, he should change this back (looks like he edited it about 16 days ago around the time of the release).

https://github.com/KSP-CKAN/CKAN-meta/commits/7f5d6b5181a4b1945ae1d49aafc5fb61e4447fce/TarsierSpaceTechnologyWithGalaxies/TarsierSpaceTechnologyWithGalaxies-1-7.10.ckan

**Comment by HebaruSan** [comment]
Replied in the thread.

https://forum.kerbalspaceprogram.com/index.php?/topic/154853-19x-tarsier-space-technology-with-galaxies-v710-29th-feb-2020/&do=findComment&comment=3757182

**Comment by HebaruSan** [comment]
Fixed after the author updated the remote version file.

https://github.com/KSP-CKAN/CKAN-meta/commit/b4fafed0895279584f0d7b84ae05341db3478338
