### ISSUE TITLE
[Bug] Can't install KSP Interstellar Extended

### ISSUE THREAD

**Issue by Monniasza** [KSP-CKAN/NetKAN#7785]
Background
----------
* Operating System: Windows 10
* CKAN Version: 
* KSP Version: 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Problem
-------
**Describe the bug**

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
No info = can't investigate.
