### ISSUE TITLE
Distribute Engine Group Controller and Ferram Aerospace Research separately

### ISSUE THREAD

**Issue by Monniasza** [KSP-CKAN/NetKAN#7786]
With CKAN, both mods must be installed together, even if mods are allowed to be installed with missing dependencies. For me, I used EGC without FAR and it worked. Please distribute two different mods under separate positions and provide recommendations for both.

**Comment by HebaruSan** [comment]
I took a look in the FAR(C) archive, and I don't see anything labeled "Engine Group Controller" or "EGC ". What is this request?

**Comment by HebaruSan** [comment]
Closing because this is too unclear to be worked on. Will re-open if we get clarification.

**Comment by Monniasza** [comment]
> Closing because this is too unclear to be worked on. Will re-open if we get clarification.

Re-opened at https://github.com/KSP-CKAN/NetKAN/issues/7827
