### ISSUE TITLE
CKAN installation error

### ISSUE THREAD

**Issue by JajajTec** [KSP-CKAN/NetKAN#7788]
Datei:               GameData/CryoTanks/Plugins/SimpleBoiloff.dll
Installierende Mod : CryoTanks 0.4.11
Besitzende Mod :     CryoTanks-Core
CKAN-Version :       v1.27.0
what should i do?

When i try to fix it that error comes:

```
************** Ausnahmetext **************
System.ArgumentException: Already contains module:GPO
   bei CKAN.RelationshipResolver.Add(CkanModule module, SelectionReason reason)
   bei CKAN.RelationshipResolver.AddModulesToInstall(IEnumerable`1 modules)
   bei CKAN.ModuleInstaller.InstallList(ICollection`1 modules, RelationshipResolverOptions options, RegistryManager registry_manager, IDownloader downloader, Boolean ConfirmPrompt)
   bei CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   bei System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   bei System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by HebaruSan** [comment]
CryoTanks 0.4.11 isn't supposed to be installed alongside CryoTanks-Core; that split was made with the 1.1.2 version. 

Which version of CryoTanks-Core do you have installed?

**Comment by JajajTec** [comment]
yeah had the 1.1.2 version

**Comment by JajajTec** [comment]
and i reinstalled everything and rearranged everything (took 4 houres) but jet everything works. i found out that many things was messed up and the only problems i have are 3 excepions on the startup on warp plugin air intake.cfg and a massive lag every time i open the map. Sorry i forgot to close this. and when you have a clue what causes the lag i will be very happy to know it.

**Comment by HebaruSan** [comment]
So this is working now?
