### ISSUE TITLE
Can't install Realism Overhaul

### ISSUE THREAD

**Issue by sdegrace** [KSP-CKAN/NetKAN#7790]
Background
----------
* Operating System: Ubuntu 19.04
* CKAN Version: 1.27.0
* KSP Version: 1.8.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Installed KS3P

Problem
-------
Can't install Realism Overhaul due to Real Fuels Max KSP version

**Steps to reproduce**
- Install Realism Overhaul
* See error
RealismOverhaul v12.8.0 depends on RealFuels, which is not compatible with the currently installed version of KSP

**Expected behavior**
Installs all necessary mods

**Comment by HebaruSan** [comment]
Doesn't look like that's true:

https://github.com/KSP-CKAN/CKAN-meta/blob/6c2d735e7871fcebf4d5a888a1cda4db3bf6d8d3/RealFuels/RealFuels-rf-v12.8.4.1.ckan#L14

```json
    "ksp_version_min": "1.8.0",
```

Can you show us the actual problem?

**Comment by sdegrace** [comment]
I opened this way too early, I'm sorry. There was a compatibility problem with another mod that I missed.
