### ISSUE TITLE
Rescind / Recall a Release

### ISSUE THREAD

**Issue by DRVeyl** [KSP-CKAN/NetKAN#7796]
Is there a recommended process for rescinding or recalling a release that has been indexed by CKAN?

For example, one release of a mod has a significant bug.  The fixed release is completed and has been indexed by CKAN.  Ideally, the broken version should get rescinded and no longer be accessible.  On its GitHub host, I would just delete the bad release, but I believe that won't impact the references here, and would just result in an error if a user tried to install it.

**Comment by DasSkelett** [comment]
To answer the question if it's even necessary or recommended to freeze/delete/recall a buggy release:
If the fixed release follows shortly after or is already released (as in your described case), it's probably not worth the effort.
Users that have already updated to the buggy release will be prompted to upgrade again. Users that didn't update yet, will skip the buggy release when they update the next time. For new installations CKAN will also default to the newer release.

(As author, I probably wouldn't even delete the old release on GitHub. The newer one will be shown on top, people should default to the fixed one.)
But _if_ you are going to delete it on GitHub and, for whatever reason, somebody tries to install this older version via CKAN despite the newer one existing, then
a) if the mod is archived on archive.org, CKAN will fallback to it. The download +installation are likely to succeed.
b) if the mod isn't archived, the download+installation will fail.


If the case is different and a fixed release isn't going to come out soon, it may make sense to take it down on all platforms again, and to freeze the release on CKAN so users don't get errors trying to install or update the mod.

For that, you can
a) do a PR in [CKAN-meta](https://github.com/KSP-CKAN/CKAN-meta) which renames the file from `<name>-<version>.ckan` to `<name>-<version>.frozen`. Before the PR gets merged the release has to be deleted upstream (GitHub/Spacedock), else our bot automatically reindexes it.
b) simply contact us in any way you like (Open a issue like this one here/Discord/Forum thread or PMs/...) so we can do it for you. The same as above applies, the release has to be deleted upstream first, before we can freeze it on CKAN.

**Comment by DRVeyl** [comment]
Thankyou.  Sounds like no further action is required.  For this particular case, the new release is available and that is considered sufficient.  "Downgrade at your own risk" is maybe imperfect, but I'm just looking to be consistent with your normal practice.

**Comment by DasSkelett** [comment]
Great! I'm closing the issue now since the question seems to be answered, feel free to reopen if you have additional questions.
