### ISSUE TITLE
mod probloem

### ISSUE THREAD

**Issue by Pat250rick** [KSP-CKAN/NetKAN#7803]
A mod called B9 part switch is showing a fatal error sign when ckan is not showing any issues and i am unable to use certain mods because of this

**Comment by HebaruSan** [comment]
- Where is this error sign?
- When does it appear?
- What does it look like?
- Why/how are you not able to use certain mods?
- Which mods are you not able to use?

Please fill in the questions in the template that you deleted:
https://github.com/KSP-CKAN/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
