### ISSUE TITLE
Process Question: Updating a Mod With a New Dependency

### ISSUE THREAD

**Issue by DRVeyl** [KSP-CKAN/NetKAN#7818]
This is addressed in the guide here (https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN#internal-ckan-files), but I'm a little unclear on the follow-up.

The RO team is preparing several of its mods previously released for KSP 1.7 to support KSP 1.8+. The 1.8 releases will gain a dependency on the new ROLib library, currently PR'd.  The existing 1.7 mods "must" not gain that dependency: there is no ROLib for 1.7.

I believe the correct process is to add a .ckan file to each of the upcoming releases like so:
```
{
    "depends": [
	{ "name": "ROLib" }
    ]
}
```
Once the new release of a given mod is indexed by CKAN, we should then update that mod's .netkan to add the dependency and remove this .ckan file for any future release.  Is this correct?

Is the `"spec_version": "v1.16",` line required for this patching?

**Comment by HebaruSan** [comment]
Some caveats:

- An internal .ckan file can only **add** properties; it cannot override or remove properties that are set in your main netkan entry, which means you would need to delete the `depends` property from the main netkan to be able to populate it from the internal ckan file
- If you want the internal ckan to override `depends`, it would have to contain **all** of the dependencies, not just the new one

> Is the `"spec_version": "v1.16",` line required for this patching?

I think `"spec_version"` is required (`NetKAN.Model.Metadata`'s constructor throws an exception if it's missing), but it doesn't have to be `"v1.16"`, could just be `"1"` if you like, unless you use some property or feature that requires a higher spec version (e.g., `"find"` in `"install"` requires `"v1.4"` or higher; [the spec](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md) annotates these where appropriate).

The easiest way to handle this in this case might be to just make all the updates and uploads and then let us clean it up after the fact if anything gets messed up. It's easy to revert the metadata for the 1.7 mods if they are affected accidentally, and the 1.8+ ones will be updated as soon as the netkans are changed.

**Comment by DRVeyl** [comment]
What is the recommended order?

Release the new mods for 1.8.  Wait for it to get indexed [with the incorrect .netkan dependencies].  Then PR the .netkan update?  On finding a new .netkan file, is the most recent .ckan data automatically updated, or is that manually initiated?

**Comment by HebaruSan** [comment]
Merging a NetKAN PR causes the module to be checked/indexed at that point. So if you release for 1.8 and then PR the netkan updates *without* waiting, merging the PR would index the new release immediately according to the new metadata.

However, the bot checks for updates every few hours automatically. If the bot is in the middle of a pass while the release/PR are happening, there's a chance that the new release would be indexed according to the old metadata. In that case we would just have to revert those changes.

**Comment by DRVeyl** [comment]
Cool, think I understand.

In my case, I'm not concerned about the new release temporarily having stale metadata and people updating incorrectly before the .netkan PR merges.  I'm more concerned about the legacy release getting inappropriate new metadata.

In that vein, the answer is to publish the new release first and then submit the PR, because even if the bot discovers the new release first and assigns stale metadata, the .netkan merge will update it.

**Comment by DRVeyl** [comment]
Thanks for the answers and the help with updating the .netkan for the mods.  Much appreciated!  Believe this can be closed.  Consider clarifying in the modders guide the result of updating the netkan file.

**Comment by HebaruSan** [comment]
Yeah, the adding-a-mod wiki needs a lot of updates. It could and should be a lot simpler and easier now. I've started making some notes about it...

Let's leave this issue open until the wiki is improved; it can serve as a ticket requesting that.

**Comment by HebaruSan** [comment]
OK @DRVeyl, I have made a temporary copy of the wiki so I can have folks review it before we switch over, because it's a pretty big change to the old page. Please review if you have time and send any feedback:

- https://github.com/HebaruSan/CKAN/wiki/Adding-a-mod-to-the-CKAN
