### ISSUE TITLE
[Update] Actions Everywhere

### ISSUE THREAD

**Issue by Monniasza** [KSP-CKAN/NetKAN#7822]
I think that Actions Everywhere should be replaced by ModActions, which also has more features.

**Comment by HebaruSan** [comment]
Actions Everywhere isn't listed, as far as I can tell. What are you asking us to do?

**Comment by Monniasza** [comment]
> ~Actions Everywhere isn't listed, as far as I can tell. What are you asking us to do?~
> 
> Ahh, it's listed as [`ActsEW`](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/ActsEW.netkan) (this is why I'm anti-acronym).
> 
> ModActions is already indexed though:
> 
> * https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/ModActions.netkan
> 
> Not sure what this is requesting. Are you saying we should set the `replaced_by` property?

Yes

**Comment by HebaruSan** [comment]
Interesting; the author appears to agree with this idea:

![image](https://user-images.githubusercontent.com/1559108/78694515-4d235e80-78ec-11ea-8fe4-2c7e9f9a6d27.png)

I guess it makes sense...

**Comment by HebaruSan** [comment]
Thanks for the suggestion!
