### ISSUE TITLE
Distribute Realism Overhaul and Engine Group Controller separately

### ISSUE THREAD

**Issue by Monniasza** [KSP-CKAN/NetKAN#7827]
In https://github.com/KSP-CKAN/NetKAN/issues/7786 , i accidentally misidentified bundled mod. 

With CKAN, both mods must be installed together, even if mods are allowed to be installed with missing dependencies. For me, I used EGC without RO and it worked. Please distribute two different mods under separate positions and provide recommendations for both.

**Comment by HebaruSan** [comment]
The CKAN team doesn't control RealismOverhaul's metadata. You'll need to ask the KSP-RO team to change this:

- https://github.com/KSP-RO/RealismOverhaul/blob/master/RealismOverhaul.netkan
