### ISSUE TITLE
BetterTimeWarpContinued mod not having dependencies.

### ISSUE THREAD

**Issue by CRCasey** [KSP-CKAN/NetKAN#7849]
Background
----------
* Operating System: Win10
* CKAN Version: 1.27.0
* KSP Version: 1.9.1.2788

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Only after Problem.  

Problem
-------
BetterTimeWarpContinued is missing required dependencies as listed below...

ToolbarControl - DL at https://github.com/linuxgurugamer/ToolbarControl/releases

ClickThroughBlocker - DL at https://github.com/linuxgurugamer/ClickThroughBlocker/releases

Both from the same author as the mod.  GPL3 Lic.  Notes indicate that it has KCAN support.

**Steps to reproduce**
Install BetterTimeWarpContinued

**Expected behavior**
Mod and dependencies installed together.

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Thanks for letting us know. Looks like this was an accidental change by LGG in #7734. Will fix shortly.
