### ISSUE TITLE
[Mod] SuperBattery

### ISSUE THREAD

**Issue by Monniasza** [KSP-CKAN/NetKAN#7853]
Mod info
--------
* Mod name: SuperBattery
* Author(s): [baddzse233](https://spacedock.info/profile/baddzse233)
* License: CC-BY-NC-SA 4.0
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/193141-%E3%80%9018x-19x%E3%80%91-superbatterymod-%E3%80%90release-now%E3%80%91/&tab=comments#comment-3771113
* Download: https://spacedock.info/mod/2368/SuperBattery

**Comment by HebaruSan** [comment]
@Monniasza has this author granted permission?

**Comment by Monniasza** [comment]
> @Monniasza has this author granted permission?
Please contact the author at amdyes_qwq@outlook.com OR langbaobao1015@163.com

**Comment by Monniasza** [comment]
> @Monniasza has this author granted permission?

Asked: https://forum.kerbalspaceprogram.com/index.php?/topic/193141-%E3%80%9018x-19x%E3%80%91-superbatterymod-%E3%80%90release-now%E3%80%91/&do=findComment&comment=3785669

**Comment by baddzse233** [comment]
I hope you can change the "download" link to the mod's spacedock home page link, otherwise other people will download the old version from you after I update it.(Translated by translate software)

**Comment by Monniasza** [comment]
> I hope you can change the "download" link to the mod's spacedock home page link, otherwise other people will download the old version from you after I update it.(Translated by translate software)

Done. Please look at the first comment.

**Comment by Monniasza** [comment]
Author agreed: https://forum.kerbalspaceprogram.com/index.php?/topic/193141-%E3%80%9018x-19x%E3%80%91-superbatterymod-%E3%80%90release-now%E3%80%91/&do=findComment&comment=3785740

**Comment by HebaruSan** [comment]
There are some syntax errors in the version file, reported here:

- https://github.com/baddzse233/SuperBatteryMod/issues/1

**Comment by baddzse233** [comment]
> There are some syntax errors in the version file, reported here:
> 
> * [baddzse233/SuperBatteryMod#1](https://github.com/baddzse233/SuperBatteryMod/issues/1)

OK,i will fix it.Thanks for your report

**Comment by Monniasza** [comment]
Please remove Blocked-on-Mod-Author and add Blocked-on-Other label.

**Comment by HebaruSan** [comment]
@Monniasza, don't worry about labels. They don't actually block anything, they're just so we can track what's happening with the issues and pull requests.
