### ISSUE TITLE
removing the Blizzy Toolbar (installed automatically) removes all mods which have it as a suggestion or recommendation

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7857]
Got a complaint today.  Apparently someone wanted to remove the Toolbar, but leave the ToolbarController, but  CKAN insisted on deleting all mods which had it listed as either a suggestion or recommendation

I've checked all the netkans, and I don't see it being listed as a dependency in any mod which has the ToolbarController listed as a dependency

Any ideas?

**Comment by HebaruSan** [comment]
Sounds like something else happened, and this user made incorrect assumptions and guesses. No way to tell what the reality is with no screenshots, steps to reproduce, or even specific affected mods.

**Comment by HebaruSan** [comment]
Where was the original complaint made?

**Comment by linuxgurugamer** [comment]
It was made on a stream, I think it was the ReadPanda.
I’ll do some testing this weekend

**Comment by HebaruSan** [comment]
Looks like we're not going to get enough info to investigate.
@linuxgurugamer, if you find out what happened, let us know and we can re-open this.
