### ISSUE TITLE
KDEX is show as incompatible

### ISSUE THREAD

**Issue by mwerle** [KSP-CKAN/NetKAN#786]
KDEX v1.04 seems to work just fine in KSP 0.90.

I posted in the [mod forum thread](http://forum.kerbalspaceprogram.com/threads/54656-0-25-KDEX-Kerbal-Dust-Experiment-v1-04?p=1685528&viewfull=1#post1685528) about this a month ago, but it appears the author is currently unavailable.  Is it possible to override the KerbalStuff metadata in order to mark this mod as compatible with 0.90?

**Comment by AlexanderDzhoganov** [comment]
[Fixed](https://github.com/KSP-CKAN/NetKAN/commit/28784956f92f2d524a18ae7ef91b295d73426e2f). Thanks for the info.
