### ISSUE TITLE
[Mod] Bluedog Design Bureau

### ISSUE THREAD

**Issue by Monniasza** [KSP-CKAN/NetKAN#7867]
Mod info
--------
* Mod name: Bluedog Design Bureau
* Author(s): [CobaltWolf](https://github.com/CobaltWolf)
* License: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
* Homepage: https://github.com/CobaltWolf/Bluedog-Design-Bureau
* Download: https://github.com/CobaltWolf/Bluedog-Design-Bureau/archive/master.zip
The mod bundles ModuleManager.
The repository contains source code and "Gamedata" and "Craft Files" directories should be downloaded.

Extra patch
------------
* Download: https://github.com/CobaltWolf/Bluedog-Design-Bureau/tree/master/BD_Extras%20(No%20Warranty)

**Comment by HebaruSan** [comment]
Are you serious??

https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/BluedogDB.netkan
