### ISSUE TITLE
Illegal mod

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7869]
The following mod violates the original mod license

https://github.com/KSP-CKAN/CKAN-meta/tree/master/AIESAerospace-Unofficial

**Comment by HebaruSan** [comment]
How?

**Comment by linuxgurugamer** [comment]
The license is:

All pieces AIES are creating Carmics
use is free to all users to Kerbal Space Program, 
however it is not allowed for commercial use, 
and distribution through other unknown links


I may be jumping too fast, but I saw that it had gotten an update today listed as "patched", which seems to include the whole thing.

**Comment by HebaruSan** [comment]
It's exactly the same as the existing AIES module except it depends on your patches. No sign of anything illegal.

**Comment by HebaruSan** [comment]
See KSP-CKAN/CKAN-meta#1904 for more details.

**Comment by linuxgurugamer** [comment]
ok, thank you for the fast response
