### ISSUE TITLE
[Mod] SSTO Project

### ISSUE THREAD

**Issue by Monniasza** [KSP-CKAN/NetKAN#7886]
Mod info
--------
* Mod name: SSTO Project
* Author(s): Monniasza
* License: MIT
* Homepage: https://spacedock.info/mod/2417/SSTO%20Project
* Download: https://spacedock.info/mod/2417/SSTO%20Project/download/1.0
--------
The mod did not get any attention at all, originally at https://github.com/KSP-CKAN/NetKAN/pull/7873

**Comment by HebaruSan** [comment]
Duplicate of #7873
