### ISSUE TITLE
[Mod] QuickSearch

### ISSUE THREAD

**Issue by Monniasza** [KSP-CKAN/NetKAN#7895]
Mod info
--------
* Mod name: QuickSearch
* Author(s): malah, linuxgurugamer
* License: GPLv3
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/174445-141-malahs-quick-mods/
* Download: https://spacedock.info/mod/101/QuickSearch/download/3.3.0.10

**Comment by DasSkelett** [comment]
Already indexed: https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/QuickSearch.netkan

@Monniasza, if you open the client, you can search for mods using this and the other text boxes:
![Screenshot_20200513_141041](https://user-images.githubusercontent.com/28812678/81810923-1ad8d280-9524-11ea-8d6c-4d5b2658161b.png)

Just enter the name in the first one, and the mod will show up.
You might have to switch your filter to "All" before, to see incompatible mods.

**Comment by HebaruSan** [comment]
And if you don't have the client, you can try searching on [the status page](http://status.ksp-ckan.space/):

![image](https://user-images.githubusercontent.com/1559108/81872629-b88dcb00-953f-11ea-8735-cdd7b0008136.png)
