### ISSUE TITLE
[Mod]

### ISSUE THREAD

**Issue by DarthPointer** [KSP-CKAN/NetKAN#7925]
Mod info
--------
* Mod name: PayToPlay
* Author(s): DarthPointer
* License: MIT
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/193467-18x-19x-paytoplay-maintenance-costs-money/&tab=comments#comment-3777542
* Download: https://github.com/DarthPointer/PayToPlay/releases

**Comment by HebaruSan** [comment]
You should see it show up in a few minutes.

**Comment by DarthPointer** [comment]
Thanks!
