### ISSUE TITLE
[Bug] Bot or github is not working

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7937]
I submitted a PR a few hours about, it's still sitting in the pending checks

https://github.com/KSP-CKAN/NetKAN/pull/7935

**Comment by HebaruSan** [comment]
@techman83  All of the builds for CKAN-meta can be cancelled, they're not needed. The NetKAN ones are what we care about.

**Comment by techman83** [comment]
Stuck netkan job, it's supposed to run both projects at the same time. Sorted it out.
