### ISSUE TITLE
[Bug] PlanetShine missing dependency error

### ISSUE THREAD

**Issue by NanoExplorer** [KSP-CKAN/NetKAN#7946]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.27.2
* KSP Version: 1.9.1.2788

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Added Gamedata/PlanetShine/Config folder containing CelestialBodies.cfg and Settings.cfg after game crash related to these missing files.

Problem
-------
**Describe the bug**
From the Status Log tab of CKAN:

Module "ReStock" successfully installed
Module "ReStock+" successfully installed
Module "Spectra" successfully installed
The following inconsistencies were found:
* PlanetShine 0.2.6.3 missing dependency PlanetShine-Config
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open a issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose

**Steps to reproduce**
From a fresh KSP install, I installed several mods, including Spectra and PlanetShine.
Today I tried to update Spectra, and two ReStock mods, and received this error.

PlanetShine-Config is not an available package in CKAN, and PlanetShine - default config conflicts with Spectra apparently (even though spectra does not bundle any configuration data for PlanetShine)

**Comment by HebaruSan** [comment]
> PlanetShine-Config is not an available package in CKAN

PlanetShine-Config-Default provides it, though, so it would be pulled in :

https://github.com/KSP-CKAN/NetKAN/blob/b8d2839bb46a2f7d9d6cc6ee9e15c95c70e25b03/NetKAN/PlanetShine-Config-Default.netkan#L17-L19

> PlanetShine - default config conflicts with Spectra apparently (even though spectra does not bundle any configuration data for PlanetShine)

Why do you say that? Maybe you have more information that could help with the investigation.

**Comment by NanoExplorer** [comment]
I think that if I had not installed Spectra CKAN would have installed PlanetShine-Config-Default, but if I go to the "relationships" tab for Spectra, PlanetShine-Config is listed with an exclamation point triangle next to it, indicating that with Spectra installed CKAN will not install PlanetShine-Config. If I had to take a guess, I'd say this conflict was added in error and Spectra does not actually conflict with PlanetShine-Config.

I'm not sure that Spectra is doing much at the moment, since it's mostly config files for EVE and Kopernicus (which don't run on 1.9) so I tried uninstalling it (so I can install PlanetShine-Config) and managed to crash CKAN. I'll try again in the morning.

**Comment by NanoExplorer** [comment]
OK, now that I've uninstalled spectra and installed planetshine config, spectra doesn't list planetshine config as a conflict anymore. It could have been because I manually installed planetshine config.

I wonder how I managed to install planetshine without planetshine config in the first place, leading me to install the planetshine config files manually, causing this issue...

**Comment by HebaruSan** [comment]
OK, I'm guessing you installed Spectra before #7891; it did used to provide and conflict with PlanetShine-Config. Then later that was removed, and you would have tried to upgrade to the new release without that.
