### ISSUE TITLE
[Mod] Radial Engine for spacecraft

### ISSUE THREAD

**Issue by Monniasza** [KSP-CKAN/NetKAN#7952]
Mod info
--------
* Mod name: Radial Engine for spacecraft
* Author(s): [Kevin4D](https://spacedock.info/profile/Kevin4D)
* License:  configs: MIT, assets: All Rights Reserved
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/192553-19x-radial-engine-for-spacecraft-tgol-group/
* Download: https://spacedock.info/mod/668/%20Radial%20Engine%20for%20spacecraft%20-%20T.G.O.L%20group%20?ga=%3CGame+3102+%27Kerbal+Space+Program%27%3E

**Comment by HebaruSan** [comment]
I think you can guess what I'm about to ask...

**Comment by Monniasza** [comment]
@HebaruSan 
> I think you can guess what I'm about to ask...

Did you ask the author?

**Comment by HebaruSan** [comment]
Please let us know if the author ever responds.

**Comment by Monniasza** [comment]
@HebaruSan 
> Please let us know if the author ever responds.
No
