### ISSUE TITLE
Merged PR not available in CKAN.exe

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7954]
I merged the following PR 10 hours ago, CKAN still isn't seeing it when I refresh:

https://github.com/KSP-CKAN/NetKAN/pull/7953

**Comment by DasSkelett** [comment]
Yes, see this comment on the out-of-order-version PR:
https://github.com/KSP-CKAN/CKAN-meta/pull/2005#issuecomment-637216303

**Comment by linuxgurugamer** [comment]
I just did, was coming to close this.  You guys are too fast for me
