### ISSUE TITLE
Mod tag typo

### ISSUE THREAD

**Issue by embermctillhawk** [KSP-CKAN/NetKAN#7957]
Mod info
--------
* Mod name: Double It
* Author(s): Hyper_Fun
* License: CC0
* Homepage: https://spacedock.info/mod/2399/Double%20It
* Download: 

This mod is already in CKAN. However, it is not tagged under "planet-pack", but under the less common "plant-pack". The intriguing possibility of additional flora to discover aside, is there anything to be done on CKAN's end for this or should I try to get a hold of the author? I would have already done so but I find SpaceDock's UI confusing. I can't find where the tags for a mod are listed.

**Comment by HebaruSan** [comment]
Thanks for letting us know! Should be fixed in a couple of minutes, maybe an hour.

**Comment by HebaruSan** [comment]
https://github.com/KSP-CKAN/CKAN-meta/commit/5bdac59454fdb07af51fbc444b83e0e9705854aa
