### ISSUE TITLE
[Mod] [Mutiple packages] Textures Unlimited Recolour Depot

### ISSUE THREAD

**Issue by Monniasza** [KSP-CKAN/NetKAN#7961]
Stock Recolour
* Mod name: Textures Unlimited Stock Recolour Pack
* Download: https://drive.google.com/file/d/1GXjyxHEFhdBYEaFlYWpaXEwOP8QcyoJD/view
--------
MK2 Expansion
* Mod name: Textures Unlimited MK2 Expansion Pack
* Download: https://drive.google.com/file/d/18promxfAPvGYYSoKgWGt0bn5n6vEyQen/view
Requires Stock Recolour
--------
MK3 Expansion
* Mod name: Textures Unlimited MK3 Expansion Pack
* Download: https://drive.google.com/file/d/1o9RpuwRir9r3m8FQEjQyw4cwWE-4rgDn/view
Requires Stock Recolour
--------
MKIV Spaceplane Systems
* Mod name: Textures Unlimited MKIV Spaceplane Systems Pack
* Download: https://drive.google.com/file/d/1BISdVmXYdp8ukyCPKuoBQUKonJMzfZmY/view
* License: All Rights Reserved **only** for textures
Requires Stock Recolour
--------
OPT Spaceplane
* Mod name: Textures Unlimited OPT Spaceplane Pack
* Download: https://drive.google.com/file/d/1RJIi1rgDFiReD_DE43aXuXCftknazEMc/view?usp=sharing
Requires Stock Recolour
--------
Procedural Wings
* Mod name: Textures Unlimited Procedural Wings Pack
* Download: https://drive.google.com/file/d/1936dZkTLyZpq5Kesq0kMECOdxG9wJJ4D/view
Requires Stock Recolour
--------
Values shared for all mods (unless otherwise stated):
* Author(s): [Manwith Noname](https://forum.kerbalspaceprogram.com/index.php?/profile/117203-manwith-noname/)
* License: ![CC BY-NC-SA](https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png)
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/174188-18x-textures-unlimited-recolour-depot/

**Comment by HebaruSan** [comment]
Two of these won't work because Google Drive's virus scan warning comes up.

![image](https://user-images.githubusercontent.com/1559108/83946435-766e4700-a7d6-11ea-87ea-d20d31c677d5.png)

![image](https://user-images.githubusercontent.com/1559108/83946445-80904580-a7d6-11ea-83f3-f0b174fb8c90.png)

**Comment by Monniasza** [comment]
@HebaruSan You can download them and then scan.

**Comment by HebaruSan** [comment]
@Monniasza But the CKAN client will not be able to download them; users will just get an error. We have had this problem before with Google Drive links.

**Comment by Monniasza** [comment]
@HebaruSan You can ask the author to reupload them to some other webite.

**Comment by Monniasza** [comment]
Asked the author for re-upload: https://forum.kerbalspaceprogram.com/index.php?/topic/174188-18x-textures-unlimited-recolour-depot/&do=findComment&comment=3798322

**Comment by Monniasza** [comment]
@HebaruSan The author didn't reply yet. OPT and Stock possibly can be reuploaded, and other packages may be added immediately after the upload (mention in this issue).

**Comment by HebaruSan** [comment]
Looks like it's still on Google Drive. Please let us know if there's a move to another host.

**Comment by Monniasza** [comment]
@HebaruSan
> Looks like it's still on Google Drive. Please let us know if there's a move to another host.

There is no reupload.

**Comment by Monniasza** [comment]
> Looks like it's still on Google Drive. Please let us know if there's a move to another host.

@HeabruSan Asked again, after he became active again: https://forum.kerbalspaceprogram.com/index.php?/topic/174188-18x-textures-unlimited-recolour-depot/&do=findComment&comment=3821437
