### ISSUE TITLE
[Mod] kRPC.MechJeb

### ISSUE THREAD

**Issue by Genhis** [KSP-CKAN/NetKAN#7963]
Mod info
--------
* Mod name: kRPC.MechJeb
* Author(s): Genhis
* License: GPL-3.0
* Homepage: https://genhis.github.io/KRPC.MechJeb/
* Download: https://github.com/Genhis/KRPC.MechJeb/releases

**Comment by HebaruSan** [comment]
Hi, thanks for the request!

CKAN does not index pre-releases, so we'll need a normal release to list.

![image](https://user-images.githubusercontent.com/1559108/84088795-fc46e980-a9b2-11ea-83fc-c39fc8741964.png)

And after that's fixed, the backslashes in the file names are not valid in the ZIP format, which causes a fatal validation error when we try to scan it:

![image](https://user-images.githubusercontent.com/1559108/84088906-3fa15800-a9b3-11ea-8d00-12a88d2eccbf.png)

> 2445 [1] FATAL CKAN.NetKAN.Program (null) - https://github.com/Genhis/KRPC.MechJeb/releases/download/v0.6.0/krpc-mechjeb-0.6.0.zip is not a valid ZIP file: Error in step EntryHeader for C#/MechJeb.cs: Exception during test - 'Central header and local header file name mismatch'

We've seen this before with certain ZIP creation tools, mainly ones embedded in .NET I believe if that helps. The standard Unix `zip` utility does fine.

**Comment by HebaruSan** [comment]
@Genhis, all of the releases are still pre-releases. If this is fixed at some point, please let us know and we can re-open this.

**Comment by Genhis** [comment]
Thank you. I am quite busy at the moment but as soon as I get next release ready, I'll let you know.
