### ISSUE TITLE
[Bug] Cannot install "AVP-Textures" for "Astronomers Visual Pack"

### ISSUE THREAD

**Issue by Artemonim** [KSP-CKAN/NetKAN#7974]
Background
----------
* Operating System: Win10 Pro
* CKAN Version: 1.27.2
* KSP Version: 1.9.1.2788

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Yes, but not with this mod.

Problem
-------
1. AstronomersVisualPack 2:v4.04 depends on AVP-Textures, which is not compatible with the currently installed version of KSP
   1. AVP-2kTextures v1.11 depends on AstronomersVisualPack, which is not compatible with the currently installed version of KSP
   2. AVP-4kTextures v1.11 depends on AstronomersVisualPack, which is not compatible with the currently installed version of KSP
   3. AVP-8kTextures v1.11 depends on AstronomersVisualPack, which is not compatible with the currently installed version of KSP

My guess is that they are going into some kind of cyclical dependency, which is why CKAN can't properly handle their "Max KSP version".

**Comment by HebaruSan** [comment]
No, it's the EVE dependency. Check the relationships tab.

![image](https://user-images.githubusercontent.com/1559108/84597019-99c47200-ae26-11ea-9e3b-3672f3c641b7.png)

**Comment by Artemonim** [comment]
I apologize for forgetting to clarify: I allowed CKAN to install modifications starting from KSP v1.8 and up to 1.9.1

![2020-06-14_19-17-46](https://user-images.githubusercontent.com/36363466/84598493-cfdc1300-ae73-11ea-826b-67227ed983fc.png)
![2020-06-14_19-18-10](https://user-images.githubusercontent.com/36363466/84598506-eedaa500-ae73-11ea-904d-682ec2c24573.png)

**Comment by HebaruSan** [comment]
When I try that, it installs without any problems and the relationships look fine.

![image](https://user-images.githubusercontent.com/1559108/84598654-ea8d9800-ae31-11ea-8e63-4f595518cb6b.png)

**Comment by HebaruSan** [comment]
@Artemonim, what other mods do you have installed? Maybe one of them has a conflict with AVP (notably JNSQ has this).

**Comment by Artemonim** [comment]
It turned out that first you had to put the EVE Stock Config on deletion, apply it, and only then try to install AVP. I tried to do it together and here it is.
[Desktop 2020.06.15 - 01.47.18.03.zip](https://github.com/KSP-CKAN/NetKAN/files/4777360/Desktop.2020.06.15.-.01.47.18.03.zip)

Check whether "Environmental Visual Enhancements-HR" is written correctly in the CKAN and in "AstronomersVisualPack" conflicts section.

**Comment by HebaruSan** [comment]
Yup, they're correct. Glad you got it working!
