### ISSUE TITLE
[Mod] "Real Fuels" and "ScrapYard" do not have new versions in CKAN for more than a day

### ISSUE THREAD

**Issue by Artemonim** [KSP-CKAN/NetKAN#7976]
![Kerbal Space Program Screenshot 2020 06 16 - 08 56 13 24](https://user-images.githubusercontent.com/36363466/84813450-a90b1180-b018-11ea-9599-773960890572.png)

**Comment by HebaruSan** [comment]
The RealFuels release is a pre-release. CKAN doesn't index pre-releases.

![image](https://user-images.githubusercontent.com/1559108/84824841-26695e80-afe6-11ea-8bb7-0b6ddce53d8f.png)

The latest version of ScrapYard on SpaceDock is 2.1.0.0.

https://spacedock.info/mod/1746/ScrapYard
