### ISSUE TITLE
FAR-C installation fails

### ISSUE THREAD

**Issue by osunpokeh** [KSP-CKAN/NetKAN#7979]
Background
----------
* Operating System: Wiindows 10 x64
* CKAN Version: 1.27.2
* KSP Version: 1.9.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No changes have been made to my GameData folder outside CKAN.

Problem
-------
**Describe the bug**
Install of FAR-C fails with error message 

```
Oh no!

It looks like you're trying to install a mod which is already installed,
or which conflicts with another mod which is already installed.

As a safety feature, the CKAN will *never* overwrite or alter a file
that it did not install itself.

If you wish to install FerramAerospaceResearchContinued 3:0.15.11.4 via the CKAN,
then please manually uninstall the mod which owns:

Ships/@thumbs/SPH/E42.png

and try again.
Your GameData has been returned to its original state.
```

**Steps to reproduce**
Enable compatibility for 1.9, 1.8, 1.7
Install RO (which contains FAR)

**Expected behavior**
Successful install message

**CKAN error code (if applicable):**

```
None given
```

**Comment by HebaruSan** [comment]
https://github.com/KSP-CKAN/CKAN/wiki/Clean-and-reinstall-process#remove-modded-ships

**Comment by kylemiller3** [comment]
I'm having the same issue. Fresh install - no other mods and verified the game integrity. 

```
About to install...

 * Ferram Aerospace Research Continued 3:0.15.11.4 (cached)
 * Module Manager 4.1.3 (cached)
 * ModularFlightIntegrator 1.2.7.0 (cached)

Oh no!

It looks like you're trying to install a mod which is already installed,
or which conflicts with another mod which is already installed.

As a safety feature, the CKAN will *never* overwrite or alter a file
that it did not install itself.

If you wish to install FerramAerospaceResearchContinued 3:0.15.11.4 via the CKAN,
then please manually uninstall the mod which owns:

Ships/@thumbs/SPH/E42.png

and try again.
Your GameData has been returned to its original state.
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open a issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose
```

**Comment by HebaruSan** [comment]
@kylemiller3 obviously NOT a fresh install. Those craft files came from somewhere!
https://github.com/KSP-CKAN/CKAN/wiki/Clean-and-reinstall-process#remove-modded-ships

**Comment by kylemiller3** [comment]
I don’t know what you want me to say. I verified the files; It didn’t work, same error. I deleted install entirely through steam and again same error. I’ll delete the install and verify again and report back.

**Comment by kylemiller3** [comment]
Deleting the ships folder and re-verifying worked but not deleting the game through steam. Weird to me

**Comment by DasSkelett** [comment]
> Deleting the ships folder and re-verifying worked but not deleting the game through steam. Weird to me

Steam keeps additional, not self-installed, files after uninstall, just like CKAN does.
