### ISSUE TITLE
[Mod] Knes

### ISSUE THREAD

**Issue by don-vip** [KSP-CKAN/NetKAN#7987]
Mod info
--------
* Mod name: Knes
* Author(s): [Well](https://forum.kerbalspaceprogram.com/index.php?/profile/145290-well/)
* License: CC BY-NC-ND 4.0
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/164035-191-knes-172-time-to-explore
* Download: https://spacedock.info/mod/1470/Knes

**Comment by HebaruSan** [comment]
https://forum.kerbalspaceprogram.com/index.php?/topic/164035-191-knes-172-time-to-explore/&do=findComment&comment=3342931

> I don't use CKAN. I don't know how it works, and i don't care about it.
>
> I don't have the time for supporting that.
>
> But, If that respect my licence, make what you want

That sounds like it's OK with the author. :heavy_check_mark:
