### ISSUE TITLE
[Mod] LLL-Continued

### ISSUE THREAD

**Issue by hypodronic** [KSP-CKAN/NetKAN#7989]
Mod info
--------
* Mod name: Lack Luster Labs Continued
* Author(s): Lack
* License: (CC BY-NC-SA 4.0). 
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/151603-14x-15x-lll-continued-dev-thread-updating-for-14x/
* Download: https://github.com/linuxgurugamer/LLL-Continued/releases/tag/1.2.1.1

Version currently on CKAN is from pre-KSP 1.2, so it's more broken than the 2019 pre-release.

**Comment by HebaruSan** [comment]
This is already indexed.
- #4431
- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/LLL.netkan

**Comment by hypodronic** [comment]
Like I said, it is indexed way out of date, I'm requesting that it be updated to the current version.

**Comment by HebaruSan** [comment]
Oh I see. @linuxgurugamer made a bunch of pre-releases.

https://github.com/linuxgurugamer/LLL-Continued/releases

![image](https://user-images.githubusercontent.com/1559108/85250617-afd0c480-b41c-11ea-9a19-07dd7b3e0c99.png)

CKAN doesn't index pre-releases.
