### ISSUE TITLE
Ships/SPH/A Nuke Cruiser-Skalou-03.craft installed by both RecycledPartsRSCapsuledyne and RecycledPartsFarscape

### ISSUE THREAD

**Issue by imWACC0** [KSP-CKAN/NetKAN#7992]
No idea what this means, I'm just following orders.

> Oh no! We tried to overwrite a file owned by another mod!
> Please try a `ckan update` and try again.
> 
> If this problem re-occurs, then it maybe a packaging bug.
> Please report it at:
> 
> https://github.com/KSP-CKAN/NetKAN/issues/new
> 
> Please including the following information in your report:
> 
> File      : Ships/SPH/A Nuke Cruiser-Skalou-03.craft
> Installing Mod : RecycledPartsRSCapsuledyne 0.2.0.1
> Owning Mod: RecycledPartsFarscape
> CKAN Version   : v1.27.2
> Your GameData has been returned to its original state.

**Comment by HebaruSan** [comment]
@linuxgurugamer which of these mods should own `Ships/SPH/A Nuke Cruiser-Skalou-03.craft`, RecycledPartsRSCapsuledyne or RecycledPartsFarscape?

**Comment by imWACC0** [comment]
I do not know. I ass-u-me both might have it.

**Comment by HebaruSan** [comment]
Craft file | Modded parts | Mod
:-- | :-- | :--
A Nuke Cruiser-Skalou-03.craft | NuclearJetEngine | RecycledPartsAtomicAge
Farscape 1.craft | MNZFarscape MNZFarscapeWingLH MNZFarscapeWingRH MNZFARENG MNZFarscapeGearNose MNZFarscapeGearLH MNZFarscapeGearRH | RecycledPartsFarScape
Farscape (Hetch).craft | MNZFarscape MNZFarscapeWingLH MNZFarscapeWingRH MNZFARENG MNZFarscapeGearNose MNZFarscapeGearLH MNZFarscapeGearRH | RecycledPartsFarScape

So, RecycledPartsRSCapsuledyne shouldn't be installing any craft files.
