### ISSUE TITLE
Update SSTO Project

### ISSUE THREAD

**Issue by Monniasza** [KSP-CKAN/NetKAN#7997]
I've updated SSTO Project on request of [theJesuit](https://forum.kerbalspaceprogram.com/index.php?/profile/122369-thejesuit/) to work with TETRIX Tech Tree.

Please add:
- Compatible: TETRIX Tech Tree, Bluedog Design Bureau, Behemoth Aerospace Engineering, RealEngines, Real Scale Boosters
- Suggested: B9 Aerospace, 
- Recommended: Community Tech Tree, Real Solar System, Modular Fuel Tanks, SMURFF

**Comment by HebaruSan** [comment]
Thanks for letting us know, should be updated in a couple of minutes, maybe an hour.
