### ISSUE TITLE
GPP and Grannus Expansion Pack include some of the same files preventing install

### ISSUE THREAD

**Issue by feardosi** [KSP-CKAN/NetKAN#8023]
These mods are compatible with each other. There are several files in the Grannus folder that I would think CKAN could recognize as already being installed by another owning mod and skip installing those files? Or give dual ownership, though I suppose things might become a bit messy this way perhaps?

GameData/Nereid/FinalFrontier/Ribbons/Grannus/Atmosphere.png
Installing Mod : GrannusExpansionPack 1.2.1
Owning Mod: GPP
CKAN Version   : v1.27.2

**Comment by HebaruSan** [comment]
Hmm, might have to involve @OhioBob to figure this out. Those files are indeed in both mods' ZIP files, so the conflict is real, and CKAN doesn't skip files or do dual ownership.

I guess we could create a Grannus-Ribbons package that extracts just this folder, then filter it out of the other modules and make them depend on Grannus-Ribbons? Otherwise we would have to choose which mod gets to own the ribbons, and that doesn't seem right.

**Comment by HebaruSan** [comment]
OK, GPP's metadata is in a metanetkan, so we'll have to do PRs over there to get this refactored:

- https://github.com/Galileo88/Galileos-Planet-Pack/tree/master/CKAN

**Comment by HebaruSan** [comment]
We would have to choose whether to source a new Grannus-RibbonPack module from GPP or GEP. Unfortunately this could mean a lot of extra downloading for some users; if the ribbons come from GEP, then a user installing GPP would have to download both GPP and GEP, just to get the ribbons. Or vice versa if we sourced them from GPP.

**Comment by feardosi** [comment]
Thinking about this, perhaps having a Grannus Expansion Pack-GPP Compatible which basically just has the ribbons removed and has GPP listed as a dependency?

**Comment by HebaruSan** [comment]
I think I'd rather keep GrannusExpansionPack as the one GrannusExpansionPack mod. What if we find another subtle conflict later, are we going to have...

- GrannusExpansionPack-GPPCompatible-OPMCompatible
- GrannusExpansionPack-GPPIncompatible-OPMCompatible
- GrannusExpansionPack-GPPCompatible-OPMIncompatible
- GrannusExpansionPack-GPPIncompatible-OPMIncompatible

... and so on? The upgrade path is not pretty either, users initially installing regular GEP would have to uninstall and switch to GEP-GPPCompatible to install GPP.

___

The big-downloads issue could be mitigated by making _two_ modules: Grannus-RibbonPack-FromGEP and Grannus-RibbonPack-FromGPP, both providing and conflicting with Grannus-RibbonPack. Then the user could simply choose whichever the version corresponding to the main mod they're already installing.

**Comment by HebaruSan** [comment]
Should be possible to install GPP and GEP soon (typically ~5 minutes of delay when things update on GitHub).

GPP will implicitly conflict with the new ribbon pack modules until Galileo88/Galileos-Planet-Pack#64 is merged, but after that everything should be pretty smooth.
