### ISSUE TITLE
Possible timing issue

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#8034]
Could you check BetterLoadSaveGame?  I updated the mod, and then went and updated the netkan file for a new dependency.
My local CKAN updated, and does not show the SpaceTuxLibrary as a dependency

**Comment by linuxgurugamer** [comment]
Oh, i see it updated, closing

**Comment by HebaruSan** [comment]
@linuxgurugamer if you want it to be faster, check the CKAN checkbox on SpaceDock. Otherwise SpaceDock doesn't send notifications.

https://spacedock.info/mod/2326/Better%20Load%20Save%20Game%20Renewed

**Comment by linuxgurugamer** [comment]
@HebaruSan It was already in there, I was updating it to add a new dependency.  It wasn't the speed, it was just that I essentially crossed over the changes, I should have updated the netkan first and then updated the mod
