### ISSUE TITLE
Connectivity problems from China to SpaceDock

### ISSUE THREAD

**Issue by guozijing-zjk** [KSP-CKAN/NetKAN#8051]
Background
----------
* Operating System:  Windows10
* CKAN Version:  v1.28.0
* KSP Version:  1.10.0.2917

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

- No manual changes have been made to the game files

Problem
-------
**Describe the bug**
[I was trying to play with the "Realism Overhaul" module last night, and then I installed it manually and found that it had The game crashed.....
Then one of my "gay friends" recommended the module manager CKAN to me, and I was so happy! However, when I select the module Realism Overhaul and install it, it always fails to download. (probably because I have a bad network in China), however, I have a VPN enabled on my computer, and I am connected to a server in Hong Kong (which makes the network better.) (Key China has the Great Firewall, you know) The network is a little better, but the download still fails.... I think it's the Mod metadata....]
(Translated above from DeepL，Because my English isn't good........)

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**
![批注 2020-07-18 112151](https://user-images.githubusercontent.com/26113017/87843677-0e3c7600-c8e9-11ea-9d55-aad3d256f172.png)

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Hi, welcome, and I hope we'll be able to communicate!

> I think it's the Mod metadata....

The mod metadata for ToolbarController and KSP-AVC is fine, as far as I can tell. What problems did you notice with the metadata?

My guess is that this is a network problem. I've reached out to the SpaceDock team to see if they have any tips about connecting from China. Do the archive.org fallback downloads finish?
