### ISSUE TITLE
[Bug] Can't update OPT-Reconfig, metadata contains wrong filesize

### ISSUE THREAD

**Issue by hypodronic** [KSP-CKAN/NetKAN#8055]
Background
----------
* Operating System: Win 10
* CKAN Version: 1.28.0
* KSP Version: 1.10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No.

Problem
-------
**Describe the bug**
Can't install OPTReconfig, metadata contains wrong file size. File on both Spacedock & Github is 2799708, CKAN expects 2799702.

**Steps to reproduce**
Hit "update all", batch includes OPT & OPT-Reconfig. Downloading OPT-Reconfig throws the below error.

**Expected behavior**
Update OPT-Reconfig.

**Screenshots (if applicable)**
n/a

**CKAN error code (if applicable):**

CKAN.InvalidModuleFileKraken: OPTReconfig 2.0.6: C:\Users\John\AppData\Local\Temp\tmp2E7F.tmp has length 2799708, should be 2799702
   at CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error)

**Comment by Avalon2neo** [comment]
With me too...

CKAN.InvalidModuleFileKraken: OPTReconfig 2.0.6: C:\Users\Gianni\AppData\Local\Temp\tmpD95E.tmp has length 2799708, should be 2799702
   a következő helyen: CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   a következő helyen: CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error)

**Comment by HebaruSan** [comment]
Replaced by KSP-SpaceDock/SpaceDock#312, the CKAN code seems to be functioning properly here.
