### ISSUE TITLE
[Mod] BDArmory for Runway Project

### ISSUE THREAD

**Issue by josuenos** [KSP-CKAN/NetKAN#8064]
Mod info
--------
* Mod name: BDArmory for Runway Project
* Author(s): illectro, JR, DocNappers, Cl0by, Josue, aubranium, benbenwilde, TheKurgan
* License: CC BY-SA 2.0
* Homepage: https://docs.google.com/document/d/1taFjsHjuBoWwbpLLyg5V7c72eQUGGuPHdLIf0LueX_o/edit#heading=h.ozhxjvdiq0ma
* Download: https://spacedock.info/mod/2487/BDArmory%20for%20Runway%20Project
* Source Code: https://github.com/BrettRyland/BDArmory/

**Comment by HebaruSan** [comment]
Thanks! SpaceDock got us started already at #8063.
