### ISSUE TITLE
16k RSS texture pack

### ISSUE THREAD

**Issue by siimav** [KSP-CKAN/NetKAN#8069]
With the latest RSS-Textures release we've added our own official 16k texture pack in addition to Vannadin's 16k textures. Actually the new release is already based on @Vannadin 's work which we've used with their permission and added some of our own improvements on top of that. Now the issue is that heightmap handling changed for some of the planets which makes Vannadin's current release incompatible with the latest RSS.  Additionally it looks like this pack also uses the `RSSTextures16K` identifier which we would have preferred to use for official textures. What do you think would be the best approach to go forward with from the CKAN perspective?
Also does CKAN support setting up release compatibility based on dependency versions instead of KSP versions? This might come in handy since both the RSS and RSS-textures currently only work with the latest releases of each other.

**Comment by HebaruSan** [comment]
Links for convenience:

- #7699
- #7700
- https://github.com/KSP-RO/RSS-Textures
- https://github.com/KSP-RO/RSS-Textures/releases

**Comment by HebaruSan** [comment]
> Now the issue is that heightmap handling changed for some of the planets which makes Vannadin's current release incompatible with the latest RSS.
> Also does CKAN support setting up release compatibility based on dependency versions instead of KSP versions? This might come in handy since both the RSS and RSS-textures currently only work with the latest releases of each other.

What changed to become incompatible? Was it RSS itself, or KSP, or Kopernicus...?

**Comment by siimav** [comment]
Yes, RSS itself. Changes to RSS and the -Textures means that the latest releases do not work together with any of the previous releases even though those are also meant for the same KSP version.
