### ISSUE TITLE
[Mod] Principia

### ISSUE THREAD

**Issue by PhakphumV** [KSP-CKAN/NetKAN#8076]
Mod info
--------
* Mod name: Principia
* Author(s):  mockingbirdnest 
* License: MIT license
* Homepage: https://github.com/mockingbirdnest/Principia
* Download: https://bit.ly/3fFGN2g

Hello, I'm not sure if my request here is appropriate as I'm not an author of this mod.
As a KSP player, I would like to have this mod indexed in CKAN.
Please feel free to share if it's feasible or need some collaboration from its author.

**Comment by HebaruSan** [comment]
I'll see if I can find the most recent previous request, but this has come up before and we decided not to index it (with the author's agreement) because it requires external third-party dependencies that CKAN doesn't install (some C++ libraries). Sorry for the disappointment.

**Comment by HebaruSan** [comment]
- #6242
- #5643
- mockingbirdnest/Principia#1720
- mockingbirdnest/Principia#2656

**Comment by PhakphumV** [comment]
Thank you for your prompt reply. :+1:
