### ISSUE TITLE
Metadata Issue - IXS-Warpship-OS

### ISSUE THREAD

**Issue by etmoonshade** [KSP-CKAN/NetKAN#8079]
I'm kinda surprised y'all don't have a specific category for metadata issues.

Currently, the forum link for this mod is as follows:
https://forum.kerbalspaceprogram.com/index.php?/topic/191422-18x-ixs-warpship-spacedock-redocked-betas/&do=edit

This takes you to a "can't edit this" page, which makes sense - I'm definitely not the mod author.
Removing the &do=edit allows the link to work as expected.

attn: @linuxgurugamer too - I'm not sure who the task of actually fixing this falls on.

**Comment by HebaruSan** [comment]
That was coming from SpaceDock, I just fixed it over there. Should propagate through to CKAN in 30 minutes or less.
