### ISSUE TITLE
[Bug] Incorrect metadata for AT Utils and Configurable Containers

### ISSUE THREAD

**Issue by georgedorn** [KSP-CKAN/NetKAN#8085]
As discussed [here](https://forum.kerbalspaceprogram.com/index.php?/topic/150104-19-110-configurable-containers/&do=findComment&comment=3830296) Configurable Containers 2.6.x and AT_Utils-1.9.6 are not backwards-compatible with KSP 1.9.1.  This manifests as almost every fuel tank containing no resources.  Given that a lot of Kopernicus users are still on 1.9.1, this has caused some problems.

CKAN lets me install specific versions, but I cannot pin a specific version and have the auto-updater ignore updates, so I'm almost certainly going to accidentally install the broken updates again.

The creator of those two mods expresses a [desire to fix the metadata](https://forum.kerbalspaceprogram.com/index.php?/topic/150104-19-110-configurable-containers/&do=findComment&comment=3830198), but this may not be possible from their side alone?  I'm unclear on how prior version's metadata can be corrected.  Perhaps somebody can drop into that thread and clear things up?

**Comment by HebaruSan** [comment]
Thanks. Submitted to help the author fix it:

- allista/AT_Utils#24
- allista/ConfigurableContainers#40

**Comment by HebaruSan** [comment]
Actually @georgedorn, those will only fix the current versions, and from your description it sounds like older versions are affected as well. I'll update CC 2.6.0, but do you know which AT_Utils release broke compatibility with KSP 1.9?

**Comment by georgedorn** [comment]
Oh, I thought there was more to it.  Thanks.  I'll keep this in mind if I find other mods that break backwards compatibility.

**Comment by HebaruSan** [comment]
Well, it's not always quite this easy. These mods are set up properly to support this kind of change. Mileage may vary with others.
