### ISSUE TITLE
[Mod] [Asked again] Radial Engine for spacecraft

### ISSUE THREAD

**Issue by Monniasza** [KSP-CKAN/NetKAN#8098]
* Mod name: Radial Engine for spacecraft
* Author(s): [Kevin4D](https://spacedock.info/profile/Kevin4D)
* License:  configs: MIT, assets: All Rights Reserved
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/192553-19x-radial-engine-for-spacecraft-tgol-group/
* Download: https://spacedock.info/mod/668

The mod author has approved the upload to CKAN: https://forum.kerbalspaceprogram.com/index.php?/topic/192553-19x-radial-engine-for-spacecraft-tgol-group/&do=findComment&comment=3840052

Replaces https://github.com/KSP-CKAN/NetKAN/issues/7952

**Comment by HebaruSan** [comment]
Thanks for persisting! Since the author approves, I decided to try editing the entry on SpaceDock in order to check the "add to CKAN" checkbox, which created #8103 and will ensure fast indexing of new releases.
