### ISSUE TITLE
[Mod] NeptuneCamera

### ISSUE THREAD

**Issue by Tantares** [KSP-CKAN/NetKAN#8101]
Mod info
--------
* Mod name: NeptuneCamera
* Author(s): Beale
* License: MIT
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/196339-110x-neptune-camera-basic-camera-utility-1016082020/
* Download: https://github.com/Tantares/NeptuneCamera/releases

**Comment by HebaruSan** [comment]
Will add this to #8091...
