### ISSUE TITLE
[Mod] TMasterson5's TweakScale patches

### ISSUE THREAD

**Issue by Monniasza** [KSP-CKAN/NetKAN#8123]
Mod info
--------
* Mod name: TMasterson5's TweakScale patches
* Author(s): [TMasterson5](https://forum.kerbalspaceprogram.com/index.php?/profile/144591-tmasterson5/)
* License: ![CC BY-NC-ND 4.0](https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png)
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/181010-tmasterson5-mod-family/
* Download: https://www.dropbox.com/sh/u6cliq18972oo1g/AACzEh7IjLnN2eo-lCXysw07a/TMasterson5TweakscalePatches/TM5TweakscalePatchesV1.zip?dl=1
* Dependency: https://www.dropbox.com/sh/b5ipxgohpwtd4s9/AAACsMMgUQQO0onwnbQV8Y0Wa?dl=1

**Comment by HebaruSan** [comment]
This author last visited the forum in July 2019, so it may not be easy to contact him...
