### ISSUE TITLE
[Mod] Neist Airliner

### ISSUE THREAD

**Issue by Monniasza** [KSP-CKAN/NetKAN#8124]
Mod info
--------
* Mod name: Neist Airliner
* Author(s): [neistridlar](https://forum.kerbalspaceprogram.com/index.php?/profile/20296-neistridlar/)
* License: ![CC BY-NC-SA 4.0](https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png)
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/174152-wip-neist-airliner-parts/
* Download: https://github.com/neistridlar/Neist-Airliner-Parts/releases

The TweakScale patch is located at https://github.com/KSP-CKAN/NetKAN/issues/8123

**Comment by Monniasza** [comment]
The author has agreed to place the mod on CKAN: https://forum.kerbalspaceprogram.com/index.php?/topic/174152-wip-neist-airliner-parts/&do=findComment&comment=3849971

**Comment by HebaruSan** [comment]
Hmm, all of this mod's releases are marked as pre-releases, which CKAN doesn't index:

![image](https://user-images.githubusercontent.com/1559108/92409838-8b3ddc00-f131-11ea-9fa4-fc1e0d9e85ab.png)

So if we do list this mod, it will only take effect once there is a "real" release.

**Comment by Monniasza** [comment]
Please leave an issue on the mod's repository and provide a link.

**Comment by HebaruSan** [comment]
> Please leave an issue on the mod's repository and provide a link.

Here's why I'm not going to do that:

![image](https://user-images.githubusercontent.com/1559108/92412457-79613680-f13b-11ea-80ce-de2440f36ef6.png)

If this author considers these to be pre-releases, that's his own decision to make, and it's not an "issue" to be fixed.

**Comment by Monniasza** [comment]
> > Please leave an issue on the mod's repository and provide a link.
> 
> Here's why I'm not going to do that:
> 
> ![image](https://user-images.githubusercontent.com/1559108/92412457-79613680-f13b-11ea-80ce-de2440f36ef6.png)
> 
> If this author considers these to be pre-releases, that's his own decision to make, and it's not an "issue" to be fixed.

You'll need to add parameter to .ckan file that allows pre-releases to be indexed.

**Comment by HebaruSan** [comment]
No, we don't need to do that.

**Comment by HebaruSan** [comment]
Will re-open if this mod ever publishes a non-pre-release (I signed up for notifications).
