### ISSUE TITLE
[Bug] Updated L-TechContinued not visible in CKAN

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#8137]
I updated the LTechContinued file last night, changed it from frozen to .netkan and updated the data

It's been merged, but hasn't yet shown up in CKAN, AFAICT

**Comment by DasSkelett** [comment]
https://github.com/KSP-CKAN/CKAN-meta/pull/2154#issuecomment-688588804

**Comment by linuxgurugamer** [comment]
Hmmm.  I added an epoch statement, committed, but I don't see it in https://github.com/KSP-CKAN/CKAN-meta
Sorry about closing that commit you did, I'm kind of working on autopilot due to some meds for a migraine.  
Not going to make any other changes right now.

Reason for the renumbering was the old version uas using the major and minor, and I wanted to use  minor, patch & build.

**Comment by DasSkelett** [comment]
Just give it a few minutes, it's here now: https://github.com/KSP-CKAN/CKAN-meta/commit/1695e841699777470705e5aa23f7435e582720ae

> Sorry about closing that commit you did

That was an automated PR, no worries. Both achieved the same in the end, so everything fine :+1: 

Get well soon!

**Comment by linuxgurugamer** [comment]
Thank you
