### ISSUE TITLE
[Metadata] Kerbal Health seems to have some sort of bad data

### ISSUE THREAD

**Issue by etmoonshade** [KSP-CKAN/NetKAN#8139]
When updating Kerbal Health to 1.4.6:

```
CKAN.InvalidModuleFileKraken: KerbalHealth v1.4.6: _%appdata%_\Local\Temp\tmp8C6C.tmp has length 108046, should be 108051
   at CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error)
```

I've attempted deleting the file pointed to and trying again, and removing extra temporary files to move where the file lands on the SSD. All other mods appear to be updating correctly.

**Comment by DasSkelett** [comment]
Looks like a ninja reupload from the author. The bot has already picked up the changed zip and updated the metadata: https://github.com/KSP-CKAN/CKAN-meta/commit/7904dc038c013a239868525252b7809da0c7fa45#diff-29595738c0c9be568f955e17f2ba8fd0

Try hitting "Refresh" in CKAN and try again, it should work then.

**Comment by etmoonshade** [comment]
Huh, yup. Guess I had bad timing there - I know there were a couple of issues with the upload mentioned on the mod page, but they'd been more than a few hours prior to the report.
Thanks @DasSkelett ! I'll close this.
