### ISSUE TITLE
[Mod] Ven's New Parts subdirectory renaming in next version

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [KSP-CKAN/NetKAN#8141]
Mod info
--------
* Mod name: Ven's New Parts
* Author(s): Kerbas_ad_astra
* License: CC-BY
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/189732-19x-vens-stock-revamp-resurrected-v1151-nattering-nodes-of-negativism-02020-mar-15/
* Download: https://github.com/Kerbas-ad-astra/Stock-Revamp/releases

To facilitate Module Manager patches, the subfolder containing Ven's New Parts is being renamed from "Part Bin" to "PartBin".  I believe this will require a change in the netkan file: https://github.com/KSP-CKAN/NetKAN/blob/3a59435cd45e92c8f348a3ce17c6ef8588008b64/NetKAN/VenStockRevamp-NewParts.netkan#L26.

**Comment by HebaruSan** [comment]
Thanks for the heads-up. You can go ahead and upload the release, the NetKAN bot will print an error and we will make the update.

**Comment by HebaruSan** [comment]
We can handle this change without having an open issue for it; closing to tidy up a bit.
