### ISSUE TITLE
[Mod]Less Simple Isru

### ISSUE THREAD

**Issue by juanml82** [KSP-CKAN/NetKAN#8167]
Mod info
--------
* Mod name: Less Simple Isru
* Author(s): juanml82
* License: GNU LESSER GENERAL PUBLIC LICENSE
                       Version 3GPLv3
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/192738-18-110less-simple-isru-for-modded-fuels-v03-electrolysis-sabatier-and-more-added-rss-and-nfc-integration/
* Download: https://spacedock.info/mod/2378/Less%20Simple%20ISRU

**Comment by HebaruSan** [comment]
Already indexed in #7802.

- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/LessSimpleISRU.netkan
- https://github.com/KSP-CKAN/CKAN-meta/tree/master/LessSimpleISRU

**Comment by HebaruSan** [comment]
(Presumably this is harder to find now thanks to BobPalmer/CommunityResourcePack#249. Pray for BobPalmer/CommunityResourcePack#252 to get re-opened and merged.)
