### ISSUE TITLE
[Mod] Oddiseo Corp contracts

### ISSUE THREAD

**Issue by oddiseo-ksp** [KSP-CKAN/NetKAN#8172]
Mod info
--------
* Mod name: Oddiseo Corp contracts
* Author(s): Tattie Kerbal
* License:  GPL 3.0
* Homepage: https://github.com/oddiseo-ksp/oddiseo
* Download: https://github.com/oddiseo-ksp/oddiseo

Hi CKAN folks, I've been creating a contract mod and would like to get it added to CKAN so that my friends can install it. I tried to create a `netkan` file myself but didn't have much luck. Would you be able to assist me in getting it into the system?

**Comment by HebaruSan** [comment]
Hi @oddiseo-ksp, you're probably having trouble because your repo has no releases:

- https://github.com/oddiseo-ksp/oddiseo/releases

That's where Netkan looks for ZIPs to download. If you click "Create a new release", it should take you to a page where you can pick a version number and name and upload the contents of the mod:

![image](https://user-images.githubusercontent.com/1559108/95021804-e7185980-0638-11eb-8c49-35274e5d1d8d.png)

**Comment by oddiseo-ksp** [comment]
Thanks @HebaruSan . I've clicked there and created a "v0.1" release, but still no joy. Any ideas?

**Comment by HebaruSan** [comment]
Yes, the "Assets" list in the release should contain a download in addition to the source code links:

![image](https://user-images.githubusercontent.com/1559108/95023750-5e9fb600-0644-11eb-8802-dcb9aa97f30e.png)

Make a ZIP file containing the files you want users to install, then edit the release and click this to upload it:

![image](https://user-images.githubusercontent.com/1559108/95023780-82fb9280-0644-11eb-8d5a-7748fcd6eaeb.png)

**Comment by oddiseo-ksp** [comment]
Oh, right, didn't realise I needed to create those manually. Now done! Do you want to take it from here, or do you want me to open a pull request with my descriptor file?

**Comment by oddiseo-ksp** [comment]
(I should add that I've tested installation via the instructions [here](https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN) and it seems to be working fine.)

**Comment by HebaruSan** [comment]
I took the liberty of starting a PR with your file at #8173. I'll go trigger a rebuild to see if it's working...

**Comment by oddiseo-ksp** [comment]
Looks good!
