### ISSUE TITLE
[Bug]Meta data of Dynamic Battery Storage error

### ISSUE THREAD

**Issue by zkx741481546** [KSP-CKAN/NetKAN#8176]
Background
----------
* Operating System: win10
* CKAN Version: 1.28.0
* KSP Version: 1.8.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Problem
-------
**Describe the bug**
the same as adriaans's
https://forum.kerbalspaceprogram.com/index.php?/topic/186207-110x-dynamic-battery-storage-electricalthermal-planning-and-timewarp-compensation-sept-1/page/6/

According to the mod's author, the Dynamic Battery Storage 2.1.9.0 does not support ksp1.8.1, but CKAN shows it does.

**Comment by HebaruSan** [comment]
This mod's metadata is 100% author-controlled. Try submitting a PR to fix the version file here:

- https://github.com/ChrisAdderley/DynamicBatteryStorage/blob/master/GameData/DynamicBatteryStorage/Versioning/DynamicBatteryStorage.version

**Comment by HebaruSan** [comment]
> According to the mod's author, the Dynamic Battery Storage 2.1.9.0 does not support ksp1.8.1

Also note that the above is not correct:

![image](https://user-images.githubusercontent.com/1559108/95244553-be7a9600-07d7-11eb-8bd7-ae21d7fbb9cf.png)

The possible conflict is specifically with **Kopernicus**. If you install DBS on KSP 1.8.1 _without_ installing Kopernicus, this would not apply.
