### ISSUE TITLE
[Mod] Tantares - Stockalike Soviet Spacecraft

### ISSUE THREAD

**Issue by Tantares** [KSP-CKAN/NetKAN#8178]
Mod info
--------
* Mod name: Tantares - Stockalike Soviet Spacecraft
* Author(s): Beale
* License: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/73686-110x-tantares-stockalike-soyuz-and-mir-2004082020venera-9/
* Download: https://github.com/Tantares/Tantares/releases

**Comment by HebaruSan** [comment]
I believe this is already indexed as "New Tantares":

- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/NewTantares.netkan

@Tantares can you confirm? Is there something about that listing that isn't working as intended?

**Comment by Tantares** [comment]
Hey @HebaruSan .
Apologies, I had received some reports the CKAN version was out of date, but this appears to have been an issue with the Git release being marked as a draft.

I will close this now.
