### ISSUE TITLE
OS Win 10 build 18363.1082 CKAN v1.28.0 KSP 1.10.1.2939

### ISSUE THREAD

**Issue by DareDrop** [KSP-CKAN/NetKAN#8183]
Background
----------
* Operating System: 
* CKAN Version: 
* KSP Version: 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Problem
-------
**Describe the bug**

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Please say something when submitting issues.
