### ISSUE TITLE
[Mod] Request Updates to BDB Netkan

### ISSUE THREAD

**Issue by zorg2044** [KSP-CKAN/NetKAN#8185]
Mod info
--------
* Mod name: Bluedog Design Bureau: https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/BluedogDB.netkan

Hi could you kindly help us with the following updates to the BDB netkan

1) add Simple Adjustable Fairings as a hard dependency for BDB

https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/SimpleAdjustableFairings.netkan

2) update the ``author`` field as follows: ``Cobaltwolf, JSO, Zorg``

3) Add "Contract Configurator" to ``recommends``
https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/ContractConfigurator.netkan

4) Add the following to ``Suggests``
SCANsat https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/SCANsat.netkan
Dock Rotate https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/DockRotate.netkan

5) Add the following to ``Supports``

TACLifeSupport https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/TACLS.netkan
EngineIgnitorReignited https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/EngineIgnitorReignited.netkan

Thanks very much

**Comment by HebaruSan** [comment]
Hi @zorg2044, thanks for the updates!

I'll do most of these in a pull request, but for the `author` change, that field is pulled from the authors list on SpaceDock. I've just added you to the authors list over there, there should be an invitation that you can accept to make it official.

**Comment by zorg2044** [comment]
Thanks a lot!
