### ISSUE TITLE
Kurricane Expanded is not showing up

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#8201]
Mod which has been released for a long time, all of a sudden, in CKAN, it isn't showing up,  The old one (which is frozen) IS showing up.  Not sure if this is a meta data issue or a bug in CKAN

**Comment by DasSkelett** [comment]
It's showing up for me:
![KurrikaneExpanded](https://user-images.githubusercontent.com/28812678/97595488-0621c580-1a04-11eb-834e-3f340ce0c339.png)

Did you check the filter?

**Comment by HebaruSan** [comment]
@linuxgurugamer try updating the compatibility on SpaceDock:

![image](https://user-images.githubusercontent.com/1559108/97612639-ab797100-19e5-11eb-99c7-adf86d2ca4ba.png)

**Comment by linuxgurugamer** [comment]
I have 1.8, 1.8.0 &  1.8.1 compatibility enabled in CKAN.
I wonder if it's the .version file only having KSP_VERSION_MIN in there???
I'd rather not update Spacedock right now, until this gets figured out.  Spacedock currently thinks it's for 1.8.1.
I may update the .version file with the KSP_VERSION and upload it to Spacedock, keeping the compatibility the same
It's just odd, because it did work when I started my current career, then stopped

**Comment by linuxgurugamer** [comment]
Additional info:  when I change the filter to All, it still doesn't show the version on Spacedock, just the one from Beluwel.
So I'm wondering if there is something off in CKAN.  What can I do to fix?
FYI I just updated the spacedoc with an updated .version file

**Comment by HebaruSan** [comment]
> I have 1.8, 1.8.0 & 1.8.1 compatibility enabled in CKAN.

When I try that, I can install it no problem:

![image](https://user-images.githubusercontent.com/1559108/97809208-37330d80-1c31-11eb-8d1f-d3e05e2a41bb.png)

**Comment by linuxgurugamer** [comment]
I'm going to assume it's something wrong on my side, 

Overview of my install:

Window 10 Pro
CKAN.exe is installed:  D:\KerbalInstalls\CKAN\ckan.exe
All games are installed on R:\



I tried

1.  deleting ALL references to the Kurrikane from the registry.json for one install
2. Started CKAN,
3. Selected the install
4. Did a refresh
5. Verified that 1.8, 1.9 & 1.10 are selected in the KSP Compatibility
6.  Verified that both Kurrikane entries are in the registry.json after the refresh.

The original Kurrikane shows up, but the KurrikaneExpanded (my version) does not.

What makes it even stranger is when I look in the history folder and search in those files, the KurrikaneExpanded does show up in there.

I tested on a different computer, and it worked over there.

I compared the registry.json from the second computer with the same file on my main system.  The files were identical up to the end where the "installed_dlls" was different.

So what else would cause an issue like this?

**Comment by linuxgurugamer** [comment]
One more odd thing:  I updated it today to add a KSP_VERSION stanza, and bumped the version number.  Strangely enough, CKAN had me update it, even though I can't see it

**Comment by linuxgurugamer** [comment]
It's now happening on another mod of mine, Fusebox.  I just updated the game version on spacedoc, will see if that helps. 
But why is this happening, and what can I do to fix it?

**Comment by HebaruSan** [comment]
Maybe something to do with tags or labels? Did you add it to the Hidden label, or hide the parts or uncrewed tags in the grid header right click menu?

**Comment by HebaruSan** [comment]
Both Kurricane and FuseBox have the `uncrewed` tag. My guess is that tag is filtered out in your GUI.

**Comment by linuxgurugamer** [comment]
That was it, thank you.
