### ISSUE TITLE
TweakScale has moved

### ISSUE THREAD

**Issue by pellinor0** [KSP-CKAN/NetKAN#821]
Hi, I am the new developer of TweakScale. The Github repo has moved to
https://github.com/pellinor0/TweakScale/

If you keep a link to the release thread, it should now point to
http://forum.kerbalspaceprogram.com/threads/112693

TweakScale now has AVC support, AVC looks at the version file on the master branch. The current release can also be found on KerbalStuff or on Curse (those links are unchanged). 

I also keep a dev branch, which should not be seen by CKAN. So if there is a version v1.52 on master and v1.52.1 on dev, then v1.52 is the stable version that should be distributed. 

Could you check the CKAN references for TweakScale and update them if needed?

**Comment by pjf** [comment]
All hail the new TweakScale! :)

I'm checking out metadata now. Stand by. :)

**Comment by pjf** [comment]
@pellinor0: I've updated the TweakScale metadata in #822. Can you confirm that all looks good to you?
