### ISSUE TITLE
ShipSaveSplicer needs a kick

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#8216]
I accidently uploaded a wrong versoin number to Spacedock for it.  I have since deleted that file and uploaded the correct version, (1.1.6), but I don't see it having been updated in the meta data yet

**Comment by DasSkelett** [comment]
The bot got it this inflation round: https://github.com/KSP-CKAN/CKAN-meta/commit/ae9a9639799dff55e1dbc0a08b8045c285b8a4ed
