### ISSUE TITLE
ShipSaveSplicer install screwup

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#8217]
Following up on my previous ticket (which I can't find)

Its still saving the mod into:  veSplicer

So if I change the directory to:

Ship_Save_Splicer

Will that bypass the problem?

**Comment by HebaruSan** [comment]
The previous ticket was moved to KSP-CKAN/CKAN#3187 because it is due to a bug in code rather than a metadata problem.
We then fixed the bug in KSP-CKAN/CKAN#3180 which was already touching some of the relevant code.
I noted in a comment in #8215 that your install stanza change did nothing.

**Comment by HebaruSan** [comment]
**Please** turn on GitHub notifications so you can be aware of this as it happens.

**Comment by HebaruSan** [comment]
The new version of CKAN should install this to the right folder.

https://github.com/KSP-CKAN/CKAN/releases/tag/v1.29.0

**Comment by linuxgurugamer** [comment]
I asked again because I didn't know when the next release would be, and I couldn't find the closed issue

Tested the new release, it works, thank you for a timely update.
Also like the search bar being moved to the top.
