### ISSUE TITLE
Kerbal Space Program HyperEdit disappeared last night

### ISSUE THREAD

**Issue by zaropas** [KSP-CKAN/NetKAN#8218]
I have been using Hyperedit in KSP.  Currently running the latest KSP.  I install via CKAN which now reports HyperEdit as not compatible.  It was last night.  There was a suggestion that I should log this with you (came from CKAN).  Did a manual install into Game Data but no luck.  Went to Version info in CKAN and clicked the compatibility box for the latest listed version.  Went to install and the error came up as follows;

```
About to install...

 * HyperEdit 1.5.8.0 (cached)

Access to the path 'D:\KSP\GameData\Kerbaltek\HyperEdit.dll' is denied.
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose
```

[KSP.log](https://github.com/KSP-CKAN/NetKAN/files/5505318/KSP.log)

**Comment by HebaruSan** [comment]
HyperEdit's metadata hasn't changed in 8 months.

https://github.com/KSP-CKAN/CKAN-meta/tree/master/HyperEdit

```
Access to the path 'D:\KSP\GameData\Kerbaltek\HyperEdit.dll' is denied.
```

Is the game still running?

**Comment by zaropas** [comment]
The game works fine.  But Hyperedit is not being loaded.  The icon is not there.  I hear you about no changes.  At midnight last night I was using Hyperedit and when I loaded the program today, it was gone.  I went to GitHub and grabbed it again from their site and manually installed it in Game Data and that didn’t work.  CKAN reported the error when I tried going to version.  

 

Weird, eh.


Gord

**Comment by zaropas** [comment]
The game works fine.  But Hyperedit is not being loaded.  The icon is not there.  I hear you about no changes.  At midnight last night I was using Hyperedit and when I loaded the program today, it was gone.  I went to GitHub and grabbed it again from their site and manually installed it in Game Data and that didn't work.  CKAN reported the error when I tried going to version.

Weird, eh.

**Comment by zaropas** [comment]
From: gr.andrews@telus.net <gr.andrews@telus.net> 
Sent: Saturday, November 7, 2020 12:51 PM
To: 'KSP-CKAN/NetKAN' <reply@reply.github.com>; 'KSP-CKAN/NetKAN' <NetKAN@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [KSP-CKAN/NetKAN] Kerbal Space Program HyperEdit disappeared last night (#8218)

 

The game works fine.  But Hyperedit is not being loaded.  The icon is not there.  I hear you about no changes.  At midnight last night I was using Hyperedit and when I loaded the program today, it was gone.  I went to GitHub and grabbed it again from their site and manually installed it in Game Data and that didn’t work.  CKAN reported the error when I tried going to version.  

 

Weird, eh.


Gord

**Comment by HebaruSan** [comment]
Sorry, what I was asking was whether the game is currently open/running when you tried to install in CKAN. On Windows, KSP locks the DLLs that it loads, so that would explain why the DLL could not be written.

**Comment by zaropas** [comment]
I will redo it. Normally I would remind clan first then run the program. Just to be sure I will try again.

**Comment by HebaruSan** [comment]
So you don't know or don't remember whether the game was running at the time?

**Comment by zaropas** [comment]
I am not sure.  I normally don’t run the game first because I want to do any updates before starting.  I just ran ckan and had it install hyperedit again and I didn’t get that error and it appeared that it did install.  However, I just started KSP again and it isn’t there.

 

Here is the log again.

**Comment by zaropas** [comment]
I am not sure.  I normally don’t run the game first because I want to do any updates before starting.  I just ran ckan and had it install hyperedit again and I didn’t get that error and it appeared that it did install.  However, I just started KSP again and it isn’t there.

 

Here is the log again.

**Comment by HebaruSan** [comment]
> I just ran ckan and had it install hyperedit again and I didn’t get that error and it appeared that it did install.

Excellent, sounds like CKAN is working fine!

The support thread for HyperEdit is here:

- https://forum.kerbalspaceprogram.com/index.php?/topic/34785-110-hyperedit
