### ISSUE TITLE
[Bug] Parallax not showing as compatible for stock, up-to-date 1.10.1

### ISSUE THREAD

**Issue by kikanaide** [KSP-CKAN/NetKAN#8231]
Background
----------
* Operating System: Win10 x64
* CKAN Version: 1.29 Eddison
* KSP Version: 1.10.1.2939

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No, new Steam install with no mods.

Problem
-------
**Describe the bug**
Parallax listed as incompatible, despite being released as 1.10.1 only.

**Steps to reproduce**
Open CKAN, see Parallax not listed.  Change to incompatible, find Parallax.

**Expected behavior**
Open CKAN, see Parallax in compatible list.

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/5238761/99189597-8dbb4400-2727-11eb-997d-c5587de0ad59.png)

**Comment by HebaruSan** [comment]
It depends on Kopernicus, which is only for 1.9 by default. See the Kopernicus bleeding edge release to install on 1.10.

https://forum.kerbalspaceprogram.com/index.php?/topic/195699-191-1101r-t-bs-kopernicus-unified-bleeding-edge-branch/

**Comment by kikanaide** [comment]
Thanks!
