### ISSUE TITLE
[Mod]

### ISSUE THREAD

**Issue by TheRaveninGitHub** [KSP-CKAN/NetKAN#8246]
Mod info
--------
* Mod name: KK Launchers Pack
* Author(s): Kartoffelkuchen
* License: https://forum.kerbalspaceprogram.com/index.php?/topic/193933-191-kks-spacex-pack-june-03-2020/
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/193933-191-kks-spacex-pack-june-03-2020/
* Download: https://forum.kerbalspaceprogram.com/index.php?/topic/193933-191-kks-spacex-pack-june-03-2020/

**Comment by HebaruSan** [comment]
This is already indexed as SpaceXLaunchVehicles (see #5533):

- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/SpaceXLaunchVehicles.netkan
- https://spacedock.info/mod/269/SpaceX%20Launch%20Vehicles
