### ISSUE TITLE
[Mod] Part Overhaul Integration

### ISSUE THREAD

**Issue by LouisB3** [KSP-CKAN/NetKAN#8249]
Mod info: 

The Part Overhauls mod was published by Squad during the KSP 1.2 Pre-Release to showcase the new PartUpgrade feature and to preview the planned Rocket Engine Overhaul.

The visual overhaul has since been overtaken by and included in the Restock project. Part Overhaul Balance Integration aims to incorporate the PartUpgrade-based rebalance for 1.25m engines into the stock/Restock+ engines, thereby combining gameplay-optimized stats with the best available visuals.

**Dependencies**

Required, not included:

- ModuleManager

Recommended, not required:

- Restock/Restock+

If Restock+ is not installed, the Valiant and Pug engines will not be available.

--------
* Mod name: Part Overhaul Integration
* Author(s): LouisB3
* License:  Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/182797-181-part-overhaul-balance-integration/
* Download: https://github.com/LouisB3/PartOverhaulIntegration/releases
--------
Please let me know if I can or should do anything to facilitate CKAN indexing.

**Comment by HebaruSan** [comment]
Thanks for contacting us, and please let us know if there are any problems!
