### ISSUE TITLE
[Bug] Error downloading pathfinder

### ISSUE THREAD

**Issue by eceer21** [KSP-CKAN/NetKAN#8253]
Background
----------
* Operating System: Windows 10 
* CKAN Version: 1.29.2
* KSP Version: 1.10.0.2917

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
yes

Problem
-------
**Describe the bug**

> About to install:
> 
>  * Pathfinder v1.36.1 (cached)
>  * Buffalo v2.9.0 (cached)
> Module "Pathfinder" successfully installed
> Oh no! We tried to overwrite a file owned by another mod!
> Please try a `ckan update` and try again.
> 
> If this problem re-occurs, then it may be a packaging bug.
> Please report it at:
> 
> https://github.com/KSP-CKAN/NetKAN/issues/new/choose
> 
> Please include the following information in your report:
> 
> File      : Ships/SPH/Guppy.craft
> Installing Mod : Buffalo v2.9.0
> Owning Mod: Pathfinder
> CKAN Version   : v1.29.2
> Your GameData has been returned to its original state.
> Error during installation!
> If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
> If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
> If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose

**Steps to reproduce**
* Uninstall Pathfinder and Buffalo.
* Choose Pathfinder and Buffalo to reinstall.
* Click on Apply change and Apply
* See error

**Expected behavior**
Successful install

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Thanks for the report. As of b8c7a70a6b4bfee02b5104c5cc900eefcdacaaa1 from #7982, Pathfinder seems to be installing the Ships folder from its bundled copy of Buffalo; it has no Ships folder of its own. No wonder they conflict!

**Comment by eceer21** [comment]
Great. Thanks. Fix works for me.
