### ISSUE TITLE
Tundra exploration mod download error

### ISSUE THREAD

**Issue by pexpress** [KSP-CKAN/NetKAN#8315]
Background
----------
* Operating System: Windows 10
* CKAN Version: v1.29.2
* KSP Version: 1.9.0

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
I have tried to download the tundra exploration mod, it appeared an error. I have tried different versions of the mods and reinstall CKAN but still not working.

**Expected behaviour**
error frame appears

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/77549707/104820871-de0f6900-5872-11eb-84d9-3eaad46db00e.png)

Thx for your help!

**Comment by HebaruSan** [comment]
Looks like there's a `\u00b7` middle dot character in that file name:

![image](https://user-images.githubusercontent.com/1559108/104821152-91d71100-57ff-11eb-91d2-82c6b60d51a2.png)

But that character isn't banned by either Windows or the ZIP format, so the error is a bit mysterious.

Are you able to unpack this mod manually? If it's a problem with the file name as it says, then unzipping it manually on Windows should also produce an error.

**Comment by HebaruSan** [comment]
Worked fine when I tried it on Linux, for what that's worth.

**Comment by DasSkelett** [comment]
Just tried both extracting using Windows Explorer's built-in feature and installing the mod via CKAN on Windows, both worked without problems...

**Comment by HebaruSan** [comment]
This file has been in this mod since its version 1.2.1, released 2018-11-18, so there are no recent changes here...

**Comment by pexpress** [comment]
So what should I do? Manually extract something?

**Comment by HebaruSan** [comment]
@pexpress We can't really advise you because the error you're seeing doesn't happen for us. I notice there appear to be some chinese characters in the screenshot:

![image](https://user-images.githubusercontent.com/1559108/104871219-1dd85e00-5910-11eb-974d-d957ef69df51.png)

Are you in a Chinese locale? Maybe your OS has different rules for valid file name characters?

**Comment by pexpress** [comment]
Yes I come from Hong Kong
That word means *at* or *in*

**Comment by HebaruSan** [comment]
OK, I hope you are safe and well!

It might help our investigation if you downloaded this and tried to unzip the full contents:
-https://spacedock.info/mod/223/Tundra%20Exploration%20-%20Stockalike%20Dragon%20V2%20and%20Falcon%209/download/3.2.1

**Comment by pexpress** [comment]
Sure I will try it later when available
I have tried manually installing but it isn't work anyway

**Comment by pexpress** [comment]
Tried and had done
Thx for everyone's help
