### ISSUE TITLE
Download-Bug RealChute_v1.4.8.1

### ISSUE THREAD

**Issue by Mr-C-Kite** [KSP-CKAN/NetKAN#8325]
Realchute v1.8.4.1 won't download.
(KSP 1.8., I tried to install RO).

**Comment by DasSkelett** [comment]
v1.8.4.1 has been deleted upstream. For KSP 1.8 - 1.10, download v1.4.8 instead, for KSP 1.11, download v1.4.8.2.

Freezing the deleted version in a moment, since it isn't mirrored to archive.org...

**Comment by DasSkelett** [comment]
Okay, if you refresh now, the deleted version should no longer show up and be tried to be installed.

Thanks for the report.
