### ISSUE TITLE
Need to revert WASDEditorCamera to 0.7.0.1

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#8329]
Something is wrong with my build process, the last few releases have been bad, i've deleted all releases after 0.7.0.1

Not sure of the best way to fix this, Can you do it and let me know?

Thanks

LGG

**Comment by HebaruSan** [comment]
Done. Do users who installed those versions need help?

**Comment by linuxgurugamer** [comment]
I hope not, will post in the thread
Thank you
