### ISSUE TITLE
[Mod] Kopernicus Beleeding Edge

### ISSUE THREAD

**Issue by Monniasza** [KSP-CKAN/NetKAN#8360]
Mod info
--------
* Mod name: Kopernicus
* Author(s): [R-T-B](https://github.com/R-T-B)
* License: [LGPL-3.0](https://github.com/R-T-B/Kopernicus/blob/UBE/LICENSE)
* Homepage: https://github.com/R-T-B/Kopernicus
* Download: https://github.com/R-T-B/Kopernicus/releases
--------
This request applies to the bleeding-edge version of Kopernicus. A stable version already exists.

**Comment by DasSkelett** [comment]
You can already install this mod via CKAN by enabling a custom repository in the settings, see the forum thread for instructions.
@R-T-B maintains the metadata personally [here](https://github.com/R-T-B/CKAN-meta-dev-Kopernicus_BE).

I don't think he wants us to add it to the main CKAN repository. This would defeat the purpose of a "Bleeding Edge" / beta release, if we'd offer it to all CKAN users by default. Users might not realize that they are installing an unstable, potentially save breaking mod if they don't see the disclaimers in the forum.

The BE releases are also missing version files, so we wouldn't have a way to get compatibility data automatically, which makes a multi asset mod basically impossible to index.

**Comment by HebaruSan** [comment]
See KSP-CKAN/CKAN-meta#2159, this experimental code is intentionally opt-in.
