### ISSUE TITLE
Stock Waterfall Effects

### ISSUE THREAD

**Issue by KnightofStJohn** [KSP-CKAN/NetKAN#8380]
Mod info
--------
* **Mod name:** Stock Waterfall Effects
* **Author(s):** KnightofStJohn
* **License:** CC BY-NC-SA 4.0
* **Homepage:** https://forum.kerbalspaceprogram.com/index.php?/topic/200334-111x-stock-waterfall-effects-a-waterfall-config-set-for-realistic-rocket-exhaust-plumes-for-the-stock-engines/
* **Download:** https://github.com/KnightofStJohn/StockWaterfallEffects/releases
* **Dependencies:** 
          • ModuleManager: https://forum.kerbalspaceprogram.com/index.php?/topic/50533-18x-110x-module-manager-414-july-7th-2020-locked-inside-edition
          • Waterfall: https://forum.kerbalspaceprogram.com/index.php?/topic/196309-111x-waterfall-a-framework-for-continuous-mesh-driven-engine-effects-feb-25
* **Incompatible mods:**
          • ReStock: https://forum.kerbalspaceprogram.com/index.php?/topic/182679-1111-restock-revamping-ksps-art-ksp-111-jan-31
* **Mod description:** This mod contains a set of template and engine configuration files, that give amazing waterfall effects to the stock engines.
* **Compatible KSP version:** 1.8.1 to 1.11.99

**Comment by HebaruSan** [comment]
@KnightofStJohn, Thanks for the request!
FYI, CKAN does not index pre-releases, so the red oval will have to come off to get this added:

![image](https://user-images.githubusercontent.com/1559108/109395104-39ac2800-78f0-11eb-815f-0861b5b96f37.png)

**Comment by KnightofStJohn** [comment]
Alright. I changed it to a release.

**Comment by HebaruSan** [comment]
> * **Incompatible mods:**
>   • ReStock: https://forum.kerbalspaceprogram.com/index.php?/topic/182679-1111-restock-revamping-ksps-art-ksp-111-jan-31

@KnightofStJohn, we are seeing reports on the CKAN forum thread that this may no longer be incompatible with ReStock. Can you confirm whether that is correct? If so, we can remove the conflict from the CKAN metadata to allow them to be installed together.
