### ISSUE TITLE
File overwrite conflict with WildBlueTools

### ISSUE THREAD

**Issue by tjanke42** [KSP-CKAN/NetKAN#8420]
Background
----------
* Operating System:  Win10
* CKAN Version:  1.30 (also v1.29.2)
* KSP Version:  1.11.1.3066

Only manually installed mod is CactEye2.

Problem
-------
When upgrading 'Classic Stock Resources' from v1.1.4 to v 1.2.0, receive the following error message from ckan:

Oh no! We tried to overwrite a file owned by another mod!  Please try a `ckan update` and try again.

If this problem re-occurs, then it may be a packaging bug.  Please report it at:

https://github.com/KSP-CKAN/NetKAN/issues/new/choose

Please include the following information in your report:

File      : GameData/WildBlueIndustries/000WildBlueTools/Templates/ClassicStock/Production/MM_OSEWorkshop.cfg
Installing Mod : WildBlue-PlayMode-ClassicStock v1.82.1
Owning Mod: WildBlueTools
CKAN Version   : v1.30.0
Your GameData has been returned to its original state.

**Steps to reproduce**
o Check the 'Update' box for Classic Stock Resources
o Click the Apply Changes button
o Click the Apply button

**Expected behavior**
Install the upgrade

**Comment by HebaruSan** [comment]
Yeah, we had to restructure how the Wild Blue Industries mods are installed, so some hiccups are expected as folks upgrade to the new structure, see #8275.

Do you get this error if you try just upgrading WildBlueTools by itself?

**Comment by HebaruSan** [comment]
Would also help to know which version of WildBlueTools you have installed currently. The restructure should have been applied to older versions in KSP-CKAN/CKAN-meta#2224, but maybe you haven't reinstalled yet?

**Comment by tjanke42** [comment]
Thanks for the reply.  My WildBlueTools is currently v1.81.5.  
  
I see now that the latest version is v 1.82.1, but when I click Refresh in ckan, WBT does not show up as Upgradeable, so I was unaware a new version was out.  
  
So, since ckan apparently doesn't (yet) know WBT is upgradeable, does that mean I need to upgrade WBT manually now?  

Thanks for your help!

**Comment by HebaruSan** [comment]
Thanks, that confirms that you haven't reinstalled WildBlueTools to get the restructuring yet. v1.81.5 was [updated to depend on `WildBlue-PlayMode` on Jan 10](https://github.com/KSP-CKAN/CKAN-meta/commit/359e5a7f56c62598fa08d54454e5146524f1e051#diff-62762b664baf099966b7f0250dac205094d4d2d64501d04cd8020dc810b84556) (and [CKAN has known about v1.82.1 since it was released](https://github.com/KSP-CKAN/CKAN-meta/blob/master/WildBlueTools/WildBlueTools-v1.82.1.ckan)), but if it's not upgradeable then there's probably a conflict between the old structure and the new.

> does that mean I need to upgrade WBT manually now?

No, it would be better to find a path that gets you to CKAN installing the latest versions of these mods, but it may take a little more experimentation to determine how to do that. The relationships are pretty complicated.

If you right click WildBlueTools, there should be a reinstall option, which _might_ cause it to prompt you to choose a play mode. Can you try that? If it works, then you should pick the ClassicStock play mode because it's the only one that works with ClassicStockResources.

**Comment by tjanke42** [comment]
Reinstalling WBT just... reinstalls v1.81.5 of WBT.  Nothing else.  No playmode prompt.  
  
However!  When I click ckan's Refresh button, I get a popup with the following message:

--------------
The following mods have had their metadata changed since last update:

- Buffalo v2.9.0
- WildBlueTools v1.81.5
- ExtraPlanetaryLaunchpads 6.8.3.0
- ClassicStockResources v1.1.4

You should reinstall them in order to preserve consistency with the repository.

Do you wish to reinstall now?
--------------

Clicking yes pops up another message, saying:

--------------
Failed to connect to repository. Exception: Too many mods provide Buffalo-PlayMode:
* Buffalo-PlayMode-CRP v2.10.2
* Buffalo-PlayMode-ClassicStock v2.10.2
* WildBlue-PlayMode-Pristine v1.82.1
* WildBlue-PlayMode-Simplified v1.82.1
* WildBlue-PlayMode-USI v1.0.0.2
--------------

Given the above, any suggestions for what to do next?  Thanks in advance!

**Comment by tjanke42** [comment]
Based on that new bug report, looks like there is not going to be a quick or easy fix.  That's ok.  I can live with things as they are for now.  
  
HebaruSan, thanks for your replies and for digging into the root cause of that error message.  I appreciate your dedication and diligence.  
  
I'd prefer to keep this thread open until the issue is fully resolved and I can upgrade, but if you must close it I understand.  Thanks for all your help!

**Comment by HebaruSan** [comment]
@tjanke42, thanks for helping us drill down to some things that we can investigate further.

Are you able to try simply upgrading the WBT mods?

If not, there are two options remaining that I can think of at this point:

1. Try right-clicking to reinstall again now that you have the latest metadata (the two different methods of reinstallation follow different code paths, and right clicking from the mod list should avoid the problem described in KSP-CKAN/CKAN#3335); OR
2. Uninstall the WildBlueTools mods and install them again normally

**Comment by tjanke42** [comment]
Reinstalling simply reinstalled the cached defective versions.  I uninstalled and re-installed, that worked.  Everything appears to be up to date with no error messages.  Thanks!
