### ISSUE TITLE
[Mod] Bluedog Design Bureau metadata update request

### ISSUE THREAD

**Issue by zorg2044** [KSP-CKAN/NetKAN#8432]
Hi,

I would like to request some updates to our metadata. If possible we would like it to apply to the next release, v1.7.2 which we plan to release as soon as these metadata updates are live. https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/BluedogDB.netkan

1) Add Waterfall to Depends https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/Waterfall.netkan

2) Move RealPlume from Supports to Suggests

3) Add Neptune Camera to Suggests https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/NeptuneCamera.netkan

4) Add Space Dust to supports https://raw.githubusercontent.com/post-kerbin-mining-corporation/SpaceDust/master/CKAN/SpaceDust.netkan

Thanks a lot

**Comment by zorg2044** [comment]
Actually it might be easier if we have the metadata under our own management on our repository. Could you please advise how to go about doing this? Thanks.

**Comment by DasSkelett** [comment]
> Actually it might be easier if we have the metadata under our own management on our repository. Could you please advise how to go about doing this? Thanks.

You need to copy the netkan files into a repository of yours, then the kref of the netkan file in this repo needs to be changed to point to that metanetkan.
* [RealismOverhaul](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/RealismOverhaul.netkan) for example

But be advised that in our repository there is a lot of validation going on before a change gets merged. Without that validation there's a higher chance to introduce syntax or logical errors. Especially syntax errors can prevent new mod updates from being indexed.
You should definitely monitor http://status.ksp-ckan.space/ in this case, which shows all current warnings and errors for all the active netkans.
I'd also encourage you to try out this GitHub Action to validate netkan files: https://github.com/KSP-CKAN/xKAN-meta_testing. This is [what we use](https://github.com/KSP-CKAN/NetKAN/blob/master/.github/workflows/inflate.yml) to validate changes in our repositories.

**Comment by zorg2044** [comment]
@DasSkelett Thanks a lot for the advice, I'll discuss these points with my co-authors for future consideration. Thus in the meantime would appreciate if you could proceed as initially intended in the first post. We'll keep the netkan here for the moment.

Cheers!
