### ISSUE TITLE
PlaneMode metadata not showing compatiblity with KSP 1.11

### ISSUE THREAD

**Issue by Hyperspeed1313** [KSP-CKAN/NetKAN#8466]
Mod PlaneMode 1.4.5 still lists a maximum version compatibility of 1.10.1 and hasn't been updated in some time. From my testing, the mod appears to be completely functional in KSP 1.11.2.3077 (Tested on Windows 10 20H2 19042.867). This issue is a request to update PlaneMode's compatibility metadata to include 1.11 builds.

**Comment by HebaruSan** [comment]
Explicit expressions of author intentions generally take precedence over random users' claims of testing.

![image](https://user-images.githubusercontent.com/1559108/114283182-f63cf180-9a37-11eb-870d-6c51112590c8.png)

This mod's compatibility is set in its author-owned metanetkan. You could try submitting a pull request there:

- https://github.com/Apokee/PlaneMode/blob/master/PlaneMode.netkan

Users wishing to install a mod that's only compatible up to KSP 1.10 on KSP 1.11 already have a feature allowing them to do that:

https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions
