### ISSUE TITLE
Bad links on UniversalStorage2's SpaceDock page

### ISSUE THREAD

**Issue by Lunesombre** [KSP-CKAN/NetKAN#8473]
Broken link to a mod mainpage, possible phishing
----------
* Operating System: Win 8.1
* CKAN Version: v1.30.0
* KSP Version: many. Problem appeared on a 1.10.1 version but shouldn't be linked with KSP version.

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Yes, added the recompiled RSSVE for 1.9+, but it shouldn't be related.

Problem
-------
Mod : **Universal Storage II** (by Paul_Kingtiger, DMagic, Daishi)
**The link to the main page (http://www.kingtiger.online//uvsii/) sent me to a phishing page - an obviously fake "windows defender" alert.** Multiple tests sent me to multiple different webpages, mostly commercials.

The link to spacedock works as intended though.

I haven't tried the mod on 1.10.1 (mainly because it hasn't been updated).

**Steps to reproduce**
* Go to CKAN indexed mod Universal Storage II
* Click on the main page link
* See where it sends you

**Expected behavior**

**Screenshots (if applicable)**

https://drive.google.com/file/d/1V56DMi6j81bQul4hbdz6y4qCTFUeMzbm/view?usp=sharing

**CKAN error code (if applicable):**
None
```
PLACE CODE HERE !
```

**Comment by DasSkelett** [comment]
Thanks for the report.
Looks like that one was a personal domain by one of the authors, KingTiger, which expired.
The links are coming directly from SpaceDock:
![image](https://user-images.githubusercontent.com/28812678/114534159-f95dfa80-9c4e-11eb-8ca5-9159f64aed67.png)

It has also already been reported on the forum thread, but the author hasn't been online in almost a year, so it's unlikely they'll come back (soon) and renew the domain.

I've changed the links to point to the forum thread + their OneDrive source code archive which will also propagate to CKAN for the latest release, but we should probably also replace all the links in older metadata.
