### ISSUE TITLE
Outdated Metadata: USI Tools

### ISSUE THREAD

**Issue by InterplanetaryEngineer** [KSP-CKAN/NetKAN#8585]
Background
----------
* Operating System: Win10
* CKAN Version: 1.30.4
* KSP Version: 1.7.2.2556

No manual changes to the GameData folder

Problem
-------
The installation of USI Tools gets stuck trying to fetch https://github.com/UmbraSpaceIndustries/UmbraSpaceIndustries/releases/download/1.2.0.0/USITools_1.2.0.0.zip, which does not exist.

**Steps to reproduce**
* Have KSP 1.7.2
* Try to install USI Tools

**Expecded behavior**
Mod is installed.

**Comment by DasSkelett** [comment]
Ugh. @BobPalmer has renamed the repository (`UmbraSpaceIndustries/UmbraSpaceIndustries`->[UmbraSpaceIndustries/USITools](https://github.com/UmbraSpaceIndustries/USITools)) (see [this CKAN-meta commit](https://github.com/KSP-CKAN/CKAN-meta/commit/3c63a72469e88c8772c6dab1217be03a1806e5cc)), but also moved `BobPalmer/Constellation` to [UmbraSpaceIndustries/UmbraSpaceIndustries](https://github.com/UmbraSpaceIndustries/UmbraSpaceIndustries), so GitHub's automatic redirects no longer work. Now we're stuck with [tons of outdated metadata](https://github.com/KSP-CKAN/CKAN-meta/tree/master/USITools) that lead to a 404 and need their download links updated.

**Comment by DasSkelett** [comment]
```bash
for C in *.ckan; do jq --indent 4 'if ( .download and (.download | contains("github.com/UmbraSpaceIndustries/UmbraSpaceIndustries"))) then (.download |= sub("github\\.com/UmbraSpaceIndustries/UmbraSpaceIndustries"; "github.com/UmbraSpaceIndustries/USITools")) else . end' $C | sponge $C; done

for C in *.ckan; do jq --indent 4 'if ( .resources.repository and (.resources.repository | contains("github.com/UmbraSpaceIndustries/UmbraSpaceIndustries"))) then (.resources.repository |= sub("github\\.com/UmbraSpaceIndustries/UmbraSpaceIndustries"; "github.com/UmbraSpaceIndustries/USITools")) else . end' $C | sponge $C; done

for C in *.ckan; do jq --indent 4 'if ( .resources.bugtracker and (.resources.bugtracker | contains("github.com/UmbraSpaceIndustries/UmbraSpaceIndustries"))) then (.resources.bugtracker |= sub("github\\.com/UmbraSpaceIndustries/UmbraSpaceIndustries"; "github.com/UmbraSpaceIndustries/USITools")) else . end' $C | sponge $C; done
```

**Comment by DasSkelett** [comment]
Thanks you very much for the report @InterplanetaryEngineer!

The download links are updated now, if you wait 5 minutes then hit "Refresh" in CKAN, you should get the updated metadata and the installation should succeed.

**Comment by InterplanetaryEngineer** [comment]
Wow, that was quick! Thank you!

**Comment by DasSkelett** [comment]
Can't leave our users hanging with download errors :grin:
