### ISSUE TITLE
TweakScale v2.4.5.1 reuploaded, metadata mismatch 

### ISSUE THREAD

**Issue by jtdutta1** [KSP-CKAN/NetKAN#8598]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.30.4
* KSP Version: 1.12.0.3140

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
```
CKAN.InvalidModuleFileKraken: TweakScale v2.4.5.1: C:\Users\jtdut\AppData\Local\Temp\tmpB35E.tmp has length 256221, should be 288147
   at CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error)
```

**Steps to reproduce**
* Check Tweak Scale.
* Click on Apply Changes.
* After it downloads, when it starts to install, the given error pops up. 

Should install without any error.

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/21063647/123546966-76900a80-d77c-11eb-942e-22b1b4659a93.png)

**Comment by DasSkelett** [comment]
Looks like a reupload, `"release_date": "2021-06-27T13:11:02.084553+00:00"`
https://github.com/KSP-CKAN/CKAN-meta/blob/41620ba1e4542963391f4b4ab3a2d242cd0c973e/TweakScale/TweakScale-v2.4.5.1.ckan#L57
vs `"created": "2021-06-27T13:29:56.901567+00:00"`
https://spacedock.info/api/mod/127

The bot should pick it up in a few minutes.

**Comment by DasSkelett** [comment]
Welp, that reupload was more than a simple typo fix. The layout of the zip has changed, the `Extras` folder is gone, and the contents of the `GameData` directory are now at the root of the zip.
![image](https://user-images.githubusercontent.com/28812678/123548357-c662d780-d764-11eb-909f-45136db583e2.png)

**Comment by DasSkelett** [comment]
[Metadata update arrived](https://github.com/KSP-CKAN/CKAN-meta/commit/5ccb12797542c2b2a551b052263d960884bdc46b)

If you refresh CKAN's repository in a few minutes, you should be able to install it without problems.

**Comment by DasSkelett** [comment]
Various people are still reporting download errors, but with yet another file size:
`288150` now vs. `256221` that our bot received vs. `288147` from the initial upload.

However, the `created` property on SpaceDock has not  been updated, it still says `"2021-06-27T13:29:56.901567+00:00"`
https://spacedock.info/api/mod/127/16439

My theory: Lisias reupload twice, once shortly before our bot inflated from #8599, and our bot got the updated `created` date, but an outdated (yet still updated from the first time) zip, probably from ATS' cache.

(╯°□°)╯︵ ┻━┻

**Comment by DasSkelett** [comment]
Oh and guess what, the zip layout changed again.
![image](https://user-images.githubusercontent.com/28812678/123554315-ae4c8180-d77f-11eb-9eee-fcf60308ba2a.png)

**Comment by DasSkelett** [comment]
My plan worked! Metadata is updated once again, with the data from the 288150 bytes zip.

@raziel420, if you refresh the repository in CKAN in a few minutes, you should be able to install it successfully.

**Comment by jtdutta1** [comment]
Yup installed without any problem. Thanks.
