### ISSUE TITLE
How to fix the Kerbalism RO Config versioning?

### ISSUE THREAD

**Issue by NathanKell** [KSP-CKAN/NetKAN#8602]
The existing netkan is pointing at Kerbalism's version, not ROKerbalism's. That's, uh, bad, right? We could fix the netkan and include our own version file but it might get counted as lower than Kerbalism's own version, no?

cc @Standecco

**Comment by DasSkelett** [comment]
> We could fix the netkan and include our own version file but it might get counted as lower than Kerbalism's own version, no?

Not sure what you mean with "getting counted" lower. We can adjust the netkan to point to a specfic version file, if you change the zip to include Kerbalism core again. But right now there's no version file at all in the zip.

With the `Kerbalism` directory gone from the zip, we definitely need to change something to get the new version indexed.
Yeah, depending on how KSP version specific each config release is, we could either set `ksp_version: any` and rely on Kerbalism core and the rest of RO to dictate the compatibility, or you include your own version file, or, worst case, we hardcode the compatibility in the netkan.

**Comment by NathanKell** [comment]
Should be fine to leave it as any since this won't be installed standalone (or if it is installed standalone, it won't do anything). We're talking internally about splitting it up into RO and RP-1 anyway so will probably just leave things as-is for now, it was more that I was worried it would get indexed as v3.14 or something (the Kerbalism version) rather than 1.1. But if it's drawing main-versioning from the tag and only KSP versioning from the .version that's fine. Cheers!

**Comment by DasSkelett** [comment]
>  But if it's drawing main-versioning from the tag and only KSP versioning from the .version that's fine.

Exactly. Version files are too unreliable to get release tags from. They are usually not kept up to date properly. We always take the release tag as mod version.

> Should be fine to leave it as any since this won't be installed standalone (or if it is installed standalone, it won't do anything).

Sounds good. Just gonna remove the vref from the netkan the, for the sake of cleanliness, and to remove the warning.
