### ISSUE TITLE
Might have to clear cache on RP-1

### ISSUE THREAD

**Issue by NathanKell** [KSP-CKAN/NetKAN#8603]
Sorry, I uploaded a bad zip for the v1.9 release (it had a bare RP-0 folder instead of GameData/RP-0). I removed it and uploaded a zip of a different name with the proper structure in the hope that will make NetKAN index it, but might have to force it to since it's the same tag. Sorry!

**Comment by DasSkelett** [comment]
Our bot detects reuploaded zips based on the `updated_at` tag from the API.
However in this case, it shouldn't be in the cache at all, since the inflation of the latest release fails:
> Too many .version files located: RP-0/RP-0.version, RP-0/RP-1.version

This is still the case in the reupload, there's a stray `RP-0.version` with really outdated data in it:
```json
{
   "VERSION" : {
      "PATCH" : 0,
      "BUILD" : "260",
      "MAJOR" : "0",
      "MINOR" : "51"
   },
   "GITHUB" : {
      "REPOSITORY" : "RP-0",
      "USERNAME" : "KSP-RO",
      "ALLOW_PRE_RELEASE" : false
   },
   "NAME" : "Realistic Progression Zero",
   "KSP_VERSION" : {
      "MINOR" : "1",
      "MAJOR" : "1",
      "PATCH" : "3"
   },
   "DOWNLOAD" : "https://github.com/KSP-RO/RP-0/releases",
   "URL" : "https://raw.githubusercontent.com/KSP-RO/RP-0/master/GameData/RP-0/RP-0.version"
}

```

**Comment by NathanKell** [comment]
Huh. Looks like I had a local file that was .gitignored and I mistakenly zipped it. Thank you! Reuploaded.

Back in Ancient Times the bot didn't use to be that smart, IIRC, hence my question. But then, back then they were travis jobs I think?

**Comment by DasSkelett** [comment]
> Back in Ancient Times the bot didn't use to be that smart, IIRC, hence my question. 

Indeed, removing stale zips for reuploads has been added in https://github.com/KSP-CKAN/CKAN/pull/2337 for GitHub and https://github.com/KSP-CKAN/CKAN/pull/2859 for SpaceDock, and https://github.com/KSP-CKAN/CKAN/pull/2526 made the bot prune zips of failed inflations, which happened in this case.

> Huh. Looks like I had a local file that was .gitignored and I mistakenly zipped it. Thank you! Reuploaded.

Looks good, thanks for fixing it: https://github.com/KSP-CKAN/CKAN-meta/commit/0f581d6282306d1f1ca832cb524aae76dda47b9e
