### ISSUE TITLE
RealPlume and RealPlume Stock Config Dependency Issue

### ISSUE THREAD

**Issue by Retr0r0cket** [KSP-CKAN/NetKAN#8618]
Background
----------
* Operating System: Windows 10 Version 20H2
* CKAN Version: 1.30.4
* KSP Version: 1.12.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Yes

Problem
-------
**Describe the bug**
RealPlume says RealPlume Stock Configs are a dependency which isn't up to date so you can't download either and the same happens in reverse (i.e. try to download Stock Configs, says RealPlume is out of date). This is despite both being listed to support any version of 1.12

**Steps to reproduce**
Click on box to install either RealPlume or RealPlume stock configs

**Expected behavior**
Will say, "RealPlume 2:v13.3.2 depends on RealPlumeConfigs, which is not compatible with the currently installed game version" or, " RealPlumeConfigs depends on RealPlume 2:v13.3.2, which is not compatible with the currently installed game version."

**Comment by HebaruSan** [comment]
Both depend on ModuleManager, which @sarbian hasn't confirmed as compatible with 1.12 yet. Try marking 1.11 as compatible.

https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions

**Comment by DasSkelett** [comment]
@sarbian is the latest ModuleManager release okay to be marked as compatible with KSP 1.12?
We got a bunch of 1.12 mods depending on ModuleManager already, would be nice to have them all show up on KSP 1.12 installations.

**Comment by sarbian** [comment]
It is but I am unable to do the change for a few more days. Feel free to do it,

**Comment by Retr0r0cket** [comment]
Apologies for the mistake I made by opening a new issue.

**Comment by DasSkelett** [comment]
Looking at the dependency tree, there's still SmokeScreen which has yet to be updated/marked as compatible with KSP 1.12 (or even KSP 1.11).
![image](https://user-images.githubusercontent.com/28812678/124522007-e42ddd80-ddf1-11eb-8b88-800439d3d110.png)

As it happens, this one is also maintained by @sarbian. @sarbian, there's a [comment](https://forum.kerbalspaceprogram.com/index.php?/topic/64987-18x-110x-smokescreen-2814-extended-fx-plugin-18-april-2020/&do=findComment&comment=3986353) from you saying it should still work fine with the newest version, which was KSP 1.11 at the time the comment was written.
Can we update the metadata for SmokeScreen as well, to set max compatibility to KSP 1.11? Maybe even to 1.12?

@Retr0r0cket, you might want to allow CKAN to install older mods by [setting compatible game versions](https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions). Many people select 1.8 and above as of now, which is okay for most mods, with a few exceptions.
