### ISSUE TITLE
Interstellar, 0.90 and TreeLoader

### ISSUE THREAD

**Issue by tsal** [KSP-CKAN/NetKAN#862]
From the previous issue that was closed:

"Interstellar has been taken up by a new modder to keep it functional on new versions; it can be found at http://forum.kerbalspaceprogram.com/threads/104943-0-90-KSP-Interstellar-port-maintance-thread . I don't know any details on what would be needed (CKAN is the third mod manager for KSP I'm trying out, and I'm not entirely sure how ti works yet) but this might let you get a functional 0.90 version listed on there?"

In addition, this IS showing up for 0.90 installations and IS causing problems.  Please take a look and either remove KSP Interstellar entirely from the tree (there's a replacement that provides a slightly older version) OR please update it - it does NOT use TreeLoader anymore:

https://github.com/FractalUK/KSPInterstellar/wiki/Illustrated-Guide-Chapter-0:-Installing-and-Patching

**Comment by Dazpoet** [comment]
I assume the previous topic you refer to is https://github.com/KSP-CKAN/CKAN-meta/issues/318 ?
Is this also a thing for KSPInterstellar lite or is that a totally different fork of the mod?

**Comment by Dazpoet** [comment]
Problem should now be resolved as the PR has been merged.
