### ISSUE TITLE
Ship Manifest is not updating

### ISSUE THREAD

**Issue by mwerle** [KSP-CKAN/NetKAN#863]
https://kerbalstuff.com/mod/261/Ship%20Manifest

Has been updated to v4.1.4.0 and (current) v4.1.4.1.
CKAN is still showing v4.1.3.1 as current.

**Comment by Dazpoet** [comment]
According to CKAN-meta the data was updated about an hour ago and should now be correct. My client now correctly reports 4.1.4.1 as the latest version.

**Comment by mwerle** [comment]
Ditto; closing this. Thanks for kicking it!
