### ISSUE TITLE
[Mod Suggest] BDArmory Multiplayer 

### ISSUE THREAD

**Issue by help-programming-is-hard** [KSP-CKAN/NetKAN#8634]
Mod info
--------
* Mod name: BDA Multiplayer
* Author(s): @Papa_Joe, @jrodriguez, @SpannerMonkey(smce), @gomker, @TheDog, @DoctorDavinci, @Eidahlil, @TheKurgan
* License: CC-BY-SA 2.0
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/184167-191-bdarmory-continued-v134-bdarmory-multiplayer-09042020/ 
* Download: https://github.com/jrodrigv/BDAMultiplayer/releases

**Comment by HebaruSan** [comment]
HI @jrodrigv, may I ask whether you are planning a full release for BDAMultiplayer? We've had a request to add it to CKAN, but it looks like it isn't quite ready yet. If this repo was just a now-concluded experiment, we can close this request. Thanks!

**Comment by HebaruSan** [comment]
It doesn't look like this is going to happen. If anybody notices a non-prerelease for this mod, please let us know and we can re-open this.

**Comment by jrodrigv** [comment]
Hi @HebaruSan Sorry I think I missed this. I'm fine with adding BDAMultiplayer to CKAN. I have done a "probably" latest release for KSP 1.12.5 and latest LunaMultiplayer 0.29
