### ISSUE TITLE
Can't install Scatterer

### ISSUE THREAD

**Issue by ChainofChaos** [KSP-CKAN/NetKAN#8637]
Background
----------
* Operating System:  Windows 10
* CKAN Version: v1.30.4
* KSP Version: 1.12.1.3142

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
Scatterer can't be installed to KSP it says there is a conflict but I don't think it's a conflict since I can manually install the scatterer mod to the game folder and it works fine. But I need the scatterer from CKAN because I need the dependency for another mod. Without it, I can't install another mod.

**Steps to reproduce**
* Download scatterer contents
* See error

**Expected behavior**
Scatterer can be installed without any conflict

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/17515882/125204118-cb1ba580-e2a5-11eb-8771-45bfb94a2f33.png)

**Comment by HebaruSan** [comment]
> it says there is a conflict but I don't think it's a conflict

No, that's not why it's not installable. The exclamation point here is trying to alert you to the actual cause:

![image](https://user-images.githubusercontent.com/1559108/125204358-7b57c280-e242-11eb-9456-dfacec9e17c2.png)

**Comment by ChainofChaos** [comment]
> > it says there is a conflict but I don't think it's a conflict
> 
> No, that's not why it's not installable. The exclamation point here is trying to alert you to the actual cause:
> 
> ![image](https://user-images.githubusercontent.com/1559108/125204358-7b57c280-e242-11eb-9456-dfacec9e17c2.png)

**Comment by ChainofChaos** [comment]
> > > it says there is a conflict but I don't think it's a conflict
> > 
> > 
> > No, that's not why it's not installable. The exclamation point here is trying to alert you to the actual cause:
> > ![image](https://user-images.githubusercontent.com/1559108/125204358-7b57c280-e242-11eb-9456-dfacec9e17c2.png)

Hi, I just aware that this is a game version issue but I have tried to install it manually and it works fine with my latest KSP. Meanwhile I can't install it from CKAN

**Comment by HebaruSan** [comment]
Yes, that's because you have KSP 1.12.1, and the author has only marked this as compatible up to 1.12.0 on SpaceDock:

https://spacedock.info/mod/141/scatterer

Hopefully the author will update that, but in the meantime you can tell CKAN to consider all of KSP 1.12 as compatible:

https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions

**Comment by ChainofChaos** [comment]
> Yes, that's because you have KSP 1.12.1, and the author has only marked this as compatible up to 1.12.0 on SpaceDock:
> 
> https://spacedock.info/mod/141/scatterer
> 
> Hopefully the author will update that, but in the meantime you can tell CKAN to consider all of KSP 1.12 as compatible:
> 
> https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions

Ok. Thanks for the support.
