### ISSUE TITLE
extraneous author listed for SimpleConstruction

### ISSUE THREAD

**Issue by zer0Kerbal** [KSP-CKAN/NetKAN#8650]
should only be MatterBeam, RealGecko, EricWi, and zer0kerbal.

thank you for your understanding!

**Comment by DasSkelett** [comment]
The list comes from the SpaceDock entry, if there's a chance you could get the SpaceDock page to show the list as it should be, that would be preferred, however we can also overwrite it if you want.

Just to confirm, it currently says `"matterbeam", "zer0Kerbal", "linuxgurugamer"`, you want us to remove linuxgurugamer and add RealGecko and EricWi?

**Comment by HebaruSan** [comment]
https://spacedock.info/mod/59/SimpleConstruction

![image](https://user-images.githubusercontent.com/1559108/125962595-32681887-4f22-4ae6-8346-d3d0e47851d7.png)

I think you can...

1. Click "Edit this Mod"
2. Click the "X" in the "Additional Authors" list to remove
3. Type a username and click Add to add

**Comment by DasSkelett** [comment]
This functionality is limited to the original author, AFAIK.
https://github.com/KSP-SpaceDock/SpaceDock/blob/ebb54cb85da0ea798cdbc3578e52b56fd04ee0c2/templates/edit_mod.html#L144

So @zer0Kerbal would need to reach out to MatterBeam to do that.

**Comment by HebaruSan** [comment]
> So @zer0Kerbal would need to reach out to MatterBeam to do that.

... or an admin, apparently. @zer0Kerbal, @DasSkelett and I are both SpaceDock admins, so we could edit that list. Can you help convince us that it's the right thing to do? Why is @linuxgurugamer being cut out?

**Comment by zer0Kerbal** [comment]
It is one of those unfortunate side effects of going off-grid for 2020. 

Toward the end of this extended vacation - LGG started the process of adopting some of my mods. This is one. It is also the first one I updated once I got back.

LGG hadn't done anything, but @MatterBeam must have been contacted and must have given access, since one or more others have been removed as authors IIRC.

Thank you for understanding!

Just would be nice to gain access to other listings that have been given permission to adopt, but authors can't remember password or similar. Kaboom is one of those.

**Comment by HebaruSan** [comment]
Welcome back!

> but @matterbeam must have been contacted and must have given access

Close, I removed LGG myself and invited RealGecko; he'll have to log in to SD and accept to show up on the page. I could not find an account for Ericwi. If he makes one, we can arrange to send him an invite.

**Comment by zer0Kerbal** [comment]
it  is good to be back, and with it a new-to-me PC that the bios isn't partially fried making the f,d,s,e,r,g keys operable again! Just taking time to migrate and update to new stuff...

Thank you.

**Comment by HebaruSan** [comment]
Looks like RealGecko accepted the invite:

https://github.com/KSP-CKAN/CKAN-meta/commit/f4667976c7d0ef4f55bfd5f78c1e34097c3ef32d#diff-e68784b742a5a37ea807cf31fb7f6d62357d446c1416f82ec53036e00111a03a

Please let us know if you hear from Ericwi.

**Comment by zer0Kerbal** [comment]
shall do
