### ISSUE TITLE
would like to specify download from curseforge

### ISSUE THREAD

**Issue by zer0Kerbal** [KSP-CKAN/NetKAN#8651]
for SimpleConstruction!

(https://www.curseforge.com/kerbal/ksp-mods/sc/files/3334872)

how would I do that? in the .version file? and/or in the NetKAN file?

**Comment by DasSkelett** [comment]
Curse is no longer available as source on CKAN, see [this discussion](https://github.com/KSP-CKAN/NetKAN/issues/7446). They are blocking CKAN from accessing Curse, and this is unlikely to ever change again.

Theoretically it would however be the netkan file that needs to be updated, specifically the [$kref line](https://github.com/KSP-CKAN/NetKAN/blob/113cef429e8f21bf6e7f0909c2c31b59d16d67b9/NetKAN/SimpleConstruction.netkan#L6). [Here's the spec]( https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#kref) explaining how it's set up.
Just if you're interested.

**Comment by DasSkelett** [comment]
Is there something wrong with SpaceDock, something we could help with?

**Comment by zer0Kerbal** [comment]
@DasSkelett no, I personally use SpaceDock and appreciate it!

I just use CurseForge as the initial -early release- so to test releases before fully letting them into the wild.  This has been working very well, and prevents undo work load on both CKAN and SpaceDock. Helps to catch issues - and even though more work for me, has been worth it.

**Comment by DasSkelett** [comment]
Glad to hear.
In this case CKAN users will have to wait for the stable/full release, sorry. We would love to bring back support for CurseForge, but it's simply not possible – they've blocked our NetKAN bot and the CKAN client. They don't _want_ us to have mods on their site indexed.
You could reach out to them, and let them know that there's demand. All we need is a working API, without our bot, CI, or clients being blocked.

Closing this issue as answered, but feel free to ask further questions if you have any.
