### ISSUE TITLE
Retire mods

### ISSUE THREAD

**Issue by ChrisAdderley** [KSP-CKAN/NetKAN#8654]
I'd like to retire two mods from CKAN and am not sure what the procedure is. They are:
- KerbalAtomics-NFECompatibility
- StationPartsExpansionRedux-Metal

**Comment by HebaruSan** [comment]
Asking here is a good way to start. :+1: 

Do you want these to be completely unavailable for install by CKAN (i.e., including all old historical versions), or just no longer checked for new releases?

**Comment by ChrisAdderley** [comment]
The latter is probably best, but I will not be distributing the files supporting these in archives going forward. As long as CKAN understands this and gets appropriate legacy archives that's probably fine.

**Comment by HebaruSan** [comment]
OK, in that case the changes in #8655 should suffice; these mods will no longer be checked by the bot as of when that was merged, but metadata for the historical versions will be retained.

**Comment by HebaruSan** [comment]
I think this is resolved now. If anything else comes up, please don't hesitate to let us know.
