### ISSUE TITLE
[Bug] Kerbal Konstructs and Custom Pre Launch Checks repository links

### ISSUE THREAD

**Issue by 4x4cheesecake** [KSP-CKAN/NetKAN#8698]
Background
----------
* Operating System: Win 10
* CKAN Version: 1.30.4
* KSP Version: 1.8.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
/

Problem
-------
Applies to "Kerbal-Konstructs" and "Custom Pre Launch Checks":
The CKAN client shows links to the github repositories of "GER-Space" (https://github.com/GER-Space/*), but the files are actually received from the "KSP-RO" repositories (https://github.com/KSP-RO/*). This leads to some confusing since the fork available from KSP-RO got a version bump so CKAN reports an available update but the linked github version of GER-Space doesn't contain any changes.

**Comment by 4x4cheesecake** [comment]
I just realized that Kerbal Konstructs (which includes Custom Pre Launch Checks) is now maintained by the KSP-RO team and actually got his own forum thread: https://forum.kerbalspaceprogram.com/index.php?/topic/204210-ksp-18-kerbal-konstructs-continued/

Maybe it should get his own, separate entry in CKAN?

**Comment by DasSkelett** [comment]
The CKAN-meta files are correct, they link to the new repositories and forum thread:
- https://github.com/KSP-CKAN/CKAN-meta/blob/master/KerbalKonstructs/KerbalKonstructs-v1.8.2.1.ckan
- https://github.com/KSP-CKAN/CKAN-meta/blob/master/CustomPreLaunchChecks/CustomPreLaunchChecks-1.8.1.1.ckan

Also see the discussion of https://github.com/KSP-CKAN/NetKAN/pull/8666.

And the client shows the correct URLs:
![image](https://user-images.githubusercontent.com/28812678/128496131-cd24097f-3669-4f21-b9e8-86000dc254cc.png)

If it shows outdated information for you, refresh the repositories.

**Comment by 4x4cheesecake** [comment]
Indeed, I get the correct links now.... sorry for the confusion.
