### ISSUE TITLE
[Mod] GemstoneLV - Stockalike JAXA / NASDA

### ISSUE THREAD

**Issue by Tantares** [KSP-CKAN/NetKAN#8709]
Mod info
--------
* Mod name: GemstoneLV - Stockalike JAXA / NASDA
* Author(s): Beale
* License: MIT
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/204309-112x-gemstonelv-stockalike-jaxa-nasda-10/
* Download: https://github.com/Tantares/GemstoneLV/releases

Apologies for confusion, is it possible to specify with NetKan that it requires the following?
- B9 Part Switch
- Community Resource Pack
- Simple Adjustable Fairings

**Comment by HebaruSan** [comment]
Thanks for the submission, it should be there now:

![image](https://user-images.githubusercontent.com/1559108/128940766-b6c63b93-02bc-4857-9675-95e6f99ba2cb.png)
