### ISSUE TITLE
Panocean mod has wierd conflicts

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#8727]
![ckan_2021-08-25_11-33-58](https://user-images.githubusercontent.com/1630166/130821422-911d5b7f-1a33-4320-8e58-20745208ab01.png)

Trying to install on a KSP 1.12.2, I do NOT have KerbinSide installed at all, pretty much a clean install.  See th eimage for what's happening
The following is what's installed:
![ckan_2021-08-25_11-41-22](https://user-images.githubusercontent.com/1630166/130821699-ed7b1b4c-4872-4472-b077-ef14503e1ced.png)

**Comment by linuxgurugamer** [comment]
FYI, I did do a refresh before doing this

**Comment by HebaruSan** [comment]
Sorry, what is the part that you think is wrong?

**Comment by HebaruSan** [comment]
KerbinSideCore only goes up to KSP 1.5.1, and PanoceanCanal depends on it, so it won't show up as installable unless you have a very broad version compatibility set up. Looks like this is working correctly.

**Comment by linuxgurugamer** [comment]
Ok, I didn't realize that.
Thanks
