### ISSUE TITLE
Unspecified difficulty in uninstalling a mod

### ISSUE THREAD

**Issue by Ronin0505** [KSP-CKAN/NetKAN#8758]
I cant seem to uninstall a mod called SNACKS on Ckan i have even tried to delete manually but i didnt seem to work anybody can help?

**Comment by HebaruSan** [comment]
Hi @Ronin0505, we'll need more information about what you're doing and what's happening to help. Please start with filling in the issue template:

https://github.com/KSP-CKAN/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by HebaruSan** [comment]
@Ronin0505, if you're able to provide a more complete description of the problem you're having, please do so and we can re-open this.
