### ISSUE TITLE
netkan.exe on release page is old

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#880]
The release page isn't showing the latest netkan.exe, which will be a problem for someone who tries to validate their netkan file against kerbalstuff.com

**Comment by Dazpoet** [comment]
Newest netkan is always available from CKAN-nightly although I agree this could be made clearer,

**Comment by obivandamme** [comment]
I was on stuck on this today, since I tried to create my first netkan file. Only by looking at each release I found an older one where netkan.exe was available. It would be really helptful, especially for new modders to fix this.

**Comment by Dazpoet** [comment]
I've now updated https://github.com/KSP-CKAN/CKAN-support/wiki/Adding-a-mod-to-the-CKAN#before-you-start to reflect the place to get the newest netkan.exe.

I assume all people who wants to add mods will at some point end up at that page and will now have an easier time locating the utilities they need.
