### ISSUE TITLE
[Bug] Incorrect dependency of Probes Before Crew mod.

### ISSUE THREAD

**Issue by Shaggy90** [KSP-CKAN/NetKAN#8807]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.30.4
* KSP Version: 1.12.2

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Nope.

Problem
-------
Probes Before Crew has a dependency on old "Celestial Body Science Editor" mod, which wasn't updated for 2 years. This dependency is not listed in install instructions of the mod. It's simply not a dependency. I don't know if the fix is on your side or on the mod devs side, but it's a bug. When I'm trying to install it anyway, it shows an error about the mod being dependant on another mod and my Changeset tab disappears.

**Comment by HebaruSan** [comment]
Confirmed that it's (still) a bundled dependency:

![image](https://user-images.githubusercontent.com/1559108/136674843-90e5c711-aed4-41a3-b6b8-2e6ea1ab03e7.png)

And the Readme.txt in the download mentions it:

```
================================= (3) Science Definitions =================================

This is just a quick note for users who wish to alter the Science Definitions made by this mod.
If you prefer to see the science reward values of vanilla or a different mod,

First find the
	= = Zs_Science.cfg
file contained within 
	= = GameData/ProbesBeforeCrew/_Core
and delete/remove the file.
You could also rename the EXTENSION to disable the file, for example
	= = Zs_Science.txt

The |ScienceParamModifier| mod by DMagic packaged with this mod also overhauls Celestial Body Science Multipliers.
If you deleted/removed/renamed the Zs_Science.cfg file above, then you will probably also want to delete this entire folder
	= = GameData/ScienceParamModifier
	
Everything else will remain as PBC defines, including where the experiment parts are supposed to be on the tech tree.
```

Closing as not-a-bug.
