### ISSUE TITLE
[Bug] Weird version compatibility bug

### ISSUE THREAD

**Issue by mariusvn** [KSP-CKAN/NetKAN#8852]
Background
----------
* Operating System: Windows
* CKAN Version: 1.30.4
* KSP Version: 1.12.2.3167

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
None

Problem
-------
**Describe the bug**
I cannot download the compatible version of **Stockalike Station Parts Expansion Redux** that should be compatible up to v**1.12.9** with KSP v**1.12.2.3167**

**Steps to reproduce**
* just try to download **Stockalike Station Parts Expansion Redux** in KSP v1.12.2.3167 with CKAN v1.12.2.3167

**Expected behavior**
Download the compatible version

**Screenshots (if applicable)**

![bug](https://i.imgur.com/Qa1cmgB.png)

**CKAN error code (if applicable):**
None

**Comment by DasSkelett** [comment]
The "Max game version" column only applies to the mod itself, however for installation CKAN also checks the compatibility of dependencies, and blocks it if one or more dependencies aren't compatible yet.
In the case of Stockalike Station Parts Expansion Redux, it's B9 Part Switch. CKAN signals that through the "Relationships" tab (see the `<!>` marker and the mods listed in red):
![relationship tab](https://user-images.githubusercontent.com/28812678/140662922-cce2ddc0-0b99-4675-ad54-4f449b8babc0.png)

If you want to install it regardless, you need to [extend the range of KSP versions that CKAN considers as compatible](https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions). Many people go with KSP 1.8-1.12 currently, but of course, there is always a bit of risk involved in installing outdated mods.

**Comment by mariusvn** [comment]
Yeah i just viewed that i i was on my way to cancel the request , my bad
keep up the good work 💪🔥
