### ISSUE TITLE
Issue installing Probes before Crew in 1.12.9

### ISSUE THREAD

**Issue by Lincolnator42069** [KSP-CKAN/NetKAN#8855]
Hello, I am new to GitHub but I felt this is an issue that should be posted promptly, as I don't believe it is a difficult fix.  The mod Probes Before Crew is marked as incompatible with 1.12.9, due to dependency on Celestial Body Science Editor, which is only compatible up to 1.8.  Downloading and installing PBC manually from SpaceDock works fine, as it includes a ScienceParamModifier folder that is not dependent on Celestial Body Science Editor.  PBC is supposed to be compatible with 1.12.9.

If this issue can be fixed I would greatly appreciate it.

**Comment by HebaruSan** [comment]
Hi, thanks for contacting us.

ScienceParamModifier **_is_** Celestial Body Science Editor. Mod authors commonly ignore or misrepresent the supported compatibility of mods that they copy into their ZIPs, and this is an example of that. CKAN is showing you the actual versions the author of the mod supports:

![image](https://user-images.githubusercontent.com/1559108/140839249-b96c9f74-708b-4de8-aa52-cb58810e574e.png)

You can take a look at the `ScienceParamModifier.version` file contained in that ZIP to confirm:

```json
     "KSP_VERSION_MAX":{
         "MAJOR":1,
         "MINOR":8,
         "PATCH":8
     }
```

If you likewise want to take your chances with an unsupported version, you can add 1.8 to the versions that CKAN treats as compatible:

- https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions
