### ISSUE TITLE
[Bug] Mod - "scatterer 3:v0.0825b" conflicts with "Scatterer"

### ISSUE THREAD

**Issue by MgnfcntBstrd** [KSP-CKAN/NetKAN#8866]
Background
----------
* Operating System: Windows 10 21H1
* CKAN Version: 1.30.4
* KSP Version: 1.12.2.3167

In the past, I've added some manual mods like Grimmcore and BDB's patches, and have deleted the Mod manager cache file.  This problem did not start at that time.

Problem
-------
I have been getting "Meta data has changed, do you want to reinstall?" with scatterer when launching CKAN, which isn't fixed by clicking either button.

I was trying to add Antenna Helper today, but when I click the Apply button from the Changeset tab where only Antenna Helper is showing, I get an error:

The following inconsistencies were found:
* Scatterer 3:v0.0825b conflicts with Scatterer
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose

Neither Retry nor OK will continue and allow me to install the new mod.
![image](https://user-images.githubusercontent.com/94755111/142734510-576e0ecb-e17b-4c5e-bd88-ad7b896558ed.png)
![image](https://user-images.githubusercontent.com/94755111/142734518-4a2f628d-1d0a-4e19-9117-6edac3f574c5.png)
![image](https://user-images.githubusercontent.com/94755111/142734491-87a15c19-1f1b-4bae-8ce7-6631443553dc.png)

If I highlight Scatterer, and check the Relationships tab, it shows a self-referential conflict:
![image](https://user-images.githubusercontent.com/94755111/142734583-98ff0dec-d83e-422d-b56f-8a55579431d2.png)

I tried to get a screenshot of the "metadata changed" error, but it wouldn't come up again.

**Comment by HebaruSan** [comment]
Thanks for the report, we fixed this in KSP-CKAN/CKAN#3479. As a short term workaround, you can try renaming the folder `GameData/scatterer` to `GameData/Scatterer`.

**Comment by MgnfcntBstrd** [comment]
Awesome, thank you!
