### ISSUE TITLE
Duplicate CLSInterfaces.dll from ConnectedLivingSpace bundled in ShipManifest

### ISSUE THREAD

**Issue by georgedorn** [KSP-CKAN/NetKAN#8874]
Background
----------
* Operating System: Xubuntu 20.04
* CKAN Version: 1.29.0
* KSP Version: 1.12.2.3167

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Manually removed duplicate DLLs when problem appeared previously.

Problem
-------
Installing both of these mods results in an error message about duplicate DLLs, specifically CLSInterfaces.dll which appears in both mods.  Manually removing the copy within ShipManifest (as the message suggests) fixes it, but updating ShipManifest puts it back.

**Comment by DasSkelett** [comment]
You mean the in-game warning by ZeroMiniAVC, not an installation error by CKAN, right?

There is already a discussion in the forum about this: https://forum.kerbalspaceprogram.com/index.php?/topic/192130-111-connected-living-spaces-adopted-2006-2020-12-29/&do=findComment&comment=4044234

I don't think there's much CKAN can do about it right now, splitting it into a separate mod and installing it as dependency into the `GameData/ConnectedLivingSpace` directory will break conditional MM patches, as people already mentioned on the thread.

The mod is currently in the process of switching authors. Both ShipMnifest and ConnectedLivinSpace will be maintained by @PapaJoesSoup. I think it's likely that we are going to see a fix that helps both manual installers and CKAN soon.

**Comment by HebaruSan** [comment]
There's also some discussion on the ship Manifest thread:

https://forum.kerbalspaceprogram.com/index.php?/topic/56643-112x-ship-manifest-crew-science-resources-v-6030-21-nov-21/&do=findComment&comment=4058441

We might be able to hack something together that could make this better for CKAN users, but @PapaJoesSoup is going to be looking at it from the point of view of making changes that would also help non-CKAN users, and eventually the KSP devs should fix the bug that makes it crash when there are duplicate DLLs. So whatever hack workaround modules we add to the CKAN metadata would eventually just be clutter and have to be removed (probably after causing various problems of their own).

It's also worth noting that the current CLS releases are only marked compatible up to KSP 1.11, and the multi-DLL freeze bug only happens on KSP 1.12, so technically the CKAN metadata already accounts for this and any user experiencing this issue has already installed CLS at his or her own risk:

![image](https://user-images.githubusercontent.com/1559108/143250780-56e464d5-98b4-4fe8-bc60-960c40103156.png)

**Comment by HebaruSan** [comment]
What do you think of #8877, @DasSkelett? I think this is the solution that @PapaJoesSoup is planning to make to Ship Manifest for the short term:

![image](https://user-images.githubusercontent.com/1559108/143380425-a41a5dcc-2865-4cf5-aa97-8638b156e469.png)
