### ISSUE TITLE
File conflict between ContractConfigurator-HistoricMissions and ContractConfigurator-HistoricMissionsRSS

### ISSUE THREAD

**Issue by Dan-megabyte** [KSP-CKAN/NetKAN#8884]
Background
----------
* Operating System: Windows 10
* CKAN Version: v1.30.4
* KSP Version: 1.11.1.3066

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.
(Latest Ver of CKAN)

**Steps to reproduce**
About to install:

 * Additional Progression Contracts 1.1.1 (spacedock.info, 16.3 KiB)
 * Contract Configurator 1.30.5 (github.com, 552.1 KiB)
 * Contract Pack: Advanced Progression 4.5.1 (archive.org, 7.5 KiB)
 * Contract Pack: Base Construction 0.2.3 (github.com, 51.8 KiB)
 * Career Evolution 1.0 (github.com, 49.2 KiB)
 * Contract Pack: Clever Sats 1.4 (github.com, 205.0 KiB)
 * CommNet Relays v2.1.0 (github.com, 47.8 KiB)
 * Contract Pack: Historical Progression 1.6 (spacedock.info, 737.9 KiB)
 * Contract Pack: SCANSat v0.6.0.1 (github.com, 32.1 KiB)
 * Epic Space Program 0.5 (spacedock.info, 375.3 KiB)
 * Contract Pack: Exploration Plus 2.0.1 (github.com, 8.9 KiB)
 * Contract Pack: Field Research 1.2.2 (github.com, 33.1 KiB)
 * Contract Pack: Grand Tours 1:0.1.11 (spacedock.info, 202.5 KiB)
 * Contract Pack: Historic Missions 2.3.0 (spacedock.info, 3.9 MiB)
 * Contract Pack: Historic Missions for RSS 2.3.0 (spacedock.info, 3.9 MiB)
 * Contract Pack: Interplanetary Mountaineer 1.1.2 (spacedock.info, 55.3 KiB)
 * Contract Pack: GAP for JNSQ 1.0.4 (spacedock.info, 219.3 KiB)
 * Contract Pack: Kerbal Academy 1.1.10 (spacedock.info, 27.2 KiB)
 * Contract Pack: Kerbin-Side Jobs 2.1 (spacedock.info, 125.2 KiB)
 * Contract Pack: Bases and Stations Reborn 2:3.7.3 (github.com, 68.4 KiB)
 * Contract Pack: The K-Files 1.1.1.3 (github.com, 1.7 MiB)
 * Contract Pack: RemoteTech 2.1.4 (github.com, 29.2 KiB)
 * Contract Pack: Save the ROUND-8 1.3.0 (github.com, 11.7 KiB)
 * Contract Pack: Rover Missions 0.1.7 (spacedock.info, 189.4 KiB)
 * SCANsat mission pack 1.0.3 (github.com, 13.5 KiB)
 * Contract Pack: Sounding Rockets 1.2 (spacedock.info, 52.5 KiB)
 * Contract Pack: Tourism Plus 1.5.2 (github.com, 30.7 KiB)
 * Contract Pack: Unmanned Contracts 0.3.27 (spacedock.info, 198.0 KiB)
 * Contract Filter Continued 0.1.1.1 (spacedock.info, 42.7 KiB)
 * Crowd Sourced Science v6.0 (github.com, 337.5 KiB)
 * Easy Vessel Switch (EVS) 2.3 (spacedock.info, 157.9 KiB)
 * Contract Pack: Giving Aircraft a Purpose (GAP) 1.6.1 (spacedock.info, 230.5 KiB)
 * Kerbal Attachment System 1.10 (spacedock.info, 2.8 MiB)
 * Kerbal Planetary Base Systems v1.6.14 (spacedock.info, 36.2 MiB)
 * KSP Rescue Contract Fix 1.1.0 (spacedock.info, 13.1 KiB)
 * SCANsat v20.4 (spacedock.info, 19.3 MiB)
 * SETI-Contracts 1.3.0.0 (spacedock.info, 67.1 KiB)
 * Toolbar 1:1.8.0.7 (spacedock.info, 93.3 KiB)
 * Waypoint Manager 2.8.3.3 (github.com, 110.7 KiB)
 * AtmosphereAutopilot (Fly-By-Wire) v1.5.17 (github.com, 125.8 KiB)
 * Coherent Contracts 1:1.02 (spacedock.info, 11.7 KiB)
 * Kerbal Inventory System 1.28 (spacedock.info, 24.3 MiB)
 * Real Solar System Textures - 16384 x 8192 v18.3 (github.com, 1.7 GiB)
 * Module Manager 4.2.1 (ksp.sarbian.com, 61.5 KiB)
 * SpacetuxSA 0.3.13.1 (spacedock.info, 147.6 KiB)
 * Real Solar System v18.3.0 (github.com, 74.2 MiB)
 * Kopernicus Planetary System Modifier 2:release-1.12.1-66 (github.com, 391.7 KiB)
 * ModularFlightIntegrator 1.2.10.0 (ksp.sarbian.com, 9.3 KiB)
 * JNSQ 0.10.2 (github.com, 1.9 GiB)
 * Scatterer Sunflare 3:v0.0825b (spacedock.info, 6.9 MiB)
 * Kronometer v1.12.0.2 (github.com, 15.7 KiB)
 * Kerbal Konstructs v1.8.3.0 (github.com, 6.1 MiB)
 * Custom Pre Launch Checks 1.8.1.1 (github.com, 10.0 KiB)
 * RemoteTech v1.9.12 (spacedock.info, 3.4 MiB)
 * Community Category Kit v5.2.0.0 (github.com, 118.2 KiB)
 * Community Resource Pack 1.4.2 (github.com, 53.8 KiB)
 * ClickThrough Blocker 1:0.1.10.17 (spacedock.info, 109.4 KiB)
 * Zero MiniAVC 1:1.1.2.4 (spacedock.info, 28.5 KiB)
 * Toolbar Controller 1:0.1.9.6 (spacedock.info, 86.3 KiB)
 * SpaceTux Library 0.0.8.2 (spacedock.info, 485.0 KiB)

**Expected behavior**
It installs

**Screenshots (if applicable)**

![image](https://user-images.githubusercontent.com/80708654/143904140-cb4b7f72-b365-417c-bd85-7484bb556781.png)

**CKAN error code (if applicable):**

```
File      : GameData/ContractPacks/HistoricMissions/FuturePlans/LauncherMissions/Atlas-Agena.cfgx
Installing Mod : ContractConfigurator-HistoricMissionsRSS 2.3.0
Owning Mod: ContractConfigurator-HistoricMissions
CKAN Version   : v1.30.4
```

**Comment by DasSkelett** [comment]
Looks like we need a conflict between those two mods.
Btw, these mods are pretty outdated. They are just contract packs, so they might still work, but be aware that there could be issues.

**Comment by vinix38** [comment]
> Side note, if you're installing JNSQ, you probably don't want `ContractConfigurator-HistoricMissionsRSS`, since that would be for RealSolarSystem.

That could be another example for #2961 🤔
