### ISSUE TITLE
[Bug] module manager bug?

### ISSUE THREAD

**Issue by jas171006** [KSP-CKAN/NetKAN#8984]
Background
----------
* Operating System: windows 10
* CKAN Version: v1.29.2
* KSP Version: 1.12.3.3173

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
yes, I have downloaded mods via github and downloaded module manager

Problem
-------
**Describe the bug**
DLL for module ModuleManager found at GameData/Orion-1.8.2/GameData/ModuleManager.4.1.4.dll, but it's not where CKAN would install it. Aborting to prevent multiple copies of the same mod being installed. To install this module, uninstall it manually and try again.
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose

but I have deleted it from that folder but it just keeps saying that

**Steps to reproduce**
* Go to... update mods
* Click on... apply and continue and it loads for few seconds and downloads 2 things then there comes: installation failed above the green download bar
* See error

**Expected behavior**
just downloading it?

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by DasSkelett** [comment]
> DLL for module ModuleManager found at GameData/Orion-1.8.2/GameData/ModuleManager.4.1.4.dll

> but I have deleted it from that folder but it just keeps saying that

After deleting the file you need to click "Refresh" in CKAN so it rescans GameData.

However ModuleManager isn't the only problem, the whole mod (Orion) is installed incorrectly. Do you see that double GameData in the path? That is never a good sign.
When you manually install mods, you need to pull what's _inside_ the zip's _GameData_ folder, and put it into your KSP's GameData.

However in this case you shouldn't install this mod manually at all, as it is also available on CKAN. Look for "Stockist Project Orion".

Closing as this isn't a bug.
