### ISSUE TITLE
[Bug] "Procedural Parts - Hazard Tanks Textures" Related Mods are Reversed

### ISSUE THREAD

**Issue by MartyrKomplx** [KSP-CKAN/NetKAN#8998]
Background
----------
* Operating System: Windows 10, 21H2
* CKAN Version: 1.30.4
* KSP Version: 1.12.3

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Manually installed "Procedural Parts - Hazard Tanks Textures" without the CKAN-claimed dependency to verify suspicion in-game.

Problem
-------
Mod "Procedural Parts - Hazard Tanks Textures" shows Depends as "Procedural Parts - Ven's Revamp Style Textures" (VensStylePPTextures) and Suggested as "ProceduralParts".  Inspected file contents and found no reason for the former to be required, instead the latter contains the required content to make these textures work.

**Steps to reproduce**
* Go to... "Procedural Parts - Hazard Tanks Textures"
* Click on... Relationships tab

**Expected behavior**
Reverse the relationships to properly show "ProceduralParts" as required, and "Procedural Parts - Ven's Revamp Style Textures" (VensStylePPTextures) as the suggested.

**Comment by HebaruSan** [comment]
See KSP-CKAN/CKAN#1675 and #3969 for why the dependency is there. Apparently they both install `PPVensTankEnds.dds`.

**Comment by HebaruSan** [comment]
#5106 was when `ProceduralParts` was moved from depends to suggests, but unfortunately there was no documentation of why that was done. But it was done by @enceos, the author of the mod.
