### ISSUE TITLE
Change GasGiantsEnhanced Dependency

### ISSUE THREAD

**Issue by ballisticfox** [KSP-CKAN/NetKAN#9000]
Change RSS to a recommendation instead of a dependency.
--------
* Mod name: GasGiantsEnhanced 
* Author(s): ballisticfox
* License: CC-BY
* Homepage: <https://forum.kerbalspaceprogram.com/index.php?/topic/206773-gas-giants-enhanced-a-visual-mod-for-real-solar-system-and-ksrss/>
* Download: <https://spacedock.info/mod/2969/Gas%20Giants%20Enhanced>

**Comment by HebaruSan** [comment]
This appears to be so KSRSS could be used instead. KSRSS is not in CKAN and is hosted on GitLab (see KSP-CKAN/NetKAN#2554).
