### ISSUE TITLE
[Mod Update] Rocket Sound Enhancement - Default Configs

### ISSUE THREAD

**Issue by ensou04** [KSP-CKAN/NetKAN#9044]
Mod info
--------
Can the mod be renamed to "Rocket Sound Enhancement - Default"?
GitHub Repository has been moved to https://github.com/ensou04/RocketSoundEnhancementDefault

* Mod name: Rocket Sound Enhancement - Default
* Author(s): ensou04
* License: CC-BY-NC-SA-4.0
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/179579-wip110x-112x-rocket-sound-enhancement-v060-audio-framework-for-complex-sound-effects/
* Download: https://github.com/ensou04/RocketSoundEnhancementDefault/releases/

**Comment by HebaruSan** [comment]
Thanks for letting us know, should be updated for users within about 35 minutes.

**Comment by ensou04** [comment]
thank you!

**Comment by ensou04** [comment]
I just noticed the typo on ckan, it says "Rocket Sound **Enhancment** - Default"

**Comment by HebaruSan** [comment]
Thanks, a fix for that is in c31c575df5d11e1a943840888d813ff59ccc2804 and working its way through the system, shouldn't be more tan 30 minutes.
