### ISSUE TITLE
InfernalRoboticsNext.netkan - developing again

### ISSUE THREAD

**Issue by meirumeiru** [KSP-CKAN/NetKAN#9051]
in the next hours, I will release v3.0.7 of InfernalRobotics Next... and it will contain correct compatibility informations again in the version file

can you please remove the "max-version" override from the file?

**Comment by HebaruSan** [comment]
The override is specific to version `v3.0.0`, so the next release will not be affected by it. You should be fine as-is. :+1:

**Comment by meirumeiru** [comment]
ah, cool... thanks, didn't know it works like this :-)
