### ISSUE TITLE
[Mod Update] Final Frontier

### ISSUE THREAD

**Issue by jcklemme** [KSP-CKAN/NetKAN#9066]
Final Frontier is functioning 100% as expected in 1.12.  I was wondering if we could get that updated on CKAN
--------
* Mod name: Final Frontier
* Author(s): [Nereid]
* License: BSD-2-clause
* Homepage: http://forum.kerbalspaceprogram.com/index.php?/topic/61065-110-final-frontier-kerbal-individual-merits-102-2131/&page=1
* Download: https://github.com/Nereid42/FinalFrontier

**Comment by HebaruSan** [comment]
Current compatibility from forum thread:

![image](https://user-images.githubusercontent.com/1559108/162359800-52b4d003-b7f2-467e-8bea-118f7f4741b3.png)

Here's how you can mark 1.10 as compatible in your CKAN install if you want to try it anyway:

https://github.com/KSP-CKAN/CKAN/wiki/User-guide#Choosing-compatible-game-versions

CKAN's compatibility tries to reflect author intentions / support. If we make a change, then other users find bugs, and Nereid comes back to a big mess, it's not a good look for CKAN if our only response is that some rando on the internet said it was fine.
