### ISSUE TITLE
[Bug] Metadata for many USI mods should not require Community Resource Kit.

### ISSUE THREAD

**Issue by Ruedii** [KSP-CKAN/NetKAN#9090]
Background
----------
* Operating System:  (K)Ubuntu Linux
* CKAN Version: 1.30.4
* KSP Version:  1.12.3

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------
**Describe the bug**
Many USI mods require Community Resource pack when they shouldn't.
Many are inheriting this from USI Core, which does require it.  

**Desired behavior**
In all but a few necessary cases, USI Core should be considered recommended instead of Required, as should Community Resource Pack.

**Comment by DasSkelett** [comment]
The netkans for USI mods are all self-managed in https://github.com/UmbraSpaceIndustries/CKAN. Please open the issue there.
