### ISSUE TITLE
Kerbalism - Science-Only Config (hypodronic)

### ISSUE THREAD

**Issue by Mitokandria** [KSP-CKAN/NetKAN#9097]
Mod info:
A Kerbalism configuration that only enables the science mechanics in Kerbalism. Compatibility Fork for Kerbalism 3.1 and updates to supported mods.
--------
* Mod name: Kerbalism - Science-Only Config (Hypodronic's Fork)
* Author(s): SirMortimer, hypodronic, gotmachine
* License: Unilicense
* Homepage: 
* Download: https://github.com/hypodronic/KerbalismScienceOnly/archive/refs/heads/master.zip

_First time. Sorry if submitted incorrectly._

**Comment by HebaruSan** [comment]
Thanks for the suggestion. This was done in #7383.

**Comment by HebaruSan** [comment]
Oops, just noticed you're requesting a specific fork. We can look into that.

**Comment by HebaruSan** [comment]
There are no releases at <https://github.com/hypodronic/KerbalismScienceOnly/>, but the fork owner has submitted a pull request to get the changes into the main repo, see Kerbalism/KerbalismScienceOnly#3. That's a better way to go, and it looks like @hypodronic agrees. I'd recommend contacting the maintainers to make sure they know that pull request exists so they can review and merge it.
