### ISSUE TITLE
[Bug] Duplicate dll in TweakScale, Infernal Robotics and Ferram Aerospace Research Continued

### ISSUE THREAD

**Issue by angulion** [KSP-CKAN/NetKAN#9108]
Background
----------
* Operating System: Windows
* CKAN Version: 1.30.4
* KSP Version: 1.12.3

All mods installed using CKAN.

Problem
-------
TweakScale installs 999_Scale_Redist.dll in GameData\ (I think moves there with config).
Infernal Robotics installs GameData\MagicSmokeIndustries\Plugins\Scale_Redist.dll (a duplicate)
Ferram Aerospace Research Continued installs GameData\FerramAerospaceResearch\Scale_Redist.dll (yet a duplicate)

TweakScale will abort fatally if duplicates exists, while all will work fine if Scale_Redist.dll is deleted from IR and FAR.

**Comment by DasSkelett** [comment]
I think TweakScale didn't always throw the error for multiple `Scale_Redist.dll` in the past (that's kinda the purpose for redistributable libraries), but only started "recently", probably as a countermeasure to the KSP 1.12 bug with duplicate DLLs.

Looks like we need to filter them from IR and FAR, and split `999_Scale_Redist.dll` from TweakScale to a separate module.

Infernal Robotics and FAR should probably move the DLL to the root of GameData so manual installers don't hit this as well (and we don't need to filter it).

**Comment by angulion** [comment]
Updated report to clarify it is Ferram Aerospace Research Continued, not original.

**Comment by Lisias** [comment]
Hi! TweakScale ~culprit~maintainer here. Would it help to have the 999_Scale_Redist.dll delivered on its own zip file too?

**Comment by DasSkelett** [comment]
Hey, thanks for the offer. We can pick it out of the existing zip no problem. Since the TweakScale zip is already very small, it also isn't necessary to speed up the download time.
