### ISSUE TITLE
[Bug] Craft Manager & KXAPI duplicate KatLib.dll

### ISSUE THREAD

**Issue by angulion** [KSP-CKAN/NetKAN#9109]
Background
----------
* Operating System: Windows
* CKAN Version: 1.30.4
* KSP Version: 1.12.3

All mods installed using CKAN.

Problem
-------
Duplicate DLL KatLib.dll

Craft Manager contains GameData\CraftManager\Plugins\KatLib.dll
but so does Craft Managers dependency mod
KXAPI, GameData\KXAPI\Plugins\KatLib.dll

Deleting CraftManagers KatLib.dll resolves issue.

**Comment by angulion** [comment]
Can be closed as this is for an old version of KSP, mod author inactive and linuxguru making an continuation :)

**Comment by DasSkelett** [comment]
Do you actually see any error about this, or did you just find the DLLs by looking around?
Because I don't think those are a problem on KSP 1.12.3, the mods probably don't come with an install checker like TweakScale.

**Comment by angulion** [comment]
Found because of Exceptions in Player.log while solving another issue. Seems newer KSP versions are not fond of duplicates.

**Comment by DasSkelett** [comment]
> Seems newer KSP versions are not fond of duplicates.

This was a issue in KSP 1.12.0-1.12.2, but 1.12.3 has fixed the crash on duplicate DLLs.

Is there a chance you can recreate the exception and past it here, so we can see what's wrong and whether it does indeed need fixing?

**Comment by angulion** [comment]
I think best resolution for this would just be to limit KSP versions in CKAN to 1.3.x-.1.9.x as this mods forum post states, and not to "- any". User linuxgurugamer have made a continuation "[1.12.x] KSP Craft Organizer Improved - VAB/SPH tags + craft searching - BETA Release" which should be used instead.
(As I noticed this, I already replaced this old mod-pair)

**Comment by DasSkelett** [comment]
Compatibility has already been updated in #9110, so we should be good then. Thanks!
