### ISSUE TITLE
[Bug/Request] PRVE scatterer version needs updating

### ISSUE THREAD

**Issue by SpaceODY** [KSP-CKAN/NetKAN#9131]
PRVE v1.8 features the scatterer version finally being updated. I need the metadata with the mod to be updated with its required scatterer version (should be v0.0835). Thanks.

![image](https://user-images.githubusercontent.com/77604027/169188385-116310fd-c494-4164-95a8-b4ce2329881f.png)

**Comment by HebaruSan** [comment]
Thanks for letting us know. This change should become available to users shortly (it needs to go through some processing first, and then there's a 5 minute delay before GitHub updates the file CKAN downloads).
