### ISSUE TITLE
[Mod] ResearchBodies Update

### ISSUE THREAD

**Issue by AlexALX** [KSP-CKAN/NetKAN#9134]
Mod info
--------
* Mod name: ResearchBodies
* Author(s):  [JPLRepo](https://forum.kerbalspaceprogram.com/index.php?/profile/114736-jplrepo/)
* License: MIT & ARR
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/139473-112x-researchbodies-v1130-15th-may-2022/
* Download: https://github.com/JPLRepo/ResearchBodies/releases

There is New update what is not listed in CKAN. Who is responsive for updating this? As author did wrote:

> Whilst I agree CKAN is a great mod for those that can't use Zip tools. I take no part, nor am I interested in maintaining the CKAN mod metadata for my mods.
> Please don't ask me about it but refer to the [CKAN mod thread](https://forum.kerbalspaceprogram.com/index.php?/topic/90246-the-comprehensiv) if you are having issues with CKAN or the metadata it maintains.

**Comment by DasSkelett** [comment]
Which release are you missing on CKAN? We do have [V1.13.0](https://github.com/KSP-CKAN/CKAN-meta/blob/master/ResearchBodies/ResearchBodies-2-V1.13.0.ckan), which appears to match the latest one on GitHub.

**Comment by AlexALX** [comment]
Oh nevermind then, seems like my ckan failing to update by this error:

`Failed to download http://glacialsoftware.net/CKAN/Kopernicus_BE.tar.gz: System.Net.WebException: Server violated protocol. Section=ResponseStatusLine
   в System.Net.WebClient.DownloadFile(Uri address, String fileName)
   в System.Net.WebClient.DownloadFile(String address, String fileName)
   в CKAN.Net.Download(String url, String& etag, String filename, IUser user)
   в CKAN.Repo.UpdateRegistry(Uri repo, KSP ksp, IUser user, SortedDictionary`2& downloadCounts, String& currentETag)`
   
   have no idea why, but thats totally different story

**Comment by DasSkelett** [comment]
You have an external repository added to CKAN, for Kopernicus Bleeding Edge. It has moved to a different location a long time ago and the old URL apparently no longer works. You should remove it from the settings, and if you want you can add the new one there (it should show up in the list of known repositories), but I think there isn't much activity for Kopernicus BE currently.
