### ISSUE TITLE
[Mod Update] Minmar Kerbin Rings 2.1

### ISSUE THREAD

**Issue by Lithobraker** [KSP-CKAN/NetKAN#9139]
Update 2.1: Fixed a dumb oversight where the textures weren't loading properly due to the asset path in the Kopernicus config not including the proper new folder names.
Sorry for this mistake, it was late last night...
(Not sure if this is how you're supposed to upload mod updates. Couldn't find anything about it on the wiki, and just looked at the issues here.)
--------
* Mod name: Minmar Kerbin Rings
* Author(s): Lithium-7
* License: MIT
* Homepage: [Link](https://forum.kerbalspaceprogram.com/index.php?/topic/190029-112x-minmar-kerbin-rings-21-kopernicus/)
* Download: [MinmarKerbinRings2.1.zip](https://github.com/KSP-CKAN/NetKAN/files/8781050/MinmarKerbinRings2.1.zip)

**Comment by HebaruSan** [comment]
Hi, thanks for contacting us. You actually don't need to do anything for new releases; it's all automated, and the new release has already been indexed:

https://github.com/KSP-CKAN/CKAN-meta/compare/e0e661b728852f2e8fa6b1d74e1bd91e751ecdfa...e127128cfe675c2312f011e739b72aeb112b851e

**Comment by HebaruSan** [comment]
This page gives a summary of how the automation works:

https://github.com/KSP-CKAN/CKAN/wiki/How-does-CKAN-work

And more detail is available here:

https://github.com/KSP-CKAN/NetKAN-Infra/blob/master/README.md

**Comment by Lithobraker** [comment]
> Hi, thanks for contacting us. You actually don't need to do anything for new releases; it's all automated, and the new release has already been indexed:
> 
> [KSP-CKAN/CKAN-meta@e0e661b...e127128](https://github.com/KSP-CKAN/CKAN-meta/compare/e0e661b728852f2e8fa6b1d74e1bd91e751ecdfa...e127128cfe675c2312f011e739b72aeb112b851e)

Oh, thank you, and sorry! I didn't see anything added by the bot in pull requests and assumed it had to be done manually.
