### ISSUE TITLE
[Mod Update] Rocket Sound Enhancement - Default

### ISSUE THREAD

**Issue by ensou04** [KSP-CKAN/NetKAN#9155]
I made an error labeling the latest release. It says "1.2.3" it should be "1.2.2"

* Mod name: Rocket Sound Enhancement - Default
* Author(s): ensou04
* License: CC-BY-NC-SA-4.0
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/179579-wip110x-112x-rocket-sound-enhancement-v060-audio-framework-for-complex-sound-effects/
* Download: https://github.com/ensou04/RocketSoundEnhancementDefault/releases/

**Comment by HebaruSan** [comment]
Thanks for letting us know! We do have automated checks in place that ought to have caught this eventually, but it helps a lot to know exactly what you meant to do. The 1.2.3 version should be removed shortly...

**Comment by ensou04** [comment]
thank you for the work!

**Comment by HebaruSan** [comment]
1.2.2 has been added in https://github.com/KSP-CKAN/CKAN-meta/commit/c3280f49cceb30732fb6d34c881e777d707ba901
