### ISSUE TITLE
[Mod] PRVE 1.9 Changes

### ISSUE THREAD

**Issue by SpaceODY** [KSP-CKAN/NetKAN#9222]
With 1.9 released there are two things I need changed:

1. I forgot to retag the draft from v1.8.1 to v1.9 so I will need the .ckan file for v1.8.1 deleted and a new one for v1.9 with its correct links and version number created (sorry).
![image](https://user-images.githubusercontent.com/77604027/180657172-867a4964-d782-4823-b223-1606314a9d08.png)

2. There is a new mod I want added from the GitHub release on 1.9 called "PRVE-LRv1.9". 
Name = "PRVE Low Resolution"
Conflicts: PRVE
Dependencies: same as PRVE

3. Finally, since "PRVE Low Resolution" will conflict with "PRVE", I need "PRVE" to also conflict with "PRVE Low Resolution" (Vice versa)
Thanks!

___

https://github.com/SpaceODY/PRVE

**Comment by HebaruSan** [comment]
Hi, thanks for the updates.

- [x] I think [v1.9](https://github.com/KSP-CKAN/CKAN-meta/commit/bc5915902bcf3c87cb58aad52c45bdfa0b14ec5c) is already there
- [ ] To delete [v1.8.1](https://github.com/KSP-CKAN/CKAN-meta/blob/master/PhotoRealisticVisualEnhancement/PhotoRealisticVisualEnhancement-v1.8.1.ckan), you can click the trash can icon on the linked page and follow the flow through to a pull request
- [ ] I'll start a PR for the low res variant...

**Comment by SpaceODY** [comment]
![image](https://user-images.githubusercontent.com/77604027/180663030-679c4aa6-68de-40cd-b48f-c9e50eb41bae.png)
I think you forgot to rename the low res "PRVE Low Resolution"

**Comment by HebaruSan** [comment]
Yup, oops. Will do that now.
