### ISSUE TITLE
[Bug] RP-1 Shows compatibility with 1.12.3 But can not be installed

### ISSUE THREAD

**Issue by ColdFerrin** [KSP-CKAN/NetKAN#9306]
Background
----------
* Operating System: Windows 10 21H2 19044.1889
* CKAN Version: 1.31.0
* KSP Version: 1.12.3.3173

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
Realistic Progression 1 max version is listed as 1.12.9, however there is no checkbox to install the game and when you try to force it by version it says unsupported

**Steps to reproduce**
* Open CKAN with an instace of the latest game version
* In the search box put "RP-1"
* No check box is shown

**Expected behavior**
RP-1 Should be installable

**Screenshots (if applicable)**
<img width="883" alt="Screenshot 2022-08-29 190838" src="https://user-images.githubusercontent.com/5272443/187332824-4bb29898-bda6-4d56-bc7a-0b60e43e7d8d.png">
<img width="317" alt="Screenshot 2022-08-29 190901" src="https://user-images.githubusercontent.com/5272443/187332833-8e2c7bb1-5846-4607-820f-ada3dbd24217.png">

**CKAN error code (if applicable):**

**Comment by HebaruSan** [comment]
Luckily the RP-1 team has a wiki with comprehensive instructions on how to install:

https://github.com/KSP-RO/RP-0/wiki/RO-&-RP-1-Express-Installation-for-1.12.3

I'd recommend following those steps carefully.

**Comment by HebaruSan** [comment]
In case you're curious, the first incompatible dependency is SXTContinued, because it requires Firespitter:

![image](https://user-images.githubusercontent.com/1559108/187334301-e5109ac1-f64c-4765-96b2-9d072e86b5f7.png)

I'll see if we can make that clearer.

**Comment by ColdFerrin** [comment]
That would be great. It is not very clear its not compatible, because a dependency is compatible.
