### ISSUE TITLE
Parallax 1.3.1 required, but an incompatible version is in the resolver

### ISSUE THREAD

**Issue by GiGi961** [KSP-CKAN/NetKAN#9322]
Hey,

The following inconsistencies were found:
* Parallax 1.3.1 required, but an incompatible version is in the resolver

**Comment by StonesmileGit** [comment]
This has just been fixed! If you refresh the mods on ckan, it should work now

**Comment by GiGi961** [comment]
TY for your fast answer and help !

**Comment by HebaruSan** [comment]
Thanks for keeping us on our toes.
This was fixed in KSP-CKAN/NetKAN#9321.
