### ISSUE TITLE
[Mod] Starilex Intra-Vehicular Solutions: MKI Pod 'Needle'

### ISSUE THREAD

**Issue by Ailex01** [KSP-CKAN/NetKAN#9325]
Mod info
--------
* Mod name: Starilex Intra-Vehicular Solutions: MKI Pod 'Needle'
* Author(s): https://forum.kerbalspaceprogram.com/index.php?/profile/203237-ailex/ (It's me, I just use Gitlab and not Github)
* License: CC-BY-NC-SA
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/209466-1123-starilex-intra-vehicular-solutions-mki-pod-needle/
* Download: https://gitlab.com/Ailex-/starilex-mk1-iva/-/archive/main/starilex-mk1-iva-main.zip

___

- https://gitlab.com/Ailex-/starilex-mk1-iva/
- https://gitlab.com/Ailex-/starilex-mk1-iva/-/releases

**Comment by HebaruSan** [comment]
Hi, thanks for contacting us. Currently we don't have good support for mods on GitLab, but it's something that we'd like to have and have looked at before, see KSP-CKAN/CKAN#2554. I'll take another look now that we've had a real request to do it. (Frankly I'm surprised it took this long!)

**Comment by HebaruSan** [comment]
Hi @Ailex01, I think the folder name is misspelled in the ZIP; it's `liex` there whereas everywhere else it's `ilex`:

![image](https://user-images.githubusercontent.com/1559108/189190589-8a409d98-e30d-4c50-8367-693ab0b2fb09.png)

**Comment by Ailex01** [comment]
@HebaruSan well, this is a bit embarassing,
originally the name was indeed `starliex`, but like 70% into the making of the mod I liked `starilex` more, so I used that.

I was just incredibly lazy to rename every folder and file, and in fact, many of the props for the IVA have the `starliex`
name instead of `starilex` (at first glance the `.cfg` files do have the correct name, but if you open any of them
they have `name = STARLIEX__` prefix ).

So, yeah, if you can wait until tomorrow I will try to make a commit where I update the names, or if it isn't that big of deal I'm okay with this little imperfection ^^`

P.S. I've glanced at the Issue you linked on the comment above, and there's a typo on my email, at the end it's `@protonmail.ch`,
and the `l` is missing ( `@protonmai.ch` )

I hope I'm not causing too much of a hussle =)

**Comment by HebaruSan** [comment]
Well, if you want to keep the folder name like that, we can adapt. I just like to notify mod authors whenever I notice something that might not be quite right, and it's up to you whether it's actually wrong or important enough to change.

We don't actually need or use your email at all, I was just dumping all of the data from the GitLab API so I could reference it while coding.

> I hope I'm not causing too much of a hussle =)

No, not at all. :+1:

**Comment by Ailex01** [comment]
Oh, wonderful!

So yep, it's all "okay", maybe in the mid-future I will take the time to make everything neat,
but for now I guess it stays like that, oh and thanks for taking the time to look for these small details ! 🙂

**Comment by HebaruSan** [comment]
Hi @Ailex01, thanks for the request; if you look in CKAN now (and click Refresh) you should see this mod listed.

I wanted to note one important detail since you gave the `main.zip` link here and in your forum page: that is **not** what CKAN will download, since it changes every time you make a commit, which may or may not be ready for users and doesn't represent a stable version. CKAN will only look at the releases that you create here:

https://gitlab.com/Ailex-/starilex-mk1-iva/-/releases

So if you want to make new changes available to CKAN users, you can do that by making a new release.
