### ISSUE TITLE
[Mod] Kcalbeloh System Planet Pack

### ISSUE THREAD

**Issue by jcyuan06** [KSP-CKAN/NetKAN#9330]
Mod info
--------
* Mod name: Kcalbeloh System Planet Pack
* Author(s): Jason Kerman
* License: CC-BY-NC-ND
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/203753-wip-112x-kcalbeloh-system-planet-pack-beta-13-a-journey-to-a-black-hole-jul-10-2022/
* Download: https://github.com/jcyuan06/Kcalbeloh-System/releases

**Comment by HebaruSan** [comment]
Hi @jcyuan06, thanks for contacting us.

Taking a look at the repo, all of the releases seem to be marked as pre-releases:

![image](https://user-images.githubusercontent.com/1559108/189573976-07d8a0ac-e50c-4f07-98f2-8bcf36777c28.png)

The CKAN bot skips pre-releases, so if we tried to add this now, all we'd get is errors. Are you planning to create a full release at some point?

**Comment by jcyuan06** [comment]
Yes, a full release is coming soon. I will let you know when I post a full release.

**Comment by jcyuan06** [comment]
Hi! I have just posted a new release. Thank you!
