### ISSUE TITLE
File conflict between older versions of Parallax texture modules

### ISSUE THREAD

**Issue by NaethKerman** [KSP-CKAN/NetKAN#9352]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.31.0
* KSP Version: 1.12.3

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Yes

Problem
-------
**Describe the bug**
CKAN cannot update Parallax Stock Scatter Textures from 2.0.0 to 2.0.1 due to a "packaging bug".

**Steps to reproduce**
* Load CKAN
* Select KSP directory
* Load said directory
* Add available updates
* See error

**Expected behavior**
CKAN Should update all mods needing updates

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

Info wanted to be placed within report
File      : GameData/Parallax_StockTextures/_Scatters/Configs/Bop.cfg
Installing Mod : Parallax-StockScatterTextures 2.0.1
Owning Mod: Parallax-StockTextures
CKAN Version   : v1.31.0

**Comment by NaethKerman** [comment]
Its version currently is 2.0.0

**Comment by HebaruSan** [comment]
Aha! I think you managed to install Parallax-StockTextures 2.0.0 in the 4-hour interval between https://github.com/KSP-CKAN/CKAN-meta/commit/0e4d1e4aedfe8bde68e736820fac075d52651a7a and https://github.com/KSP-CKAN/CKAN-meta/commit/df7c1b740b9c793899b93943ea628457b31e6b27 while we were still working on #9319 and the wrong download file was associated with that module.

Just uninstall it and then install again. To avoid problems like this in the future, click "Yes" when CKAN prompts you to reinstall things after refreshing the registry.

**Comment by HebaruSan** [comment]
Confirmed that the prompt appears if the original copies of the .ckan files are installed, and confirmed that clicking Yes succeeds.
