### ISSUE TITLE
OPENSSL_internal:CERTIFICATE_VERIFY_FAILED for Stockalike Station Parts

### ISSUE THREAD

**Issue by CharlesCage** [KSP-CKAN/NetKAN#9375]
Background
----------
* Operating System: Linux 5.10 Debian GNU/Linux 11 64bit
* CKAN Version: 1.31.0
* KSP Version: 1.12.3.3173 (LinuxPlayer) en-us

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Problem
-------
Fails to install Stockalike Station Parts

**Steps to reproduce**
* Open CKAN
* Select Stockalike Station Parts Expansion Redux and Stockalike Parts Expansion Redux - Internal Spaces
* Select Apply Changes

**Expected behavior**
* Install mods

**Screenshots (if applicable)**
None

**CKAN error code (if applicable):**

```
About to remove:

 * Module Manager 4.2.2
About to install:

 * Stockalike Station Parts Expansion Redux 2.0.10 (spacedock.info, 424.1 MiB)
 * Stockalike Station Parts Expansion Redux - Internal Spaces 2.0.10 (spacedock.info, 424.1 MiB)
 * Near Future IVA Props 1:0.7.1 (cached)
Downloading "https://spacedock.info/mod/1682/Stockalike%20Station%20Parts%20Expansion%20Redux/download/2.0.10"
One or more downloads were unsuccessful:

Error downloading StationPartsExpansionRedux 2.0.10: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at ./external/boringssl/ssl/handshake_client.c:1132

```

**Comment by HebaruSan** [comment]
Hi, that error most likely means you have an expired certificate. Here's how to remove it:

https://github.com/KSP-CKAN/CKAN/wiki/SSL-certificate-errors#removing-expired-lets-encrypt-certificates
