### ISSUE TITLE
All Modular RSS Mods

### ISSUE THREAD

**Issue by thepres1sStuff** [KSP-CKAN/NetKAN#9384]
Stock size RSS, but all planets/systems are in separate mods
--------
* Mod name: Modular RSS: Earth/Moon/Mercury/Venus/Mars/Jupiter/Saturn/Uranus/Neptune/Pluto
* Author(s): sDaZe
* License: CC-BY-NC-SA/MIT
* https://forum.kerbalspaceprogram.com/index.php?/topic/206831-modular-stock-size-rss/
* https://spacedock.info/mod/2975/ModularRSS-Mercury
* https://spacedock.info/mod/2974/ModularRSS-Venus
* https://spacedock.info/mod/2972/ModularRSS%20-%20Earth
* https://spacedock.info/mod/2973/ModularRSS%20-%20Moon
* https://spacedock.info/mod/2976/ModularRSS%20-%20Mars
* https://spacedock.info/mod/2977/ModularRSS%20-%20Jupiter%20
* https://spacedock.info/mod/2981/ModularRSS%20-%20Saturn
* https://spacedock.info/mod/2983/ModularRSS%20-%20Uranus
* https://spacedock.info/mod/2984/ModularRSS%20-%20Neptune
* https://spacedock.info/mod/2985/ModularRSS%20-%20Pluto

**Comment by HebaruSan** [comment]
Hi @thepres1sStuff, thanks for contacting us. Has the author been asked about this? We only add mods to CKAN if it's OK with the author. I did some browsing of the thread and found this, which never got a reply:

![image](https://user-images.githubusercontent.com/1559108/196005366-d4e76c78-b491-43b9-8e7a-f621410979d4.png)

**Comment by thepres1sStuff** [comment]
I never knew about this. I will go on the forums and ask this question. Thank you for telling me. Whenever I want a mod on CKAN, I will ask the developer on the forums before requesting a mod.

**Comment by HebaruSan** [comment]
Please let us know if you do hear from the author, and we can re-open this. Closing in the meantime since we don't have any tasks here to be done by the CKAN team.
