### ISSUE TITLE
[Mod] Planetside Exploration Technologies

### ISSUE THREAD

**Issue by Kspenjoyer** [KSP-CKAN/NetKAN#9386]
Mod info
--------
* Planetside Exploration Technologies
* Benjee10 and ValiZokct
* All rights reserved
* https://forum.kerbalspaceprogram.com/index.php?/topic/201439-112x-bg-planetside-exploration-technologies-surface-bases-nasa-mmsev-wind-turbines-more-v102/
* https://spacedock.info/mod/2681/Planetside%20Exploration%20Technologies#info

**Comment by HebaruSan** [comment]
Ahh, that was this mod:

![image](https://user-images.githubusercontent.com/1559108/197091317-c7111c67-a8ec-4fcb-bcf8-853e5c10b27f.png)

![image](https://user-images.githubusercontent.com/1559108/197091424-14abb28e-f58a-4efd-ab8a-35eebc16e098.png)

Author has been asked already and didn't respond. Closing.

**Comment by HebaruSan** [comment]
Approval acquired via Discord PM:

![image](https://user-images.githubusercontent.com/1559108/205148901-3b73d41b-592c-401e-9811-459edd9b2a45.png)

**Comment by linuxgurugamer** [comment]
That's great news, thanks for following up
