### ISSUE TITLE
[Mod] Shuttle Orbiter Construction Kit Recolored

### ISSUE THREAD

**Issue by oofergoofer** [KSP-CKAN/NetKAN#9392]
Mod info
Recolors for benjee10's SOCK (shuttle orbiter construction kit)
--------
* Mod name: SHUTTLE ORBITER CONSTRUCTION KIT RECOLORED
* Author(s): Invaderchaos, benjee10
* License: MIT
* <https://forum.kerbalspaceprogram.com/index.php?/topic/195154-111x-shuttle-orbiter-construction-kit-recolored-version-13/>
* <https://spacedock.info/mod/2461/Shuttle%20Orbiter%20Construction%20Kit%20Recolored>
* <https://github.com/Invaderchaos/SOCK-Recolored>

**Comment by HebaruSan** [comment]
Hi @Invaderchaos, we've had a request to add your Shuttle Orbiter Construction Kit Recolored mod to CKAN. Would that be OK with you? We only add mods to CKAN if it's OK with the author.

**Comment by oofergoofer** [comment]
how's the process going?

**Comment by HebaruSan** [comment]
> how's the process going?

I found him but he's not online, so I sent a PM and will proceed if and when I hear back.

**Comment by HebaruSan** [comment]
Approval granted via Discord PM:

![image](https://user-images.githubusercontent.com/1559108/197359476-72654fac-82b8-49f3-9e93-2db4d1a186b4.png)

**Comment by oofergoofer** [comment]
is the mod available on ckan now?

**Comment by HebaruSan** [comment]
Yes.

https://github.com/KSP-CKAN/CKAN-meta/commit/ed8f313a8aaae10678072522d9b92f2bf5df8dda

![image](https://user-images.githubusercontent.com/1559108/197361380-eae8da0a-1627-422f-8c05-f46bf6dddbe8.png)
