### ISSUE TITLE
[Mod] LunarTransferPlanner

### ISSUE THREAD

**Issue by RCrockford** [KSP-CKAN/NetKAN#9407]
Mod info
--------
* Mod name: LunarTransferPlanner
* Author(s): RCrockford
* License: MIT
* Homepage: https://github.com/KSP-RO/LunarTransferPlanner
* Download: https://github.com/KSP-RO/LunarTransferPlanner/releases

**Comment by HebaruSan** [comment]
Thanks for the submission!
