### ISSUE TITLE
DLL для модуля «DistantObject» найдена в GameData/DistantObject/DistantObject.dll, но не там, где её бы установил CKAN. 

### ISSUE THREAD

**Issue by undivido** [KSP-CKAN/NetKAN#9422]
DLL для модуля «DistantObject» найдена в GameData/DistantObject/DistantObject.dll, но не там, где её бы установил CKAN. Во избежание установки нескольких копий модификации операция отменена. Вручную удалите модуль и попробуйте снова.
Ошибка в процессе установки!
Если сообщение выше сообщает об ошибке загрузки, попробуйте ещё раз. В противном случае отправьте отчёт об ошибке.
Если вы подозреваете ошибку в метаданных: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
Если вы подозреваете ошибку в клиенте: https://github.com/KSP-CKAN/CKAN/issues/new/choose

File - 86374C24-DistantObject-default-v2.0.3.1.zip

English translation:

> The DLL for the "DistantObject" module was found in GameData/DistantObject/DistantObject.dll, but not where CKAN would have installed it. To avoid installing multiple copies of the modification, the operation has been cancelled. Manually remove the module and try again.
> Error during installation!
> If the message above reports a download error, please try again. Otherwise, file a bug report.
> If you suspect a metadata error:

**Comment by HebaruSan** [comment]
The message contains instructions for how to handle it. Did you try those?

**Comment by HebaruSan** [comment]
(The correct path for this DLL seems to be `DistantObject/Plugins/DistantObject.dll`, for reference. So the `Plugins` folder is missing in your install.)

**Comment by undivido** [comment]
![image](https://user-images.githubusercontent.com/56364085/200762867-f482c552-d68e-49df-9683-2cf49b1544c2.png)

**Comment by HebaruSan** [comment]
> The message contains instructions for how to handle it. Did you try those?

We can't help if our questions aren't answered.
