### ISSUE TITLE
[Mod] Shuttle Pathfinder Orbiter Construction Kit

### ISSUE THREAD

**Issue by oofergoofer** [KSP-CKAN/NetKAN#9429]
Mod info: Shuttle Pathfinder Orbiter Construction Kit
--------
* Mod name: SPOCK
* Author(s): rogerwang86
* License: https://creativecommons.org/licenses/by-nc-sa/4.0/ (CC-BY-NC-SA 4.0)
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/210184-112xwipspock-shuttle-pathfinder-orbiter-construction-kit-stockalike-nuclear-shuttle-pathfinder-from-fam-v020/
* Download: https://github.com/rogerwang86/SPOCK/releases/tag/v0.2.0

**Comment by HebaruSan** [comment]
Hi @oofergoofer,  thanks for contacting us. We only add mods to CKAN if it's OK with the author. Checking the forum thread, I see one post asking about CKAN, to which the author has not replied:

https://forum.kerbalspaceprogram.com/index.php?/topic/210184-112xwipspock-shuttle-pathfinder-orbiter-construction-kit-stockalike-nuclear-shuttle-pathfinder-from-fam-v020/&do=findComment&comment=4188783

Hi @rogerwang86, would you be OK with it if we added your SPOCK mod to CKAN?

**Comment by rogerwang86** [comment]
Yes, I'm glad to see my mod on CKAN. Does CKAN accept a WIP mod? And how
can I publish my mod on CKAN?

HebaruSan ***@***.***> 於 2022年11月12日 週六 07:05 寫道：

**Comment by HebaruSan** [comment]
Excellent! The usual instructions for adding your mod to CKAN are here:

https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN

However, since someone else requested it and I've become involved already, I was planning to take care of it myself if you gave approval. You will still have the opportunity to review the metadata and inspect the output of our validation tools if you wish to do that. I will make sure to tag you when I submit the pull request with the needed changes.

**Comment by HebaruSan** [comment]
Hi @rogerwang86, the forum thread says this mod is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License, but [the repo suggests the MIT license](https://github.com/rogerwang86/SPOCK/blob/v0.2.0/LICENSE). Which would you like us to use?

**Comment by rogerwang86** [comment]
CC BY-NC-SA 4.0 license.
By the way, how can I change the repo license to CC BY-NC-SA 4.0?

HebaruSan ***@***.***> 於 2022年11月12日 週六 10:05 寫道：

**Comment by HebaruSan** [comment]
You would put the text of that license into the file at:

https://github.com/rogerwang86/SPOCK/blob/main/LICENSE

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by rogerwang86** [comment]
Cool.
If I release a new update on github, should I renew the download link?

**Comment by HebaruSan** [comment]
Once this pull request is merged, CKAN's bot will automatically find new releases from your repo.

**Comment by oofergoofer** [comment]
sorry if i seem impatient, but any updates on this getting added to CKAN?

**Comment by HebaruSan** [comment]
Yes, see #9430 for the in progress netkan. I told @rogerwang86 he could review it, and he said he would check it later, so that's the next step.

**Comment by HebaruSan** [comment]
Looks good! I will merge the pull request.
