### ISSUE TITLE
[Mod update] Kopernicus v1.12.1-139

### ISSUE THREAD

**Issue by Shadlock0133** [KSP-CKAN/NetKAN#9436]
Listed in the index as "Kopernicus Planetary System Modifier", latest release on github is 1.12.1-139 while ckan only list it up to 1.12.0-48. It might have to do with remote version file, which has been moved from `https://raw.githubusercontent.com/Kopernicus/Kopernicus/master/build/KSP19+/GameData/Kopernicus/Plugins/Kopernicus.version` to `https://raw.githubusercontent.com/Kopernicus/Kopernicus/master/build/KSP19PLUS/GameData/Kopernicus/Plugins/Kopernicus.version`

**Comment by DasSkelett** [comment]
It's there:
![screenshot](https://user-images.githubusercontent.com/28812678/201521620-ecc493cc-60fa-44dd-afda-9c49ed245184.png)

Maybe you just haven't refreshed the repository in CKAN in a long time?

**Comment by Shadlock0133** [comment]
I definitely refreshed it, maybe my metadata repo is outdated?

**Comment by DasSkelett** [comment]
Can you send a screenshot of the "Versions" tab like I did?

I'm not seeing any change in metadata between [1.12.0-48](https://github.com/KSP-CKAN/CKAN-meta/blob/master/Kopernicus/Kopernicus-2-release-1.12.0-48.ckan) and [1.12.1-49](https://github.com/KSP-CKAN/CKAN-meta/blob/master/Kopernicus/Kopernicus-2-release-1.12.1-49.ckan), something like compatibility or dependencies, that might cause newer versions not to be offered as upgrades to you.

**Comment by Shadlock0133** [comment]
I've cleared the "metadata repositories" list and re-add the default one, now it works correctly.

**Comment by HebaruSan** [comment]
KSP-CKAN/CKAN#3699 also reported missing updates. It's possible there's a bug that we haven't identified yet.
