### ISSUE TITLE
[Mod] kRPC for 1.12 by nullprofile

### ISSUE THREAD

**Issue by Shadlock0133** [KSP-CKAN/NetKAN#9437]
Mod info
--------
* Mod name: kRPC
* Author(s): djungelorm, nullprofile
* License: LGPLv3
* Repository: https://github.com/nullprofile/krpc
* Download: https://github.com/nullprofile/krpc/releases
* https://forum.kerbalspaceprogram.com/index.php?/topic/62902-14x13x122-krpc-remote-procedure-call-server-v047-27th-july-2018/
* https://forum.kerbalspaceprogram.com/index.php?/topic/130742-15x-to-122-krpc-control-the-game-using-c-c-java-lua-python-ruby-haskell-c-arduino-v048-28th-october-2018/

This fork is updated for KSP v1.12, but also includes some changes (mod integrations, mentioned in readme).

**Comment by HebaruSan** [comment]
Hi @nullprofile, are you interested in having your kRPC fork added to CKAN? The current version in CKAN is from 2018, and your repo has been promoted recently by users on both of the currently active kRPC forum threads.

**Comment by HebaruSan** [comment]
@Shadlock0133, please let us know if you are able to contact @nullprofile to get approval for this, and we can re-open it.
