### ISSUE TITLE
[Mod] reCOLOR a SOCK addon

### ISSUE THREAD

**Issue by oofergoofer** [KSP-CKAN/NetKAN#9454]
Mod info
--------
* Mod name: ReCOLOR
* Author(s): [Lil_Bread402](https://forum.kerbalspaceprogram.com/index.php?/profile/208484-lil_bread402/), Benjee10
* License: Not listed in both forum and github? may want to ask the author, I can't find it anywhere
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/209107-recolor-a-sock-addon/
* Download: https://github.com/matvey00701/reCOLOR

**Comment by HebaruSan** [comment]
This has `reDIRECT` as a dependency, which we haven't been able to get approval for (I think Benjee10 may no longer be supporting it).

We have already added a few SOCK reskin mods though, have you seen them?

- <https://forum.kerbalspaceprogram.com/index.php?/topic/195154-*> (#9395)
- #9292

And for our own future reference, there's apparently this one that we haven't added yet:

- <https://forum.kerbalspaceprogram.com/index.php?/topic/208794-*>
- <https://spacedock.info/mod/3053/SOCKrepainted>

Reskinning SOCK has become a pretty popular pastime!

**Comment by oofergoofer** [comment]
👍

**Comment by HebaruSan** [comment]
Hi @matvey00701, we've had a request to add your SOCK reskin to CKAN. If we can get approval from Benjee10 for reDIRECT, would that interest you?

**Comment by HebaruSan** [comment]
@oofergoofer, if you're able to get in touch with @matvey00701, please let us know and we can re-open this.

**Comment by oofergoofer** [comment]
> @oofergoofer, if you're able to get in touch with @matvey00701, please let us know and we can re-open this.

I'll try my best
