### ISSUE TITLE
[Mod] Habtech2

### ISSUE THREAD

**Issue by oofergoofer** [KSP-CKAN/NetKAN#9456]
Mod info
--------
* Mod name: Habtech2
* Author(s): benjee10
* License: ARR
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/133501-112x-habtech2-stockalike-iss-parts-026/
* <https://github.com/benjee10/HabTech2>
* <https://spacedock.info/mod/2078/HabTech2>

**Comment by HebaruSan** [comment]
Sent Discord PM to author...

**Comment by HebaruSan** [comment]
No reply so far. @oofergoofer, if you're able to get in touch with Benjee10, please let us know and we can re-open this.
