### ISSUE TITLE
[Mod] ASTRO

### ISSUE THREAD

**Issue by oofergoofer** [KSP-CKAN/NetKAN#9470]
Mod info
--------
* Mod name: ASTRO
* Author(s): astro119
* License: All rights reserved
* <https://github.com/astro119/ASTRO>

**Comment by astro119** [comment]
yeah im fine with it

**Comment by HebaruSan** [comment]
Oh, I didn't realize all the releases were pre-releases. CKAN doesn't index pre-releases. @astro119, are you planning to make a full release soon? If not we can come back to this when you're ready.

**Comment by HebaruSan** [comment]
Second question: What _is_ this mod? We'll need to write a short description for the `abstract` property. Looks like it's parts, but what's the theme?

**Comment by astro119** [comment]
it's a parts mod based off of systems from the lockheed martin mars base camp concept

**Comment by HebaruSan** [comment]
> Oh, I didn't realize all the releases were pre-releases. CKAN doesn't index pre-releases. @astro119, are you planning to make a full release soon? If not we can come back to this when you're ready.

This is still a showstopper for this request. If a release is posted that is not a pre-release, please let us know; until then we can't move forward.
