### ISSUE TITLE
[Mod] Persistent Thrust Navigator (v1.1.0)

### ISSUE THREAD

**Issue by oofergoofer** [KSP-CKAN/NetKAN#9488]
Mod info
--------
* Mod name: PersistentThrustNavigator
* Author(s): JarredEagley
* License: Unlisted (or i just can't find it)
* Homepage: https://github.com/JarredEagley/PersistentThrustNavigator
* original forum post: https://forum.kerbalspaceprogram.com/index.php?/topic/107676-wip13-solarsailnavigator-v109/
* Download: https://github.com/JarredEagley/PersistentThrustNavigator/releases

**Comment by oofergoofer** [comment]
any progress?

**Comment by HebaruSan** [comment]
An adoption and significant rewrite/rebranding of SolarSailNavigator (see #1165, #1376, #8477).

License here: <https://github.com/JarredEagley/PersistentThrustNavigator/blob/PTNavigator/LICENSE.txt>

Looks like it's packaged wrong; basically all of the dependency DLLs from the game are in the Plugin folder (which probably also violates various copyrights). (And the mod's DLL is still called `SolarSailNavigator.dll`.) The repo doesn't have issues enabled, but it shouldn't be too hard to whip up a pull request to fix this if it comes to that.

Hi @JarredEagley, are you still working on this mod? If so, would it be OK with you if we added it to CKAN?

**Comment by JarredEagley** [comment]
> An adoption and significant rewrite/rebranding of SolarSailNavigator (see #1165, #1376, #8477).
> 
> License here: https://github.com/JarredEagley/PersistentThrustNavigator/blob/PTNavigator/LICENSE.txt
> 
> Looks like it's packaged wrong; basically all of the dependency DLLs from the game are in the Plugin folder (which probably also violates various copyrights). (And the mod's DLL is still called `SolarSailNavigator.dll`.) Submitted [JarredEagley/PersistentThrustNavigator#1](https://github.com/JarredEagley/PersistentThrustNavigator/pull/1) to fix.
> 
> Hi @JarredEagley, are you still working on this mod? If so, would it be OK with you if we added it to CKAN? We only add mods if it's OK with the author/maintainer.

Hey @HebaruSan!

I don't actively work on this mod at this time; my spare time has plummeted like a Mk.3 capsule missing its parachutes ever since I started my career. 

However, having the project packaged wrong is definitely quite the miss! I really didn't know what I was doing at the time, so I'm not all too surprised that something is horribly wrong. 
Sorry about that, and thanks for the PR. I'll review it shortly.

You may add this mod to CKAN if you'd like. I would defer to the original mod creator, but I don't think he's active anylonger.

**Comment by HebaruSan** [comment]
New release has addressed the problem with packaging✔️:

https://github.com/JarredEagley/PersistentThrustNavigator/releases/tag/v1.1.3

**Comment by JarredEagley** [comment]
> An adoption and significant rewrite/rebranding of SolarSailNavigator (see #1165, #1376, #8477).
> 
> License here: https://github.com/JarredEagley/PersistentThrustNavigator/blob/PTNavigator/LICENSE.txt
> 
> Looks like it's packaged wrong; basically all of the dependency DLLs from the game are in the Plugin folder (which probably also violates various copyrights). (And the mod's DLL is still called `SolarSailNavigator.dll`.) Submitted [JarredEagley/PersistentThrustNavigator#1](https://github.com/JarredEagley/PersistentThrustNavigator/pull/1) to fix.
> 
> Hi @JarredEagley, are you still working on this mod? If so, would it be OK with you if we added it to CKAN? We only add mods if it's OK with the author/maintainer.

I don't remember if I replied to this-- but in case I didn't, go ahead! Licensing should be the same as the original mod. Might not have made it into the release zip file by accident.
