### ISSUE TITLE
TALSphericalToroidalPack not a valid ZIP file: broken uncompressed block

### ISSUE THREAD

**Issue by guska84** [KSP-CKAN/NetKAN#9507]
Background
----------
* Operating System: Windows 11
* CKAN Version: 1.31.2
* KSP Version: 1.12.4.3187

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

No

Problem
-------
When trying to install Spherical and Toroidal Tank Pack, CKAN throws this error when unpacking
```
CKAN.InvalidModuleFileKraken: TALSphericalToroidalPack 3.12: C:\Users\goose\AppData\Local\CKAN\downloads\downloading\0E819EA4-TALSphericalToroidalPack-3.12.zip is not a valid ZIP file: Error in step EntryData for ModsByTal/Parts/FuelTank/Toroidal/Textures/Brown.png: Exception during test - 'broken uncompressed block'
   at CKAN.NetModuleCache.Store(CkanModule module, String path, IProgress`1 progress, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error, String etag)
```
I have retried this multiple times. 

**Steps to reproduce**
Go to Manage Mods, Refresh
Select Spherical and Toroidal Tank Pack
Apply changes
Allow Firespitter Core v7.17 (Dependency)
Do not install Real Fuels
Apply

**Expected behavior**
Expect CKAN to download and install Firespitter Core and Spherical and Toroidal Tank Pack

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/17737429/211429748-20b95627-e4cf-43cd-b3a9-af2bbfbd1c0f.png)

![image](https://user-images.githubusercontent.com/17737429/211429770-d1c530ae-c9c0-4637-a2d7-f936e69cb07c.png)

![image](https://user-images.githubusercontent.com/17737429/211429815-812e4a2d-858e-4a09-af00-127d2d461a90.png)

![image](https://user-images.githubusercontent.com/17737429/211429864-c5cf796f-4026-4eda-8133-03a5429e5cfc.png)

**CKAN error code (if applicable):**

```
N/A
```

**Comment by HebaruSan** [comment]
Seems to be a real problem with that file in that ZIP. Here's what Windows says when I try to extract it manually:

![image](https://user-images.githubusercontent.com/1559108/211461166-41e04fce-15f1-482f-921e-98c4cbf56845.png)

**Comment by HebaruSan** [comment]
Looks like this mod's repo is here, you could try asking about the issue with the ZIP there:

https://github.com/taniwha/TalisarParts

Although I suspect this is an outdated download. This (very old) module is downloading from http://taniwha.org/~bill/spherical-tanks.zip , but the forum thread:

https://forum.kerbalspaceprogram.com/index.php?/topic/116849-18-19-talisar-parts-v130/

... mentions http://taniwha.org/~bill/TalisarParts-1.3.0.zip , which is indexed in CKAN as TalisarParts.

@guska84, I would recommend installing the TalisarParts mod instead. This one's probably broken and unlikely to be fixed.
