### ISSUE TITLE
[Bug] Scatterer Download Error

### ISSUE THREAD

**Issue by reloc4** [KSP-CKAN/NetKAN#9516]
Background
----------
* Operating System: Win10
* CKAN Version: 1.31.3 / 1.31.2
* KSP Version: 1.12.5.3190

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

NO as far as I know, 
uninstalled every mod with CKAN und let Steam check the files.

Problem
-------
**Describe the bug**
The Folloing Error Apears:

CKAN.InvalidModuleFileKraken: Scatterer-sunflare 3:v0.0831: C:\Users\reloc4\AppData\Local\CKAN\downloads\downloading\F2E8567B-Scatterer-sunflare-3-v0.0831.zip has length 9382395, should be 9382103
   at CKAN.NetModuleCache.Store(CkanModule module, String path, IProgress`1 progress, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error, String etag)

**Steps to reproduce**

Install / Download Scatterer 

**Expected behavior**

No Error

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
This download was replaced by the author, and the CKAN metadata was updated in Feb 2022:

https://github.com/KSP-CKAN/CKAN-meta/commit/169976d904cfe8427282556c16a78c240ade7114

Click Refresh to update your registry.

**Comment by reloc4** [comment]
Refresh says Repo already up to date.

How do I update the registry?

**Comment by HebaruSan** [comment]
Hmm, that sounds like KSP-CKAN/CKAN#3699, then. You could switch over to the dev build:

- https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe

... and then refresh again the next time there's a new metadata update commit:

- https://github.com/KSP-CKAN/CKAN-meta/commits/master

They should continue rolling in every few hours as authors update compatibility to the new 1.12.5 game version.

**Comment by reloc4** [comment]
OK Thanks,
I fixed the for me now by copying the install files from CKAN\downloads\downloading to CKAN\downloads\ 
this prevents the check.
Has to be done as long as the Error messege is there because the downolad will be deleted later.

**Comment by HebaruSan** [comment]
Cool. The metadata looks OK, the functional issue is covered by KSP-CKAN/CKAN#3699, and a workaround has solved the immediate issue. Closing.
