### ISSUE TITLE
[Mod] [x] Science!

### ISSUE THREAD

**Issue by Ralnoc** [KSP-CKAN/NetKAN#9546]
Mod info
--------
* Mod name: [x] Science!
* Author(s): Z-Key Aerospace, Brodrick, Flupster
* License: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International license
* Homepage: https://github.com/Flupster/KSP-X-Science
* Download: https://github.com/Flupster/KSP-X-Science/releases/download/5.26/x-science-v5.26.zip

The original [x] Science! was hosted at https://github.com/thewebbooth/KSP-X-Science. This has been taken over by Flupster with his post here: https://forum.kerbalspaceprogram.com/index.php?/topic/182683-ksp-190-x-science-continued-ksp-science-report-and-checklist-v523/

Version 5.26 has been tested and is fully functional with KSP 1.12.5

**Comment by HebaruSan** [comment]
Thanks for the request. This mod is already indexed, starting three years ago in #7021. It was subsequently adopted by @linuxgurugamer, see #8676 and #9311.

- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/xScienceContinued.netkan
- https://github.com/KSP-CKAN/CKAN-meta/blob/master/xScienceContinued/xScienceContinued-5.26.ckan
- https://spacedock.info/mod/3100/[X]%20Science!%20Continued
