### ISSUE TITLE
i deleted all mods but it says it tried to add a mod owned by another mod or something

### ISSUE THREAD

**Issue by apolloTheidiot** [KSP-CKAN/NetKAN#9570]
ive closed ckan already so i cant show anything, sorry

**Comment by HebaruSan** [comment]
We can't do anything for you with no info. Sorry.

**Comment by HebaruSan** [comment]
The issue template is here, if you can submit enough info to re-open this:

https://github.com/KSP-CKAN/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
