### ISSUE TITLE
Download for EPL is corrupted

### ISSUE THREAD

**Issue by quasinaut** [KSP-CKAN/NetKAN#9578]
Downloaded via CKAN (http://taniwha.org/~bill/ExtraplanetaryLaunchpads_v6.99.3.zip):
![image](https://user-images.githubusercontent.com/126029878/220490389-a5c63209-9c97-429e-88a8-46f88f01cfb3.png)

Downloaded via web browser (http://taniwha.org/~bill/ExtraplanetaryLaunchpads_v6.99.3.zip):
![image](https://user-images.githubusercontent.com/126029878/220490247-96061978-9513-4b68-b0f3-7f6b0200f74d.png)

Quick fix:
Change extra planetary launchpads to use github (https://github.com/taniwha/Extraplanetary-Launchpads/releases/tag/v6.99.3), where I have no issues with corruption upon unzipping

Feature fix:
Change CKAN to automatically skip files corrupted files

**Comment by HebaruSan** [comment]
This should be reported to the mod author, whose server has been distributing corrupted ZIPs for a while now (maybe a failing disk?):

- <https://github.com/taniwha/Extraplanetary-Launchpads/issues>

The GitHub releases are not usable because the source archive does not contain the plugin. You can unzip them, but the mod won't work.

**Comment by quasinaut** [comment]
Thanks, I did not realize the "release" contained no plugin. To be fair, CKAN could skip corrupted files like windows does but this is a distribution issue

**Comment by HebaruSan** [comment]
Skipping corrupted files would be installing the mod incorrectly. Mod authors tend not to like it if CKAN installs their mods incorrectly, so we go to great lengths to avoid that.

**Comment by quasinaut** [comment]
That makes sense but does that mean via direct download would be incorrect then? It seems like there is no way to get the mod now. Anyways, thanks

**Comment by HebaruSan** [comment]
I don't know what you mean by "via direct download would be incorrect", so I can't answer that.

Yes, it's quite problematic that this author's mods are unreliably available. We're not able to solve that, though.

**Comment by HebaruSan** [comment]
The server problems have been reported to the mod author here:

- taniwha/Extraplanetary-Launchpads#202
- taniwha/Extraplanetary-Launchpads#205

No response so far. If @taniwha isn't active anymore, maybe we should freeze these mods and redirect their downloads to archive.org.

**Comment by HebaruSan** [comment]
Bad sector on firewall noted about 8 months ago:

<https://forum.kerbalspaceprogram.com/topic/54284-112-extraplanetary-launchpads-v6993/?do=findComment&comment=4201640>

![image](https://github.com/KSP-CKAN/NetKAN/assets/1559108/b7e11a62-cf95-4240-9f72-a83d573fa311)
