### ISSUE TITLE
[Bug] ht Robotics bundled with SOCK

### ISSUE THREAD

**Issue by blooest** [KSP-CKAN/NetKAN#9585]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.31.2
* KSP Version: 1.12.5

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
ht Robotics as required by HabTech 2 and newly added to CKAN is also bundled with Shuttle Orbiter Construction Kit as it currently exists on the repository, creating a conflict if both mods are requested.

**Steps to reproduce**
Attempt to install both HabTech2 and Shuttle Orbiter Construction Kit

**Expected behavior**
Both mods can be installed as they are intended to be run together.

**Screenshots (if applicable)**
N/A

**CKAN error code (if applicable):**

```
File      : GameData/htRobotics/Parts/@thumbs/ht.C1.LEE_icon.png
Installing Mod : HabTechRobotics v1.0.0
Owning Mod: ShuttleOrbiterConstructionKit
CKAN Version   : v1.31.2
Your GameData has been returned to its original state.
Error during installation!
```

**Comment by HebaruSan** [comment]
Thanks, good point, I think I couldn't find a standalone repo for that one when SOCK was being added...
