### ISSUE TITLE
[Bug] Tweakscale Redist requires KSP Recall mod as a dependancy

### ISSUE THREAD

**Issue by SsapS** [KSP-CKAN/NetKAN#9588]
Background
----------
* Operating System: Win10
* CKAN Version: 1.31.2
* KSP Version: 1.12.5.3190

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
Symmetry glitched out.  After uninstalling mods one by one i narrowed it down to tweakscale.  Visited the forum page for tweakscale and they are aware that KSP Recall is a required dependency.

https://forum.kerbalspaceprogram.com/index.php?/topic/179030-ksp-130-tweakscale-under-lisias-management-24623-2023-0207/

Edit: This did not actually fix the bug I was experiencing, but CKAN also did not report the dependency of KSP Recall mod, so if that needs to be addressed by CKAN or the mod creator I will leave this up.

If its not related to CKAN and only metadata from mod creator, mark as solved.

**Comment by HebaruSan** [comment]
Thanks for the report. KSP-Recall is already listed as a dependency of TweakScale:

https://github.com/KSP-CKAN/NetKAN/blob/b401106aa611d20c74aa37bf3fcd8e68b2d68465/NetKAN/TweakScale.netkan#L27-L31

TweakScale-Redist is not the same thing as TweakScale; TweakScale-Redist is just an API DLL that other mods can use to talk to Tweakscale. It can be installed without installing TweakScale. Dependency listings on the TweakScale forum page apply to TweakScale, not TweakScale-Redist.
