### ISSUE TITLE
[Mod] Add Eve Optimized Engines

### ISSUE THREAD

**Issue by Blu3wolf** [KSP-CKAN/NetKAN#9593]
Mod info
--------
* Mod name: Eve Optimized Engines
* Author(s): OhioBob
* License: CC-BY-NC-ND-4.0
* Homepage: <https://forum.kerbalspaceprogram.com/index.php?/topic/136342-1122-eve-optimized-engines-v302/>
* Repo: https://github.com/OhioBob/Eve-Optimized-Engines
* Download: https://github.com/OhioBob/Eve-Optimized-Engines/releases

I was certain this was previously on CKAN, but I dont see it in the history of the NetKAN repo.

**Comment by HebaruSan** [comment]
> I was certain this was previously on CKAN, but I dont see it in the history of the NetKAN repo.

Sounded familiar to me as well, I think we were thinking of:

- <https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/ExplodiumBreathingEngines.netkan>
