### ISSUE TITLE
[Mod]: Plume Party

### ISSUE THREAD

**Issue by JadeOfMaar** [KSP-CKAN/NetKAN#9626]
### Mod Name

Plume Party

### Author(s)

JadeOfMaar

### License

CC-BY-NC-SA

### Homepage link

https://github.com/JadeOfMaar/PlumeParty/

### Download link

https://github.com/JadeOfMaar/PlumeParty/releases

**Comment by JadeOfMaar** [comment]
Asking for two entries to be created. One for the bulk of the mod and the other for its `Configs/` dir which contains configs for Squad's parts. Some mods (example, made by benjee10, and BDB) include Plume Party but are looking to depend on it without carrying outdated bundles within themselves.

**Comment by HebaruSan** [comment]
Noting the last time this was discussed and we decided to allow bundling: #7711

**Comment by HebaruSan** [comment]
Checking the readme:

> Plume Party has known incompatibilities with ReStock and will, where possible, avoid activation on engines made or remodeled by Nertea.

... should this be reflected in CKAN as a `conflicts` relationship?

**Comment by HebaruSan** [comment]
FYI, it looks like the version file is out of date, so if this was added as a dependency, users would have to manipulate the compatible versions settings to install this and the depending mods:

```json
	"KSP_VERSION":
	{
		"MAJOR":1,
		"MINOR":9,
		"PATCH":1
	}
```
