### ISSUE TITLE
[Mod]: Biome Corrections [v1.1]

### ISSUE THREAD

**Issue by 16BitWonder** [KSP-CKAN/NetKAN#9646]
### Mod Name

Biome Corrections

### Author(s)

Rodg88

### License

CC BY-NC-SA 4.0

### Homepage link

https://spacedock.info/mod/1555/Biome%20Corrections

### Download link

https://spacedock.info/mod/1555/Biome%20Corrections/download

**Comment by 16BitWonder** [comment]
This mod is currently listed on Ckan but only the 1.0 version, a more recent 1.1 release was made that drops the edits to Tylo since its biomes have been fixed in stock.

**Comment by HebaruSan** [comment]
Thanks for letting us know; 4 years between releases was enough to trip the tools we use to detect mods that aren't being updated anymore. #9647 will put this mod back in the rotation.
