### ISSUE TITLE
[Bug]:  TACLS does not install

### ISSUE THREAD

**Issue by Dr4kn** [KSP-CKAN/NetKAN#9659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Linux PopOS (latest)

### CKAN Version

1.32.0 (latest)

### KSP Version

1.12.5 (latest)

### Did you make manual changes?

No

### Describe the bug

It fails to install

Even without any other mods installed, and after I cleared the cache and verified the integrity of the game files.

### Steps to reproduce

Select TAC and press Apply 

### Relevant log output

```shell
File      : GameData/ThunderAerospace/TacLifeSupport/LifeSupport.cfg
Installing Mod : TACLS-Config-Stock v0.12.4
Owning Mod: TACLS
CKAN Version   : v1.32.0
Your GameData has been returned to its original state.
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
```

**Comment by HebaruSan** [comment]
Don't install `TACLS-Config-Stock`. This is an old module that existed to support an old way of handling TACLS's configs, and is no longer needed (see #5326 and #5330).
