### ISSUE TITLE
[Mod]: SRCS - Stageable RCS

### ISSUE THREAD

**Issue by kurgut** [KSP-CKAN/NetKAN#9687]
### Mod Name
SRCS - Stageable RCS

### Author(s)
[kurgut](https://github.com/kurgut)

### License
CC BY-SA

### Short Description
This mod simply allows you to activate RCS via staging. So at launch, they'll be in a disabled state, until staged by user. You can re-order stages as any other engines in the VAB too.

### Homepage link
https://forum.kerbalspaceprogram.com/index.php?/topic/176365-131-112-srcs-stageable-rcs/

### Download link
https://github.com/kurgut/SRCS-Stageable-RCS/releases

### Repository
https://github.com/kurgut/SRCS-Stageable-RCS

### Issues
https://github.com/kurgut/SRCS-Stageable-RCS/issues

### Spacedock link
https://spacedock.info/mod/1900/SRCS%20-%20Stageable%20RCS

### Incompatible with :
Realism Overhaul

### Compatible with KSP versions :
1.3.1 - 1.12.*

**Comment by HebaruSan** [comment]
Thanks, this is already in progress in #9686.

**Comment by kurgut** [comment]
Yeah sorry for the inconvenience,
I was unsure as this is the first time I submit a mod to CKAN.
Peace
