### ISSUE TITLE
[Mod]: Neptune Camera

### ISSUE THREAD

**Issue by Tantares** [KSP-CKAN/NetKAN#9708]
### Mod Name

Neptune Camera

### Author(s)

Beale (Forum) / Tantares (GitHub) 

### License

All Rights Reserved

### Homepage link

https://forum.kerbalspaceprogram.com/topic/196339-111x-neptune-camera-basic-camera-utility-4014022021/

### Download link

https://github.com/Tantares/NeptuneCamera/releases

**Comment by HebaruSan** [comment]
Hi,

> This does already seem to be on CKAN somehow

Yes, it was requested by @Tantares in #8101 and added in #8091.

> but lacks a version file, etc. I've now added this to the repo.

Cool, thanks for letting us know, we can update that...
