### ISSUE TITLE
[Bug]: Overwrite between Tweakscale Redist and Tweakscale

### ISSUE THREAD

**Issue by bobby2411** [KSP-CKAN/NetKAN#9736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10

### CKAN Version

v1.32.0

### Game Version

Steam KSP 1.12.5.3190

### Describe the bug

I was not expecting this error to occur, also had this occur on an earlier version of CKAN, so that's not the issue. Might be a packaging error with the files.

### Steps to reproduce

Attempt to download Tweakscale Redist while having the regular Tweakscale installed
Let it download and attempt to install the file.
Get the "Oh no! We tried to overwrite a file owned by another mod!" error, caused by this file apparently being overwritten: GameData/999_Scale_Redist.dll

### Relevant log output

From the status log, attempting in install the TweakScale Redist file as a standalone to see if any mods were conflicting, turns out to be a no.
About to remove:

 * Zero MiniAVC 1:1.1.0.1
About to install:

 * TweakScale Redistributable v2.4.7.1 (cached)
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it may be a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/NetKAN/issues/new/choose

Please include the following information in your report:

File      : GameData/999_Scale_Redist.dll
Installing Mod : TweakScale-Redist v2.4.7.1
Owning Mod: TweakScale
CKAN Version   : v1.32.0
Your GameData has been returned to its original state.
Error during installation!

**Comment by HebaruSan** [comment]
Which file?

**Comment by bobby2411** [comment]
> Which file?

went ahead and put that into the thing, didn't know that that was a requirement.

**Comment by HebaruSan** [comment]
CKAN hasn't installed that file for TweakScale since #9114. Are you trying to install an old version of TweakScale or something?

**Comment by bobby2411** [comment]
> CKAN hasn't installed that file for TweakScale since #9114. Are you trying to install an old version of TweakScale or something?

no, i have the TweakScale file already, I just don't know why some mods need it.

**Comment by HebaruSan** [comment]
What version of TweakScale do you have installed or are trying to install?

**Comment by HebaruSan** [comment]
Try uninstalling TweakScale and then installing it again.

**Comment by bobby2411** [comment]
alright, I'll see if that makes it not install that file.

**Comment by HebaruSan** [comment]
That shouldn't matter, you can delete it or not as you please.

**Comment by bobby2411** [comment]
> That shouldn't matter, you can delete it or not as you please.

hmmm
![image](https://github.com/KSP-CKAN/NetKAN/assets/77946045/28f858ac-1082-4165-8b32-846653fd758c)
I don't think TweakScale is going to be re-installed anytime soon on my KSP instance...

**Comment by HebaruSan** [comment]
That screenshot looks fine to me. I don't know what problem you're trying to highlight.

**Comment by bobby2411** [comment]
well it managed to install properly... weird.

**Comment by HebaruSan** [comment]
Glad you got it working! 🎉

**Comment by bobby2411** [comment]
guess it didn't realize that that KSP Recall mod was a dependency or smth... then again I had it manually installed so maybe that was the issue.
