### ISSUE TITLE
Kopernicus.dll is registered to Kopernicus but has not been removed

### ISSUE THREAD

**Issue by ink0r** [KSP-CKAN/NetKAN#9747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Win 10

### CKAN Version

1.33.2

### Game Version

1.12.5.3190

### Describe the bug

Can't install an update to Kopernicus 2, CKAN gives an error about inconsistencies found
No idea if this is a NetKAN or CKAN bug sorry if this is in wrong place, but metadata problem sounds more likely?

### Steps to reproduce

cleared Kopernicus archive from CKAN cache
attempted to re apply update through CKAN as if it were a download error, still happens

### Relevant log output

```
* Upgrade: Kopernicus Planetary System Modifier 2:release-1.12.1-176 to 2:release-1.12.1-177 (cached)
The following inconsistencies were found:
* D:/Games/SteamLibrary/steamapps/common/Kerbal Space Program/GameData/Kopernicus/Plugins/Kopernicus.Parser.dll is registered to Kopernicus but has not been removed!
* D:/Games/SteamLibrary/steamapps/common/Kerbal Space Program/GameData/Kopernicus/Plugins/Kopernicus.dll is registered to Kopernicus but has not been removed!
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose
```

**Comment by HebaruSan** [comment]
That means your OS  wouldn't let CKAN delete that file, which usually means either the permissions got messed up (possibly because CKAN was run as administrator previously) or the game is still running. Make sure the game is closed (reboot if necessary), check the permissions, and try again.
