### ISSUE TITLE
[Mod]: SigmaDimensions is outdated on CKAN

### ISSUE THREAD

**Issue by jcyuan06** [KSP-CKAN/NetKAN#9771]
### Mod Name

Sigma Dimensions

### Author(s)

Sigma88

### License

All Rights Reserved

### Homepage link

https://github.com/Sigma88/Sigma-Dimensions

### Download link

https://github.com/Sigma88/Sigma-Dimensions/releases

**Comment by HebaruSan** [comment]
Hi, this was by author request, see #6527.
