### ISSUE TITLE
[Mod]: Stock Alarm Clock Disabler

### ISSUE THREAD

**Issue by UltraJohn** [KSP-CKAN/NetKAN#9773]
### Mod Name

Stock Alarm Clock Disabler

### Author(s)

UltraJohn

### License

GNU General Public License v3.0

### Homepage link

https://forum.kerbalspaceprogram.com/topic/219015-112x-stock-alarm-clock-disabler/

### Download link

https://github.com/UltraJohn/StockAlarmClockDisabler/releases

### Additional info
Compatible with KSP 1.12.x
Requires [HarmonyKSP](https://github.com/KSPModdingLibs/HarmonyKSP/releases)
Recommends: Kerbal Alarm Clock

**Comment by HebaruSan** [comment]
Thanks for the submission!
