### ISSUE TITLE
[Mod]: Better Screen Messages

### ISSUE THREAD

**Issue by UltraJohn** [KSP-CKAN/NetKAN#9777]
### Mod Name

Better Screen Messages

### Author(s)

UltraJohn

### License

GNU General Public License v3.0

### Homepage link

https://forum.kerbalspaceprogram.com/topic/219077-112x-better-screen-messages/

### Download link

https://github.com/UltraJohn/BetterScreenMessages/releases

**Comment by HebaruSan** [comment]
Hi @UltraJohn, thanks for the submission. I had a follow-up question I was hoping you could answer:

There's a `PluginData/settings.cfg` file in here that looks to have user configuration already in it. By default, if a user installs this mod, changes those settings, and then later upgrades to a newer version of the mod, CKAN would unpack the `settings.cfg` file again and overwrite the user's settings (as would many users attempting to upgrade manually). Normally it's bad to use user configuration.

We could address this by excluding this file from the install, but that only works if the mod can handle it being missing. Do you know whether the mod will work properly if `settings.cfg` file is absent? Thanks!

**Comment by HebaruSan** [comment]
Looking at the code, without a config file, the mod won't crash, but it also won't do anything:

https://github.com/UltraJohn/BetterScreenMessages/blob/e1efe38efd5bc0a7303bfb881d75fc97864330c9/Source/BetterScreenMessages.cs#L15-L31

So neither option is ideal; either the mod does nothing when you install it, or you lose any customizations you may have made at upgrade. Ideally a reasonable default setting would be applied if the config file is missing, so users don't have to edit a .cfg file to get something out of this mod.

**Comment by HebaruSan** [comment]
On the other hand, if we install the settings file, users could apply their own ModuleManager patches in other custom unmanaged files. That way the customizations would survive upgrades.

**Comment by UltraJohn** [comment]
Hi, thanks for the heads up. I was initially not planning on making any major changes to the mod, unless someone requests it, so the thought of the file being overwritten on a new version slipped my mind. I can look into making the file auto generate on launch, so that the file is not needed to be included with the download. But I think for now we can let it be included, and if I make any major changes, I will make sure to not bundle the settings.cfg with future updates, and that should be fine?

**Comment by HebaruSan** [comment]
> if I make any major changes, I will make sure to not bundle the settings.cfg with future updates, and that should be fine?

Then the file would be deleted and not replaced at upgrade, since CKAN would have installed it originally in this release. Upgrading involves removing the files CKAN installed for the old version and then installing the new version fresh.

For now I think it's OK to install it and let users patch it with ModuleManager if they really want to.

**Comment by UltraJohn** [comment]
So if I'm understanding it correctly, if the next version I release does not include settings.cfg, then the file will get deleted automatically upon upgrading via CKAN? That seems like the best solution, since then I will have implemented the code to generate a default file if it doesn't exist. And then from there on the settings file will persist through further upgrades as it won't be part of the installation initially.

**Comment by HebaruSan** [comment]
That's a reasonable long-term solution, with only one problematic short-term scenario:

1. User installs current version now
2. User edits the config file to customize
3. User upgrades to next version, customizations are deleted along with the old file

And I guess the point about ModuleManager was incorrect because the file is in `PluginData`, which ModuleManager can't touch since the game won't load it.

**Comment by UltraJohn** [comment]
Yeah I'll just go with that solution for this time. Future mods I make I will make sure to keep your advice in mind, to avoid doing the same mistake.

Thank you for the advice!
