### ISSUE TITLE
[Mod]: kos-ferram

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/NetKAN#9856]
### Mod Name

kos-ferram

### Author(s)

giuliodondi

### License

GPLv3

### Homepage link

https://github.com/giuliodondi/kOS-Ferram

### Download link

https://github.com/giuliodondi/kOS-Ferram/releases

**Comment by JonnyOThan** [comment]
Waiting for final confirmation here: https://github.com/giuliodondi/kOS-Ferram/issues/3

**Comment by HebaruSan** [comment]
I think "I'd like to see it there" is a pretty good confirmation.

**Comment by giuliodondi** [comment]
Hello, as per the issue opened I renamed the dll to 'kOS-Addons-Ferram.dll' with no dots, is the new name ok?

**Comment by JonnyOThan** [comment]
@giuliodondi yeah that should be fine, thanks!

**Comment by HebaruSan** [comment]
> Hello, as per the issue opened I renamed the dll to 'kOS-Addons-Ferram.dll' with no dots, is the new name ok?

Hi, sorry, I thought it was at first, but the code isn't what I remembered; any file starting with `kOS` and ending with `.dll` will trigger this error. I'll fix that in the next release of CKAN...

**Comment by giuliodondi** [comment]
that's good to know, because I discovered that the latest change broke the addon somehow. If the name change isn't required anymore I'll revert it

**Comment by JonnyOThan** [comment]
I'll try and get a Netkan up in the next few days, ran out of time today.  Or someone else can get to it first.
