### ISSUE TITLE
CryoTanks is missing a dependency on B9PartSwitch

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/NetKAN#9894]
The dependency is listed in the forum post.  Without B9PS, CryoTanks will remove resources from stock parts.  But the netkan is managed on nertea's github repo.  Can/should we just add the dependency on our side?

**Comment by HebaruSan** [comment]
First I would try a pull request for the metanetkan. We should be able to get @ChrisAdderley's attention either there or on DIscord eventually.

- <https://github.com/post-kerbin-mining-corporation/CryoTanks/blob/master/CKAN/CryoTanks.netkan>

**Comment by HebaruSan** [comment]
I was trying to find where this is actually mentioned, and finally found it bundled in the ZIP starting in 1.6.0:

![image](https://github.com/KSP-CKAN/NetKAN/assets/1559108/54f2d104-9c4e-49ff-bcea-847abefc29f3)
