### ISSUE TITLE
WBI play modes and classic stock resources needs another look

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/NetKAN#9899]
Relevant background: https://github.com/KSP-CKAN/NetKAN/pull/8275

Currently ClassicStockResources depends on WildBlue-PlayMode-ClassicStock, which seems backwards: https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/ClassicStockResources.netkan

Recently we took steps to make sure that CommunityResourcePack conflicts with wildblue play modes other than WildBlue-PlayMode-CRP and WildBlue-PlayMode-USI (note the latter is maintained by TheDog and not Angel-125.  And it may be abandoned).  https://github.com/KSP-CKAN/NetKAN/pull/9893.  This came out of some bug reports from people trying to use CommunityResourcePack and other play modes.

So, my proposal:

* Flip the dependency: WildBlue-PlayMode-ClassicStock should depend on ClassicStockResources, not the other way around.
* Make ClassicStockResources conflict with CommunityResourcePack
* MAYBE: make WildBlue-PlayMode-Pristine conflict with ClassicStockResources
* MAYBE: make WildBlue-PlayMode-Simplified depend on ClassicStockResources

I'd want to do at least a little digging to look for other mods that interact with these to make sure we're not screwing anything up.

**Comment by HebaruSan** [comment]
> * Flip the dependency: WildBlue-PlayMode-ClassicStock should depend on ClassicStockResources, not the other way around.

This just seems wrong to me. It's a separate mod that the (non-CKAN) user can choose to install or not. If flipping the dependency was appropriate, then there would be no reason for ClassicStockResources to exist as its own mod outside of the base WildBlueTools. It would just be some additional cfg files in the `Templates/ClassicStock` folder of that mod.

The current relationship, on the other hand, makes sense to me. In order to use the resources that come with ClassicStockResources, you need the definitions of the ClassicStock play mode **and** the tools for managing/switching play modes, both of which are in WildBlueTools.

WildBlueTools' installation instructions in `Readme.txt` [in the ZIP](https://github.com/Angel-125/WildBlueTools/releases/download/v1.89.2/WildBlueTools.zip) say nothing about also needing to install ClassicStockResources:

```
Wild Blue Tools

A KSP mod that provides common functionality for mods by Wild Blue Industries.

---INSTALLATION---

Copy the contents of the mod's GameData directory into your GameData folder.
```

Everything about the actual contents and structure of these mods aligns with the current metadata and away from these changes. Is there some contrary objective aspect of it that I'm missing here?

**Comment by HebaruSan** [comment]
Found a confounding factor: DSEV bundles ClassicStockResources:

![image](https://github.com/KSP-CKAN/NetKAN/assets/1559108/bc9f1d10-0aa1-4ac8-9d6a-6af50f292f36)

So the intention there would seem to be to make the ClassicStockResources configs always available in case the user chooses the ClassicStock play mode. In effect, bundling is an implicit way of defining a dependency without mentioning it in installation instructions.

The same pattern holds for:

- [x] DSEV
- [x] Pathfinder
- [x] MOLE
- [x] Heisenberg
- [x] Buffalo

That makes me a lot more comfortable with the idea of flipping the dependency.

**Comment by HebaruSan** [comment]
Taking a look at the rest of the metadata, the RationalResources family are the only others depending on `ClassicStockResources`. The other relationships mentioning that identifier are `supports`. And I don't think any mods outside the WildBlue family interact with the play mode structure. So the risks for other mods should be minimal.

Alright, I'm turning my key. 🔑
I'll start a pair of PRs in NetKAN and CKAN-meta with these changes to properly reflect the bundling structure.

**Comment by HebaruSan** [comment]
> * MAYBE: make WildBlue-PlayMode-Pristine conflict with ClassicStockResources
> * MAYBE: make WildBlue-PlayMode-Simplified depend on ClassicStockResources

These might be best handled by leaving the current CSR→CSP dependency in place while adding CSP→CSR. Then if you install ClassicStockResources, you're forced into the ClassicStock play mode, and we don't have to mess with the other play modes.

**Comment by JonnyOThan** [comment]
> This might be best handled by leaving the current CSR→CSP dependency in place while adding CSP→CSR (a circular dependency to effectively turn them into one logical mod). Then if you install ClassicStockResources, you're forced into the ClassicStock play mode, and we don't have to mess with the other play modes.

I only did a cursory skim but I'm pretty sure that Simplified play mode uses resources from ClassicStockResources so I don't think this works.

**Comment by HebaruSan** [comment]
> Should be tested!

Done. I installed DSEV and Pathfinder manually, then switched to Simplified (which apparently is known in-game as "Lite Blue"):

![image](https://github.com/KSP-CKAN/NetKAN/assets/1559108/bfc75873-e5f3-4072-b2f9-6b99afb2ca5a)

And now all of ClassicStockResources' .cfg files are renamed to .txt:

![image](https://github.com/KSP-CKAN/NetKAN/assets/1559108/85ba017e-2dc8-4798-84ff-aa22ff88d6fd)

**Comment by JonnyOThan** [comment]
> And now all of ClassicStockResources' .cfg files are renamed to .txt:

Did you check every file that is included in the ClassicStockResources ckan module? 

![image](https://github.com/KSP-CKAN/NetKAN/assets/9804078/37cd9370-013d-4fcb-a342-8707891794c7)

I'm worried that some of those are required by the Simplified play mode.

**Comment by JonnyOThan** [comment]
I don't think we necessarily need two separate modules, right?  Simplified play mode is clearly expected to be usable with ClassicStockResources installed.  What's the motivation for making ClassicStockResources depend on the play mode?

**Comment by HebaruSan** [comment]
But yes, it does need to be two separate modules, to accurately model the two states of ".cfg files are left alone" and "all but one .cfg file are renamed to .txt".

**Comment by JonnyOThan** [comment]
Yeah I made that comment based on the fact that mods which support the simplified play mode sometimes bundle classic stock resources, and they’re in .cfg form there.

If you install ClassicStockResources outside of ckan, the resources are in .cfg files. Isn’t it possible that some other mod uses those resources directly and doesn’t have anything to do with play modes?

rather than make ClassicStockResources depend on the play mode, why not make the other play modes conflict with ClassicStockResources?  That seems correct, meaning that if you have CSR then you must use the corresponding play mode.

**Comment by HebaruSan** [comment]
Rather than trying to answer a bunch of hypotheticals, are there actual problems with the current metadata as it stands?

**Comment by JonnyOThan** [comment]
> Rather than trying to answer a bunch of hypotheticals, are there actual problems with the current metadata as it stands?

Don’t many of the RationalResources family mods depend on CRP or CSR, and if you select CSR you shouldn’t necessarily be forced to install the WBI play mode?

**Comment by HebaruSan** [comment]
Does that cause a problem?

**Comment by JonnyOThan** [comment]
Not that I know of, but it spiderwebs into other dependencies like Wild Blue Tools and Kerbal Actuators.  What does making Classic Stock Resources depending on Classic Stock PlayMode buy us?

**Comment by HebaruSan** [comment]
The current dependencies of ClassicStockResources are:

```yaml
depends:
  - name: ModuleManager
  - name: ClassicStockResources-PlayMode
```

**Comment by JonnyOThan** [comment]
agh, what??  
![image](https://github.com/KSP-CKAN/NetKAN/assets/9804078/cb6166d3-20a5-4c37-94fb-93ce0baa3a1e)

this is madness.  Why is a CRP mode there?

**Comment by HebaruSan** [comment]
Because you can install `ClassicStockResources/Templates/Common/Intakelqd.cfg` and have it active while CRP is installed.

**Comment by JonnyOThan** [comment]
> Because you can install ClassicStockResources/Templates/Common/Intakelqd.cfg and have it active while CRP is installed.

You *can* but it's a no-op because everything in that file gets removed if CRP is installed.

**Comment by HebaruSan** [comment]
Sure. Which means that mods that bundle it can be used in other play modes.

**Comment by ProgrammerFailure** [comment]
Hello, I am running into a metadata problem that seems related to this.
I have WBI USI play mode installed:
https://github.com/TheDogKSP/WBIPlaymodeUSI

I am trying to install Pathfinder, which requires classic stock resources, which requires the classic stock playmode. WBI USI playmode isnt an option as a classic stock playmode, so I need to select one of the other classic stock playmode options, all of which are incompatible with WBI USI playmode. This means I am unable to use WBI USI playmode with pathfinder, which was it's intended use, rendering said playmode useless. I think this can be corrected by adding WBI USI as a playmode for Classic stock, or by removing the incompatibility between classic stock resources classic stock playmode.

**Comment by JonnyOThan** [comment]
@HebaruSan is the solution here to make the USI play mode provide ClassicStockResources-PlayMode?
