### ISSUE TITLE
[Mod]: AtmosphericBeats KSRSS config for EVE Volumetrics

### ISSUE THREAD

**Issue by atmosphericbeats** [KSP-CKAN/NetKAN#9902]
### Mod Name

AtmosphericBeats KSRSS clouds config for EVE Volumetrics

### Author(s)

AtmosphericBeats

### License

GPL-3.0

### Homepage link

https://github.com/atmosphericbeats/atmosphericbeats_eveconfig_ksrss

### Download link

Github, SpaceDock

**Comment by JonnyOThan** [comment]
done here: https://github.com/KSP-CKAN/NetKAN/pull/9901

FYI @atmosphericbeats all you need to do is click the "add to ckan" checkbox in spacedock (which sets up the PR and everything automatically).  The "request a mod" issue form is for people not using spacedock, or for 3rd parties to ask us to work with a mod author to get something added.

Perhaps we should amend the template...
