### ISSUE TITLE
Pathfinder installs WBIPlayMode.cfg to GameData root

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/NetKAN#9905]
https://github.com/KSP-CKAN/NetKAN/blob/83fe0b95edb2f6280935ce144ddec9aa14672154/NetKAN/Pathfinder.netkan#L39

Is this intentional?  Shouldn't this be controlled by the play mode selection?  If I select a play mode in-game and then try to install pathfinder (using simplified play mode, the same one I had selected), CKAN throws up this warning: 
![image](https://github.com/KSP-CKAN/NetKAN/assets/9804078/be1fb0f3-be80-4c01-b5eb-6214bfc2bee5)

For reference, other WBI mods like DSEV and Heisenberg *do not* install the WBIPlayMode.cfg file.

**Comment by HebaruSan** [comment]
Nope, looks like that was an error from #7982 that didn't get removed in #8275's revamp. I'll add that to the current PR(s).
