### ISSUE TITLE
CryoTanks-Core can cause issues because of mods that use NEEDS[CryoTanks]

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/NetKAN#9911]
just untangled this nightmare...

![image](https://github.com/KSP-CKAN/NetKAN/assets/9804078/f131247a-d49a-40b1-929b-586042051887)

> Endurance uses a tank type named OX
It provides this tank type on its own, but conditioned on :NEEDS[!CryoTanks] - seems reasonable, because CryoTanks also provides this tank type.
You have CryoTanks CORE installed but not the full CryoTanks mod.  So you have the folder named CryoTanks which satisifies the NEEDS clause (or rather, causes Endurance to not create the tank type).
Therefore the tank type doesn't exist and b9ps throws a fatal error

https://github.com/JPLRepo/Endurance/blob/14768ade5644ff372e3ad83f134dfba040d1d026/Distribution/GameData/Endurance/Patches/B9PS.cfg#L205

https://github.com/JPLRepo/Endurance/blob/14768ade5644ff372e3ad83f134dfba040d1d026/Distribution/GameData/Endurance/Patches/B9PS.cfg#L298

I'm not really sure how to resolve this in a general way.  Ideally installing CryoTanks Core (the simpleboiloff dll) wouldn't satisfy the needs clause, because I'm sure that a lot of mods use NEEDS[CryoTanks] assuming that all of the tank types are installed.  That implies it would need to be installed in a different folder.  In the current regime, other mods don't have a great way to check for whether the tank types are installed, unless they use NEEDS for a specific cfg file which seems nonobvious and fragile.

A possible solution would be to remove the separation between CryoTanks-Core and CryoTanks - but the .netkan files are on @ChrisAdderley 's repo: https://github.com/post-kerbin-mining-corporation/CryoTanks/tree/master/CKAN

Indeed, there are NO other mods that depend on solely CryoTanks-Core on CKAN, so the separation isn't buying us anything.

Another possible solution for Endurance specifically would be to use its own EN_OX tank type rather than depending on CryoTanks to provide it.  But I'm pretty sure we're just going to hit this in other mods too.

@JPLRepo  FYI.

**Comment by linuxgurugamer** [comment]
Not an expert here, but isn't there a way in MM to need a specific part?  If so, can you use that?

**Comment by JonnyOThan** [comment]
> Not an expert here, but isn't there a way in MM to need a specific part? If so, can you use that?

That's this: 

> they use NEEDS for a specific cfg file which seems nonobvious and fragile.

**Comment by HebaruSan** [comment]
> Indeed, there are NO other mods that depend on solely CryoTanks-Core on CKAN, so the separation isn't buying us anything.

Found one, sort of:

https://github.com/KSP-CKAN/NetKAN/blob/88d4df2b318a6054ac81819f22c5e232b8356f89/NetKAN/SkyhawkScienceSystem.netkan#L20-L21

That was based on a third party's use of the metadata-webtool in #9377, so presumably changing it to the full `CryoTanks` mod would be fine or even preferred.

**Comment by JonnyOThan** [comment]
> Found one, sort of:

Ooh good catch.  

According to this list, it doesn't make a distinction: https://github.com/CessnaSkyhawk/SkyhawkScienceSystem/wiki/Mod-Support

And the split between core/full seems to only exist in CKAN, and Skyhawk was not originally intended for CKAN.  Looking through Skyhawk's configs, it *looks* like it could work with just cryotanks-core, or the full mod.

**Comment by HebaruSan** [comment]
> You have CryoTanks CORE installed but not the full CryoTanks mod.

@JonnyOThan, how did a user end up in the state of having CryoTanks-Core without CryoTanks, since (almost) no mods depend on CryoTanks-Core?

**Comment by HebaruSan** [comment]
> That's a good question. I don't recall.

Did it actually happen? Or was the cause of the error in the OP something else?
