### ISSUE TITLE
[Bug]: SpaceY Extended/Heavy Lifters appears to install incorrectly

### ISSUE THREAD

**Issue by heyimastopsign** [KSP-CKAN/NetKAN#9913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### CKAN Version

1.34.2

### Games

KSP 1

### Game Version

1.12.5

### Describe the bug

<img width="586" alt="Screenshot 2024-01-30 at 3 10 56 pm" src="https://github.com/KSP-CKAN/CKAN/assets/139853723/17801264-93d5-4e21-885a-17346c749935">
A fair amount of SpaceY parts use the magenta placeholder texture instead of their proper ones. 
<img width="144" alt="Screenshot 2024-01-30 at 3 20 27 pm" src="https://github.com/KSP-CKAN/CKAN/assets/139853723/710d1382-e4a6-4ce7-bb60-4061b31e884a">

### Steps to reproduce

* Install SpaceY Extended/Heavy Lifters
* Open KSP, and view parts in parts list
![image](https://github.com/KSP-CKAN/CKAN/assets/139853723/8ae78124-81e7-40cf-988c-a88358b8e4c4)

**Comment by JonnyOThan** [comment]
I'm pretty sure SpaceYExpanded references textures from SpaceY, and SpaceY has changed its directory structure at some point and SpaceYExpanded has not yet been updated.  So this isn't really a metadata bug, unless we wanted to set a max version on the relationship from SpaceYExpanded.

**Comment by NecroBones** [comment]
> I'm pretty sure SpaceYExpanded references textures from SpaceY, and SpaceY has changed its directory structure at some point and SpaceYExpanded has not yet been updated. So this isn't really a metadata bug, unless we wanted to set a max version on the relationship from SpaceYExpanded.

I can't speak to how it's been modified, but yes that's correct-- SpaceYExpanded was designed as an extension and requires SpaceY to be installed for the textures.

**Comment by Lisias** [comment]
I think the following issue is related to this problem:

https://github.com/KSP-CKAN/NetKAN/pull/9533

**Comment by linuxgurugamer** [comment]
@zer0Kerbal totally reorganized this mod for his own reasons.  Until he fixes SpaceYExpanded, there isn't anything that CKAN can do to fix this

**Comment by Lisias** [comment]
> @zer0Kerbal totally reorganized this mod for his own reasons. Until he fixes SpaceYExpanded, there isn't anything that CKAN can do to fix this

AFAIK, SpaceYExpanded is fixed - but CKAN choose not to index it. See #9533

**Comment by Lisias** [comment]
On a (more or less, it's my dev install) KSP 1.12.5 installment, I installed the most recent versions of:

* https://spacedock.info/mod/88/SpaceY%20Heavy%20Lifters%20(SYL)%20by%20NecroBones
* https://spacedock.info/mod/89/SpaceY%20Expanded%20(SYX)%20by%20NecroBones

fired the thing up, and then tried to reproduce the problem mentioned by @heyimastopsign :

![screenshot61](https://github.com/KSP-CKAN/NetKAN/assets/64334/eed953af-679a-40d6-8be3-f6a9f12dae26)

It's working for me - but nothing on this rig was installed using CKAN.

**Comment by JonnyOThan** [comment]
> > @zer0Kerbal totally reorganized this mod for his own reasons. Until he fixes SpaceYExpanded, there isn't anything that CKAN can do to fix this
> 
> AFAIK, SpaceYExpanded is fixed - but CKAN choose not to index it. See #9533

Actually it IS indexed from spacedock, however it was frozen 4 years ago because of inactivity.  PR #9353 is actually not the correct change, but we can get this unfrozen so that the more recent and future versions will be available on ckan.

**Comment by JonnyOThan** [comment]
Working on this here: https://github.com/KSP-CKAN/NetKAN/pull/9914

**Comment by JonnyOThan** [comment]
And done!  Any further updates can be submitted as PRs to this file: https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/SpaceY-Expanded.netkan

**Comment by linuxgurugamer** [comment]
My understanding was that @zer0Kerbal was working on updating both mods
