### ISSUE TITLE
Near Future Solar Core split should probably be removed

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/NetKAN#9922]
Similar to #9911 , but I haven't seen any examples of a mod doing `NEEDS[NearFutureSolar]` yet. However (due to CKAN not recognizing when mods are manually removed), this split does contribute to user frustration because it's a common culprit of B9PS errors: https://www.reddit.com/r/KerbalSpaceProgram/comments/1akzguu/endless_list_of_issues_reported_by_b9_part_switch/

I think that kind of problem would be less likely to occur if the split didn't exist - the user might notice that CKAN says they have Near Future Solar but it's not in their GameData, so they'd use CKAN to reinstall it and everything would be fine.

Also sorta related to https://github.com/KSP-CKAN/CKAN/issues/4017

**Comment by linuxgurugamer** [comment]
what split?

**Comment by JonnyOThan** [comment]
> what split?

NearFutureSolar is actually two packages in CKAN:

https://github.com/KSP-CKAN/NetKAN/blob/2992710bec6c0d1b6785ca939a4c0b886438cccb/NetKAN/NearFutureSolar.netkan
https://github.com/KSP-CKAN/NetKAN/blob/2992710bec6c0d1b6785ca939a4c0b886438cccb/NetKAN/NearFutureSolar-Core.netkan

**Comment by linuxgurugamer** [comment]
Interesting, they both point to the same  download.  The core only installs the dll.

**Comment by JonnyOThan** [comment]
> Interesting, they both point to the same download. The core only installs the dll.

Yes, it's the same situation as CryoTanks.  Nertea apparently decided to split the plugin from the content, with the forethought that perhaps the DLL could be used by other mods without the content being installed.  That's perfectly reasonable.  But no other mods are actually doing this, and the splits are causing issues.

I think there's a clue here: https://www.reddit.com/r/KerbalSpaceProgram/comments/1akzguu/comment/kpcicut/?utm_source=share&utm_medium=web2x&context=3

> Yeah CKAN's ability to detect manually installed mods is pretty limited - it only works if the mod has a DLL with the same name as the CKAN identifier (e.g. scatterer works, EVE doesn't). I highly recommend using CKAN to install everything that's available there, and then manually installing things that aren't. That definitely gets a lot trickier with KSRSS and volumetric clouds, etc.
> OMG I think you just cracked it. The DLL for NearFutureSolarCore is *named* NearFutureSolar. So CKAN incorrectly auto-detects this as NearFutureSolar being installed.

**Comment by JonnyOThan** [comment]
> For better or worse, CKAN offers to "update" manually-installed mods to bring it under CKAN's control. I bet this is what happened:

1. You manually installed NearFutureSolar
2. CKAN auto-detects it as installed (so far so good)
3. You did the "update all" action in CKAN, which includes NearFutureSolar
4. Somehow this doesn't install NearFutureSolarCore (the dll)

Going to verify...
