### ISSUE TITLE
[Bug]: Possibly corrupted mod zip was uploaded

### ISSUE THREAD

**Issue by dhasial** [KSP-CKAN/NetKAN#9926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Arch Linux, latest

### CKAN Version

1.32.0-1 (`ckan-bin` in the AUR)

### Games

KSP 1

### Game Version

1.12.5

### Describe the bug

About to install:

 * Module Manager 4.2.3 (cached)
 * Kethane Mining 0.11.0 (taniwha.org, 13.9 MiB)
Downloading "http://taniwha.org/~bill/Kethane-0.11.0.zip"
Finished downloading Kethane 0.11.0, validating and storing to cache...
Module "Module Manager" successfully installed
Trying to install Kethane 0.11.0, but it's not downloaded or download is corrupted
Error during installation!

### Steps to reproduce

Attempt to install kethane, "Trying to install Kethane 0.11.0, but it's not downloaded or download is corrupted"

**Comment by linuxgurugamer** [comment]
Just an FYI, it downloads without any problem from here:

**Comment by HebaruSan** [comment]
@linuxgurugamer, try extracting all the files. The problem is not that the file won't download, it's that it is corrupt.

**Comment by linuxgurugamer** [comment]
Ok, I see.

I just checked,  I do have a good copy locally, if needed

**Comment by HebaruSan** [comment]
For example, trying to extract all the files from the link provided above produces this currently:

![image](https://github.com/KSP-CKAN/NetKAN/assets/1559108/57bbd713-05d8-4ee0-a9f4-8ce182bdc49e)

**Comment by dhasial** [comment]
@linuxgurugamer 
Could you send it to me? I could certainly use it.

(I was going to pm you but I don't believe github has such functionality)
