### ISSUE TITLE
[Mod]: JFA

### ISSUE THREAD

**Issue by D4RKN3R** [KSP-CKAN/NetKAN#9944]
### Mod Name

JFA

### Author(s)

D4RKN3R

### License

MIT

### Homepage link

https://forum.kerbalspaceprogram.com/topic/223852-jfa-jeb-far-away-1125

### Download link

https://spacedock.info/mod/3565/JFA

**Comment by HebaruSan** [comment]
Hi @D4RKN3R, thanks for the submission. This is already in progress...

**Comment by HebaruSan** [comment]
Duplicate of #9937
