### ISSUE TITLE
Rocket Motor Menagerie version compatibility

### ISSUE THREAD

**Issue by Capkirk123** [KSP-CKAN/NetKAN#9952]
Rocket Motor Menagerie, being a straightforward part mod, should be compatible with all versions of 1.12 (and probably older versions as well, but that's a can of worms I don't want to get into). Since it's metadata is pulled from Spacedock, which does not allow for compatibility to be specified for multiple versions, it is currently only marked as compatible with KSP version 1.12.5.

I have gotten permission from @EStreetRockets to have RMM marked as compatible with all versions of KSP 1.12.x

**Comment by HebaruSan** [comment]
Confirmed author intent on forum thread:

- <https://forum.kerbalspaceprogram.com/topic/202266-112x-rocket-motor-menagerie-v110-stockalike-engine-pack/>

![image](https://github.com/KSP-CKAN/NetKAN/assets/1559108/ef691ead-55cb-4a40-83cd-4aecee7163fa)
