### ISSUE TITLE
[Bug]: Failing in Installing FreeIva 0.2.18.4

### ISSUE THREAD

**Issue by DigDin013** [KSP-CKAN/NetKAN#9966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows

### CKAN Version

v1.34.4

### Games

KSP 1

### Game Version

1.12.0.3140

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

no other changes, never

### Describe the bug

 Im just trying to installing FreeIva 0.2.18.4 and says that cannot find central directory and then the download fails, all other mods i intalled, have with no problem but only FreeIva is the only not working.

### Steps to reproduce

I intall like a 80 mods before this error acours and its has horking perfectly, but some day i update the mod and if fails, so i uninstall FreeIva and install again clicking on the square to add the mod, then the square is checked, i click on the VERSIONS and select the greenest, the  version: 0.2.18.4  Ksp 1.12.0-1.12.99  Date: 03/03/2024 16:10, and i click in lint of alterations and then shows only the FreeIva mod to install, then i click in apply, show some remomendantions(i dont add none of that) click in continue, and the download failed, and shows this:

Installing FreeIva 0.2.18.4...
Cannot find central directory
Error during installation!

I dont know why this happends, so im here, please help me, i want to my kerbals walk in my giant base.
Im from Brazil so the relevant log output is in Portuguese if need to translate.

### Relevant log output

About to install:

 * FreeIva 0.2.18.4 (Em cache)
Installing FreeIva 0.2.18.4...
Cannot find central directory
Error during installation!
Se a mensagem acima indicar um erro de download, por favor tente novamente. Caso contrário, por favor abra um problema para que possamos investigar.
Se você suspeita de um problema com nos metadados: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
Se você suspeita de um problema com no CKAN: https://github.com/KSP-CKAN/CKAN/issues/new/choose

**Comment by HebaruSan** [comment]
Hi, this means the ZIP file on your disk was corrupted after CKAN downloaded and validated it. Use the "Purge from cache" right click menu option to delete it and force it to be re-downloaded:

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/c7872417-c389-4f4d-ad90-80084ba039bb)

You should also consider backing up your important files, scanning for other corrupted files, and replacing your storage device.

**Comment by DigDin013** [comment]
THANK YOU SO MUCH, IT WORKED

**Comment by DigDin013** [comment]
allright
