### ISSUE TITLE
[Bug]: Kerbal crashing when i open a ship

### ISSUE THREAD

**Issue by DigDin013** [KSP-CKAN/NetKAN#9968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows

### CKAN Version

v1.34.4

### Games

KSP 1

### Game Version

1.12.0.3140

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

no

### Describe the bug

At first everything was normal, then I need to update Free Iva, so I updated it by clicking with the right button and pressing Purge from cache, I did this because a guy said the file was corrupt and so I updated it by removing the zip or the error it had, but then I went to open the game and all ok, so i open a base i have and the game just crashed, and this was my view:

![image](https://github.com/KSP-CKAN/NetKAN/assets/164579314/ad775e79-c9b6-47b6-805a-1ca216dd2af7)

I dont know what causes thisbut i dont have this problem 1 day ago, I have many mods in my game like 80 and not a single couse me problems, I tried to uninstall the FreeIva but it gave the same error with the same image everytime i open a ship, being when I create in space center or open a ship already existing, 
What do i do?
Please i dont know what to do, if you have a question, ask me, because I won't be able to get rid of this problem alone

### Steps to reproduce

open the game and it seems normal, you can set contrats and everything but everytime you enter a ship or create one, the game just crashes, and before i crate put a ship in the world, the save shows that  ModuleIva is missing!  in red, like a part of the ship is not buyed, but you can launch normal, bur craches the moment that show the ship (and the vision is like below the surface)

### Relevant log output

just crash the game

**Comment by DigDin013** [comment]
if needed here is the photos of all my mods instaled:

![image](https://github.com/KSP-CKAN/NetKAN/assets/164579314/3c1be9af-2131-4b16-9250-4178d0cab581)
![image](https://github.com/KSP-CKAN/NetKAN/assets/164579314/449adb99-7e9a-4de5-b72c-7f3fd008d842)
![image](https://github.com/KSP-CKAN/NetKAN/assets/164579314/105e61da-c10d-46dc-883e-b52ce9f1c2d1)
![image](https://github.com/KSP-CKAN/NetKAN/assets/164579314/c014451f-455e-4cce-b710-a0b86fe536f5)
![image](https://github.com/KSP-CKAN/NetKAN/assets/164579314/e223aced-4f8b-48ca-8c56-142c19f9ca55)

**Comment by HebaruSan** [comment]
Hi @DigDin013, welcome back. This does not appear to be a CKAN-related problem. Try the forum for support with in-game issues:

- <https://forum.kerbalspaceprogram.com/forum/70-ksp1-technical-support-pc-modded-installs/>

**Comment by HebaruSan** [comment]
Since the problem you reported in #9966 strongly implied that your storage device is failing, it's likely that that is a factor in this issue as well. I would once again recommend backing up your important data, running whatever the modern equivalent of scandisk is, and replacing your hard drive. Otherwise it's possible that your computer may simply stop working completely without warning, with the loss of any data it contained.
