### ISSUE TITLE
[Bug]: Mini Airbrakes by FishInferno Homepage Link is Broken

### ISSUE THREAD

**Issue by jcklemme** [KSP-CKAN/NetKAN#9974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

1.12.5

### Describe the bug

The home page link is broken, goes to a missing page on the forums.

### Steps to reproduce

Click on the link for Home Page for the Mod "Mini Airbrakes" by FishInferno

**Comment by HebaruSan** [comment]
Looks like it's this:

- <https://forum.kerbalspaceprogram.com/topic/108121-102-mini-airbrakes-now-for-mm/>

That mod's metadata was sourced from KerbalStuff, so it hasn't been possible to update it automatically for about 8 years, during which there were multiple forum updates, some of which changed the URL format.
