### ISSUE TITLE
[Mod]: Kcalbeloh System

### ISSUE THREAD

**Issue by jcyuan06** [KSP-CKAN/NetKAN#9975]
### Mod Name

Kcalbeloh System

### Author(s)

Jason Kerman

### License

CC-BY-NC-ND

### Homepage link

https://github.com/jcyuan06/Kcalbeloh-System

### Download link

https://github.com/jcyuan06/Kcalbeloh-System/releases/

**Comment by jcyuan06** [comment]
Hi there! In a recent update, I changed the way of its installation. You can find the installation guide on the release page. The mod files are now divided into config packs and texture packs. One should choose between 4k and 8k for texture packs.
In future updates, I may only upload the config pack, but CKAN needs to install the newest texture pack as well.
Apart from the dependencies listed on the release page, the following mods should also be listed as dependencies (the dependencies list is the same as before):
- [Kopernicus Expansion](https://forum.kerbalspaceprogram.com/topic/195844-110-112-kopernicus-expansion-continued-er/)
- [Mitchell-Netravali Filtered Heightmap](https://forum.kerbalspaceprogram.com/topic/207768-112-niakos-kopernicus-utilities-smoother-heightmaps/)

Feel free to let me know if you have any questions.
Thank you!

**Comment by HebaruSan** [comment]
Hi @jcyuan06, thanks for letting us know about this. The metadata should now be up to date for the latest release (you might need to click Refresh in CKAN if you don't have auto-updates enabled). Please let us know if there are any problems!

**Comment by jcyuan06** [comment]
Thank you so much! I tested it just now and it's working well. Thank you so much! I will think about the extras stuff and let you know later if it is needed.
