### ISSUE TITLE
[Bug]: Space Dust Unbound suggests data is incorrect 

### ISSUE THREAD

**Issue by ProgrammerFailure** [KSP-CKAN/NetKAN#9992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

1.12.5.3190

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No

### Describe the bug

Space Dust Unbound, by Vexxel, suggests the Blueshift mod by Angel-125. However, in its metadata it suggests BlueShift, not Blueshift, and so CKAN thinks that the suggested mod is not indexed. Pretty sure the S just needs to be changed to a lowercase s. 

### Steps to reproduce

Open CKAN
Search for SpaceDust Unbound
Look at the relationships menu
BlueShift is suggested at the bottom, shows up as not indexed.

**Comment by HebaruSan** [comment]
Hi @ProgrammerFailure, thanks for the report. Would you like to try fixing it yourself? You can click here:

https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/SpaceDustUnbound.netkan

... and then use the pencil icon to make the edit and submit a pull request.

**Comment by ProgrammerFailure** [comment]
Made a pull request above. Sorry if it's incorrect, this is my first time forking somthing/making a pull request.
